### ISSUE TITLE
Insufficient error checking of cached environment

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1015]
When the `GangaLHCb` plugin is started it checks if it has used the given `LHCbDIRAC` version before. If not, it writes a file into `~/.cache/Ganga` with a cache of the environment. If this file is somehow corrupt, it can give rise to very odd errors in calls to `DIRAC`. Solution would be to read file at start-up and perform some standard error checking on it.

**Comment by mesmith75** [comment]
What kind of check would be sufficient? We could run a basic DIRAC command after loading it though that takes a few seconds.

**Comment by egede** [comment]
Have failed to reproduce the problem.
