### ISSUE TITLE
xroot/root protocols not being sent in correct order

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1024]
There is a rather unhelpful error for when a file is unavailable:

```python
ERROR    GangaDiracError: 'RAL-USER'
ERROR    JobManagerError: error during submit
ERROR    JobManagerError: error during submit ... reverting job 672 to the new status
```

It would be nice to have a bit more information than just the name of the troublesome SE.

**Comment by drmarkwslater** [comment]
After much messing around with this, this error is not actually as a result of the file not being available but of a but in the code. `getAcessURL` should be called with `['xroot', 'root']` as the protocol rather than ['root', 'xroot']. It's an easy fix I'll try to get in today.

**Comment by mesmith75** [comment]
Huh - that was copied from LHCbDirac - does it work with it being that way round for other sites? Is it just an issue with RAL?

**Comment by chaen** [comment]
It is an issue with any castor based storage. The reason is that castor understands 'root' as the 'castor' protocol. in LHCbDIRAC, when root or xroot is required, we always add both, and make sure xroot is before root.

**Comment by chaen** [comment]
if protocol is a list:
```
      if 'root' in protocol and 'xroot' not in protocol:
        protocol.insert( protocol.index( 'root' ), 'xroot' )
      elif 'xroot' in protocol and 'root' not in protocol:
        protocol.insert( protocol.index( 'xroot' ) + 1, 'root' )
      elif 'xroot' in protocol and 'root' in protocol:
        indexOfRoot = protocol.index( 'root' )
        indexOfXRoot = protocol.index( 'xroot' )
        if indexOfXRoot > indexOfRoot:
          protocol[indexOfRoot], protocol[indexOfXRoot] = protocol[indexOfXRoot], protocol[indexOfRoot]
```

Now, this is maybe something we could put on our side as well... @phicharp, any reason not to ?

**Comment by drmarkwslater** [comment]
@chaen This code is present in the `executeAccessURL` function, just not in `getAccessURL`. I suppose if there's no issue then moving it makes sense (at least from my naive perspective!) though I don't feel very strongly about it.

@mesmith75 The Ganga issue is that, though the code in https://github.com/ganga-devs/ganga/blob/develop/python/GangaLHCb/Lib/Server/DiracLHCbCommands.py is copied **alomst** exactly, the kick is the addition of:
```
if protocol == '':
        protocol=['root', 'xroot']
    elif 'root' in protocol and 'xroot' not in protocol:
```
All we need to do is swap the default option around and everything should be fine 😄

**Comment by drmarkwslater** [comment]
Put in a simple PR that should fix the problem 😄

**Comment by mesmith75** [comment]
Would it still be worth trying to improve the printed error? I assume Dirac gives rather more information.

**Comment by drmarkwslater** [comment]
Possible - the actual return from Dirac is:
```
>>> dirac.getAccessURL('/lhcb/user/a/amerli/2017_06/168856/168856404/MinBias_inclb.sim', 'RAL-USER', ['root', 'xroot'])
{'OK': True, 'Value': {'Successful': {}, 'Failed': {'RAL-USER': {'/lhcb/user/a/amerli/2017_06/168856/168856404/MinBias_inclb.sim': "Connection timed out ( 110 : Something went wrong while checking for extended attributes. GError('srm-ifce err: Connection timed out, err: [SE][StatusOfGetRequest][ETIMEDOUT] httpg://srm-lhcb.gridpp.rl.ac.uk:8443/srm/managerv2: User timeout over\\n', 110))"}}}}
```
and Ganga just selects the `RAL-USER` dict key and returns that. I suppose a similar error could return on other timeouts...?
