### ISSUE TITLE
LHCb uses dirac-proxy-init rather than lhcb-proxy-init

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#1025]
From what I can see, LHCb users call `dirac-proxy-init` as the LHCb plugin requires the `DiracProxy` credential to run stuff which has `dirac-proxy-init` hardcoded. Just talked to the Grid guys and this is a bad idea as in some cases, this puts RFC proxies in that are no longer supported. They suggest that the best way is to **always** call `lhcb-proxy-init` and the best way to do this that I can see is to create another Credential type (`LHCbProxy`) that calls this. 

What do people think?

P.S. This isn't massively urgent but needs to be fixed in the next couple of weeks!

**Comment by rob-c** [comment]
This would probably be better dinner through making the object configurable to save reproducing the amount of differences between lhcb and other dirac users.
Where are RFC proxies no longer supported? Is this something we should contact the gridpp dirac devs about?

**Comment by drmarkwslater** [comment]
On reflection, I think agree - making `DiracProxy` configurable is probably a better idea as long as things are almost exactly the same with the arguments it takes and the output of it. 

As regards RFC proxies, I'm afraid I can't remember. I did hear about this in a WLCG meeting a couple of months ago but can't remember the details. I suspect that it will come along with the appropriate Dirac release but what I'll do if I can remember is ask people next week when I'm at CERN and see if it's something they should worry about.

**Comment by mesmith75** [comment]
Fixed by #1047
