### ISSUE TITLE
After running a Ganga script the shell window crashes

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#1028]
After speaking to LSST users, theyr'e seeing ganga crash (exit?) terminal windows after running.

The user reports that running: `ganga someScript.py` and that the script completes as expected but then proceeds to crash the terminal window rather than returning to a bash(shell) prompt.

I'm going to try and reproduce this if possible and if I can debug it. This may be an issue for us or may be a (mis)configuration issue.

**Comment by egede** [comment]
@rob-c `ganga` is a Python script, so I can't see how this is possible. When you start `ganga`, you start a new process. What you say is that we on exit manage to kill the parent process. Maybe ask the user to start the session as `bash ganga someScript.py` and then get the exit code from the shell process that is killed.

**Comment by rob-c** [comment]
@egede I agree and have confirmed by email that this is what they're seeing. I've asked them to explore running it as `python /path/to/ganga script.py` to see if this still crashes.
I can conceive of how if we try to write something bad to the stdout and the shell is mis-configured this can cause problems. I'm trying to get them to do some legwork but if this is a Cern-VM I may actually ask to get a copy of the image if they can faithfully reproduce this.

**Comment by egede** [comment]
@rob-c You mean if Ganga would write something like `^D` to stdout. I tried this and can't even get that to work. I tried 

```
printf '\004'
eval printf '\004'
```

which do not result in the terminal to exit. The only thing I could get to work was 

```
`printf 'exit'`
```

but that is again driven from the parent process.

**Comment by rob-c** [comment]
@egede I'm thinking of more something like IPython printing something clever to do with formatting to the stdout and the shell not supporting certain escape codes correctly.
(It's unlikely but it could be responsible).

I'll try and get them to run a few variations of scripts at some point and see if they can isolate where the problem is happening, currently off-site due to HEPSYSMAN. (If this becomes clearly not a ganga issue then I'll close this as cannot reproduce).

**Comment by rob-c** [comment]
Closing as this is _expected but odd_ behaviour from the gridpp guide. I've proposed changes but don't know how long the change may take to go live.
https://github.com/gridpp/user-guides/pull/76
