### ISSUE TITLE
Make how Root is setup for mergers more configurable 

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#1029]
At present, GangaLHCb uses
```
[ROOT]
path = /cvmfs/lhcb.cern.ch/lib/RootConfig/pro/x86_64-slc6-gcc49-opt
```

And then sets ROOTSYS to this, LD_LIBRARY_PATH to this+/lib and then runs this+/bin/hadd. This fails badly if LHCb users are just running ganga straight (i.e. outside of lb-run) as the compiler (and other things) are not added to the LD_LIBRARY_PATH. This could be completely fixed by doing:
```
lb-run ROOT hadd
```
Instead but there is no config option to completely change the `rootprefix` used in the `RootMerger:mergefiles` function. I would propose adding this as a config option and setting the default LHCb setting to the above.

**Comment by rmatev** [comment]
what is the workaround?

**Comment by rmatev** [comment]
For reference, here's the hack that I did
```python
import Ganga.Utility.root
def getrootprefix(rootsys=None):
    return 0, 'lb-run ROOT '
Ganga.Utility.root.getrootprefix = getrootprefix
```
