### ISSUE TITLE
Cannot submit job - Atlas Release not recognised when using git-based release

### ISSUE THREAD

**Issue by will-cern** [ganga-devs/ganga#1037]
Hello,

Following the simple instructions here: https://twiki.cern.ch/twiki/bin/view/AtlasComputing/SoftwareTutorialxAODAnalysisInCMake to set up a git-based analysis release, an attempt to then submit a job to condor using ganga leads to the following error:

```
ERROR    ApplicationConfigurationError: j.application.atlas_release is empty - No ATLAS release version found. Run prepare() or specify a version explictly. 
ERROR    ApplicationConfigurationError: j.application.atlas_release is empty - No ATLAS release version found. Run prepare() or specify a version explictly.  ... reverting job 7 to the new status
```

I will note that the release is not correctly extracted:

```
INFO     Found ATLAS Release 
INFO     Found ATLAS Production Release 21.2.0
INFO     Found ATLAS Project AthAnalysis
INFO     Found ATLAS CMTCONFIG x86_64-slc6-gcc62-opt
```

**Comment by will-cern** [comment]
The problem isn't there if I setup a svn-based release ```asetup AthAnalysisBase,2.6.3``` so the problem is only there when using the git-based releases: ```asetup AthAnalysis,21.2,latest```

**Comment by drmarkwslater** [comment]
Fairly easy to fix - I was only allowing `AthAnalysisBase` to not have `atlas_release` set. Incoming fix to allow `AthAnalysis` as well!

**Comment by will-cern** [comment]
Thanks. Out of interest, why is it 'needed' at all?

**Comment by drmarkwslater** [comment]
Because originally, if `atlas_release` wasn't set that means there was a problem with getting the Athena environment. I think this is still the case in the majority of setups (though I may be wrong here). It may be something I can relax completely now but I'm loath to do it at the moment
