### ISSUE TITLE
Custom platform isn't passed from GaudiExec to DIRAC

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#1054]
I suspect from a quick example job that the correct platform isn't being translated into the jdl for LHCBDIRAC jobs.

I think this is simply because the JDL doesn't have a `###PLATFORM###` substitute string but it is being passed from the `GaudiExecRTHandler`.

**Comment by egede** [comment]
@rob-c I think this is irrelevant. The wrapper we write is setting up the architecture through an `LbLogin` command. Can this just be closed?

**Comment by rob-c** [comment]
@egede I would disagree. We don't know what the LHCbDIRAC pilot does to potentialy prepare the environment before we try to source the correct CMTCONFIG from cvmfs. It's only 2 or 3 lines of well placed code and it means we can rule this out as a potential source of bugs in the future, esp if Marco is thinking of multi-platform payloads.

**Comment by mesmith75** [comment]
Apparently this is still an issue - people can't run the latest Brunel on the grid.

**Comment by egede** [comment]
I thought that the LHCb grid at the moment only allowed a single architecture, `x86_64-slc6-gcc49-opt`, and that anything else would fail.

**Comment by mesmith75** [comment]
This was fixed by a change to LbScripts (from v9r1p10), so I'll close this.
