### ISSUE TITLE
remoteDir for DiracFile doesn't work when submitting a job

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#1055]
There is no mechanism that I can see where a DiracFile in the current code can modify the output JDL structure.

This relates to the _quick fix_ put in for #1040 as there is simply no mechanism behind the scenes in ganga to pass this requirement from a DiracFile object to DIRAC even though DIRAC now supports this.
(I plan to break this out into a small PR which is probably the best way of doing this without embarking on a large amount of work).
This is something a few users are asking for.

It would be nice to share the same functionality as MassStorageFile here to allow for powerful outputfile naming but I suspect that this isn't entirely possible without a bit of work and will likely result in us modifying the payload of DIRAC jobs to juggle files before DIRAC picks them up after execution.

**Comment by mesmith75** [comment]
Fixed by #1072
