### ISSUE TITLE
Need a LocalFile splitter for LHCb

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1056]
Ganga is asking for a grid certificate even when not submitting to the grid or using DiracFile etc.

**Comment by rob-c** [comment]
Do you have jobs which need to be monitored?

**Comment by mesmith75** [comment]
No - this was the first use of ganga to submit things to batch.

**Comment by rob-c** [comment]
I've just started from a clean repo and submitted a test hello world to LSF and don't see this.
What type of job are you submitting?

**Comment by mesmith75** [comment]
This was a BenderBox.

**Comment by rob-c** [comment]
This is potentially a bug in the `GaudiExec` RT handler in that case as I think that is shared and from memory the `BenderBox` app doesn't have anything requiring network code in it.
Are you definitely not submitting something using LFNs?

**Comment by mesmith75** [comment]
Ah sorry - I should have looked more carefully - The SplitByFiles requires a credential. Is there a better splitter for local files?

**Comment by rob-c** [comment]
Erm, probably the `GangaDatasetSplitter` https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/Lib/Splitters/GangaDatasetSplitter.py but I've not used it myself so I'd be interested in knowing if it works. I've been recommending it to LSST for a while now but haven't had the chance to submit some test jobs.

**Comment by mesmith75** [comment]
It doesn't work for GaudiExec:
```
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.6.2/python/Ganga/GPIDev/Lib/Job/Job.py", line 1504, in submit
WARNING      jobsubconfig = self._getJobSubConfig(rjobs)
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.6.2/python/Ganga/GPIDev/Lib/Job/Job.py", line 1230, in _getJobSubConfig
WARNING      jobsubconfig = [rtHandler.prepare(sub_job.application, sub_conf, appmasterconfig, jobmasterconfig) for (sub_job, sub_conf) in zip(subjobs, appsubconfig)]
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.6.2/python/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py", line 202, in prepare
WARNING      input_sand = genDataFiles(job)
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.6.2/python/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py", line 49, in genDataFiles
WARNING      data_str = data.optionsString()
WARNING  AttributeError: 'GangaDataset' object has no attribute 'optionsString'
WARNING  --------------------------------------------------
ERROR    'GangaDataset' object has no attribute 'optionsString' ... reverting job 60 to the new status
INFO     job 60 status changed to "new"
ERROR    JobError: Error: 'GangaDataset' object has no attribute 'optionsString'
```

**Comment by rob-c** [comment]
Hmm. You may have to write your own splitter which returns LHCbDataset's for each subjob or get the DatasetSplitter to make LHCbDatasets vs GangaDatasets when it constructs the subjobs.
(Why it's not doing that is potentially a cause for concern as it should be using the proxy based setter given it's constructing a job object, although I suspect it's not)

**Comment by mesmith75** [comment]
Yes - it returns `j.inputdata = GangaDataset()`
