### ISSUE TITLE
AFS-based EOS clients are deprecated

### ISSUE THREAD

**Issue by MannyMoo** [ganga-devs/ganga#1069]
See [OTG0037759](https://cern.service-now.com/service-portal/view-outage.do?n=OTG0037759).

At least for LHCb, ganga is using 
/afs/cern.ch/project/eos/installation/lhcb/bin/eos.select
The quick fix is to change instances of this in ~/.gangarc to
/afs/cern.ch/project/eos/installation/lhcb.old/bin/eos.select

Longer term, it seems the only option is to require and use a local installation of EOS tools, as per [KB0003846](https://cern.service-now.com/service-portal/article.do?n=KB0003846).

**Comment by mesmith75** [comment]
I am not sure this is really Ganga's responsibility. MassStorageFile is designed to be configurable for any generic storage solution - you just point it to what you want it to use.

**Comment by rob-c** [comment]
@mesmith75 Does this mean that the CERN/cvmfs site configs need to be changed so that the default location is to something sensible?

**Comment by mesmith75** [comment]
@rob-c Yeah perhaps. Really the solution depends on how you are running eos.

If you are on lxplus then `/usr/bin/eos` will suffice. I guess most installations will be the same.

**Comment by rob-c** [comment]
@mesmith75 Would it be good to scan for it in the path and ask the user to 'contact their sysadmin to fix it' if it's not I suppose.

**Comment by mesmith75** [comment]
@rob-c  ok. I'll update the defaults in the config and add a check in the init that the relevant paths exist
