### ISSUE TITLE
GangaRepositoryXML can't parse complex dictionaries and doesn't warn of this

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#1073]
Dictionaries such as in the GenericSplitter don't correctly support GangaObject derrived classes being stored in them when they're flattened into the job description XML.

The result of this is that the user will generate a job which will run and correctly submit but when ganga re-launches it will fail to parse the string representation of a proxied object into a meaningful class.

This throws an XML error and marks the job as incomplete and inaccessible to prevent potential further data loss.

The most complete fix for this is to implement a GangaDictionary class to have a much better handle on the object being parsed into and back from XML.

For the time being I think a fix can be coded up just within VStreamer but this is a strong limitation on the existing workflows for users wanting to make extensive use of simpler class structures.

A work-around may be to inform the user that the dictionary object can't be saved if it contains class objects and to store an empty string. This minor amount of data loss would allow for complex jobs to be constructed and submitted although the exact configuration of the job splitter may be lost.

**Comment by egede** [comment]
@rob-c I do not think that a data loss is acceptable. Instead, it would be better if the code would throw an exception already at the creation stage and thus avoid the submission of the job.

**Comment by rob-c** [comment]
@egede OK In that case I think we need to recursively check all dictionary objects as they're assigned at the proxy layer.
It's a shame that this isn't supported though as it allows for some interesting workflows and moving files around just using the GenericSplitter.

Did we ever have a prototype for a GangaDictionary or was this never started, I'm sure this has come up in conversation before.

**Comment by egede** [comment]
@rob-c We have indeed discussed problems with dictionaries before, but I think that was mainly concerning that our current implementation doesn't allow us to write protect them. No development has ever started in a `GangaDictionary` and given all the problems that we have had with `GangaList` over the years, we should not underestimate the amount of work required.

To implement the check that you describe above I imagine should be fairly straight forward.

**Comment by rob-c** [comment]
@egede After fixing #1103 We may just need to add XML support for a dict type which may already be there. I'll have a look at some point soon but after fixing the proxy to correctly strip itself everywhere this may be a much less technical thing to `fix` to allow for putting Ganga classes within a dict in the XML. (If it turns into too mich work this may drop to a side project).

**Comment by egede** [comment]
Will becoe irrelevant with new persistency.
