### ISSUE TITLE
Problems with SmartMerge from LSST users

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#1083]
I've had some reports that the smart merger tool doesn't naievely do what is expected based on the docs.

Once I narrow down where the differences are I'll either ammend/update the docs or update this bug report if some code needs fixing.

(Looking at the merge tests there is a lot of checking the code doesn't crash but not a lot of checking that the output of the merge is what we expect it to be)

**Comment by egede** [comment]
@rob-c Try to ask them for a minimal failing example.

**Comment by rob-c** [comment]
@egede I'm in the process of this but I'm juggling quite a bit of other work atm and the person working on this too only has time to work on lsst/ganga work for a few days a week so this will probably be something which is debugged on Monday at the earliest.

I thought a heads up is worth mentioning. Although I think they are just doing a smart merge and passing a `*.txt` filename to the merge tool so my naive expectation is that this is a lack of support for regex in the merging scripts which would be a shame. (looking through the tests quickly (I've _not_ re-read the docs) there is room for this being the case).
