### ISSUE TITLE
XML Repo still seems a little fragile

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#109]
Hi,

This is just a task to remind me to look into the XML repo code again in the near future as I keep coming across some situations where a job fails to load despite the backup file being perfectly readable. The expected behaviour is that it then loads the backup and sends a warning.

I don't think these errors occur during 'normal use' as I'm torture testing my repository with other tasks whenever I see this and I've not been able to reproduce it in a sane way yet.

I expect looking through the code should reveal that either an exception for missing file isn't handled somewhere or is mis-handled so it should be relatively trivial to track down by inspection.
/
Rob

**Comment by egede** [comment]
@rob-c Closed by other PRs?

**Comment by rob-c** [comment]
I think this has been closed along the way. However I'll be trying to look for how corruption is handled in a unittest in the near future by intentionally corrupting a repo as running some simple tests.
