### ISSUE TITLE
Migrate tests in GangaCore/Utility/Config/tests.py to the testing framework

### ISSUE THREAD

**Issue by alexanderrichards** [ganga-devs/ganga#1091]
```
Ganga/Utility/Config/tests.py
Ganga/Utility/logging/message_caching_test.py
Ganga/Utility/logging/test.py
```

**Comment by egede** [comment]
https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/Utility/Config/tests.py has a number of tests that should be migrated to the proper testing framework located in https://github.com/ganga-devs/ganga/tree/develop/ganga/GangaCore/test. The `A.ini` and /B.ini` files should probably be moved and/or deleted.

**Comment by dilawari2008** [comment]
How do I run the tests files in GangaCore/test and GangaCore/Config such as tests.py ?

**Comment by egede** [comment]
pip install --upgrade -r requirements.txt

and then for me

~/programming/ganga/bin/pytest Unit/TestProxy.py

For some reason I have to give the full path to pytest for it to work. 
Not quite sure why.

Ulrik.

**Comment by egede** [comment]
#1609 did some of this
