### ISSUE TITLE
ganga 6.6.3 not working on lxplus

### ISSUE THREAD

**Issue by will-cern** [ganga-devs/ganga#1096]
Hi,
I was just testing ganga on lxplus by trying to run ```ganga athena -h``` and the command fails with:

```
given client cert (/afs/cern.ch/user/w/will/$X509_USER_PROXY) doesn't exist
ERROR    given client cert (/afs/cern.ch/user/w/will/$X509_USER_PROXY) doesn't exist
ERROR    problems with loading Plugin /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.6.3/install/6.6.3/python/GangaAtlas
ERROR    Reason: Cannot authenticate.
Details: x509 authentication failed
```

Here's what I did (for ATLAS user) from a fresh shell:

```
setupATLAS
lsetup ganga
ganga athena -h
```

Can you please investigate this, it's preventing us using ganga on lxplus?

**Comment by drmarkwslater** [comment]
This has (hopefully!) been fixed by changes to `/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/gangaGridSetup.sh`

Thanks!
