### ISSUE TITLE
Simple lxbatch job fails with unknown module __future__

### ISSUE THREAD

**Issue by will-cern** [ganga-devs/ganga#1098]
Hi,

Following instructions at: https://twiki.cern.ch/twiki/bin/viewauth/AtlasComputing/SoftwareTutorialxAODAnalysisInCMake

My simple job submits to lxbatch backend but fails with: 

```
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "/afs/cern.ch/user/w/will/gangadir/workspace/will/LocalXML/0/0/input/./__jobscript__", line 2, in <module>
    from __future__ import print_function
ImportError: No module named __future__
```

(Also, the ganga monitoring does not seem to recognise that the job failed, it just leaves the state as 'submitted')

This issue is not encountered on a local institute machine when submitting to condor backend.

**Comment by rob-c** [comment]
At first glance I'd say the environment you're trying to run your job in isn't set up correctly (possibly missing or a wrong PYTHONPATH). Do you have private modifications in your .gangarc or is this broken out of the box for lxbatch jobs for atlas?

**Comment by will-cern** [comment]
It's broken out of the box ... the .gangarc was freshly regenerated before I launched the job.

**Comment by drmarkwslater** [comment]
Hi @will-cern  - looking at this now...

**Comment by drmarkwslater** [comment]
Hi Again! So this is another incidence of some conflict of `PYTHONHOME` with the other environment set up by Ganga. @will-cern Could you try setting the following in your .gangarc?
```
[LSF]
extraopts='-env "all,PYTHONHOME=/usr"'
```
If that works I'll change the default in Atlas.ini for the release tomorrow 😄

**Comment by will-cern** [comment]
Sadly that didn't fix it for me :-(

**Comment by drmarkwslater** [comment]
My bad - make that:
```
[defaults_LSF]
extraopts='-env "all,PYTHONHOME=/usr"'
```

I've just tried with the example you gave and the job was monitored to completion. If it doesn't work again, could you run ganga and send the output of:
```
jobs(...).backend
```
Thanks!

**Comment by will-cern** [comment]
Ok the problem existed between chair and keyboard - I miscopied the line. With that change the job starts to run. BUT ... something worries me here ... the job fails due to a mistake in the python joboptions, but that mistake isn't a problem in local running of the code. Does this mean this kludge/fix is ending up with a different version of python being used on the workers compared to locally? Or why else would a mistake in the python only show up on the workers and not in a local run?

The error was to do with trying to append to a list with bad syntax:

list1 = []
list1 += {"something"};

rather than good syntax:

list1 += ["something"]

I'm guessing in future versions of python the former is bad ... I'm worried that the workers invoked a different version of python?

Thanks
Will

**Comment by drmarkwslater** [comment]
Hi @will-cern 

So after more investigation, this turns out to be nothing to do with Ganga at all :smile: Could you check you see the same behavior when doing the following? Can you create a file with the following in it:
```
#!/usr/bin/env python
import site
import os
print "HELLO"
```
and then do:
```
setupATLAS
asetup AthAnalysis,21.2.0,here
chmod +x test2.py
./test2.py
bsub -q 8nm test2.py
```

For me, it runs fine in the shell but the job then fails with the same `import site` error as above. Note: no mention of Ganga here at all!

**Comment by drmarkwslater** [comment]
Just to confirm, without settings up the release, it works fine. Now what is causing this I really don't know. Maybe a question for the Athena devs?

**Comment by will-cern** [comment]
I'm confused ... your 'extraopts' thing DID fix this, so can't we go with that? 

It might indeed be a separate issue with lxbatch that has caused this, but we have a fix, should we apply it?

**Comment by will-cern** [comment]
With the "none" option you give below, the behaviour of the job is consistent with what I would have expected locally, so I think I prefer that to your previous fix!

Thanks
Will

**Comment by drmarkwslater** [comment]
Rightio - I'll get that into #1084 and it should be in for 6.6.4 :smile:
