### ISSUE TITLE
ganga takes a long time to start up on lxplus

### ISSUE THREAD

**Issue by will-cern** [ganga-devs/ganga#1099]
Hello again,

This is a bit of a vague observation - I don't usually use lxplus very much because it is often much slower for me than local institute machines. But I was doing some testing recently for lxplus, and notived ganga takes about 5 minutes to start up for me on there (compared to about 40 seconds on local institute machines). 

I ran ganga with ```ganga --debug``` and noticed that there's a large pause on the execution of 'gangaGridSetup.sh', about 30-40 seconds. Now, I appreciate that there are plans to get rid of this in the startup chain, but what I noticed was this command gets executed *four times* !!! Is it really necessary that ganga executes this expensive script so often? Can ganga not cache the result of the first call and avoid calling it over and over?

Thanks
Will

**Comment by drmarkwslater** [comment]
@will-cern I also noticed this as I was fixing things in the last couple of days. It should be using a caching mechanism to reduce this problem but that seems to not be happening for some reason. I'm going to have a look at that ASAP to either get this working as it should or put in a fix.

**Comment by will-cern** [comment]
guess this problem still exists in 6.6.4 yes?

**Comment by drmarkwslater** [comment]
I'm afraid so but I'll look at this early next week so hopefully get something out pretty quickly 😄

**Comment by drmarkwslater** [comment]
This should be fixed now after removing the proxy stuff so am closing
