### ISSUE TITLE
Problem with TaskChainInput

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#11]
Hi,
I've got a strange problem with the TaskChainInput.
This is Ganga-6-0-44 here (for the moment I need to stick to the 6.0.x branch).
I cannot convince a "transform" to use a specific subset of files, coming from the previous "transform", as "input files".
Here's the skeleton of my script:
```python
tk = SomeTask() # ... the "task" ...
# ...
trf_first = SomeTransform() # ... the first "transform" ...
trf_first.nbinputfiles = 1 # ... several tens of jobs wil be run ...
trf_first.backend = PBS()
trf_first.application = SomeApplication
# ...
# "SomeApplication" produces two kinds of files, "*_A_*.root" and
# "*_B_*.root", and I want to "save" all of them in "/.../First/"
trf_first.outputfiles = [MassStorageFile(namePattern='*.root',outputfilenameformat='/'.join(['First','{fname}']))]
# ...
tk.appendTransform(trf_first)
# ...
trf_second = SomeTransform() # ... the second "transform" ...
trf_second.nbinputfiles = 0 # ... just one job for all files ...
trf_second.backend = PBS()
# ...
indata = TaskChainInput()
indata.input_trf_id = trf_first.getID() # ... here's the link ...
indata.single_unit = True;
indata.use_copy_output = False;
# only "*_B_*.root" files (from the previous "trf_first" step) should be
# used as input files for the "trf_second" step, ... but ...
# ... the "include_file_mask" seems to be ignored ...
indata.include_file_mask=['*_B_*.root']
# ... and ... the "exclude_file_mask" seems to be ignored, as well ...
indata.exclude_file_mask=['*_A_*.root']
# ... and, as a result, all available "*.root" files are passed as "input" ...
trf_second.addInputData(indata)
# ...
# "save" the output in "/.../Second/"
trf_second.outputfiles = [MassStorageFile(namePattern='*.root',outputfilenameformat='/'.join(['Second','{fname}']))]
# ...
tk.appendTransform(trf_second)
# ...
tk.float = 100
tk.run()
```
Could you, please, help me.
Thanks in advance,
Best regards,
Jacek.

**Comment by JacekHoleczek** [comment]
Hi.
let me also ask another question here.

In the "MassStorageFile" description, I find:

"namePattern" = "pattern of the file name ..."

while in the description of "TaskChainInput", I find:

"include_file_mask" = "List of Regular expressions of which files ..."
"exclude_file_mask" = "List of Regular expressions of which files ..."

Am I really supposed to provide full-featured python "regular expressions" for the "TaskChainInput" and simple shell-like "file patterns" for the "MassStorageFile"?

For example someting like "r'.*_A_.*\.root'" for the "TaskChainInput" versus "'*_A_*.root'" for the "MassStorageFile"?

Thanks in advance,
Best regards,
Jacek.

**Comment by drmarkwslater** [comment]
Hi Jacek,

This is correct - the Transform file masks take regular expression strings whereas the MassStorageFiles take Glob style file patterns. Sorry for this being confusing - I've opened another issue to attempt to make it a bit easier to use. In the meantime though, could you try with the regular expressions and see if that works? 

Thanks,

Mark

**Comment by alexanderrichards** [comment]
linking the other issue #12

**Comment by JacekHoleczek** [comment]
Hi,
thanks for the clarification.
I ran three tests (please correct me if my "regular expressions" are not right):
1. apply only ''' indata.include_file_mask=[ r'oa_.*_B_.*\.root' ] ''',
2. apply only ''' indata.exclude_file_mask=[ r'oa_.*_A_.*\.root' ] ''',
3. apply both above properties simultaneously,
and in all cases "trf_second" gets all ''' 'oa_*_[AB]_*.root' ''' files as input.
Best regards,
Jacek.

**Comment by drmarkwslater** [comment]
hi Jacek,

The copying is actually done by the Task/Transform code which isn't included in the base class (specifically the 'createChainUnit' method in the Transform class). Are you using 'CoreTransform'? If not, then you'll have to send me your code so I can see how this is being done as there seems to be some problems there.

Thanks,

Mark

**Comment by JacekHoleczek** [comment]
HI,
thanks, very much, for your help.
Indeed the Task/Transform code is "experiment specific", so I will need to talk to the original author.
For the moment you can close this issue.
Sorry for misleading.
Best regards,
Jacek.

**Comment by alexanderrichards** [comment]
Not a problem, please re-open the issue if we need to come back to this
