### ISSUE TITLE
How to add an extra attribute to a job?

### ISSUE THREAD

**Issue by willfurnell** [ganga-devs/ganga#1102]
Hi,

I'm currently trying to run a GPU based CREAM job using Ganga. In the JDL file one would normally add GPUNumber = 1, however I can't see how to do this using Ganga with the Job or backend- 

```
Ganga In [2]: j.GPUNumber = 1
ERROR    GangaAttributeError: Can't assign 'GPUNumber' as it does NOT appear in the object schema for class 'Job'
```
```
Ganga In [8]: j.backend.GPUNumber = 1
ERROR    GangaAttributeError: Can't assign 'GPUNumber' as it does NOT appear in the object schema for class 'CREAM'
```
Is there a way I can achieve this?
Thanks,
Will

Edit: I'm using the latest installation in /cvmfs/ganga.cern.ch

**Comment by drmarkwslater** [comment]
Hi Will,

Would:
```
j.backend.requirements.other = ['GPUNumber = 1']
```

work? This will put this request in to the 'requirements' part of the JDL. If not, let me know how the JDL **should** look and I'll do some quick dev work 😄

**Comment by willfurnell** [comment]
Unfortutunately this doesn't work and prevents the job from being submitted.
Here's an example JDL.
```
[
Executable = "script.sh";
inputSandbox = { "script.sh"};
StdOutput = "hello.out";
StdError = "hello.err";
OutputSandbox = {"hello.out","hello.err"};
outputsandboxbasedesturi = "gsiftp://localhost";
GPUNumber=1;
VirtualOrganisation = "cernatschool.org";
]
```
Thanks.
