### ISSUE TITLE
Strange merger behaviour

### ISSUE THREAD

**Issue by kgizdov** [ganga-devs/ganga#1109]
I've noticed a peculiar behaviour in ganga on successful jobs. I get the following warning:
```
WARNING  XMLSummary for job XXX subjobs will not be merged as 'summary.xml' not present in job XXX.0 outputdir
```
The interesting parts are two - I do not use a merger tool & this always happens on subjob 0 only.

**Comment by mesmith75** [comment]
This is to do with the job metadata.

Which application are you using? Which version of Ganga were the jobs submitted/finalised with.

**Comment by kgizdov** [comment]
These are DaVinci jobs sent to DIRAC, through Ganga 6.6.4. I use `DiracFiles` as my storage.

**Comment by mesmith75** [comment]
When you say DaVinci do you mean the old application or GaudiExec with DaVinci?

**Comment by kgizdov** [comment]
I don't think `DaVinci()` method works with latest versions of Ganga, so I mean `GaudiExec()` with DaVinci v42r5p1.

**Comment by mesmith75** [comment]
There is probably a slight mistake in the metadata handling for GaudiExec - I'll take a look. The warning is just when the postprocessor of the master job tries to merge the summary xml files for each of the subjobs to fill in the metadata for the whole job. It can't find the first so it stops. This for sure won't affect the successful completion of the jobs.

By the way, if you do want the metadata just set `j.application.getMetadata = True` and it should work. Also the old style applications still work but are only for using the pre-cmake versions of applications.
