### ISSUE TITLE
Ganga does not work at lxplus.cern.ch at ATLAS setup

### ISSUE THREAD

**Issue by pstaroba** [ganga-devs/ganga#1124]
Dear colleagues,

at lxplus.cern.ch, when I do:

setupATLAS
lsetup ganga
ganga

I get the following crash:

[pstaroba@lxplus030]~% ganga
WARNING  Ganga will soon be depending on Python 2.7. You have Python 2.6 installed. See https://github.com/ganga-devs/ganga/wiki/Python-2.7

*** Welcome to Ganga ***
Version: 6.6.4
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.

INFO     reading config file /afs/cern.ch/user/p/pstaroba/.gangarc
INFO     reading config file /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.6.4/install/6.6.4/python/GangaAtlas/Atlas.ini
Enter GRID pass phrase for this identity:
Contacting lcg-voms2.cern.ch:15001 [/DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch] "atlas"...
Remote VOMS server contacted succesfully.

Created proxy in /tmp/x509up_u10156.

Your proxy is valid until Mon Sep 18 09:25:33 CEST 2017
INFO     GridProxy creation/renewal successful.
given client cert (/afs/cern.ch/user/p/pstaroba/$X509_USER_PROXY) doesn't exist
ERROR    given client cert (/afs/cern.ch/user/p/pstaroba/$X509_USER_PROXY) doesn't exist
ERROR    problems with loading Plugin /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.6.4/install/6.6.4/python/GangaAtlas
ERROR    Reason: Cannot authenticate.
Details: x509 authentication failed
PluginError: Failed to load plugin: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.6.4/install/6.6.4/python/GangaAtlas. Ganga will now shutdown to prevent job corruption.
(consider --debug option for more information)
INFO     Stopping Job processing before shutting down Repositories
INFO     Shutting Down Ganga Repositories
INFO     Registry Shutdown
[pstaroba@lxplus030]~% 

How should I run ganga at lxplus using ATLAS setup? Up to now it worked.

Thank you,
Pavel

**Comment by egede** [comment]
The 6.7.0 release was made yesterday and it included some changes to how proxies are handled in ATLAS. I wonder if this solves your problem.

@drmarkwslater Is 6.7.0 automatically available to ATLAS logins at CERN or is some extra step required?

**Comment by pstaroba** [comment]
How can I use ganga 6.7.0 at lxplus using ATLAS setup? 6.6.4  is the default currently - I just checked it.
                                                                                                                   Thank you,
                                                                                                                   Pavel

**Comment by egede** [comment]
@drmarkwslater has to reply on that I am afraid ...

**Comment by drmarkwslater** [comment]
I'm afraid we need to wait for Asoka to deploy it. I'll prod him and get back to you!

**Comment by mesmith75** [comment]
6.7.1 has just been released. Could you let us know if that fixes the problem?

**Comment by pstaroba** [comment]
Hi, 
how can I access 6.7.1 at lxplus? Few minutes ago, I done at lxplus026.cern.ch (userid pstaroba):
setupATLAS
lsetup ganga

and I got:
[pstaroba@lxplus026]~% lsetup ganga
************************************************************************
Requested:  ganga ... 
 Setting up ganga 6.6.4 ... 
>>>>>>>>>>>>>>>>>>>>>>>>> Information for user <<<<<<<<<<<<<<<<<<<<<<<<<
 ganga:
  generateGangarc      to recreate .gangarc settings file
   Warning : ~/.gangarc is not properly setup for grid middleware and ddm: generateGangarc
  Important note for Ganga 6.7.* and newer 
   The next new versions of Ganga will only officially support local access. 
   If you are submitting to the grid, please use PandaClients now.
************************************************************************
[pstaroba@lxplus026]~% 

- so, ganga 6.6.4 is still present. How can I run 6.7.1 ?

Thank you very much,
Pavel

**Comment by pstaroba** [comment]
Sorry for the strange part of my previous message - I do not, how it happened - I just copied a message from lxplus. Anyhow, it is clear, that ganga 6.64 is still present.

                Thank you,
                Pavel

**Comment by drmarkwslater** [comment]
Hi Pavel,

Asoka is in the process of installing this now - maybe a few hours and it should be there!

Thanks,
Mark

**Comment by pstaroba** [comment]
Hi Mark,

I can run ganga 6.7.1 at lxplus now. When doing

setupATLAS
lsetup ganga
ganga

I get 

[pstaroba@lxplus035]~% ganga
WARNING  Ganga will soon be depending on Python 2.7. You have Python 2.6 installed. See https://github.com/ganga-devs/ganga/wiki/Python-2.7
WARNING  Ganga will soon be depending on Python 2.7. You have Python 2.6 installed. See https://github.com/ganga-devs/ganga/wiki/Python-2.7
WARNING  Ganga will soon be depending on Python 2.7. You have Python 2.6 installed. See https://github.com/ganga-devs/ganga/wiki/Python-2.7

*** Welcome to Ganga ***
Version: 6.7.1
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


INFO     reading config file /afs/cern.ch/user/p/pstaroba/.gangarc
INFO     reading config file /afs/cern.ch/user/p/pstaroba/.gangarc
INFO     reading config file /afs/cern.ch/user/p/pstaroba/.gangarc
INFO     reading config file /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.7.1/install/6.7.1/python/GangaAtlas/Atlas.ini
INFO     reading config file /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.7.1/install/6.7.1/python/GangaAtlas/Atlas.ini
INFO     reading config file /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.7.1/install/6.7.1/python/GangaAtlas/Atlas.ini
ERROR    unknown configuration section: [defaults_GridProxy]
ERROR    unknown configuration section: [defaults_GridProxy]

[09:21:49]
Ganga In [1]: 

so, no it seems to work. 
   What does mean the message
 "ERROR    unknown configuration section: [defaults_GridProxy]"

  Is it signature of something serious?

         Thank you,
         Pavel

**Comment by egede** [comment]
If you recreate your `.gangarc` file (do `ganga -g`), then the `gridProxy` warning should go away.

**Comment by pstaroba** [comment]
Hi, I have just done ganga -g at lxplus. I get questions like:

The config option Configuration RUNTIME_PATH with value GangaAtlas:GangaPanda:: in your old .gangarc is not the default. Do you want to copy it to the new .gangarc file ([y]/n) ?

Should I replay y , or n ?

Thank you,
Pavel

**Comment by egede** [comment]
I would reply `n`. I imagine that you changed something a lo gtime ago that you have subsequently forgotten about.

**Comment by pstaroba** [comment]
Hi, 

I logged off from lxplus, then logged on again, and done:

setupATLAS
lsetup ganga
ganga -g 

and got:

[pstaroba@lxplus035]~% ganga -g
WARNING  Ganga will soon be depending on Python 2.7. You have Python 2.6 installed. See https://github.com/ganga-devs/ganga/wiki/Python-2.7
WARNING  Ganga will soon be depending on Python 2.7. You have Python 2.6 installed. See https://github.com/ganga-devs/ganga/wiki/Python-2.7
WARNING  Ganga will soon be depending on Python 2.7. You have Python 2.6 installed. See https://github.com/ganga-devs/ganga/wiki/Python-2.7

*** Welcome to Ganga ***
Version: 6.7.1
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


INFO     reading config file /afs/cern.ch/user/p/pstaroba/.gangarc
INFO     reading config file /afs/cern.ch/user/p/pstaroba/.gangarc
INFO     reading config file /afs/cern.ch/user/p/pstaroba/.gangarc
INFO     reading config file /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.7.1/install/6.7.1/python/GangaAtlas/Atlas.ini
INFO     reading config file /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.7.1/install/6.7.1/python/GangaAtlas/Atlas.ini
INFO     reading config file /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.7.1/install/6.7.1/python/GangaAtlas/Atlas.ini
ERROR    unknown configuration section: [defaults_GridProxy]
ERROR    unknown configuration section: [defaults_GridProxy]
INFO     re-reading in old config for updating...
INFO     re-reading in old config for updating...
INFO     re-reading in old config for updating...
INFO     reading config file /afs/cern.ch/user/p/pstaroba/.gangarc
INFO     reading config file /afs/cern.ch/user/p/pstaroba/.gangarc
INFO     reading config file /afs/cern.ch/user/p/pstaroba/.gangarc
INFO     reading config file /afs/cern.ch/user/p/pstaroba/.gangarc
INFO     Copied current config file to /afs/cern.ch/user/p/pstaroba/.gangarc.24
INFO     Copied current config file to /afs/cern.ch/user/p/pstaroba/.gangarc.24
INFO     Copied current config file to /afs/cern.ch/user/p/pstaroba/.gangarc.24
INFO     Creating ganga config file /afs/cern.ch/user/p/pstaroba/.gangarc
INFO     Creating ganga config file /afs/cern.ch/user/p/pstaroba/.gangarc
INFO     Creating ganga config file /afs/cern.ch/user/p/pstaroba/.gangarc
INFO     Stopping the monitoring component...
INFO     Stopping the monitoring component...
INFO     Stopping the monitoring component...
INFO     Stopping Job processing before shutting down Repositories
INFO     Stopping Job processing before shutting down Repositories
INFO     Stopping Job processing before shutting down Repositories
INFO     Shutting Down Ganga Repositories
INFO     Shutting Down Ganga Repositories
INFO     Shutting Down Ganga Repositories
INFO     Registry Shutdown
INFO     Registry Shutdown
INFO     Registry Shutdown
[pstaroba@lxplus035]~% 

I have done ganga after then and got:

[pstaroba@lxplus035]~% ganga
WARNING  Ganga will soon be depending on Python 2.7. You have Python 2.6 installed. See https://github.com/ganga-devs/ganga/wiki/Python-2.7
WARNING  Ganga will soon be depending on Python 2.7. You have Python 2.6 installed. See https://github.com/ganga-devs/ganga/wiki/Python-2.7
WARNING  Ganga will soon be depending on Python 2.7. You have Python 2.6 installed. See https://github.com/ganga-devs/ganga/wiki/Python-2.7

*** Welcome to Ganga ***
Version: 6.7.1
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


INFO     reading config file /afs/cern.ch/user/p/pstaroba/.gangarc
INFO     reading config file /afs/cern.ch/user/p/pstaroba/.gangarc
INFO     reading config file /afs/cern.ch/user/p/pstaroba/.gangarc
INFO     reading config file /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.7.1/install/6.7.1/python/GangaAtlas/Atlas.ini
INFO     reading config file /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.7.1/install/6.7.1/python/GangaAtlas/Atlas.ini
INFO     reading config file /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.7.1/install/6.7.1/python/GangaAtlas/Atlas.ini
ERROR    unknown configuration section: [defaults_GridProxy]
ERROR    unknown configuration section: [defaults_GridProxy]

[09:50:04]
Ganga In [1]: 

So, the message "ERROR unknown configuration section: [defaults_GridProxy]"
is still present - even after recreating .gangarc by ganga -g

Thank you,
Pavel

**Comment by egede** [comment]
OK, most likely some lines in the `Atlas.ini` that should have been deleted. Should be harmless. I will leave it for @drmarkwslater to fix.

**Comment by pstaroba** [comment]
Thank you very much. 
                          Pavel

**Comment by pstaroba** [comment]
Thank you very much. 
                          Pavel

**Comment by drmarkwslater** [comment]
Hi Pavel,

Yes - these messages can be ignored and will be removed in future releases. What's a bit stranger is that now if you start Ganga on Python 2.6, you seem to have every message repeated 3 times. That should be filed as a separate bug though and also, should go away if you setup an Athena release beforehand that gives you Python 2.7.

Thanks!

mark
