### ISSUE TITLE
Calculate cpu work needed by user analysis job and provide it to LHCbDIRAC

### ISSUE THREAD

**Issue by roiser** [ganga-devs/ganga#1132]
As a followup on the discussion session 29 Sep '17 on LHCb user analysis I would like to suggest to have a means to calculate the cpu work needed by each user analysis job. I post below the first two comments from the mail thread from Philippe and myself.

**Comment by roiser** [comment]
One point I want to add to the list below of improvements is that we should also look into the possibility to calculate the CPU work needed by a user job such that it’s not killed because it reaches the end of a queue. If we manage this - even only very course - we could increase the user job success rate by a good percentage (currently 75% of user jobs succeed vs ~ 95 % overall success rate).

**Comment by roiser** [comment]
Philippe: 

This is some information that is provided by DIRAC for each job in the “parameters” and it is trivial for ganga to get the average, min and max for a set of jobs. Up to users to add a margin. IIRC this is provided already in some form by ganga, but should be confirmed by experts…

AFAIU most users split by number of files, therefore it would be reasonable to try and get the value for “regular” files, i.e. 5 GB. Doing it job by job is a bit cumbersome and would take a lot of time for extracting the number of events etc… Not sure it is worth it (we don’t do it for productions, but use a max value).

**Comment by egede** [comment]
It it unclear to me how this will work. A user submits a job and we get some information back about CPU time used per event/file. When the user submits a new job, should we then use that information to set the limit? But we have no knowledge about if the new job does the same thing, so I do not see how this is meaningful.

**Comment by roiser** [comment]
I believe one possibility would be if the user submits many jobs of the "same kind" Ganga could submit the first 10 or so and from those calculate a weighted average (e.g. per input file size). the user then can take this number and plug it into the remaining 90% of his jobs (with some margin). Would this be possible?

**Comment by egede** [comment]
You could have a system where jobs with above say 500 subjobs would submit the first 10 subjobs and then submit the rest with an adjusted CPU time (if the first 10 finish without errors). It would give a higher efficiency; from the requirement of success and from the modified CPU time. However, there is a big BUT. The system will only work if the user keeps the Ganga session running and I think it would go down quite badly among users ("you are delaying the submission of my perfect code"). In my mind it doesn't look viable.

**Comment by rmatev** [comment]
This might be better done by Dirac:
- user submits a job with 500 subjobs
- a few run with VERY high priority (randomly selected or based on input data size)
- if sufficiently many succeed, Dirac modifies the CPU requirement of the rest and queues the jobs as usual
- if none succeed, priority goes to -Inf, ...

**Comment by egede** [comment]
@rmatev This will not work as Dirac sees all the subjobs as individuals (due to the lack of bulk submission in LHCb).

**Comment by rmatev** [comment]
Sure, nothing will work without some (significant) development. While ugly, even now jobs can be logically grouped by looking at the name.
