### ISSUE TITLE
Create replica of uploaded GaudiExec files

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1133]
We should request a replica of the uploaded GaudiExec files when we submit a job and maybe get rid of one in the postprocessor.

**Comment by rob-c** [comment]
@mesmith75 This sounds like something which should be managed on a per-file basis. We used to request multiple replicas of most files uploaded to the grid by a job but (if memory serves) this was turned off and replicas reduced to 1 at a request from LHCbDirac due to space concerns.
