### ISSUE TITLE
Problem with submitting jobs at grid

### ISSUE THREAD

**Issue by pstaroba** [ganga-devs/ganga#1139]
Dear colleagues, 

I have the following problem: starting from 30.6.2017, I am not able to submit jobs at grid from lxplus(for the analysis of 2012 8 TeV data I am using Root Core in AnalysisBase 1.5.13 using EventLoop).

   It looks like that the problem was triggered by the installation of new versions of ganga at lxplus. The error messages are very complex.

The submission at grid was working last time with ganga version 6.2.3 , which is not available any more
at /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/ .
   Would it be possible to put ganga 6.2.3 back at this place - until the end of this year? 

                                                                                                          Thank you,
                                                                                                          Pavel

**Comment by mesmith75** [comment]
Hello,
I am not an ATLAS expert but the grid utilities for ATLAS were removed from Ganga 6.7.0 so any version older than that should be fine.

I don't know about the ATLAS releases but from our side we have not removed anything. @drmarkwslater will know more.
