### ISSUE TITLE
submitting without a proxy beforehand trigger infinite loop 

### ISSUE THREAD

**Issue by po10** [ganga-devs/ganga#1141]
Hi,

Dan (see message below) has j.parralel_submit=True and seems to get stuck in Ganga asking for a gridProxy infinitely. If I get time this afternoon I will test myself.

Cheers,
Patrick

Hi,

My grid proxy expired, and Ganga tries to refresh it, but then gets stuck in a cycle of constantly asking to refresh. This has happened a few times to me now, so I wonder if it is a known bug?

Dan

Uploading proxy for lhcb_user...
Uploading proxy for private_pilot...
Proxy generated:
subject      : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=johndan/CN=676483/CN=Daniel Johnson/CN=9973783078/CN=2573188346
issuer       : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=johndan/CN=676483/CN=Daniel Johnson/CN=9973783078
identity     : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=johndan/CN=676483/CN=Daniel Johnson
timeleft     : 23:53:58
DIRAC group  : lhcb_user
rfc          : True
path         : /tmp/x509up_u32781
username     : johndan
properties   : NormalUser
VOMS         : True
VOMS fqan    : ['/lhcb/Role=user']

Proxies uploaded:
 DN                                                                              | Group         | Until (GMT)
 /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=johndan/CN=676483/CN=Daniel Johnson | lhcb_user     | 2018/05/11 07:38
 /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=johndan/CN=676483/CN=Daniel Johnson | private_pilot | 2018/05/11 07:38
INFO     job 3948 status changed to "submitted"
INFO     resubmitting job 3950.1
INFO     job 3950 status changed to "submitting"
INFO     resubmitting job 3950.1 to Dirac backend
INFO     Found credential [DiracProxyInfo at /tmp/x509up_u32781 : TimeLeft = 0:00:00, Valid = False] but it is invalid. Trying to renew...
Generating proxy...
Enter Certificate password:
Added VOMS attribute /lhcb/Role=user
Uploading proxy for lhcb_user...
Uploading proxy for private_pilot...
Proxy generated:
subject      : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=johndan/CN=676483/CN=Daniel Johnson/CN=4137622831/CN=2714968406
issuer       : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=johndan/CN=676483/CN=Daniel Johnson/CN=4137622831
identity     : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=johndan/CN=676483/CN=Daniel Johnson
timeleft     : 23:53:58
DIRAC group  : lhcb_user
rfc          : True
path         : /tmp/x509up_u32781
username     : johndan
properties   : NormalUser
VOMS         : True
VOMS fqan    : ['/lhcb/Role=user']

Proxies uploaded:
 DN                                                                              | Group         | Until (GMT)
 /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=johndan/CN=676483/CN=Daniel Johnson | lhcb_user     | 2018/05/11 07:38
 /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=johndan/CN=676483/CN=Daniel Johnson | private_pilot | 2018/05/11 07:38
INFO     job 3950 status changed to "submitted"
INFO     resubmitting job 3952.5
INFO     job 3952 status changed to "submitting"
INFO     resubmitting job 3952.5 to Dirac backend
INFO     Found credential [DiracProxyInfo at /tmp/x509up_u32781 : TimeLeft = 0:00:00, Valid = False] but it is invalid. Trying to renew...
Generating proxy...
Enter Certificate password:

**Comment by rob-c** [comment]
Someone needs to check if the cached values are locked and cleared when a new proxy is created.
I suspect the simple caching isn't completely lock-safe and is resulting in many requests to create a new credential as they are reading the cached information that says the credential is not valid.

I suspect there is a minor bug in the cache locking from #917 specifically in https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/GPIDev/Adapters/ICredentialInfo.py#L20
I think the cache is stored correctly per object but all of the individual objects have their own idea as to whether the credential is valid.
I would rework this method to remove the self.cache entries relating to credential lifetime and access this information directly from the actual credential itself (maybe with some caches within the credential object to avoid it hammering the disk).

Not sure I have too much time to look into this atm apologies, I'm busy with a few different things for the next few weeks.

**Comment by mesmith75** [comment]
@rob-c  there is indeed a bug. The new credential file gets created but ganga doesn't update so still thinks its expired.

**Comment by rob-c** [comment]
@mesmith75 I suspect it's https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/GPIDev/Adapters/ICredentialInfo.py#L53 from reading the code.
It may be enough to add `or 'mcache'  not in self.cache` to the check here as I think this is a bad check when the credential has just been created.
