### ISSUE TITLE
Ganga not closing automatically after running in batch form

### ISSUE THREAD

**Issue by mrwillia** [ganga-devs/ganga#1143]
I have a simple ganga script which downloads Dirac files from a given job (ganga-getfiles.py - code below). I have been calling this in a bash script which loops over several jobs and performs a few simple operations, like this (code simplified for clarity):

> for j in `seq 200 300` ; do
>     ganga ../common/ganga-getfiles.py $j
>     hadd myoutfile_${j}.root <gangadir>/${j}/*/output/file.root
>     rm <gangadir>/${j}/*/output/file.root
> done 

(where the python script ganga-getfiles.py is just a few ganga commands to grab root files from the grid for this job $j).

I have observed that if the script ganga-getfiles.py fails to download any Dirac files (e.g. if there are no matching files, or the job doesn't exist) then ganga will not automatically exit - it prompts me to answer:

"Job status update or output download still in progress (shutdown not completed after 5 seconds). 6 background thread(s) still running: ['SessionLockRefresher', 'JobRegistryFlusher', 'TaskRegistryFlusher', 'JobRegistryFlusher', 'JobRegistry_Monitor', None]. Do you want to force the exit (y/[n])?" 

which clearly causes problems when trying to perform automatic tasks. Is this expected behaviour? If not, what might be causing it?

Many thanks,
Mark

==== ganga-getfiles.py ====

> from Ganga.GPI import *
> import sys
> import inspect
> import os
> 
> 
> if len(sys.argv) not in (2,3):
>     sys.exit("Script requires the id of the job to use as inputdata and optionally name of a file containing LFNs to process.")
> 
> jobnum = int(sys.argv[1])
> 
> 
> for sj in jobs(jobnum).subjobs.select(status='completed'):
>     		for f in sj.outputfiles.get(DiracFile):
>         		if f.namePattern.endswith('BGun.root'):
>             			if f.lfn:    #ensure file has lfn
>                 			f.localDir = sj.outputdir
>                 			f.get()

**Comment by mrwillia** [comment]
The 'insert code' function doesn't appear to work, and .py attachments are not supported - I hope that the code is clear.

**Comment by rob-c** [comment]
Hmm, this looks like the batch shutdown method isn't propagating the force flag correctly to the queues system somewhere when attempting to close, managing the worker threads on shutdown has historically proven tricky.
