### ISSUE TITLE
Batch submission with LHCbDataset is too slow

### ISSUE THREAD

**Issue by rmatev** [ganga-devs/ganga#1146]
Batch submission with LHCbDataset is extremely slow compared to using Dirac. This is likely the case for any backend other than Dirac.

Splitting is fast, but then for each subjob time is wasted in two dirac calls per input file in the LHCbDataset. You can see that from a stack trace below.

The following diff speeds things up by overriding the generic `GangaDataset` method and making a single call. Actually, I am quite sure that this call shouldn't be made in the first place as the `catalog.xml`, which is generated before and shipped to the WN, has all the LFN->PFN mappings. However, fixing this is way beyond my understanding of how ganga works internally.

```diff
diff --git a/python/GangaLHCb/Lib/LHCbDataset/LHCbDataset.py b/python/GangaLHCb/Lib/LHCbDataset/LHCbDataset.py
index 46ff131..9099746 100755
--- a/python/GangaLHCb/Lib/LHCbDataset/LHCbDataset.py
+++ b/python/GangaLHCb/Lib/LHCbDataset/LHCbDataset.py
@@ -12,7 +12,7 @@ import Ganga.Utility.logging
 from LHCbDatasetUtils import isLFN, isPFN, isDiracFile, strToDataFile, getDataFile
 from Ganga.GPIDev.Base.Proxy import isType, stripProxy, getName
 from Ganga.GPIDev.Lib.Job.Job import Job, JobTemplate
-from GangaDirac.Lib.Backends.DiracUtils import get_result
+from GangaDirac.Lib.Backends.DiracUtils import get_result, getAccessURLs
 from Ganga.GPIDev.Lib.GangaList.GangaList import GangaList, makeGangaListByRef
 from Ganga.GPIDev.Adapters.IGangaFile import IGangaFile
 logger = Ganga.Utility.logging.getLogger()
@@ -277,6 +277,17 @@ class LHCbDataset(GangaDataset):
                     raise GangaException("Cannot Get File Name")
         return names

+    def getFilenameList(self):
+        "return a list of filenames to be created as input.txt on the WN"
+        lfns = []
+        for f in self.files:
+            if len(f.subfiles) == 0:
+                lfns.append(f.lfn)
+            else:
+                for i in f.subfiles:
+                    lfns.append(i.lfn)
+        return getAccessURLs(lfns)
+
     def getCatalog(self, site=''):
         '''Generates an XML catalog from the dataset (returns the XML string).
         Note: site defaults to config.LHCb.LocalSite
```

```
  File "<ipython-input-1-26cd9c8b2d25>", line 1, in <module>
    jobs(603).subjobs[13].submit()
  File "/afs/cern.ch/user/r/rmatev/ganga/python/Ganga/GPIDev/Base/Proxy.py", line 708, in proxy_wrapped
    r = f(*s_args, **s_kwargs)
  File "/afs/cern.ch/user/r/rmatev/ganga/python/Ganga/GPIDev/Lib/Job/Job.py", line 1523, in submit
    r = self.backend.master_submit( rjobs, jobsubconfig, jobmasterconfig, keep_going, self.parallel_submit)
  File "/afs/cern.ch/user/r/rmatev/ganga/python/Ganga/GPIDev/Adapters/IBackend.py", line 196, in master_submit
    if b.submit(sc, master_input_sandbox):
  File "/afs/cern.ch/user/r/rmatev/ganga/python/Ganga/Lib/Batch/Batch.py", line 130, in submit
    scriptpath = self.preparejob(jobconfig, master_input_sandbox)
  File "/afs/cern.ch/user/r/rmatev/ganga/python/Ganga/Lib/Batch/Batch.py", line 432, in preparejob
    '###CREATEINPUTDATALIST###' : getWNCodeForInputdataListCreation(job, ''),
  File "/afs/cern.ch/user/r/rmatev/ganga/python/Ganga/GPIDev/Lib/File/OutputFileManager.py", line 348, in getWNCodeForInputdataListCreation
    '###FILELIST###', "%s" % job.inputdata.getFilenameList())
  File "/afs/cern.ch/user/r/rmatev/ganga/python/Ganga/GPIDev/Lib/Dataset/GangaDataset.py", line 96, in getFilenameList
    filelist += f.accessURL()
  File "/afs/cern.ch/user/r/rmatev/ganga/python/Ganga/GPIDev/Credentials/__init__.py", line 44, in cred_wrapped_method
    return method(self, *args, **kwargs)
  File "/afs/cern.ch/user/r/rmatev/ganga/python/GangaDirac/Lib/Files/DiracFile.py", line 574, in accessURL
    return getAccessURLs(lfns, thisSE, protocol, self.credential_requirements)
  File "/afs/cern.ch/user/r/rmatev/ganga/python/GangaDirac/Lib/Backends/DiracUtils.py", line 173, in getAccessURLs
    thisSEFiles = execute('getAccessURL(%s, "%s", %s)' % (lfns, SE, protocol), cred_req=credential_requirements)['Successful']
  File "/afs/cern.ch/user/r/rmatev/ganga/python/GangaDirac/Lib/Utilities/DiracUtilities.py", line 229, in execute
    update_env=update_env)
  File "/afs/cern.ch/user/r/rmatev/ganga/python/Ganga/Utility/execute.py", line 241, in execute
    logger.debug(''.join(traceback.format_stack()))
```

**Comment by rob-c** [comment]
@rmatev I would be weary of calling DIRAC for the accessURL for _all_ LFN in a large list this can get stuck when a single file lookup takes a long time or the call can timeout if a user is asking for too many files at once.
I tried to work around problems like this in the splitter by having large calls broken up into blocks of 500 LFN at once which turned out to be less prone to communication problems. 

That being said I think `catalog.xml` is still generated by DIRAC and dropped on the WN as in principle a file can change it's PFN between the time of submission and the job running on the WN. It's only non-DIRAC backends that Ganga will manually generate this file as required which is the best solution to accessing LFN on a non-DIRAC system.

Certainly reducing the number of DIRAC calls does have performance benefits so good spot on this one.

**Comment by rmatev** [comment]
Oh my diff should certainly not go in as is.

Not sure I explained the issue very clearly. For each subjob, the `catalog.xml` generation is very fast, but afterwards there are two dirac calls per input data file, which surely must be redundant.

**Comment by rob-c** [comment]
@rmatev I think there was at some point some level of caching within the DiracFile object which was intended to keep the result of `getAccessURL` I suspect that may either be broken or dropped as it was a bit of a hacky solution but yes I think some caching of the metadata of an LFN within ganga to reduce calls elsewhere is always good.
Tbh I think only an extra line or 2 to break up the LFN list into sensible sub-lists and then reassembling them is all that's needed as this looks like a good change to accept.

**Comment by rmatev** [comment]
But I still think this is not right. There should be no need for **any** dirac call after the `catalog.xml` generation.

**Comment by rob-c** [comment]
@rmatev Indeed. That is why there should be some caching in the DiracFile class of metadata already collected from DIRAC in the current session.
I think the `DiracFile._storedReplicas` is the object which keeps a cache of the result of calls like this. But I suspect some code isn't properly making use of this to look for AccessURLs.

**Comment by rmatev** [comment]
It's not really about dirac calls or caching. I think there should be no LFN->PFN translation happening after `catalog.xml` is generated. Or else, why is the catalog made and shipped in the first place?

Probably, this
```
File "/afs/cern.ch/user/r/rmatev/ganga/python/Ganga/Lib/Batch/Batch.py", line 432, in preparejob
    '###CREATEINPUTDATALIST###' : getWNCodeForInputdataListCreation(job, ''),
```
should just give LFNs and not do LFN-PFN translation and give PFNs.

**Comment by rob-c** [comment]
Hmm, any additional calls here are likely due to the fact that the handling code is written to pass the PFN addresses to the job in some manner. I suspect (but it's been a long time since I looked at this code) there is some `data.txt` or equivalent made which contains a flat list of PFN of the files the job is written to access.
It should be possible to disable this being generated as I suspect this functionality is needed for grid users who expect to be able to test locally from the vanilla dirac file catalog. Failing that what happens when you change the above method you made to return an empty string? I suspect the problem goes away and you get an empty text file with the job which isn't needed for LHCb apps.
