### ISSUE TITLE
Rename LCG.CERN.ch to LCG.CERN.cern

### ISSUE THREAD

**Issue by rmatev** [ganga-devs/ganga#1149]
Right now the `LHCb.LocalSite` is wrongly defined in `/cvmfs/lhcb.cern.ch/lib/GangaConfig/config/6-3-0/GangaLHCb.ini`:
```
Ganga In [5]: config.LHCb.LocalSite
Ganga Out [5]: 'LCG.CERN.ch'
```
`git grep` reveals a couple of examples to be changed.

The workaround is of course to add `LocalSite=LCG.CERN.cern` under `[LHCb]` in `.gangarc`.

**Comment by mesmith75** [comment]
Thanks for bringing this up. There is a JIRA to copy the update to CVMFS:
https://sft.its.cern.ch/jira/browse/LHCBDEP-3564
