### ISSUE TITLE
Dirac jobs don't transition to completed

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#115]
Hi all,

I'm opening a 'meta-task' to look into Dirac jobs not reaching the 'completed' state as there have been several reports of Dirac jobs not transitioning between states as intended.

I'm marking this as Dirac as I cannot reproduce this behaviour with the Local backend so suspect that this is a Dirac issue.
(Although I know that in testing I had Dirac jobs reach a 'completed' state so this could potentially be a Core bug in the handling of GangaFiles or another post-processor I'm not certain)

This may or may not be related to some jobs not being transitioned into a completed state from within the Monitoring. I'm assuming that for the moment the job getting stuck in the monitoring is different to Dirac jobs getting stuck in the 'completing' state.

I'll run some test jobs and see if I can produce a mwe which would help track down what is or isn't going on.

Thanks,

Rob

**Comment by rob-c** [comment]
I believe I have a fix for this in #117 so hopefully once that gets merged this will be fixed.

**Comment by drmarkwslater** [comment]
Don't know if it's related but doing some investigation on Friday, it seems that the monitoring loop for Dirac is getting called constantly - i.e. as soon as it's monitored the jobs once it immediately starts again whereas I would have expected ~30s in between. I haven't untangled the code enough yet to sort out a fix but this may be exposing more race conditions that you'd expect!

**Comment by rob-c** [comment]
As for the polling this is something I think needs testing in the Monitoring loop.

I have spotted that DiracBase is calling for a transition of 'running' to 'completing' due to some combination of commands now changing the status from 'running' to 'completing'.

This fails (silently) and hence the jobs get put into the 'completing' state due to another piece of code.

How the 'running' to 'complete' transition is occurring is something I'm hoping to investigate now. There is an easy fix (which I have privately) but I want to be sure nothing too bad is happening before I commit it to github.

**Comment by rob-c** [comment]
I can confirm 'disabling' the ```_index_cache``` parameter in the Node fixes all of the repo problems at the cost of the lazy loading. I'll do some work to make sure this is cleared whenever a job is loaded.

**Comment by egede** [comment]
Fixed by other monitoring fixes.
