### ISSUE TITLE
ArgSplitter uses final argument for all subjobs

### ISSUE THREAD

**Issue by chrisburr** [ganga-devs/ganga#1156]
When submitting jobs using `ArgSplitter`, all subjobs are submitted with the arguments of the final job (`[109]` in the example).

### Example:
```bash
echo '#!/bin/bash' > example.sh
echo 'date >> Example.${1}.txt' >> example.sh
echo 'echo ${1} >> Example.${1}.txt' >> example.sh
echo 'cat "Example.${1}.txt"' >> example.sh
chmod +x example.sh
```
```python
j = Job()
j.application = Executable(exe=File('example.sh'))
j.splitter = ArgSplitter(args=[[i] for i in range(100, 110)])
j.outputfiles = [DiracFile(namePattern='Example.*.txt')]
j.backend = Dirac()
j.submit()
```

Follow up to the "Failure to upload output data from Executable job" thread on `lhcb-distributed-anaysis`.

**Comment by chrisburr** [comment]
I also see the same if I use `GenericSplitter`

```python
j.splitter = GenericSplitter()
j.splitter.attribute = 'application.args'
j.splitter.values = [[i] for i in range(100, 110)]
```

**Comment by rob-c** [comment]
This is not the case with the local backend at least:
```
j=Job()
j.splitter = ArgSplitter(args=[[i] for i in range(100, 110)])
j.submit()
j.subjobs(0).application.args
j.subjobs(9).application.args
```

Could this be a bug in the new bulk submission to DIRAC?

Rob

**Comment by mesmith75** [comment]
Potentially, although SplitByFiles appears to be working at least.

**Comment by rob-c** [comment]
@mesmith75 This is a feature used by quite a few lsst people I have worked with. Is the bulk submit turned on for all users?

**Comment by egede** [comment]
@rob-c Yes, it is turned on by default. So mitigation while we consider the bug is to stay with the old version or disable it in your own `.gangarc`.

**Comment by mesmith75** [comment]
You'll have to go back to an old version I'm afraid - it is just for ArgSplitter.

**Comment by chrisburr** [comment]
@rob-c `subjob.application.args` appears to be correct in all cases for me, but it doesn't correspond to the arguments which are actually used.

@egede #1150 appears to prevent me from disabling `blockSubmit`.

Using `ganga --ganga-version DEV` results in:
```
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/python/Ganga/GPIDev/Lib/Job/Job.py", line 1523, in submit
WARNING      r = self.backend.master_submit( rjobs, jobsubconfig, jobmasterconfig, keep_going, self.parallel_submit)
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/python/GangaDirac/Lib/Backends/DiracBase.py", line 238, in master_submit
WARNING      return IBackend.master_submit(self, subjobconfigs, masterjobconfig, keep_going, parallel_submit)
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/python/Ganga/GPIDev/Adapters/IBackend.py", line 131, in master_submit
WARNING      logger.debug("SubJobConfigs: %s" % len(subjobconfigs))
WARNING  TypeError: object of type 'StandardJobConfig' has no len()
WARNING  --------------------------------------------------
```

Maybe this is another bug that needs reporting?

I've submitted my test job with an `6.6.4`, I'll report back when it runs.

**Comment by mesmith75** [comment]
Sorry, that is a stupid bug - I've just fixed it.

I've found the source of the other bug. It doesn't affect things submitted with split by files fortunately but it will affect those that have different inputsandboxes for each job, as for argsplitter. If I have a moment I'll commit the fix.

**Comment by chrisburr** [comment]
@mesmith75 Thanks, I've found a workaround for what I'm doing so I'm not affected for now.
