### ISSUE TITLE
GenericSplitter() w/ attribute = 'inputfiles' doesn't copy files to WN

### ISSUE THREAD

**Issue by biplabdey** [ganga-devs/ganga#1162]
Hi,
I want to split a job according to several input root files. I've successfully used GenericSplitter() w/ attribute = 'inputfiles', and values set to the list of the root files (DiracFiles from a previous job actually).
In my script, I first dump the list of files on the local worker node for a given subjob and it used to show the root file being present locally. Now it doesn't.
I attach a simplified setup that should reproduce the problem. I tested it on both 6.7.1 and an older 6.6.4 version (where I think it was working previously) -- currently the result is the same for both versions. 
Any help would be appreciated. 
Thanks,
-Biplab

[options.zip](https://github.com/ganga-devs/ganga/files/1485086/options.zip)

**Comment by rob-c** [comment]
This sounds like: https://github.com/ganga-devs/ganga/issues/1156
Do you still have problems with the dev version of ganga which I think has https://github.com/ganga-devs/ganga/pull/1157 applied?

**Comment by mesmith75** [comment]
Closing this as I think it was fixed by #1157
