### ISSUE TITLE
Tests to python 2.7

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1163]
Any objections to moving the tests to python 2.7? I had to upgrade a Jenkins plugin to get the release tests to work but it need python 2.7.

**Comment by mesmith75** [comment]
One test now fails: https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/test/Unit/Utility/TestUtilitiesExecuteOutput.py #L44
The cause is in the execute :
```python
stderr: python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
```
Does anyone know how to fix this - I can reproduce the problem running Ganga in my own virtualenv but not when using the LHCb python installation.

**Comment by alexanderrichards** [comment]
> Does anyone know how to fix this ? I can reproduce the problem running Ganga in my own virtualenv but not when using the LHCb python installation.

which version of python do you use in your virtualenv?
```bash
%> . venv/bin/activate
(venv) %> python --version
```

**Comment by mesmith75** [comment]
This can be fixed by putting a soft link in the lib folder of the virtualenv. Why it is not there already I don't know. I guess we need to do the same on the Jenkins machine @egede

**Comment by mesmith75** [comment]
It worked on my lxplus but not on Jenkins - the link is already there and `LD_LIBRARY_PATH` already points to it so something else is going wrong.

**Comment by mesmith75** [comment]
I think the Travis-CI also needs to drop python 2.6 - there are some requirements that no longer work.
