### ISSUE TITLE
Appending (or renaming) output file with strings from input file

### ISSUE THREAD

**Issue by cjustin88** [ganga-devs/ganga#1165]
It seems that ganga appends `.X` to the output filename of each (athena) subjob, where .X is the subjob number. Is it possible to append more information to the output filename? E.g. extract "NthField" from the filename of the input ROOT file or of the input list?

E.g.

`mc16_12345.top.stuff.txt` results in outputs named `my.output.root.12345.top.<subjob#>`

in a similar way to how `-NthFieldAsOutDir` works:

```
ganga athena --help:

  --NthFieldAsOutDir=NTH_FIELD_AS_OUTDIR
                        If multiple input list files given, store the output
                        in a dir given by the field of the list file name,
                        e.g. =2,3 data.201608.top.stuff.txt ->
                        201608.top/<output>
```

**Comment by cjustin88** [comment]
Hi,

Is it possible to add this? Many months later, I am wishing again for this feature.

Thanks.

**Comment by drmarkwslater** [comment]
@cjustin88 I'll try to look into this in the next couple of days - very sorry for the delay!
