### ISSUE TITLE
Automatic resubmission broken in the latest Ganga? 

### ISSUE THREAD

**Issue by JiboHE** [ganga-devs/ganga#1166]
It seems the automatic resubmission is broken in the latest Ganga, all the (LHCb) jobs ended with “submitting”. The error messages is attached below (with 6.7.2 - DEV)

> INFO     job 172 status changed to "submitting"
> INFO     resubmitting job 172.170 to Dirac backend
> WARNING  ---------- error in user/extension code ----------
> WARNING  Traceback (most recent call last):
> WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/python/GangaDirac/Lib/Backends/DiracBase.py", line 457, in master_auto_resubmit
> WARNING      result = b._resubmit()
> WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/python/GangaDirac/Lib/Backends/DiracBase.py", line 493, in _resubmit
> WARNING      raise BackendError('Dirac', 'No "dirac-script.py" found in j.inputdir or j.master.inputdir')
> WARNING  BackendError: BackendError: No "dirac-script.py" found in j.inputdir or j.master.inputdir (Dirac backend) 
> WARNING  --------------------------------------------------
> ERROR    failed to resubmit job, JobManagerError: error during submit
> WARNING  reverting job 172 to the submitted status
> ERROR    Monitoring Error: JobManagerError: error during submit
> INFO     job 172 status changed to "submitting"

**Comment by mesmith75** [comment]
Thanks for reporting this. Another oversight - we duplicate too much code.

**Comment by rob-c** [comment]
@mesmith75 I've been contacted by a few people about this, what's the status of the testing of the Dirac submission code? Can the tests be run manually before release?

**Comment by mesmith75** [comment]
it should be in the nightlies but there are certificate issues at the moment. We really need to get them working again - I think the hope was to move to the Imperial testing system before the end of the year to make that simpler but I don't know where we are that.

**Comment by JiboHE** [comment]
It looks like the problem is still there. I still see it with the job submitted last Saturday (so probably Ganga 6.7.4 or 6.7.3). 

> INFO     resubmitting job 51.254 to Dirac backend
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.7.4/python/GangaDirac/Lib/Backends/DiracBase.py", line 457, in master_auto_resubmit
WARNING      if self._blockResubmit():
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.7.4/python/GangaDirac/Lib/Backends/DiracBase.py", line 616, in _blockResubmit
WARNING      raise BackendError('Dirac', 'Script for job number %s not found. Resubmission failed.' % j.fqid)
WARNING  BackendError: BackendError: Script for job number 51 not found. Resubmission failed. (Dirac backend) 
WARNING  --------------------------------------------------
ERROR    failed to resubmit job, JobManagerError: error during submit
WARNING  reverting job 51 to the submitting status
ERROR    Monitoring Error: JobManagerError: error during submit

**Comment by cjones051073** [comment]
Note, I believe this issue persists in ganga 7.0.1

```
WARNING  Auto-resubmit job 69...
INFO     resubmitting job 69
INFO     job 69 status changed to "submitting"
INFO     resubmitting job 69.20 to Dirac backend
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/7.0.1/ganga/GangaDirac/Lib/Backends/DiracBase.py", line 457, in master_auto_resubmit
WARNING      if self._blockResubmit():
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/7.0.1/ganga/GangaDirac/Lib/Backends/DiracBase.py", line 616, in _blockResubmit
WARNING      raise BackendError('Dirac', 'Script for job number %s not found. Resubmission failed.' % j.fqid)
WARNING  BackendError: BackendError: Script for job number 69 not found. Resubmission failed. (Dirac backend) 
WARNING  --------------------------------------------------
ERROR    failed to resubmit job, JobManagerError: error during submit
ERROR    failed to resubmit job, JobManagerError: error during submit
WARNING  reverting job 69 to the submitted status
ERROR    Monitoring Error: JobManagerError: error during submit
ERROR    Monitoring Error: JobManagerError: error during submit
```
