### ISSUE TITLE
Proposal for improving handling of broken (sub)jobs

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#1174]
Hi all,

There are some users again reporting that the monitoring isn't picking up DIRAC jobs with subjobs in the `submitting` state.

I can't think of any meaningful way that _any_ of the current backends can deal with monitoring a job in the `submitting` state. I could be wrong, but to me if the job is in this state in the XML it indicates that something failed.
If a (sub)job has been loaded from disk and is in this state then the (sub)job is, I suspect by definition in a bad state. To get here something has crashed/failed or ganga was force exited or killed during the job submission so some or all of the monitoring information has probably been lost.

Can we consider force failing a job automatically if it's loaded from disk in a `submittting` state?

These (sub)jobs seem to be confusing the monitoring as some people are still seeing ganga struggling to update jobs with a subjob in the `submitting` state.

I think a short PR could accomplish this from the XML layer but what are people's opinions on this?

Rob

**Comment by mesmith75** [comment]
@rob-c I think that is a good idea - we already force the job to fail if some subjobs failed to submit.

**Comment by mesmith75** [comment]
Fixed by #1193
