### ISSUE TITLE
Using GridPP DIRAC with Ganga

### ISSUE THREAD

**Issue by twhyntie** [ganga-devs/ganga#1176]
Hello! Long time no see 😄 

I'm trying to use Ganga with the GridPP DIRAC backend, and following the instructions [here](http://ganga.readthedocs.io/en/latest/UserGuide/UsingDifferentBackends.html) I see there's now a script for doing that (I'm using a CernVM which has CVMFS access) - nice!

After adding the `[defaults_DiracProxy]group = gridpp_user` to `.gangarc`, I run the script and get the following errors:

```bash
source /cvmfs/ganga.cern.ch/runGanga-dirac.sh
...
*** Welcome to Ganga ***
Version: 6.7.3
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


INFO     reading config file /home/gridpp/.gangarc
INFO     reading config file /home/gridpp/.gangarc
INFO     reading config file /home/gridpp/.gangarc
INFO     reading config file /cvmfs/ganga.cern.ch/Dirac.ini
INFO     reading config file /cvmfs/ganga.cern.ch/Dirac.ini
INFO     reading config file /cvmfs/ganga.cern.ch/Dirac.ini
ERROR    unknown configuration section: [defaults_GridProxy]
ERROR    unknown configuration section: [defaults_GridProxy]
ERROR    unknown configuration section: [defaults_GridCommand]
ERROR    unknown configuration section: [defaults_GridCommand]
ERROR    unknown options [LCG]GLITE_ENABLE
ERROR    unknown options [LCG]GLITE_ENABLE

[11:05:49]
Ganga In [1]:
```

Submitting the Hello World job then fails as follows:

```python
Ganga In [1]: j = Job()
Ganga In [2]: j.backend = Dirac()
Ganga In [3]: j.submit()
INFO     submitting job 1
INFO     submitting job 1
INFO     submitting job 1
INFO     submitting job 1
INFO     job 1 status changed to "submitting"
INFO     job 1 status changed to "submitting"
INFO     job 1 status changed to "submitting"
INFO     job 1 status changed to "submitting"
INFO     Preparing Executable application.
INFO     Preparing Executable application.
INFO     Preparing Executable application.
INFO     Created shared directory: conf-cae51e72-4e9d-4db2-86a7-799ee44053a0
INFO     Created shared directory: conf-cae51e72-4e9d-4db2-86a7-799ee44053a0
INFO     Created shared directory: conf-cae51e72-4e9d-4db2-86a7-799ee44053a0
ERROR    ConfigError: attempt to create a configuration section [defaults_GaudiXMLSummary] after bootstrap 
ERROR    ConfigError: attempt to create a configuration section [defaults_GaudiXMLSummary] after bootstrap 
ERROR    ConfigError: attempt to create a configuration section [defaults_GaudiXMLSummary] after bootstrap  ... reverting job 1 to the new status
ERROR    ConfigError: attempt to create a configuration section [defaults_GaudiXMLSummary] after bootstrap  ... reverting job 1 to the new status
INFO     job 1 status changed to "new"
INFO     job 1 status changed to "new"
INFO     job 1 status changed to "new"
INFO     job 1 status changed to "new"
ERROR    JobError: Error: ConfigError: attempt to create a configuration section [defaults_GaudiXMLSummary] after bootstrap
```

(I've created a proxy with `dirac-proxy-init` and successfully submitted a test job via `dirac` directly.)

Am I missing something/doing something wrong, or do I need to add anything to my `.gangarc` file?

Any help much appreciated as ever.

Cheers, @twhyntie

**Comment by rob-c** [comment]
Hi again, I fixed this in a PR: https://github.com/ganga-devs/ganga/pull/1155
There is functional code needed for the GangaDirac plugin which is in the wrong part of the codebase (GangaGaudi).
This needs to be corrected in head.

The first set of errors: `ERROR    unknown configuration section: [defaults_GridProxy]` etc are _harmless_ but if you either remove the offending sections from your .gangarc file or start again with a minimal .gangarc ganga will stop complaining about these sections.
Whether this should be an error or a warning I don't know.

**Comment by twhyntie** [comment]
Thanks.

FWIW these:
```
ERROR    unknown configuration section: [defaults_GridProxy]
ERROR    unknown configuration section: [defaults_GridProxy]
ERROR    unknown configuration section: [defaults_GridCommand]
ERROR    unknown configuration section: [defaults_GridCommand]
ERROR    unknown options [LCG]GLITE_ENABLE
ERROR    unknown options [LCG]GLITE_ENABLE
```
appear to be added by the DIRAC script - they aren't in my local `.gangarc` (but yes, they don't seem to affect anything after that...).

So should I wait for the merge before trying again?

Cheers, T

**Comment by rob-c** [comment]
@twhyntie The cvmfs area has needed updating for a while now I suspect. I'll wait to hear back from the ganga devs before pushing my fix but until then can you try adding: 
```
[Configuration]
RUNTIME_PATH = GangaDirac:GangaGaudi
```
to your .gangarc

You may hit a problem trying to use the dirac_ui instance on cvmfs, I don't know if it's been updated or not.

**Comment by twhyntie** [comment]
No joy 😢 - same errors...

Same errors when using `/cvmfs/ganga.cern.ch/runGanga.sh` - is this expected, i.e. are all of the CVMFS scripts out of date and/or tied to Gaudi?

**Comment by rob-c** [comment]
@twhyntie I think the scripts are likely outdated I don't know who maintains them.

You are probably following the tutorials to setup a local dirac_ui and point ganga to that in the config.

Are you comfortable running ganga from git? In which case you can just grab the PR and run from there. (Not quite as easy as it once was I appreciate)

**Comment by twhyntie** [comment]
Is it @drmarkwslater who does the CVMFS updates?

**Comment by twhyntie** [comment]
Okey dokey!

So, I installed ganga on my CernVM using the `fixGaudiBadness` branch.  This was non-trivial, not because of Ganga, but because the CernVM is shipped with Python 2.6.6 (SL6 dependency for yum etc. bla bla bla). _However_ this was quite handy as it forced me to find out how to actually get 2.7.X running on the CernVM - and there's a nice guide [here](https://danieleriksson.net/2017/02/08/how-to-install-latest-python-on-centos).

Once this was done, I could create a 2.7 `virtualenv` in which to install Ganga from your Git PR branch - which _was_ trivial 😄 

Launching Ganga from this - and using the DIRAC CVMFS script - I am able to submit jobs via the Dirac() backend once I updated my `.gangarc` file as documented elsewhere.

Woohoo! Thank you very much for your help, as ever.

**Comment by mesmith75** [comment]
Can we close this?

@twhyntie The DEV version on CVMFS will be updated at 1am so from tomorrow you should be able to use that if you like.

**Comment by twhyntie** [comment]
@mesmith75 Sure - and thanks again for your help.

(I'll give the CVMFS scripts a try tomorrow too but actually the 2.7 thing has solved a few other things for me too!)

**Comment by twhyntie** [comment]
(Have tried running with the `/cvmfs/ganga.cern.ch/runGanga[-dirac].sh` script today and still get Gaudi errors when submitting with DIRAC - but I can run with the version I have so not a showstopper at the moment, will leave the issue closed.)

**Comment by rob-c** [comment]
These scripts i think only use the latest stable version. There may one that users the latest DEV version of ganga which should have now been updated against this issue
