### ISSUE TITLE
Sharedir decrementing not working for subjobs

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1180]
The sharedir for jobs with subjobs is not being indexed properly. Removing a job with subjobs doesn't remove the sharedir - for a job without subjobs it works fine.

**Comment by rob-c** [comment]
@mesmith75 Sounds interesting, does the counter on the sharedir reflect the number of subjobs+1 when the parent job is fully prepared?

**Comment by mesmith75** [comment]
@rob-c Yes. I think its just that the subjobs don't explicitly get remove when the master does, so the counter only goes down by 1, not 1+nSubjobs. Should be a simple fix.

I wonder if that also means that the subjobs are persisting in the repository?

**Comment by rob-c** [comment]
@mesmith75 I would have assumed the subjob XML are being removed correctly.
From a quick look the method at: https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/GPIDev/Lib/Job/Job.py#L1731 just needs to be expanded to iterate over subjobs and a simple test written to check the behaviour

**Comment by mesmith75** [comment]
@rob-c Actually I don't think that is the issue. That bit behaves as it should.

I think the problem is that jobs loaded from disk apparently don't have any subjobs, i.e. `len(self.subjobs)` returns 0.

**Comment by rob-c** [comment]
Hmm, this object should be a SubJobXMLList instance which should be returning the correct length. If this is wrong then there may be a bug there.

**Comment by mesmith75** [comment]
So they type is right:
```
type(self.subjobs)
type of subjobs:  <class 'Ganga.Core.GangaRepository.SubJobXMLList.SubJobXMLList'>

```

**Comment by rob-c** [comment]
Hmm, my instinctive reaction is to blame `stat(self._jobDirectory).st_ctime` for failing.
(I forgot to mention this may be a standard list object if the job wasn't loaded from disk).

Does this work if you do all of this in one session? i.e. split, prepare/submit and remove the job without restarting ganga?

**Comment by mesmith75** [comment]
yes - its only jobs loading from disk that have the issue.

**Comment by rob-c** [comment]
Huh, a quick modification to `Ganga/test/GPI/newXMLTest/TestSJXMLGenAndLoad.py` to explicitly test the length of the subjobs works as expected. And this is what I see in ganga normally...

Does the above test work on the system you're having problems on?

**Comment by rob-c** [comment]
Ah, I see you may have spotted and fixed the bug 👍
