### ISSUE TITLE
locations attribute not updated for LCGSEFile

### ISSUE THREAD

**Issue by apingault** [ganga-devs/ganga#1186]
Whenever I run a job with `j.outputfiles` set to some `LCGSEFile` the `LCGSEFile.locations` attribute is not updated when the job is finished: it stays empty.
I then have to manually go check the guid of the files in the `__postprocesslocations__` file in the output folder. This is quite tedious and don't think it's the intended behavior if I look at the `setLocation` function in [`LCGSEFile.py`](https://github.com/ganga-devs/ganga/blob/6.7.4/python/Ganga/GPIDev/Lib/File/LCGSEFile.py): there is ` lcgse_file.locations = guid` instruction that seems to never be called.

>**EDIT**: If I pass the exact file name in the `namePattern` field the `locations` is properly set with the guid of the file. It's not working when using a wildcard.

Another question somewhat related : Is it possible to define our own lfn for the `LCGSEFile`?
In my case it defaults to `/grid/$voname/generated/$date/file-$some_random_number`
I didn't find a way to change that in the `config` or using the various attribute of LCGSEFile.
I would be interested in defining it to something like `se_rpath` + `namePattern` for example.
`se_rpath` and `namePattern` seems to only impact the srm name.

**Comment by egede** [comment]
@apingault Can I ask in which connection that you use `LCGSEFile`? The bug itself looks quite easy to fix, but I would like to make sure that what you do is actually optimal (as `LCGSEFile` is pretty much deprecated).

**Comment by apingault** [comment]
I'm running jobs on the `CREAM` backend (with the 'calice' vo). In the past I was using bash scripts with `lcg` commands to be executed on the WorkerNode to transfer files. For various reasons the upload (WN->grid storage) script would often fails and my files would be stuck on the WN.

I saw that the `LCGSEFile` seems to be able to do the download/upload of the files by itself and probably better than what I was doing (better error handling). I didn't know it was deprecated.

What File type should I be using instead?

**Comment by egede** [comment]
Nearly all job submission to the grid go through a workload management system such as DIRAC, and as far as I know, submission directly to grid sites through cream was discouraged. 

Nevertheless, we are happy to fix the bug you reported and I am pleased that the rest is still working.
