### ISSUE TITLE
Message caching not working

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1191]
Ganga isn't caching logging messages when it should.

**Comment by rob-c** [comment]
This is a long standing issue with the logging I think. If you want to investigate this I'd have a look at the use of MemoryHandler passing https://docs.python.org/2/library/logging.handlers.html#memoryhandler https://github.com/ganga-devs/ganga/blob/develop/python/GangaCore/Utility/logging/__init__.py

We may want to consider _not_ flushing errors to the user unless it's from the main thread as you would expect a worker thread failing to inform you on your next carriage return but in the current setup as soon as an error is hit the whole historical log data is dumped to screen.

With regard to the original dast email should we offer a way to save the result of job.peek somewhere for people wanting to examine more closely a (long-)running job?
