### ISSUE TITLE
Condor() backend fails trying to copy file to node

### ISSUE THREAD

**Issue by natfarleydev** [ganga-devs/ganga#1199]
When I submit a ganga job via the `Condor()` backend, I get the following error

```
Traceback (most recent call last):
  File "/var/lib/condor/execute/dir_21888/condor_exec.exe", line 161, in <module>
    shutil.copy(inFile, os.path.join(os.getcwd(), os.path.basename(inFile)))
  File "/usr/lib64/python2.7/shutil.py", line 133, in copy
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 83, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
shutil.Error: `ntuple_maker_mc_12103091_2011.py` and `/var/lib/condor/execute/dir_21888/ntuple_maker_mc_12103091_2011.py` are the same file
```

where `ntuple_maker_mc_12103091_2011.py` is my DaVinci submission script.

I believe the offending lines are: 
* https://github.com/ganga-devs/ganga/blob/47825403bdb9f6d6123d1b6745751f0711318d15/python/GangaCore/Lib/Condor/Condor.py#L288-L290
* https://github.com/ganga-devs/ganga/blob/47825403bdb9f6d6123d1b6745751f0711318d15/python/GangaCore/Lib/Condor/Condor.py#L315-L319
such that `shutil.copy` effectively ends up trying to copy the file over itself.

**Comment by rob-c** [comment]
After checking with the user this is a bug being thrown from the job backend or part of the wrapper for a `GaudiExec` application and so should be treated as a bug in the Condor code.
Obviously fully testing this without a condor backend is tedious but it may be good to try and submit a job with the submit stage noop-ed away in testing.
