### ISSUE TITLE
Parallel submit on Local backend spams local system

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#1207]
Hi,

I've been doing some testing and was surprised that splitting 1000 subjobs would nuke my system by submitting so much stuff in parallel.

Is there objection to adding some simple logic to stop jobs landing on the local backend hammering a machine by accident?

Rob

**Comment by mesmith75** [comment]
sounds reasonable - if you wanted you could follow the Interactive backend example and just prevent any parallel submitting.
