### ISSUE TITLE
develop failing to cache logs

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#1211]
I think this was addressed a short while ago but I'm seeing the main thread getting spammed while I try to type a complex command out.
(on latest develop)

Did something change with regard to the cache size or the log caching to keep logging from spamming the user while they're busy?

**Comment by mesmith75** [comment]
@rob-c The monitoring is definitely caching messages for me.

**Comment by rob-c** [comment]
@mesmith75 is this buffering errors (imo it probably should be but am I incorrect)?
A simple way I can reproduce this is to fire off 100 jobs locally on one lxplus node then move to another and I get spammed with missing folder errors even when I try to type something unrelated.

**Comment by mesmith75** [comment]
It is not caching errors (also maybe not warnings), just INFO
