### ISSUE TITLE
ITransform self._parent returns NoneType

### ISSUE THREAD

**Issue by NickHastings** [ganga-devs/ganga#1212]
Using ganga 6.7.4 I get the following error when running an ND280Task(). Sample code:

<pre>
hastings@kudu ~ 
% work/ganga-debug/install/6.7.4/bin/ganga

*** Welcome to Ganga ***
Version: 6.7.4
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.

INFO     reading config file /home/hastings/.gangarc
tas
[10:51:03]

Ganga In [1]: execfile('nd280test.gpi')
INFO     Reading . ...

[10:51:07]
Ganga In [2]: ERROR    Exception occurred in task monitoring loop: <type 'exceptions.AttributeError'> 'NoneType' object has no attribute 'n_tosub'
The offending task was paused.
ERROR    Full traceback:
 Traceback (most recent call last):
   File "/home/hastings/work/ganga-debug/install/6.7.4/python/Ganga/GPIDev/Lib/Tasks/TaskRegistry.py", line 92, in _thread_main
    p.update()
   File "/home/hastings/work/ganga-debug/install/6.7.4/python/Ganga/GPIDev/Lib/Tasks/ITask.py", line 98, in update
    if trf.update() and not self.check_all_trfs:
   File "/home/hastings/work/ganga-debug/install/6.7.4/python/Ganga/GPIDev/Lib/Tasks/ITransform.py", line 224, in update
    unit_status["bad"], self._getParent().n_tosub())
 AttributeError: 'NoneType' object has no attribute 'n_tosub'
</pre>
The problem seems to be because self._getParent() in ITransform.update() returns None.
[nd280test.gpi](https://github.com/ganga-devs/ganga/files/1718348/nd280test.gpi.gz) s a very stripped down version of python/GangaND280/examples/runND280RDP_tasks.py 
I place it here inline too:
<pre>t   = ND280Task()
trf = ND280Transform()
trf.application = runND280RDP()
d=ND280LocalDataset()
d.get_dataset('.','fakedata.mid.gz')
trf.addInputData(d)
t.appendTransform(trf)
t.float = 10
t.run()</pre>
Note that the file "fakedata.mid.gz" does not need to exist to reproduce the error.

This error does not occur with ganga 6.6.4 or earlier versions. It seems that perhaps something in the ND280Transform or DataSet needs to be updated to use ganga 6.7.4 or that perhaps something under GPIDev broke. I looked in ITransform.py but don't understand why this is happening.

P.S. This looks like it may be the same problem as reported at https://github.com/ganga-devs/ganga/issues/1144 hopefully the devs can reproduce it now with the nd280test.gpi I provided.

**Comment by mesmith75** [comment]
Thanks. I can reproduce this with the most basic LHCbTask. We shall take a look.

**Comment by NickHastings** [comment]
@mesmith75  thanks. Let me there is anything I can test or do to help get this fixed.

**Comment by mesmith75** [comment]
@NickHastings I think #1216 should fix this. If you have a local installation could you try with that branch?

**Comment by NickHastings** [comment]
Hi @mesmith75 ,

thanks for the very fast work! I  made that change in my 6.7.4 installation and it seems to fix that particular bug but it also reveals a new one. I submitted a new issue, #1218 for this.

Cheers,

Nick.
