### ISSUE TITLE
Ganga-ci testing at Imperial

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1213]
This is a list of issues that still have to be considered for the ganga-ci testing at Imperial

- [ ] Put /cvmfs on parent machine to allow caching from one test to the next of file system
- [ ] Change LHCb docker container to be the officially supported one
- [ ] Introduce nightly test that runs all the external tests
- [ ] Get external tests to work for Core test by setting up certificates
- [ ] Upload new gangage certificate
- [ ] Create cron job that cleans up orphaned Docker containers and images
- [ ] Set a maximum time for test to make sure that ones caught in an infinite loop are not hogging test slots.

**Comment by mesmith75** [comment]
- [ ] Make workspace directories shorter. I was getting problems with pip install in virtual env because the directory was too long, hence Ganga-Release -> Release.

**Comment by egede** [comment]
Machine has stopped responding. I have requested a reboot. Suspect that it is casused by a full disk as we have not put any protections in place yet for orphaned docker images.

**Comment by alexanderrichards** [comment]
Could be, however I will check with Simon as I know he was planning some upgrade work on the cloud at some point.

**Comment by egede** [comment]
Yes, it was indeed down for maintenance. Simon put it back up but it will go down shortly tomorrow again. I just take the chance now to clean up old images - there are indeed quite many.

**Comment by alexanderrichards** [comment]
did he say how long it will be down for tomorrow?

**Comment by egede** [comment]
@alexanderrichards  @mesmith75  The machine is running now, but it seems like the tests are not starting. Any idea what is wrong?

**Comment by alexanderrichards** [comment]
unlike before they don't start when you use a keyword in the pull request message box. I believe that they only start when a commit is made (or manually on the jenkins system).

**Comment by alexanderrichards** [comment]
they have just started now

**Comment by egede** [comment]
OK, so the Jenkins box picks up on a commit, but it does not pick up the missed ones.

@mesmith75 I thought you got the keyword thing "test me" or whatever to work. What is the magic?

**Comment by egede** [comment]
@alexanderrichards The one that started was due to a commit that I made.

**Comment by alexanderrichards** [comment]
I havent got that magic working yet as it's a different project type so I'll have to investigate if it's even possible. It is of course possible to manually start it from the jenkins box

**Comment by egede** [comment]
OK. I just committed a noop to the different pending ones. It should all go through now,

**Comment by mesmith75** [comment]
`test this please` should do it.

**Comment by egede** [comment]
Just updated the expired grid certificate on the Jenkins machine.
