### ISSUE TITLE
Errors caused from stdin being inherited from parent process

### ISSUE THREAD

**Issue by chrisburr** [ganga-devs/ganga#1215]
Using Control+C to cancel a running cell or clear the current prompt sometimes causes errors in ganga's internals, such as:

```
Ganga In [2]: WARNING  exit status [1] of command lhcb-proxy-info --file "/tmp/x509up_u25156"
WARNING  exit status [1] of command lhcb-proxy-info --file "/tmp/x509up_u25156"
WARNING  exit status [1] of command lhcb-proxy-info --file "/tmp/x509up_u25156"
WARNING  exit status [1] of command lhcb-proxy-info --file "/tmp/x509up_u25156"
WARNING  exit status [1] of command lhcb-proxy-info --file "/tmp/x509up_u25156"
```

I think this is being caused by commands in `subprocess` being implicity called with `stdin=None` (for example in [`GangaCore.Utility.Shell`](https://github.com/ganga-devs/ganga/blob/b024d67066f02bfa545f928b324de7d9842abf65/ganga/GangaCore/Utility/Shell.py)). From the Python docs:

> stdin, stdout and stderr specify the executed program’s standard input, standard output and standard error file handles, respectively. Valid values are PIPE, an existing file descriptor (a positive integer), an existing file object, and None. PIPE indicates that a new pipe to the child should be created. **With the default settings of None, no redirection will occur; the child’s file handles will be inherited from the parent.**

**Comment by mesmith75** [comment]
I think this has been negated by #1194 so I'll close this.
