### ISSUE TITLE
IApplication  does not have a is_prepared member 

### ISSUE THREAD

**Issue by NickHastings** [ganga-devs/ganga#1218]
Hi,

thanks for the very fast work on #1212. I  made that change in my 6.7.4 installation and it seems to fix that particular bug but it also reveals a new one.  My application is derived from IApplication which does not have a is_prepared member which seems to be needed in Job.py

From my ganga session
<pre>astings@kudu ~ 
% ~/work/ganga-debug/install/6.7.4/bin/ganga

*** Welcome to Ganga ***
Version: 6.7.4
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.

INFO     reading config file /home/hastings/.gangarc
</pre>
....
<pre>
10:46:47]
Ganga In [5]: execfile('nd280test.gpi')
INFO     Reading . ...

[10:46:50]
Ganga In [6]: 

[10:50:28]
Ganga In [16]: INFO     submitting job 12
INFO     job 12 status changed to "submitting"
Please ensure a value for nd280ver using the object.options['nd280ver']
ERROR please make sure all options stated above are entered
INFO     Preparing subjobs
ERROR    Exception raised executing '_prepare_sj' in Thread 'None':
Traceback (most recent call last):
  File "/home/hastings/work/ganga-debug/install/6.7.4/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py", line 115, in __worker_thread
    result = item.command_input.function(*these_args, **item.command_input.kwargs)
  File "/home/hastings/work/ganga-debug/install/6.7.4/python/Ganga/GPIDev/Lib/Job/Job.py", line 1209, in _prepare_sj
    if app.is_prepared in [None, False]:
AttributeError: 'runND280RDP' object has no attribute 'is_prepared'
</pre>

I had to flesh out the sample code a little more this time.
 [nd280test.gpi](https://github.com/ganga-devs/ganga/files/1730027/nd280test.gpi.gz) is now:
<pre>
import os
t   = ND280Task()
trf = ND280Transform()
app = runND280RDP()
app.cmtsetup = [ 'fakesetup.sh']
trf.application = app
d=ND280LocalDataset()
datafile='fakedata.mid.gz'
if not os.path.exists(datafile):
    file(datafile,'w').close()
d.get_dataset('.',datafile)
trf.addInputData(d)
trf.backend=Local()
t.appendTransform(trf)
t.float = 10
t.run()
</pre>
The files setup.sh  does not need to exist but I think fakedata.mid.gz does otherwise there is no attempt to prepare the subjobs. Also note that the the error message about "nd280ver" not being set is not relevant here.

I hope the fix for this problem is as simple as the last!

**Comment by mesmith75** [comment]
I'm not sure if that is supposed to be in IApplication - for every other application it is put in their schema. Someone more knowledgeable should probably comment.

In any case I have added it into the ND280RDP application on the same PR #1216 . Let me know if that works.

**Comment by NickHastings** [comment]
Ok thanks @mesmith75 , this seems to have fixed that problem. Now when running in the app I get

<pre>
anga In [7]: INFO     submitting job 15
INFO     job 15 status changed to "submitting"
ERROR    GangaAttributeError: Object 'runND280RDP' does not have attribute: 'prepare'
ERROR    GangaAttributeError: Object 'runND280RDP' does not have attribute: 'prepare' ... reverting job 15 to the new status
INFO     job 15 status changed to "new"
ERROR    Couldn't submit the job. Deactivating unit.
INFO     Unit 0 of transform 0, Task 26 has aborted the loop
</pre>

Looking at at another application (python/GangaLHCb/Lib/Applications/GaudiExec.py) I see that it  has:
_exportmethods = ['prepare', 'unprepare', 'execCmd', 'readInputData'] and has the prepare() method implemented. So it seems  'prepare' needs to be added to added to _exportmethods in my task (currently an empty list) and I need to implement a prepare() method that does nothing.  I tried this and it seems to have worked: the task is able to submit the job. The change is currently only in my 6.7.4-cedar02 branch.

I think if I make similar changes to other apps under GangaND280 I may now be able to get my feature/ND280 branch into shape to make a pull request into develop.

**Comment by alexanderrichards** [comment]
IPrepareApp inherits from IApplication and the prepared stuff is in there. Please inherit from that rather than IApplication. The Job.py file should not really be calling any prepared stuff directly but rather that should be done by the IPrepareApp in the standard master_configure methods or something like that. Given that we havent fixed that you should just inherit from IPrepareApp.

**Comment by NickHastings** [comment]
@alexanderrichards ahh, thanks, I thought it should be in a base class, but didn't notice IPrepareApp. I'll try as you suggest.
