### ISSUE TITLE
Outdated requirements

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1222]
In our setup.py we require some ancient versions of things - in particular I note ipython 1.2.1 . We should update or get rid of the version specific requirements altogether.

**Comment by rob-c** [comment]
IPython 2 requires Python 2.7 hence the holding this back (is sl6 still supported?): `http://ipython.org/ipython-doc/2/install/install.html#installing-ipython-itself` `http://ipython.org/ipython-doc/2/install/install.html#installing-ipython-itself`

On the other hand jumping to 3 would be fun ;) it has some proper solutions to work-arounds I'm aware of in 1.

If there was a docker image or set of instructions to install via virtualenv I'd say bump everything to the latest asap :)

**Comment by rob-c** [comment]
otoh, this is not python3 so IPython 5 is the best I think ganga can realistically aim for atm `http://ipython.readthedocs.io/en/stable/install/index.html`: `If you are looking for an IPython version compatible with Python 2.7, please use the IPython 5.x LTS release and refer to its documentation (LTS is the long term support release).`

**Comment by egede** [comment]
I would hope that `pip` is clever enough to only install a version that is compatible with `Python2` if I use the `python2` version of `pip`.

Concerning `python2.6`, we are no longer supporting it. We basically say that people on an `slc6` system should in one way or the other have support for a more modern version of python.

**Comment by rob-c** [comment]
regarding python 2.6 good to hear!
regarding pip2 yes pip2 is smart enough to limit itself to python2.x packages. (I don't know if ganga even tries to install with pip3)
