### ISSUE TITLE
ARC backend

### ISSUE THREAD

**Issue by afortiorama** [ganga-devs/ganga#1231]
Hi,

it doesn't seem to be possible to add the queue to the list of xrsl parameters. 

The cream syntax <CE><port>:<queue> to submit doesn't work with arcsub and there is no queue object for the ARC backend, i.e. j.backend.queue does't work. Could you let me know if there is a recipe or consider to add an extra attribute to the ARC backend list?

cheers
alessandra

**Comment by afortiorama** [comment]
Any news on this?

**Comment by mesmith75** [comment]
Hello,

I'll add a `queue` attribute to the ARC backend - would I be correct to see it has to be in the JDL but can be empty?

Unfortunately I don't have access to ARC so I can't test it though.

**Comment by afortiorama** [comment]
Thanks, I can help with testing if you point me to a development version.

**Comment by mesmith75** [comment]
@afortiorama The branch from #1267 has the queue added. The xrsl looks like:
```
&
(environment=("GANGA_LCG_CE" "")
("GANGA_LCG_VO" "lhcb")
("LFC_HOST" "")
("GANGA_LOG_HANDLER" "WMS")
)
(queue="some_queue")
(executable="__jobscript_11__")
(inputFiles=("_input_sandbox_11.tgz" "/afs/cern.ch/work/m/masmith/GangaTest/test/repos/workspace/masmith/LocalXML/11/input/_input_sandbox_11.tgz")
("__jobscript_11__" "/afs/cern.ch/work/m/masmith/GangaTest/test/repos/workspace/masmith/LocalXML/11/input/./__jobscript_11__")
)
(outputFiles=("__jobscript__.log" "")
("stdout.gz" "")
("stderr.gz" "")
)
```

By default the `queue` argument is blank.

**Comment by afortiorama** [comment]
Hi,

the submission doing something like ganga job.py worked ok for me and it picked the right queue. 

I couldn't though use this version to monitor the job because it complained about ipython missing. I put it down to the fact that I downloaded from github and the setup might be wrong.

replying to your comment in the other ticket, if you can add other extras, it will make easier for user using direct submission to their local cluster.

**Comment by mesmith75** [comment]
@afortiorama Thanks for testing this - I also added `xRSLextras` that can take a `dict` if you want to add other arguments.

**Comment by afortiorama** [comment]
Thanks

**Comment by egede** [comment]
@afortiorama To get a running version when using Github, the best is to use pip inside a virtualenv and then just give the url for the download from git. Then the dependencies will get installed.

**Comment by mesmith75** [comment]
@afortiorama That has been merged and will be in the DEV version on CVMFS from tomorrow.
