### ISSUE TITLE
python-gflags : Obsolete. Please migrate to absl-py instead.

### ISSUE THREAD

**Issue by JacekHoleczek** [ganga-devs/ganga#1235]
[PyPI > Package Index > python-gflags > 3.1.2](https://pypi.python.org/pypi/python-gflags/3.1.2)

**Comment by mesmith75** [comment]
Yes. I think this should be done with the ipython update - upgrading will also likely break the old versions on CVMFS and AFS.

**Comment by mesmith75** [comment]
Fixed in #1229
