### ISSUE TITLE
Different architecture/gcc version on submitting machine and server causes CMake failure

### ISSUE THREAD

**Issue by natfarleydev** [ganga-devs/ganga#1242]
Having a different architecture on the host and on the server causes cmake to fail building as:

```
ERROR    Failed to execute command: /tmp/tmps0Q3Wy.sh
ERROR    Failed to execute command: /tmp/tmps0Q3Wy.sh
ERROR    Tried to execute command in: /disk/homedisk/home/nasf/git/rootless-broccoli/ntuple-maker/DaVinciDev_v39r1p1
ERROR    Tried to execute command in: /disk/homedisk/home/nasf/git/rootless-broccoli/ntuple-maker/DaVinciDev_v39r1p1
ERROR    StdErr: WARNING : using environment variable CMTSITE for cmtsite
WARNING : using environment variable User_release_area for userarea
WARNING : using environment variable VO_LHCB_SW_DIR for sharedarea
./run: line 21: ./build_env.sh: No such file or directory
ERROR    StdErr: WARNING : using environment variable CMTSITE for cmtsite
WARNING : using environment variable User_release_area for userarea
WARNING : using environment variable VO_LHCB_SW_DIR for sharedarea
./run: line 21: ./build_env.sh: No such file or directory
ERROR    GangaException: Failed to Execute command
ERROR    GangaException: Failed to Execute command
ERROR    GangaException: Failed to Execute command ... reverting job 299 to the new status
ERROR    GangaException: Failed to Execute command ... reverting job 299 to the new status
```

(Different versions as demonstrated using LHCb software stack:

```
[10:56:21]
Ganga In [13]: x.j.application
Ganga Out [13]:
 GaudiExec (
   getMetadata = False,
   extraArgs = []  ,
   is_prepared = None,
   extraOpts = ,
   useGaudiRun = True,
   platform = x86_64-slc6-gcc49-opt,
   directory = /disk/homedisk/home/nasf/git/rootless-broccoli/ntuple-maker/DaVinciDev_v39r1p1,
   options = [ LocalFile (
   namePattern = 'ntuple_maker_mc_12103091_2011.py',
   compressed = False,
   localDir = '/disk/homedisk/home/nasf/git/rootless-broccoli/ntuple-maker/tangled'
 )]
 )
[10:56:24]
Ganga In [14]: !echo $CMTCONFIG
x86_64-slc6-gcc62-opt
```
)

**Comment by mesmith75** [comment]
This shouldn't be an issue. When ganga makes the tarball it should do it in a fresh environment for whatever platform you asked for. Of course CMTCONFIG will give you gcc62 as that is the standard LHCb environment.

Have you tried running make first outside of ganga (with the desired platform)?

**Comment by natfarleydev** [comment]
If I switch platform (`source /cvmfs/lhcb.cern.ch/group_login.sh -c x86_64-slc6-gcc49-opt`) so that ganga is running on the same platform as the `GaudiExec` job, it builds fine.

The DaVinci folder builds using the platform `x86_64-slc6-gcc49-opt` (which is the platform `prepareGaudiExec` chooses) but with `x86_64-slc6-gcc62-opt` it fails. 

(NOTE: DaVinci only builds after doing `git lb-use DaVinci`, but I presume Ganga does this itself when preparing the build)

**Comment by mesmith75** [comment]
hmm - I'll check this out.

This is for sure fine with regards the platform you submit from and the platform on the WN though.

**Comment by natfarleydev** [comment]
Yes, the job works fine if it manages to get submitted (or rather, it builds fine and then fails for an unrelated DaVinci reason).

**Comment by mesmith75** [comment]
Is this with prepareGaudiExec or with a DaVinci version you previously built?
