### ISSUE TITLE
trivial GangaND280/ND280RecoValidation/VFT_make_ana.py modification

### ISSUE THREAD

**Issue by JacekHoleczek** [ganga-devs/ganga#1248]
Could you, please, modify one line in the existing "GangaND280/ND280RecoValidation/VFT_make_ana.py".
Please replace:
`args.append('$ND280ANALYSISTOOLSROOT/macros/grtf/pdfgen/make_pdf.py')`
with:
`args.append('${ND280ANALYSISTOOLSROOT:-${RECONUTILSROOT}}/macros/grtf/pdfgen/make_pdf.py')`
You may add a git commit note in form:
The "grtf" macros are possibly moved from nd280AnalysisTools into reconUtils.
Thanks in advance.

**Comment by mesmith75** [comment]
Unfortunately none of the developers are involved with ND280. You are more than welcome to fork the repository and prepare your own PRs if you like.

**Comment by drmarkwslater** [comment]
@JacekHoleczek As Mark says, I think for traceability it's best if this comes directly from you or another ND280 member - we don't want to be accused of breaking it 😄

**Comment by drmarkwslater** [comment]
Ah - I should have looked a bit closer! I can see that @mesmith75 has already prepared the PR 😄
