### ISSUE TITLE
No Ganga/__init__.py shipped with job

### ISSUE THREAD

**Issue by mjmottram** [ganga-devs/ganga#125]
Running the latest develop version, ```Ganga/Utilities/__init__.py``` and ```files.py``` are both shipped with the job, but no ```Ganga/__init__.py```, meaning that the job fails on the backend whenever attempting to load files relative to the _python/Ganga base directory (e.g. when adding an output sandbox).

**Comment by rob-c** [comment]
@mjmottram What backend(s) are you seeing this problem with? I'm seeing jobs passing on a few tests I'm running atm so I can probably take a look at this

**Comment by mjmottram** [comment]
LCG.  Ganga was removed from the default modules list to get shipped to the backend at some point recently.

**Comment by rob-c** [comment]
OK, I'll see if I can do any testing, strange I'm not seeing this on my Dirac jobs atm.
The list was shortened when I removed the 'spyware' from the worker nodes which was at least in the way or at worst getting fragile in it's old age.

**Comment by mjmottram** [comment]
Running with outputfiles (maybe specifically LocalFile or at least anything that then requires an import of any of Ganga.xxx during running) should cause this.

**Comment by drmarkwslater** [comment]
As mentioned in PR #126, this was due to #87 (apologies!). I'll try to put in a good fix for this ASAP.
