### ISSUE TITLE
Max # of concurrent subjobs in ganga athena --local mode

### ISSUE THREAD

**Issue by cjustin88** [ganga-devs/ganga#1255]
If I submit a --local job with N number of subjobs, ganga athena launches all N subjobs at once. This could result in sub-optimal performance if N is greater than the # of cores on the machine and/or results in too much stress on the storage subsystem.

Can a setting that limits the max # of concurrent subjobs be added for --local operation? It could start (max #), then once one subjob finishes, another subjob is started in its place.

For example, I run over many datasets, with multiple text files listing the files of each dataset:
``` ganga athena --local --inPfnListFile='1.txt,2.txt,...25.txt' --split=8 ...```

Ganga warns:
```
WARNING  Number of requested subjobs smaller than number of output dirs found - changing j.splitter.numsubjobs = 25
INFO     submitting 25 subjobs
```
Then it starts 25 subjobs:
```jobs(8).subjobs```
```Registry Slice: jobs(8).subjobs (25 objects)```

**Comment by will-cern** [comment]
I'll just add that I think it would be ok if the "ganga athena" process sits there waiting for the running processes to finish so that it can spawn the next batch. 

This functionality is only requested for the --local mode, it's probably not relevant for batch
