### ISSUE TITLE
DiracFile missing `get` method

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1256]
DiracFile doesn't have a `get` method implemented.

**Comment by rob-c** [comment]
I think the logic for file `get`-ing is something similar to:

`DiracFile::get` == `IGangaFile::get` -> `IGangaFile::copyTo` -> `DiracFile::internalCopyTo`

The `get` method has slightly confusing (to preserve old expected) behaviour and if you want to know where a file is going I'd highly recommend using `copyTo` instead as this is implicit in what you're after.

A unittest for this would probably be helpful to demonstrate I suppose

**Comment by rob-c** [comment]
Is this causing problems for people, or has the method become broken?

**Comment by mesmith75** [comment]
Ah I see - in which case this is a non-issue. There was a bug elsewhere. Thanks!
