### ISSUE TITLE
Submitting Notebook as Ganga job

### ISSUE THREAD

**Issue by apsknight** [ganga-devs/ganga#1260]
While submitting Notebook as a Ganga Job, I am getting following error.

```
Traceback (most recent call last):
  File "notebook_wrapper_generated.py", line 15, in <module>
    from IPython.nbconvert.preprocessors import ExecutePreprocessor
ImportError: No module named preprocessors
```

The error is because of this line:
https://github.com/ganga-devs/ganga/blob/cb18fa716605ac219e3f2ec354b05ab12adef7bc/ganga/GangaCore/Lib/Notebook/wrapperNotebookTemplate.py.template#L15

However the following is working fine 
```python
from nbconvert.preprocessors import ExecutePreprocessor
```

IPython version = 1.2.1

**Comment by egede** [comment]
@apsknight So this is in the code that is executed as part of the job. I suspect that it is an IPython version related issue. But why doesn't the test case fail in our continuous integration? Can you create a pull request with the suggested change. The continuous integration tests will then automatically run on it and we ca investigate the difference.

As a side comment, we are in the process of updating the ancient IPython dependency to a modern one.
