### ISSUE TITLE
Importing Ganga in ipython shell.

### ISSUE THREAD

**Issue by apsknight** [ganga-devs/ganga#1265]
In version 7.0.2 of Ganga, On running `import ganga.ganga` in an ipython shell, it gives following error

```python
File "/home/knight/.local/lib/python3.6/site-packages/ganga/ganga/__init__.py", line 46
    raise GangaException(x), None, sys.exc_info()[2]
                           ^
SyntaxError: invalid syntax
```

**Comment by rob-c** [comment]
@apsknight This looks like a Python3 related issue but is due to ganga failing to load the plugins.
Can you comment out this line 46 in the above file and re-run as this will give a more complete stack trace of what went wrong, hopefully with a meaningful error

**Comment by apsknight** [comment]
@rob-c After commenting `Line 46` following error is received
```python3
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-d24f1d79c1ac> in <module>()
----> 1 import ganga.ganga

/home/knight/ganga/ganga/ganga/__init__.py in <module>()
      4 import atexit
      5 
----> 6 from GangaCore.Utility.Runtime import allRuntimes
      7 from GangaCore.Utility.Config import getConfig, setSessionValuesFromFiles
      8 from GangaCore.Utility.logging import getLogger

/home/knight/ganga/ganga/GangaCore/__init__.py in <module>()
      4 import inspect
      5 import getpass
----> 6 import commands
      7 from GangaCore.Utility.ColourText import ANSIMarkup, overview_colours
      8 

ModuleNotFoundError: No module named 'commands'
``` 

This error is because `commands` has been deprecated since Python 2.6 (https://docs.python.org/2/library/commands.html) but Python 2.6 has been deprecated by recent versions of ipython (http://ipython.readthedocs.io/en/stable/) so is there any possibility of importing Ganga in ipython ?

**Comment by egede** [comment]
@apsknight After @rob-c fixed the small issue this morning, I can import ganga into an ipython session. Did you try with the develop branch from Github?

**Comment by egede** [comment]
So from my desktop running Fedora 27

```
[heppc47] ~/git/ganga % ipython
Python 2.7.14 (default, Mar 14 2018, 13:36:31) 
Type "copyright", "credits" or "license" for more information.

IPython 5.5.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import ganga.ganga


In [2]: 
```

**Comment by rob-c** [comment]
@apsknight Can you verify which version of (I)Python you're using? when you use the very latest IPython by default you pull in Python3 as a requirement (_I think_).

**Comment by apsknight** [comment]
@egede Yeah, it works for Python2.7 but ipython has deprecated version lower than Python3.3 since ipython 6 (http://ipython.readthedocs.io/en/stable/). So I wanted to ask how can I import Ganga on a kernel running latest version of ipython.

**Comment by egede** [comment]
@apsknight At the moment, I do not think that is possible. We have not yet migrated Ganga to Python 3 (as there has been no demand within particle physics). I do not think it is a big job, but it is not done right now. Does this present a big problem for you?

**Comment by apsknight** [comment]
Closing it for now, will let you know if I require something specific.
