### ISSUE TITLE
WARNING  Could not find info for job id 'None'

### ISSUE THREAD

**Issue by sabahsalih** [ganga-devs/ganga#1268]
I keep getting this every time I type

jobs

Ganga In [3]: jobs

WARNING  Could not find info for job id 'None'
WARNING  Could not find info for job id 'None'
WARNING  Could not find info for job id 'None'
WARNING  Could not find info for job id 'None'

and sometime when I quit

**Comment by egede** [comment]
This looks like an error from jobs submitted to the ARC backend. When using this backend, there is some pattern recognition done on stdout files, and it fails in this instance. This causes the job status to be stuck. If you can guess the jobs causing the error, I suggest just to remove them by using `j.remove()` with `j` being the job object. Using the ARC backend is a fairly deprecated use of the Grid. Can you elaborate on your use case.
