### ISSUE TITLE
new release 

### ISSUE THREAD

**Issue by sabahsalih** [ganga-devs/ganga#1270]
Dear All,
            I shall be very grateful if you could let us know when this become  a release please

https://github.com/ganga-devs/ganga/commit/52b367862ebc7af1a81878f52ee46264437073f8

Many Thanks, Sabah.

**Comment by egede** [comment]
@mesmith75 Can we initiate a new release this week?

**Comment by mesmith75** [comment]
@egede I'll check with @alexanderrichards in case anything is occurring with Jenkins, otherwise yes.

**Comment by alexanderrichards** [comment]
yes please go ahead

**Comment by mesmith75** [comment]
7.0.3 has been released.

**Comment by sabahsalih** [comment]
Dear Mark,
         Thank you and Thank you ever so much.

   Many Thanks, Sabah.


From Sabah Salih
Particle Physics Group,
The School of Physics and Astronomy,
The University of Manchester,
Schuster Laboratory,
Brunswick Street,
Manchester M13 9PL.
Tel: +44 1612754171 or  x4171
E-mail: sabah.salih@manchester.ac.uk
________________________________
