### ISSUE TITLE
Make GaudiExec build failure errors friendly.

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1280]
They are not very helpful at the moment.

**Comment by rob-c** [comment]
Yeah I'd been thinking this for a while seeing the mailing list posts over and over.

Maybe the `execCmd` is the wrong place to log an error and it should be the processes calling this which track what went wrong? I suppose the whole "_failed to execute command:..._" is only useful for debugging.

**Comment by mesmith75** [comment]
I think we should return the whole stdout here. It is very possible the build fails due to bad user code, in which case that would be the most useful for them, even though it is lengthy.
