### ISSUE TITLE
DiracFiles in inputfiles should not be labelled as inputdata in Dirac

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1282]
When an LFN is listed in the inputsandbox in the Dirac API, the file pointed to is copied to the PWD on the worker node when the job starts. This is waht happens if a `DiracFile` is used a an inputfile for the `Dirac` backend. However, in the line 

https://github.com/ganga-devs/ganga/blob/8ca6ee73653e32b272d4d5055187d1892f5558e3/ganga/GangaDirac/Lib/RTHandlers/DiracRTHUtils.py#L148

we set it as `inputdata` in the Dirac API as well. This seems wrong. It will cause the job just to be matched to sites where the LFN is present, but that seems wrong in this case (it is typically not a datafile). I suggest to delete the above line.

**Comment by egede** [comment]
Suggested fix above is not correct. The line above actually correctly assigns the inputdata field. I have so far failed to find where DiracFiles in inputfiles are assigned as inputdata as well.

**Comment by mesmith75** [comment]
Is this just an issue for GaudiExec ?

**Comment by egede** [comment]
No, I just reproduced this myself with a standard executable application.

```
j = Job(backend=Dirac(), inputfiles = [DiracFile('LFN:/lhcb/test')])
```
is producing the script

```
resultdict = {}

# dirac job created by ganga
from DIRAC.Core.Base.Script import parseCommandLine
parseCommandLine()
from DIRAC.Interfaces.API.Dirac import Dirac
from DIRAC.Interfaces.API.Job import Job
dirac = Dirac()
sjNo='2'

j = Job()

# default commands added by ganga
j.setName('{Ganga_Executable_(2)}')
j.setExecutable('exe-script.py','','Ganga_Executable.log')
j.setInputSandbox(['/home/hep/egede/gangadir/workspace/egede/LocalXML/2/input/_input_sandbox_2.tgz', 'LFN:/lhcb/test', 'LFN:/lhcb/test', ])
j.setInputData(['/lhcb/test'])
...
```

Also note that `/lhcb/test` is repeated twice in the inputsandbox.

**Comment by rob-c** [comment]
A workaround for the moment might be to try `j.backend.settings({'InputData':[]})` within ganga as this should overload the `setInputData` attribute before the job is submitted.
Granted this doesn't fix the double inputsandbox attribute which is a little odd. Could this have come from the recent changes to collect the jobs before submission?

**Comment by mesmith75** [comment]
@rob-c I apologise, I was wrong. This does indeed work fine for executable jobs. There is an issue with GaudiExec not including DiracFiles which I think I have found the source of. Let's merge this and I'll fix that in a separate PR.
