### ISSUE TITLE
Python3 pickle decoding error

### ISSUE THREAD

**Issue by apsknight** [ganga-devs/ganga#1288]
https://github.com/ganga-devs/ganga/blob/845f3f8239f17304fe92aa0a8efab4ab93406967/python/Ganga/Core/GangaRepository/PickleStreamer.py#L18

`UTF-8` is unable to decode some characters in byte string thus it is giving errors like this,
```bash
'utf-8' codec can't decode byte 0xb2 in position 17: invalid start byte
```

a simple solution of this could be changing the line to 
```python3
    fileobj.write(str(output)[2:-1])
```
Reference: https://stackoverflow.com/a/46748988

**Comment by apsknight** [comment]
@alexanderrichards Should I update this line as stated above ?

**Comment by egede** [comment]
@apsknight Yes, please go ahead if this solves the problem.

**Comment by alexanderrichards** [comment]
@apsknight I'm happy to go with this fix if it solves the problem but I'm a little nervous that we are not throwing away something important by slicing the output string. what is in the first two characters that we slice?

**Comment by apsknight** [comment]
@alexanderrichards
It removes `b(` and `)` from output.

**Comment by alexanderrichards** [comment]
ah of course. What is the source of this string if not utf-8 is this a pickled object?

**Comment by apsknight** [comment]
@alexanderrichards Yes
