### ISSUE TITLE
Runtime of jobs submitted to condor

### ISSUE THREAD

**Issue by apsknight** [ganga-devs/ganga#1289]
`Ganga Version: 7.0.3`
While querying the runtime of jobs submitted to Condor backend using `j.time.runtime()`. I am getting following error.

```bash
WARNING  Could not calculate duration: 'backend_running' not found.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/ganga/GangaCore/GPIDev/Base/Proxy.py", line 709, in proxy_wrapped
    r = f(*s_args, **s_kwargs)
  File "/usr/lib/python2.7/site-packages/ganga/GangaCore/GPIDev/Lib/Job/JobTime.py", line 365, in runtime
    masterrun = masterrun + jobs.time.runtime()
TypeError: unsupported operand type(s) for +: 'datetime.timedelta' and 'NoneType'
```

**Comment by apsknight** [comment]
@alexanderrichards @egede Please look into this.

**Comment by alexanderrichards** [comment]
is this only the case for Condor backend?

**Comment by apsknight** [comment]
For Localhost backend, I can query the runtime after Job has been completed.

**Comment by alexanderrichards** [comment]
I assume then that the error lies in the Condor backend, specifically in the monitoring function.
perhaps it's not setting the timing information properly

**Comment by mesmith75** [comment]
Setting the timestamps hasn't been implemented for Condor. I'll add that in and make it fail nicely if a backend doesn't have them.
