### ISSUE TITLE
Font color barely readable on dark backgrounds

### ISSUE THREAD

**Issue by jheuel** [ganga-devs/ganga#1301]
Some font colors are barely readable in combination with dark backgrounds (e. g. dark blue font color for the prompt).

As I understand the color schemes of ipython are used and there is a section in the default .gangarc where I should be able to configure ipython to use another colorscheme ("Linux", "LightBG", "NoColor", ...). uncommenting this and trying the different schemes has no effect on my session. I also deleted my ~/.ipython and ~/.ipython-ganga folders to cover the case that I misconfigured ipython somewhere.

Is there a way to change the color scheme or turn it off if it is not possible?

**Comment by egede** [comment]
Which version of Ganga do you use? As the latest version (7.1.0) has changed the iPython version, something may very well have gone wrong here.

**Comment by jheuel** [comment]
I am using 7.1.0 (the default on lxplus).

![image](https://user-images.githubusercontent.com/12282358/42619894-a138fdfe-85b9-11e8-8876-5e0b9abe6dac.png)

**Comment by egede** [comment]
Colour schemes has indeed changed for iPython5. See https://ipython.readthedocs.io/en/stable/config/details.html
A short term fix is to use the iPython magic command like

```%colors Linux```

at the prompt. See ```%colors?`` for other options available.

**Comment by jheuel** [comment]
Is there also a way to make this permanent? 
I did set the color scheme in `.ipython-ganga/profile_default/ipython_config.py`:
```
c = get_config()
c.TerminalInteractiveShell.colors = 'Linux'
```
This works in the vanilla ipython shell but is ignored by ganga.

**Comment by egede** [comment]
Yes, sure, it should go into the next version.

**Comment by jheuel** [comment]
Thank you! :+1:

**Comment by egede** [comment]
Please try the DEV version on /cvmfs tomorrow and report back if problem is not fixed. Just try

```
ganga -o'[TextShell_IPython]colourscheme=Linux'
```
