### ISSUE TITLE
cvmfs dirac-ui installation having problems

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#1304]
From a machine where I don't have admin access to create a missing directory I get the following error when trying to use the installation from cvmfs.
(installing the ui by hand on this machine locally fixes this as a work-around but for new users this is a bit of a mess as the ui doesn't strictly need this directory to exist, and imo shouldn't rely on it).

```
Traceback (most recent call last):
  File "/cvmfs/ganga.cern.ch/dirac_ui/DIRAC/Core/DISET/private/Transports/SSL/SocketInfo.py", line 144, in __getCAStore
    for fileName in os.listdir( casPath ):
OSError: [Errno 2] No such file or directory: '/etc/grid-security/certificates'
```

I'm not sure there is a nice way to fix this short of installing this on a _clean_ machine then copying the files over to cvmfs.

Feel free to mark as won't fix as this is more here to help anyone else who stumbles across this.

**Comment by mesmith75** [comment]
@rob-c I don't know if we maintain the DIRAC installation on CVMFS. At least I know I don't. I'll stick this down as a won't fix and close. Maybe this should be taken up with the DIRAC devs as it looks like a simple fix from their side.
