### ISSUE TITLE
rename the tab "Ganga Jobs"

### ISSUE THREAD

**Issue by moscicki** [ganga-devs/ganga#1309]
Please rename to "Jobs"

![image](https://user-images.githubusercontent.com/621965/43410474-4b6f18fa-9427-11e8-9868-c86e4447d178.png)

**Comment by apsknight** [comment]
@moscicki Maybe, you wanted to open this issue on `gangaextension` repo, I've opened it here : https://github.com/apsknight/gangaextension/issues/23
