### ISSUE TITLE
Updating version in CVMFS

### ISSUE THREAD

**Issue by afortiorama** [ganga-devs/ganga#1311]
Hi,

could the version in CVMFS be updated please? Or is there a reason why it hasn't? Some users are waiting to for the last fix Rob committed.

thanks

cheers
alessandra

**Comment by mesmith75** [comment]
The DEV version on CVMFS is updated daily if you need it.

We just haven't made a new release recently but we can do that this week.

**Comment by afortiorama** [comment]
Hi Mark, it'd be helpful if the production release in CVMFS was was updated.

**Comment by mesmith75** [comment]
@afortiorama Sorry for the delay with this - the testing was having issues and then some things got merged that needed checking before release.
I'll do the new release first thing in the morning.

**Comment by mesmith75** [comment]
7.1.1 release

**Comment by afortiorama** [comment]
Thanks
