### ISSUE TITLE
Lost Connection Error

### ISSUE THREAD

**Issue by apsknight** [ganga-devs/ganga#1314]
While submitting Ganga Jobs, sometimes there is an error due to stomp library. More discussion about this error can be found here: https://github.com/apsknight/gangaextension/issues/8

This is the logger entry corresponding to this error in `.ganga.log` file:

![](https://user-images.githubusercontent.com/19551774/43357791-843c6f04-92a4-11e8-9ebc-3782ff5d6074.png)

**Comment by mesmith75** [comment]
We could change this to DEBUG ?

**Comment by apsknight** [comment]
But this is also slowing down the submission of Job. Maybe @egede or @rob-c can tell better, what to do with this.

**Comment by mesmith75** [comment]
Ah I see, we want to stop stomp entirely

**Comment by mesmith75** [comment]
What if you set `UsageMonitoringMSG` to `False` in your .gangarc ? That should stop stomp trying to publish things.

**Comment by mesmith75** [comment]
Solved
