### ISSUE TITLE
Ganga Condor job splitting

### ISSUE THREAD

**Issue by moscicki** [ganga-devs/ganga#1318]
Instead of submitting 1000 subjobs as 1000 individual Condor jobs Ganga should split it using Condor mechanisms... Is anything like that available?

Please see here: https://github.com/apsknight/gangaextension/issues/28

**Comment by mesmith75** [comment]
This is not so straightforward. Each subjob has its own script to execute but you can only have one `executable` in the condor submission script.

The executable needs to be a wrapper that takes an argument to execute the real `Ganga_0_Executable` that gets copied over.
