### ISSUE TITLE
ROOT not correctly setup

### ISSUE THREAD

**Issue by rmatev** [ganga-devs/ganga#1333]
The ROOT that ganga is trying to use for merging is not usable the way ganga tries to use it, as it requires a newer `libstdc++` than available on the system. A LHCb-specific solution could be to give the possibility to configure the entire prefix and set it to `lb-run root ` for LHCb. I'm not sure how version selection can be implemented in this scheme. 

Version: 7.1.3
Tested platforms: `x86_64-slc6-gcc62-opt` and `x86_64-centos7-gcc62-opt`
Reproducer:
```python
import GangaCore
import commands
cmd = GangaCore.Utility.root.getrootprefix()[1] + 'hadd'
commands.getstatusoutput(cmd)

# /cvmfs/lhcb.cern.ch/lib/RootConfig/pro/x86_64-centos7-gcc62-opt/bin/hadd: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /cvmfs/lhcb.cern.ch/lib/RootConfig/pro/x86_64-centos7-gcc62-opt/bin/hadd)
# /cvmfs/lhcb.cern.ch/lib/RootConfig/pro/x86_64-centos7-gcc62-opt/bin/hadd: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /cvmfs/lhcb.cern.ch/lib/RootConfig/pro/x86_64-centos7-gcc62-opt/lib/libGraf3d.so)
# ...
```

PS It might be useful to run this or something similar to see where libraries come from.
```sh
lb-run root bash -c 'ldd `which hadd`'
```

**Comment by mesmith75** [comment]
@rmatev Thanks for bringing this up - it has been on the to-do list for too long (#1029 ). I'll take a look.

**Comment by mesmith75** [comment]
Even better would be to use the ROOT version in the application.
