### ISSUE TITLE
Adding to job schema

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1342]
I would like to add something to the schema for `Job`. Is it possible to do this without breaking the lazy loading of existing jobs?

**Comment by egede** [comment]
If the information is printed out when you type `jobs`, I suspect it will trigger a full load for all jobs.

@rob-c You have a comment?

**Comment by mesmith75** [comment]
sorted.

**Comment by rob-c** [comment]
Hi, probably a little late,

The _lazy loading_ functionality I think is more or less restricted to a smaller dictionary of job id, current status and name. Changing the job Schema unless it impacts these parameters doesn't impact this functionality it's more or less independent. (these parameters are also those in the default _jobs_ summary).

However,  the lazy loading is also needed for the `jobs` summary to be a lightweight command. If the user changes the job summary to include say the executable name or build path then the `jobs` summary _will_ break in the sense of it will trigger an expensive load of all job objects from disk.
There are some working tests in the test area which test (I think) against the default `jobs` summary as well as on querying job status (done by any sensible monitoring component).
