### ISSUE TITLE
Registry race conditions still happening

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#136]
I'm going to have to do some minor development in the Registry to give more information on race conditions and add some logic to protect against exceptions from the code designed to prevent this.

Some users still report problems when torture testing the repo. It's not clear if this could be a threading issue as I'm not 100% certain that the use of RLock is 100% safe hence why I added a conventional Lock around the flush mechanism as part of 6.1.15

**Comment by rajanandakumar** [comment]
Code used by me : a file "test.py" which has the following lines of code. Note the two python scripts which are included which I will be happy to provide also if you want - they are specific to my analysis though, and not general.

############################
magnet = "MagDown" # or "MagUp"
year = "12"
energy = "/Beam4000GeV"
strip  = "Stripping21"
path = "/LHCb/Collision" + year + energy + "-VeloClosed-" + magnet + "/Real Data/Reco14/" + strip + "/90000000/LEPTONIC.MDST"
dataset = BKQuery(path).getDataset()
j = Job(application=DaVinci(version='v37r2p4'))
typeFile = "/home/ppd/nraja/ppd_raja/xemu/gangaFiles/DV_data_mdst.py"
optsFile = "/home/ppd/nraja/ppd_raja/xemu/gangaFiles/DVBd2LLKstar.py"
j.application.optsfile = typeFile
j.application.optsfile.append(optsFile)
j.name = "Data " + magnet + " " + year
j.do_auto_resubmit = True
j.inputdata = dataset
j.splitter = SplitByFiles()
j.splitter.filesPerJob = 15
j.backend = Dirac()
queues.add(j.submit)
############################

And then within Ganga, I run the above file using - execfile("test.py"), separately for MagUp and MagDown. As you can see, the command will return the iPython prompt quite fast, as I submit the job to the queues.

What I found was that in each case of MagUp and MagDown, Ganga went through the loop and created ~400 subjobs each and then looped over each of them. For both the MagUp and MagDown, the submission crashed at subjob ~144 (error below) and stopped. This crash ended up turning off the monitoring also.

Ganga.GPIDev.Adapters              : INFO     submitting job 0.144 to Dirac backend
Ganga.GPIDev.Lib.Job               : INFO     job 0 status changed to "submitting"
Ganga.GPIDev.Adapters              : WARNING  ---------- error in user/extension code ----------
Ganga.GPIDev.Adapters              : WARNING  Traceback (most recent call last):
Ganga.GPIDev.Adapters              : WARNING    File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r14/install/ganga/python/Ganga/GPIDev/Adapters/IBackend.py", line 183, in master_submit
Ganga.GPIDev.Adapters              : WARNING      if b.submit(sc, master_input_sandbox):
Ganga.GPIDev.Adapters              : WARNING    File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r14/install/ganga/python/GangaDirac/Lib/Backends/DiracBase.py", line 200, in submit
Ganga.GPIDev.Adapters              : WARNING      return self._common_submit(dirac_script_filename)
Ganga.GPIDev.Adapters              : WARNING    File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r14/install/ganga/python/GangaDirac/Lib/Backends/DiracBase.py", line 163, in _common_submit
Ganga.GPIDev.Adapters              : WARNING      self.id = idlist
Ganga.GPIDev.Lib.Job               : INFO     job 0 status changed to "submitted"
Ganga.GPIDev.Adapters              : WARNING    File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r14/install/ganga/python/Ganga/GPIDev/Base/Objects.py", line 595, in __set__
Ganga.GPIDev.Adapters              : INFO     submitting job 0.145 to Dirac backend
Ganga.GPIDev.Adapters              : WARNING      obj_reg.turnOnAutoFlushing()
Ganga.GPIDev.Lib.Job               : INFO     job 0 status changed to "submitting"
Ganga.GPIDev.Adapters              : WARNING    File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r14/install/ganga/python/Ganga/Core/GangaRepository/Registry.py", line 327, in turnOnAutoFlushing
Ganga.GPIDev.Adapters              : WARNING      self._backgroundFlush()
Ganga.GPIDev.Adapters              : WARNING    File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r14/install/ganga/python/Ganga/Core/GangaRepository/Registry.py", line 701, in _backgroundFlush
Ganga.GPIDev.Adapters              : WARNING      self._flush(objs)
Ganga.GPIDev.Adapters              : WARNING    File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r14/install/ganga/python/Ganga/Core/GangaRepository/Registry.py", line 799, in _flush
Ganga.GPIDev.Adapters              : WARNING      del self._inprogressDict[self.find(stripProxy(obj))]
Ganga.GPIDev.Adapters              : WARNING  KeyError: 0
Ganga.GPIDev.Adapters              : WARNING  --------------------------------------------------
Ganga.GPIDev.Lib.Job               : WARNING  Not all subjobs have been sucessfully submitted: IncompleteJobSubmissionError:  ('1.141', '0') 

As I mentioned in the email, what I ended up doing to recover from this is

1. Note the error (above).
2. Then killed and restarted Ganga.
3. Go to the two sub jobs which were stuck in "submitting" state, force them to "failed" status and then "resubmit" them.
4. Make a quick ganga loop to submit the remaining jobs which were in "new" state.
5. Every once in a while, reset the backend of one of the jobs to start the monitoring again, whenever I suspect it to be down.

Do let me know if you need any more information from me.

**Comment by rajanandakumar** [comment]
Also, as an observation, a job resubmit done interactively, i.e.

j.resubmit()

is at least apparently much slower than doing it through the queues system, i.e.

queues.add(j.resubmit)

Of course, this is primarily a subjective feeling, but I believe backed by quite a bit of observation.

**Comment by rob-c** [comment]
@rajanandakumar Thanks for letting me know about the resubmit observation. I'll do some investigating and see if everything is being correctly done in the case of resubmit on queues.

**Comment by rob-c** [comment]
I believe this should have been fixed in recent changes to make registry transactions thread-safe.
