### ISSUE TITLE
no output on jobs which fail and were killed on the grid

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#1363]
Hi,

Might have spotted a potential cause of confusion/bug.

From working with a local user in Edinburgh, if a job has been killed by ganga due to many subjobs failing does Ganga still automatically download the output for the failed subjobs for debugging.

I think there may have been some subjobs which have the correct output downloaded but at least some of the subjobs didn't auto-download the output which made life confusing.
(The subjob was marked as failed so should have finished finalizing from a worker thread but there was nothing in the subjob output folder)

Just seemed like an odd bug that there was no output from Ganga despite the jobs being marked as killed/failed.

If I get a chance I'll try and verify the behaviour but this seemed a little odd,

Thanks,

Rob

**Comment by mesmith75** [comment]
@rob-c There is a bug with the latest release so that sandboxes are not being downloaded. #1364 will fix it. If you like you can approve it and I'll release a new version now.
