### ISSUE TITLE
permission errors when downloading to eos

### ISSUE THREAD

**Issue by ttekampe** [ganga-devs/ganga#1368]
When downloading output files of grid jobs to eos via the eos fuse mount on lxplus I get errors like this:

```
GangaDiracError: {'Successful': {}, 'Failed': {'/lhcb/user/t/ttekampe/2018_10/233615/233615802/Bu_D0pipipi_Kenu_MC_12185008_2016_Sim09c_MagDown.root': 'Operation not permitted ( 1 : Could not copy srm://lhcbsdrm.
t1.grid.kiae.ru:8443/srm/managerv2?SFN=/t1.grid.kiae.ru/data/lhcb/lhcbuser/lhcb/user/t/ttekampe/2018_10/233615/233615802/Bu_D0pipipi_Kenu_MC_12185008_2016_Sim09c_MagDown.root to file:///eos/lhcb/user/t/ttekampe/K
1sim_noStrip/134/10/Bu_D0pipipi_Kenu_MC_12185008_2016_Sim09c_MagDown.root, [1] Could not open destination: errno reported by local system call Operation not permitted)'}}
```

What I do exactly is putting `DiracFile.Get(...)` into the ganga queues. That way multiple files are downloaded at the same time. I reported the issue to the eos support and they might have found the source of the problem.

Quoting  Andreas Joachim Peters:

> So what I think is, that GANGA switches authentication tokens to talk to the GRID, which result in a permission denied error on the FUSE mount. You probably use a grid certificate to fetch files and to do so the KRB5CCNAME variable might get invalidated and when this happens in an uncoordinated way by parallel agents you end up revoking the authentication token to talk to EOS. I see that the initial requests are mapped to your kerberos name while later they are mapped to a GRID pool account which has no permission to work in your directory. It might be that in the past this has worked because there was a nother credential binding mechansim used on the FUSE mount.

So a possible workaround, which seems to work for some people is to just download one file at a time, but maybe there is also a way to fix this in ganga?

**Comment by egede** [comment]
I thought this was due to the caching of the DIRAC environment in Ganga, but reading again I am not so sure. I wonder rather if DIRAC is doing something where it writes a temporary file with a fixed name and then can't cope with simultaneous operations.

**Comment by egede** [comment]
Maybe back to the first idea. When logging into lxplus, the KRB5CCNAME environment variable gets a value like FILE:/tmp/krb5cc_12230_b2HFgU where the first number is the uid of the user but the second part is a random string (to avoid writing files with predictable names in /tmp I guess). In any case, a DIRAC command that executes will use the file name given in the cache instead.

**Comment by egede** [comment]
Solution might be to modify code around https://github.com/ganga-devs/ganga/blob/ea53546c0b03dbed1afa5eccc8362a509185d632/ganga/GangaDirac/Lib/Utilities/DiracUtilities.py#L227 to let KRB5CCNAME stay the same as in the running Ganga session.

**Comment by egede** [comment]
@ttekampe Can you try to 

- exit Ganga
- remove the directory ~/.cache/Ganga
- start Ganga again and see if everything works for downloading to /eos in that particular session (where you will then have a matching KRB5CCNAME in the newly created cache and in your session.

**Comment by ttekampe** [comment]
I followed you instructions and downloaded 456 files without getting a single exception. So this seems to work.

**Comment by egede** [comment]
@ttekampe Thanks for the test. I think we have discovered the issue then. The comments about queues and parallel downloads or not, I think are then a red herring and not actually related. I searched through the complete software stack of both LHCbDIRAC and DIRAC and did not find a single mention of KRB5CCNAME or the use of kinit.
