### ISSUE TITLE
JobTime has no parent issues

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#137]
Hi all,

I'm seeing a (new?) bug that some jobs can't update their status on HEAD due to the jobTime object not having a parent object correctly assigned.

This object should be being assigned using the ```__set__``` method in Objects.py and automatically picking up a parent. It's not clear if this is due to the setParent methods being subverted or whether there is an incorrect use of setattr over setNodeAttribute somewhere for (just?) this attribute.

This is quite serious and I'd like to get this fixed asap to avoid getting into a situation as with 6.1.14 where these problems plague the release debugging for longer than they should.

Rob

**Comment by milliams** [comment]
This is strange as the only place `JobTime` objects are created is in the schema job `Job` via its `defvalue`. The only way this might not be working is if somehow the value being passed in is a proxied JobTime object and so the `if isinstance(attrib_value, Node)` is failing. This theoretically shouldn't happen but at the moment it's technically possible.

**Comment by rob-c** [comment]
Other than if we have a broken copy method i agree. either way this is potentially very bad and needs attention

**Comment by rob-c** [comment]
This appears to have gone away. I think this was a bug my end when I modified something that 'should have no effect' and it broke readin in the XML in a strange and unusual way.

I'll close this for now as I can't reproduce it on HEAD :D
