### ISSUE TITLE
LHCbDirac env cache

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1388]
There is a recurring problem of the cached LHCbDirac env becoming corrupted somehow - often users are not able to debug this themselves (the errors are non-sensical) and end up wasting time on red-herrings / complaining.

The caching of the env takes between 1 and 3 seconds typically. Can we just do this for every time ganga starts?

Alternatively shall we modify the `diracCommand` wrapper to make a new cache the first time it catches an exception and make it try again?

**Comment by egede** [comment]
I think we can change it to just do it every time. The cache was introduced when we had the old SetupProject where it could easily take 20s.
