### ISSUE TITLE
Monitoring Loop timeouts/poll-rates are not what is naively expected.

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#139]
Hi all,

This came up in last weeks meeting and I mentioned I wasn't sure if this was un-related. Now I think this is a quite serious (albeit separate) bug.

From what I can tell the poll rate for backends is being passed into ```timeoutMax``` in ```UpdateDict.addEntry```.
This doesn't appear to be used in executing code from the monitoring thread unless I've missed something?

In addition the use of base_poll_rate is out by a factor of 2 in HEAD so causes it to appear as if backend tasks are being polled every 1 sec instead of 2.
(This is an easily fixed typo)

After some investigating the monitoring system seems to run like this:

1. Infinite loop with break point is launched on construction of Monitoring loop.
2. Active backends and other queries are added to dictionary of actions in Monitoring system (internal set of queue instructions).
(potential bug, this appears to ALWAYS be populated once, regardless of if monitoring is supposed to be running)
3. Once running the main loop runs through the dictionary of actions and each action spawns a task on a queue system. This running through the dictionary is controlled by the 'base_poll_rate'.
4. Infinite loop keeps the queues system populated with 'tasks' from the dictionary of items

The queues system has it's own mechanics which is slightly difficult to disentangle from all of this.

1. A small thread-pool is setup on launch of ganga which cycles through the threading queues and runs tasks on various threads.
2. Actions are added to the queue from the main monitoring loop:
  * If the action isn't in this queue already it's added.
  * If the action is already in the queues give it the list of jobs of interest and return.
(no point in queueing if a friend is queueing for you and if the friend is busy, return and come back later)
3. Action is run on the queue system once it's reached it's turn. First thing it should do is get a thread lock on itself and remove itself from the queue. Whilst an action is executing it shouldn't allow for another action to cause it upset.

The polling times from the various backends appear to be used only for giving information when executing the command ```runMonitoring``` which is intended to perform a single pass of the infinite monitoring loop if the monitoring system is turned off.

 
 

__I have a few questions based upon this:__

1. Should we change the documentation to reflect the fact that these poll rates don't appear to effect the rate at which the backend is polled?
2. Should we allow the backends to be polled at different rates (We can easily add a conditional pause into the check backends function to sleep unless a certain length of time has passed)?
3. Do we need disk and credential polling here? Do they work?
  * Can we get rid of deprecated functionality
  * Can we simplify some of this code and collect a lot of related static functions into one place?
(There is code in the IBackend at the moment which should be in the monitoring system imo)
4. Should we just leave this all alone in favour of starting again with a new system based on something more modern?

After just inspecting the code I've spotted a few minor bugs which need addressing anyway and one of these relates to thread safety so I'm inclined to add these fixes into a PR and see what the performance of the monitoring under stress behaves like.

**Comment by milliams** [comment]
Good investigation, I'll need to re-read this a few times to get the hang of it :smile:

One think I will say is that `timeoutMax` does seem to be used by `UpdateDict.timeoutCheck()` since it is stored in the `_DictEntry` class as `timeoutCounter` and `timeoutCounterMax`. How they are used further to that and what thread that is run in I haven't looked in to.

**Comment by alexanderrichards** [comment]
hi guys, for those of us with less time to investigate could you make things like `UpdateDict.timeoutCheck()` a link to the appropriate line in the code as it will save me a lot of time figuring out what dict this is...many thanks :smile:

**Comment by alexanderrichards** [comment]
e.g. [`UpdateDict.timeoutCheck()`](https://github.com/ganga-devs/ganga/blob/7d2fa2e07c7bd15b5e6158d68cdc33fdea68ebe9/python/Ganga/Core/MonitoringComponent/Local_GangaMC_Service.py#L278)

Although having said that it didn't take me too long to actually find :wink: so maybe you can just ignore my noise

**Comment by rob-c** [comment]
@milliams They're only used for 'debug' style messages from ```runMonitoring``` I've found which is interesting but ultimately a bit misleading imo. It just tells us if the code executed in < the ''poll time'' which to me is not what poll time suggests it should be.


Apologies this is a bit of a mess but unfortunately after getting my head around this, that post made sense. Which probably means I need to explain it in a meeting.

We basically have 1 loop running in the background managing Actions.
As well as this we have a thread-pool of 4 threads which all attempt to keep grabbing the next JobAction from the internal Que and then execute the function the JobAction wraps.

The machinery is such that the inifinite loop has break statements on shutdown and should send a message to all of the monitoring worker threads to stop at shutdown.
During running the threads keep trying to re-populate themselves by emptying the global Queue which is re-populated by the main monitoring loop.

1. There appears to be no timeout forcing jobs to execute in a certain window.
I think this is the correct behaviour and wouldn't like to implement this in the monitoring loop. If a backend needs it, it can implement it itself.
2. There is no throttling of various backends. This can be set globally but not in a per-backend way.
3. There appears to be some logging which never displays :/ I have no idea how to debug this.
4. I think we could keep a lot code from the current system if we ever move to a different system to what we currently have.

**Comment by milliams** [comment]
@rob-c The first step in this is definitely trying to understand exactly how the current system works. The second step is working out, based on that, how it was originally designed (the diff between the two is the years is feature creep and misunderstood fixes). We can then start simplifying the code back to that and hopefully make use of newer Python features, modules etc to make the code easier to understand and shorter.

What would be good is to document some of the architecture of this in the [Ganga dev guide](http://ganga.readthedocs.org/en/latest/dev/index.html) that's part of the new manual.

**Comment by drmarkwslater** [comment]
I personally think a re-write may not be a bad idea. The fact that 3+ of us have now looked at this code and we're still not entirely sure what's going on is a bad sign :) I may be over simplifying it but I would have thought that all the monitoring loop needs to do is every <polltime> for each active backend, run the updateMonitoring function for that backend. Using queues as well I can't see this being more than a couple of pages of code...

Having said that, I quite possibly *have* over simplified and so we really do need to make sure we understand this completely before replacing it :)

**Comment by egede** [comment]
@milliams asked about the original intention of this code. I think it is/was as follows.
1. Create a list of all sub-jobs that should be monitored.
2. Split this list into different backends.
3. Place calls to the backend specific monitoring on a queue which a thread pool picks
    tasks from **if** previous call has finished and the time since that backend was last queued
   is above the minimal cycle time.
4. Repeat from 1.

So point 3. is obviously the tricky one. 
   * You do not want to risk that you stack up monitoring requests on the queue for a given backend.
   * You do not want to monitor too often if the loop is more or less empty. The minimal cycle time
     I think should be different for different backends (for a Local job I expect to be notified just a few
     seconds after the job has finished while for a Grid/Cloud backend even a few minutes is fine.

**Comment by rob-c** [comment]
@milliams How do we edit that?

**Comment by milliams** [comment]
@rob-c If you edit [doc/dev/index.rst](https://github.com/ganga-devs/ganga/blob/develop/doc/dev/index.rst) and then run `make html -j4` in the `doc/` directory it will create some HTML files in `doc/_build/html/dev/index.html` (it uses [Sphinx](http://www.sphinx-doc.org)). If it ends up being too much for one page, we can always split it out later.

**Comment by rob-c** [comment]
I think this can be closed for now, the conversation on the monitoring has moved elsewhere
