### ISSUE TITLE
the latest "Documentation/Full Tutorial (On Read The Docs)" severely broken

### ISSUE THREAD

**Issue by JacekHoleczek** [ganga-devs/ganga#1399]
Are you aware that the "latest" documentation is severely broken?
https://ganga.readthedocs.io/en/latest/

Accidentally, I found now the "stable" documentation which seems to be o.k..
https://ganga.readthedocs.io/en/stable/

**Comment by mesmith75** [comment]
What do you mean by "severely broken"? I can go through both of those links without issue.

**Comment by JacekHoleczek** [comment]
See, for example, some short page, like "User Guide" :  "Configuration" or "Running Executables".

**Comment by mesmith75** [comment]
So it is. Thanks for pointing it out - the paths didn't get updated when we reordered ganga.
