### ISSUE TITLE
Metadata not populated for subjobs

### ISSUE THREAD

**Issue by rmatev** [ganga-devs/ganga#140]
I have a checker that fails with 6.1.14 because the metadata per job is missing. The strange thing is that the combined metadata for the master job is there. 
```
[09:33:40]
Ganga In [1]: j=jobs[-1]

[09:33:45]
Ganga In [2]: j.subjobs[0].metadata
Ganga Out [2]: <Ganga.GPIDev.Lib.Job.MetadataDict.MetadataDict at 0x7f19501e3b10>

[09:33:59]
Ganga In [3]: j.subjobs[0].metadata.data
Ganga Out [3]: {}

[09:34:07]
Ganga In [4]: j.metadata
Ganga Out [4]:
{
     xmldatafiles = {'full': set(['LFN:/lhcb/data/2015/RAW/LUMI/LHCb/LEAD15/169504/169504_0000000088.raw', ...,  'LFN:/lhcb/data/2015/RAW/LUMI/LHCb/LEAD15/169503/169503_0000000405.raw'])}
     xmldatanumbers = {'full': 49}
     lumi = Not Available.
     events = {'output': 0, 'input': 90383787L}
     xmlskippedfiles = set([])
    }
```
On a side note, subjobs are not returned as proxy objects, so it is annoying to work interactively with them.

**Comment by rob-c** [comment]
The issue with proxies is being addressed (somewhat) in 6.1.15 there has been some further work in this area.

The metadata issue is however an LHCb bug which probably needs addressing but may be a result of the repo syncing issues in 6.1.14 so I'll check for subjobs of a 6.1.15 job in a bit,

Rob

**Comment by milliams** [comment]
I'm putting together an integration test for this but I've come across a number of broken things with subjobs which I will be fixing soon.

**Comment by rob-c** [comment]
I suspect that this has been broken for a long time but the logging has failed to display. I think you had to be using cvmfs and 6.1.14 to get it to display there for some reason which shouldn't be to blame.

**Comment by rob-c** [comment]
@milliams I suspect there may be a missing addProxy in the SubJobXMLList class which could lead to this but I don't see it from the standard tools if memory serves

**Comment by milliams** [comment]
RP #143 relates to this as the code breaks otherwise. At least in current *develop* `type(j.subjobs[0])` returns `Ganga.GPIDev.Base.Proxy.Job` so I think that's fixed.

The metadata issue still needs attention though.

**Comment by rmatev** [comment]
Hi,
Any chance you can have a look at the metadata issue for the next release? We're using a checker to make sure all input files were fully processed and the metadata is what we look at.

**Comment by egede** [comment]
Hi Rosen,

No, as explained a few days back on the distributed analysis list, the 
only focus of the next release is to restore the stability of Ganga that 
has gone lost.

But after that has been achieved, it is certainly a thing to attack.

Ulrik.

**Comment by rmatev** [comment]
ping
metadata issue is still there in 6.1.20

**Comment by rob-c** [comment]
@rmatev There is still a strong focus elsewhere (CMake support and a few different bottlenecks are being fixed over the next release or 2) I'll try and look into this after Ganga 6.2.0 is out unfortunately unless this is an obvious fix.
