### ISSUE TITLE
Problem with GenericSplitter and attribute = "application.env"

### ISSUE THREAD

**Issue by JacekHoleczek** [ganga-devs/ganga#1400]
I've got a strange problem (ganga-7.1.9).
A simple "task" which demonstrates it is ("test_exit.py"):
```
t = CoreTask()
trf = CoreTransform()
trf.application = Executable()
trf.application.exe = File('/bin/sh')
trf.application.args = ['-c', 'set; exit 0']
trf.backend = Slurm()
trf.unit_splitter = GenericSplitter()
trf.unit_splitter.attribute = 'application.env'
trf.unit_splitter.values = [ {'MYENV':'test1'}, {'MYENV':'test2'} ]
trf.abort_loop_on_submit = False
t.appendTransform( trf )
t.float = 100
t.run()
```
None of the two jobs' outputs shows "MYENV" (i.e. "MYENV" was NOT put in the environment of these jobs and so "set" does not list it), when running with the "Local" or "Slurm" backend.

(I've just checked that it does work as expected with the old ganga-6.0.44 and the "Local" and "SLURM as SGE" backends.)

**Comment by mesmith75** [comment]
This looks to be a general problem with executables rather than just the splitter.

**Comment by mesmith75** [comment]
Ha - looking at the history it dropped out of the RTHandler 4 years ago!
