### ISSUE TITLE
DEBUG log level neglected

### ISSUE THREAD

**Issue by JacekHoleczek** [ganga-devs/ganga#1410]
I've got a strange problem (ganga-7.1.9).
As there are no comments for https://github.com/ganga-devs/ganga/issues/1400 nor https://github.com/ganga-devs/ganga/issues/1401,  I wanted to have a look myself at what the "DEBUG" shows.
So, in my "\$\{HOME\}/.gangarc", I tried "Ganga = DEBUG", "GangaCore.GPIDev = DEBUG", "GangaCore.Utility.logging = DEBUG" and "_format = DEBUG" ... but the screen output and the "_logfile = ~/.ganga.log" remain almost completely empty (there are just some 10 "INFO" lines printed).

Do I need to add that it does work as expected with the old ganga-6.0.44 or do I not?

**Comment by mesmith75** [comment]
This is likely a hangover from the move to IPython 5 when the logging changed a bit.

Edit: Though `ganga --debug` still gives you the debug for every module.

**Comment by egede** [comment]
Just checked and this problem is still there. I can't change the logging level from within an interactive session neither. So

```
Ganga In [3]: config.Logging.Ganga='DEBUG'
```

has no effect.

**Comment by hedonhermdev** [comment]
Can I work on this issue?

**Comment by egede** [comment]
> Can I work on this issue?

You are welcome. It will likely take a bit of digging to figure out what the actual problem is.

**Comment by varunbankar** [comment]
Will like to take up the issue.

From exploring a bit found out that `logger.debug("test")` is not seen on the screen as well not recorded in `~/.ganga.log`

Is this the issue that needs to be solved?

**Comment by varunbankar** [comment]
@egede 
I have further dug into the issue and there seems no problem in the functionality as stated by the in first post. Please refer to the screenshot below.

<img width="1325" alt="Screenshot 2020-04-05 at 11 02 10 PM" src="https://user-images.githubusercontent.com/47035057/78505618-454fa700-7792-11ea-9f45-03a7c22e87a2.png">

Let me know what type of functionality is expected from the logger.

`--debug` options sets all the logger level to `DEBUG`. If desired we can add this functionality in the configuration and once the logger level is set to `DEBUG`, all the messages can be seen on the screen as well in `~/.ganga.log`.

**Comment by egede** [comment]
There is something wrong with the logger levels and how they are set. As an example, if I do
```
ganga -o'[Logging]Ganga=WARNING' -o'[Logging]GangaCore.Runtime.bootstrap=WARNING' -o'[Logging]GangaCore.GPIDev=WARNING' -o'[Logging]GangaCore.Utility.logging=WARNING'
```
I still get `INFO` messages when I start and quite Ganga. It seems to me that the processing of the log directives is not quite correct. If I inspect the config object inside Ganga I see that the levels are set correctly, but it is not taken into account.
