### ISSUE TITLE
Readtedocs documentation is incomplete

### ISSUE THREAD

**Issue by 97amarnathk** [ganga-devs/ganga#1417]
Hello. I am new to open source and Ganga in general.

While browsing the documentation at [ganga.readthedocs.io/en/latest](https://ganga.readthedocs.io/en/latest/UserGuide/InstallAndBasicUsage.htmll) I came across several places where it was not exactly clear what the docs was trying to explain. 

For example, in the section [Hello World with Ganga](https://ganga.readthedocs.io/en/latest/UserGuide/InstallAndBasicUsage.html) there is no mention about the very concept of Jobs itself or how to run them. 

There are numerous other such instances, where I had to run Ganga, read its codebase to understand what exactly is it all about. 

Improving the documentation will make it much easier for a new person to know about and contribute to Ganga.

**Comment by JacekHoleczek** [comment]
See: https://github.com/ganga-devs/ganga/issues/1399

I assume, the committed fixes will appear "online", once a new ganga version (i.e. 7.2.0 ) is released.

**Comment by 97amarnathk** [comment]
@JacekHoleczek , The home page of [https://ganga.web.cern.ch/ganga/](https://ganga.web.cern.ch/ganga/) still points to  [ ganga.readthedocs.io/en/latest](ganga.readthedocs.io/en/latest)

Shouldn't the "latest" documentation be corrected ? Since its the one seen by people visiting the Ganga website.

**Comment by mesmith75** [comment]
The person responsible for the read the docs has long stopped working on ganga. I am waiting for him to add me to the maintainers. @milliams @drmarkwslater

**Comment by 97amarnathk** [comment]
Also in the code base, `ganga/GangaTutorial` contains a hands on tutorial. But there is no mention about this in the docs.
