### ISSUE TITLE
heartbeat and jobstatus files' enhancement proposal

### ISSUE THREAD

**Issue by JacekHoleczek** [ganga-devs/ganga#1425]
I have met a strange problem on a SLURM cluster. For completely unknown reasons, some jobs (out of many hundreds) instead of running at "full speed" are getting something like 17% CPU "job efficiency" (well, jobs which should end in less than 10h are running for 65h and more and SLURM doesn't allow me to login to the batch node and "inspect" what really happens).

So, here's my proposal ...

1. Ganga automatically creates the "heartbeat file". Currently it simply prints a "." character every 30s. Maybe we could print the actual real job's "CPU usage". One could use a very simple "two characters" encoding. Small values (up to 99%) one could directly "encode" as two decimal digits (0% = 00, 1% = 01 to 99% = 99). Bigger values would always be divided by a factor of 10 and then "encoded" as 100%-109% = A0, 110%-119% = A1 to 190%-199% = A9, 200%-209% = B0, 210%-219% = B1 to 290%-299% = B9, 300%-309% = C0, 310%-319% = C1 to 390%-399% = C9 and so on, up to 2690%-2699% = Z9 (any higher value could be "encoded" as ZZ but, have you ever seen that high "CPU usage"?).

2. Ganga automatically creates the "jobstatus file". Maybe we could add there two lines: one line with the "average CPU usage" for the job and another line with the "average RAM usage" (both values could be "collected" every 30s when the "heartbeat file" gets updated)? Actually, in both cases, maybe we could print three values "min. / average / max.".

**Comment by mesmith75** [comment]
Sounds reasonable. I think Condor already does this.

**Comment by mesmith75** [comment]
I think this is actually rather tricky. This is the kind of information that is normally collected by the job scheduler no?

The wrapper script runs as a python script that then spawns a new process that runs your actual task - I don't think it is then so straightforward to collect the resource usage of just your task.

**Comment by mesmith75** [comment]
You can stick anything you like in https://github.com/ganga-devs/ganga/blob/595fbebae8affe003e82a0c2072fe88b6f0ec701/ganga/GangaCore/Lib/Batch/BatchScriptTemplate.py.template#L108 but whether you can put anything meaningful in there is debatable.

**Comment by JacekHoleczek** [comment]
Yes, that's the place that I was thinking about, too. I just hoped that you know some magic python function which returns the total cpu usage (of this script and all child processes), averaged over the last 30 seconds (actually, over the "heartbeat_frequency" time).

**Comment by mesmith75** [comment]
From my googling I am not sure it is possible with standard python.

**Comment by egede** [comment]
The different processes in a given batch job will all be part of the same process group. You could then use the `psutil` package, see https://psutil.readthedocs.io/en/latest/. Would require some effort to get to work though and it is not obvious to me that there is a huge benefit.

**Comment by mesmith75** [comment]
I don't think you can rely on `psutil` being available on the WN as it is not in the standard library.

**Comment by mesmith75** [comment]
Closing this as unfeasible.

**Comment by JacekHoleczek** [comment]
Well, can we safely assume that all WN are Unix-like and have `/proc/<pid>/stat`?
If yes, there's an example:
https://codereview.stackexchange.com/questions/67904/calculate-cpu-by-process-from-proc-stat-and-proc-pid-stat

**Comment by egede** [comment]
Seems like we try to solve an individual problem by making changes to Ganga overall. Is it not better in this instance just to implement a wrapper script that provides a similar functionality for a specific job. The script mentioned above will probably more or less do.
