### ISSUE TITLE
DiracFile with inputfiles deleted too early

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1426]
If the following is executed

```
j.prepare()
j.submit()

:
Wait some days
:
j2 = j.copy()
j2.submit()
j.remove()
```
the job `j2` will fail as the `j.remove` deleted the uploaded sandbox. The logic for deleting uploaded sandboxes should be the same as for deleting them in the shared area.

**Comment by mesmith75** [comment]
Looks like a problem with the sharedir counting again...
