### ISSUE TITLE
Automatic expansion of all environment variables used in ".gangarc" (an enhancement proposal)

### ISSUE THREAD

**Issue by JacekHoleczek** [ganga-devs/ganga#1449]
I want to use environment variables in MassStorageFile and SharedFile "path" settings (in the ".gangarc" file).
Something like: `MassStorageFile = {..., 'uploadOptions': {'path': '${VAR1}/${VAR2}', ...}, ...}`
This does not work with the current ganga (7.1.12).
I have found that a trivial fix works (I tested it with a SharedFile).
In the `ganga/GangaCore/GPIDev/Lib/File/MassStorageFile.py` file, in two places (in lines 284 and 437), one needs to replace `massStorageConfig['path']` with `os.path.expanduser(os.path.expandvars(massStorageConfig['path']))`.
If you accept this proposal, I can prepare the pull request.

**Comment by egede** [comment]
Yes, that sounds like a good idea. We already do a similar thing for the location of the `gangadir` `GangaCore/Runtime/bootstrap.py`. Can I please request that he pull request is made on a branch based on the latest version of the `develop` branch.

**Comment by JacekHoleczek** [comment]
Now part of https://github.com/ganga-devs/ganga/pull/1451

**Comment by JacekHoleczek** [comment]
Could you maybe think of a general solution for all settings?
When the config file is parsed (at startup), maybe one could expand all variables in all entries?
The `os.path.expandvars` should work fine in all cases, so it could be applied to all. The `os.path.expanduser` might be a bit fragile so one would have to test it (either it works fine in all cases or one could leave it out and warn users not to use `~` and `~user`).
It seems to me that one would simply need to modify the `load_config_files` routine in the `ganga/GangaCore/Utility/Config/__init__.py` file or maybe the `read_ini_files` routine in the `ganga/GangaCore/Utility/Config/Config.py` file (but I did not play with it).
Actually, maybe one just needs to use `return os.path.expanduser(os.path.expandvars(v))` in the `expandgangasystemvars` routine in the `ganga/GangaCore/Utility/Config/__init__.py` file.

**Comment by mesmith75** [comment]
So this can already happen on a per option basis. One just sets `filter ==GangaCore.Utility.Config.expandvars ` when adding the option.

I am not sure we want to automatically do this for every config option - there may be times where we don't want to automatically expand variables.

**Comment by JacekHoleczek** [comment]
I've been thinking about it, too. If one uses `${SOM_VAR}` then it will be expanded but, if one uses `\${SOME_VAR}` or `\\${SOME_VAR}` then it will not be (actually, the initial automatic "expansion" could also "strip" all `\` characters so that any successive / following call would simply see `${SOME_VAR}`).

**Comment by egede** [comment]
Marked as won't fix. See last comment by Mark.
