### ISSUE TITLE
Change the way LHCb User Environment is prepared

### ISSUE THREAD

**Issue by pikacic** [ganga-devs/ganga#1461]
Ganga prefixes every command with
```
export CMTCONFIG=%s; source LbLogin.sh --cmtconfig=%s && 
```
which is (to say the least) redundant, because `source LbLogin.sh --cmtconfig=%s` would be enough.

In any case, LHCb will soon decommission `LbLogin.sh` so it must be replaced with something else (what exactly has to bee coordinated between Ganga developers and LHCb Core Software).

Note that I only had a look at `GaudiExec` so I cannot really much about other places.

**Comment by egede** [comment]
Where is the best place to read up on the required changes? And what time constraint do we have?

**Comment by mesmith75** [comment]
Fixed by #1462
