### ISSUE TITLE
Maybe add abort option to exit()

### ISSUE THREAD

**Issue by jheuel** [ganga-devs/ganga#1469]
When trying to quit the ganga shell with `exit()` I am sometimes told that some tasks are still running and asked if I want to force the exit. Would it be possible to add an "abort" option to this dialog? It would be useful to be able to continue using the shell.

**Comment by mesmith75** [comment]
I don't quite follow. Do you want to abort the exit to keep using ganga, or force ganga to quit quickly?

**Comment by egede** [comment]
I am not sure if aborting the exit (and returning to the Ganga prompt) is possible. My feeling is that several tasks has already been carried out that are not really reversible.

**Comment by jheuel** [comment]
@mesmith75 I meant an option to abort the exit and keep using ganga

I thought that ganga did first check if it can be closed before taking any action. You can close this issue if it is not straight forward to implement it.

**Comment by mesmith75** [comment]
I don't think this is readily feasible so I'll close this for now.
