### ISSUE TITLE
Undefined variable in job class

### ISSUE THREAD

**Issue by alexanderrichards** [ganga-devs/ganga#1472]
While doing the 2 to  3 conversion...
https://github.com/ganga-devs/ganga/blob/1547fa1d73b1e29d09ee4a7708f411e7a7e518f2/ganga/GangaCore/GPIDev/Lib/Job/Job.py#L2182

here variable `do_not_copy` appears undefined unless I'm missing something?

**Comment by mesmith75** [comment]
You are correct, there is a missing import.

**Comment by alexanderrichards** [comment]
so the next question is given that this has never been spotted and seemingly not noticed by users, is this a bit of code that we are actually not using? (i.e. deletion candidate)

**Comment by mesmith75** [comment]
That is a good question. This is essentially a copy of the base object copy method but with some things stripped out to make it quicker. I am not sure why it doesn't matter here but would for objects in general.
