### ISSUE TITLE
Status of master job left in "submitting" when some subjobs fail to submit.

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1479]
If some subjobs fail to submit (error from the batch system), then they are left in the new state. If I then individually call submit on those subjobs, they start OK, but the master job is left in the "submitting" state and therefore will not do any monitoring. Restarting Ganga doesn't help - the only remedy is to do `j._impl.status='submitted'` which is not a solution.

**Comment by mesmith75** [comment]
What do we want to happen?

If the submission fails for a subjob then the master should end up in `new`. I think that should preclude then submitting the individual subjobs by hand.

**Comment by egede** [comment]
It is very convenient that jobs that failed the submission can just be submitted individually. I would expect that the master job status would be derived from the subjobs and thus go into the `submitted` state.

**Comment by dilawari2008** [comment]
Hi
I am Vagish and I would like to contribute to Ganga.
As far as I have understood this issue, the master job is unable to derive the status of the subjob and thereby modify its status.
I tried this also. I made a submitted subjob to fail explicitly, but the master job had its status submitted(which I expect should have become failed).
I guess the output which is required is that if any modification is made in the status of any subjob, it should affect the status of the masterjob.
I would like to solve this issue. Can someone tell me which classes/files to begin searching in. I want to modify the functionality of the function trying to access the current status of the subjob and link it to the master job.

**Comment by dilawari2008** [comment]
Hi
I am Vagish and I would like to contribute to Ganga.
As far as I have understood this issue, the master job is unable to derive the status of the subjobs and thereby modify its status.
I tried this also.
First I created a job and split it into 3 subjobs. The status of these subjobs was new and I explicitly made the master to status='submitting'
now when I submitted each individual subjob as j.subjobs(0).submit(), the status of the master job changed to submitted automatically. So it seems to be working just fine.
Can I get a little more insight as to what is the issue?

**Comment by egede** [comment]
Hello,

A bit more investigation is required on this issue to see if there indeed is a problem or not. I do not think your testing quite explore the problem.

- Create a job with a few subjobs
- Call `j.submit()` but ensure that one of the subjobs is failing the submit (by raising a `JobError`)
- Now investigate the status of the master job (is it in `submitting` or in `new`?)
- Try to submit the subjob that should now succeed.
- Investigate if the master job is automatically moving into the submitted state.

The easiest way to do this might be by one of the Batch backends, where you in the `.gangarc` configuration file can set which commands it should use for submission. You can then just make something that succeeds/fails according to some pattern.

**Comment by egede** [comment]
@dilawari2008  If interest is in connection with GSoC https://hepsoftwarefoundation.org/gsoc/projects/2020/project_Ganga.html, then please contact me by using the information on the mentor part of the individual projects.

**Comment by egede** [comment]
Looking at recent error reports, there is no issue here.
