### ISSUE TITLE
Misbehaving logger

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1495]
Message taken from #1470 by @JacekHoleczek 

Now, when the "high CPU usage" problem is confirmed, I would like to return to another problems that I reported here.

I think I can live with the misbehaving logger. Under normal conditions, the amount of "screen output" is not that big (just the usual messages about jobs being submitted and completed) so, I think I can enforce _interactive_cache = False (note: --very-quiet is not an option, I really want to see what happens).

However, I would really like to get the misbehaving ganga prompt fixed (pressing any key destroys the last printed "INFO" line, or maybe even two lines). It seems to me that the origin of this problem is that the prompt uses two lines. I haven't found any option in the ".gangarc" file to (re)define my own prompt (e.g. I could imagine having a one line "[HH:MM:SS] In [...]:" prompt).

**Comment by mesmith75** [comment]
To some extent this is out of our hands - it is up to what IPython does.

**Comment by JacekHoleczek** [comment]
So, the "misbehaving logger" problem started in the https://github.com/ganga-devs/ganga/issues/1453 thread for the ganga 7.1.12 version. But I used this version for a short time only as a test (my "production version" was 6.0.44). I then switched to ganga 7.1.14 and you can see my full report in point 4. of [my first post](https://github.com/ganga-devs/ganga/issues/1470#issue-448467697) in the https://github.com/ganga-devs/ganga/issues/1470 thread and then also some additional notes in [my second post](https://github.com/ganga-devs/ganga/issues/1470#issuecomment-496496005) there.

Note that the "prompt" problem is related but I guess it is a separate issue.

**Comment by mesmith75** [comment]
So I don't really follow this. What exactly do we want to happen?

Currently any `INFO` messages are cached (up to 1000kB). They are then printed to the screen when the IPython cell next executes something (or the cache fills up if that is sooner). This is so you can write your code without `INFO` messages appearing.

Any `WARNING` or higher messages are always printed as soon as they occur.

Is this not what we want? If it is not, what exactly do we want?

Note that we don't print the messages relating to subjobs any more as a deliberate choice - only the master job. It is not ideal to have a print out for several thousand subjobs changing state from `new` to `submitted` to `running` etc.
