### ISSUE TITLE
Excessive CPU usage of Ganga when idle

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1496]
So I am getting some understanding of this. I managed to get the profiling to work for all threads and I looked at a simple Ganga session that does absolutely nothing. That takes up 20% of CPU time, by just keeping the threads alive. Look at tables below.

First just CPU time used.

```
Tue Aug  6 09:04:44 2019    pstats

         3025011165 function calls (3045501047 primitive calls) in 18608.766 seconds

   Ordered by: internal time
   List reduced from 2552 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
111672296/111672382 5302.618    0.000 5302.619    0.000 time:0(sleep)
15955981/15956009 3455.435    0.000 10966.966    0.001 threading.py:309(_Condition.wait)
203432054/203432055 1564.325    0.000 1564.325    0.000 __builtin__:0(<method 'acquire' of 'thread.lock' objects>)
13893115/13893158  623.255    0.000 10083.479    0.001 Queue.py:150(PriorityQueue.get)
178002954  485.361    0.000  485.361    0.000 time:0(time)
101874671  463.914    0.000  463.914    0.000 __builtin__:0(min)
 24576283  446.015    0.000  731.661    0.000 threading.py:147(_RLock.acquire)
 20650850  429.269    0.000 1753.586    0.000 GangaThread.py:10(GangaThread.decorated)
35396110/54437560  394.032    0.000  916.908    0.000 lexer.py:616(Python3TracebackLexer.get_tokens_unprocessed)
 24576282  357.426    0.000  523.322    0.000 threading.py:187(_RLock.release)
366362488  283.677    0.000  283.677    0.000 __builtin__:0(<method 'match' of '_sre.SRE_Pattern' objects>)
 67826741  202.180    0.000  202.180    0.000 threading.py:64(_RLock._note)
  4249734  186.170    0.000 1303.766    0.000 html.py:738(HtmlFormatter._format_lines)
```

and now who is calling the first ones in the table above

```
pstats% callers
   Ordered by: internal time

Function                                                                          was called by...
                                                                                      ncalls  tottime  cumtime
time:0(sleep)                                                                     <- 2109382/2109379  115.992  115.992  Registry.py:254(RegistryFlusher.run)
                                                                                   932748/932747   50.326   50.326  SessionLock.py:114(SessionLockRefresher.run)
                                                                                   6755424/6755423  344.783  344.784  TaskRegistry.py:57(TaskRegistry._thread_main)
                                                                                   13709/13708    0.757    0.757  stacktracer.py:90(TraceDumper.run)
                                                                                   101861067/101861039 4790.758 4790.760  threading.py:309(_Condition.wait)
                                                                                        52/0    0.002    0.002  time:0(sleep)
threading.py:309(_Condition.wait)                                                 <- 1356775/1356774  297.449  862.149  Local_GangaMC_Service.py:571(JobRegistry_Monitor.run)
                                                                                   13893158/13893142 2832.294 8983.367  Queue.py:150(PriorityQueue.get)
                                                                                   705964/705959  325.688 1121.431  Queue.py:150(Queue.get)
                                                                                         3/0    0.000    0.001  threading.py:309(_Condition.wait)
                                                                                     107/106    0.003    0.019  threading.py:600(_Event.wait)
                                                                                         2/0    0.000    0.000  time:0(sleep)
__builtin__:0(<method 'acquire' of 'thread.lock' objects>)                        <-    2262    0.004    0.004  Queue.py:86(Queue.qsize)
                                                                                        2262    0.003    0.003  Queue.py:107(Queue.put)
                                                                                    13893158  115.596  115.596  Queue.py:150(PriorityQueue.get)
                                                                                      705963    4.861    4.861  Queue.py:150(Queue.get)
                                                                                    24495405  147.286  147.286  threading.py:147(_RLock.acquire)
                                                                                     1356777    6.821    6.821  threading.py:220(_RLock._acquire_restore)
                                                                                    14599213  119.928  119.928  threading.py:297(_Condition._acquire_restore)
                                                                                    14603840  112.348  112.348  threading.py:300(_Condition._is_owned)
                                                                                   133773055/133773054 1057.476 1057.476  threading.py:309(_Condition.wait)
                                                                                          81    0.001    0.001  threading.py:860(Thread.__stop)
                                                                                          39    0.000    0.000  time:0(sleep)
Queue.py:150(PriorityQueue.get)                                                   <-    27/0    0.000    0.006  Queue.py:150(PriorityQueue.get)
                                                                                   13893125/13893115  623.255 10083.479  WorkerThreadPool.py:61(WorkerThreadPool.__worker_thread)
                                                                                         6/0    0.000    0.001  threading.py:309(_Condition.wait)
```

So I see that the monitoring thread in the tasks `TaskRegistry.py:57(TaskRegistry._thread_main)` is one of the sinners but that the main problem is coming from `Queue.py:150(PriorityQueue.get)` 

It turns out that this is a known issue, see http://blog.codedstructure.net/2011/02/concurrent-queueget-with-timeouts-eats.html. Ganga indeed has a huge number of these `queue.get` calls with a timeout (it is how we figure out if the threads should stop or not. This is all related to CPU activity when Ganga is idle. Seems a good place to start though.

_Originally posted by @egede in https://github.com/ganga-devs/ganga/issues/1470#issuecomment-518441414_

**Comment by egede** [comment]
An idea to look into is to change the way Ganga works such that we can avoid calls to the thread queue with a timeout. The "poison pill" idea discussed in the blog referenced above might be the way to go.

**Comment by egede** [comment]
@JacekHoleczek Please comment on the CPU when idle issue here and not in the meandering issue which it arose from.

**Comment by egede** [comment]
Above tests were done in python2.

Running the same profiling in the python3 branch gives less information. I am not sure why. However, the idle ganga session is still using high CPU, even when there is nothing to monitor. Running strace -f on the process reveals a huge number of calls of the type
```
[pid 30903] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=136, tv_nsec=346691436}) = 0
```
which to me looks like almost the same problem. I thought about as a test to make all the threads blocking. This should still leave Ganga working but it will be unable to shut down cleanly. OK for testing.

**Comment by egede** [comment]
To make progress on this I suggest

1. Create a branch based on `develop`. This will still be python 2.7 where we have the better debugging information.
2. Install `yappi` with `pip install yappi`
3. Modify https://github.com/ganga-devs/ganga/blob/develop/bin/ganga to start and report on the profiling.
```
import yappi
:
: 
try:
    # Import GPI and run Ganga
    yappi.set_clock_type("cpu")
    yappi.start(builtins=True, profile_threads=True)
    GangaCore.Runtime.setupGanga()
    from GangaCore import GPI
    GangaCore.Runtime._prog.run(GPI.__dict__)
    yappi.get_func_stats().print_all()
    yappi.get_func_stats().save("pstats","pstat")
    yappi.get_thread_stats().print_all()
```
4. While running ganga interactively, look at if you see significant CPU usage (just use `top` in a terminal for this). Leave it to run for some minutes to get some data for the profiling. When quitting `ganga` a file called `pstats` is produced (from the `save` call above). You can analyse that file with `python -m pstats pstats`, When inside the `pstats` programme just type `help`. I find something like
```
strip
sort time
stats 20
```
useful.
5. Try to modify the calls to the thread queue such that they are blocking instead (just remove the timeout argument). I see a call in https://github.com/ganga-devs/ganga/blob/d4fa1cce3cf5d4d8d8a3fdc990cfdf1d82b41ef4/ganga/GangaCore/Core/GangaThread/WorkerThreads/WorkerThreadPool.py#L79 but you might have to search the code for other similar calls. 
6. Report back the results!

**Comment by sriram-sb** [comment]
Hi all,
I'm very sorry about not being able to get back to this sooner. University is starting up soon and tying up the loose ends beforehand took longer than intended. I've already completed up to step 4 in the comment above, and intend to report the results back within the next 1-2 days. Sorry for the delay.

**Comment by sriram-sb** [comment]
@egede Hi Professor:

Ganga does, like you noted, seem to be taking a significant amount of cpu on idle - `top` reports that it takes anywhere from about 16 - 25% of the cpu on idle. This is what I see when I run those commands on the `pstats` tool, I get [this](https://hastebin.com/isaruriqov.js).

When I try removing the timeout on the `item = self.__queue.get(True, 0.05)` as you suggested above I get the odd result that instead the Python process running Ganga starts taking up anywhere from 33% to 51% of the CPU on idle. The top 20 results of the `pstats` file in this case can be found [here](https://hastebin.com/edojenulor.js)

Based on a comment in the code regarding waiting 0.05 seconds, it's probably because the shutdown function never gets a chance to be called, which would explain the increase in CPU usage.

The article about consecutive Queue.get() calls with timeouts was an interesting read, but I'm unfortunately not yet familiar enough with the Ganga codebase to figure out where we could put a change like that. So how do you suggest we should do proceed?

**Comment by egede** [comment]
The two different outputs from `pstats` look almost identical to me. So my feeling is that we do not understand what is going on. It is possible to get `pstats` to report on who made the different function calls (so who was it that made the call to `sleep` etc. Can you try to look into this. I wonder if we are looking at the wrong piece of code somehow.

**Comment by egede** [comment]
We discussed this issue in todays weekly operational meeting. The suggestion coming up was to try to understand if the excessive CPU usage that we see is due to a fundamental problem with python threads or if it is due to the way that we use them in Ganga. 

So the proposal is to create a standalone python programme for testing. It should simply start a large number of worker threads and then them them ask for work from a priority queue. We are then interested in looking at the CPU consumption if the threads are idle (so there is nothing to do in the queue. The example code from the `queue` documentation should be a good starting point. I have added a few comment lines with a `#ue`

```
def worker():
    while True:
       #ue You might want to play around with if this q.get call is blocking or not.
        item = q.get()
        if item is None:
            break
        do_work(item)
        q.task_done()

q = queue.Queue()
threads = []
# So maybe study behaviour as function of number of threads. Try anything between 1 and 100
for i in range(num_worker_threads):
    t = threading.Thread(target=worker)
    t.start()
    threads.append(t)

# ue So you want to add nothing to the queue as we study the behaviour of an empty queue
for item in source():
    q.put(item)

# block until all tasks are done
# Here you probably just want to sleep for a while as you want to take measurements.
q.join()

# stop workers
for i in range(num_worker_threads):
    q.put(None)
for t in threads:
    t.join()
```
Example is taken from https://docs.python.org/3/library/queue.html

**Comment by ishanrai05** [comment]
Increasing the timeout to something larger should decrease the CPU usage but it will also decrease the responsiveness. I have made a PR that allows user to set timeout according to their machine. Ideally one should aim for timeout time that balances CPU usage and responsiveness.

A better solution would be to have a separate thread that periodically checks the process and informs the queue if it dies. although this would require some major changes.
