### ISSUE TITLE
Migrate Dockerfile's to python3

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1500]
The Dockerfile's used for the Jenkins testing should be upgraded to install python3.

**Comment by egede** [comment]
https://monovm.com/blog/how-to-install-python-3-on-centos-7/ might be the best way to install python3 on a plain centos7 machine.

**Comment by JacekHoleczek** [comment]
The "community approved" [EPEL](https://wiki.centos.org/AdditionalResources/Repositories) repository provides the "python36" package (python 3.6.8) plus many dependent ones.
There is also the older "python34" package (python 3.4.10) plus its dependent packages.
There are also some "\*python3\-\*" packages which do not depend on the exact version.
Also, the "additional CentOS provided" [SCL](https://wiki.centos.org/AdditionalResources/Repositories) repository provides some python 3.3, 3.4, 3.5 and 3.6 versions.
Try: `yum list "*python3*"`

**Comment by mesmith75** [comment]
Can we close this?
