### ISSUE TITLE
Ganga process suspended for LHCb users

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1504]
In the past few weeks, LHCb users have observed that the Ganga process gets suspended. It can then be restarted with foregrounding the process. Below is an analysis by Chris Burr

```
Hi Ulrik,

I've had a look and it think it's related to leaking file handles to subprocesses which then close the stdin pipe and disconnect the process.

For me it only happens on launch if I have a proxy and seems to happen when the background call to lhcb-proxy-info exits. I've also seen it happen when calling gridProxy.renew():

Ganga In [2]: gridProxy.renew()
Generating proxy...

Your certificate will expire in 26 days. Please renew it!


[1]+  Stopped                 ganga
bash-4.2$ fg
ganga
Enter Certificate password:

I can reproduce independently of lhcb-proxy-info in various ways such as this:

import subprocess, os, signal
for i in range(1000):
     process = subprocess.Popen(['/bin/sh', '-c', 'ls > /dev/null 2>&1'], shell=True)
     os.kill(process.pid, signal.SIGKILL)

This reproducer isn't reliable but if you run enough loops of that it stops eventually. Replacing ls with voms-proxy-info makes it much more reliable but I haven't figured out why.

I can fix launching ganga by modifying the lhcb-proxy-init wrapper to prevent the stdin pipe from being inherited by the child process with this patch:

diff --git a/tmp/cburr/bin/lhcb-proxy-info b/tmp/cburr/bin-fixed/lhcb-proxy-info
index eb579c1..c503c47 100755
--- a/tmp/cburr/bin/lhcb-proxy-info
+++ b/tmp/cburr/bin-fixed/lhcb-proxy-info
@@ -18,7 +18,8 @@ while i < len(sys.argv):
     arguments = arguments + " " +sys.argv[i]
   i = i + 1

-s = subprocess.Popen(arguments, stdin=sys.stdin, shell=True, env=dict(os.environ))
-s.communicate()
+with open(os.devnull, 'w') as devnull:
+    s = subprocess.Popen(arguments, stdin=devnull, shell=True, env=dict(os.environ))
+    s.communicate()

I think the "correct" fix is that subprocesses in background threads should never inherit stdin.

Cheers,

Chris
```

**Comment by egede** [comment]
I can reproduce the problem on my local machine by limiting the number of available file descriptors (using `ulimit -n 32`). This might explain why the problem tends to show up on resource limited machines. For the problematic implementation of the `lhcb-proxy` commands, the following should be a work-around that can be tested.

```
ganga -o'[DIRAC]proxyInitCmd=/cvmfs/lhcb.cern.ch/lib/lhcb/LHCBDIRAC/pro/scripts/lhcb-proxy-init' -o'[DIRAC]proxyInfoCmd=/cvmfs/lhcb.cern.ch/lib/lhcb/LHCBDIRAC/pro/scripts/dirac-proxy-info'
```

**Comment by mesmith75** [comment]
So this is an LbScripts issue? Odd that it hasn't affected me on SLC6.

Do we have similar problems with our subprocesses?

**Comment by chrisburr** [comment]
I don't think it's a LbScripts issue as I can reproduce a similar problem using `voms-proxy-info` directly or even `ls`. In my opinion it's an issue with Ganga that stdin is shared with processes running in background threads. I don't think there is a use case for it and it's cause other issues in the past https://github.com/ganga-devs/ganga/issues/1215.

**Comment by egede** [comment]
@chrisburr Thanks for the comments. I think I actually understand the issue now. There is a short term fix for lhcb-proxy-info and lhcb-proxy-init, (which I have asked for). There is then a longer term issue to solve for Ganga which I will create a new issue for.

**Comment by chrisburr** [comment]
I've discussed with Marco Clemencic and he's happy for me to hotfix `lhcb-proxy-info` in LbScripts on CVMFS to use my devnull patch. I'll do this now (EDIT: I'm waiting for the Stratum 0 to become available so it'll be done "soon").

I won't change `lhcb-proxy-init` as it needs stdin to enter the users password and therefore doesn't get used in the background?

**Comment by egede** [comment]
@mesmith75 What happens when the monitoring loop requires a proxy for a Dirac job? Does it silently refrain from monitoring, give a warning or do we request it from the background thread?

**Comment by mesmith75** [comment]
I think it gives a warning or info about a missing credential and doesn't monitor the job.

**Comment by chrisburr** [comment]
Hotfix applied and it no longer seems to happen on the lxplus node I tested. It might take a while to propagate everywhere.

https://lblogbook.cern.ch/Core+Software+processes+and+tools/275

**Comment by egede** [comment]
Thanks. I will close this as there is a separate issue on fixing this in general.
