### ISSUE TITLE
Make stdin=devnull for all subprocess calls in background threads.

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1505]
To avoid trouble with stdin getting closed by a subprocess,, we should have stdin=devnull for any subprocess started from a background thread. See #1504 for some details.

**Comment by egede** [comment]
As the background threads quite often get functions simply passed to them, it is not trivial how this should be implemented. Think of (contrived) code like

```
queues.add(gridProxy.create)
```
In this case we will have to ensure that `/dev/null` is passed as stdin for the eventual subprocess that is started. It seems like we in the methods that use subprocess we can detect if we are in the main thread. If not, we will redirect stdin. See https://docs.python.org/3.4/library/threading.html#threading.main_thread

**Comment by chrisburr** [comment]
Now that Ganga has stopped using `LbScripts` https://github.com/ganga-devs/ganga/issues/1504 is back. There isn't an equivalent of my hack that can be applied to `LbEnv` so this needs to be fixed properly.
