### ISSUE TITLE
Selecting on status produces warning

### ISSUE THREAD

**Issue by mjmottram** [ganga-devs/ganga#152]
When running jobs.select(status='blah') https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/GPIDev/Lib/Registry/RegistrySlice.py#L137 produces an error (although the selection is still successful) that is confusing for users.

**Comment by rob-c** [comment]
@mjmottram Thanks for tracking down the line. This just needs an additional boolean of True to be passed as a second parameter to silence this from a user perspective.
