### ISSUE TITLE
Add execfile to the GPI

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1523]
Unfortunately `execfile` is no longer there in python 3. We should try and add an equivalent to the GPI as it was useful.

**Comment by egede** [comment]
Is `%run` from the iPython magic a good enough replacement?

**Comment by egede** [comment]
As this is part of basic python, I think it is a bad idea to put a replacement in the GPI. For interactive use, the `%run` magic seems the best.
It seems like it was removed as it by the python designers was considered bad practise due to the way that it executes code inside the current namespace. In scripts, it can be replaced with

```
import runpy
file_globals = runpy.run_path("file.py")
```
where the name space for executing the code is isolated. I guess for Gangam we often want he shared namespace though ...

**Comment by mesmith75** [comment]
Yes it was useful because it ran in the ganga namespace which %run does not.

**Comment by alexanderrichards** [comment]
however `runpy.run_path` will act like exec in that you can pass the current namespace into `init_globals` and it returns the namespace after running the file which can then be merged with current namespace either selectively (for security) or entirely using the dict.update method

**Comment by alexanderrichards** [comment]
> It seems like it was removed as it by the python designers was considered bad practise due to the way that it executes code inside the current namespace

Whilst this was the default behaviour I think we already used it like the new `runpy` module in that we passed in a copy of the namespace and repopulated it afterwards. In this case the switch to runpy should be seamless

**Comment by mesmith75** [comment]
Ah that seems like a reasonable solution. I think it would be a nice if we added it as a helper function for users.

**Comment by egede** [comment]
Yes, I agree. Would be good to make the name reflect what it wraps.

**Comment by hedonhermdev** [comment]
Hello, I would like to work on this issue. Am I supposed to add the function to ganga.GangaCore.Runtime.GPIFunctions? Also is `runfile()` a good name?

**Comment by mesmith75** [comment]
That sounds great!
I am not sure where exactly it should go. It needs to have access to everything in the Ganga namespace.
`runfile` sounds fine.
