### ISSUE TITLE
Excessive startup warnings/info for non LCG/LHCb environment

### ISSUE THREAD

**Issue by alexanderrichards** [ganga-devs/ganga#153]
I see the following when starting ganga in a python 2.7.10 virtual env

```python
*** Welcome to Ganga ***
Version: 6.1.14
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


Ganga.Utility.Config               : INFO     reading config file /home/hep/arichard/git/ganga/python/
Ganga.Utility.Config               : WARNING  Exception reading config file [Errno 21] Is a directory: '/home/hep/arichard/git/ganga/python/'
Ganga.Utility.Config               : INFO     reading config file /home/hep/arichard/.gangarc
Ganga.Utility                      : WARNING  Configuration of GLITE for LCG:
Ganga.Utility                      : WARNING  File not found: /afs/cern.ch/sw/ganga/install/config/grid_env_auto.sh
Ganga.Utility                      : WARNING  Configuration of GLITE for LCG:
Ganga.Utility                      : WARNING  File not found: /afs/cern.ch/sw/ganga/install/config/grid_env_auto.sh
Ganga.Lib.LCG                      : WARNING  LCG-GLITE UI has not been configured. The plugin has been disabled.
Ganga.Core.GangaRepository         : WARNING  XML File: /home/hep/arichard/gangadir/repository/arichard/LocalXML/6.0/jobs/0xxx/5/data missing, recovering from backup, some changes may have been lost!
Ganga.Utility                      : WARNING  command dirac-proxy-info -path not found
Ganga.Utility                      : WARNING  command dirac-proxy-info not found
Ganga.GPIDev.Credentials           : WARNING  Command 'dirac-proxy-info' not found
Ganga.GPIDev.Credentials           : WARNING  Unable to obtain information on Grid proxy
Ganga.Utility                      : WARNING  command dirac-proxy-info -path not found
Ganga.Utility                      : WARNING  command dirac-proxy-info not found
Ganga.GPIDev.Credentials           : WARNING  Command 'dirac-proxy-info' not found
Ganga.GPIDev.Credentials           : WARNING  Unable to obtain information on Grid proxy
Ganga.Utility                      : WARNING  command dirac-proxy-info -path not found
Ganga.Utility                      : WARNING  command dirac-proxy-info not found
Ganga.GPIDev.Credentials           : WARNING  Command 'dirac-proxy-info' not found
Ganga.GPIDev.Credentials           : WARNING  Unable to obtain information on Grid proxy
Ganga.GPIDev.Credentials           : WARNING  Grid proxy will expire in !
Ganga.GPIDev.Credentials           : WARNING  Renew by typing 'gridProxy.renew()' at the prompt.
Ganga.Utility                      : WARNING  command dirac-proxy-info -path not found
Ganga.Utility                      : WARNING  command dirac-proxy-info not found
Ganga.GPIDev.Credentials           : WARNING  Command 'dirac-proxy-info' not found
Ganga.GPIDev.Credentials           : WARNING  Unable to obtain information on Grid proxy
Ganga.Core.MonitoringComponent     : ERROR    Problem in the monitoring loop: GridProxy checking failed!
Ganga.Core.MonitoringComponent     : INFO     Further error messages from GridProxy handler in the monitoring loop will be skipped.
/home/hep/arichard/git/ganga/gangaenv2.7.10/lib/python2.7/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
```

**Comment by milliams** [comment]
There are two issues here. Firstly is the:
```
INFO     reading config file /home/hep/arichard/git/ganga/python/
WARNING  Exception reading config file [Errno 21] Is a directory: '/home/hep/arichard/git/ganga/python/'
```
which is perhaps a `GANGA_SITE_CONFIG_AREA` problem.

Secondly is the many warning about the GLite and Dirac UIs being missing. For the latter I would much prefer to defer this error until the LCG backend is used. The `proxy-info` warnings will be fixed by my credentials branch.

**Comment by alexanderrichards** [comment]
so regarding the trying to read the config from the directory I have tracked this down to the following line:
[Ganga.Runtime.bootstrap.py:628](https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/Runtime/bootstrap.py#L628)

where we have:

```python
        # all relative names in the path are resolved wrt the _gangaPythonPath
        # the list order is reversed so that A:B maintains the typical path precedence: A overrides B
        # because the user config file is put at the end it always may override
        # everything else
        config_files = Ganga.Utility.Config.expandConfigPath(self.options.config_path, _gangaPythonPath)
        config_files.reverse()
```

It's been a while since I've looked at the bootstrap code but to me this looks like it's doing the wrong thing, namely filling what should be a list of *files* with a list of *directories*.

perhaps this call to `Ganga.Utility.Config.expandConfigPath` was supposed to instead populate the config_path variable?

I will if people agree put in a fix to change this to 
`config_path += Ganga.Utility.Config.expandConfigPath(blah...`

However I would like some imput from someone who has touched this code recently and therefore will know what this call is actually supposed to be doing.

**Comment by milliams** [comment]
It looks like the core reason for the change in behaviour is a change in how the `GANGA_CONFIG_PATH` config variable's default value has changed. It used to default to `None` but now it defaults to some directory. It should be a simple change but it needs a quick look through.

**Comment by alexanderrichards** [comment]
presumably the change from None to said default happened along with the introduction of this expandConfigPath function else you would get an exception in 
[Ganga/Utility.Config.Config.py:L1036](https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/Utility/Config/Config.py#L1036)

when trying to split the None:
```python
def expandConfigPath(path, top):
    <snip>
    for p in path.split(':'):
```

So for those of you running within the ATLAS/LHCb environments, how does your config_path differ at this point (since you don't see this error)?

**Comment by rob-c** [comment]
The system config is a single fixed path but the config path relates to the plugins I think ```GangaDirac:GangaLHCb``` for instance which needs to be correctly fully expanded as we could have ```GangaDirac:GangaLHCb:~/myUserPlugin```

**Comment by alexanderrichards** [comment]
right o, the solution then is presumably:

```python
        # all relative names in the path are resolved wrt the _gangaPythonPath
        # the list order is reversed so that A:B maintains the typical path precedence: A overrides B
        # because the user config file is put at the end it always may override
        # everything else
        config_files = []
        if self.options.config_path:
            config_files = Ganga.Utility.Config.expandConfigPath(self.options.config_path, _gangaPythonPath)
            config_files.reverse()
```

I'll put in a PR for this then. Thanks guys

**Comment by alexanderrichards** [comment]
sorry ignore that, clearly as I mentioned earlier `self.options.config_path` is not `None` but a directory.

**Comment by alexanderrichards** [comment]
right I believe that commit 231dc8ff1056c978e093893af10868df868b4860 fixes at least the trying to read the GangaRoot dir as a config file problem but I'll leave this open since there is still a lot of startup messages that we can remove

**Comment by rob-c** [comment]
I think this has been superseded by other issues, are we ok to close this?

**Comment by alexanderrichards** [comment]
yeah close it

**Comment by rob-c** [comment]
Closing as covered by other issues such as #410
