### ISSUE TITLE
Add tests for readInputData

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1545]
Add tests for `GaudiExec.readInputData`.

**Comment by masterashu** [comment]
@mesmith75  I would like to work on it. Since i am not familiar with Ganga, can you just tell me where to start.

**Comment by mesmith75** [comment]
Turns out this already exists here:
https://github.com/ganga-devs/ganga/blob/97cf1c6d7ceca0d99364532d598cb475d1dd006f/ganga/GangaLHCb/test/GPI/TestExternalGaudiExec.py#L66
Closing the issue.
