### ISSUE TITLE
Check XML data file integrity

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#155]
We want to make sure that the ```data~``` file contains a backup of the actual ```data``` file and to make sure that the operations which move a new data file into place are as atomic as possible to prevent future data loss.

I'll look into this asap.

**Comment by egede** [comment]
@rob-c Is this not solved now?

**Comment by milliams** [comment]
I think last I checked, `~data` contained the backup of the data from before the new data was written (i.e. `data` moved to `~data`, new text written to `data`). If we want another step to overwrite `~data` with the new info then I *think* that makes sense.

**Comment by drmarkwslater** [comment]
Current order of events is (with ~nothing in between):

1. Write new data to data.new
2. Move old data to data~
3. Move data.new to data

i.e. data~ is a backup from the **previous** flush, not the one that is being written. I personally think this makes more sense in that if you have a corrupt flush you always have the previous one to go back to though I can see the argument for basically having data~ == data

**Comment by rob-c** [comment]
I think there is about 10 lines of code where ```data``` doesn't exist. It would be nice (just for sake of systems with potentially very slow file access) to get this down to 1 or 2 lines if possible I think.
I'm happy to not delay 6.1.16 on this but I think it's worth addressing by investigating if it's possible to overwrite a file in a copy then remove the .new afterwards.

**Comment by drmarkwslater** [comment]
The code in question is:
```
            try:
                if os.path.isfile(fn):
                    os.rename(fn, fn + "~")     # This is where data -> data~
            except OSError as e:
                logger.debug("Error on file backup %s (%s) " % (fn, e))
            try:
                if os.path.isfile(fn+'.new'):
                    os.rename(fn + ".new", fn)  # This is where data.new -> data
            except OSError as e:
                raise IOError("Error on moving file %s.new (%s) " % (fn, e))
```
So actually, excluding the try..except, there's very little going on between the two renames. I'd be happy to keep it like this actually.

**Comment by rob-c** [comment]
Can we change the backup. If (for whatever reason) the ```.new``` doesn't exist I'd rather not be stuck missing the ```data``` file even if this should never happen.
(I've seen some problems with afs not reporting a file as being there when it is due to timeouts)

**Comment by rob-c** [comment]
i.e. possibly something like:
```python
            try:
                if os.path.isfile(fn):
                    if os.path.isfile(fn+'.new'):
                        os.rename(fn, fn + "~")     # This is where data -> data~
                    else:
                        raise GangaError("Some sort of error")
            except OSError as e:
                logger.debug("Error on file backup %s (%s) " % (fn, e))
            try:
                if os.path.isfile(fn+'.new'):
                    os.rename(fn + ".new", fn)  # This is where data.new -> data
            except OSError as e:
                raise IOError("Error on moving file %s.new (%s) " % (fn, e))
```

**Comment by drmarkwslater** [comment]
I've got a proposed change in PR #228 which addresses this
