### ISSUE TITLE
Put limit on subjobs that can pull virtualization image from the same server.

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1552]

**Comment by egede** [comment]
The server gitlab.cern.ch is not able to cope with potentially thousands of subjobs pulling a virtualization image at the same time. We should configure it such that there is a limit on how many subjobs can do that. Create two configurables for the virtualization, one that deals with the maximum number and another a regexp matching the image names that it should apply to.

**Comment by egede** [comment]
@chrisburr Please make further comments here.

**Comment by chrisburr** [comment]
I brought this up for discussion in today's LHCbDIRAC developers meeting and we all agreed that the infrastructure is not ready for this to be used without any restrictions. This isn't LHCb specific and applies to the grid as a whole.

The main issue is that containers that analysts will want to use are often quite large and these must then be fully unpacked into `$TMPDIR` each time singularity is started. Externally people are looking at unpacking user provided containers onto CVMFS, but this requires management procedures and infrastructure that doesn't currently exist (see Tuesday's pre-gdb meeting). This is how effectively how LHCb production jobs are using containers, but it's a simpler case as we only need two different images.

We agreed that Ganga should implement the following restrictions for now:

* Never pull containers on worker nodes, always ship them as a input data, regardless of source
* Prevent users from submitting containers which are larger than 1GB
* Prevent too many jobs being submitted that use `job.virtualization` (~10)
* Display a prominent warning whenever `job.virtualization` is used to state that this is experimental and abuse (i.e. avoiding these restrictions) will result in grid access being immediately revoked

To be clear, we all agree that it has the potential to be incredibly useful and popular. We are just concerned that using singularity could become too popular before the grid is ready to handle it.

**Comment by egede** [comment]
Returning to this after the holidays.

At least for Singularity, I do not think that `$TMPDIR` is used for anything. The wrapper sets `$SINGULARITY_CACHEDIR` to the working directory, so it should be confined to there. If `$TMPDIR` is not used at all (I will test), should we then reconsider some of the statements below? See my first comments.

- *Never pull containers on worker nodes, always ship them as a input data, regardless of source*
In Ganga, the inputsandbox is uploaded to the Grid before submission (to prevent uploading the same sandbox several thousand times in case of subjobs), so to enforce this rather than having it as a `DiracFile` (i.e a file on a storage element), seems silly. We could rather implement a block on downloading directly from `Gitlab` at CERN to prevent overloading of their server.

- *Prevent users from submitting containers which are larger than 1GB*
I do not really see how we can effectively limit the size of the container prior to submitting, but we can make the jobs fail if it is the case.

- *Prevent too many jobs being submitted that use job.virtualization (~10)*
A limit can be placed on the number of subjobs. If submitted as individual jobs, there is nothing that can be done though (but the warning below will be displayed for every job).

- *Display a prominent warning whenever job.virtualization is used to state that this is experimental and abuse (i.e. avoiding these restrictions) will result in grid access being immediately revoked*
Sure.

**Comment by egede** [comment]
In the next release there will in Ganga be support to take images from `/cvmfs/unpacked.cern.ch`. That is a much better way to use images for DIRAC jobs, so I think what is written here can be forgotten.
