### ISSUE TITLE
Jenkins failures

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1563]
```
#4 docker-image://docker.io/docker/dockerfile:1.0-experimental@sha256:cbd64...

#4 CACHED

failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: frontend grpc server closed unexpectedly

script returned exit code 1
```
This is the cause of the recurring failures in Jenkins.

**Comment by egede** [comment]
Is this still the case?

**Comment by egede** [comment]
OK, so in the past few days, I have seen this error several times again. Googling a bit around indicate that there might be a race condition going on. The GangaDirac container build on top of the GangaCore container, but the GangaCore container is not registered yet with the docker daemon. Can we include a sleep statement of maybe a minute at https://github.com/ganga-devs/ganga/blob/cab178021c3b88e060f53c00e0bb76f4d5db6247/Jenkinsfile#L19 to see if that solves the issue? If I just edit this file, will it get pushed to the test machine directly, or is there some manu step involved?

**Comment by mesmith75** [comment]
Is there a reason GangaLHCb doesn't fail - does it not build on top of GangaCore?

If you edit the file and create a new PR then the tests on the PR will use the Jenkinsfile from that PR's branch.

**Comment by egede** [comment]
> Is there a reason GangaLHCb doesn't fail - does it not build on top of GangaCore?

That is correct. The GangaLHCb container builds on top of an external LHCb container.

> If you edit the file and create a new PR then the tests on the PR will use the Jenkinsfile from that PR's branch.

Done - let's see how it goes.
