### ISSUE TITLE
Revive GangaTutorial package

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1566]
The GangaTutorial package is not working in the latest release.

```
export GangaTutorial/Tutorial.ini`
(ganga) (base) [desktop] ~/programming/ganga % bin/ganga

*** Welcome to Ganga ***
Version: 8.2.0 - DEV
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


INFO     reading config file /home/egede/.gangarc
INFO     reading config file /home/egede/programming/ganga/src/ganga/ganga/GangaTutorial/Tutorial.ini
ERROR    problems with loading Plugin /home/egede/programming/ganga/src/ganga/ganga/GangaTutorial
ERROR    Reason: No module named 'Lib'
PluginError: Failed to load plugin: /home/egede/programming/ganga/src/ganga/ganga/GangaTutorial. Ganga will now shutdown to prevent job corruption.
(consider --debug option for more information)
INFO     Stopping Job processing before shutting down Repositories
INFO     Shutting Down Ganga Repositories
INFO     Registry Shutdown
```
Looking at https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaGaudi/PACKAGE.py and https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaGaudi/__init__.py should make it clear what changes are required. Inside package there might be further changes required to deal with python3.

**Comment by advait-l** [comment]
I would like to work on this issue.

**Comment by egede** [comment]
You are very welcome.

**Comment by advait-l** [comment]
I have set up the code but I'm unable to replicate the issue with the GangaTutorial package.
How do I do that?

**Comment by egede** [comment]
Typo in instructions. It should say
```
[desktop] ~/programming/ganga % export GANGA_CONFIG_PATH=GangaTutorial/Tutorial.ini
[desktop] ~/programming/ganga % bin/ganga
```

**Comment by egede** [comment]
Sorry, updated the instructions.

Ulrik.

**Comment by advait-l** [comment]
Thanks, I was actually unable to replicate the issue.

Could you please elaborate upon what needs to be done to fix this issue?

**Comment by egede** [comment]
If I ask `Ganga` to load the tutorial package on startup with the line
```
export GANGA_CONFIG_PATH=GangaTutorial/Tutorial.ini
```
and then start `Ganga`, I get the error
```
ERROR    problems with loading Plugin /home/egede/programming/ganga/src/ganga/ganga/GangaTutorial
ERROR    Reason: No module named 'Lib'
```
If you do not see the error, I suspect that you fail to set the environment variable correctly.
