### ISSUE TITLE
Migrate tests from old testing framework

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1567]
The tests located in https://github.com/ganga-devs/ganga/tree/develop/ganga/GangaCore/old_test are not executed as part of the Continuous Integration tests. The following should be done

- [ ] Migrate tests that look useful to https://github.com/ganga-devs/ganga/tree/develop/ganga/GangaCore/test by changing them to run within `pytest`.
- [ ] Remove all tests that no longer have value. Almost for sure everything in `Bugs`, `Regression` and `Performance`.
- [ ] Remove the old_test directory completely.

The first part of the task can be broken up into individual pull requests for one or a few tests at a time.

**Comment by mayankDhiman** [comment]
I look forward to work on this.

**Comment by hedonhermdev** [comment]
Hey, @mayankDhiman are you working on this?

**Comment by mayankDhiman** [comment]
Hi @hedonhermdev, Yes I am.
