### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1573]
The installation instructions available at https://ganga.readthedocs.io/en/latest/UserGuide/InstallAndBasicUsage.html need a bit of updating. The file to update is 
https://github.com/ganga-devs/ganga/blob/develop/doc/UserGuide/InstallAndBasicUsage.rst

What is required is:
- Make it clear at the top that Ganga is only available for Python3 and that it is only supported on linux systems.
- In the PyPI section, change the virtualenv line to `virtualenv -ppython3 gangaenv`
- Remove section with "Ganga Install Script"
- In section "From Github", replace what is there with something like
```
# Create a virtualenv
virtualenv -ppython3 ganga
cd ganga/
. bin/activate
# Install Ganga and its dependencies
pip install -e git+git@github.com:ganga-devs/ganga.git#egg=ganga

# Start Ganga
ganga
```
- Remove the "For LHCb" section

**Comment by Corxrew** [comment]
I would like to take this up

**Comment by egede** [comment]
> I would like to take this up

You are welcome.
