### ISSUE TITLE
GangaDataset and GangaDatasetSplitter with treat_as_inputfiles

### ISSUE THREAD

**Issue by ast0815** [ganga-devs/ganga#1583]
Hello,

I seem to have several issues with `GangaDataset`  and `GangaDatasetSplitter`. I will create an issue for each. I am using Ganga 8.2.0.

I noticed that `GangaDataset`'s `treat_as_inputfiles` argument does not work when combined with  a `GangaDatasetSplitter`.

This works:

```
j = Job()
j.application = Executable()
j.application.exe = '/bin/ls'
j.application.args = ['-l']
j.inputdata = GangaDataset(files=[LocalFile(path) for path in input_files], treat_as_inputfiles=True)
```

showing the two dataset `*.mac` files:

```
total 28
-rw-rw---- 1 kdf77245 t2k  233 Feb 21 13:15 __GangaInputData.txt__
-rw-rw---- 1 kdf77245 t2k 9011 Feb 20 15:56 intp13020010.mac
-rw-rw---- 1 kdf77245 t2k 9011 Feb 20 15:56 intp50113010.mac
drwxrwx--- 2 kdf77245 t2k   22 Feb 21 13:15 _python
-rw-rw---- 1 kdf77245 t2k    0 Feb 21 13:15 stderr
-rw-rw---- 1 kdf77245 t2k    0 Feb 21 13:15 stdout
-rw-rw---- 1 kdf77245 t2k    0 Feb 21 13:15 __syslog__
```

This does not work:

```
j = Job()
j.application = Executable()
j.application.exe = '/bin/ls'
j.application.args = ['-l']
j.inputdata = GangaDataset(files=[LocalFile(path) for path in input_files], treat_as_inputfiles=True)
j.splitter = GangaDatasetSplitter(files_per_subjob=1)
```

showing a distinct lack of input files:

```
total 4
-rw-rw---- 1 kdf77245 t2k 116 Feb 21 13:18 __GangaInputData.txt__
drwxrwx--- 2 kdf77245 t2k  22 Feb 21 13:18 _python
-rw-rw---- 1 kdf77245 t2k   0 Feb 21 13:18 stderr
-rw-rw---- 1 kdf77245 t2k   0 Feb 21 13:18 stdout
-rw-rw---- 1 kdf77245 t2k   0 Feb 21 13:18 __syslog__
```

Is that expected behaviour? How can I make the dataset files be copied to the subjobs' worker nodes?

**Comment by egede** [comment]
Syntax is fine, so looks like a bug. A workaround while problem is fixed will be to use the `GenericSplitter`.

**Comment by egede** [comment]
Looking a bit closer at this, I am not sure that fixing it is the right approach. The `treat_as_inputfiles` argument is really a legacy. Is there anything that prevent these files just to be added as `inputfiles` and a splitter to be based around that instead? While the specific issue is relatively easy to fix, there is at least one more bug due to the legacy behaviour (if you make a copy of one of the subjobs, you get the unsplit dataset assigned as inputfiles).

So my suggestion is to remove the `treat_as_inputfiles` instead if fixing the problem. comments?

**Comment by mesmith75** [comment]
Does it have an impact on Dirac or other remote files as it should cause them to be downloaded to the WN?

**Comment by ast0815** [comment]
My intended use case was to use the `GangaDataset` for the actual input data and the `inputfiles` for scripts and other supplementary files that are common to all (sub-)jobs. I guess it could be achieved with a generic splitter and some logic around it, or a custom splitter, but I have not looked into the latter so far. I have only been using the provided classes.

**Comment by egede** [comment]
> Does it have an impact on Dirac or other remote files as it should cause them to be downloaded to the WN?

I think the `Dirac` backend is OK. If you give a file as `inputdata`, it will (for a non `GaudiExec` application) give the `__GangaInputData.txt__` file. If you give it in `inputfiles` it will be copied to the worker node. Works for all `GangaFile` types I believe.

**Comment by egede** [comment]
New issue #1600 created.
