### ISSUE TITLE
Error in "pip install Ganga"

### ISSUE THREAD

**Issue by AbhinavMir** [ganga-devs/ganga#1591]
pip log overview:
_ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output._

How to reproduce: "pip install ganga" on Windows machine, using Python3.

**Comment by egede** [comment]
Ganga only works on a linux architecture. Please install a virtual machine or similar and work within that.

**Comment by Adarsh-NP** [comment]
Also, kindly read and take a note of this


Using pip, you can install things in different ways, and there might be some confusion there.

As suggested in the README, you can create a virtualenv and then do everything inside there. As long as you have sourced the 'activate' script, you will then have 'ganga' in our PATH. This is the recommended solution.
If you simply do 'pip install ganga' then a system installation will be attempted. Most likely sudo will be required for this, but depends on your local setup. I do not recommend this as it pollutes your system instllation with what is a development project.
You can do pip --user install ganga which will make an installation into some hidden directories of your local user. This is in my mind even worse than the second option as you tend to forget what is there. 
    ~Ulrik
