### ISSUE TITLE
Make backend wrappers work in both python2 and python3

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1592]
The backend wrapper for the local backend https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/Lib/Localhost/LocalHostExec.py.template explcitly requires python2. The simple script (and the code injected into it) should be agnostic to python2/3 and the shebang changed to just say `/bin/env python`

**Comment by egede** [comment]
This might be solved at the same time as #1588

**Comment by egede** [comment]
Thanks to @EdwardCullen30 for reporting this issue.

**Comment by EdwardCullen30** [comment]
is this issue resolved ? cause i just try to do the same task and was able to get a error-free result

**Comment by egede** [comment]
The problem is still there, see https://github.com/ganga-devs/ganga/blob/d9d8f56601d83a321d52ad5f8c90bc091c9ccc9d/ganga/GangaCore/Lib/Localhost/LocalHostExec.py.template#L1
However, it will be solved by #1598

**Comment by egede** [comment]
Time has moved on, and there will now be an explicit requirement of `python3`

**Comment by alexanderrichards** [comment]
I'll close this issue then.

--Edit--
Sorry didn't see it was linked to a PR which would have closed it automatically
