### ISSUE TITLE
Condor jobs stop being updated in `jobs` list?

### ISSUE THREAD

**Issue by ast0815** [ganga-devs/ganga#1611]
I noticed that sometimes jobs with the `Condor` backend stop tracking the status of the actual jobs on Condor. I.e. they have a perpetual state of "submitted" instead of transitioning to "running" or "completed". I suspect that it might have something to do with the jobs being moved around by the actual Condor system. I.e. I have seen this happen when the job is "held" by Condor and subsequently "released" to a different node. In this case the `actualCE` reported by ganga is also different from the one the Condor job is actually running on.

By the way, should a Condor job with the "submitted" status even have a `backend.actualCE` value?

**Comment by egede** [comment]
I would like to migrate the status updates of the `condor` backend to use the same heartbeat mechanism as the other batch backends to track the status of the jobs. However, if jobs are held and migrated to different nodes, that might represent a problem (for the other batch backenbds, a job is declared failed if it is running and doesn't update its heartbeat within a given period of time.

I am not sure if the problem you observe is (only) related to a job being held and released again. With other batch systems we have had the issue that the change of status of jobs is not updated often enough (so you could submit a job, and then if you query the status of the job a few seconds later, it simply doesn't exist in the system). That was what moved us to the heartbeat solution.

**Comment by ast0815** [comment]
I think marking the job as failed when it gets held would be reasonable. At least that would prompt an investigation by the user into what happened to that job. Ideally the "held" status would be reflected by the Ganga job (including a way of releasing it from ganga). But I guess adding another job state (and methods to deal with it) just for a single backend is maybe not such a wise choice from an API design point of view.

Would this change how jobs are handled before being marked as "running" though? I am not 100% sure the jobs ever reached a "running" status in Ganga. Though I guess they must, if they had an "actualCE" assigned, right? Is there a defined transition from "running" back to "submitted"?

**Comment by egede** [comment]
We have a mapping from the often fine grained native backend states to the states reported in Ganga. To me it looks like `held` could be mapped to submitted. We do allow for a transition from running to submitted, so that should be OK. We see this happen quite often with the `Dirac` backend in fact.

**Comment by ast0815** [comment]
So then to get the held job to run, one has to use the Condor tools, right? Or can you re-submit a job in the submitted state from Ganga?

**Comment by egede** [comment]
You are exposing my lack of knowledge of Condor. I thought jobs themselves would start again from the `held` state. When a job is `held` is it stopped mid execution and then restarted from that point (like a container that is stopped on one machine and restarted on another) or is it starting from the beginning again when released?

**Comment by ast0815** [comment]
My knowledge is spotty as well. But looking at the docs: https://www.cl.cam.ac.uk/manuals/condor-V6_8_3-Manual/condor_hold.html

> A job in the hold state remains in the job queue, but the job will not run until released with condor_ release.
> 
> A currently running job that is placed in the hold state by condor_ hold is sent a hard kill signal. For a standard universe job, this means that the job is removed from the machine without allowing a checkpoint to be produced first.

I'm not quite sure what causes a job to be put in hold automatically though. I think I read somewhere that this happens when there is e.g. an IO error, so something that can be expected to "fix itself" later.

**Comment by ast0815** [comment]
See also https://htcondor.readthedocs.io/en/stable/users-manual/managing-a-job.html#placing-a-job-on-hold and https://htcondor.readthedocs.io/en/stable/users-manual/managing-a-job.html#job-in-the-hold-state .

Seems like it can continue from a previous checkpoint, and sometimes jobs are released from hold automatically.

**Comment by egede** [comment]
So is the correct thing to do when  job goes into hold, to simply remove it from the condor queue and make the Ganga job failed? From Ganga the job can then be resubmitted if required.

**Comment by ast0815** [comment]
I guess that would be the easiest, consistent way of doing it. Even if it might not be ideal in the cases where there is a checkpoint (as you would lose that progress). Checkpoints need to be implemented by the user, though. If you just send off a program without compiling it with the special Condor compiler, there are no checkpoints, I think. And even then I am not sure how that works. So short of adding another job state to Ganga, that might be the best way of dealing with it.

**Comment by ast0815** [comment]
Just a quick update. I noticed that Condor jobs stop being updated as soon as I `.kill()` and then `.resubmit()` them. They do not have to go through the "held" state.

**Comment by egede** [comment]
> Just a quick update. I noticed that Condor jobs stop being updated as soon as I `.kill()` and then `.resubmit()` them. They do not have to go through the "held" state.

Thanks for this report. Sounds like a clear bug to trace down!

**Comment by egede** [comment]
This will be solved by #1588
