### ISSUE TITLE
Create a method for user to upload output of `report` functionality.

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1617]
The `report()` function has been updated but we can no longer use the CERN based server. There is a need to create a new one. See #1587.

**Comment by egede** [comment]
@RajatSingh95 Can you please add a link to the specification for the server backend.

**Comment by RajatSingh95** [comment]
@egede https://aws.amazon.com/ec2/instance-types/
In the given link, you can have a look at **T2** instance. This instance is sufficient for the purpose.
Currently, I have hosted the service for accepting requests from `report()` function on **ec2 T2 instance**.

**Comment by egede** [comment]
> @egede https://aws.amazon.com/ec2/instance-types/
> In the given link, you can have a look at T2 instance. This instance is sufficient for the purpose.

But you then setup some server on it?

**Comment by RajatSingh95** [comment]
Yes. After creating the instance, you have to host a web server(in my case, it was django server) on it..

**Comment by egede** [comment]
I am no expert here, so is there a way to more or less automate this (so having requested a T2, can I simply execute a script to setup, configure and start the server)?

**Comment by RajatSingh95** [comment]
Yes. We can automate the whole process (from **requesting a T2 instance** to **starting the server**).
I will update you once I am ready with the script which can automate the whole process.

**Comment by RajatSingh95** [comment]
@egede I have created a repository where I have pushed all the codes and instructions which need to be done to automate the whole process that we have discussed earlier. Below is the repo link:
https://github.com/RajatSingh95/ec2-automation

Please have a look at it and let me know if you encounter any problem.

**Comment by RajatSingh95** [comment]
Currently, The setup of the Django webserver through the above automation script is the clone of the repo link given below:
https://github.com/RajatSingh95/report-server

If there are some changes to be made to this repo before deploying a permanent server, we can discuss it.

**Comment by egede** [comment]
Many thanks.

**Comment by DumbMachine** [comment]
@egede Once the [`GoogleFile`](https://github.com/ganga-devs/ganga/pull/1625) PR is merged I think we can use that for submitting reports. With the use of `report(job)` function, the required files (which are available [here](https://github.com/ganga-devs/ganga/blob/f9ca0c5b1c007ecdbc71d4af96566dc430c78a96/ganga/GangaCore/Utility/feedback_report.py#L149), I assume) will be uploaded by adding the corresponding file to a `GoogleFile` object.
https://github.com/ganga-devs/ganga/blob/f9ca0c5b1c007ecdbc71d4af96566dc430c78a96/ganga/GangaCore/Utility/feedback_report.py#L149

**Comment by RajatSingh95** [comment]
I think the credentials used for GoogleFile are user-specific and cannot be used as a permanent one. `report(job)` function sends the report to the developer server which return a permanent URL for the user report that could be used as a future reference by the user or developer both.

**Comment by egede** [comment]
So in the past we had this server running that could receive the reports from users. However, I am not keen on that we have the responsibility to keep a server updated and patched. So an alternative idea is that a user simply create the file as a `GangaFile` object. This object can then be a `LocalFile` and the user can share the file with developers in some manual way, or it can be a 'GoogleFile` where the user then afterwards can just share the file in Google with the developers. Implementing it like this also makes it clearer to the user with whom they share the information and how (as there potentially can be sensitive information). This will require a bit of change to how the interface for `report` is working.

**Comment by DumbMachine** [comment]
@egede I believe the work here is done and the issue can be closed.
