### ISSUE TITLE
New test system

### ISSUE THREAD

**Issue by milliams** [ganga-devs/ganga#162]
This is an issue to track the remaining issues with converting everything over to the new test system. I will keep it updated as we go. For now it will focus on the equivalent of the `gangage` tests.

There are a number of categories of tests:
- [ ] Convert `GPI/Bugs` tests
  - [x] Convert Local/Executable-based
  - [x] Convert Grid-based
  - [ ] Convert Batch-based
- [ ] Convert `GPI` tests
- [ ] Convert `Internals` tests
- [ ] Convert `Schema` tests
- [ ] Convert unit-type tests that are scattered around the code

And a set of blockers for getting them done (other than time):
- [x] Grid proxy for LCG tests
  - [x] Get on GridPP VO
  - [ ] Get on ATLAS VO
  - [x] Get on LHCb VO
- [ ] Batch system (connect to Birmingham or Liverpool?)
- [ ] Multi-pass tests or generally long-running tests

**Comment by rob-c** [comment]
Multi-pass tests should be considered on a test by test basis imo such as with #161 You just need to make sure your test's are all names appropriately and they will run consecutively on the same repo shutting down and restarting ganga (or do extremely close to this).
````.gpip``` tests or multi-threaded tests are I think impossible to test easily with the unittest system unless we build something like ```MultiGangaUnitTest```

**Comment by milliams** [comment]
So is the purpose of GPIM to just test closing Ganga and opening it again and to check that things are persisted correctly? I thought it was something more. If not then I agree that your approach in #161 makes sense. We just have to make sure that `[TestingFramework] AutoCleanup=False` really does work as we expect.

**Comment by rob-c** [comment]
Yes AutoCleanup is working. At least when I tested it, by default each test should get a fresh repo when they startup but if they change this to False the repo remains in the same state from one test to the next.
(And currently isn't cleaned up on exit, hence my wanting to use tearDownClass)

I would be weary that a few of the GPIM tests pass some 'knowledge' from one step of the test to the next. (not something I overly agree with).
Either the tests should be ported with care to reconstruct this knowledge in a better way in one test to the next or we build in some mechanim to pass information(objects?) from one test to the other.
Frankly as we have a Job and Box repo working as expected We should be fine tbh.

**Comment by milliams** [comment]
Yes, I think that the GPIM tests will need to be redone in some sense. There's only 19 of them so it shouldn't be as large a job. If possible, as you say, we should pass information via the repository but if we really can't then just setting a python variable which persists should work fine (we already do this to avoid repetition of file names in a few places).

**Comment by rob-c** [comment]
Where is this done? I'm slightly curious

**Comment by milliams** [comment]
For example in [TestCustomMerger](https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/test/GPI/Mergers/TestCustomMerger.py#L14) where `self.file_name` is used in multiple functions. Now, it's possible that this should be done in a subtly different way but I can't think of one that's much better.

**Comment by rob-c** [comment]
Ah, I thought you meant in the already ported tests

**Comment by alexanderrichards** [comment]
I haven't really looked into this in a while but if there is scope for dumping the multipass tests and replacing them with something more python standard then it gets my vote ;-)

**Comment by egede** [comment]
We have in the past (and also very recently) had problems with that the persisting mechanism works correctly. So we preferably need some other kind of test where we can be sure that we re-read an object from the persisted version. If that is in place, it is for sure a less fragile way of testing compared to the 2-step tests that we have now.

**Comment by rob-c** [comment]
Would it be worth having a ```GangaTestDataObject``` (or equivalent) which will store any ```serializable``` object in the Box repo. I can't think we'd want to store anything more than simple data here but it does store the data in a way which we can do some basic integrity tests on if we suspected problems. (The repo can be set to persist data between tests as per the lazyLoading test)

**Comment by milliams** [comment]
I've started work on a separate work so that we can easily set up isolated environments for running, e.g. LHCb tests on. It's also a slightly more powerful VM so it should slightly reduce the hanging tests we see occasionally.

**Comment by milliams** [comment]
I've also been looking into running our tests using little ganga and pytest. As an example, a full working example can be seen at [this gist](https://gist.github.com/milliams/43bb69cf7f18dc398526) where the first file defines the test fixtures (one which makes little ganga available and another which provides a monitoring loop) and the second file is the complete test. Obviously it is slightly simplistic but I hope it shows what can be possible.
