### ISSUE TITLE
Remove SandboxFile

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1626]
`SandboxFile` https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/GPIDev/Lib/File/SandboxFile.py  is deprecated and the whole file can be removed. Complete code should be checked for any stale references to it and they should be removed.

**Comment by Harshagarwal19** [comment]
Hi,
I was working on this issue. But it seems https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaNA62/Lib/Applications/NA62MC.py#L245 uses SandboxFile. How should I proceed?

**Comment by egede** [comment]
Thye NA62MC package is not updated, so you can remove `SandboxFile` anyway. If the developers of that package ever get their act together, they will have to make many other changes anyway.

**Comment by egede** [comment]
Closed by #1628
