### ISSUE TITLE
Enable Ganga to run in non-persisted mode

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1631]
Nearly all of the Continuous Integration tests that we run in Ganga do not rely on that jobs are persisted as they run within a single Ganga session. In fact it is only tests related to the persistency itself that needs it.

It would be good for this reason to be able to run Ganga without anything getting persisted (or indeed loaded from disk). With an upcoming database implementation of the persistency, this will also make things easier in terms of testing.

**Comment by DumbMachine** [comment]
A simple `hack` or `workaround` would be to create empty `file buffers` which will be used in place of the files at `ganga/repository`.

**Comment by egede** [comment]
> A simple `hack` or `workaround` would be to create empty `file buffers` which will be used in place of the files at `ganga/repository`.

I do not think that we need a `hack` here. To use `file buffers` or maybe something like https://docs.pyfilesystem.org/en/latest/index.html might be useful for the files in `shared` and `workspace`. For the repository, I think it would be better to think about how we could simply disable the persistency. If that is the case, the solution will work when we move to a database model as well.

**Comment by DumbMachine** [comment]
I believe one solution can be adding another `GangaRepository`, i.e `GangaRepositoryTest`. 
https://github.com/ganga-devs/ganga/blob/d057b9e9f7fce0713190b4597c7e7ef8580608e3/ganga/GangaCore/Core/GangaRepository/Registry.py#L95
Then when implementing this `GangaRepositoryTest`, the appropriate persistency calls can be removed from `startup()` and `update_index()` since we don't need to read prior jobs.

A similar solution could work when we move to database model, i.e adding a `GangaRepositoryDatabase`

**Comment by egede** [comment]
This looks like a good proposal. Looking at that bit of code, it also looks like we need to start this by cleaning up (or understand) what is already there. In particular, Is the `Transient` or `ImmutableTransient` types already doing what we would like? I notice that this code, apart from some compliance issues, has not been touched since the code entered formal version control (12 years ago I believe), so I must admit that I do not remember anything about this.

**Comment by DumbMachine** [comment]
`GangaRepositoryImmutableTransient` makes use of disk for reading `pickled job objects` 
https://github.com/ganga-devs/ganga/blob/d057b9e9f7fce0713190b4597c7e7ef8580608e3/ganga/GangaCore/Core/GangaRepository/GangaRepositoryImmutableTransient.py#L44
https://github.com/ganga-devs/ganga/blob/d057b9e9f7fce0713190b4597c7e7ef8580608e3/ganga/GangaCore/Core/GangaRepository/GangaRepositoryImmutableTransient.py#L48

`GangaRepositoryTransient` doesn't issue any `io`, it adds new jobs/objects by taking jobs as a list of objects
https://github.com/ganga-devs/ganga/blob/d057b9e9f7fce0713190b4597c7e7ef8580608e3/ganga/GangaCore/Core/GangaRepository/GangaRepository.py#L250

**Comment by DumbMachine** [comment]
I believe `GangaRepositoryTransient` is the way to go, i.e having a `in-memory` repo, as it's docs tell us.

**Comment by egede** [comment]
> I believe `GangaRepositoryTransient` is the way to go, i.e having a `in-memory` repo, as it's docs tell us.

Yes, that sounds good. So maybe the task is changing to
- Make sure the `GangaRepositoryTransient` is working.
- Make the testing use this transient repository by default.
- Remove the repository types that no longer work or are no longer required (the pickle one, the old SQL implementation).

**Comment by DumbMachine** [comment]
`GangaRepositoryTransient` does not work out of the box. Additional `methods` and attributes will have to be added to make it compatible with code that calls the `repository`.

Small example, indicating that the `repository` lacks the `objects` attribute to store the `jobs`. 
```bash
(base)  ✘ dumbmachine@den  ~/code/ganga   temp ●  ganga

*** Welcome to Ganga ***
Version: 8.2.2 - DEV
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


INFO     reading config file /home/dumbmachine/.gangarc
Traceback (most recent call last):
  File "/home/dumbmachine/anaconda3/bin/ganga", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/dumbmachine/code/GSOC_SELECTION/ganga/bin/ganga", line 90, in <module>
    GangaCore.Runtime.setupGanga()
  File "/home/dumbmachine/code/GSOC_SELECTION/ganga/ganga/GangaCore/Runtime/__init__.py", line 19, in setupGanga
    GangaCore.Runtime._prog.bootstrap(GangaCore.Runtime._prog.interactive)
  File "/home/dumbmachine/code/GSOC_SELECTION/ganga/ganga/GangaCore/Runtime/bootstrap.py", line 933, in bootstrap
    startUpRegistries()
  File "/home/dumbmachine/code/GSOC_SELECTION/ganga/ganga/GangaCore/Runtime/Repository_runtime.py", line 261, in startUpRegistries
    for n, k, d in bootstrap():
  File "/home/dumbmachine/code/GSOC_SELECTION/ganga/ganga/GangaCore/Runtime/Repository_runtime.py", line 135, in bootstrap
    registry.startup()
  File "/home/dumbmachine/code/GSOC_SELECTION/ganga/ganga/GangaCore/GPIDev/Lib/Registry/PrepRegistry.py", line 24, in startup
    super(PrepRegistry, self).startup()
  File "/home/dumbmachine/code/GSOC_SELECTION/ganga/ganga/GangaCore/Core/GangaRepository/Registry.py", line 205, in decorated
    return f(self, *args, **kwargs)
  File "/home/dumbmachine/code/GSOC_SELECTION/ganga/ganga/GangaCore/Core/GangaRepository/Registry.py", line 614, in startup
    self._objects = self.repository.objects
AttributeError: 'GangaRepositoryTransient' object has no attribute 'objects'
INFO     Stopping Job processing before shutting down Repositories
INFO     Shutting Down Ganga Repositories
INFO     Registry Shutdown
(base)  ✘ dumbmachine@den  ~/code/ganga   temp ●  
```

**Comment by egede** [comment]
> GangaRepositoryTransient does not work out of the box. Additional methods and attributes will have to be added to make it compatible with code that calls the repository.

I am not surprised.

**Comment by egede** [comment]
I think we should just make this part of the new persistency system. Either as a specific flag or through an easy way to mock the calls to the database.
