### ISSUE TITLE
pip install broken

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#166]
Hi all,

Apologies if this is a known bug but I keep getting:
```
Collecting ganga
  Could not find a version that satisfies the requirement ganga (from versions: )
No matching distribution found for ganga
```

from pip install ganga on multiple platforms. I don't know if this is known bug/limitation or not but these systems are not fedore/RHEL based/compatible so I don't know if this effects anything.

This is a minor detail as I can just clone and run Ganga for testing.

Thanks,

Rob

**Comment by milliams** [comment]
This is because we haven't released Ganga on PyPI yet. Once 6.1.15 is released it will be uploaded.

**Comment by rob-c** [comment]
OK, apologies I thought this was working. Sorry for the noise

**Comment by milliams** [comment]
No worries, I'll post a thing to the list once its there so we can give it some testing.
