### ISSUE TITLE
Error when getOutputSanbox in Dirac Job

### ISSUE THREAD

**Issue by asnaylor** [ganga-devs/ganga#1661]
I've submitted a number of simple test jobs (`echo "hello world" | tee -a test.txt`) to dirac which ran successfully (i've checked the job out on dirac gridpp site) but when Ganga tries to retrieve  the output sandbox i get an error out it taking at most 5 arguments. I tried again in a fresh virtualenv with only ganga installed and i still get the same error and i'm able to retrieve the output sandbox fine using the dirac gridpp site so it's not dirac.

Python version 3.6.7, ganga version 8.3.0, dirac_ui version v6r19p10

```
Ganga In [7]: j.submit()
INFO     submitting job 30
INFO     job 30 status changed to "submitting"
INFO     Preparing Executable application.
INFO     Created shared directory: conf-1d43de58-f98b-4d04-99c6-38422dd6ec35
INFO     Preparing subjobs
INFO     Submitting job
INFO     job 30 status changed to "submitted"
INFO     Submitted job
Ganga Out [7]: 1
[14:23:09]
Ganga In [8]: ERROR    Unable to finalise job 30 after 5 retries due to error:
GangaDiracError: Error: getOutputSandbox() takes at most 5 arguments (6 given)
INFO     job 30 status changed to "running"
INFO     job 30 status changed to "completing"
WARNING  An error occured finalising job: 30
WARNING  Attemting again (2 of 5) after 2.5-sec delay
INFO     job 30 status changed to "submitted"
INFO     job 30 status changed to "running"
INFO     job 30 status changed to "completing"
WARNING  An error occured finalising job: 30
WARNING  Attemting again (3 of 5) after 2.5-sec delay
INFO     job 30 status changed to "submitted"
INFO     job 30 status changed to "running"
INFO     job 30 status changed to "completing"
WARNING  An error occured finalising job: 30
WARNING  Attemting again (4 of 5) after 2.5-sec delay
INFO     job 30 status changed to "submitted"
INFO     job 30 status changed to "running"
INFO     job 30 status changed to "completing"
WARNING  An error occured finalising job: 30
WARNING  Attemting again (5 of 5) after 2.5-sec delay
ERROR    GangaDiracError: Error: getOutputSandbox() takes at most 5 arguments (6 given)
INFO     Forcing job 30 to status "failed"
INFO     Job 30 PostProcessor Failed
INFO     job 30 status changed to "failed"
```

**Comment by mesmith75** [comment]
This is because of the Dirac version - a change was made here: https://github.com/DIRACGrid/DIRAC/pull/3843/files and ganga updated accordingly.

Perhaps we should make ganga compatible with older versions again.

**Comment by alexanderrichards** [comment]
I don't think we should make Ganga compatible with older versions of Dirac UI but I do think we need to make it clearer what the minimum version is as I certainly had forgotten this and couldn't easily debug it.

**Comment by alexanderrichards** [comment]
Is there even a way to programmatically detect the dirac UI version from the dirac bashrc perhaps and issue a warning to the user of it's too old

**Comment by asnaylor** [comment]
Thanks I Update my dirac ui version to v6r22p6 and it's working great now

**Comment by egede** [comment]
That is great.
