### ISSUE TITLE
Initial database Support for ganga

### ISSUE THREAD

**Issue by DumbMachine** [ganga-devs/ganga#1662]
# GangaDB Project

This issue will hold the word to be done for the project, current status, and future scopes. The `[database-master](https://github.com/ganga-devs/ganga/tree/database-master)` will hold the latest changes for this feature.

# About the Project

This project aims to remove `job metadata` and `data warehousing` based persistence from file system to a database. With this, jobs information would be stored as `json` files in a database instead of `xml` files in the file-system. Following are the components of this feature:

- Replace `VStreamer` class that was responsible for information conversions in `xml` with `DStreamer` class that will do the conversions in `json` to facilitate storage in the database.
- Database functions to store and extract `json` data from the database.
- Container Controllers:
- Addition of `GangaRepositoryDatabase`, the `ganga` repository that makes use of a database to run `ganga`.
- (Future Scope, builds on the prior) Addition of `GangaRepositoryCentral`, the `ganga` repository that makes use of a database to run `ganga` for many different users at once.

## [List of PRs](https://github.com/ganga-devs/ganga/pulls?q=is%3Apr+author%3Adumbmachine):

[#1735](https://github.com/ganga-devs/ganga/pull/1735)

[#1744](https://github.com/ganga-devs/ganga/pull/1744)

[#1](https://github.com/ganga-devs/ganga/pull/1744)[751](https://github.com/ganga-devs/ganga/pull/1751)

[#1](https://github.com/ganga-devs/ganga/pull/1744)[756](https://github.com/ganga-devs/ganga/pull/1756)

[#1](https://github.com/ganga-devs/ganga/pull/1744)[757](https://github.com/ganga-devs/ganga/pull/1757)

[#1](https://github.com/ganga-devs/ganga/pull/1744)[767](https://github.com/ganga-devs/ganga/pull/1767)

## Documentation:
1.[User Guide](https://github.com/ganga-devs/ganga/wiki/GangaDB-User-Guide)
2 [Developer Guide](https://github.com/ganga-devs/ganga/wiki/Ganga-Database)
## Future Work:

1. Remove `subprocess` call to check statuses of processes and instead use `psutil.`
2. Add `authentication` for database.
3. Complete `GangaRepositoryCentral` implementation.

---

This issue will be closed once the feature is fully integrated into `ganga`.
Further feature requests and comments can be discussed here.

**Comment by egede** [comment]
The new package should be named `GangaPersistency` to make its purpose clearer. As we discussed briefly yesterday, keep in mind that the code eventually probably will be merged into `GangaCore`. So try to mirror the directory structure where relevant to make that easier.
