### ISSUE TITLE
Proxy not available for xrootd in singularity container

### ISSUE THREAD

**Issue by alexanderrichards** [ganga-devs/ganga#1668]
problem reported by user to follow:
------------
Hey alex, i’ve been running into some x509 proxy certificate issues with ganga on dirac. I’m just running this simple test command in a ganga dirac job to see if i can access the lz files on the grid in my dirac jobs:
```bash
source /cvmfs/sft.cern.ch/lcg/views/LCG_95apython3/x86_64-centos7-gcc8-opt/setup.sh
python -c "import ROOT; ROOT.TFile.Open('root://gfe02.grid.hep.ph.ic.ac.uk/pnfs/hep.ph.ic.ac.uk/data/lz/lz/data/MDC3/calibration/LZAP-4.3.1/20180201/lz_20180201234_lzap.root').Get('Events')"
```
This works fine when i’m not using singularity and i am able to open the root file on the grid. However when i use singularity in ganga 
```python
j.virtualization = Singularity("docker://luxzeplin/offline_hosted:centos7_2")
j.virtualization.mounts = {'/cvmfs':'/cvmfs'}
```
 I get authentication failed:
```
Error in <TNetXNGFile::Open>: [FATAL] Auth failed
```
I compared the x509 envs for the dirac singularity and no singularity case and they seem the same:

```bash
#singularity
X509_CERT_DIR=/cvmfs/grid.cern.ch/etc/grid-security/certificates
X509_VOMS_DIR=/srv/localstage/condor/dir_11962/DIRAC_QaCrClpilot/etc/grid-security/vomsdir
X509_USER_PROXY=/srv/localstage/condor/dir_11962/tmpXLfkcq
#no_singularity
X509_CERT_DIR=/cvmfs/grid.cern.ch/etc/grid-security/certificates
X509_VOMS_DIR=/srv/localstage/condor/dir_1707/DIRAC_v6juUqpilot/etc/grid-security/vomsdir
X509_USER_PROXY=/srv/localstage/condor/dir_1707/tmpShG0nQ
```
I also ran the code locally without `j.backend = Dirac()` and i get the same root authentication error message so i don’t think it’s an issue with the grid. What am i doing wrong? The envs for x509 look right in both cases

-------
additionally given the problem with running in container locally I was wondering if it's a permissions problem so asked the user to try listing the proxy and looks like this is not possible.
-------------------

So within container it was able to able to view X509_CERT_DIR but it couldn’t access both the X509_VOMS_DIR  and X509_USER_PROXY . So that sounds like the issue so it cannot access the /srv/localstage:
```
X509_CERT_DIR=/cvmfs/grid.cern.ch/etc/grid-security/certificates
X509_VOMS_DIR=/srv/localstage/condor/dir_132066/DIRAC_ffJKCupilot/etc/grid-security/vomsdir
X509_USER_PROXY=/srv/localstage/condor/dir_132066/tmpS7aRBu
```

**Comment by asnaylor** [comment]
Mouting `srv` fixed the issue, now I can access the files on the grid in the Singularity container:
`j.virtualization.mounts = {'/cvmfs':'/cvmfs', '/srv':'/srv'}`
Should `srv` be mounted by default or is a site specific thing?

**Comment by alexanderrichards** [comment]
Seems like mounting the volume works but Ulrik did mention you could try:

```
export XRD_LOGLEVEL="Debug"
```
 
and compare inside and outside the Singularity container. Lots of useful information.

**Comment by egede** [comment]
Hi Andrew,

> Mouting `srv` fixed the issue, now I can access the files on the grid in the Singularity container:
> `j.virtualization.mounts = {'/cvmfs':'/cvmfs', '/srv':'/srv'}`
> Should `srv` be mounted by default or is a site specific thing?

Thanks for checking this out. The `/srv` is either a site specific or a `condor` specific thing, so it can lead to failures that are hard to debug later to just add it. I would like to understand what is going wrong though, so can I get you to return the stdout and stderr of a job that runs using Singularity.

```
source /cvmfs/sft.cern.ch/lcg/views/LCG_95apython3/x86_64-centos7-gcc8-opt/setup.sh
export XRD_LOGLEVEL="Debug"
echo ******
echo The PWD is: $PWD
echo ******
python -c "import ROOT; ROOT.TFile.Open('root://gfe02.grid.hep.ph.ic.ac.uk/pnfs/hep.ph.ic.ac.uk/data/lz/lz/data/MDC3/calibration/LZAP-4.3.1/20180201/lz_20180201234_lzap.root').Get('Events')"
```
Thanks,
       Ulrik.

**Comment by asnaylor** [comment]
I'm now getting an error with singularity on the dirac jobs. The job went to IC `LCG.UKI-LT2-IC-HEP.uk`:
```
<<<<<<<<<< exe-script.py Standard Output >>>>>>>>>>

Using singularity
Exception occured in downloading Singularity image: ['singularity', 'build', '--sandbox', 'singularity_sandbox', 'docker://luxzeplin/offline_hosted:centos7_2']
Err was: [Errno 2] No such file or directory
Exception occured in downloading Singularity image: ['singularity', 'build', '--sandbox', 'singularity_sandbox', 'docker://luxzeplin/offline_hosted:centos7_2']
Err was: [Errno 2] No such file or directory
Exception occured in downloading Singularity image: ['singularity', 'build', '--sandbox', 'singularity_sandbox', 'docker://luxzeplin/offline_hosted:centos7_2']
Err was: [Errno 2] No such file or directory
Exception occured in running process: ['singularity', '-q', 'exec', '--bind', '/srv/localstage/condor/dir_2925/DIRAC_SBIqyYpilot/25335055:/work_dir', '--no-home', '--bind', '/c\
vmfs:/cvmfs', '--bind', '/srv:/srv', 'singularity_sandbox', '/srv/localstage/condor/dir_2925/DIRAC_SBIqyYpilot/25335055/worker_node_script.sh']
Err was: [Errno 2] No such file or directory
/srv/localstage/condor/dir_2925/DIRAC_SBIqyYpilot/Linux_x86_64_glibc-2.17/bin:/srv/localstage/condor/dir_2925/DIRAC_SBIqyYpilot/Linux_x86_64_glibc-2.17/bin:/srv/localstage/cond\
or/dir_2925/DIRAC_SBIqyYpilot/scripts:/srv/localstage/condor/dir_2925/DIRAC_SBIqyYpilot/Linux_x86_64_glibc-2.17/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
PATH: /srv/localstage/condor/dir_2925/DIRAC_SBIqyYpilot/25335055:/srv/localstage/condor/dir_2925/DIRAC_SBIqyYpilot/Linux_x86_64_glibc-2.17/bin:/srv/localstage/condor/dir_2925/D\
IRAC_SBIqyYpilot/Linux_x86_64_glibc-2.17/bin:/srv/localstage/condor/dir_2925/DIRAC_SBIqyYpilot/scripts:/srv/localstage/condor/dir_2925/DIRAC_SBIqyYpilot/Linux_x86_64_glibc-2.17\
/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
PWD: /srv/localstage/condor/dir_2925/DIRAC_SBIqyYpilot/25335055
files on WN: ['job.info', 'worker_node_script.sh', 'jobDescription.xml', '_input_sandbox_30.tgz', '_python', 'exe-script.py']
 <<<<<<<<<< exe-script.py Standard Error >>>>>>>>>>

Traceback (most recent call last):
  File "/srv/localstage/condor/dir_2925/DIRAC_SBIqyYpilot/25335055/exe-script.py", line 60, in <module>
    rc = subprocess.call(execmd, env=runenv, shell=False)
  File "/srv/localstage/condor/dir_2925/DIRAC_SBIqyYpilot/Linux_x86_64_glibc-2.17/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/srv/localstage/condor/dir_2925/DIRAC_SBIqyYpilot/Linux_x86_64_glibc-2.17/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/srv/localstage/condor/dir_2925/DIRAC_SBIqyYpilot/Linux_x86_64_glibc-2.17/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by asnaylor** [comment]
What's odd is that my script was working fine last week

**Comment by egede** [comment]
As far as I understand the message, `singularity` should be available on all Tier 2 sites. The message looks like `singularity` is simply not in the PATH. A few comments.

- Most likely this is a mis-configuration at the Grid site and they should be contacted. @alexanderrichards , can you query with Daniela if there actually is an expectation that singularity should be in the PATH,
- You might be able to get the jobs to run using the `Docker` virtualisation. It will download the `udocker` wrapper and run the job using that (in reality quite similar to `singularity` but probably slightly less stable).
- We could add the ability to point to where the `singularity` binary can be found. In that way you could use something like `/cvmfs/atlas.cern.ch/repo/containers/sw/singularity/x86_64-el7/current/bin/singularity` but it seems a bit hacky to me. This will require a new Ganga release.

**Comment by egede** [comment]
Please file other questions or problems to Ganga as new Issues to make title reflect the topic.
