### ISSUE TITLE
singularity missing from dirac job $PATH

### ISSUE THREAD

**Issue by asnaylor** [ganga-devs/ganga#1671]
Original seen in issue https://github.com/ganga-devs/ganga/issues/1668#issuecomment-628647494: singularity couldn't be found in `$PATH` on a dirac job. Spoke to Daniela and it seems that singularity is now not expected on any site.

I am going to try installing the ganga pr https://github.com/ganga-devs/ganga/pull/1670 which @egede suggested and set the singularity binary to one on cvmfs.

**Comment by asnaylor** [comment]
I managed to install the ganga pr #1670 and run a singularity binary from cvmfs:
`j.virtualization.binary='/cvmfs/oasis.opensciencegrid.org/mis/singularity/current/bin/singularity'`

**Comment by egede** [comment]
Good to hear. It will go into the next Ganga release.
