### ISSUE TITLE
jobs.comment not lazy loading

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1687]
From the time it takes to print it looks as if `j.comment` is loading the whole job rather than just reading the index.

**Comment by egede** [comment]
Why would you expect the the `comment` attribute to be in the index? Is it not part of the summary information printed by `jobs` which I thought was the only thing going into the index. This will anyway be re-implemented for the database persistency, so I am not sure it is worth looking into.

**Comment by mesmith75** [comment]
It is in the summary for my ganga - I don't think I did anything special to set that up.

This is annoying me at the moment because it is slowing me down, so if it is easy I will fix it.

**Comment by egede** [comment]
Yes, it seems that you are right - I hadn't noticed because I never use it. Does this mean that lazy loading is broken completely, or is it only broken if the comment field is not `None`? I am a bit worried about what a field with an in principle unlimited length will do to the index files.

**Comment by mesmith75** [comment]
I think it is just comment. `j.name` prints instantly. I only noticed this because of issue #1689 forces me to store the job name in the comment.
