### ISSUE TITLE
Expose Dirac API to fetch replicas from specific sites

### ISSUE THREAD

**Issue by alexpearce** [ganga-devs/ganga#1695]
I would like to be able to filter a DIRAC dataset (`LHCbDataset`) based on where the files it refers to are replicated. I do this as I need some runtime feature only available at a certain site. My workflow is:

1. Run bookkeeping query to get all files
2. Filter files to keep those with replicas at site `X`
3. Submit job, restricting submissions to site `X`.

In Ganga this looks this:

    In [3]: bkq = BKQuery("/MC/Upgrade/Beam7000GeV-Upgrade-MagDown-Nu7.6-25ns-Pythia8/Sim09c-Up02/Reco-Up01/27163002/LDST")

    In [4]: ds = bkq.getDataset()

    In [5]: replicas = ds.getReplicas()

    In [6]: ds_cern = LHCbDataset([f"LFN:{lfn}" for lfn, pfns in replicas.items() if any("CERN" in site for site in pfns)])

    In [7]: j.inputdata = ds_cern

    In [8]: j.backend = Dirac()

    In [9]: j.backend.settings["Destination"] = "LCG.CERN.cern"

I understand that DIRAC has an API that allows one to fetch all replicas at a given site. This would simplify the filtering step above, so it would be nice to expose this in the `LHCbDataset.getReplicas` interface, say:

```
replicas_at_cern = ds.getReplicas(sites=["LCG.CERN.cern"])
ds_cern = LHCbDataset(replicas_at_cern.keys())
```

or something to that effect.

/cc @chrisburr

**Comment by mesmith75** [comment]
Sure we can do this - the splitter kind of does it already but we can add something to the BKQuery or LHCbDataset

**Comment by alexpearce** [comment]
Nice, thanks for considering it!

I did wonder if something even higher level would be appropriate. Being able to say "I want to submit only to sites X and Y; just do the best you can and drop any data you can't run over". But this is probably a bit too opaque/implicit, nicer to have the user explicitly request the data.

**Comment by mesmith75** [comment]
Let's start with making the selection for a single site in the `BKQuery.getDataset()` .

To use a list of sites may need some adjustment of the splitter logic. As data is replicated fairly randomly it could make sets that are common to a third site you don't want to run at, but won't be completely satisfied by the sites you do.
