### ISSUE TITLE
LHCbTasks background loop

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#17]
[Copied from JIRA https://its.cern.ch/jira/browse/GANGA-2038]

Hi,
Sometimes the tasks background thread spits out the following error:
```python
Ganga.GPIDev.Lib.Tasks : ERROR Full traceback:
Traceback (most recent call last):
File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r8/install/ganga/python/Ganga/GPIDev/Lib/Tasks/TaskRegistry.py", line 144, in _thread_main
p.update()
File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r8/install/ganga/python/Ganga/GPIDev/Lib/Tasks/ITask.py", line 101, in update
if trf.update() and not self.check_all_trfs:
File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r8/install/ganga/python/Ganga/GPIDev/Lib/Tasks/ITransform.py", line 241, in update
unit.getID(), self.getID(), task.id))
File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r8/install/ganga/python/Ganga/GPIDev/Lib/Tasks/ITransform.py", line 180, in getID
return task.transforms.index(self)
File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r8/install/ganga/python/Ganga/GPIDev/Lib/GangaList/GangaList.py", line 386, in index
return self._list.index(self.strip_proxy(obj))
ValueError: <GangaLHCb.Lib.Tasks.LHCbTransform.LHCbTransform object at 0x7fe54a4b7310> is not in list
Ganga.GPIDev.Lib.Tasks : INFO Some Transforms of Task 121 'D2KShh realdata' have been paused. Check tasks.table() for details!
```
Somehow this also resets the 'float' of the Task to zero when it pauses it.
I haven't noticed anything really bad happening to the task afterwards, if I start it again things seem to keep going.
As it happens in a background thread it's hard to tell exactly what triggers the error. It came immediately after a job from that Task had finished submitting:
```python
Ganga.GPIDev.Adapters : INFO submitting job 292.53 to Dirac backend
Ganga.GPIDev.Lib.Job : INFO job 292.53 status changed to "submitting"
Ganga.GPIDev.Lib.Job : INFO job 292 status changed to "submitting"
Ganga.GPIDev.Lib.Job : INFO job 292.53 status changed to "submitted"
Ganga.GPIDev.Lib.Job : INFO job 292 status changed to "submitted"
Ganga.GPIDev.Lib.Tasks : ERROR Full traceback: <see above>
```
where 292.53 is the last subjob of 292.
I realise this isn't a huge amount to go on, but thought I'd open a ticket as a place to collate information about future occurrences.
Thanks, Olli

**Comment by drmarkwslater** [comment]
Hi Olli,

Quick question: Are you using the 'submit_with_threads' option? Or similar? 

Thanks!

Mark

**Comment by olupton** [comment]
Hi Mark,

I have Transforms that do/don't use submit_with_threads so I'm not sure if the error is correlated with the option. I'm pretty sure the job 292 in the bug report was from a Transform with submit_with_threads = False, but unfortunately I've since deleted it. I'll be sure to check next time I see the error.

Cheers, Olli

**Comment by alexanderrichards** [comment]
> line 144, in _thread_main

looks like it's running in the main thread
> return self._list.index(self.strip_proxy(obj)) 
> ValueError: < GangaLHCb.Lib.Tasks.LHCbTransform.LHCbTransform object at 0x7fe54a4b7310 > is not in list

looks like the Transform that you are searching for with list.index is not there.

my quick two cents :smile:

**Comment by drmarkwslater** [comment]
@olupton : Actually it doesn't matter - I realised after I sent that it wouldn't have made a difference anyway :) However, do you use LHCbTask.addQuery() at all? This may have an effect, I'm not sure...

@alexanderrichards What's weird is that to have even run this code, it's gone through the following in ITask.py:

        for trf in self.transforms:
            if trf.status != "running":
                continue

            if trf.update() and not self.check_all_trfs:
                break

Which means the object *has* to be there. I'm guessing python just compares object pointers in the 'index' function of a list, right? If so, I suspect I may just put in protection for the error and have to leave it at that :(

**Comment by alexanderrichards** [comment]
> return task.transforms.index(self)

looking at this line in your traceback, should it not read:
```python
task.transforms.index(trf)
```

?

**Comment by rob-c** [comment]
Hi Mark,

Could it be that the transform has been added to the GangaList with a proxy?
This would cause GangaList to get confused when it searches for the element after stripping the proxy first.

I'll have a glance at the code and see if this could be happening

Rob

**Comment by alexanderrichards** [comment]
this would be happening when your adding the transform to the task

**Comment by rob-c** [comment]
This looks like it happens if the user adds the transform interactively as the list is initialized as a raw list 'transforms = []'

As the transform has the proxy interactively I think adding the proxy interactively and running would lead to this happening. This should reproduce the problem and you should be able to dump the ganga-list to verify if the proxy is causing this confusion.

The simplest solution is probably to run stripProxy on the transform before inserting into the list in this case.

**Comment by drmarkwslater** [comment]
Hmmm... That sounds possible but I don't understand why it only *sometimes* happens. There are a few other calls to this .getID function, most notably whenever a job is created and I guess they are working OK.

@olupton Could you send me a typical Task that you are running? i.e. the submission script? And are you doing anything at all to the task after submission? How reproducible is the problem - i.e. would I need 5-10 tasks running or does it happen with just one?

Thanks!

**Comment by olupton** [comment]
Hi Mark,

Again I use .addQuery() in some places and not others; the Task I pasted the error from did not use it though.

I pasted the submission script here:
https://gist.github.com/olupton/948cb5b5236bbb7118be
although it depends on some helper functions in my .ganga.py so presumably won't run for you.

I don't think I'm doing anything special, the recent times it's happened have been when I haven't touched anything for a while. Typically I guess I have O(5) tasks running; the problem doesn't show up frequently enough (probably O(5-10) times in total) to really be sure about it correlating with anything.

(I realise this isn't phenomenally helpful, but at least it's giving me ideas of what to check next time I see the issue!)

Cheers, Olli

**Comment by drmarkwslater** [comment]
So after discussions with @milliams it seems that actually using the 'index' function here is a bad idea because it will go down to __eq__ functions that will loop over the whole schema (which can be big for a Transform) and compare each item. I've therefore decided to fix the id for Tasks/Transforms/Units when they are added and just store this id in the schema. This should hopefully solve this problem!
