### ISSUE TITLE
GangaGUI/gui_db.sqlite is wrong location

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1723]
Hi Varun,

I just noticed that when running Ganga with the `--webgui` option, it creates the file `GangaGUI/gui_db.sqlite` inside the Ganga source code. You can't assume that you have write access to this location (in general user will have Ganga installed on a shared file system where they do not have write access). I think the file should go inside the `gangadir` instead.

**Comment by varunbankar** [comment]
Okay I'll shift the location. I guess I'll be able to get the location of gangadir using the config. Also should I shift to the root of gangadir or inside a particular folder like GangaGUI inside gangadir?

**Comment by egede** [comment]
Hi Varun. Did this issue get solved? Can i close the issue?

**Comment by varunbankar** [comment]
Yes, this issue has been resolved. It can be closed
