### ISSUE TITLE
Support for NERSC submission via Slurm

### ISSUE THREAD

**Issue by asnaylor** [ganga-devs/ganga#1729]
I'd like to submit jobs on the cori supercomputer at NERSC using ganga. In theory this is possible as NERSC uses Slurm which is a ganga supported backend.

When I try a simple test job without changing the default ganga Slurm config, I got this error:
```python
INFO     reading config file /global/homes/a/asnaylor/.gangarc
INFO     reading config file /global/homes/a/asnaylor/.gangarc
INFO     reading config file /global/homes/a/asnaylor/.gangarc
INFO     reading config file /global/homes/a/asnaylor/.gangarc
INFO     reading config file /global/homes/a/asnaylor/.gangarc
Submssion Mode...
INFO     submitting job 0
INFO     job 0 status changed to "submitting"
INFO     Preparing Executable application.
INFO     Created shared directory: conf-db855e73-2959-49c6-ab9e-39945db61c83
INFO     Preparing subjobs
INFO     Submitting a prepared application; taking any input files from conf-db855e73-2959-49c6-ab9e-39945db61c83
WARNING  could not match the output and extract the Batch job identifier!
WARNING  command output
 sbatch: error: No architecture specified, cannot estimate job costs.
sbatch: error: Batch job submission failed: Unspecified error
ERROR    Parallel Job Submission Failed: IncompleteJobSubmissionError: ('0', 'submission failed')
INFO     job 0 status changed to "new"
WARNING  Not all subjobs have been sucessfully submitted: IncompleteJobSubmissionError: (['0'], "submission failed for subjobs ['0']")
Traceback (most recent call last):
  File "/global/u2/a/asnaylor/.conda/envs/ganga_test/lib/python3.7/site-packages/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 1556, in submit
    r = self.backend.master_submit( rjobs, jobsubconfig, jobmasterconfig, keep_going, self.parallel_submit)
  File "/global/u2/a/asnaylor/.conda/envs/ganga_test/lib/python3.7/site-packages/ganga/GangaCore/GPIDev/Adapters/IBackend.py", line 183, in master_submit
    incomplete_subjobs, 'submission failed for subjobs %s' % incomplete_subjobs)
GangaCore.Core.exceptions.IncompleteJobSubmissionError: IncompleteJobSubmissionError: (['0'], "submission failed for subjobs ['0']")
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/global/u2/a/asnaylor/.conda/envs/ganga_test/lib/python3.7/site-packages/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 573, in updateStatus
    state = self.status_graph[initial_status][newstatus]
KeyError: 'failed'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "ganga_test_job.py", line 46, in <module>
    main()
  File "ganga_test_job.py", line 14, in main
    functions[args.mode](args)
  File "ganga_test_job.py", line 30, in submit
    j.submit()
  File "/global/u2/a/asnaylor/.conda/envs/ganga_test/lib/python3.7/site-packages/ganga/GangaCore/GPIDev/Base/Proxy.py", line 720, in proxy_wrapped
    r = f(*s_args, **s_kwargs)
  File "/global/u2/a/asnaylor/.conda/envs/ganga_test/lib/python3.7/site-packages/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 1580, in submit
    self.updateStatus('failed')
  File "/global/u2/a/asnaylor/.conda/envs/ganga_test/lib/python3.7/site-packages/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 579, in updateStatus
    raise JobStatusError('forbidden status transition of job %s from "%s" to "%s"' % (fqid, initial_status, newstatus))
GangaCore.GPIDev.Lib.Job.Job.JobStatusError: JobStatusError: forbidden status transition of job 0 from "new" to "failed"
INFO     Stopping Job processing before shutting down Repositories
INFO     Shutting Down Ganga Repositories
INFO     Registry Shutdown
``` 

What do i need to change in the `.gangarc` to get it working?

I've linked an example [MPI job script file](https://docs.nersc.gov/jobs/examples/#basic-mpi-batch-script) from the NERSC website.

**Comment by asnaylor** [comment]
I managed to submit a job with this script:
```python
import argparse
import os
import stat

import ganga.ganga
from ganga import Job, Slurm, File, Executable, LocalFile

def main():
    parser = argparse.ArgumentParser(description='Ganga job submission')
    parser.add_argument('mode', action='store',help='modes',choices=['submit'])
    parser.add_argument('-j','--job_number', default=None, nargs='+', action='store', help='put ganga job number(s)')

    args = parser.parse_args()
    functions[args.mode](args)


def submit(args):
    print("Submssion Mode...")

    #sort the permission out for script (chmod +x)
    os.chmod('worker_node_script.sh', os.stat('worker_node_script.sh').st_mode | stat.S_IEXEC )

    with open('job_list.log', 'a') as job_list:
        j = ganga.Job()
        j.application=Executable(exe=File('worker_node_script.sh'), args=[])
        j.inputfiles = [LocalFile('input_text_file.txt')]
        j.outputfiles = [LocalFile('worker_node.log'), LocalFile('*.list')]

        j.backend = Slurm()
        SBATCH = '-A lz '
        SBATCH+= '-q debug '
        SBATCH+= '-t 00:02:00 '
        SBATCH+= '-N 1 '
        SBATCH+= '-C haswell '
        SBATCH+= '--module=cvmfs '
        SBATCH+= '--image=luxzeplin/offline_hosted:centos7_1 '
        SBATCH+= '-L SCRATCH,cfs '
        SBATCH+= '-J lz_debug_job '

        j.backend.extraopts=SBATCH
        j.submit()
        job_list.write("ganga Job ID={}\n".format(j.id))
    return

functions = {'submit': submit}

if __name__ == "__main__":
    main()
    pass

```
The job ran sucessfully and i was able to get the output files and see the job log without changing any of the `.gangarc`. Although i did see this error when submitting but the job ran okay:
```python
INFO     Preparing subjobs
INFO     Submitting a prepared application; taking any input files from conf-fb186418-611c-49a6-a2e0-d91e9b9e2bc0
INFO     could not match the output and extract the Batch queue name
INFO     job 2 status changed to "submitted"
```

But it's missing the normal OpenMP setting i would put into the job_script like this:
```bash
#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
```
And also i normally specify the number tasks per node and cores per task in the srun line e.g. `srun -n 1 -c 64 --cpu_bind=cores ./worker_node_script.sh`

How can i add the openmp settings and the srun command line options?

**Comment by egede** [comment]
Ok, let me take the easy ones first. To avoid the long SBATCH lines in your script, you can simply put the ones that you never change into the default in your `.gangarc`. 

```
[defaults_Slurm]
extraopts=-A lz -t 00:02:00 -N 1 -C haswell --module=cvmfs --image=luxzeplin/offline_hosted:centos7_1 -L SCRATCH,cfs
```
I would avoid putting the queue name in there as it already has a separate attribute in the backend object.

Not being able to extract the batch queue name is really just a spurious error and only matters for bookkeeping. I would just ignore it.

**Comment by egede** [comment]
Are the `OpenMP` settings just environment variables that need to be defined at runtime? If yes, then you can set them in the `Executable` application object as a dictionary.

```
j.application.env = {'OMP_NUM_THREADS': '1', 'OMP_PLACES':'threads', 'OMP_PROC_BIND': 'spread'}
```

**Comment by egede** [comment]
I am not that familiar with SLURM, so find it a bit confusing how `srun` works. However, if I look at one of the examples from the web page that you give
```bash
#!/bin/bash
#SBATCH --qos=debug
#SBATCH --time=5
#SBATCH --nodes=7
#SBATCH --ntasks=28
#SBATCH --cpus-per-task=16
#SBATCH --constraint=haswell

export OMP_PROC_BIND=true
export OMP_PLACES=threads
export OMP_NUM_THREADS=8

srun --cpu-bind=cores check-hybrid.intel.cori

```
it looks to me as if the `srun` command is simply just part of the script that is executed on a worker node (rather than being part of the submission). I find it a somewhat odd two-level system. In your case, I would probably just make a small wrapper script (let's call it `wrapper.sh`) and then do something like

```bash
% cat wrapper.sh
#!/bin/bash
srun -n 1 -c 64 --cpu_bind=cores ./worker_node_script.sh
```
and then in Ganga have the job as
```python
j = ganga.Job()
j.application=Executable(exe=File('wrapper.sh'), args=[])
j.inputfiles = [LocalFile('input_text_file.txt'), LocalFile('worker_node_script.sh')]
j.outputfiles = [LocalFile('worker_node.log'), LocalFile('*.list')]
```
In your example, I am a bit confused about from which directory the `worker_node_script.sh` file is picked up from.

**Comment by egede** [comment]
Finally, you run Ganga from an import in python, rather than starting `ganga` and then submitting a job. That is fine (and fully supported), but I am surprised by the line
```python
        job_list.write("ganga Job ID={}\n".format(j.id))
```
in your example. One of the main points about Ganga is that by starting a Ganga session, you can use Ganga to do all the bookkeeping for you. Here it seems like you do some DIY bookeeping as well.

**Comment by asnaylor** [comment]
> Ok, let me take the easy ones first. To avoid the long SBATCH lines in your script, you can simply put the ones that you never change into the default in your `.gangarc`.
> 
> ```
> [defaults_Slurm]
> extraopts=-A lz -t 00:02:00 -N 1 -C haswell --module=cvmfs --image=luxzeplin/offline_hosted:centos7_1 -L SCRATCH,cfs
> ```
> 
> I would avoid putting the queue name in there as it already has a separate attribute in the backend object.
> 
> Not being able to extract the batch queue name is really just a spurious error and only matters for bookkeeping. I would just ignore it.

Yeah I appreciate that there are some variables which won't change job to job so i could just add them into the `.gangarc`. For the queue name i've seen in the `queue_name ` variable in `.gangarc` but can you change that in ganga like `j.backend.queue_name = 'debug'` as this might change from job to job?

**Comment by asnaylor** [comment]
> Are the `OpenMP` settings just environment variables that need to be defined at runtime? If yes, then you can set them in the `Executable` application object as a dictionary.
> 
> ```
> j.application.env = {'OMP_NUM_THREADS': '1', 'OMP_PLACES':'threads', 'OMP_PROC_BIND': 'spread'}
> ```

I am not sure, I think you're right though.


> I am not that familiar with SLURM, so find it a bit confusing how `srun` works. However, if I look at one of the examples from the web page that you give
> 
> ```shell
> #!/bin/bash
> #SBATCH --qos=debug
> #SBATCH --time=5
> #SBATCH --nodes=7
> #SBATCH --ntasks=28
> #SBATCH --cpus-per-task=16
> #SBATCH --constraint=haswell
> 
> export OMP_PROC_BIND=true
> export OMP_PLACES=threads
> export OMP_NUM_THREADS=8
> 
> srun --cpu-bind=cores check-hybrid.intel.cori
> ```
> 
> it looks to me as if the `srun` command is simply just part of the script that is executed on a worker node (rather than being part of the submission). I find it a somewhat odd two-level system. In your case, I would probably just make a small wrapper script (let's call it `wrapper.sh`) and then do something like
> 
> ```shell
> % cat wrapper.sh
> #!/bin/bash
> srun -n 1 -c 64 --cpu_bind=cores ./worker_node_script.sh
> ```
> 
> and then in Ganga have the job as
> 
> ```python
> j = ganga.Job()
> j.application=Executable(exe=File('wrapper.sh'), args=[])
> j.inputfiles = [LocalFile('input_text_file.txt'), LocalFile('worker_node_script.sh')]
> j.outputfiles = [LocalFile('worker_node.log'), LocalFile('*.list')]
> ```
> 
> In your example, I am a bit confused about from which directory the `worker_node_script.sh` file is picked up from.

Yeah i think you're right that `srun` is executed on a worker node so maybe the variables just need to be exported before `srun` is called. 
The `worker_node_script.sh` is just in the local directory where i call the ganga script.

**Comment by asnaylor** [comment]
> Finally, you run Ganga from an import in python, rather than starting `ganga` and then submitting a job. That is fine (and fully supported), but I am surprised by the line
> 
> ```python
>         job_list.write("ganga Job ID={}\n".format(j.id))
> ```
> 
> in your example. One of the main points about Ganga is that by starting a Ganga session, you can use Ganga to do all the bookkeeping for you. Here it seems like you do some DIY bookkeeping as well.

I like to be able to run my ganga job as a script and not interactively and so i just want to keep track of what was the last ganga job number

**Comment by egede** [comment]
> I like to be able to run my ganga job as a script and not interactively and so i just want to keep track of what was the last ganga job number

That is fine. Just keep in mind that the monitoring of Ganga (that tracks what has completed etc) require a Ganga process to run. You might not need that monitoring though.

**Comment by egede** [comment]
One could consider if there is a way to natively support this `sbatch` feeds into `srun` paradigm of SLURM. That would require a new backend class.

Please close this issue if you feel all questions are answered for now.

**Comment by asnaylor** [comment]
Thanks, this has been really helpful.
