### ISSUE TITLE
Limit ganga workers for Local backend

### ISSUE THREAD

**Issue by asnaylor** [ganga-devs/ganga#1733]
I would like to be able to limit the new of jobs running on my local machine when using ganga. I was testing the `Local()` backend with `GenericSplitter()` and it spawn new processes until it couldn't anymore. I ran a job which had 30 files and it ran 30 instances of the executable script. Is there any way to control the number of concurrent processes without using `Task` objects?

**Comment by egede** [comment]
This is currently not possible. Not a completely trivial change as it would require some sort of queue to be implemented for Local jobs

**Comment by asnaylor** [comment]
Is this something the ganga devs are interested in adding? If so what would be the timeframe?

**Comment by egede** [comment]
I have labelled this as a "good first issue" as it is quite decoupled from the rest of Ganga and could be picked up by an external contributor. I do not see it done by anybody from the core team in the short term. I think the best implementation would be by implementing the bulk submit function. That could then spawn an independent process that would limit the number of simultaneous subjobs completely independent of Ganga.

**Comment by egede** [comment]
The number of jobs running simultaneously should be a configurable in the `[Local]` section of the configuration. Maybe the default value could be `auto` but a fixed number like `8` could be set as well. The meaning of `auto` would be that it is limited to the number of available cores.

**Comment by asnaylor** [comment]
Thanks, this is great 👍🏻
