### ISSUE TITLE
Length of LHCbCompressedDataset.files is misleading

### ISSUE THREAD

**Issue by chrisburr** [ganga-devs/ganga#1741]
I thought I had already seen this reported somewhere but I can't find it, apologies if this is a duplicate.

When testing Ganga against `v10r1-pre6` I noticed the length of a dataset is misleading and you now have to sum over each element in the returned value instead of just using `len`:
```python
[11:09:41]
Ganga In [40]: dataset = BKQuery( type='Path', dqflag='OK', path=bkpath ).getDataset()
         ...: print(len(dataset.files))
         ...: print([len(x) for x in dataset.files])
1
[213]
```

**Comment by mesmith75** [comment]
The `len(dataset)` is correct though.

This is a bit tricky as `dataset.files` really should be of length 1 but I'll look into it.

**Comment by mesmith75** [comment]
So there is nothing we can do about it unfortunately - it was a poor design choice to label the schema in the way it was. Unfortunately the only way to fix it is to amend the schema but that would break loading old jobs so we are too committed. At some point I would like to introduce an improved version of the compressed dataset though and make that the default.

**Comment by chrisburr** [comment]
That seems like a reasonable conclusion given the constraints. Thanks for looking into this @mesmith75
