### ISSUE TITLE
Compile GaudiExec in a container

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1745]
slc6 is about to disappear. There is still a use case for users and releases that are only on slc6 - we need to be able to build the applications in a container.

**Comment by egede** [comment]
In principle a "pre-command" should be able to do this. So
```bash
source /cvmfs/lhcb.cern.ch/lib/LbEnv && lb-sdb-query listPlatforms %s %s
```
would turn into
```bash
udocker run slc6-image source /cvmfs/lhcb.cern.ch/lib/LbEnv && lb-sdb-query listPlatforms %s %s
```
The `lb-docker-run` command is not suitable for this unless changed as it has `docker` hardwired into it and thus will not work with neither `udocker` nor `singularity`. In principle, we could just use a standard `slc6` image and mount `/cvmfs` from the server.

**Comment by egede** [comment]
We could add `udocker` as a special LHCb dependency to make sure that it is there.

**Comment by mesmith75** [comment]
`lb-run` has an option to run the command inside a container:

```
  --container=CONTAINER
                        wrap the command to run in a container supporting the
                        requested platform [allowed values: singularity]
```
which looks like:

```
(LHCb Env) [masmith@lxplus781]~$ lb-run --container=singularity -c x86_64-slc6-gcc49-opt DaVinci/v39r1p6 gaudirun.py
WARNING: container does not have /.singularity.d/actions/exec, calling env directly
# setting LC_ALL to "C"
ApplicationMgr    SUCCESS 
====================================================================================================================================
                                                   Welcome to DaVinci version v39r1p6
                                          running on lxplus781.cern.ch on Mon Jul 27 08:18:19 2020
====================================================================================================================================
ApplicationMgr       INFO Application Manager Configured successfully
HistogramPersis...WARNING Histograms saving not required.
ApplicationMgr       INFO Application Manager Initialized successfully
ApplicationMgr       INFO Application Manager Started successfully
EventSelector        INFO End of event input reached.
EventLoopMgr         INFO No more events in event selection 
ApplicationMgr       INFO Application Manager Stopped successfully
EventLoopMgr         INFO Histograms converted successfully according to request.
ToolSvc              INFO Removing all tools created by ToolSvc
ApplicationMgr       INFO Application Manager Finalized successfully
ApplicationMgr       INFO Application Manager Terminated successfully

```
I don't know if we can use that to build a development environment?

**Comment by egede** [comment]
> I don't know if we can use that to build a development environment?

Yes, I guess that should work. A few tricky issues are
1. Not obvious that everywhere has Singularity in PATH. We can take one from /cvmfs, but a complication.
2. Do we need some nasty table inside Ganga that decides if we need this option or not, based on a regexp of the platform string (sounds fragile).
3. If already running inside a Singularity container (like I do on my desktop), this will not work. But it actually opens up the alternative of *not* running inside an slc7 container and just build everything inside a container.

So maybe the solution to point 2., is to always run inside a container for the LHCb s/w commands.

**Comment by mesmith75** [comment]
I think this is a non-issue. It looks as if things are already working submitting slc6 jobs from centos7.
