### ISSUE TITLE
checkDiskQuota possibly not working

### ISSUE THREAD

**Issue by rmatev** [ganga-devs/ganga#1746]
To reproduce, start `ganga --debug` and type

```
from GangaCore.Runtime.Repository_runtime import checkDiskQuota
checkDiskQuota()
```

which shows

```
DEBUG    Error checking disk partition: a bytes-like object is required, not 'str' (Repository_runtime.py:93)
```

**Comment by mesmith75** [comment]
It works for me on AFS. Where is your gangadir located?

**Comment by rmatev** [comment]
it's in `/home` but is a symlink to another volume

```
ls -l  /home/rmatev/gangadir
lrwxrwxrwx. 1 rmatev z5 17 12 jun  2019 /home/rmatev/gangadir -> /mnt/tmp/gangadir
```

**Comment by rmatev** [comment]
as far as I see, https://github.com/ganga-devs/ganga/blob/bc950b4c7135d9c80698c0427a998eee6a7ca476/ganga/GangaCore/Runtime/Repository_runtime.py#L80 is raising because `output` is of type `bytes`. I can't quite see the difference between AFS and no AFS, both code paths seem to have the output in binary mode.

**Comment by mesmith75** [comment]
Ah no you are right, I hadn't noticed the error wasn't being raised. I'll fix that. Thanks for bringing this up!
