### ISSUE TITLE
ganga-gui not installed with pip

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1776]
ganga-gui is not being put in bin along with ganga when I install with pip

**Comment by egede** [comment]
Just as well that we have not announced it yet then. I wonder if it just needs adding to the list at https://github.com/ganga-devs/ganga/blob/1d6130f7f0a592f12a022d8a95e1c48fe2e3ba0b/setup.py#L84

**Comment by alexanderrichards** [comment]
> Just as well that we have not announced it yet then. I wonder if it just needs adding to the list at
> 
> https://github.com/ganga-devs/ganga/blob/1d6130f7f0a592f12a022d8a95e1c48fe2e3ba0b/setup.py#L84

indeed

**Comment by mesmith75** [comment]
It also needs to ship the package data because there are a lot of html files needed.
