### ISSUE TITLE
Remove psutil from the database

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1787]
Is it possible to remove `psutil` from the database code. This requires some compiling - we would prefer not to have any compiled dependencies. Indeed this doesn't work on lxplus now.

**Comment by DumbMachine** [comment]
One way would be to write code to do all the things that `psutil` does. (psutil is only used to know whether db is running or not)
This can be done using subprocess calls.
Find the `pid` for the mongo db process:
```bash
❯ ps -aux | grep mongo
dumbmac+   26951  0.5  1.2 1583756 99320 pts/0   Sl+  02:22   0:03 mongod --bind_ip_all
```
And then parse the environ vars to perform checks
```bash
❯ cat /proc/26951/environ
```
This is not hard to do and would remove the dependency. If the implementation using `subprocess` calls seems fine then I will implement it.
Other ideas are also welcome.

**Comment by mesmith75** [comment]
looks good
