### ISSUE TITLE
Clean up import ganga code and start using this in tests

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#180]
After discussions with @milliams we think it would be good to get the little ganga stuff properly cleaned up and understood so we can then know exactly what's done at startup. In addition, the exit handlers should be able to be run independently of the atexit versions. We can then have tests such as:

``` python
class TestStartup(unittest.TestCase):
   @safe_shutdown    # decorator to run proper shutdown code
   def test_startup_submit(self):
      from ganga import *
      j = Job()
      j.submit()
      monitorUntilCompleted(j)    # Or something similar

   # Note: Don't care about the shutdown here so no decorator
   def test_checkjob_persist(self):
      from ganga import *
      assertEqual(len(jobs), 1)
```

This will do away with all the GangaTestCase stuff, be much closer (~the same) as what user will actually do and as a by product, I may be able to clean up the bootstrap code :)

**Comment by alexanderrichards** [comment]
> In addition, the exit handlers should be able to be run independently of the atexit versions.

All sounds good to me. I didn't fully understand what you meant by the above though.



> This will do away with all the GangaTestCase stuff,

:+1:

**Comment by drmarkwslater** [comment]
@alexanderrichards Basically, if you just run a test such as:

```
class TestStartup(unittest.TestCase):
   def test_startup_submit(self):
      from ganga import *
      j = Job()
      j.submit()
      monitorUntilCompleted(j)   
```

Then everything will get unloaded/destroyed but e.g. your job may not get flushed to disk. If you add the decorator, this can add the call to anything that is added to atexit and properly flush, etc. It may be a separate function isn't needed and it can all be put in the decorator, but it may be nice just to have everything properly documented and separated: e.g. `atstartup()` and `atshutdown` functions in `ganga/__init__.py`

**Comment by rob-c** [comment]
I don't understand what you mean by: 'the exit handlers should be able to be run independently of the atexit versions'.

Are you planning to scrap the Shutdown function or still make use of it in the future but only when ganga is shutdown at the end. 

I'd strongly argue we want to do a full shutdown between all of the tests in a tearDown anyway. If you can reduce the startUp in the GangaUnittest to be basically ```import ganga``` or even remove it then I'm happy to have the startup understood and safe.

**Comment by rob-c** [comment]
Just to confirm are we wanting ```import ganga``` to trigger loading of the monitoring?

**Comment by milliams** [comment]
@rob-c We will not want `import ganga` to start the monitoring, no. When running unit/integration tests we will manually run the monitoring loop and when running interactively we will expect the user to run `start_monitoring()` or similar.

**Comment by drmarkwslater** [comment]
@rob-c I just mean that we can run the Shutdown 'manually'. In the example above, you wouldn't get a full tearDown because the atexit stuff isn't being called so the decorator would supply that in whatever way is currently done when the `atexit` handlers **are** called. I realise this is something that GangaTestCase does do in theory but it seems that is having problems and also that would be the only reason to keep GangaTestCase over the normal Python test stuff. If the Ganga shutdown code can be in one (and only one) place and just called when needed in a test, then we should be able to simplify things.

Now, the point about doing a full shutdown after every test is up for debate. Personally, I feel that most (but certainly not all) tests don't need the full shutdown and in fact shouldn't care about it. If all you want to do is some unit tests or basic GPI tests, you shouldn't need to fully shutdown everything. However, I can see a reason for doing this as well. Anyway, none of this is happening soon anyway so we can discuss and come to a consensus.

**Comment by rob-c** [comment]
In your model I would agree this isn't a problem if Ganga is guaranteed to startup in a clean __empty__ repo for every test but at the moment there isn't anything to allow for this from what I can see.

We'd need to introduce some ability to wipe the repo on exit between some tests to avoid future tests doing the (sensible) thing of accessing jobs(0) and getting something they don't expect.

I don't like the notion of not flushing everything to disk as doing something as 'simple' as this has exposed numerous problems in the past.

At the very least this would require a dummy testing repo to be written which just 'pass'-es any calls to things like flush or startup/shutdown.
This could be very nice to have for testing btw as it would speed up tests not concerned with persistence immensely.

Allowing the user to start or stop the monitoring code on demand is a nice idea and I'm on board with this 110% but currently we have problems just starting/stopping it __once__ per Ganga session in a reliable way.
Doing this potentially multiple times for different tests I think will expose a lot of still broken behaviour.

I think we can discuss this in more detail in the next group meeting

**Comment by milliams** [comment]
On the point of monitoring I spent some time today writing a replacement for the monitoring code. It does most of what we need and is currently about 120 lines of code. It will certainly be longer by the time it has all the necessary features but still an order of magnitude less than the current code. One of the things it provides is the ability to stop and restart monitoring at will. Again, a topic of the meeting.

**Comment by rob-c** [comment]
@milliams I'd be keen to see the ability to break the monitoring kept as it took long enough to implement in the current system.

Would it be possible to strip down ```master_updateMonitoringInformation``` to be a minimal method and handle the number of subjobs we pass to the backend in the monitoring code directly?
I'm thinking of moving the current code from there mostly into the monitoring loop and having the backend functions be really simple function that to zeroth order just redirects to the correct function from the backend class.

If we get rid of the AFSToken and Grid credential checking from the current loop then the amount of code needed reduces by a factor of 10 easily as I'm sure you're seeing :)

**Comment by alexanderrichards** [comment]
> and is currently about 120 lines of code

:+1: 

> reduces by a factor of 10 easily

:+1: 
All good!
