### ISSUE TITLE
depreceated Job.sandboxfield recommended in config file

### ISSUE THREAD

**Issue by jonas-eschle** [ganga-devs/ganga#1800]
In the .gangarc there is a field specifying the sandboxoutput_types. It's written that this can be overriden by "...the user in a specific job via the Job.outputsandbox field". The latter [is depreceated](https://github.com/ganga-devs/ganga/blob/b3ae7335f8e952e00122f28c06e421091d9a8e4c/ganga/GangaCore/GPIDev/Lib/Job/Job.py#L2136)

https://github.com/ganga-devs/ganga/blob/873f92ac2bea5ed3bc73665d40acbf8621d0100c/ganga/GangaLHCb/__init__.py#L53

Should we change the .gangarc and remove this recommendation (and configuration option?)

**Comment by mesmith75** [comment]
No, this is right as it is. Sandbox here is more referring to what we get back from Dirac. Perhaps the docstring should be updated though to say `outputfiles`.
