### ISSUE TITLE
Remove subjob in a job of multiple subjobs

### ISSUE THREAD

**Issue by VukanJ** [ganga-devs/ganga#1806]
Dear ganga developers,
Quite often one has resubmit failed subjobs as another job and reconfigure the splitter so that the one problematic input data file can be found. I do not think that there is a way to split a subjob into more subjobs, right? So ideally it would be good to be able to remove the failed subjobs in the original job so that one does not process the same data twice by accident (e.g. by resetting the backend / resubmitting / etc). `jobs(X).subjobs(Y).remove()` does not work even though subjobs have a `remove()` method. Is there a reason why remove() cannot be applied to subjobs?
Thank you for your help

**Comment by egede** [comment]
It is by construction that this is not possible. The idea behind it is that if a dataset is split into subjobs, then the sum of the dataset in the subjobs, should be equal to the dataset in the parent. If you delete subjobs, you break that link. There is a different proposal in #1669 that might deal with your issue when implemented.

**Comment by egede** [comment]
I suggest that further discussion goes on in #1669 so plan to close this one soon.

**Comment by VukanJ** [comment]
Thank you for that answer, it is good to have the reassurance that resubmitting failed jobs with another splitter setting is the recommended way of processing data. (When splitting is neccessary)
