### ISSUE TITLE
Job stuck in running

### ISSUE THREAD

**Issue by VukanJ** [ganga-devs/ganga#1807]
Dear ganga developers,
Recently, some of my jobs get stuck in the "running" mode even though every single subjob is completed. I don't know how to reproduce this, it may have happened after the grid certificate expired a couple of times, but is there a way to force such a job to "completed" or at least to update its state? This may be just a cosmetic problem, not 100% sure

**Comment by mesmith75** [comment]
If you do `j.backend.reset()` it should work

**Comment by VukanJ** [comment]
`ERROR: GangaAttributeError: Object 'Local' does not have attribute: 'reset'`
Maybe I should have mentioned that I am using the Local backend. Also, according to the backend reset stdout, it only applies to failed and completing jobs, so if it has other side effects one could reformulate this prompt?

**Comment by egede** [comment]
For the `Local` backend, this is a really odd situation. Can you please try to do
```python
j = jobs(X)
report(j, LocalFile)
```
where `X` is the id of one of the jobs having this behaviour. Then please make the file produced available to me in some non-public way.

**Comment by VukanJ** [comment]
I am sorry, but I have since deleted the ganga job, but I still have the complete output folder that is written under `gangadir/workspace/user/LocalXML/X`. Would that be useful to you? It did not know there was a report function, I will use it next time

**Comment by egede** [comment]
>  I am sorry, but I have since deleted the ganga job, but I still have the complete output folder that is written under gangadir/workspace/user/LocalXML/X. Would that be useful to you? It did not know there was a report function, I will use it next time

No, unlikely to be enough as I would need the timestamps from the monitoring as well. Please `report` if it comes up again.
