### ISSUE TITLE
Ganga web page not updating with release info

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#181]
I'm not sure how this will fit in with the new release process but the main Ganga page isn't being updated with the new releases:

https://ganga.web.cern.ch/ganga/

**Comment by rob-c** [comment]
Is the source this page in github anywhere?

**Comment by drmarkwslater** [comment]
I don't believe so - all the web pages are just hosted at CERN on AFS. This may be something to look into changing in the near future....

**Comment by alexanderrichards** [comment]
I mentioned in the meeting a few weeks ago, we could host on github itself using github pages

**Comment by drmarkwslater** [comment]
Sounds like a plan - just need to remember to redirect from CERN I guess
