### ISSUE TITLE
"failed" is not enough to classify a job failure state

### ISSUE THREAD

**Issue by VukanJ** [ganga-devs/ganga#1828]
A job that is failed can be failed because the backend is not up-to-date, the executable finished with errors, or some other problem. If the job is completed but the data was removed from the grid because it is outdated, the job is not even failed, it is "completed" but really should be failed if getOutputData has not been successfully called by the user. Consider the following scenarios:

**Scenario 1:**
1. User submits a job (DiracFile) with subjobs and 20 files per subjob; some jobs fail and need to be re-splitted, to have a change of succeeding
2. Now the original job must be preserved in its current failed state under all circumstances (no backend reset or resubmit allowed) so that we do not select the same data twice
3. If the user now: resets the backend of the original job, or resubmits some the original subjobs and they complete, we partially select the same data twice -> Physics analysis show-stopper

**Scenario 2:**
1. User submits a job (DiracFile) with subjobs and 20 files per subjob; some jobs fail and need to be re-splitted, to have a change of succeeding
2. Now some of the original job output files are removed from the grid because of overfull quota, or the user just does not make the download in time (or deletes the files himself to be pedantic)
3. Now, some "original" jobs are still marked as completed, but the user needs to resubmit them, right? So we force the job to failed.... and then it is indistinguishable from other failed jobs, that should stay failed.  -> Physics analysis show-stopper

In both cases the user is more or less required to do very detailed manual bookkeeping, which should be gangas job.
What I want to say is that there does not really seem to be a security measure in place in ganga, which ensures, that there is continuity between jobs. The user is not really prevented from losing data or selecting it twice. I think one reason for this problem, is that the "failed" state is just not enough to characterize a failure state. A job or subjob should ideally have more states like: "frozen" if the user does not want to change the job state ever again, or "unavailable" if the data turns out to be missing on the grid if getOutputData fails, which hardly can be called "completed", right?

**Comment by mesmith75** [comment]
I am not sure what you are after. Bookkeeping of data is not ganga's responsibility.

**Comment by VukanJ** [comment]
Well I think that Scenario 1 is pretty self explanatory. The precautions a user needs to take to keep a job and all its subjobs in the failed state to prevent himself from resubmitting it in any way (e.g. through resubmit / backend reset) is already a bit awkward and can easily go wrong, leading to a huge waste of time potentially. If I had the ability to fix a subjob in its current state, this would not be an issue. So it is not about keeping track of file availability, but instead checking output data consistency once we try to retrieve it (meaning everything). I have the constant fear when working with ganga, that I will overlook a file which cannot be retrieved temporarily or that I will process a file twice, which can easily happen in the workflow I described above.

**Comment by mesmith75** [comment]
So you want an option to freeze a job? That would stop any changes to it - that is probably feasible.

**Comment by VukanJ** [comment]
In my opinion, this would make data processing a bit safer. A job that is "failed", (but its couple of failed subjobs are already splitted again and taken care of in another job) can be regarded as a success and can be (I argue that it almost always must be) fixed in that state (including its subjobs). (I actually lost a couple of weeks because I chose a wrong job range in jobs.select(...) once, when I was resetting backends..)

Regarding file availability: This is not critical at all, but if getOutputData() fails, because of a "No accessible replicas found" error, it is not gangas fault, sure, but currently, ganga does not flag the job accordingly (I think). So to retrieve the file, I am running getOutputData() on every subjob and hope to see no error message in the console, and afterwards I check all the files with another python script. If ganga would flag the completed subjob accordingly, that would be a nice feature, but that is a design choice

**Comment by mesmith75** [comment]
So I don't think we can call a job with failed subjobs ever a success but sure I agree having a freeze option would be helpful. That would be up to the user to choose to do though - I am certain it is not something you can ask ganga to do automatically.

The thing with the `getOutputData` is that these are helper functions. The status refers to the job itself - SEs go in and out of downtime - that doesn't change if the job was successful or not. I am surprised you run it on every subjob - you should just be able to do it once on the master job. We could certainly update the helper function to check the availability of LFNs before starting the download and fail immediately if they are not all available (with an `ignore_missing` option)

**Comment by VukanJ** [comment]
Yes, I agree that this should be a choice of the user. I queue the individual downloads up in order to use all worker threads, but I did not measure whether this is actually faster.

**Comment by mesmith75** [comment]
I'll check exactly what the function does - maybe we can make it quicker.

**Comment by VukanJ** [comment]
Ok, great :) Thanks a lot for taking your time to read this!

**Comment by egede** [comment]
There is indeed often confusion happening when a user is forced to "resplit" a subjob that for some reason is failing to run with the dataset given. It means that the complete processing of the dataset is split across at least two jobs where one of them is forever labelled as failed.  I would quite like to see the possibility to take a failed subjob, assign a new splitter to it and the resubmit those. Technically, we would delete the subjob and append a new set of subjobs.

**Comment by mesmith75** [comment]
We have implemented frozen states and improved the `getOutputData` function so I shall close this

**Comment by VukanJ** [comment]
Fantastic, Thank you!
