### ISSUE TITLE
ganga 8.4.5: getOutputData() throws error when there is nothing to do

### ISSUE THREAD

**Issue by VukanJ** [ganga-devs/ganga#1837]
The error is thrown when job(X).subjobs(Y).backend.getOutputData() is run twice. In both versions (8.4.4 and 8.4.5), the initial download works and the file is retrieved, but in ganga 8.4.5 a GangaDiracError is raised when the command is run a second time, whereas in 8.4.4 the function effectively does nothing (I guess the latter behaviour is the expected one). The error is
```
ERROR    GangaDiracError: Not all files downloaded successfully and ignoreMissing=false! Check your gangadir for missing files! len lfns: [<my lfn>], len success: []
```

**Comment by mesmith75** [comment]
Thanks for the report.

**Comment by thekingpin1** [comment]
> The error is thrown when job(X).subjobs(Y).backend.getOutputData() is run twice. In both versions (8.4.4 and 8.4.5), the initial download works and the file is retrieved, but in ganga 8.4.5 a GangaDiracError is raised when the command is run a second time, whereas in 8.4.4 the function effectively does nothing (I guess the latter behaviour is the expected one). The error is
> 
> ```
> ERROR    GangaDiracError: Not all files downloaded successfully and ignoreMissing=false! Check your gangadir for missing files! len lfns: [<my lfn>], len success: []
> ```

@VukanJ , please provide the link #1837  below
