### ISSUE TITLE
Make substitution of illegal characters in batch job names generic

### ISSUE THREAD

**Issue by ryuwd** [ganga-devs/ganga#1838]
I am trying to submit Tasks (or `LHCbTask` in my case) using the Sun Grid Engine `SGE()` as the backend, but the colon in the job names are stopping the jobs being submitted. Any advice on what I should do here, other than maybe edit the source code on my end? Many thanks in advance.

https://github.com/ganga-devs/ganga/blob/f784982461cc8830160630e540a815902ab38d3f/ganga/GangaCore/GPIDev/Lib/Tasks/IUnit.py#L201

![image](https://user-images.githubusercontent.com/56410978/108126182-716dd100-70a1-11eb-8249-4fa0e839d8eb.png)

**Comment by egede** [comment]
I think you can work around this by taking advantage of that later options in general override earlier ones on the command line. So in the `[SGE]` section of the `.gangarc` try something like  

```
[SGE]
submit_str = cd %s; qsub -cwd -S /usr/bin/python -V %s %s %s %s -N noname 
```
which might then give all your jobs `noname` as the name. SGE might still complain about the invalid option even if it is overridden later ...

In reality this should be fixed by making the code at https://github.com/ganga-devs/ganga/blob/f784982461cc8830160630e540a815902ab38d3f/ganga/GangaCore/Lib/Batch/Batch.py#L171 more flexible. Each backend could have a configurable that has a regexp for how names should be mangled.

**Comment by ryuwd** [comment]
Ah, I didn't see this until after submitting #1839. Thank you for the workaround!

**Comment by ryuwd** [comment]
Maybe I should have a go at this in #1839 if you'd prefer a more comprehensive solution to the workaround I proposed there. Could you point me to where I should introduce the new configurable? 

As you suggest, perhaps a configuration option e.g. called `jobname_replace` (maybe someone has a better idea for a name!) could accept a regular expression or just a string of characters, which are used to replace matched substrings with some delimiter e.g. `_` or `-` specified in a second configurable. 

Alternatively `jobname_replace` it could be a list of lists, where each sublist `(a,b)` contains a regex/string and a string to replace it with.

**Comment by egede** [comment]
> Maybe I should have a go at this in #1839 if you'd prefer a more comprehensive solution to the workaround I proposed there. Could you point me to where I should introduce the new configurable?
> 

You are very welcome. The configurable should be introduced for the different batch backends at https://github.com/ganga-devs/ganga/blob/f784982461cc8830160630e540a815902ab38d3f/ganga/GangaCore/__init__.py#L429. Do not touch the `condor` backend which is special.

> As you suggest, perhaps a configuration option e.g. called `jobname_replace` (maybe someone has a better idea for a name!) could accept a regular expression or just a string of characters, which are used to replace matched substrings with some delimiter e.g. `_` or `-` specified in a second configurable.
> 
> Alternatively `jobname_replace` it could be a list of lists, where each sublist `(a,b)` contains a regex/string and a string to replace it with.

I think a regexp is the best. In that way it can cope with both illegal characters, a maximum length, a special `pre` string etc. I suggest that the argument should be a list that takes exactly the two strings required for the `re.sub` method. https://docs.python.org/3/howto/regex.html#search-and-replace. So maybe something like.

```
[SGE]
jobnamesubstitution = [':', '_']
```
would solve your current problem. This substitution might of course just be added as a default. Make sure to make docstring in the `makeconfig` call explain well how it works.

**Comment by egede** [comment]
Please fork the `develop` branch and make the pull request against that one.

**Comment by ryuwd** [comment]
Thanks a lot for the pointers! I'll have a go at impementing this in #1839.
