### ISSUE TITLE
GangaList tests failing

### ISSUE THREAD

**Issue by milliams** [ganga-devs/ganga#184]
Since 6.1.13 (and it got worse in 6.1.14) we've been failing on a number of `GangaList` tests which, after some investigation, needs some discussion. The primary bug I've come across is a change in how calling `copy` on a `GangaList` preserves references or not.

If you make a `GangaList` with:
```python
gl = GangaList()
gl.append(LocalFile())
```
then you have a `GangaList` with a single `LocalFile` in it. Calling:
```python
gl2 = copy.copy(gl)
```
should, by normal Python convention, create a new `GangaList` where `id(gl) != id(gl2)` _but_ `id(gl[0]) == id(gl2[0])` so while the outer container has been copied, the contained objects are references to the same thing.

One of the conditions is this (assigning `self._list` in `makeGangaListByRef()`): An object is being assigned to a schema item which is not marked as a `sequence` but the item is a `ComponentItem` and the object we're passing in is a list-type thing (in this case an actual Python `list`). The code will make a deepcopy-type `cloneVal()` of the object, converting any list-type things to `GangaList`s. This has the effect of deepcopying all the objects so that none of the `id`s match anymore.

Can anyone thing of a solid reason why we would want to be doing a recursive deepcopy of a list object when assigning it to a `GangaObject`? Or should I fix the code so that it's back to 6.1.12 when all the tests passed?

**Comment by drmarkwslater** [comment]
Tricky because though I would say that naively you'd want to revert the behaviour back, I can see there's an issue if you did something like:

```
j.inputfiles = j2.inputfiles
```

as you would then have a reference between jobs. This would break when loaded from disk and would also produce odd behaviour if, e.g. you submitted one job with wildcarded inputfiles, the second job would then have it's inputfiles resolved automatically.

@rob-c Does any of this ring a bell? If the test isn't valid anymore then fine, but we should make a decision one way or another I guess :)

**Comment by milliams** [comment]
It looks like this *might* have been changed at [18cd9ac3b99](https://github.com/ganga-devs/ganga/commit/18cd9ac3b99562bff08bccba6cfb70414971a762#diff-3a5f5ed88f274eb570dccbab85337abfR364) but it's not clear from the commit message if this was intended.

**Comment by rob-c** [comment]
I personally think that the behavior highlighted by mark is consistent with what we intend to happen, we need a new copy whenever Python would prefer to make a lightweight copy.

We could get this to change depending on if an object is copyable but IMO  because we can never have 2 parents to one object by design my vote is to kill the copy test as moving contrary to the ganga ethos.

**Comment by rob-c** [comment]
We can make sure that the copy method is lightweight but then the GangaList needs to remember to copy the object before any and all changes are made to objects it is ownership of.

As it's incredibly easy to subvert this and have a GangaList wrapper which would not know if the dataset it's linking to from an older job has changed I think it's much more sensible to have an explicit copy actually made here.

i.e we have to protect against:
```
j.inputfiles = GangaList(myAwesomeList)
j2.inputdata = j.inputdata
fixMyAwesomeList( j.inputdata )
```
This would cause j2.inputdata to change unless we build GangaList to be very complicated to break soft links on the returning of an element or a list and then this breaks the test I would have imagined by design.

Is there a very good reason to prefer the lightweight copy other than it's more Pythonic?

**Comment by rob-c** [comment]
The componentitem was needed as a result of storing objects in threads. This could possibly be improved or fixed but we run the risk of not being able to load old valid XML as a result of schema changes. I'd rather avoid this if we can.

**Comment by milliams** [comment]
I guess it come down to what the purpose of `GangaList` *is*. Why do we have `GangaList` instead of a normal Python `list`? I can think of a few possible things:

1. So that we can provide a proxy list interface whereby real `GangaObject`s are stored but if you're in GPI-land when requesting items (`mylist[3]`) you get proxied objects.
2. Persistency. It makes it easier to put a `GangaList` in a `ComponentItem` and have it know how to store itself. Of course, we could just as easily have the serialisation code say "it's a `list`, serialise as a sequence" instead of "you're a `GangaList`, serialise yourself as a sequence".
3. Parents. I'm not sure where we're *supposed* to be here but I suppose it's good that the `GangaList` can automatically set the parent of all its elements to the `GangaList`'s parent. Of course, we could just as easily do that in the getter and setter with a normal `list`.

All of which come together to mean that I feel that really `GangaList` should exist simply as a way of proxy-wrapping a `list` so that `addProxy([1,2,3])` give a `GangaList`. And even then it's only needed if the list is containing `GangaObject`s.

**Comment by egede** [comment]
You need to add write protection to your items. If a GangaList is inside 
a write protected object, you should not be able to do

list[2]='foo'

**Comment by alexanderrichards** [comment]
Jobs gain a write protected status upon submission and this is independent I think of proxy so I think in this instance the GangaList may be more that a simple proxy wrapping.

**Comment by milliams** [comment]
The definition of `protected` is "not modifiable via GPI" and indeed the "object %s is read-only and attribute "%s" cannot be modified now" is only done on the proxy layer.

**Comment by alexanderrichards** [comment]
ah ha ok then. I though that even behind the proxy the job was in essence locked down once the status was submitting

**Comment by alexanderrichards** [comment]
what about taking Ulriks example:
```python
list[2] = 'foo'
```
This will also need to trigger a dirty update. I don't recall now but I assume that GangaList handles this through the standard GangaObject dirty mechanism.

**Comment by alexanderrichards** [comment]
also I think that we add functionality in the GangaList as well like there is a get method right?

**Comment by alexanderrichards** [comment]
however don't read this as I'm not in favour of removing it :smile: I'm just trying to understand all the intricacies.  Lets discuss it in the meeting.

**Comment by milliams** [comment]
As for
```python
mylist[2] = 'foo'
```
the question is, where did `mylist` come from? If it was from something like:
```python
mylist = j.inputfiles
```
then even if `j.inputfiles` is stored internally as a `list` then when it's requested via the proxy layer like this, the proxy layer will return a `GangaList` (with parent set appropriately) so that object will be able to do the write-protection and dirty notification.

**Comment by alexanderrichards** [comment]
> then even if j.inputfiles is stored internally as a list then when it's requested via the proxy layer like this, the proxy layer will return a GangaList (with parent set appropriately) so that object will be able to do the write-protection and dirty notification.

That's convincing. What is the expected behaviour of a straight list in the box? I guess the same then right? i.e. when the user gets from the box we would proxy wrap to a GangaList which will take care of dirty notification.

**Comment by milliams** [comment]
Yes, I think so. The box is a proxy object so passing things into or out of it should wrap as appropriate. Now, doing:
```python
box.add([1,2,3], 'l')
type(box['l'])
```
would print `Ganga.GPIDev.Base.Proxy.GangaList` but that's fine (and is indeed the current behaviour).

**Comment by rob-c** [comment]
Was this fixed recently or are there still some failing GangaList tests?

**Comment by drmarkwslater** [comment]
I think the original reason for this issue is now fixed.

**Comment by drmarkwslater** [comment]
...Though there's other discussion here that may want to be continued!

**Comment by milliams** [comment]
I think my reasons for opening this in the first place is solved with @drmarkwslater's recent work. The discussion above is largely superseded by #330 so I think we can close this issue.
