### ISSUE TITLE
Add tags for Dirac backend if /cvmfs locations are requested in inputfiles or for singularity

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1840]
See https://gitlab.cern.ch/-/snippets/1524 for syntax to request `/cvmfs` locations in the matching. User can do this manually but it should be automatic for inputfiles.

**Comment by thekingpin1** [comment]
sir, it requires single sign-on  authentication! to work further

**Comment by egede** [comment]
> sir, it requires single sign-on authentication! to work further

Yes, I am afraid that to develop and test this one, registration at CERN is a pre-requisite.

**Comment by mesmith75** [comment]
I'm not sure I understand the inputfiles point here. If it is a LocalFile it will be copied from CVMFS into the sandbox so there won't be an issue.

I'll add the tag for the virtualisation path.

**Comment by egede** [comment]
There is actually another part missing here. If the Singularity virtualisation option is used, the `/cvmfs/unpacked` should be treated in a special way and not placed as a `LocalFile`. It makes running containers far more effective.
