### ISSUE TITLE
LHCbTask doesn't work with non-Dirac backend

### ISSUE THREAD

**Issue by ryuwd** [ganga-devs/ganga#1848]
In this file, as a workaround I can get LHCbTask to run on e.g. `Batch` backends, by setting `j.splitter = None`:
https://github.com/ganga-devs/ganga/blob/736cff033327a9753c44d5c71b14d15e600c5935/ganga/GangaLHCb/Lib/Tasks/LHCbUnit.py#L54

Are there any alternative splitters that can be used instead of `SplitByFiles` (which depends on `Dirac`) that work with `MassStorageFile` ? 

Many thanks!

P.S. for context, I am running private LHCb MC productions / tests, so in this case I have no need to access or use Dirac storage.

**Comment by mesmith75** [comment]
Is the issue that you want a splitter for batch backends or is it specific to `LHCbTask`?

**Comment by mesmith75** [comment]
`SplitByFiles` doesn't need Dirac - I have submitted jobs to the Imperial batch with `SplitByFiles` on a data set of `LocalFile` objects.

Could you post an example of what you are doing and the error you get?

**Comment by ryuwd** [comment]
Here's my `LHCbTask`: https://gitlab.cern.ch/-/snippets/1535

I'm using `MassStorageFile` and `SGE` as my backend. The first Gauss step works just fine, but the steps following have `SplitByFiles` used as the splitter by default, and the objects are created with a `DiracProxy` as a credential requirement so the jobs fail since a grid proxy can't be found.

Maybe I've just misconfigured my `ganga` install?

I don't have the traceback to hand unfortunately.. I've since worked around it but I can reproduce and post it again

**Comment by mesmith75** [comment]
Ah ok - that is a slightly different issue. There is an ill-placed `@require_credential` decorator in the code. Thanks for reporting it.

**Comment by mesmith75** [comment]
Whilst we fix that you can use the splitter that `SplitByFiles` inherits from (and is used when Dirac is not involved) - `GaudiInputDataSplitter`. That has no credential decorators.

**Comment by ryuwd** [comment]
Ah, great! Thanks!

**Comment by ryuwd** [comment]
I had a go at using `GaudiInputDataSplitter` but ran into this 
![image](https://user-images.githubusercontent.com/56410978/108679059-de3efc00-74e3-11eb-81e7-6b114b3fecc3.png)

I see that the `GaudiDataset` import is commented out
https://github.com/ganga-devs/ganga/blob/1e2877a8b6254cc3218bd2dd0b1a663532a93663/ganga/GangaGaudi/Lib/Splitters/GaudiInputDataSplitter.py#L8

but uncommenting this line causes ganga to crash on startup 
![image](https://user-images.githubusercontent.com/56410978/108681514-23b0f880-74e7-11eb-93ae-73503cec0f85.png)

**Comment by ryuwd** [comment]
I used `SplitByFiles` from #1851 and it worked :+1:
