### ISSUE TITLE
XML files disappearing

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#185]
I think I've tracked this problem down. I think the only way that the data file can be blanked and yet the data~ file still be present is because in the `safe_save` method in `GangaRepositoryXML.py`, the backup file is created from a rename of the `data` file before the new `data` file is created from a rename of `data.new`. If this function has been called from multiple threads simultaneously, this can lead to a race condition where the `data.new` file is overwritten by the second thread before the `data` file is created from it. The original `data` file is removed to produce the backup file and then, because the `data.new` file has gone, it can't create the proper `data` file, fails silently, thus leaving just the backup file. 

This has two issues to address:

1. safe_save isn't thread safe. Though it never really could be, we could make it a lot better by shifting things around a bit and being a bit cleverer with how things are handled. I try to get this done tomorrow.

2. safe_save should **never** be called by multiple threads. This may be sorted by the locking changes that are being discussed for the repo but there should at least be some form of global lock on accessing a repo by more than one thread.

Note that this was found through Tasks because I suspect there are explicit flushes coming from multiple threads (still got to track these down) but I think this is the only way the similar reports of XML files disappearing from the job repo can be explained as well.

**Comment by drmarkwslater** [comment]
Thinking a bit more, a simple single global lock in the `safe_save` may be the best way to go, irrespective of registry or object id. This means that You cannot right to the repo in parallel and so could cause a performance hit there but I expect the majority of the time (for the job repo at least) there's only one thread doing it anyway.

**Comment by rob-c** [comment]
A global lock here gets my vote :)
