### ISSUE TITLE
Should Executable's env var not be type dict?

### ISSUE THREAD

**Issue by alexanderrichards** [ganga-devs/ganga#1850]
Am I missing something here or should this not be type dict?

https://github.com/ganga-devs/ganga/blob/1e2877a8b6254cc3218bd2dd0b1a663532a93663/ganga/GangaCore/Lib/Executable/Executable.py#L57

**Comment by alexanderrichards** [comment]
Additionally why do we comment out the applications environment to favour None in the RTH?

https://github.com/ganga-devs/ganga/blob/1e2877a8b6254cc3218bd2dd0b1a663532a93663/ganga/GangaDirac/Lib/RTHandlers/ExeDiracRTHandler.py#L113

**Comment by alexanderrichards** [comment]
the background to this is that Andrew Naylor is trying to run an Executable on the Dirac backend and his app.env environment variables are not being propagated to the worker node.

**Comment by alexanderrichards** [comment]
@ganga-devs/ci just tagging you in case you missed this one

**Comment by mesmith75** [comment]
Looks like it should be yes
