### ISSUE TITLE
LHCbTask: delete_chain_input doesn't work with MassStorageFile

### ISSUE THREAD

**Issue by ryuwd** [ganga-devs/ganga#1852]
See this code:
https://github.com/ganga-devs/ganga/blob/1e2877a8b6254cc3218bd2dd0b1a663532a93663/ganga/GangaLHCb/Lib/Tasks/LHCbUnit.py#L95-L102

Not all backends will have a `status` parameter, so the first crash happens there.

Also see:
https://github.com/ganga-devs/ganga/blob/1e2877a8b6254cc3218bd2dd0b1a663532a93663/ganga/GangaLHCb/Lib/Tasks/LHCbUnit.py#L114

The call to `MassStorageFile` `remove(...)` hangs the terminal here, since it prompts for a `y / n` input from the user from inside the monitoring loop
https://github.com/ganga-devs/ganga/blob/1e2877a8b6254cc3218bd2dd0b1a663532a93663/ganga/GangaCore/GPIDev/Lib/File/MassStorageFile.py#L501-L509

I think I only got about that far trying to work around it until I just turned `delete_chain_input` off

**Comment by ryuwd** [comment]
Also, many thanks so far for helping me fix / work around these issues !

**Comment by mesmith75** [comment]
Aha, that is quite amusing. ~~We should get rid of the question.~~ We should make use of the `force` option.
