### ISSUE TITLE
Overiding executable permissions in the input Sandbox error

### ISSUE THREAD

**Issue by gurudattapatil** [ganga-devs/ganga#1865]
![image](https://user-images.githubusercontent.com/42720547/110915574-d2ee2c00-833d-11eb-8ed2-6a7e7106accf.png)
I am getting this error while trying to complete a job.
Any idea on how this can be solved?

**Comment by egede** [comment]
Both of thse are just warnings. The first one means that the file `counter.py` doesn't have the executable bit set. You can get rid of it by doing `chmod u+x counter.py` on the script before submitting the job in Ganga. The second warning means that you told Ganga that a file `ans.txt` would be produced by your job, but when the job finished, Ganga could not find the file.

**Comment by gurudattapatil** [comment]
Thank you for the help @egede. The other  error was due to shebang.
