### ISSUE TITLE
Problems with CoreTasks not running properly

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#187]
I'm seeing many errors and stalled tasks. Going through and cleaning this up so it works again.

**Comment by milliams** [comment]
This sounds like a blocker for 6.1.16?

**Comment by drmarkwslater** [comment]
Normally I would say yes but on the totem pole of major problems, this is under the others and I'd prefer to get a version out with a working repo/monitoring loop rather than hold it up for this. This is still a serious problem that will hopefully be fixed in the next week as well, but I have no desire to push it/hold up the release for it.

**Comment by drmarkwslater** [comment]
Should be fixed by #377 and others

**Comment by drmarkwslater** [comment]
Fixed by #377
