### ISSUE TITLE
Check if DiracFiles placed in inputfiles are actually available

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1875]
When you do something like
```python
j.inputfiles=[DiracFile('LFN:/ddbbd/file.root')]
```
the file will be downloaded by Dirac to the worker node before the job starts running. However if a file is not there, this leads to an almost infinite rescheduling of the jobs. Can we check if such files have available replicas as part of the submission process?

**Comment by VladimirRomanovsky** [comment]
Absence of available replica is not the reason to not submit job, the site can be in downtime and replica will be available later.
The real problem is when the file is absent in file catalog, so there is no replica et all.

**Comment by mesmith75** [comment]
For which application is this not happening? It is already implemented for `GaudiExec`. I can add it for a regular `Exectuable` as well.
