### ISSUE TITLE
Adding subjobs to job

### ISSUE THREAD

**Issue by acampove** [ganga-devs/ganga#1882]
Hi,

I have a job (ID=23) with many subjobs, some of them failed and I cannot get them to succeed due to site problems. Therefore I made copies of each of these subjobs in such a way that if a subjob (ID=23.4) takes ten input files, I made ten copies which will process just one input (ID=31, 32...40). Thus, I can:

1. Run this job in either of two sites that contain replicas of the input file, so that if the first file/site is broken I can still process the data.
2. If some file is just not good and is breaking the job, only one of those ten files won't be processed.

This seems to work well. However I would like to:

1. **Remove the old subjob** This I do with `jobs(23).subjobs[4].remove()`.
2. **Add each of the ten new jobs as subjobs** Can this be done? I would expect something like
`jobs(23).subjobs.add(jobs(31))`
`jobs(23).subjobs.add(jobs(32))`
`jobs(23).subjobs.add(jobs(33))`

Cheers.

**Comment by egede** [comment]
The issue #1669 is already there to allow something like this. So at the moment it is not possible, but is is a feature that we would like to implement.

**Comment by acampove** [comment]
I see that the issue was opened a year ago. How many years do you think it would take this feature to be implemented?

**Comment by egede** [comment]
A few days if you are willing to do it ;-) Kidding aside. It was planned to be part of this years Google Summer of Coding but that project will take a different direction now. Your request might move it from "nice to have but nobody asked for it" into some higher category. I am afraid that I do not want to make a promise though.
