### ISSUE TITLE
subjob.resubmit() stalling for at least some jobs on the Dirac backend

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#19]
subjob.resubmit() is stalling for (at least) some subjobs. This was first reported in private communications from a user.

The tested workflow is to run a job with subjobs to completion.
1) Take a subjob which can run on multiple sites.
2) Run job until it completes
3) Blacklist the site the subjob ran on in subjob.backend
4) try to do a subjob.resubmit()

This hangs on an inifinite loop which after exiting with Ctrl+C seems to be due to a subprocess call hanging either not terminating correctly or waiting on missing some extra input.

This should be fixed before 6.1.12

**Comment by egede** [comment]
Hi Rob,

This sounds as if the call to the Dirac server is hanging. If that is the 
case, it is really hard for us to fix, but bug should be reported upwards. 
We already have a timeout for Dirac calls but it is long as some calls 
indeed take a very long time.

Ulrik

**Comment by rob-c** [comment]
Hi Ulrik,

Not exactly. We construct a new JDL and submit this JDL in the resubmit method using the same common code for submitting a job.
I can submit jobs correctly but when I resubmit a working job then the submit always hangs for me. I'm going to be comparing the JDL and code paths today as I suspect this is something internal to ganga.

I'm also thinking of implementing a 'resubmitDiracJob()' method within the Dirac backend which will allow for us to resubmit a Dirac job without constructing an entirely new Dirac job. This is something which would be equivalent to resubmitting a job from the Dirac web interface which is something I've done regularly in the past to get a job to resubmit when the job has hit some bad grid weather.

I'm aiming to work on this Today/Monday as I think this (hopefully) shouldn't be too difficult to track down.

Thanks,

Rob

**Comment by egede** [comment]
Hi Rob,

On 23/10/15 09:14, Robert Currie wrote:
> Hi Ulrik,
>
> Not exactly. We construct a new JDL and submit this JDL in the resubmit
> method using the same common code for submitting a job.
> I can submit jobs correctly but when I resubmit a working job then the
> submit always hangs for me. I'm going to be comparing the JDL and code
> paths today as I suspect this is something internal to ganga.
>
> I'm also thinking of implementing a 'resubmitDiracJob()' method within
> the Dirac backend which will allow for us to resubmit a Dirac job
> without constructing an entirely new Dirac job. This is something which
> would be equivalent to resubmitting a job from the Dirac web interface
> which is something I've done regularly in the past to get a job to
> resubmit when the job has hit some bad grid weather.

On initial thoughts this would be a bad idea. One of the selling points 
of Ganga is that we hide the complexity of different backends by giving 
them an identical interface. We should strive to get closer to that 
situation rather than further away. I can see that there is a small 
performance improvement from having 'resubmitDiracJob()' but are there 
any other benefits? If you think this is an idea we should go ahead 
with, then put it as a separate feature and we can discuss.

Ulrik.

**Comment by rob-c** [comment]
OK, this turned out to be the way we were passing certain objects to the JDL. fix incoming
