### ISSUE TITLE
Make GaudiExec prepare virtual

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1915]
We should have the option to run the GaudiExec build in a container if need be so we can submit very old `slc5` stacks

**Comment by egede** [comment]
I seem to remember that there is some support available for this within the LHCb software stack already. Can we just hook into that?If it relies on `singularity`, we might unfortunately hit the intermittent problems about running `singularity` on lxplus. The long standing bug-report I have had about it was closed with `wont fix, use podman instead` a few weeks back.

**Comment by mesmith75** [comment]
Unfortunately the LHCb software stack is not quite there. You can use `lb-run` with a container quite nicely (`lb-run --container=singularity DaVinci/v32r2p18`) but unfortunately not `lb-dev`.
There is `lb-docker-run` but that needs you to have docker running.
The best solution I have is 
```sh
singularity exec -e --bind /cvmfs docker://gitlab-registry.cern.ch/lhcb-core/lbdocker/slc5-build:latest bash -c ". $LBENV_ENTRYPOINT
> lb-dev DaVinci/v32r2p18
> cd DaVinciDev_v32r2p18
> make"
```
but its not super nice. I'll have a look at the LHCb scripts and see if it would be straightforward to implement a singularity type thing.

**Comment by mesmith75** [comment]
Superseded by #2320
