### ISSUE TITLE
Overwrite existing files in Dirac

### ISSUE THREAD

**Issue by jco-dev20** [ganga-devs/ganga#1943]
Users may want to re-upload/overwrite an existing file on Dirac, for example in toy studies where there may be small changes to the toy files these may need to re-uploaded with the same, previously used names resulting in LFN/GUID clashes.

I notice there is a force keyword in the put method for DiracFile. Using this doesn't overwrite the files or prevent LFN/GUID clashes. Looking at the code, this doesn't seem to do anything. Are there plans to implement this kind of functionality?

**Comment by egede** [comment]
Seems low priority to me. It is in general poor practise to overwrite files (as it prevents tracking of what was used for what). Also, I guess that you can just first remove the file and then create it again.

**Comment by mesmith75** [comment]
I don't think Dirac even allows this - there doesn't seem to be an option in `dirac-dms-add-file`. Can we close this?
