### ISSUE TITLE
stomp monitoring appears non-threadsafe

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#195]
This is just a small issue to remind me to look into the stomp monitoring code at the start of next week.
This code appears to have issues when submitting many jobs in parallel and I suspect this might be that some of the code isn't fully thread-safe.
This isn't a major bug (2 or 3 jobs aren't reported per 100) but it does fire a critical logging error which would be best avoided.

**Comment by rob-c** [comment]
e.g.
```2016-02-12 17:47:45,611 StompReceiver stomp.py                           :493 ERROR   : Lost connection```

**Comment by rob-c** [comment]
I suspect this may just be due to the logging not having the logging level set to critical as expected as this doesn't go away with large global locks around most of the stomp code and there are very few global or cross-thread parameters here as there is typically 1 publisher per thread.

**Comment by milliams** [comment]
I've been seeing thread-related issues with stomp where many threads are hanging on
```python
File: "/usr/lib64/python2.7/threading.py", line 783, in __bootstrap
  self.__bootstrap_inner()
File: "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
  self.run()
File: "/usr/lib64/python2.7/threading.py", line 763, in run
  self.__target(*self.__args, **self.__kwargs)
File: "/home/matt/ganga_venv/lib/python2.7/site-packages/stomp/transport.py", line 306, in __receiver_loop
  frames = self.__read()
File: "/home/matt/ganga_venv/lib/python2.7/site-packages/stomp/transport.py", line 338, in __read
  c = self.receive()
File: "/home/matt/ganga_venv/lib/python2.7/site-packages/stomp/transport.py", line 575, in receive
  return self.socket.recv(1024)
```
when I've been submitting from lots of threads at once. It's nothing super reproducible at the moment but it's worth keeping an eye one.

**Comment by rob-c** [comment]
I'd like to get it to ignore the errors at least from the users, but a minor bug yes

**Comment by rob-c** [comment]
I'm bumping this to 6.1.20 but I've not seen any problems with this for a long time now, has anyone else noticed this crop up at all?

**Comment by rob-c** [comment]
I think this is less thread safety and more to do with the connections being flaky. It would be nice to get the error to be hidden from users but it's not clear where it's originating.
