### ISSUE TITLE
Save quick runfile

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1951]
It might be nice in the GUI to save the created quick runfile that you can create.

It may also be nice if you can interactively create a job, i.e. select the application from a menu etc.

It may also be nice if the quick runfile creation includes some auto python things - i.e. when pressing tab it indents rather than selecting the next button.

**Comment by egede** [comment]
@gurudattapatil is working on integrating the terminal into the GUI again. I wonder if this quick runfile should use the same interface as much as possible. Or maybe this quick runfile is not at all required then?

**Comment by gurudattapatil** [comment]
Yes, I will try to make cli run, incase the cli part does not work we can do this.
