### ISSUE TITLE
Append ArgSplitter args

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1975]
`ArgSplitter` should append its run-time arguments rather than replace them. It would be better to be able to set up a job as 
```python
j = Job()
j.application.args = ['a','list','of','common','args']
j.splitter = ArgSplitter(args = [['args'],['for'],['each'],['subjob']])
```
Currently only the `ArgSplitter` args get passed to the subjobs

**Comment by egede** [comment]
This might be better, but the change will break existing code like
```python
j = Job(application=Executable(exe='sleep'), splitter=ArgSplitter(args=[i for i in range(10)]))
```
as it will leave the default `Hello World` argument of the `Executable` object. So if we make this change it should be carefully managed.
