### ISSUE TITLE
Change report to use LocalFile by default

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1984]

**Comment by egede** [comment]
The `report` function is very useful for debugging user problems. It is set up to use `GoogleFile` by default for creating the debug file. This is not ideal though as setting up `GoogleFile` in itself is not trivial. The default should be changed to `LocalFile`. 

See https://github.com/ganga-devs/ganga/blob/730e7aba192407d35eb37dd7938d49071124be8c/ganga/GangaCore/Utility/feedback_report.py#L27
A test case should be written as well that confirms that the function works.

**Comment by joj0s** [comment]
I would like to work on this as my first issue
