### ISSUE TITLE
Planned removals in LHCbDIRAC

### ISSUE THREAD

**Issue by chrisburr** [ganga-devs/ganga#1986]
In the next release of LHCbDIRAC I [plan to remove some functions](https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC/-/merge_requests/1105) which exist in ganga. The main one is which is `LHCbJob.setApplicationScript` and used here:

https://github.com/ganga-devs/ganga/blob/6764ce216e418bf481115fc5665ebbe5f4891aab/ganga/GangaLHCb/Lib/RTHandlers/RTHUtils.py#L38-L55

I think this isn't actually used in practice. Could someone take a look and confirm? (or summarise how it is used so I can fix/add a test on the LHCbDIRAC side)

There are also three occourances in this test file but I guess those don't matter:

https://github.com/ganga-devs/ganga/blob/3bca19714de423e0a1cdd3767319738575d8a9d1/ganga/GangaDirac/test/Unit/Backends/TestDiracBase.py#L30-L32

**Comment by mesmith75** [comment]
Hi @chrisburr, thanks for bringing this up.

It is in fact used in the run-time handlers for the old style applications and also for the ROOT application. Admittedly these are rarely, if ever used these days. We need to see if we can get rid of them completely, otherwise we should probably come up with a workaround.

**Comment by chrisburr** [comment]
Thanks for taking a look @mesmith75.

I also think the old application classes can be removed. If a workaround is needed I'll figure out a way to re-implement `setApplicationScript` on the LHCbDIRAC side bu I'll wait for you to confirm before figuring out how to.

**Comment by egede** [comment]
So am I right that this affects releases with the old `SetupProject` way of working? Could there be some forever-delayed project that is still using that? The `ROOT` application I think it would in fact be good to remove anyway. It has proven hard to maintain and doesn't really add much.

**Comment by mesmith75** [comment]
Yes - an `Executable` with a wrapper script is much better for ROOT. Let's create an issue to remove it.

**Comment by chrisburr** [comment]
> So am I right that this affects releases with the old SetupProject way of working? Could there be some forever-delayed project that is still using that?

I'd be surprised if such cases were still working but I don't think we can really check. It'll be rare and not time senstive so a situation shows up I think we can find a solution on a case-by-case basis (e.g. Analysis Productions should be usable for such cases).

**Comment by mesmith75** [comment]
So I think these old applications can anyway be set up with lb-dev, but then we have the platform issue that #1917 may deal with. In any case we have long said we no longer support those applications but leave the code there in case people want it. So I think you are fine to proceed @chrisburr

**Comment by mesmith75** [comment]
Root has been removed so I'll close this. We can keep an eye out if issues occur.
