### ISSUE TITLE
Setting Condor requirements

### ISSUE THREAD

**Issue by kh296** [ganga-devs/ganga#1998]
Is it possible for the user to set Condor requirements?  It used to be possible via the [CondorRequirements class](https://github.com/ganga-devs/ganga/blob/23b1de3d4179508aa2f7b8b9867dc261d8e15036/ganga/GangaCore/Lib/Condor/CondorRequirements.py#L37).  The [Condor class](https://github.com/ganga-devs/ganga/blob/23b1de3d4179508aa2f7b8b9867dc261d8e15036/ganga/GangaCore/Lib/Condor/Condor.py#L49) includes a `requirements` item in its schema, but as far as I can see doesn't do anything with it.  Experimentally, any values set for `requirements` seem to be ignored :(

Thanks, Karl.

**Comment by kh296** [comment]
Okay, I see that requirements can be set via:
```
backend = Condor()
backend.cdf_options['requirements'] = 'my_requirements'
```

It could be worth removing `requirements` from the `Condor` schema, and updating the user guide.

Thanks, Karl.

**Comment by mesmith75** [comment]
Thanks for bringing this up. Indeed `requirements` does nothing now - it was effectively moved when we changed to the python API. I wonder if that was a mistake though.
