### ISSUE TITLE
Splitting of local jobs not working on MacBook

### ISSUE THREAD

**Issue by kh296** [ganga-devs/ganga#2004]
On a MacBook (intel processor), if I submit a job created with:

```
j = Job()
j.splitter=ArgSplitter(args=[['Hello 1'], ['Hello 2']])
```

the traceback below is repeated continuously until I kill the process that's running `__jobscript__`.  This is using `ganga 8.5.0`, installed with `pip`.  The same job runs without problems on a Linux machine.

Any ideas?

Thanks, Karl.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/test/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/miniconda3/envs/test/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/opt/miniconda3/envs/test/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/miniconda3/envs/test/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/opt/miniconda3/envs/test/lib/python3.10/runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/miniconda3/envs/test/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/miniconda3/envs/test/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/user/gangadir/workspace/user/LocalXML/6/input/__jobscript__", line 33, in <module>
    os.mkdir(outdir)
FileExistsError: [Errno 17] File exists: '/Users/user/gangadir/workspace/user/LocalXML/6/output'
```

**Comment by egede** [comment]
Please retry with the latest version - I see that there has been several changes to the wrapper scripts since `8.5.0`. If problem is still there please post the jobscript that causes the error.

**Comment by kh296** [comment]
Unless I'm mistaken, `8.5.0` is the latest version available for MacOS on `pypi`.  The error occurs with the simple example given in the original issue description:

```
j = Job()
j.splitter=ArgSplitter(args=[['Hello 1'], ['Hello 2']])
j.submit()
```

**Comment by kh296** [comment]
It looks as if Ganga versions newer than `8.5.0` can't be installed on MacOS because they have a dependency on `htcondor`, which seems to have builds on `pypi` only for Linux.

I've had a go at running Ganga `8.5.7` by cloning from the repository, removing the reference to `htcondor` in `setup.py` and disabling loading of the Condor plugin.  The submission script I gave previously needs a small modification to actually perform splitting:

```
j = Job()
j.application.args = []
j.splitter=ArgSplitter(args=[['Hello 1'], ['Hello 2']])
j.submit()
```

This submits two subjobs, without the previous traceback, but both stay in the submitted state.  If I query the processes running python, I obtain output such as the following:

```
  501 90441 85572   0 10:59am ??         0:00.08 /opt/miniconda3/envs/test/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=10, pipe_handle=29) --multiprocessing-fork
  501 90442 85572   0 10:59am ??         0:00.08 /opt/miniconda3/envs/test/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=10, pipe_handle=28) --multiprocessing-fork
  501 90443 85572   0 10:59am ??         0:00.07 /opt/miniconda3/envs/test/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=10, pipe_handle=28) --multiprocessing-fork
  501 90444 85572   0 10:59am ??         0:00.07 /opt/miniconda3/envs/test/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=10, pipe_handle=28) --multiprocessing-fork
  501 90445 85572   0 10:59am ??         0:00.07 /opt/miniconda3/envs/test/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=10, pipe_handle=28) --multiprocessing-fork
```

So I'm afraid there's a problem with local splitting on MacOS also for Ganga `8.5.7` :(

**Comment by egede** [comment]
I do not have a MacOS system to test on and as we do not test on MacOS neither, this is not trivial to support. However, I am happy to help debug and to implement solutions if supplied. 

The execution of subjobs on the `Local` backend was changed last year. Before, it would start all subjobs at the same time, even if there was 1000 of them. Now it will only run a number simultaneously that fits into the number of cores on the machine you run on. This was achieved though making the main job run a wrapper script that controls the execution of the subjobs. I think it is this script that fails on MacOS. You can find the script in `/Users/user/gangadir/workspace/user/LocalXML/6/input` or similar and try to execute it standalone. I include my script from a test below.
```python
#!/usr/bin/env python3
import os
import sys
import subprocess
import time
import multiprocessing
from pathlib import Path
from os.path import dirname, join, isdir

def mp_worker(name):
    print(f'START: {name} '+ time.strftime('%a %b %d %H:%M:%S %Y',time.gmtime(time.time())))
    subprocess.run(['python3', name], preexec_fn=os.setsid)

workdir = '/home/egede/gangadir/workspace/egede/LocalXML/10'
batch_size = 8
subjoblist = ['0', '1']
    
scriptnames_g = [join(workdir,sj,'input','__jobscript__') for sj in subjoblist]

outdir = join(workdir,'output')
if not isdir(outdir):
    os.mkdir(outdir)
statusfilename = join(outdir,'__jobstatus__')

try:
    statusfile=open(statusfilename,'w')
except IOError as x:
    print('ERROR: not able to write a status file: ', statusfilename)
    print('ERROR: ',x)
    raise

line='START: '+ time.strftime('%a %b %d %H:%M:%S %Y',time.gmtime(time.time())) + os.linesep
statusfile.writelines(line)
statusfile.flush()

sys.stdout=open(join(outdir,'__syslog__'),'w')
sys.stderr=sys.stdout

print(f'Running with a batch size of {batch_size}')
try:
    pool = multiprocessing.Pool(batch_size)
    pool.map(mp_worker, scriptnames_g)
finally:
    pool.close()
    pool.join()

sys.stdout=sys.__stdout__
sys.stderr=sys.__stderr__

line='STOP: '+time.strftime('%a %b %d %H:%M:%S %Y',time.gmtime(time.time())) + os.linesep
statusfile.writelines(line)
statusfile.close()
sys.exit()
```

Alternatively, you can at the Ganga prompt try to do `report(job=j, filetype=LocalFile)` and share with me the file that is created. I can then have a look.

**Comment by kh296** [comment]
I've experimented a bit with running the jobscript standalone, and two small changes allow it to run:

1.  Place the multiprocessing lines inside `if __name__ == '__main__':`, so:

```
if __name__ == '__main__':
    try:
        pool = multiprocessing.Pool(batch_size)
        pool.map(mp_worker, scriptnames_g)
    finally:
        pool.close()
        pool.join()
```

2. Remove the final `sys.exit()`.

The first change seems in line with the example in the documentation for [Using a pool of workers](https://docs.python.org/3/library/multiprocessing.html#using-a-pool-of-workers).  I'm not sure why the second change has any effect.

After making the same changes in [LocalHostExec_batch.py.template](https://github.com/ganga-devs/ganga/blob/8.5.7/ganga/GangaCore/Lib/Localhost/LocalHostExec_batch.py.template) the job splitting for submission from Ganga also works!  The print out from [mp_worker()](https://github.com/ganga-devs/ganga/blob/8ae8118eec18dd30fc17ecdf1e4be29774f59b61/ganga/GangaCore/Lib/Localhost/LocalHostExec_batch.py.template#L10) is sent to the terminal rather than being captured, but that's not such a big deal.

**Comment by kh296** [comment]
I've made a fork of the repository, where I've added a branch [MacOS_no_htcondor](https://github.com/kh296/ganga/tree/MacOS_no_htcondor).  This implements on top of [8.5.7](https://github.com/kh296/ganga/tree/8.5.7) the small changes need to enable local job splitting on MacOS:

- `htcondor` commented out in `install_requires` list of [ganga/setup.py](https://github.com/kh296/ganga/blob/bb9d02170891527ad3a08fb027f8189cc7aaaad6/setup.py#L107);
- changes outlined in previous post implemented in [ganga/ganga/GangaCore/Lib/](https://github.com/kh296/ganga/blob/c63f792e2ebfc275cac205237501110b3656a631/ganga/GangaCore/Lib/Localhost/LocalHostExec_batch.py.template#L40).
