### ISSUE TITLE
Can we split the ganga repository

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#2019]
Would it be feasible to split the `gangadir` such that we have the job repository and sharedir in one place (i.e. AFS) and the workspace somewhere else (EOS)?

I don't think writing job input/output on EOS will be so affected by the responsiveness in the way that the job repository is?

**Comment by alexanderrichards** [comment]
at the moment there is a single config variable that holds the root of the `gangadir` I assume this would have to be split along with all usages of it?

**Comment by mesmith75** [comment]
yes I think so.

**Comment by egede** [comment]
To test the performance of this, you could just try with a softlink.

**Comment by mesmith75** [comment]
I think the soft link is in any case the optimum solution for this - no change of code required so I shall close this.
