### ISSUE TITLE
CustomMerger documentation examples not updated to Python 3

### ISSUE THREAD

**Issue by alexverus** [ganga-devs/ganga#2021]
The  `mymerger.py` template code in the [documentation](https://ganga.readthedocs.io/en/latest/UserGuide/PostProcessors.html) uses the old file() i/o function from Python2.7 namespace. Changing it to `open` would allow it to run with the newer versions as well as preserve backward compatibility if necessary.

**Comment by egede** [comment]
An easy fix would be to just update the syntax in the [manual source](https://github.com/ganga-devs/ganga/blob/develop/doc/UserGuide/PostProcessors.rst). An even better solution would be to turn it into a test and then include the test code directly (as many of the other pieces in the file). That would prevent it from breaking in the future.

**Comment by egede** [comment]
@alexverus If you are up for it, you are welcome to fix and just create a pull request.

**Comment by alexverus** [comment]
@egede I definitely am! I'll proceed with the fix as you suggested.
