### ISSUE TITLE
little ganga unload

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#203]
I'm just adding a small issue here around 'ganga'.

What is the expected behaviour of the following code:

Edit: including code
```
def myFunc():
  import ganga
  j=ganga.Job()
  j.do_something()

myFunc()
```

do we expect little ganga to have vanished after ```myFunc``` exits. Do we expect the repos to be shutdown here?
Or, do we expect the shutdown and repo closing commands to be run only on exit of the python?

**Comment by drmarkwslater** [comment]
I think we expect similar behaviour to normal python modules in that the module (and associated gubbins) would stay cached whenever you import, i.e. the above code **would** keep the repos up and wouldn't call shutdown until python exit (or explicitly called by the user). Would do you think?

**Comment by rob-c** [comment]
I'm just curious about the opinion as I was just under the assumption that maybe once I'm finished and can't access 'ganga' any more it would be sensible to close and flush any changes I've made?
I can see the motivation for keeping things in the future but then what happens if I run:
```
myFunc()
myFunc()
```
Would the 2nd import here cause Ganga to be re-initialized despite the fact that a lot of global objects are still persisting in memory at the moment?

**Comment by drmarkwslater** [comment]
I believe (and @milliams or @alexanderrichards can comment here!) that if you do a subsequent import, then you just access the instance that's cached in memory, i.e. it won't initialise anything a second time because it won't run the `__init__.py` code a second time.

**Comment by milliams** [comment]
Indeed, quoting from [the manual](https://docs.python.org/2.6/reference/simple_stmts.html#import):

> Import statements are executed in two steps: (1) find a module, and initialize it if necessary; (2) define a name or names in the local namespace.
>...
> The first place checked is sys.modules, the cache of all modules that have been imported previously. If the module is found there then it is used in step (2) of import.

**Comment by rob-c** [comment]
OK, after playing with the code it looks like you're correct. I think I was getting myself confused about nothing here.
Would we ever sanely expect to be wanting to allow the user to unload 'ganga' after importing it do we think? (I'm happy if the answer is no)

**Comment by drmarkwslater** [comment]
I think we need this functionality (and was actually the source of the confusion in #180 due to my poor wording of it) for the tests if nothing else. But I can also see a use case for normal users as well - they might want to be sure that they have 'shut ganga down' after leaving a function. This may lead to issues of starting it up again though - I'm not sure how to force python to unload a module so you can reimport it....

**Comment by egede** [comment]
Towards the user, I do not really think we can do this. I think that just simple code like

`import ganga
j = ganga.Job()
reload(ganga)`

will effectively leave two instances running as you can't get rid of the reference to the jobs that you created (and thus can't completely get rid of the old code before reloading). Take a look at http://stackoverflow.com/questions/437589/how-do-i-unload-reload-a-python-module
where the relevant sentence is 

> As with all other objects in Python the old objects are only reclaimed after their reference counts drop to zero.

**Comment by rob-c** [comment]
So do we want to expose and encourage use of a ```shutdownGanga``` method which does a cleanup of our internals which allows for Ganga to be stated up again?
(I imagine this to basically be a hook to the atextit manager)

**Comment by milliams** [comment]
I feel that for explicitness and simplicity a single function which shuts down any of the run-time services we might be running is a good idea.

**Comment by rob-c** [comment]
OK, after reading, http://bugs.python.org/issue9072 It looks like 'un-loading' of a module is a bad way to go.

I think we should probably in this case move to make the ```import ganga``` effectively just call a simple ```setUpGanga``` method might be a better approach as then we could have a ```setUpGanga``` and ```tearDownGanga``` method which encapsulates everything to do with startup/shutdown?

**Comment by egede** [comment]
> I think we should probably in this case move to make the import ganga effectively just call a simple setUpGanga method might be a better approach as then we could have a setUpGanga and tearDownGanga method which encapsulates everything to do with startup/shutdown?

@rob-c Seems good to me. I do not see any need to expose these methods to the user though.
