### ISSUE TITLE
MassStorageFile remove method bugs

### ISSUE THREAD

**Issue by joj0s** [ganga-devs/ganga#2032]
While testing the MassStorageFile class for #1627, I found a couple of bugs that cause the `remove` method to break.

- BUG 1:
[This line of code](https://github.com/ganga-devs/ganga/blob/d7b5f9db3b0e37a39a9e93a1df67599c65f54ab3/ganga/GangaCore/GPIDev/Lib/File/MassStorageFile.py#L516) should use the `remove` method instead of the `pop` method, since the local i variable is a filepath and not an index. Right now it causes a `TypeError`.

- BUG 2:
Even if the are multiple file locations to remove, [this loop](https://github.com/ganga-devs/ganga/blob/d7b5f9db3b0e37a39a9e93a1df67599c65f54ab3/ganga/GangaCore/GPIDev/Lib/File/MassStorageFile.py#L495) always exits after one iteration. This is due to `self.locations` being an instance of `GangaList` and not a regular list, and there is some fault in the implementation which I haven't yet discovered. I can confirm however that converting `self.locations` to a regular Python list using a list comprehension fixes the problem and loops as expected.

I can submit a PR to fix those, but I'm not sure how you want to deal with the second bug. Is it OK to use the quick fix I suggested or should I keep looking for the fault in `GangaList`?

**Comment by egede** [comment]
I am not sure that the problem is with `GangaList`, I think it might just be due to that you iterate over a list that you are modifying. This leads to undefined behaviour in python.  So the "quick fix" is correct I believe.
