### ISSUE TITLE
Core codebase linting report

### ISSUE THREAD

**Issue by joj0s** [ganga-devs/ganga#2044]
As per our last discussion, I ran flake8 on the entirety of the Ganga maintained codebase to help us identify PEP8 violations and decide what rules to enforce for the codebase in the future. In particular I found

- **1075 E501 (Line too long) violations**. The line limit I set was 120 characters.
- **801 F401 (Unused import) violations**.
- **502 E265 (Block comment should start with '#') violations**.
- **378 F821 (Undefined name) violations**. Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaCore/Runtime/GPIexport.py#L64).
- **286 W291 (Trailing whitespace) violations**. Even though a previous autopep8 PR fixed whitespace issues, it doesn't automatically fix comments, this is where all the whitespace violations still exist.
- **270 F841 (Local variables are assigned but never used) violations.** Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaCore/Runtime/Repository_runtime.py#L134).
- **209 F405 ('x' may be undefined or defined from start imports) violations.** Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaCore/Runtime/GPIFunctions.py#L101).
- **131 E722 (Using bare except) violations.**
- **110 W605 (Invalid escape sequence) violations.** Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaCore/Runtime/GangaCompleter.py#L15).
- **66 W504 (Line break after binary operator) violations.** Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaCore/Runtime/gangadoc.py#L200).
- **48 F811 (Redefinition of unused 'x') violations.** Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaCore/Runtime/bootstrap.py#L1232) (redefined from line 1202).
- **48 E266 (Too many leading '#' for block comment) violations.** Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaCore/Runtime/GangaCompleter.py#L28).
- **41 F403 (Unable to detect undefined names) violations.** Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaCore/old_test/GPI/MigrationFramework/Test1/AttributeMigration.py#L8).
- **41 E741 (Ambiguous variable name) violations.** Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaCore/test/GPI/TestLogger.py#L35).
- **38 E713 (Test for membership should be 'not in') violations.** Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaCore/Runtime/Repository_runtime.py#L208).
- **31 E712 (comparison to True should be 'if cond is True:' or 'if cond:') violations.** Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaCore/test/GPI/FileTests/TestMassStorageClient.py#L111).
- **29 W293 (Blank line contains whitespace) violations.**
- **22 E721 (Do not compare types, use 'isinstance()') violations.** Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaCore/Utility/Config/Config.py#L441).
- **22 E714 (Test for object identity should be 'is not') violations.** Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaLHCb/Lib/LHCbDataset/LHCbDataset.py#L519).
- **21 E704 (Multiple statements on one line) violations.** Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaCore/Utility/files.py#L76).
- **16 W503 (Line break before binary operator) violations.** Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaCore/GPIDev/Adapters/IPostProcessor.py#L152).
- **13 F632 (use ==/!= to compare constant literals str, bytes, int, float, tuple) violations.** Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaCore/test/GPI/TestShared.py#L107).
- **6 E114 (E114 indentation is not a multiple of 4 (comment)) violations**. Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaCore/GPIDev/Lib/Job/JobTime.py#L420).
- **5 E711 (Comparison to None should be 'if cond is None:') violations.**
- **4 F541 (F string is missing placeholders) violations.**. Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaCore/Core/GangaRepository/container_controllers.py#L241).
- **2 F523 (.format(...) has unused arguments) violations**. Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaCore/Runtime/bootstrap.py#L58).
- **2 F507 ( % ... has 1 placeholder(s) but 2 substitution(s)) violations**. Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaCore/GPIDev/Base/Proxy.py#L1011).
- **2 F402 (import 'x' from line shadowed by loop variable)**. Example [here](https://github.com/ganga-devs/ganga/blob/d8a2542ddd27dd437f15cb0ab06746f8c38dfbe3/ganga/GangaTest/Lib/TestRobot/Tester.py#L72).
- **2 E303 (Too many blank lines) violations.**
- **2 E301 (Expected 1 blank line, found 0) violation.**
- **1 E305 (Expected 2 blank lines after class or function definition, found 1) violation.**
- **1 E231 (Missing whitespace after ',') violation**

**Comment by joj0s** [comment]
As you can see it is quite a large number. I suggest we start by deciding if we will omit any of these rules from future linting checks so I can submit a PR with the appropriate linting setup in GitHub Actions.

**Comment by egede** [comment]
All the ones that are relatively rare, we can just keep (it wouldn't make much difference if they are omitted), so I would say, it is really just the ones with 50 or more violations that are up for discussion. Looking at those, I feel a bit that they divide up into "trivial to fix" (i.e. F401 (Unused import) violations.) and harder to fix but potentially important (E722 (Using bare except) violations., W605 (Invalid escape sequence) violations). My suggestion would be to:

- Include all the rules as above
- Make the check non-mandatory to pass. So we can merge without it, but really should not.
- A recommendation to create a separate PR that fix the (unrelated) PEP8 issue and then submit the real code change as a now PEP8 compliant PR.

**Comment by joj0s** [comment]
All of that sounds good. Just two things to note:
1. Linting the project on CI is going to be a problem until we sort out the current PEP8 violations as we will always end up with a failing check and thousands of output lines. In the meantime, to ensure code quality on new PRs I can add a git hook that acts as a warning on the devs' machine before the code reaches CI, and add a GitHub Action that lints **only newly changed files** (likely using [this action](https://github.com/tj-actions/changed-files)). Let me know if you agree.
2. As far as I can tell, Github Actions does not support an intermediary _warning_ state. See [this issue](https://github.com/actions/runner/issues/2347) and [this discussion](https://github.com/orgs/community/discussions/15452). Which means that it will either always be a green check by having the linter always exit 0 (as it is right now) or it will be a red check when failing but still allow merging.

**Comment by egede** [comment]
1. Yes, to lint only changed files I think is the way to go. Obviously this is not ideal, but we might then file issues on sorting out some of the individual ones (like fixing all bare except clauses).
2. I think it is fine to have the test as a fail but still allow merging - that was actually what I had in mind when I said warning.
