### ISSUE TITLE
Obsolete URL for documentation and support

### ISSUE THREAD

**Issue by kh296** [ganga-devs/ganga#2051]
Just a small thing, but the print out when starting Ganga includes a line referencing a URL that's no longer valid:
```
Documentation and support: http://cern.ch/ganga
```
This is coming from [GangaCore.Runtime.bootstrap](https://github.com/ganga-devs/ganga/blob/50902fa181aec8c6eff5dbecec5b676589fbb81a/ganga/GangaCore/Runtime/bootstrap.py#L229).  The same URL shows up in a few other places (try repository search for "documentation and support"), I think all in the user documentation.

It could be useful for the URL to be upated.

**Comment by mesmith75** [comment]
Thanks - we'll get that updated.
