### ISSUE TITLE
ganga 8 montoring freezes or freezes a finishing job on exit

### ISSUE THREAD

**Issue by Deborah-Morris** [ganga-devs/ganga#2067]
hi, i am currently migrating the sno+ data processing system from python2/ ganga 7 to python3/ ganga 8.

we call GangaCore.monitoring_component.runMonitoring this runs, returns then ganga either fails to close waithing on a Job (number) Finalizing background thread OR forces the Job Finalizing thread closed preventing the job from ever finishing.

I think this is related to the issue from VukanJ number 1855, the problem is we are running in a script and cant do anything to wait for the finishing job to finish.

**Comment by Deborah-Morris** [comment]
[monitoring thread crash.txt](https://github.com/ganga-devs/ganga/files/9658139/monitoring.thread.crash.txt)
here is a terminal dump with --debug of the monitoring thread crashing.
edit, it does something else after that dump, here is a longer one
[monitoring thread crash longer.txt](https://github.com/ganga-devs/ganga/files/9658274/monitoring.thread.crash.longer.txt)

**Comment by egede** [comment]
Looking at the long debug file, I see that it is trying to finalize 5 subjobs from DIRAC (corresponding to the 5 threads that are dealing with this). Then a minute later these are still not finished (seems a bit long, but depending on what is downloaded from Dirac, this might be reasonable). What then happens for the next 10 minutes is not clear. Do you run this as a script or do you run interactively? If as a script, can you try interactively instead - I wonder if there is a bug where Ganga is waiting for input on stdin?

**Comment by Deborah-Morris** [comment]
run as a script, not interactively. i don't think our jobs take very long to finish. i have left this running overnight with the same result so it isn't waiting for the job to finish.
Edit: we also pipe in "yes" to it but it doesn't help, I am not sure how to run it interactively our system is quite complex and has a lot of scripts.

**Comment by Deborah-Morris** [comment]
[ganga actual error.txt](https://github.com/ganga-devs/ganga/files/9668113/ganga.actual.error.txt)
running in interactive mode got me this error, it is calling a function that doesn't exist in dirac or it isn't able to communicate with dirac... i think

**Comment by Deborah-Morris** [comment]
... or maybe dirac isn't installed. I assumed if that was the case ganga would give some kind of error. i will try ~tomorrow~ our system is loaded down with reprocessing, i will try over the ~weekend~. _later_

**Comment by egede** [comment]
I assume that this is submitting jobs to the Dirac WMS at Imperial? To me it indeed looks like a setup problem. Looking at [how we setup testing against the Dirac WMS at Imperial](https://github.com/ganga-devs/ganga/blob/229dc06a38e6093a85f0bcda54b9126d80e76a50/.github/workflows/ci_push_testing.yml#L179)  in our CI testing might be helpful. Otherwise @alexanderrichards might be able to provide a bit more local help.

**Comment by alexanderrichards** [comment]
Can you check you have a local DIRAC UI installed. For running against the Imperial DIRAC instance you should use the UI setup instructions listed [here](https://www.gridpp.ac.uk/wiki/Quick_Guide_to_Dirac). Note that you may also have an old UI setup and that Imperial made changes to the underlying DIRAC instance that required the updating of your UI.

**Comment by egede** [comment]
I am clising this as there has been no further discussion. Please reopen if there are still questions to be answered.
