### ISSUE TITLE
Issue adding new arguments to command

### ISSUE THREAD

**Issue by gurudattapatil** [ganga-devs/ganga#2074]
[Branch](https://github.com/ganga-devs/ganga/tree/cli)
PR #2061 
[Code](https://github.com/ganga-devs/ganga/blob/5a7e9d7faa99e9537806818e92f2ac95715fb673/bin/ganga-gui-terminal#L29)
Unable to add new args to code, --internal-port as it is not defined in the usage, unable to locate where this error arises  
<img width="934" alt="Screenshot 2022-10-10 at 3 51 16 PM" src="https://user-images.githubusercontent.com/42720547/194846322-8743d0f7-d281-4a85-8b42-adc768e3e94c.png">

**Comment by mesmith75** [comment]
Does it work in quotation marks?

**Comment by egede** [comment]
I think the error comes from the code around [this line](https://github.com/ganga-devs/ganga/blob/5a7e9d7faa99e9537806818e92f2ac95715fb673/ganga/GangaGUI/gui/cli.py#L112). You get a second processing of command line arguments there (a bit messy to do this twice). As `internal-port` is not listed there, it gives an error.

**Comment by gurudattapatil** [comment]
Thank you ulrik that seems to be it.
Will start working on the command
