### ISSUE TITLE
Require Python 2.7

### ISSUE THREAD

**Issue by milliams** [ganga-devs/ganga#21]
All our code already runs on Python 2.7 without issue but we would like to move to _requiring_ it so that we can make the most of its features and make future-proofing for Python 3 easier.

I have a plan about how to enact the change and will put up a feature branch soon with the code.

**Comment by alexanderrichards** [comment]
@milliams sounds excellent to me and a long time coming

**Comment by JacekHoleczek** [comment]
[See my entry in the "Move to IPython 3.x by default thread".](https://github.com/ganga-devs/ganga/issues/20#issuecomment-150938436)

**Comment by egede** [comment]
@milliams can you remind about how to make python 2.7 available on plain slc6 systems. I guess it does require a sysadmin involvement though.

@JacekHoleczek are you sure that Python 2.7 is not already available as "python2.7" on the system?

**Comment by milliams** [comment]
@alexanderrichards On SLC6: Add http://linuxsoft.cern.ch/cern/scl/slc6-scl.repo as `/etc/yum.repos.d/slc6-scl.repo` and then `yum install python27`

On SL6, Fedora, CentOS, RHEL etc.: Follow [these instructions](https://www.softwarecollections.org/en/scls/rhscl/python27/).

Once that's done, you can run it with `scl enable python27 python`

**Comment by JacekHoleczek** [comment]
I think the problem is that I'm just a "guest" on any external computing clusters.
I do not manage them and I believe it will be extremely difficult to convince remote administrators to install additional software just because I want it.
That said, I believe that even if an additional python 2.7 version is installed on the "User Interface" machine, there is no guarantee that it's also installed on all of the "batch machines" (e.g. PBS or grid) and there is no guarantee that a comprehensive set of additional accompanying python packages are installed as well (which one can expect for the "system default" python version).
(The same holds for the "ipython", of course.)

**Comment by alexanderrichards** [comment]
> there is no guarantee that it's also installed on all of the "batch machines" (e.g. PBS or grid)

The python 2.7 requirement would be for the user interface only and all run scripts will remain 2.6 compliant as Ulrik reminds us https://github.com/ganga-devs/ganga/issues/20#issuecomment-150518601

**Comment by milliams** [comment]
Indeed, we need to assume that any remote code can run on a bare install of SL6 (which means Python 2.6). If a particular experiment wants newer software then they follow their usual processes (CVMFS etc.) which for LHCb means Python 2.7 is available but cannot assume this.

Finally, if a user does not have administrator access (or a friendly sysadmin) for their UI box then it's not impossible to install Python 2.7 in their user area.

**Comment by JacekHoleczek** [comment]
I think I can see another potential problem.
Assume that the "system default" python is 2.6 but on the UI machine I make 2.7 my default python (for Ganga purposes).
What will then happen to any jobs which Ganga starts on the "local host" ("Interactive" and "Local" backends)?
Will they get the "system default" python or will they inherit the same python as Ganga uses (i.e. together with any new PATH, LD_LIBRARY_PATH, PYTHONPATH settings)?

**Comment by rob-c** [comment]
The localhost, batch and interactive backends 'should' always use the system level python binary.
In practice for the Interactive at least gets the python version from the running environment so would always be a 2.7 version if we moved today.
We work around this by launching Ganga through a script which doesn't pollute the running environment and imo this would have some advantages. Alternatively the backends need to expressly call (and check for) a chosen version of Python.

(aside)
I'm working slowly toward looking to merge the underlying code for Interactive/Localhost and Batch as this can largely share the same underlying technology with the only major change being the managmentr of the stdout/stderr streams. This would mean that we can do all the checking in one sane place but this is still very much wip

**Comment by egede** [comment]
> What will then happen to any jobs which Ganga starts on the "local host" ("Interactive" and "Local" 
> backends)?

@JacekHoleczek I think you are correct that there is a bit of a problem here. The local wrapper script indeed has a "/bin/env python" in the first line so if your default is now Python 2.7 then it will pick up that. However, if you want to make sure that your own script runs in Python 2.6, then you should in your own script insert a "/bin/env python2.6" magic line. If you depend on a specific python version, I would indeed always be specific.

**Comment by JacekHoleczek** [comment]
I think I backup the request that "localhost, batch and interactive backends 'should' always use the system level python binary" without any need for any special user's actions.
Some jobs may internally depend on the python version (e.g. there may be something that internally calls PyROOT) and so they should get the same environment regardless of which backend is used.
So, only if the user's job needs another python then the user should be responsible for proper initialization of additional components, otherwise it should get the "system default" settings.

**Comment by rob-c** [comment]
@JacekHoleczek PyROOT is a 'special' case of a python script where the version of python from the system is used to execute the Python script associated with the ROOT version that the user requested.

The levels of (re)-execution should match:

Ganga (Python-2.7-ganga) -> LocalHost script (Python-2.7-ganga)->Ganga PyROOT script(PyROOT-x.y)->User PyROOT Script(PyROOT-x.y)

(By this point you're 4 levels deep of programs internally executing other programs so you can appreciate that this can get tricky.)

Technically the payload python scripts (Localhost or Batch scripts) which are all executed at Ganga's request are all wrappers around the actual payload scripts requested by the user so can be written to be as version agnostic as possible.
Some programs such as PyROOT and others inject another layer of re-execution to make sure the correct environment is setup as the user requests, and this finally

**Comment by JacekHoleczek** [comment]
So, the proposal would be to use the following chain:

Ganga (Python-2.7-ganga) -> /proper/login/shell -l -> LocalHost script (system-python)-> ...(system-python)...

or:

Ganga (Python-2.7-ganga) -> LocalHost script (Python-2.7-ganga) -> /proper/login/shell -l -> ...(system-python)...

**Comment by rob-c** [comment]
@JacekHoleczek This is something I'm considering but I think the focus first is to look into merging as much of the code as possible for the 'local-type' backends to reduce duplication of bugs and avoid other problems. This would allow us to add/remove any extra step in a sensible structured way.

**Comment by JacekHoleczek** [comment]
I think ROOT and PyROOT are a bit "special" ... I can explicitly ask for a particular ROOT version in the ".gangarc" file and then the "setup.sh" script for this ROOT version is expected to modify relevant environment variables (including PYTHONPATH), but it will NOT try to switch the python version (to the one that was used when ROOT was compiled), so we need to make sure that the "correct" python is seen in advance (note: the job is not necessarily a PyROOT script, it can be a C++ script which internally calls PyROOT).

**Comment by milliams** [comment]
This is now underway in PR #38.

**Comment by mesmith75** [comment]
done.
