### ISSUE TITLE
Rewrite credential store without files

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#2103]
The AFS token isn't there on lxplus8 so produces a nasty error.
lxplus8 seems to be using a keyring, rather than a file to store the token. It may take a bit of reworking.

**Comment by mesmith75** [comment]
Essentially the issue is that we expect all credentials to be files so all our checks involve looking for them. I would propose rewriting how the credentials are done so we don't do that.

**Comment by egede** [comment]
Maybe the use of https://pypi.org/project/keyring/ will be beneficial.

**Comment by chrisburr** [comment]
It will probably more reliable to query kerberos directly for the credential state rather than trying to reverse engineer how it interacts with the kernel keyring.

(Plus, I think https://pypi.org/project/keyring/ doesn't have a suitable backend for lxplus.)

**Comment by egede** [comment]
Fixed by #2223
