### ISSUE TITLE
Broken method in Job class

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#2109]
The method [_outputfieldCopyable](https://github.com/ganga-devs/ganga/blob/45d523f0895c2992a4c9bc5aba1fae6b5a3867f8/ganga/GangaCore/GPIDev/Lib/Job/Job.py#L138) in the Job class is manifestly broken as it doesn't return anything and has no side effects. So the method should just be removed.

A bit of care should be taken as it is used twice in the [schema](https://github.com/ganga-devs/ganga/blob/45d523f0895c2992a4c9bc5aba1fae6b5a3867f8/ganga/GangaCore/GPIDev/Lib/Job/Job.py#L207) of the Job class. These two places will have `None` assigned where in principle a bool is expected. I think that False can just be assigned instead.

**Comment by mesmith75** [comment]
gnore this - I see what has happened
