### ISSUE TITLE
Fix GUID of Gaudi output files uploaded to SE for LHCb

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#211]
If an output file (like a DST) is produced in LHCb outside the Grid environment, and subsequently upoloded to an SE, it gets assigned the wrong GUID and a subsequent Gaudi job can't read it. So the following workflow
1. Brunel job running on a batch system produce a DST
2. The output DST is declared a DiracFile and uploaded to an SE.
3. DaVinci job reading this DST directly from SE attempts to run.

At the moment, step 3 will fail unless the script `dirac-lhcb-fix-file-guid` has been executed. Looking inside the script, it sets the GUID at upload from the result of a call to `getRootFileGUID` from `LHCbDIRAC/Core/Utilities/File.py`. The solution is to insert this call for LHCb users before the `put` method is used in `DiracFile`.

**Comment by rob-c** [comment]
Would this be best fixed by changing the code such that the LHCb plugin modifies the DiracFile config to be managed by the worker nodes and have a short payload script perform the file upload just using the correct LHCbDirac commands?

**Comment by egede** [comment]
In fact you need both. You also need to support

```
f = DiracFile(namePattern='myEvents.dst')
f.put()
```

**Comment by rob-c** [comment]
Ah ok. This could be a bit tricky but might be best done by overloading a Dirac command from within LHCb in a clever way.

**Comment by egede** [comment]
We could make a generic function in the GangaDirac package that can set the GUID before the file is uploaded. There it would just be a noop. In GangaLHCb we would then overload that function.

**Comment by egede** [comment]
Philippe Charpentier claims that the addFile method from LHCbDIRAC already does this. Some further debugging of the current behaviour required before anything else is done is required.

**Comment by rob-c** [comment]
I don't know off the top of my head what functions we're using. This may be possible to fix by simply changing the LHCbDirac command to point to the correct bit of code. (Or fix DiracFile to use the abstracted commands we define in Ganga)

**Comment by egede** [comment]
This has been fixed - broken - fixed by LHCbDIRAC
