### ISSUE TITLE
Refactor Job.py

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#2117]
The [Job.py](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/GPIDev/Lib/Job/Job.py) file is in strong need of getting broken up. There are several classes defined that can be put into individual files. Maybe also some obvious candidates for breaking into utility type functions.

**Comment by shalearkane** [comment]
If this issue is not taken, could you assign this to me?

**Comment by egede** [comment]
> If this issue is not taken, could you assign this to me.

I think it would be good just to wait for the PR #2119 to be integrated back into the `develop` branch. Otherwise you would have to deal with a large number of merge conflicts. Maybe deal with #2114 which should be very quick and then hopefully this one is ready for qork in a few days.

**Comment by shalearkane** [comment]
Alright, I am preparing the patch for #2114

**Comment by mesmith75** [comment]
Fixed by #2144 and #2156
