### ISSUE TITLE
Issues found with 6.1.16 release candidate

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#212]
So after testing I've found the following problems. I believe these are probably covered in other issues but as regards getting 6.1.16 out ASAP, I want to discuss them in one place and from a known place!

1. Tasks doesn't persist the state of Transforms. This is a showstopper as if you create a task, set some transforms going, and restart Ganga, the transforms are reset to default ones even though they are correctly recorded in the XML. This is down to `makeGangaListByRef` in `GangaList.py`:
```
temp_list = [stripProxy(element) for element in _list]
result._list = temp_list
```
This does something very odd - the temp_list is correct but the _list in result is not and goes through and resets everything to newly created objects.

2. Job.inputdata is not copied correctly. So if you you do `j.copy()` with inputdata set to something, it doesn't copy the inputdata at all. This is due to the spurious `__copy__` function in `Objects.py`:
```
    def __copy__(self):
        copied_obj = self.clone()
```
This does nothing and overrides the proper `__copy__` function further up the file. There is additional problem with the proper function in that the parent is not set correctly.

3. After fixing the above, Job.inputdata is still not set correctly and not schema attributes are copied. This is because in `Job.py` it is a `copy.copy` rather than a `deepcopy` as the other values are. This should be changed to a deepcopy as otherwise you don't copy any of the appropriate values.

I'm going to put a PR together to fix these things but in the mean time we can discuss these or any other issues.

On the plus side, the monitoring and status of jobs all seems rock solid and I haven't had any lock ups yet :)

**Comment by rob-c** [comment]
Do you mean develop as the rc for 6.1.16 or is there a pre somewhere? (apologies if I've missed an email)

**Comment by drmarkwslater** [comment]
I mean develop - I was being optimistic that this will basically be 6.1.16 :)

**Comment by rob-c** [comment]
The copy method for Job also calls all of the ```__setstate__``` so is a bit of a pain from my experience.

I had a one line fix for this in the LHCb branch, I'm a bit busy until 16:00 but I'll see what I did then. I think I just marked an object as copyable in the schema as it made this problem go away allowing for it to be copied internally within ganga.

**Comment by rob-c** [comment]
I thought tasks was being delayed until 6.1.17?

**Comment by rob-c** [comment]
@drmarkwslater does this problem exist after looking at #179 it might be fixed there.

**Comment by drmarkwslater** [comment]
The problem was that `__copy__` wasn't getting called at all - the function lower down was which did nothing. As regards Tasks, if it was restricted to Tasks then OK, but this seems like quite a major issue that would hit us elsewhere. I'm happy for others to decide though.

**Comment by drmarkwslater** [comment]
@rob-c Nope - #179 doesn't fix this problem.

**Comment by rob-c** [comment]
ok, thanks for checking :)

**Comment by egede** [comment]
> I'm going to put a PR together to fix these things but in the mean time we can discuss these or any other issues.

@drmarkwslater Yes, please do this. Do *not* fix directly in the development branch.

**Comment by drmarkwslater** [comment]
Don't worry - I wasn't going to :)

**Comment by egede** [comment]
This has all been allocated to other PRs.
