### ISSUE TITLE
importing ganga from python prompt causes config to be executed multiple times

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#2129]
When doing `import ganga.ganga` from a standard python prompt the config file is read multiple times.
```python
In [1]: import ganga.ganga
INFO     reading config file /home/egede/.gangarc
INFO     reading config file /home/egede/.gangarc
INFO     reading config file /home/egede/.gangarc
INFO     reading config file /home/egede/.gangarc
INFO     reading config file /home/egede/.gangarc
```
This might be related to each of the of the plugins defined in the `.gangarc` file. Printing a traceback at the point where the [INFO statements above appear](https://github.com/ganga-devs/ganga/blob/db078fb3ee9f76f45ec5b23c249cd03512b717f8/ganga/GangaCore/Utility/Config/Config.py#L866) might reveal the problem.

**Comment by vedanshbhartia** [comment]
Hi Ulrik, may I take up this issue?
