### ISSUE TITLE
Continuous integration testing for Dirac and LHCb to el9 architecture

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#2138]
As CERN will start to see a significant deployment of Alma Linux 9 machines, we should do some testing there.

**Comment by mesmith75** [comment]
on lxplus9:
```
[masmith@lxplus923]~$ ganga
/cvmfs/ganga.cern.ch/Ganga/install/8.6.5/bin/python3: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
[masmith@lxplus923]~$ which ganga
/cvmfs/lhcb.cern.ch/lib/bin/ganga
```

**Comment by egede** [comment]
> on lxplus9:
> 
> ```
> [masmith@lxplus923]~$ ganga
> /cvmfs/ganga.cern.ch/Ganga/install/8.6.5/bin/python3: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
> [masmith@lxplus923]~$ which ganga
> /cvmfs/lhcb.cern.ch/lib/bin/ganga
> ```

Clearly we need to fix that as a first step. We are using `python3` from LCG_100.  Looking at that one, it was never built for `centos9` or whatever the architecture is called. For LCG_103 that is the case though. So I wonder if we simply go to `/cvmfs/sft.cern.ch/lcg/releases/LCG_103/Python/3.9.12`. I would still point it to the `centos7` version and then see if that works.

**Comment by mesmith75** [comment]
Then we need to make sure that #2150 is sufficient

**Comment by egede** [comment]
With #2150 fixed, this issue can now be progressed.

**Comment by egede** [comment]
The tests related to `dirac` and `lhcb` should now be easy to migrate to the `el9` architecture.

**Comment by egede** [comment]
Dirac has been migrated. Only LHCb left.
