### ISSUE TITLE
Change required or how extras (like [LHCb]) are used.

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#2155]
I noticed the following warning in the stdout from installing Ganga in CVMFS. Having read through the provided link, I do not understand what change is required though.

```
DEPRECATION: [git+https://github.com/ganga-devs/ganga.git@8.6.4#egg=ganga](mailto:git+https://github.com/ganga-devs/ganga.git@8.6.4#egg=ganga)[LHCb] 
contains an egg fragment with a non-PEP 508 name pip 25.0 will enforce this behaviour change. 
A possible replacement is to use the req @ url syntax, and remove the egg fragment. 
Discussion can be found at https://github.com/pypa/pip/issues/11617
```

**Comment by vedanshbhartia** [comment]
pip is removing support for specifying extras (https://peps.python.org/pep-0508/#extras) in an egg name. The `[LHCb]` portion of the egg in `egg=ganga[LHCb]` is probably triggering this warning. 
Changing `pip install <url>#egg=ganga[LHCb]` to `pip install ganga[LHCb]@<url>` should fix the issue.

**Comment by egede** [comment]
> pip is removing support for specifying extras (https://peps.python.org/pep-0508/#extras) in an egg name. The `[LHCb]` portion of the egg in `egg=ganga[LHCb]` is probably triggering this warning. Changing `pip install <url>#egg=ganga[LHCb]` to `pip install ganga[LHCb]@<url>` should fix the issue.

Thanks for translating the rather mysterious warning. This indeed works.
