### ISSUE TITLE
File left open when obtaining timestamps

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#2167]
When obtaining the timestamps for a Local job, the status file will be left open in most cases. The [current implementation](https://github.com/ganga-devs/ganga/blob/6fdf1fd9be4dedbf59fcf3dc5b77dbafcadb92d3/ganga/GangaCore/Lib/Localhost/Localhost.py#L191) should be changed to using a `with` clause.

**Comment by matheus-LLC** [comment]
Hi egede! I've created a PR for this issue, let me know if this fix is suitable. 

Kind regards,
Matheus
