### ISSUE TITLE
Migrate the autopep8 PR creation step to use environment files

### ISSUE THREAD

**Issue by joj0s** [ganga-devs/ganga#2170]
The `set-output` command used in the [autopep8 PR creation step](https://github.com/ganga-devs/ganga/blob/7e2ccfa909efd7f1567f69d1cdf04a9d84c0c252/.github/workflows/ci_push_testing.yml#LL74C13-L74C13) has become deprecated (ref: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

This step should be updated to use environment files instead.

**Comment by alexanderrichards** [comment]
This is done.
