### ISSUE TITLE
Interactive backend should save a log file

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#2174]
Would be helpful to have a `stdout` saved in the gangadir for Interactive jobs.

**Comment by saumy-sh** [comment]
hey @mesmith75 I would very much like to work on it. Could you help get started with it as rn I am pretty new to it?

**Comment by mesmith75** [comment]
Great! The script that runs when you submit an interactive job (`j.backend=Interactive()`) is here: https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/Lib/Interactive/InteractiveScriptTemplate.py.template

The interactive job currently only prints output to the screen. It would be useful to have the output also piped to a log file which then gets copied to the job's outputdir, as happens for the `Local` backend.

**Comment by saumy-sh** [comment]
Hey @mesmith75 can you please help me. I first forked the repo and then cloned it. But now I wanted to see how these files work so ran them in vscode but they give error. How should I proceed?

**Comment by saumy-sh** [comment]
Hey @mesmith75  I am not able to use ganag. I installed it on linux virtual machine but command is not being detected.

**Comment by alexanderrichards** [comment]
how did you install it? did you use pip?

**Comment by saumy-sh** [comment]
yes , since I have windows so I first setup virtual ubuntu machine. Then I installed python. After that I installed ganga using pip install ganga. It did get installed but i tried using it by typing ganga but it isn't recognising it.

**Comment by alexanderrichards** [comment]
I did the following from a new ubuntu container
```shell
apt update && apt upgrade
apt install python3 python3-pip
pip install ganga
```
this was enough to install ganga and have the "binary" on the path

**Comment by saumy-sh** [comment]
I tried it but am still not able to use it. Same error is shown again

**Comment by saumy-sh** [comment]
Maybe it's because of virtual machine.

**Comment by saumy-sh** [comment]
hey now I am able to run ganga.
