### ISSUE TITLE
Pylint with Ganga scripts

### ISSUE THREAD

**Issue by kh296** [ganga-devs/ganga#2179]
Is there a way of running `pylint` for a `Ganga` script such that GPI classes are recognised?

For a minimal script `ganga_example.py`:

```
"""Example Ganga script."""
j = Job()
j.submit()
```

and from an environment set up for running `Ganga`, I obtain:

```
ganga ganga_example.py
# Job completes successfully.

pylint ganga_example.py
# ganga_example.py:2:4: E0602: Undefined variable 'Job' (undefined-variable)
#
# ------------------------------------------------------------------
# Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)

ganga pylint ganga_example.py
# ERROR    'pylint' not found
```

I can understand `pylint` having issues with the script, given that the `Job` class isn't explicitly imported.  I was wondering if there's a workaround.

Thanks!

**Comment by egede** [comment]
To use a static analyser with something like Ganga that creates the namespace dynamically is obviously not trivial. I imagine that the `--init-hook` of pylint could somehow be used.
