### ISSUE TITLE
Dirac proxy problems

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#2192]
There are a few issues with the Dirac proxy:

- There are instances where a Dirac command fails because there is no proxy, returning a `GangaDiracError` and no message. Then if you create a proxy the Dirac server is already running so subsequent Dirac commands are unsuccessful, meaning Ganga has to be restarted.
  - We need to add some missing `require_credential` decorators
  - If the Dirac Proxy is being created we need to kill any running Dirac server process such that a new one starts next time
  - We need to make sure we propagate the `Dirac` errors into the exceptions properly

**Comment by egede** [comment]
> We need to make sure we propagate the Dirac errors into the exceptions properly

Can we make that work if the procy is created externally as well (in a different terminal or just by `!lhcb-proxy-init`?

**Comment by mesmith75** [comment]
I don't think that is wise. It would mean doing an `lhcb-proxy-info` every time we run a Dirac command which would be prohibitively slow.

I am fine for Ganga to only be concerned about the contents of the `credential_store` as that is a Ganga thing.
