### ISSUE TITLE
project-ganga mailing list closed for external users

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#222]
Do we want to open it up to everyone or just point people to github issues instead?

**Comment by alexanderrichards** [comment]
lets discuss this at the meeting today

**Comment by egede** [comment]
@drmarkwslater The list is "Open, with owner/admin approval", which I give to anybody trying to subscribe that is not obviously a spammer. We might anyway want to change but that should depend on what replacement github can offer.

**Comment by afortiorama** [comment]
Hi - I asked the question because the egroup is also clearly marked for LHCb and ATLAS, but currently I'm implementing a workflow for LSST. Also people from outside CERN don't seem to be keen to open a lightweight accounts and I think this means they need to be added manually but there maybe recipes for this.

**Comment by egede** [comment]
@afortiorama As part of moving away from the CERN infrastructure and make Ganga more generic in all aspects, we will move towards a system where

- Questions can be asked as issues in ganga-devs on GitHub (just as this one).
- Announcements (releases, important messages) will be made via a new GitHub hosted front page of Ganga. Changes in this page can be followed via an RSS feed or via a Twitter feed.

Does this sound like a good solution for the future?

**Comment by afortiorama** [comment]
I think github is better. Maybe you can separate ganga-users from ganga-devs to avoid mixing real bugs or feature implementations discussions with users dilemmas. I've subscribed this but I receive all your developments posts which as a user I might not want to receive. On the other hand I'd probably would likely be interested in other users questions and solutions.

**Comment by afortiorama** [comment]
in the meantime I'll post here my queues questions.

**Comment by egede** [comment]
@afortiorama You are welcome to subscribe. However, I think you can also just post questions without following. I believe that you automatically go on the watch list for questions that you post yourself.

**Comment by alexanderrichards** [comment]
> I believe that you automatically go on the watch list for questions that you post yourself.

correct, if your "Not Watching" a repo then you will only receive notifications if you are participating or if you are @mentioned

**Comment by afortiorama** [comment]
I subscribed few weeks ago actually. 

If I subscribe only my issues I don't get anybody elses which I might be interested in unless someone points me to it (or names me). It is a way to work. I guess that I can browse issues periodically to see if there is any interesting question.

**Comment by afortiorama** [comment]
I changed my watching status.

**Comment by alexanderrichards** [comment]
Unfortunately there is not an _easy_ way to have separate issue trackers for users and for developers. 

We could have a separate repo called say ganga-devs/ganga-support which we could use as the user issue tracker. This might actually be a nice solution in a way as it would allow us to use an issue template to ensure that the user gives us information like the version of ganga etc that they are using. This repo would then essentially be empty apart from the issue template.

@ganga-devs/core what do people think about this idea of a user issue tracker repo? If we like the idea I'll go ahead and set it up now.

**Comment by alexanderrichards** [comment]
You could even add shifters to a new support team which will let them monitor these issues but would mean that they couldn't change the code directly.

**Comment by drmarkwslater** [comment]
I have to say I don't have particularly strong feelings so whatever people think :smile:

**Comment by alexanderrichards** [comment]
thanks mark, I'll wait until I've heard back from a few more people before setting this up though because even though this would be simple enough to set up. I don't think we want to tell users to start using it only to then change our minds after a proper discussion.

**Comment by egede** [comment]
My feeling is that we put the cart in front of the horse here. Let us leave this for a months or so and see if we still think it is a good idea.

**Comment by afortiorama** [comment]
Another problem of naming people is that one has to know not only that they are on github but also their user name. Auto completion on this project brings only your names up. You can certainly wait to see how many people will flock here but from the user perspective it makes things slightly more difficult.

**Comment by Unode** [comment]
So the mailing list is currently closed: 

> Delivery has failed to these recipients or groups:
> 
> project-ganga@cern.ch
> Your message can't be delivered because delivery to this address is restricted.

Everything on github then?

**Comment by egede** [comment]
No, the list is not closed. However, it only accepts mails from users who are **on the list** in order to keep it free from spam. You are registered with the address alves.renato.jc@gmail.com

**Comment by Unode** [comment]
@egede Sorry about the confusion. The return message lead me astray.
