### ISSUE TITLE
__GangaInputData__.txt not created when using the Dirac backend

### ISSUE THREAD

**Issue by ghost** [ganga-devs/ganga#2220]
When using the `GangaDatasetSplitter` with the `Dirac` backend no `__GangaInputData.txt__` is copied to the worker node.  However, the relevant files stored in the Dirac catalogue are copied into the worker node.  

When using the local backend the `__GangaInputData.txt__`  is copied to the worker node.

Both myself and a colleague (@LieutenantPorky) have observed this.

Could this be a bug similar to #1584?

Minimal working example:

```
import ganga.ganga

# Some file with LFN paths, `LFN:/<experiment>/...`
with open("lfn-paths.txt") as f:
    paths = f.read().splitlines()

j = ganga.Job()

j.application.exe = "more"
j.application.args = ["__GangaInputData.txt__"]

j.inputdata = ganga.GangaDataset(files=[ganga.DiracFile(p) for p in paths])
j.splitter = ganga.GangaDatasetSplitter()
j.splitter.files_per_subjob = 2

# j.backend = ganga.Dirac()
j.submit()
```

**Comment by egede** [comment]
When you specify `inputdata` to a job that is submitted to Dirac, the responsibility of how that is dealt with is completely controlled by the Dirac server. For a Gaudi job that means that in some instances the data will be copied locally (like you observed), and in some instances it will be streamed. The choice depends on the local site where the job runs (network speed, local disk size etc.). 

Now, this lack of predictability is not great when you are not using a Gaudi application where this is transparent to you as a user. 

If you always want a local copy of the files in the working directory, you can simply specify them as `inputfiles` instead and a local copy will always be made. 

However, it seems like you want the opposite. We can't simply "not tell" Dirac about the files as the information is used for the site matching as well. We could provide the `__GangaInputData.txt__` file though and potentially even make it point to the local copies if they are already there. Would that work?

**Comment by ghost** [comment]
Thanks for the swift reply.

**Context: what we want to achieve**

Basically we want to create a ganga script which runs some executable over files stored on the UK GRID with Dirac.  We want to be able to split this job into subjobs using `ganga.GangaDatasetSplitter()`.  We wrote (an expanded version of) the above script naïvely assuming this was the best method to accomplish this.  

As @LieutenantPorky and I are currently writing the job submission scripts for this work we would happily edit the script to use any recommended method.

**Answers to question above**

So for our workflow streaming the data or copying locally should be fine.  I find the documentation for IO with Dirac a bit confusing.  Would these streamed files be seamlessly readable in the job?  Our current (non-ganga)  workflow is to just stream the data via XRootD but I found that a bit difficult to integrate with `GangaDatasetSplitter` .  

For our current tests the only thing that is causing an issue is the lack of `__GangaInputData.txt__` which we expected to exist and contain the paths of all data used in the job (local and streamed).

So the change you suggested would work - would this also include streamed files?

**Comment by egede** [comment]
The `__GangaInputData.txt__` file is now available on the worker node for Dirac jobs as well in the PR #2235. If a `DiracFile` object has more than one replica, there is no guarantee that the PFN written into  `__GangaInputData.txt__` is the one that is "closest" to the worker node the job runs on.

If you have a very large number of jobs (1000+) that each try to access the same LFN, then using this method of accessing it could be problematic. In that case, please get in contact and there might be a better way to achieve the same result.

This will be part of the next release made in the new year. If you want to try to use it earlier, it should be in the DEV version from tomorrow `ganga --ganga-version DEV`.
