### ISSUE TITLE
Condor tests are failing

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#2237]
The Condor CI tests are failing with the error
```
https://research.cs.wisc.edu/htcondor/repo/9.1/el7/release/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```
I imagine it is due to Condor no longer being available on centos7. Solution is presumably to upgrade the tests to run on `el9` instead. The CI code to change starts [here](https://github.com/ganga-devs/ganga/blob/01f17862a2e033e9d4b9a066dc45c45c55cd08c6/.github/workflows/ci_push_testing.yml#L172).

**Comment by souravpy** [comment]
So far I notice I have to change the https://github.com/ganga-devs/ganga/blob/01f17862a2e033e9d4b9a066dc45c45c55cd08c6/.github/workflows/ci_push_testing.yml#L177C33-L177C33
to el9, and subsequent commands to be usable by ubuntu instead of centos7 since Condor doesn't support it.
Am I correct?

**Comment by egede** [comment]
I believe this is already fixed and ready for the next release. See the PR #2243.
