### ISSUE TITLE
Problems getting access URL for particular file from CNAF-USER

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#2270]
Me again! Another issue with the latest version I've found is there's something odd going on getting the `accessURL` for a file from `CNAF-USER` for some reason (it may be others but certainly this one). If I do:
```
Ganga In [13]: DiracFile("LFN:/lhcb/user/m/mws/2024_01/833012/833012356/Gauss-30000000-100ev-20240112.sim", localDir="").accessURL()

Ganga Out [13]: ['root://x509up_u34811@eoslhcb.cern.ch//eos/lhcb/grid/user/lhcb/user/m/mws/2024_01/833012/833012356/Gauss-30000000-100ev-20240112.sim']
```
All is well. But for this file from CNAF:
```
Ganga In [14]: DiracFile("LFN:/lhcb/user/m/mws/2024_01/833012/833012362/Gauss-30000000-100ev-20240112.sim", localDir="").accessURL()
ERROR    GangaDiracError: 'CNAF-USER'

[14:23:28]
Ganga In [15]:
```
Note that there is no output and this hangs submission as well. I guess the Dirac thread breaks somehow? Anyway, this doesn't happen in 8.6.9 but I don't know/can't remember enough of the details to track down the error any further. 

Let me know if you need anything more!
Mark

**Comment by mesmith75** [comment]
Hmm, it works for me:
```python
[15:38:58]
Ganga In [1]: DiracFile("LFN:/lhcb/user/m/mws/2024_01/833012/833012362/Gauss-30000000-100ev-20240112.sim", localDir="").accessURL()
Ganga Out [1]: ['root://xrootd-lhcb.cr.cnaf.infn.it:1094//storage/gpfs_lhcb/lhcb/user/m/mws/2024_01/833012/833012362/Gauss-30000000-100ev-20240112.sim']
```
I suspect it is a problem with the credential - perhaps something is missing a decorator.

**Comment by drmarkwslater** [comment]
You're right - I've just recreated the proxy and it works fine. Very odd as the proxy was certainly valid as I checked it using `lhcb-proxy-info` and could submit jobs with it. Nevermind - sorry to bother you! 😄

**Comment by mesmith75** [comment]
I'll reopen as it suggests a missing decorator for the credential. Also that we didn't report the error properly

**Comment by drmarkwslater** [comment]
Rightio. Just to say that it could be a very particular circumstance for me thinking about it as I just re-signed my contract/EDH docs and swapped my primary experiment to LHCb. I don't know if that will have changed something in the VOMS info/VOMS auth with LHCb but it might be something to keep in mind. The only thing was that this was using a long lived proxy (it had ~600 hours left) that again, might have caused a problem.

Let me know you need anything more!
