### ISSUE TITLE
Starting ganga with `-i` option doesn't start the monitoring for Dirac

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#2273]
As in the title.

Apparently then doing `enableMonitoring()` doesn't help

**Comment by mesmith75** [comment]
Maybe we should just get rid of the option. I am not sure it adds much.

**Comment by mesmith75** [comment]
So the issue is not the `-i` - it is any option being given. I added a dummy `-a` option and that also stopped the monitoring.

I think it is somehow being picked up in a dirac command that is run by the monitoring and so breaking it

**Comment by egede** [comment]
Could it be that `sys.argv` is somehow processed twice? first by us and then also by something in the Dirac related code. Maybe try to reset it to the default single element list after we have processed it?

**Comment by mesmith75** [comment]
Indeed adding `sys.argv = sys.argv[:1]` at the end of the options parsing solves the issue - but I am not sure it is a fix.

What is really strange is that my `-o[Configuration]gangadir='/path/to/somewhere' ` doesn't cause an issue.

**Comment by egede** [comment]
I think this is OK to implement as a fix.

We declare that we have finished processing the arguments passed by clearing the list. Now why something in Dirac tries to pass the arguments as well I do not know. It points to that the way that we use Dirac makes it think that we start it as a script. If that is a bug on the Ganga or the Dirac side I do not know.
