### ISSUE TITLE
How to split job over a list of input files with Dirac

### ISSUE THREAD

**Issue by ghost** [ganga-devs/ganga#2277]
Is there a method to easily split a job over a list of input filelists (Not a list of files but a list of files which contain filepaths)?

**Motivation** 

I am trying to analyse a large quantity of data via xrootd streaming.  The paths for all these files are store in one large text file
```
root://<server>/<filename1>.root
root://<server>/<filename1>.root
....
root://<server>/<filenameN-1>.root
root://<server>/<filenameN>.root
```
To analyse this data efficiently I can split into many files `[filelist.1.txt, filelist.2.txt, ..., filelist.M.txt]` where each of the files contains some fraction of the events (say 100 files each).  I can pass this to my job as 
```
j = Job()  
...
args = [
  ["--path", File(p)] for p in list_of_files
]
j.splitter = ArgSplitter(args=args)
...
j.submit()
```

On the local batch this works exactly as I want as each filelist exists on the local file system.  When using Dirac this is not the case as `File` just copies the local file path to the worker node and not the file itself.  

**Core question**

Is there any way to tell ganga that for each Dirac job in should copy the associated file (`p` in the above snippet) to the worker node? I would much rather keep the above format of just xrootd paths.   I have tried passing both `LocalFile` and `File` as an argument which does not work and have tried using a `GenericSplitter` on the `inputfiles` and `inputdata` parameters, but this also did not work.

**Comment by egede** [comment]
I am confused about that you talk about local access to root files and `xrootd` at the same time. If you plan to read the files via streaming, then there is no need for a local copy, but you need to have the permissions to read the files over the WAN. If you have the files locally where the DIRAC job runs, there is no need for `xrootd`.

Before you start on any of this, I should remind you that copying large files through the input sandbox (which seems to be what you propose here) is really not recommended and could cause trouble both in terms of very long submission times and problems for the overall DIRAC WMS. It would be much better to have the files as `DiracFile` object stored on the grid.

That being said, I think you can get this to work by using a `GangaDatasetSplitter`. If the files are available as `LocalFile` object on the machine whre you submit from, that should be straight forward. If they are only available via `xrootd` on the machine you submit from, I think you could get this to work by carefully configuring the `MassStorageFile` object, but it would quite likely be very inefficient (as you in effect would copy the files to `/tmp` on your local machine and then upload them to a temporary Dirac storage area, and finally download them to the machine running the Dirac job).

**Comment by ghost** [comment]
Thanks for the reply, so it seems that just using the `xrootd` paths is not the correct solution.  I will try and use `GangaDatasetSplitter` again for this, I opened #2220 for this reason.    

Whilst trying `GangaDatasetSplitter` on a list of `DiracFile` with the `Dirac` backend in the `8.7.0` release I have started to get the following error (`ERROR    CredentialsError: Cannot get proxy which matches requirements DiracProxy(group='<vo>_user', encodeDefaultProxyFileName=True)`).  I have checked and I do not get this error when downgrading to `8.6.0`.

**Comment by egede** [comment]
Please open a separate issue for the `CredentialsError`. An absolute minimal example that illustrate the problem is much appreciated.

**Comment by ghost** [comment]
Thanks, I will open a separate issue for the Dirac problems
