### ISSUE TITLE
Overloading AFS

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#2286]
I got an email telling me "the heavy load on your AFS volume has slowed down an AFS server, this has affected other users" and got my access temporarily removed.

Is there a possibility this is due to Ganga now doing too much in one go? Perhaps this is an indication that we need to make the interaction with the job repository and the finalising of jobs much more efficient.

**Comment by egede** [comment]
I guess this could be the case. Would be interesting to understand what overload means (too many open file descriptors, too high i/o, ...). Can you maybe try to interact with the CERN helpdesk to get a further understanding. They might have logs that show what caused it. Tell them that you are developing the software and as such wants to understand this further to prevent others from running into the same issue.
