### ISSUE TITLE
Change name of the Singularity plugin to Apptainer

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#2293]
For the container plugins, the name of the plugin itself should be changed to `Apptainer` and the default binary used should be changed to `apptainer`. The old Singularity plugin can be kept but a deprecation warning should be issued.

**Comment by egede** [comment]
The code resides at https://github.com/ganga-devs/ganga/tree/develop/ganga/GangaCore/Lib/Virtualization and some corresponding tests in https://github.com/ganga-devs/ganga/tree/develop/ganga/GangaCore/test/Unit/Utility.

**Comment by dg1223** [comment]
I am an open source first-timer. I would like to solve this issue if it's okay.

Just by skimming over the code and the repo, I guess the following changes need to be made:

1. Create a copy of [Singularity.py](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/Lib/Virtualization/Singularity.py), change the script's name to `Apptainer.py`, the class name and corresponding dependencies
2. Add a deprecation warning to [Singularity.py](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/Lib/Virtualization/Singularity.py)
3. Add new `import` statement to [__init__.py](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/Lib/Virtualization/__init__.py)
4. Add a `checkApptainer` function to [Virtualization.py](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/Utility/Virtualization.py). It's probably going to be an exact copy of the checkSingularity function except for its name and the `"singularity"` argument in the `try` block.
5. Create a copy of [TestUtilitiesVirtualizationCheckSingularity.py](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/test/Unit/Utility/TestUtilitiesVirtualizationCheckSingularity.py), change the script's name to `TestUtilitiesVirtualizationCheckApptainer.py`, the class name and corresponding dependencies.
6. Add a deprecation warning to[TestUtilitiesVirtualizationCheckSingularity.py](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/test/Unit/Utility/TestUtilitiesVirtualizationCheckSingularity.py)
7. The default binary also get updated accordingly (to `apptainer`). I believe some scripts in `GangaCore` such as [TestContainerHandler.py](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/test/gangaDB/db_controllers/TestContainerHandler.py) need to be updated.

I might be missing a few other dependencies but those should come to the surface as soon as I start testing. Any feedback is appreciated.

**Comment by egede** [comment]
This sounds overall good. Usually I would recommend against duplicating code and instead make a parent class that both inherit from but in this case I think duplication is actually better - it will make it easier to delete the `Singularity` class in a years time or so.

**Comment by dg1223** [comment]
Thank you. I'll start working on it then.

**Comment by egede** [comment]
I do not think it is a good idea to include the use of the [deprecated](https://pypi.org/project/Deprecated/) package without the development of a uniform system for it first.

**Comment by dg1223** [comment]
Sounds good!

**Comment by dg1223** [comment]
@egede For the PR, do you want me to squash all commits into one or keep them as they are in the PR?

**Comment by egede** [comment]
We are usually not fussed about this. So you can keep them as they are.

**Comment by dg1223** [comment]
Do you want me to update the documentation too?

**Comment by dg1223** [comment]
Actually, updating the documentation can be done as a separate issue. Doesn't make sense to update it right now before the code is QA'd.

**Comment by egede** [comment]
I actually think it would be good to update the documentation in the same one. The documentation is built from the code on the `develop` branch (that is our main branch). So the documentation will then be updated at the same time as the code is updated.

**Comment by dg1223** [comment]
I am keeping the Singularity documentation as it is and adding Apptainer documentation side by side (or below) as a 1-to-1 mapping since we are still going to keep Singularity alive for some time. Does that sound good?

**Comment by dg1223** [comment]
Opened a PR #2303
