### ISSUE TITLE
Reading ganga version from .gangarc in 6.1.12

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#23]
The version stored in 6.1.11 is stored in the x,y.z format rather than the x-y-z format.

Shall we fix the 6.1.12 to be able to read x.y.z as well as x-y-z even though we're storing the format of x-y-z for forward/backward compatibility.
or,
Are we content in asking users to fix their .gangarc files by hand?

Users moving forwards/backwards are already familiar with changing/fixing this but users who just naively update to 6.1.11 and don't pay attention to what version they're on will see 6.1.12 crash on launch.

This is a minor fix from the users perspective but are we wanting to fix this ourselves or have this as a user requirement?

(We could even use this to intentionally break backwards compatibility if we chose in the future i.e. with Ganga-v7 if we ever go down this route.)

**Comment by egede** [comment]
@rob-c As a general rule, the only exceptions the user should see from the Ganga code should be of type GangaException. Not an internal error like this. So the issue is if we fix the one-off error with the 6.1.11 release. As it should be easy to put in, I vote for implementing it so it works seamlessly for the user.

Ulrik.

**Comment by rob-c** [comment]
@egede I think I agree, as it's a problem caused by Ganga I think it's something we should fix internally.
Adding an exception for someone not obeying the 'do not modify this line' would probably also be a good idea so I'll have a go at intentionally breaking some things and testing that Ganga doesn't crash on startup due to some file corruptions and such.
I'll have to work out how to commit some fixes into the pre branch and sync them back to master in that case which shouldn't take me too long. I have some one liners which have come up in the integration tests that I would like to get into 6.1.12 anyway.
