### ISSUE TITLE
Better handle the case that jobs don't exist in DIRAC

### ISSUE THREAD

**Issue by chrisburr** [ganga-devs/ganga#2304]
Prompted by https://mattermost.web.cern.ch/lhcb/pl/ay6p1ejtjb8rjxc11dz76i6z3a

You could query for job parameters to get som information about jobs for months after jobs are deleted and communicate this to users.

**Comment by mesmith75** [comment]
What kind of query?

**Comment by mesmith75** [comment]
Ah yes, I see. We can make that much better.

**Comment by mesmith75** [comment]
Actually we already do this. The problem in the mattermost is unrelated.

**Comment by chrisburr** [comment]
Ah sorry for the noise!
