### ISSUE TITLE
GaudiPython not using correct project.

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#232]
For a GaudiPython job, it ignores the project that is defined in the 6.1.14 version. In 6.1.9 it works. The following test expose the problem

```
GaudiPython(project='Moore',version='v24r0')._impl.appname=='Moore'
```
This seems related to e53dca5576040328cd80f4b557c8db1a6353d794.

**Comment by egede** [comment]
A user can as a workaround do

```
app=GaudiPython(project='Moore',version='v24r0')
app._impl.appname = app.project
```

**Comment by rob-c** [comment]
I'm not seeing any references to changes of the ```appname``` in the above commit, where is the ```appname``` being modified?

**Comment by rob-c** [comment]
This is sounding like a known bug in the Proxy which was fixed between then and now in handling the arguments being passed to the constructor.

**Comment by rob-c** [comment]
Have you tried:
```
app=GaudiPython()
app.project = 'Moore'
app.version = 'v24r0'
```

**Comment by egede** [comment]
@rob-c You are correct. The line I looked at that was deleted was indeed commented out already. So let us close when it is confirmed that this works in 6.1.16.

**Comment by mvesteri** [comment]
I can confirm that Ulrik's workaround does the trick for now with 6.1.14

**Comment by egede** [comment]
@mvesteri But please use the suggested workaround from Rob instead which is much cleaner.

**Comment by mvesteri** [comment]
OK. Agree. Thanks.
