### ISSUE TITLE
Make GaudiExec use the regular virtualization options

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#2336]
Instead of having to do something different for `GaudiExec` compared to `Executable` etc, it would be nice if the user could do the same:
```
j.virtualization=Apptainer()
j.image = '/path/to/some/image'
```

**Comment by egede** [comment]
Have you tried if it works? For running the job I think it should actually be fine already. For operations that happen at the `prepare` stage, it is tricky as `prepare` by construction only considers the application object and not the whole job object.

**Comment by mesmith75** [comment]
This turns out to be trickier than I had hoped as pointed out by @egede . Closing for now - we can re-open if someone has a brilliant idea.
