### ISSUE TITLE
Ganga crashes when banned sites set to empty list

### ISSUE THREAD

**Issue by fabudine** [ganga-devs/ganga#2352]
If the banned sites for a job `j` are set to
```
j.backend.settings['BannedSites'] = []
```
Ganga crashes because `setBannedSites` wants either a filled list or a single name as input.

**Comment by mesmith75** [comment]
Could you give more information as to what the crash says? When does it crash?

**Comment by fabudine** [comment]
It crashes after the job has been submitted to the grid. It creates input tarball etc, and then you get a DIRAC error such as 
```
^[[0;31mERROR    Job submission failed for job 3.0 : DIRAC error!^[[0;0m
```

**Comment by fabudine** [comment]
Unfortunately I overwrote the DEBUG log. But it was saying exactly what I wrote in the description. That `setBannedSites([])` caused an error because it expects either a list of strings or a single string, not an empty list.

**Comment by mesmith75** [comment]
I see, so its on job submission. Thanks

**Comment by mesmith75** [comment]
Issue is in the DIRAC API.
