### ISSUE TITLE
Job master kill error with failed subjobs

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#2358]
This needs fixing:
```python
[11:27:10]
Ganga In [12]: jobs(2317).kill()
ERROR    failed to kill job 2317: JobStatusError: forbidden status transition of job 2317 from "failed" to "killed"
ERROR    JobError: failed to kill job 2317: JobStatusError: forbidden status transition of job 2317 from "failed" to "killed"
```

**Comment by egede** [comment]
To reply with an error to killing a job in a terminal (i.e. completed, failed, killed) state seems the correct behaviour to me.

**Comment by mesmith75** [comment]
The job `2317` was in the running state. Some subjobs were completed, some failed and some were running. I would assume that doing `kill()` on the master job would kill the remaining running subjobs without complaint.

**Comment by egede** [comment]
Yes, I agree that behaviour is not ideal. In my mind, what should be changed is that the request to kill a completed/failed job should just result in "no operation" and the job just stay as completed/failed.
