### ISSUE TITLE
Unittests now need a grid certificate for non gridified tests

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#237]
When I try to run the unittests on the latest develop I'm seeing that I need to provide my password to my grid certificate if I haven't make a valid proxy.

This appears as a minor issue as I can generate a proxy and then this goes away but it means that the unitests aren't starting up and getting the LHCb environment correctly defined for them.

I have correctly run ```SetupProject ganga xxx``` and I can start ganga for LHCb correctly so this is a problems with the unittests.

This means I don't trust the test configuration if it's not correctly pulling in the LHCb environment as expected.

I'm going to start investigating with stack traces to see if I can work out how the unittests are getting into this state.

**Comment by rob-c** [comment]
This is to do with ```cmd.append('python/Ganga/Runtime')``` in ```setup.py``` and concerns me that some form of environment is being setup and possibly associated with the tests which isn't what we want.

I'm going to do some further digging to work out what this code is doing.

**Comment by alexanderrichards** [comment]
We should have a presence on Zenodo such that Ganga can be properly referenced

e.g.
https://zenodo.org/record/46721#.VyHT-LPSRhE
