### ISSUE TITLE
Interactive between DaVinci and Ganga have some problems

### ISSUE THREAD

**Issue by xuzh-glhf** [ganga-devs/ganga#2381]
Hi, there is a minimum test to recreate this problem:  https://gitlab.cern.ch/xuzh/mini_test

More details can be found in the issue that I opend in LbEnv peoject: https://gitlab.cern.ch/lhcb-core/LbEnv/-/issues/51

This problem seems also related to `DaVinci`, so I also open an issue here as a redirection: https://gitlab.cern.ch/lhcb/DaVinci/-/issues/219

This problem seems related to `DaVinci`, `Ganga` and `LbEnv`, but I am not able to fix, any help is approciated.

**Comment by mesmith75** [comment]
Not a Ganga issue - LbDevTools stopped now only copies the packages to `InstallArea` which is probably right. Needs a DaVinci adjustment.
