### ISSUE TITLE
Incorrect string split across lines  in Job.py

### ISSUE THREAD

**Issue by dhcroft** [ganga-devs/ganga#2382]
In the file ganga/ganga/GangaCore/GPIDev/Lib/Job/Job.py there is code on lines 1434 and 1435 which generate error text for preparing an already prepared Job.

```
msg = "The application associated with job %s has already been prepared. "
"To force the operation, call prepare(force=True)" % self.id
```

This gives the error 
TypeError: not all arguments converted during string formatting

There should be a \ at the end of the first line so it knows to continue the line.

**Comment by mesmith75** [comment]
Thanks!
