### ISSUE TITLE
ArgSplitter breaks ordering

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#239]
The following code in release 6.1.16

```
a = ArgSplitter()
a.args = [['Hello '+repr(i)] for i in range(20)]
for i in range(20): print a.args[i]
```
produces the output
```
['Hello 0']
['Hello 1']
['Hello 10']
['Hello 11']
['Hello 14']
['Hello 2']
['Hello 12']
['Hello 13']
['Hello 15']
['Hello 16']
['Hello 17']
['Hello 18']
['Hello 3']
['Hello 4']
['Hello 5']
['Hello 6']
['Hello 9']
['Hello 7']
['Hello 19']
['Hello 8']
```
where the numbers are not ordered. As it is supposed to behave like a list, I regards this as a bug.

**Comment by rob-c** [comment]
I can reproduce this at least. Interesting. This could be due to the recursive stripping, in the proxy. The setter in the GangaObject, or due to the fact that a GangaList is used behind the scenes.

At least we can rule out any interaction with the repository here :)

**Comment by rob-c** [comment]
OK, simple testing indicates the input is mangled by the Proxy layer before it gets to the GangaObject layer. I'll do some more digging tomorrow at some point.
