### ISSUE TITLE
GangaThreadPool shutdown having troubles.

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#24]
The GangaThreadPool 'shutdown', most likely the shutdown task for GangaThread or GangaThreadPool is throwing a named exception of 'global object logging not defined' on shutdown.

I'm currently catching this and making a debug log statement about the code.

I cannot fix or mitigate this particular exception and have tried removing all logging entries from within the GangaThread and GangaThreadPool classes to rule out that it is these classes throwing the exception. (Unless I missed something this didn't fix the problem)

The shutdown method seems to do what is expected, it has a breakable wait statement attempting to give the worker threads a chance to finish with the ability to exit on demand at shutdown.

As the shutdown method works and only throws an exception at the end of it's running I'm strongly leaning to this as a low priority bug but simply cannot work out what is causing the 'logging' object to not be defined. (This could be from within the (Worker?)Thread or from within the global ThreadPool I'm not sure.

I'm opening this task to look into it over the next few releases to see if this shines a light on some other bug which is only showing up here.

edit:
Actual line I get is:
' Cannot run one of the exit handlers: shutdown ... Cause: global name 'logger' is not defined '
The part of the string of interest is this:
"global name 'logger' is not defined"

**Comment by alexanderrichards** [comment]
@rob-c This rings a very nasty bell. When I was first writing the ThreadPool I recall something similar with the Queues module. I'll have a think and see if I can help.
