### ISSUE TITLE
Understand bootstrap process

### ISSUE THREAD

**Issue by milliams** [ganga-devs/ganga#245]
I'm starting to think about being able to use the `ganga` module to run tests (at least some of them). For this purpose we need to be sure exactly what it should be providing or doing. As far as I can tell there are 3 (or 5) main tasks that it needs to do and which we should account for in little ganga. They are (in no particular order):
1. Load all plugin objects into the GPI as well as things like `export` and `report`.
2. Start the registry and the repository so that things which expect them to be present can interact with them (e.g. creating a proxied `Job` object adds itself to the registry)
3. Start background subsystems like the queues thread pool and the monitoring loop
4. Load external packages using each package's `RuntimePackage` instance (running their `BOOT.py`, calling `loadPlugins` etc.)
5. Registering shutdown hooks

Now, number 4 is almost just a repeat of number 1 for each package so conceptually they are the same. Number 5 I feel could be handled automatically during 2 and 3 so that each subsystem automatically registers its own shutdown handlers (it's not a priority to change this though).

What I would like is that a basic `import ganga` only performs something like 2, 4, 1, 5 by default and the monitoring loop should not start automatically. A function to start and stop the monitoring loop should be provided. Perhaps the code that is run during number 5 should also be provided so that the user can shut down all runtime objects (reg, repo etc.).

What are people's thoughts on this? Am I missing any obvious requirements? How does it sound from a user's point of view?

**Comment by rob-c** [comment]
Take a look at little ganga from https://github.com/ganga-devs/ganga/pull/202 It has a working repo implementation. (of a sort)

I would still like to see a ```loadRepositories``` and ```shutdownRepositories``` function which abstracts the repo logic from both ```ganga``` and the ```bootstrap.py```

**Comment by rob-c** [comment]
I think we can afford to spend the time to look at how the config files are loaded. They _work_ in #202 but the loading of the config-files/plugins is still a bit fragile and care needs to be taken.

**Comment by rob-c** [comment]
As far as I know ```ganga``` registers the shutdown hooks correctly. The difficulty is when to run them in the unittests and to deal with the bringing up/shutting down of any Ganga services with this.

I don't think we can hope to have a ```setUp``` which looks just like ```from ganga import *``` I think we'll still need to have some logic to do things like re-generate repositories when the location changes and things like this.
It would be nice to see more of the code from ```GangaUnitTest``` put into simple helper functions.

I think from the perspective of tests we need:
 0. Load the Config (if required)
 1. Bootstrap ganga (still required for the moment from the Config system).
 2. Initialize the Registries
 3. Start any Ganga services demanded by the Config. (Monitoring, Tasks, Queues....)

At the end of each test (as in shutDownClass) we at least need to:
 1. Shutdown Ganga services currently running
 2. Shutdown the Registries (This takes care of the lockfile monitoring as well)
 3. Clear the Registry and on-disk elements we've modified.

TODO (feel free to correct me but I think these items need addressing, although probably not in order):

 1. Move delattr of Ganga.GPI Objects into shutdown methods to make sure the GPI after a shutdown is really clean. This may require care with the credentials system as it is.
 2. Separate tearDown from tearDownClass functions which can be tricky but allows us to only shutdown the registries once per test which is a bit more sane than the current system.
 3. Take common code from GangaUnitTest and bootstrap and put them into methods which are common to both and integrate these into 'ganga'.
 4. Separate loading of the config/plugins from starting of the registries and populating of the GPI objects.
 5. Possible cleanup of ```ganga/__init__.py``` after everything is working so we have a single function to load the config, then call the functions to load the GPI objects and then call the function to start the services.
