### ISSUE TITLE
Ganga is abusing /tmp too much

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#25]
Transferred from JIRA:

https://its.cern.ch/jira/browse/GANGA-1243

Basically make sure Batch, LCG and Athena classes clean up unnecessary tmp files

**Comment by drmarkwslater** [comment]
Commits are in locally. Will wait until 6.1.12 is out before pushing to github.

**Comment by milliams** [comment]
You could push your local branch and just hold off on merging it? Otherwise, just go ahead and push since the release branch has already been branched from *develop*.

**Comment by drmarkwslater** [comment]
Oh OK - I thought this was the case but I wasn't 100% and as I couldn't check with you in the office today I thought I'd hold off just in case. I'll push the commits now and close the issue :)
