### ISSUE TITLE
Problem running postprocessor for Grid job, stuck in ‘Completing’

### ISSUE THREAD

**Issue by alexpearce** [ganga-devs/ganga#254]
I have some jobs, each with a couple of hundred subjobs, each of those running DaVinci on the Dirac backend. I'm using the HEAD that was [deployed on lxplus yesterday](https://github.com/ganga-devs/ganga/pull/249#issuecomment-190850270).

Every single subjobs fails to transition from Completing to Completing, which I guess are due to error messages such as the following:

```
Ganga.GPIDev.Lib.Job               : INFO     Running postprocessor for Job 22.276
Ganga.Utility.logging              : WARNING  ---------- error in user/extension code ----------
Ganga.Utility.logging              : WARNING  Traceback (most recent call last):
Ganga.Utility.logging              : WARNING    File "/afs/cern.ch/lhcb/software/DEV/GANGA/GANGA_HEAD/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py", line
609, in updateStatus
Ganga.Utility.logging              : WARNING      newstatus = self.transition_update(newstatus)
Ganga.Utility.logging              : WARNING    File "/afs/cern.ch/lhcb/software/DEV/GANGA/GANGA_HEAD/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py", line
648, in transition_update
Ganga.Utility.logging              : WARNING      passed = self.postprocessors.execute(self, new_status)
Ganga.Utility.logging              : WARNING    File "/afs/cern.ch/lhcb/software/DEV/GANGA/GANGA_HEAD/install/ganga/python/Ganga/GPIDev/Adapters/IPostProcesso
r.py", line 111, in execute
Ganga.Utility.logging              : WARNING      process_result = p.execute(job, newstatus, **options)
Ganga.Utility.logging              : WARNING  AttributeError: 'GangaList' object has no attribute 'execute'
Ganga.Utility.logging              : WARNING  --------------------------------------------------
Ganga.GangaDirac.Lib.Backends      : WARNING  An error occured finalising job: 22.276
Ganga.GangaDirac.Lib.Backends      : WARNING  Attemting again (5 of 5) after 2.5-sec delay
Ganga.GPIDev.Lib.Job               : ERROR    JobStatusError:  (AttributeError("'GangaList' object has no attribute 'execute'",),)
Ganga.GPIDev.Lib.Job               : INFO     killing job 22.276
Ganga.GPIDev.Lib.Job               : INFO     Forcing job 22.276 to status "failed"
Ganga.GPIDev.Lib.Job               : INFO     Running postprocessor for Job 22.276
Ganga.Utility.logging              : WARNING  ---------- error in user/extension code ----------
Ganga.Utility.logging              : WARNING  Traceback (most recent call last):
Ganga.Utility.logging              : WARNING    File "/afs/cern.ch/lhcb/software/DEV/GANGA/GANGA_HEAD/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py", line
609, in updateStatus
Ganga.Utility.logging              : WARNING      newstatus = self.transition_update(newstatus)
Ganga.Utility.logging              : WARNING    File "/afs/cern.ch/lhcb/software/DEV/GANGA/GANGA_HEAD/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py", line
648, in transition_update
Ganga.Utility.logging              : WARNING      passed = self.postprocessors.execute(self, new_status)
Ganga.Utility.logging              : WARNING    File "/afs/cern.ch/lhcb/software/DEV/GANGA/GANGA_HEAD/install/ganga/python/Ganga/GPIDev/Adapters/IPostProcesso
r.py", line 111, in execute
Ganga.Utility.logging              : WARNING      process_result = p.execute(job, newstatus, **options)
Ganga.Utility.logging              : WARNING  AttributeError: 'GangaList' object has no attribute 'execute'
Ganga.Utility.logging              : WARNING  --------------------------------------------------
Ganga.Core.GangaThread.WorkerThreads: ERROR    Exception raised executing 'job_finalisation' in Thread 'Job 22.276 Finalizing':
Traceback (most recent call last):
  File "/afs/cern.ch/lhcb/software/DEV/GANGA/GANGA_HEAD/install/ganga/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py", line 114, in __worker_
thread
    result = item.command_input.function(*these_args, **item.command_input.kwargs)
  File "/afs/cern.ch/lhcb/software/DEV/GANGA/GANGA_HEAD/install/ganga/python/GangaDirac/Lib/Backends/DiracBase.py", line 666, in job_finalisation
    job.force_status('failed')
  File "/afs/cern.ch/lhcb/software/DEV/GANGA/GANGA_HEAD/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py", line 1921, in force_status
    raise x
JobStatusError: JobStatusError:  (AttributeError("'GangaList' object has no attribute 'execute'",),)

Ganga.Core.MonitoringComponent     : ERROR    Monitoring Error: local variable 'try_resubmit' referenced before assignment
```

(Note that I've omitted the 4 out of 5 times it tries to ‘attempt again’ the step that's failing. They each look identical to me.)

I take a random subjob and look at it's postprocessor, as that's mentioned in the error:

```
[07:19:59]
Ganga In [28]: j.postprocessors
Ganga Out [28]: [<GangaList at: 0x7f0327fd33d0>, ]

[07:20:01]
Ganga In [29]: j.postprocessors[0]
Ganga Out [29]: [<Ganga.Lib.Notifier.Notifier.Notifier object at 0x7f0327fd3450>]
```

Each subjob has a `Notifier` postprocessor that sends me an email if the job fails. Perhaps the issue is with that?

**Comment by alexanderrichards** [comment]
the job.postprocessors attribute I think should contain a list of postprocessor objects but for whatever reason in your setup it has a `GangaList`. The postprocessors will have an execute method whereas the `GangaList` will not hence this problem I think.
---
@rob-c I vaguely recall that some change went in regarding the postprocessors. Is it possible that this was broken by the recent changes?

**Comment by rob-c** [comment]
@alexanderrichards The postprocessors are causing some problems atm, and, frankly have always been a little bit fragile.
I think I'll take a loot at how they're initialized as I suspect that there are problems with the default not being an empty MultiPostProcessor. (I'm unsure the reasoning behind this).

**Comment by alexpearce** [comment]
Assuming that, for now, I'm happy not to have this particular postprocessr (`Notifier`), is there a way I can modify the jobs to remove it, such that they can transition to Completed?

**Comment by drmarkwslater** [comment]
Not sure how/where this has changed but looking above, `j.postprocessors` should **always** be of type `MultiPostProcessor` (at least, the _impl should) and then gets picked up by the filtering system on assignment. This was done to allow both the following to work:
```
j.postprocessors = Notifier(...)   # results in a MPP with one entry
j.postprocessors.append( Notifier(...) )
```

Looking at the stack trace, it could be that the filtering is returning a list when it used to return the actual MPP and that is probably the problem.

**Comment by rob-c** [comment]
@drmarkwslater This looks to be entirely behind the proxy though so I wouldn't expect the filter system to ever get involved. (maybe this is incorrect but this I suspect is the problem)

**Comment by alexanderrichards** [comment]
> is there a way I can modify the jobs to remove it, such that they can transition to Completed?

I assume that the simplest way would be to blank your postprocessors attribute.

```python
for j in jobs:
    j.postprocessors = []
```

**Comment by rob-c** [comment]
If we expect it to always be a MultiPostProcessor then I would argue it should always be one from the start, changing the type of the object leads to problems like this were we at least need to check for the type.

@alexpearce You may need to use:
```
for j in jobs:
  j._impl.postprocessors = []
```
to be able to modify already running jobs.

**Comment by alexanderrichards** [comment]
> This looks to be entirely behind the proxy though so I wouldn't expect the filter system to ever get involved. (maybe this is incorrect but this I suspect is the problem)

We are really dredging my memory now but I **thought** that the filters were invoked even behind the proxy layer. (Happy to be corrected :wink:)

**Comment by drmarkwslater** [comment]
@alexpearce Just to confirm, could you do:
```
type(j.postprocessors)
type(j.postprocessors._impl)
```
for one of these jobs and let us know what it returns? I suspect they will be MPP objects in which case, I think we can say it's the filters that are running behind the proxy and the changes to the proxy in #241 have changed this somehow (that's assuming it was working in 6.1.16 of course :smile:)

**Comment by rob-c** [comment]
@alexanderrichards You may be correct that they used to be but I'm not certain where. Maybe in the setter but in that case so much has changed I wouldn't rely on it any more. Certainly not in the getter.

**Comment by rob-c** [comment]
@alexpearce Can you confirm this was working on 6.1.16 or prior? Thanks

**Comment by alexpearce** [comment]
@rob-c Yes, I've heard subjobs completing with no problems on 6.1.13.

**Comment by rob-c** [comment]
@alexpearce Could you provide a script used to create the job and/or ```report(myJob)```. I'll try playing around with some examples tomorrow but knowing exactly how the job is configured could help debugging :) Thanks, Rob

**Comment by kgizdov** [comment]
I had the same issue today. Removing all postprocessors did nothing. In the end I ended up doing 

    j.postprocessors.remove(XXX())  # several times until all gone
    j.postprocessors.append(FileChecker(files=[*.root], searchStrings=['bla'], filesMustExist=False))  # to have a postprocessor that always succeeds
    exit  # quit and login again
    ganga
    j.subjobs[XX].backend.reset()  # reset all subjobs
    j.force_status('completed')  # this did not work until after I did all previous steps

Now it's finally completed. I'm still not sure why it works this way.
