### ISSUE TITLE
Suppress repetitive warning messages

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#256]
We have had a couple of times recently (monitoring heartbeat and deprecation of SandboxFile, etc.) where Ganga can spew out many copies of the same warning/info message. It would be nice for repetitive messages can be removed, possibly through the basic python logger rather than GangaLogger as we want to get rid of this?

**Comment by drmarkwslater** [comment]
A quick look at the python logger seems to indicate just creating our own filter that stops printing messages after a certain number or whatever should work well. We'd have to be careful about the implementation though to ensure we don't remove required messages.

**Comment by rob-c** [comment]
How many features in the current logging system do we want to keep/drop? I'm very keen to replace the getLogger with 20-30 lines of code at max and not have any other code (if possible)

**Comment by rmatev** [comment]
I think the suppression has to be requested explicitly. I am not sure if / how this can be done, but from a quick look
`logger.warning("something is deprecated", extra={'maxprint':10})`
might be feasible.

**Comment by alexanderrichards** [comment]
@drmarkwslater I agree, using a standard python log Filter looks like a possible solution. This in combination with what @rmatev proposes would even allow different max numbr of prints for different log messages. As I understand it the `extra` keyword arg will populate the `__dict__` of the actual logrecord object which I guess we could then filter on.

**Comment by drmarkwslater** [comment]
The question would then just be do we filter and limit **all** messages or just ones that send the appropriate `maxprint` parameter? Anyone got any thoughts either way?

**Comment by alexanderrichards** [comment]
No strong feelings either way. Using the `maxprint` give your more flexibility but you will have to remember to include it for all log calls where you want it so either way is fine by me.

**Comment by egede** [comment]
@drmarkwslater @alexanderrichards I do not like the solution with `maxprint`. I think it is better if we allow this to be controlled in the same way as we do for the logging levels. Something along the lines of

```
[Logging]
Ganga = INFO
Ganga.GPIDev = WARNING

[LogSuppression]
Ganga = 10
Ganga.GPIDev = 100
GangaLHCb = 1000000
```

**Comment by rmatev** [comment]
I am not a big fan of suppressing messages globally, rather the problem giving rise to them should be fixed. For instance, you always want to get the INFO messages from job submission, etc.

However, for deprecation warnings, it is fine and desired not to repeat it to the user hundreds of times. It sounds that what is really needed there is `logger.deprecated("something is deprecated")`

For bugs like the heartbeat warnings, the underlying issue must be fixed. While users wait for the next release, they can either bare with it, or some mechanism (via .gangarc) can be defined to filter the specific messages.

Everything else seems to me potentially dangerous.

**Comment by alexanderrichards** [comment]
@egede 
Sounds fine to me, since I don't have strong feelings either way, I'm happy as long as the desired outcome is achieved.

**Comment by graipher** [comment]
Not sure if this is the right place:
The large number of warnings also seems to sometimes break the logging stream (when more than one ganga session is running). 

```
Ganga.GangaLHCb.Lib.Files          : WARNING  !!! Please update your scripts before PhysicalFile is removed
Traceback (most recent call last):
  File "/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/lib/python2.7/logging/__init__.py", line 883, in emit
    self.flush()
  File "/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/lib/python2.7/logging/__init__.py", line 843, in flush
    self.stream.flush()
IOError: [Errno 2] No such file or directory
Logged from file PhysicalFile.py, line 64
```

This appeared in the ganga session where the warnings were NOT generated. It seems to try to print a lot of warnings, but each with a few seconds delay between single occurrences. This is blocking the whole session (and has been doing it now for a few minutes already without the possibility to interrupt it with e.g. CTRL-C)

**Comment by rob-c** [comment]
The logging stream may have problems due to the file stream needing to cycle to a new file when there's a large amount of logging hitting the terminal. Most of this is due to unrelated bugs which are being addressed elsewhere.

**Comment by mesmith75** [comment]
I think this is OK now.
