### ISSUE TITLE
Exiting ganga causes jobs to be loaded and flushed

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#257]
Jobs are being loaded and flushed as part of the exit in 6.1.16 (and develop) this is caused by some logic being broken to do with the job indexes (I suspect in updating the master index).

The logic should be that the master index is updated using knowledge of only fully loaded jobs to update the information stored in various places.

I'll take a look at this and try to get a small fix in for 6.1.17 as I don't expect the logic to be too difficult to fix.

**Comment by egede** [comment]
@rob-c Yes, this sounds like a serious issue. For somebody with 20 k jobs in the repository this could be a killer. It points to something else that we are not have tests for.

**Comment by rob-c** [comment]
Actually writing a test for this shouldn't be too difficult. It's more difficult to understand/test the logic of the XMLRepository, there's a lot of code there not well understood and has some quirks.
