### ISSUE TITLE
Submitting jobs with tasks deadlocks

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#271]
Following on work from #179 When I construct a task which will submit an LHCb job my job gets as far as 'submitting' and then hangs.

This has been from an __extremely__ __minimal__ patchset which doesn't touch anything to do with the repository or GangaObject.

The job gets to a prepare state and then when I attempt to run ```jobs(1124)``` it hangs forever.

I've not even the foggiest how to go debugging this and I don't know if this is interplay between the jobs and tasks or tasks and repos. I'll do some work to make sure I can't reproduce this in standard job tests.

Potentially this means tasks are off the table for 6.1.17.

As a side note I'm getting very concerned about the amount of dead-locks which are being hit at the moment, I'm hoping that this will go away because it's making dev work _extremely_ difficult.

**Comment by drmarkwslater** [comment]
The new changes @milliams has got in coming will hopefully reduce this but I'm not surprised that we may get deadlocks with Tasks as I doubt this was ever designed to be thread safe. I agree Tasks is probably off for 6.1.17 but as soon as that's out I'll start working through it and fixing any remaining bugs/deadlocks.

**Comment by rob-c** [comment]
If there is some improvement in lock handling in Core I'd still like to get the LHCb changes in for 6.1.17.

I've been using http://code.activestate.com/recipes/577334-how-to-debug-deadlocked-multi-threaded-programs/

which gives some quite interesting code. I'm strongly thinking of shipping it as an external and integrating this into the heartbeat code as it gives a nice overview of what the various python threads are up to.

**Comment by milliams** [comment]
I've been using an enhanced version of that code for a few weeks now and it's very useful. I can put it as a utility function or as part of GangaTest?

**Comment by rob-c** [comment]
Yes please, although maybe not for 6.1.17, It would be nice if we could turn on/off this ability for users if we add it.

**Comment by milliams** [comment]
Yes, it's something I would consider turning on always for tests but users probably shouldn't need it. Perhaps integrate it into `report` if people are seeing monitoring threads hanging?

**Comment by rob-c** [comment]
It would be very nice to have a snapshot of the current status of the threads in there as well yes. If you've got the code ready could you open an issue or PR at some point to look into adding the utility :)

**Comment by drmarkwslater** [comment]
This should be fixed by #377

**Comment by rob-c** [comment]
I think this has probably gone away, I think as long as the tasks now I think I saw some LHCbTask specific things here but this is un-tested.

**Comment by drmarkwslater** [comment]
Fixed by #377
