### ISSUE TITLE
Update main Ganga web page to remove/play down CERN stuff and add Zenodo account

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#274]
As we now aren't anywhere near as reliant on CERN stuff for Ganga, we should reflect this in our web page.

**Comment by milliams** [comment]
I agree. As we move further from relying on CERN things we should document and ensure things work. On which note, I have WIP potential replacement at http://ganga-devs.github.io

**Comment by rob-c** [comment]
Why not have this as ```index.html``` to the project in this case? having the pip install readme is a little minimal. (From what I've read github knows to display this)

**Comment by alexanderrichards** [comment]
We should have a presence on Zenodo such that Ganga can be properly referenced

e.g.
https://zenodo.org/record/46721#.VyHT-LPSRhE
