### ISSUE TITLE
Web GUI is broken - fix it or re-implement a more full GUI with PyQT, etc.?

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#275]
The Web GUI is currently broken and maybe should be fixed. However, it might be nice to take this opportunity to do a 'proper' GUI. This would be more work but be a very nice addition and these days shouldn't be anywhere near as difficult as it was 10+ years ago when it was last tried.

Thoughts anyone?

**Comment by Unode** [comment]
I'd vote for the web interface. There's quite a few advantages to it over a local running GUI.
Perhaps even going as far as integrating some of it with Jupyter.

**Comment by rob-c** [comment]
Having a common enough API to be able to use either some of the features from IPython 4 or pyQT would be nice. Having said this a web interface would allow for better perceived 'integration' with Dirac monitoring I would have thought.

**Comment by drmarkwslater** [comment]
This would be the ideal solution and what I was thinking about. As you say, if the API is general from Core point of view, the viewer could be anything (Web or Qt) and it should all work. I'll start looking at this in the near future...

**Comment by rob-c** [comment]
@drmarkwslater Out of curiosity is this a 'start again from scratch' sort of thing or more of a case of adapting whatever code is in the current web interface (which I suspect is very out of date)

**Comment by drmarkwslater** [comment]
That will probably depend on the state of the Web GUI code :) However, to do it properly, I suspect a start from scratch is needed. There's still a lot of ancient code in for the original GUI that needs to be removed :smile:

**Comment by egede** [comment]
@drmarkwslater This sounds like pretty fun work. However, I do not see it a thing to give priority at all. Getting a full integration with Jupyter would be much more valuable at the moment.

**Comment by drmarkwslater** [comment]
It would certainly not be high priority but I think that integration into Jupyter is basically done/is trivial assuming `import ganga` works, is that right?

**Comment by alexanderrichards** [comment]
yes that's right as far as the notebooks go but there is a bit of work to be done to make the terminal essentially be an interactive ganga session.

**Comment by egede** [comment]
@drmarkwslater No, not really. See #277 for further comments.
