### ISSUE TITLE
Integration to Jupyter

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#277]
We should integrate Ganga with Jupyter. This requires several things for working
- [ ] import ganga such that jobs can be accessed from within a Pythn Notebook.
- [ ] A modified `terminal` in Julyter where an interactive Ganga session with monitoring can run.
- [ ] Potentially job monitoring running in a separate server like process to allow different Python 
    Notebooks to access jobs.

**Comment by alexanderrichards** [comment]
I'm happy to look at job monitoring on a separate server process since this was my suggestion.

**Comment by egede** [comment]
@alexanderrichards Sounds great. Just open as a separate PR.
