### ISSUE TITLE
Data integrity

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#281]
Hi all,

I'm about to commit a unittest which tests Ganga's resiliency to missing 'data' XML files for a job in testing.

Are we expecting that ```data``` and ```data~``` are different such that ```data~``` is the 'n-1' iteration of the job as it's stored to disk.

Would it be worth adding a ```data.bak``` to avoid if we want to restore from a backup (for whatever reason) losing data of the 'n'th iteration of the job.

Thanks,

Rob

**Comment by drmarkwslater** [comment]
At present, data~ is the n-1 version of data. We could have a data.bak as well but this would double how long it takes to flush to disk as you will be doubling the writes. At present, you write once and then just do renames/mv's. I suppose we have to decide what the chances of this happening are given the safeties now in safe_save and is it worth doubling the flushing time.

**Comment by egede** [comment]
@rob-c In general I am quite haooy with data~ storing the n-1 version. If something goes wrong, I think in many instances you would end up with both the data and the data.bak files having trouble.

**Comment by rob-c** [comment]
OK good to know that this is the case I was wanting to be 100% sure
