### ISSUE TITLE
GangaList is potentially dangerous when saving a job multiple times

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#284]
The ```_list``` ```[]``` object in GangaList objects keeps getting expanded when pushed through the XML VStreamer.

I wouldn't have spotted this without the recent tests.

Repeatedly loading (and flushing) the same XML from disk could potentially be dangerous as this causes a GangaList to replace the contents of a GangaList sequence with a GangaList.

I'm going to do some debugging for this to preserve the nested object write ability whilst preventing this behaviour.

Rob

**Comment by rob-c** [comment]
I've put in a fix for this as part of the unittest which picked it up as it's potentially a small fix. If it's not I'll revert and make a second PR

**Comment by rob-c** [comment]
This may be fixed in #268 I'd like to construct some sort of test for this involving the box repo and XML files.

**Comment by milliams** [comment]
This shouldn't be a problem as we shouldn't have any `GangaList`s as schema attribute values?

**Comment by rob-c** [comment]
1. We should be able to support this. I would strongly prefer to move to GangaList as (it allows us to do a lot of things properly) and despite this we need to support storing them if they ever get passed to the XML layer. And they do. It's at the very least possible to put them in a box repo.
 2. This is a problem in parsing the list object in an XML into a GangaList which gives you a GangaList within a GangaList by accident.

A lot (if not all?) list objects read in from XML are parsed into GangaList to cope with things such as inheritance and etc.

**Comment by rob-c** [comment]
I suspect this has gone away with many changes since I posted this. Either way I was never able to make the worst case scenario appear that we produced an extra level of nesting by loading/writing a job multiple times.
