### ISSUE TITLE
Ganga on non-case sensitive filesystems

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#297]
Hi all,

I recently tried installing ```ganga``` on a well known OS which doesn't have case sensitivity turned on in it's filesystems by default.
(This was a quick exercise to get an estimate if we could support the platform).

As a result git and/or pip install becomes extremely confused about ```Ganga/__init__.py``` vs ```ganga/__init__.py```.

I know we're not aiming to support these environments but just before we go too far down the rabbit hole I'm curious to ask if we may want to reconsider the naming of ```ganga```?

I'm happy if we want to officially decide to not support these systems but I'm curious if there is an opinion as to whether it would be nice to run our testsuite elsewhere to help debug?

Thanks,

Rob

**Comment by drmarkwslater** [comment]
This is a good point I hadn't thought of. I would actually be in favour of renaming Ganga to GangaCore or something rather than changing little ganga as little ganga is the 'public-facing' part and so should probably be more consistent with what people expect. I agree though that this really needs to be decided before we properly advertise little ganga!

**Comment by rob-c** [comment]
I'm happy with any solution but the use of 'Ganga.' is throughout the plugins which means renaming 'Ganga' is a big task. (not objecting to this though)
I was just thinking it may be nice to run on ntfs/hfs+ systems although this isn't our primary use case yet.

**Comment by egede** [comment]
I actually support this renaming. It would be worth at the same time to 
consider if we want to make GangaCore smaller and only deal with the true 
core issues. Things like local backend, executable application etc. would 
go into a new top level package.

Ulrik

**Comment by alexanderrichards** [comment]
> Ganga to GangaCore

I've been thinking this for a while :+1:

**Comment by milliams** [comment]
Before this issue gets too derailed perhaps we should start a separate one or two for these points. However, I agree in general. What is currently `Ganga` could become a number of smaller packages. Perhaps:

1. `GangaLib` for the real fundamental bits of registries, interfaces `GangaObject` etc.
2. `GangaCore` or `GangaCommon` or `GangaBase` for things like `Executable` and `Local` which are useful for everyone and shuld be loaded by default
3. `GangaGrid` for `LCG`, `CREAM`, `ARC` etc. (not loaded by default).

Names are TBC but this was my thinking over the last year or so.

**Comment by rob-c** [comment]
Would it be sensible to have the todo for this task as:

 1. Move ```Ganga``` to ```GangaCore``` and change all of the Plugins to cope/match this. (This could be early 6.1.19 or 6.1.20.)
 2. For every additional _plugin_ we want to factor out of core ```GangaCommon/GangaBase/...``` we move these packages out into their own PR so that we can track that everything points to the correct place before we merge the code?
This to me makes sense to do in stages over a few releases.

As much as I'd like to see the core broken up I think we invite something getting overlooked if we do too much in one big PR and a lot of working branches would have conflicts when re-syncing to develop if too much goes in at once.

**Comment by milliams** [comment]
@rob-c I agree. This should definitely be broken up into a series of smaller PRs and I agree with your ordering.

**Comment by egede** [comment]
#302 and #303 created to follow up on this.
