### ISSUE TITLE
Make Ganga terminate gracefully when receiving SIGTERM (kill)

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#300]
In a very common scenario for users, I suspended my laptop with a Ganga session running in a terminal window. The session was dead when I opened the laptop again. I was surprised to see that the Ganga process was in fact still running. Running strace on the process, seems to indiocate that Ganga is in fact still healthy.

```
[pid 22805] <... open resumed> )        = 14
[pid 22805] getdents(14, /* 13 entries */, 32768) = 1000
[pid 22805] getdents(14, /* 0 entries */, 32768) = 0
[pid 22805] close(14)                   = 0
[pid 22805] open("/home/egede/gangadir/repository/egede/LocalXML/6.0/sessions", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 14
[pid 22805] getdents(14, /* 13 entries */, 32768) = 1000
[pid 22805] getdents(14, /* 0 entries */, 32768) = 0
[pid 22805] close(14)                   = 0
[pid 22807] open("/home/egede/gangadir/repository/egede/LocalXML/6.0/templates", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 14
[pid 22807] getdents(14, /* 4 entries */, 32768) = 104
[pid 22807] getdents(14, /* 0 entries */, 32768) = 0
[pid 22807] close(14)                   = 0
[pid 22807] open("/home/egede/gangadir/repository/egede/LocalXML/6.0/templates.metadata", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 14
[pid 22807] getdents(14, /* 5 entries */, 32768) = 128
[pid 22807] getdents(14, /* 0 entries */, 32768) = 0
[pid 22807] close(14)                   = 0
```

Is this actually the intention? Also do we try to do something sensible if the Ganga process receives a kill signal (rather than kill -9)? Would it be possible to make Ganga shutdown nicely in this case  without producing any stdout/stderr which would cause the process to die as no terminal is attached. At the moment, a kill of the process gives the strace below.

```
[pid 22805] <... rt_sigaction resumed> NULL, 8) = 0
[pid 22805] rt_sigaction(SIGQUIT, {SIG_DFL, [], SA_RESTORER, 0x30160326a0}, NULL, 8) = 0
[pid 22805] rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
[pid 22805] stat("/home/egede/gangadir/repository/egede/LocalXML/6.0/sessions/localhost.09.30_Friday_11_March_2016.PID.22782.session.box.metadata.locks", {st_mode=S_IFREG|0775, st_size=29, ...}) = 0
[pid 22805] stat("/home/egede/gangadir/repository/egede/LocalXML/6.0/sessions/localhost.09.30_Friday_11_March_2016.PID.22782.session.box.locks", {st_mode=S_IFREG|0775, st_size=29, ...}) = 0
[pid 22805] rt_sigaction(SIGINT, {SIG_IGN, [], SA_RESTORER, 0x30160326a0}, {0x7f9b5b0837e0, [], SA_RESTORER, 0x30160326a0}, 8) = 0
[pid 22805] rt_sigaction(SIGQUIT, {SIG_IGN, [], SA_RESTORER, 0x30160326a0}, {SIG_DFL, [], SA_RESTORER, 0x30160326a0}, 8) = 0
[pid 22805] rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
[pid 22805] clone(child_stack=0, flags=CLONE_PARENT_SETTID|SIGCHLD, parent_tidptr=0x7f9b41ff9e78) = 3557
[pid 22782] <... select resumed> )      = ? ERESTARTNOHAND (To be restarted)
[pid 22782] --- SIGTERM (Terminated) @ 0 (0) ---
Process 22782 detached
[pid 22822] +++ killed by SIGTERM +++
[pid 22821] +++ killed by SIGTERM +++
[pid 22820] +++ killed by SIGTERM +++
[pid 22819] +++ killed by SIGTERM +++
[pid 22818] +++ killed by SIGTERM +++
[pid 22814] +++ killed by SIGTERM +++
[pid 22808] +++ killed by SIGTERM +++
[pid 22807] +++ killed by SIGTERM +++
[pid 22805] +++ killed by SIGTERM +++
[pid 22802] +++ killed by SIGTERM +++
[pid 22801] +++ killed by SIGTERM +++
[pid 22800] +++ killed by SIGTERM +++
[pid 22799] +++ killed by SIGTERM +++
[pid 22798] +++ killed by SIGTERM +++
[pid 22797] +++ killed by SIGTERM +++
[pid 22796] +++ killed by SIGTERM +++
[pid 22816] +++ killed by SIGTERM +++
[egede@localhost ~]$ 
```

**Comment by rob-c** [comment]
I suspect we should do something similar to the solution of http://stackoverflow.com/questions/18499497/how-to-process-sigterm-signal-gracefully to register our shutdown handler with the kill signals other than kill -9.
It should be trivial to modify the logger such that the terminal logger is disabled as the first action in the case of SIGTERM I think.

As for ganga still being alive after a suspend. I would expect this as long as you're running only one instance of ganga locally.
If you observed ganga still running over an ssh connection then I know it's possible for this to happen but it relies on the ssh connection not being broken by the laptop sleep/suspend I think.

Running multiple sessions here would more than likely result in collisions as file locks would appear stale if some time has passed.

I've some thoughts on how to handle multiple sessions in a slightly better way but this would require some invasive changes in the SessionLock to communicate between ganga sessions using on-disk resources to determine if the other ganga session is actually alive or dead. Checking the session file modified time is the simplest way to do this but it has drawbacks.

**Comment by egede** [comment]
Something should also be done to the question 

```
Do you really want to exit ([y]/n)? 
```

which at the moment is not going through the logger.

**Comment by rob-c** [comment]
Yes, but in this case we can switch the shutdown policy to be the same as on batch/headless systems. aka don't ask and turn the screen logger off so that stdout/stderr aren't addressed. I think that should cover everything. (probably slightly easier said than done with the logger)

**Comment by egede** [comment]
@rob-c To switch to the headless system indeed sounds like a good idea. This might actually make disconnected processes in general shut down in a much nicer way, Changed to an "enhancement".
