### ISSUE TITLE
The full_print(j) function is broken

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#301]
The simple test 

```
j=Job()
full_print(j)
```
prints out a reference to the job  object rather than the full listing.

```
[12:32:10]
Ganga In [9]: full_print(j)
<Ganga.GPIDev.Lib.Job.Job.Job object at 0x1c52b90> 
[12:32:13]

```

**Comment by rob-c** [comment]
I have been looking at code relating to this recently. I'm assuming that this should be printing the full job repr which should include full list expansion?
Either way this has been broken for a _long_ time now and should probably be fixed.

**Comment by egede** [comment]
> I have been looking at code relating to this recently. I'm assuming that
> this should be printing the full job repr which should include full list
> expansion?

That is correct.

> Either way this has been broken for a /long/ time now and should
> probably be fixed.

Yes, indeed; and today was the day that I got around to report it.

**Comment by rob-c** [comment]
OK. I think this may tie in with a bug I'm seeing in nested GangaList expansion for repr so I'll take a look at both of these.
It's likely that the full_print can be fixed quite easily by moving it to the new repr functions in the Proxy but I think it would be better to see if the old representation code is still working as I don't know where or how that is used.
