### ISSUE TITLE
Local wrapper script exiting with code 9

### ISSUE THREAD

**Issue by milliams** [ganga-devs/ganga#309]
We've seen a few sporadic failures of test [Savannah19123](https://github.com/ganga-devs/ganga/blob/2939a9d04bac16cf9f6a25b90dbc3feb8cfc4d9f/python/Ganga/new_tests/GPI/Bugs/TestSavannah19123.py). The symptom is that the test is checking whether certain file exist or don't exist at the right times and at the end of the test it calls `j.kill()` which errors since the job is in the `failed` state (which it should not be). We couldn't work out why the job was failing so Mark added some debug to it. The debug hasn't helped directly but it's now occurred twice in a row on the Nightly tests.

You can see the output at [ganga-ci](https://ganga-ci.cern.ch/jenkins/job/Nightly/208/consoleText) but the important part is the logging output which has:

```
Ganga.Lib.Localhost : CRITICAL wrapper script for job 0 exit with code 9
Ganga.Lib.Localhost : CRITICAL report this as a bug at https://github.com/ganga-devs/ganga/issues/
```

so it seems that `__jobscript__` is failing in some way and is returning a `9` (whatever that means). I've seen this test fail on my local computer before so I don't think it's directly related to the canga-ci machine.

**Comment by egede** [comment]
Can you get the test to dump the __jobscript__ to stdout/stderr. Or can 
you modify the test to include a "set -x" flag in the bash script and 
then look at the stdout of the job.

**Comment by rob-c** [comment]
I think I've seen problems similar to this when the job has finished and cleaned up after running but the Localhost doesn't take this scenario into account and fails to open the (now missing) file.

**Comment by rob-c** [comment]
@milliams I don't think we see this anymore, are we ok to close this?
