### ISSUE TITLE
Have protection (or offer support) for 'odd' characters in Job name (e.g. '<..>')

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#314]
There is very little (if any) protection for what you can set a Job name to in Ganga. We should either disallow the known broken things (XML tags for example) or improve the code to support them.

**Comment by egede** [comment]
@drmarkwslater I think the problem arise because we set the name in Dirac to the name of the job in Ganga. So we should just sanitise the names before we put it into the JDL.

**Comment by rob-c** [comment]
Where does this actually break things, Ganga or in one of the backends which may dislike strange job/filenames.

Can we just introduce some string sanity check into all strings at the ```__set__``` level which would reduce problems such as this a _lot_ more.

**Comment by egede** [comment]
@rob-c  This is just for DIRAC.

**Comment by rob-c** [comment]
@egede Didn't we have problems in the past with strange characters in filenames though? (again in Dirac but I suspect this is not unique)

**Comment by egede** [comment]
@rob-c Yes, I think for Dirac, we should just take any non [a-zA-Z] character out and replace it with an underscore (which is valid).

**Comment by drmarkwslater** [comment]
You're right - this isn't a Core problem but is backend dependent. However, it certainly isn't just for Dirac as I know that I've had to fix this for ARC at least before now. I feel that all backend submit code should be checked to make sure it's sanitising things properly.

**Comment by rob-c** [comment]
In this case we (at least) need the pre-submit checks for the IGangaFile to be coded up to be generic as was discussed in a face-to-face meeting a while ago.
If we're keeping the pre-submit file checking maybe it's worth having a job consistency check which asks the backend and other attributes to perform sanity checks in the same place.

**Comment by egede** [comment]
I believe this has more or less been done.
