### ISSUE TITLE
Monitoring Error: cannot import name queues

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#315]
The report from Mike Sokoloff, had an error in the shuitdown as well, that I think we missed in previous discussions. See printout below.  The error is coming from python/Ganga/Core/MonitoringComponent/Local_GangaMC_Service.py

```
Ganga.GangaLHCb.Lib.Files          : WARNING  !!! Please update your scripts before LogicalFile is removed
Ganga.Core.MonitoringComponent     : INFO     Some tasks are still running on Monitoring Loop
Ganga.Core.MonitoringComponent     : INFO     Please wait for them to finish to avoid data corruption
Ganga.Core.InternalServices        : INFO     Stopping Job processing before shutting down Repositories
Job status update or output download still in progress (shutdown not completed after 6 seconds).
1 background thread(s) still running: ['MonitoringWorker_1_1457975480358'].
Do you want to force the exit (y/[n])? Ganga.GPIDev.Adapters              : ERROR    Monitoring Error: cannot import name queues
Ganga.Core.MonitoringComponent     : ERROR    Monitoring Error: cannot import name queues
Ganga.Core.MonitoringComponent     : ERROR    Monitoring Error: cannot import name queues
```

**Comment by rob-c** [comment]
@egede Can you find out the likely job type to lead this? (or is the user running tasks)

I suspect it could be a backend/tasks problem of trying to load the queues system after it's already been shutdown. I'll move the queues shutdown into the shutdown handler manually I think to try and avoid this in the future.

**Comment by egede** [comment]
@rob-c I have not seen this myself (the user is using tasks though).

**Comment by rob-c** [comment]
I suspect this is due to some worker thread being shutdown out of the order that is expected so I can protect against this with a few minor changes.

**Comment by rob-c** [comment]
Given the queues system has moved around quite a few releases ago I think this is safe to close as nobody seems to be complaining that the queues are causing problems.
And we not try to access the queues directly rather than via the GPI so I suspect the original error applies to code we've taken out.
