### ISSUE TITLE
Ganga 6.1.17 hard-lockups

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#317]
I'm creating this issue to cover any developer related queries here about LHCb users still seeing ganga lockup during normal use (a few minutes after ganga has started).

From what I've seen of people forcing an exit through ```Ctrl+C``` this looks like the formatting part of the RegistrySlice has issues. This ties in with the my experiences that touching the ```getNodeIndexCache``` seems to cause lockups due to something in the Core not behaving as expected.

This could also be unrelated to a hard-lockup elsewhere which locks an object in such a way that getting any attribute from it is no longer possible.
I wonder if we may want to relax the ```__get__``` lock by introducing some logic to differentiate between what is currently being get and set within the GangaObject? Locking the whole object just to change it's name seems a little heavy-handed to me.

Also should the get lock walk all the way up but not reach the parent as there is no way to request the parent from within the get method so it makes no sense to lock it this way?

**Comment by egede** [comment]
@rob-c The users who have seen these issues have many jobs that have finished. Thus the monitoring threads will be busy and I guess this is the cause of the lockups. Do we have tests that are emulating this behaviour?

**Comment by rob-c** [comment]
Not presently (I've got a Dirac test waiting to go in when we have a box which can submit there).

I suspect users for LHCb are seeing problems due to multiple attempts to load the same subjob at once. (Just a hunch) which we've recently fixed in a PR so I wonder if this merits pushing out a 6.1.18 soon or not.

**Comment by rob-c** [comment]
I've spoken to Carlos who's shown interest in using the latest code from github so hopefully by the end of today he might be able to report back with any success or not

**Comment by egede** [comment]
[http://fpmac116.usc.es/cvazquez/stacktracer.html](url)

**Comment by rob-c** [comment]
@egede We test this a bit on the local backend actually in a large parallel submit test and there is a second version of this running subjobs which is up for review for being run on ganga-ci.
What we're lacking is a potential test of the LHCb backend if we suspect this could be at fault.

The given stack trace I think hints at a known bug with SubJobXMLList having an incorrect parent set on an object during load. This is effectively a bug due to double loading from more than one thread which is being addressed in a PR.

**Comment by rob-c** [comment]
I claim this will likely go away with #307 once this has been merged given the lockps experienced on this were the same as is being seen here.

**Comment by rob-c** [comment]
In fact running on this PR with several split jobs which are in a running/completing state and I'm not yet seeing a lockup. I'm keeping this session open for an hour or 2 to see if I can reproduce this on lxplus.

**Comment by rob-c** [comment]
hmmm, whilst I'm not seeing python lockup I am seeing a serious performance problem with running ```job``` running it whilst there is a lot of activity is taking > 5min despite the fact that ganga is still spawning and controlling new tasks and appears to be doing work (CPU ~ 60-70% at times)

**Comment by drmarkwslater** [comment]
After wrapping my head around the deadlocks again, I think that #307 does indeed fix the problems. I've got a couple of test tweaks to do but after that, we can merge and maybe point Carlos and Elena at the HEAD version?

**Comment by rob-c** [comment]
I'm seeing deadlocks on this branch unfortunately.
I set ganga running and left the office to go do some marking. I'll work out how to upload the trace now

**Comment by drmarkwslater** [comment]
Sod. Oh well - if we get the trace, hopefully we can see where the next problem is :(

**Comment by rob-c** [comment]
OK, I'm about to start looking at this myself
[final.trace.html.txt](https://github.com/ganga-devs/ganga/files/174147/final.trace.html.txt)

**Comment by rob-c** [comment]
Hmm I'm seeing 2 threads try to lock the parent to assign themselves as children at the same time...
I'm starting to lean very heavily on the fact we require a lock to hang a child off a parent being a bad thing.
If we were advertising the child to the parent I could almost understand this. But we're not.

**Comment by drmarkwslater** [comment]
Err.. I don't think you were running on the correct branch :smile: as in the trace you have:
```
File: "/afs/cern.ch/user/r/rcurrie/cmtuser/GANGA/GANGA_Dev/install/ganga/python/Ganga/Core/GangaRepository/SubJobXMLList.py", line 374, in _getItem
  self._cachedJobs[index]._setParent( self._definedParent )
```

and line 374 isn't doing this on the branch. It's actually blank!

**Comment by rob-c** [comment]
Well that's potentially a minor relief, I'll set it running again on the branch properly and not make a mess of checking out the code as I obviously did last time

**Comment by rob-c** [comment]
Maybe having a nightly test where we run:
```
while True:
        import time
        time.sleep(5)
        print("%s" % jobs)
```
(or some variation)
for 5 minutes to see if we get any lockups would be worth doing to try and catch this in the future.

**Comment by rob-c** [comment]
OK I can confirm ganga at least runs for much longer before locking up now

**Comment by milliams** [comment]
Is that "you've ran for a longer time with no lockup yet" or "it look longer before you saw the lockup"?

**Comment by rob-c** [comment]
I waited a long time and no lockup :D I'd say I only waited 15min but I think if it's not happened by then it won't
