### ISSUE TITLE
String interpolation warning in the AutoFlusher

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#320]
I'm seeing too much of this:

```
[16:56:49]
Ganga In [1]: Traceback (most recent call last):
  File "/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file Registry.py, line 217
<LogRecord: Ganga.Core.GangaRepository, 10, /afs/cern.ch/user/r/rcurrie/cmtuser/GANGA/GANGA_Dev/install/ganga/python/Ganga/Core/GangaRepository/Registry.py, 217, "Auto-flushing">
None
```
All I was doing was running ```ganga --no-mon --debug```

I'll prepare a PR to fix this.

**Comment by rob-c** [comment]
Also is there a strong reason for the auto-flusher non-blocking?

If a system is under heavy load we run the risk that this never flushes for us (or waits a very long time).

I'm tempted to play with this being a blocking lock to see how the performance is effected.

**Comment by milliams** [comment]
It was made non-blocking so that it would stay out of the way most of the time. We thought that if the system is under heavy load then the flusher can wait for a while (as it's really an 'auto-save'). I'm not sure how often we have a completely saturated registry lock such that it wouldn't get a chance to run. I seem to remember that I made it non-blocking to improve performance and reduce lockups but feel free to investigate.

**Comment by rob-c** [comment]
I'm much more of the opinion that the users can afford to wait for ganga to pause in order to flush data to disk.
I know it 'should' then probably run next time around I'm just very much more of the opinion this should _force_ a flush to disk before something else gets in the way.

I'll see if it causes lockups but I suspect it shouldn't

**Comment by milliams** [comment]
If it doesn't cause lock-ups (and we're reasonably sure) then I'm happy to make it blocking in principle.

**Comment by drmarkwslater** [comment]
I'm a bit wary of this as, not that it's a bad idea per se, but from a user point of view, they'll quite often see Ganga basically stall until the flusher finishes sometimes and this could make them think there's a lockup, certainly if they have a large job (lots of subjobs) that is being actively monitored and made dirty quite often.

There was an idea to give the auto flusher N tries (say 5) at non-blocking and if it can't get a lock after that, then make it blocking. Would that be a possible halfway house?

**Comment by milliams** [comment]
I feel a better compromise than that would be to instead of:
```
lock the registry
    flush all dirty jobs
```
instead
```
djs = get all dirty jobs
for each djs as dj
    lock the registry
        flush dj
```
This way the registry can be interrupted between each job if there's other threads waiting.

**Comment by rob-c** [comment]
I'll add a function to run over and collect all of the dirty objects in this case. Although my feeling is that this lock could just be handled within flush_all if it's done correctly but I'm sure that invites problems.

**Comment by milliams** [comment]
I'm not sure another method is needed. Perhaps just iterating over all objects and calling flush on each would suffice. In fact, that becomes equivalent to removing the `@synchronised` lock from `flush_all()` and not acquiring a manual lock inside the autoflusher (simpler code all round) so maybe that's the best approach?
