### ISSUE TITLE
The release scripts don't cope well with git conflicts 

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#33]
This is a placeholder for me to remember to break out the release scripts to be more resilient to git conflicts throughout the release process.

Currently the tools fall over due to a variety of different errors in the final release step and it's not as simple as just re-running the step due to different kinds of human intervention being required.

**Comment by milliams** [comment]
I guess the main problem comes from the merge of the release branch back into develop. It shouldn't usually be a problem since the release branch should be short-lived and should not contain many changes. Trivial bug fixes at most. However, it's clear that sometimes conflicts will appear and we need to account for these.

Firstly we need to make sure that if there are Git conflicts which prevent the merge then we bail out of the release appropriately and don't send any "Ganga is released!" emails (this should happen anyway since the email is the last thing to go out).

The main problem is finding a way to deal with the merge conflicts in an as automatic way as possible or at least give the release manager enough information that there is a conflict.

**Comment by rob-c** [comment]
The problem is the script initializes the release folder first which requires manual intervention to fix.
I have seen conflicts raised when merging back to develop and then in running the flow commands at the end.
In addition to sub scripts failing due to things like 'nothing' to commit to git.
I think breaking out what is actually involved in the release step is going to be required so we may want to think about what's actually going on an whether we expect all of the current steps to be needed/valid.

**Comment by rob-c** [comment]
Just adding a thought here that it would be nice to be able to run the testing scripts off git without making a pre.
I'll do some work into making sure the lhcb-prepare script can pull the latest git but we should probably bring more functionality into the testing scripts for the Core and Atlas to be able to pull a git branch from within these scripts as well as getting the code from a release branch.
This would allow us at the very least to do things like run the tests on a cvmfs based system/install rather an afs one.
I know this ties in strongly with setting up Ganga with the externals but if our release scripts can start from a new empty environment then we know we're encountering any problems users would.

**Comment by rob-c** [comment]
I've some thoughts about this, but I'm going to drop this back to 6.1.15 as with 6.1.14 I'll be trying to minimise the turnaround time of the release by doing some private testing first

**Comment by rob-c** [comment]
Adding that we need some way of abandoning the release half way through and deleting/re-creating branches.

I'm seriously beginning to think a twiki page with the instructions of what is involved with git flow would be easier to use than the 'fully automated' scripts which have problems with doing anything they weren't designed for.

I'll have a look at the scripts, I think it's already fairly modular so breaking down the release script into 8-10 separate commands from bash would be much more flexible than having the current setup imo.

**Comment by milliams** [comment]
The whole current release script process is going to be replaced with Jenkins anyway very soon (the next release if possible, we can discuss as soon as 6.1.14 is out) which does a number of things in different ways. The problem is less about git-flow and more about the way I had to retrofit the old release scripts to fit the interim Git layout.

**Comment by rob-c** [comment]
sooner the better, but I imagine we're still going to be running the test suite as it currently is somewhere? I know we're moving to get the tests to be based on something better ala GangaUnitTest or better but is the current test framework and summary web-pages possible with Jenkins? (We will also need to fix #81 before we use Jenkins properly)

**Comment by milliams** [comment]
The release and testing will be all done on Jenkins but with the addition (in the short term) of two scripts in the `gangage` account: `bin/test-from-github` and `bin/install-from-github` which respectively run the tests based on a github branch and install to AFS based on a github tag. These will be manual steps but as time goes on, their need will reduce.

I'd be happy to try to make the 6.1.15 release using Jenkins. There will likely be problems and missing stuff but as you say, the sooner the better.

**Comment by rob-c** [comment]
I'll have a look at these scripts as I want to try and run the current tests on the develop branch at least once a week (Wednesday evenings ahead of the group meeting is my feeling).
This will also require some tweaking of the LHCb test code to run with develop rather than a numbered branch but this should be a minor issue.

A lot of the problems from 6.1.14 are due to the fallout from changes earlier in the release cycle not being picked up sooner.

I have visions of 6.1.15 being a hotfix for someone so I would prefer to hold off for a week or 2 and see if any community of Ganga users hits a major problem.
If there are no major issues with 6.1.14 I'm happy for 6.1.15 to focus on moving to Jenkins but if we need to fix something critical I'd prefer to wait until 6.1.16.

**Comment by rob-c** [comment]
I'm closing this now as we've moved to Jenkins for releases and such
