### ISSUE TITLE
Storing sequences in Ganga

### ISSUE THREAD

**Issue by milliams** [ganga-devs/ganga#330]
I've been thinking about the overall requirements for storing sequences of `GangaObject`s and I've mostly narrowed it down to the following few requirements:
1. In the GPI, proxy-wrap objects as they are extracted from lists and strip proxies as they are added.
2. If the sequence is a schema attribute value:
   - set parent correctly when objects are added to a list and when a list itself is re-parented.
   - check `_readonly` (for locking submitted jobs).
   - set the dirty flag correctly.

If a sequence is not set as a value of a schema attribute then it has no parent, no need to track dirty and no need to track if it's read-only and thus special treatment is not needed (`list` is sufficient).

Currently `GangaList` is designed to provide these features but I feel it has some design flaws which make it a little tricky to use. The main problem I see with it is that it was designed as a `GangaObject` so that it could make use of the automatic proxy-generation but in the process a lot of code has needed to be added across the project to account for this. For example, it makes it difficult to work out the module dependency tree since `GangaObject` relies on `GangaList` (in getters and setters) but `GangaList` _is a_ `GangaObject`.

_As an aside before I continue, I've come to appreciate the distinction between `Node` and `GangaObject`. The former is for managing the hierarchy of parents (and serialisation) while the latter is for auto-proxying and schema-having._

My plan is a simpler replacement for `GangaList` which breaks it into two distinct parts:
- `List` is a subclass of `list` and `Node` which records the parent of all its elements and allows any new elements added to be parented correctly (point 2 above). It does not have a `_schema`. It should be used as an implementation detail of sequence schema attributes.
- `ProxyList` is a GPI-layer wrapper of this which does the proxy-wrapping of its elements (point 1 above).

I have an implementation of the above written which is about 100 lines of code. I believe that is is already in a state to be able to replace `GangaList` and would allow a lot of other code across the project to be simplified. For example it would make a lot of sense to set `SubJobXMLList` to be a subclass of `List`.

This should cover all the use cases discussed in #184 except I have not yet written any of the code to deal specifically with copying `GangaObject`s or assigning via the schema.

Thoughts?

**Comment by rob-c** [comment]
I know we probably need a ```ProxyList``` object but at some strong level I'm not sure how much is needed for this class to do.
Surely this is only a special instance of the proxy class which has ```stripProxy```/```addProxy``` to the getter and setter methods unique to lists?


I have some strong reservations about making changes to ```SubJobXMLList``` in this way unless you know it to be safe.
First off this class should __never__ be directly exposed to the user and I see no need for it to return proxied objects or accept them. It historically did/does to cope with bugs elsewhere which need squashing (hence why it is NOT in the GPI).
The user should __always__ get a ```RegistrySlice(Proxy)``` and not care whether the ```RegistrySlice``` contains a ```Registry```, list of objects, ```SubJobXMLList``` or some new iterable class type containing ```GangaObject``` things.
(Yes there are bad hacks/tests for the ```SubJobXMLList``` in ```RegistrySlice``` at the moment but these are to get around bottlenecks and areas where the equivalent code breaks lazy loading very badly).

I know we can reduce the amount of code in a list class by doing it properly but I wonder can't we just add object inspection and the relevant proxy stripping/adding code into the standard proxy class?
This would mean something of the order of 20-30 lines of code in the Proxy.
(This point is debatable, but I'd much rather not see us introduce more classes, and more files to solve the problem but if the overwhelming consensus is that this is needed then so be it)

I am glad we're sticking with something which will allow for parents in nested lists to still work as this was potentially quite powerful from the perspective of designing apps and not having to care about the limitations of the serialization code.

Forgive the naivety but isn't ```List``` just going to be ```GangaList``` everywhere and wouldn't it make sense to adopt this save changing every occurrence of ```GangaList``` in the source? (How will ```List``` deal with being serialized?)

**Comment by milliams** [comment]
We already kind of have both `List` and `ProxyList` but they're mixed together in `GangaList.py`. This would split them so that `List` is in `Objects.py` and `ProxyList` is in `Proxy.py`.

As you say, `ProxyList` is very small and is simply applying the proxy wrapping to the methods it exposes. My implementation uses a metaclass to wrap these methods so that `ProxyClass` is simply (subject to change):
```python
class ProxyList(GPIProxyObject, collections.MutableSequence):
    """This is an object which lives in the proxy layer to provide proxy wrapping to all its elements"""
    __metaclass__ = ProxyListMetaClass

    @ProxyListMetaClass.proxy_wrap
    def __init__(self, _list=None):
        if _list is None:
            _list = []

        # Set up the standard proxy interface
        self._impl = List(copy.deepcopy(_list))
        self._impl._proxyObject = self

exportToGPI('ProxyList', ProxyList, 'Classes')
```

Likewise, `List` is very simple and is just (likewise subject to change):
```python
class List(list, Node):
    """This is as close to a Python list as possible. The only thing it adds is the correct management of parents."""
    _parent = None

    def _setParent(self, parent):
        self._parent = parent
        for element in self:
            if isinstance(element, Node):
                element._setParent(parent)
        self._dirty = False

    def __setitem__(self, index, value):
        if isinstance(value, Node):
            value._setParent(self._parent)
        return super(List, self).__setitem__(index, value)  # Call the base method

    def insert(self, index, value):
        if isinstance(value, Node):
            value._setParent(self._parent)
        return super(List, self).insert(index, value)  # Call the base method
```

`SubJobXMLList` was mentioned as a potential future, not as an immediate change. As I said, it would be based on `List`, not on `ProxyList` so it wouldn't have any proxy code in at all. It would however perhaps make the parent tracking much easier.

As for the naming of `List` vs. `GangaList`: if we made any of the changes I mentioned above I would very likely rename my `List` to `GangaList` to reduce the renamings needed (although having different names would allow both to exist for a while).

`List` will be serialisable by it overriding `accept`. It will map exactly to the `<sequence>` in XML (none of this code is written yet).

In spirit you can see my proposed changes as little more than simply splitting out `GangaList.py` into two classes so that their individual purposes are more clearly defined. This will simplify the code and reduce the bugs that we have been seeing creeping in recently with parenting etc.

**Comment by rob-c** [comment]
OK, I'm quite happy with a lot of this.

If your ```List``` is essentially the serializeable simplified un-proxied version of ```GangaList``` I'm all for this :D (re-reading that sentence it's clear something is wrong with ```GangaList``` by the fact I have to say this)

Can we have a separate PR to sort out all calls to ```makeGangaList```, ```makeGangaListByRef``` and ```myGangaList._list``` calls.
(The first 2 I'd like to reduce/check their use and the 3rd I'd like to remove).

If you're going to code up ```List``` and ```ProxyList``` (I'd __really__ like to see this in 6.1.19) can we have it so that the constructor accepts non-keywords and just makes a list from iterable objects. I miss not being able to do ```myGangaList = GangaList(myOldList)```.

**Comment by milliams** [comment]
Yes, your summary of `List` is correct.

I believe @drmarkwslater has been looking at `GangaList`'s various constructor functions with an aim to do more-or-less what you say. His investigations will still be very useful if we switch to `List`/`ProxyList` as we need to have a good handle on the semantics of this all.

On your last point, this should be already possible but we're going to need to make sure we have *very* good test coverage (and documentation) of these classes before merging, If you have use-cases like these I'd be very interested in hearing about them so post them somewhere (here or on a [gist](https://gist.github.com/)) and I will add them to the test suite.
