### ISSUE TITLE
Ganga develop identifies as previous version

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#331]
Hi all,

I'm in communication with a few users who are keen to checkout the latest and greatest code and a continual question I get is, that once they checkout the latest develop, Ganga identifies as the previous version on startup.

If we've dropped the `Ganga-SVN` version name I'd like to increment the version number right at the start of each release in future.
In this case it's clearer (imo) that you're on the branch that will become 6.1.19 rather than that you're working on 6.1.18 with changes.

What are people's thoughts on this?

Thanks,

Rob

**Comment by milliams** [comment]
I can understand the reasoning for this. Perhaps a solution would be to, after a release is finalised, set the version number to, e.g. `6.1.19.dev` so that it aligns with [PEP-440](https://www.python.org/dev/peps/pep-0440/#implicit-development-release-number). Upon release the `.dev` suffix is removed, release is made (as `6.1.19`) and then the string is set to `6.1.20.dev`

**Comment by rob-c** [comment]
I'm weary of adding ```.dev``` but I suspect that we can/should fix any ganga internal problems if that is the case. Either way I'm not a fan of what we have atm.

**Comment by egede** [comment]
@milliams The `.dev` notation might break multiple parts of `bootstrap.py` from just skimming it.

**Comment by alexanderrichards** [comment]
In general this sounds like a reasonable idea, just a quick point to bear in mind.

> I'd like to increment the version number right at the start of each release in future

**NOTE** If we abort the release and re-merge into develop then start a release again, doing this at the start will over increment the version number if the incrementing is done automatically. This problem disappears of course if the version string is taken from the build parameter/branch name.

**Comment by rob-c** [comment]
@alexanderrichards I wad more intending that the last thing in the release process is to bump the version number in develop after releasing the stable version. This way that never happens. I think perhaps we're mixing the release dev cycle and the release process itself here.
aka. ```develop``` always has the version of Ganga which is unreleased.
