### ISSUE TITLE
Input Output on shared storage

### ISSUE THREAD

**Issue by unode** [ganga-devs/ganga#332]
Hi guys,

Apologies if this question should be asked elsewhere but I tried the mailing list and got the message back undelivered https://github.com/ganga-devs/ganga/issues/222#issuecomment-199442925 .

I'm currently looking at ganga's Input/Output model but I'm getting a little confused with how LocalFile works and I don't get how SandboxFile is meant to be used.

The cluster where I'm using ganga has shares using NFS and a BeeGFS cluster for high speed access as well as /scratch.

Assuming this:
a) NFS (data location - variable between jobs)
b) BeeGFS (computing location - lets assume /scratch)

I would like to setup jobs for the following scenarios:

I) Job copies data from a) to b), performs computation, job finishes and moves results from b) to a)
II) Job reads data from a), computes using /scratch for temporary files, job writes final output to a) or moves from b)
III) Job reads data from a), computes (without using /scratch), job writes final output to a).

The ones I'll use more often are I) and II).
Can I actually setup ganga to perform these actions automatically or do I need to take care of the moving/copying/linking files by some other way?

**Comment by egede** [comment]
@Unode asking here is fine.

The `SandboxFile` object is deprecated, so do not consider that one.

Some batch systems will setup a working directory for you, while others will not. Let me assume that your system does that on `/scratch` and that the working directory of the job is there. (If this doesn't happen, it is easy to make Ganga do this for you, just ask). 

### For scenario I:
Something like
```
j.inputfiles=[LocalFile(namePattern='input1.data', localDir='/data')]
j.outputfiles=[LocalFile(namePattern='output1.data', localDir='/data/results')]
```
In this case, before your executable starts, `/data/input1.data` will be copied to the working directory in `/scratch`. At the end of the job, the file 'output1.data' will get copied to `/data/results/output1.data`

### For scenario II:
simply define your input in the `j.inputdata` instead. In this case, nothing will be copied. Instead there will be a `magic` file in the working directory named '__GangaInputData.txt__' that has the content 

```
file:///data/input1.data
```
with one file per line. It is then for your job to read this file to understand which data should be processed.

### For scenario III:
At the moment, we do not really support this.

**Comment by Unode** [comment]
Thanks Ulrik,

Given the attribute name is "Pattern" does that mean I can use wildcard (`inputfiles*`) for multiple files?
What about if the pattern matches a folder, does it copy the entire structure (preserving symlinks and whatnot)?

**Comment by egede** [comment]
The pattern is matching for output that the job is producing. However, I do 
not think it matches on input. Does anybody else know. It doesn't match 
directories.

Ulrik

**Comment by alexanderrichards** [comment]
Hi, it certainly matches wildcards on outputfiles. We always intended for it to also match wildcard on input files but this was more difficult (especially with DiracFile as we need to do a wildcard DIRAC query which didn't properly exist in the API). I'm not sure if we got as far as making at least the other file types work with wildcard input. It would be easy at least to try with a simple LocalFile hello world type job.
