### ISSUE TITLE
Missing 'PBS' entries in 'backendPostprocess' plus some better documentation needed

### ISSUE THREAD

**Issue by JacekHoleczek** [ganga-devs/ganga#34]
When a new ganga creates a new ".gangarc", I can find four instances of 'backendPostprocess' ("DiracFile", "GoogleFile", "LCGSEFile", "MassStorageFile") with appropriate entries for different backends, but 'PBS' entries are missing (I assume they will always be equal to the existing 'LSF' entries).
Could you, please, modify the procedure that creates ".gangarc" so that it adds these 'PBS' related entries, too.

**Comment by egede** [comment]
Hi Jacek,

As these are just dictionary entries, it should indeed not matter that there are entries which are not relevant for a given site.

Ulrik.

**Comment by JacekHoleczek** [comment]
I'm sorry, I was not clear enough.
I do understand that if I do NOT use 'PBS' then I do NOT need its entry.
However, for everyone who DOES use 'PBS' it would be easier if its entry existed in advance (so that one does not need to create it oneself each time a new ".gangarc" is created). Moreover, for a newcomer it may be difficult to know how to set it up or that it is needed at all (it did take me some time to "discover" why my files were not copied to my "MassStorageFile" even though the 'path' was correctly set ...).

**Comment by egede** [comment]
You were clear, but my reply was unclear ;-) I agree that we should add the entries.

**Comment by JacekHoleczek** [comment]
I'd like to "extend" this "issue" a bit.
Could you also, please, add some more comments in the ".gangarc" templates (they would be really useful for newcomers, especially outside of Altas and LHCb).
For example, the "MassStorageFile" example contains now a "defaultProtocol" field with a ROOT related example, but it is nowhere shown how to use it, for example, with a simple local disk (or another possible methods).
Well, you probably know another places which currently show only Atlas/LHCb specific examples.

**Comment by milliams** [comment]
I can add the defaults for the `backendPostprocess` elements but your second question requires more thought. I've added an issue at #39 to discuss this more generally.
