### ISSUE TITLE
Possible Schema bug/shortcoming exposed by lsst hacking

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#340]
Hi all,

I think I've discovered a bug or at least a shortcoming of the Schema system as it stands.

I would like to create an application with a fully qualified IGangaFile object in the schema.
This works however when I create an instance of this application interactively I see that the schema attribute is populated with an empty IGangaFile of the correct type.

e.g I define in my class

```
...
class myClass(...)
   _schema = Schema(... { someAttr : GangaFileItem(defvalue=DiracFile(lfn='myDefaultValue'))})
...
```

however I see:

```
Ganga In [1]: myClass()
Ganga In [2]: myClass.someAttr.lfn
''
Ganga In [3]:
```

I would like to have e.g. a DiracFile pointing to a default location which can be user configurable, however this is something I'm curious to know if people agree with my expectations that the Schema be able to deliver this?

Thanks,

Rob

**Comment by milliams** [comment]
It seems that the schema system is not set up to handle complex `GangaObject`s as default values. One good reason for this is that the default value needs to be savable into the `[defaults_myClass]` section of the config file and there is no easy way to do this with `GangaObject`s.

In general I think that setting default values for `ComponentItem`s is unsupported and the docs back this up by saying for `defvalue` "for component this must be either None or a string with a name of the component in the same category". The fact that it even half-works is an accident.

**Comment by rob-c** [comment]
Well in this case I'm bugged that either we don't support this myself. I can think of solutions but they're all uglier than storing the data where it should sensibly be.
I'm avoiding hacking on this right now in favor of testing something out with a new object and the playing with some settings in the Dirac API.

I would have strongly preferred this threw an error on initialization rather than silently parsing and taking it until me interactively checking this to find it doesn't work.
As for defining the defaults of ComponentItems and how they're handled (or not). I'm not exactly happy with how much of a pain this section of code is to a) understand or b) expand/modify/fix (chose your poison).
I would like to see the config system looked at after ```ganga``` is working but I suspect that there may be hacks for even that to work 'out of the box'.


I strongly suspect we _should_ have a string which is parsed within the GPI here as part of parsing the configs from the config file so you could do the equivalent to the above still and have support for setting a ComponentItem with sane defaults.
I know this isn't a trivial fix but am I insane for thinking we should probably support this?

**Comment by milliams** [comment]
In this particular case (and probably most like it) the most elegant solution would be to create a subclass of `DiracFile` called `LSSTFile` or something and set the default value of `lfn` there. Without knowing the reason for wanting a specific default value, it's difficult to say though.

In general though, I agree that if this is not supported then it should raise an error. I have an 'ok' understanding of the config/schema system so I can try to look towards simplifying and documenting it.

I agree that something approximately like what you suggest should be possible but we need to be very careful to make sure that the use-case really does make sense and be clever about how we expose it.

**Comment by rob-c** [comment]
This is an application which would have several DiracFiles which are configurable but with sane defaults. Hence adding them in source and testing for the lfn being empty just seems bad imo.
```DiracFile``` is fine for the use case however :D

OK, I'm glad that there isn't some over-arching reason why I'm expecting to be able to do these things with the schema (even though it's not supported) I'm just a bit sore about the fact I had to go back and modify code after having written it :P
(At least a warning about complex objects being un-supported would be nice to check that nobody else has-made/will-make this mistake)

**Comment by egede** [comment]
This is exposing a bit wider problem with the default values of different `GangaObjects`. What makes sense as the default for a `DiracFile` object when used in inputfiles might indeed not make sense when used as the default value in an application object  or as an outputfile. We tried at some point to address this issue by introducing the template repository and maybe we should revisit the use of that, It is a read-only repository of whole jobs that can be defined inside a package like `GangaLSST` that provides examples of jobs, Alex implemented this about two years ago for LHCb, but we never got around to use it.

**Comment by rob-c** [comment]
@egede Would it be possible to have an 'examples' (or some other name) template-style repo which is populated by locked job objects which have been fully-configured (or mostly configured) for basic tasks for users?
I like keeping the templates repo but don't like the idea a user could edit a template we chose to give them and then forget when they go use the template in future for something else.

**Comment by egede** [comment]
@rob-c The behaviour you describe is exactly how it works. Ask @alexanderrichards for the details.

**Comment by rob-c** [comment]
@egede I mean having an example or _sticky_ templates which can't be removed or have registry manipulations performed on them. If we add stuff into the templates repo users may delete them by accident which I think we may want to avoid, but this is quickly turning into an off topic discussion I think.

**Comment by alexanderrichards** [comment]
indeed what your describing is the named template system that I implemented some 2 years ago. Note this is not the same as the regular templates in Ganga which are mutable. As I recall you need to merely create a sub directory called templates within your extension package e.g. LHCb and then you will get a new repo of templates which can be accessed for in the LHCb case as:
```python
lhcbtemplates
```

something like this. I'll have a check and get back to you.
