### ISSUE TITLE
Tasks integration test

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#349]
Hi all,

I'm just adding a small issue to ask if we can make a small set of integration tests to check the expected behavior of the tasks system as part of 6.1.19.

I keep getting confused with the tasks as it's not something I've a lot of experience with and I somehow feel a simple test which constructs a simple task which fires off a simple job and finishes would be useful to demonstrate the expected behavior.

Nothing too complex but maybe a simple task with a simple transform would also be extremely helpful for reference/education.

Thanks,

Rob

**Comment by drmarkwslater** [comment]
I've got a test in PR #219 and I plan to extend it as well. This should certainly get put in for 6.1.19.
