### ISSUE TITLE
IPython crash on exit

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#35]
On exiting the 6.1.3 release, I yesterday had a crash from IPython. No obvious side effect from this apart from nasty warnings. If I see it again, I will post the traceback.

As change of IPytuon version is upcoming, it may be that this problem can just be ignored.

**Comment by rob-c** [comment]
Hi Ulrik,

I put in the handler for this, it's a strange bug which we're now exposed to after modernising our code. 

It's related to the user typing some invalid commands into IPython and the garbage collection falling over.

Needless to say as in 6.1.14 we've dropped this ancient IPython version with only one minor bug I don't really want to debug if this is our fault or a problem with running such an old version of IPython in an environment which is mostly python 2.6

Rob

**Comment by rob-c** [comment]
@egede Actually I hope you meant 6.1.13 and not 6.1.3

**Comment by egede** [comment]
Sure.
