### ISSUE TITLE
jobs.select is broken again

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#350]
I expect the following: ```jobs.select(id=1322)``` to return the job with id 1322, however when I run this command I get my whole repo returned as a jobs slice.

However: ```jobs.select(1322, 1322)``` works as expected and returns the one job.

The jobs.select method is used __heavily__ within the monitoring system and should not be doing this.
(I suspect fixing this would also fix #286.)

This just totaled my entire repo of custom jobs which are not all loadable at runtime due to a combination of this and #164.

Can we fix this for 6.1.19 please.

**Comment by alexanderrichards** [comment]
I think that we had a conversation about this previously as I recall I think we wanted to have the behaviour that select only took keyword args which would agree with what you want here right? This will probably mean that select will need to be changed to conform to this.
