### ISSUE TITLE
Ignore comment lines in txt file of --inPfnListFile option of ganga athena 

### ISSUE THREAD

**Issue by will-cern** [ganga-devs/ganga#354]
Hi,

Could you please make --inPfnListFile ignore all lines beginning with "#" in the txt file it is given, so that comments can be put in the submission text file.

Thanks
Will

**Comment by drmarkwslater** [comment]
Thanks Will - I'll get on that :smile:

**Comment by drmarkwslater** [comment]
Addressed by #460
