### ISSUE TITLE
How to specify list of input files to condor job?

### ISSUE THREAD

**Issue by will-cern** [ganga-devs/ganga#358]
Hi again,

I was able to get my ganga condor jobs launched, but they've come back failed. I don't think it's making it as far as even executing the jobs. I've attached the stdout and stderr. The submission command was:

ganga athena --condor --nocompile --split=60  \
      --inPfnListFile="test.txt"  \
      --outputlocation="/usatlas/groups/bnl_local/wcjb/condor_output/ZdZd13TeV.20160406.test"  \
      --outputtype 'ATLAS' exampleJobOptions.py

[stderr.txt](https://github.com/ganga-devs/ganga/files/206910/stderr.txt)
[stdout.txt](https://github.com/ganga-devs/ganga/files/206911/stdout.txt)

To be clear, the list of files in test.txt are all 'locally accessible'. I just need this file list splitting and passing to the individual subjobs as the input to the athena job (the EventSelector.InputCollections property).

Can you help me figure out what has gone wrong?

Thanks
Will

**Comment by will-cern** [comment]
Hi again,

I just tried a test job where I used --localtype=Local and specified a --locallocation for a few test files, and these jobs executed successfully on the batch system.

So based on this, here are my suggestions

1. Make --inputtype default to 'Local' for the condor backend, as this is surely the most common form of input for a local batch system
2. Allow --inPfnListFile to be used with the Local inputtype, to specify the list of files rather than relying on --locallocation
3. While we're at it, could you default --outputtype to 'ATLAS' for the athena job type, it seems odd to have to specify this property too

Let me know when you think this can be done

Cheers
Will

**Comment by drmarkwslater** [comment]
Should be fixed by #391 😄
