### ISSUE TITLE
Match Arch requirement in CondorRequirement to submitting job

### ISSUE THREAD

**Issue by will-cern** [ganga-devs/ganga#359]
Hi,

The Arch requirement of CondorRequirements defaults to INTEL. This is quite dated by now. 
Could logic be added to CondorRequirements such that it defaults to some 'unspecified' state and if it stays 'unspecified' then it is not added to the list of requirements in the condor job description file. Our sys admin tells me that there shouldn't be any need to specify Arch.

Additionally, at least when submitting an Athena application job, it would be good if the command-line submission tool (ganga athena) would make use of the cmtconfig to match the Arch in the CondorRequirements to the one detected for the submitting job. Perhaps it does this if the --nocompile option is specified, because then the architecture really will have to match exactly!

Thanks
Will

**Comment by drmarkwslater** [comment]
This should be fixed by #391 and #387
