### ISSUE TITLE
ARC submission broken in 6.1.17

### ISSUE THREAD

**Issue by jepperandersen** [ganga-devs/ganga#361]
When submitting jobs with a script that worked previously, 6.1.19 fails with the following message:
Ganga.GPIDev.Lib.Job               : WARNING  ---------- error in user/extension code ----------
Ganga.GPIDev.Lib.Job               : WARNING  Traceback (most recent call last):
Ganga.GPIDev.Lib.Job               : WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.1.17/python/Ganga/GPIDev/Lib/Job/Job.py", line 1614, in submit
Ganga.GPIDev.Lib.Job               : WARNING      r = stripProxy(self.backend).master_submit( rjobs, jobsubconfig, jobmasterconfig)
Ganga.GPIDev.Lib.Job               : WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.1.17/python/Ganga/Lib/LCG/ARC.py", line 1057, in master_submit
Ganga.GPIDev.Lib.Job               : WARNING      rjobs, subjobconfigs, masterjobconfig)
Ganga.GPIDev.Lib.Job               : WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.1.17/python/Ganga/Lib/LCG/ARC.py", line 935, in master_bulk_submit
Ganga.GPIDev.Lib.Job               : WARNING      rjobs, subjobconfigs, masterjobconfig)
Ganga.GPIDev.Lib.Job               : WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.1.17/python/Ganga/Lib/LCG/ARC.py", line 218, in __mt_job_prepare__
Ganga.GPIDev.Lib.Job               : WARNING      master_input_idx = self.__check_and_prestage_inputfile__(f)
Ganga.GPIDev.Lib.Job               : WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.1.17/python/Ganga/Lib/LCG/ARC.py", line 156, in __check_and_prestage_inputfile__
Ganga.GPIDev.Lib.Job               : WARNING      self.__setup_sandboxcache__(job)
Ganga.GPIDev.Lib.Job               : WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.1.17/python/Ganga/Lib/LCG/ARC.py", line 96, in __setup_sandboxcache__
Ganga.GPIDev.Lib.Job               : WARNING      self.sandboxcache.vo = config['VirtualOrganisation']
Ganga.GPIDev.Lib.Job               : WARNING  NameError: global name 'config' is not defined
Ganga.GPIDev.Lib.Job               : WARNING  --------------------------------------------------

**Comment by drmarkwslater** [comment]
Being addressed by #403
