### ISSUE TITLE
logger is not buffering correctly

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#364]
The logger isn't buffering until carriage return.

This is annoying as there are logging statements made every 30sec by default on the debug console which get displayed every time I press a character rather than waiting for a carriage return.

This gets annoying as I'm having to turn off more and more features in order to be able to test things with full debugging on.

**Comment by egede** [comment]
@rob-c Is it correct that it is not buffering at all, or is it just that the buffer fills up and then emits the messages whether or not CR is pressed?

**Comment by rob-c** [comment]
Upon further inspection I think the messages aren't being buffered at all, I suspect that this is due to way we're deciding what to buffer.

I've a 1 line PR incoming which works for me as these messages are annoying.

**Comment by milliams** [comment]
The buffering seems to be working fine for me. At least for standard job submission messages etc. Could it be to do with the version of IPython used? I'm using 1.2.1 it seems.

**Comment by rob-c** [comment]
No this is nothing to do with IPython, this is because we are doing horrible things with the buffereing as is and only catching logging from threads matching a certain naming scheme which is horrible.
