### ISSUE TITLE
Don't rename ~/.gangarc

### ISSUE THREAD

**Issue by Unode** [ganga-devs/ganga#371]
In certain situations, including when ganga is updated, the `~/.gangarc` is automatically updated with a newer version. The old file is renamed to avoid collision and preserve the contents.

In my situation the `~/.gangarc` file is a symlink pointing to a shared location. This allows me to have the same settings across multiple machines. However when the update cycle kicks in, I have to manually fix the symlink and verify any relevant content changes. More often than not, content didn't actually change.

Would it be possible to migrate the content instead of renaming the file (i.e. `cat ~/.gangarc > ~/.gangarc.old` ; `update ~/.gangarc`) or at least provide some kind of confirmation prompt before action?

**Comment by egede** [comment]
@Unode We want to make sure that the `.gangarc` file is clean in terms of not containing syntax errors and deprecated options. This is the reason that we rewrite, rather than updating the file. However, we can check if the old file is a link and then remake the link for the new file, using `os.path.islink(src)` and `os.readlink(src)`.

**Comment by Unode** [comment]
@egede I totally agree with the automatic fixing of syntax and updating options. My point was just on  preserving the file and only modify the contents.
Wouldn't regenerating the link afterwards render the backup useless? Both would point to the same file no?

My suggestion was to simply `open('.gangarc.old', 'w').write(open('.gangarc').read())` (pardon the crude example with little control over filehandles) and then update the content of `.gangarc` by just `open('.gangarc', 'w').write(updated_content)`.
So `.gangarc.old` could or could not be a symlink but it would work on both cases.

**Comment by Unode** [comment]
@egede Another possibility that just crossed my mind. Instead of having `~/.gangarc` store files under `~/.ganga/` or something like `${XDG_DATA_HOME}/ganga/`.

This way I can make `~/.ganga` a symlink or change `XDG_DATA_HOME` and ganga can still perform the renaming as normal. As long as files are kept in the subfolder both my intention and the original (by design) are maintained.

**Comment by egede** [comment]
@Unode I am afraid I do not quite understand what you want to do and if that actually would require any changes to how Ganga works. From running `ganga --help`, I get

```
  --config=FILE         read user configuration from FILE, overrides the
                        GANGA_CONFIG_FILE environment variable. Default:
                        ~/.gangarc
```

Can that solve your use-case?

**Comment by Unode** [comment]
Erm, yeah. This will work fine.
Sorry for all the noise.
