### ISSUE TITLE
IPython on AFS

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#388]
Using Ganga with IPython pointing to the home directory for the history causes the following error when you have multiple sessions:

`The history saving thread hit an unexpected error (DatabaseError('database disk image is malformed',)).History will not be written to the database.`

This isn't the end of the world but I imagine some users could become irate over this. Maybe we could consider putting the live-history in a temp space and copying it over as part of the Ganga shutdown process (potentially allowing us to merge histories if sessions have overlapped in a nice way. i.e. 1 session writes to the history completely after another).

**Comment by rob-c** [comment]
Addendum, as a result the next session is greeted with another error:
```ERROR! History file wasn't a valid SQLite database. It was moved to /afs/cern.ch/user/r/rcurrie/.ipython-ganga/profile_default/history-corrupt.sqlite and a new file created.```

Which is more painful than I first realised.

**Comment by egede** [comment]
afs will disappear before we get this fixed.
