### ISSUE TITLE
Add a file type which writes to a shared filesystem

### ISSUE THREAD

**Issue by milliams** [ganga-devs/ganga#39]
It's common when running jobs on a local batch system to write the output files of the jobs manually to some shared file-system which is also accessible from the desktop machine of the user. We don't currently have a file type which supports this automatically. `LocalFile` will copy it over the sandbox so that is not what we want.

The closest we have is using a `MassStorageFile` with setting the `defaultProtocol` to `''`, the `uploadOptions.path` to the shared file-system and `uploadOptions.cp_cmd` etc. to `cp` etc.

Perhaps it would be worth making a new file type (e.g. `SharedFile`) which derives from `MassStorageFile` which sets these defaults to something sensible?

**Comment by alexanderrichards** [comment]
This seems reasonable to me

**Comment by egede** [comment]
In the past we said that this was just a special case of 
MassStorageFile. However, I agree that this is probably not clear and an 
explicit specialisation could be a good idea.

The exact configuration will depend a bit on if a local batch backend 
has access to this shared directory or not.

Ulrik.

**Comment by milliams** [comment]
Ok, I'll go ahead with this. Does anyone have an opinion on the name? `SharedFile` makes sense to me but is there a better option?

**Comment by rob-c** [comment]
Would it be more sensible to have this as the default for MassStorageFile and move the current 'defaults' to the LHCb and Atlas config files?

I think this is looking like a case of documenting what options people can/should use rather than adding more file objects. (just my gut reaction)

**Comment by JacekHoleczek** [comment]
I agree with rob-c. No need for an additional option. Just several well described examples in the default .gangarc (don't remove anything, leave the "more complex" examples inside, just add the "simple ones", too -> they will anyhow be "commented out").

**Comment by egede** [comment]
This is a good idea. Just on Monday we discussed how we would like to 
make the "default" in Ganga more generic and then specialise it for LHCb 
and ATLAS (rather than the other way around).

My suggestion after discussing with Rob is

- Create a new SharedFile type
- Create the MassStorageFille but in a dummy configuration that
   is not working (i.e. make it explicit that it needs a site
   specific implmentation
- Configure MassStorageFile in LHCb.ini and ATLAS.ini for using EOS.
   Preferably this should be based on "are you at CERN" instead but
   I am not sure how to do that in a safe way.

Ulrik.

**Comment by rob-c** [comment]
I've fixed some long standing issues with the `MassStorageFile` object and have a working local configuration in #735 for the testing of the `MassStorageFile` class.
I'm tempted to simply make a `SharedFile` object which is a `MassStorageFile` object which makes use of the local commands as in the integration test.
Unless anyone objects to this I'll make a PR to close this issue.

**Comment by milliams** [comment]
This is now solved right? Could it be version tagged and closed appropriately?

**Comment by rob-c** [comment]
Hmm, #744 was tagged as fixing this so github looks to have changed its syntax

**Comment by milliams** [comment]
I believe you need to have the tag on a commit rather than the PR message. It's been a while since I've used it though.

**Comment by milliams** [comment]
Also, can this be tagged with the appropriate milestone?
