### ISSUE TITLE
Splitting condor jobs by dataset in a single ganga job

### ISSUE THREAD

**Issue by will-cern** [ganga-devs/ganga#390]
Hi again,

I have a feature request that has come to me further down the analysis foodchain. I want to start a discussion here about how best to solve it. I'll start with outline:

We need a way to submit a job to run on a collection of datasets, and have the outputs preserve dataset boundaries so that no output file contains information from more than one dataset. 

When using the grid as a batch submission system, our submitter script (pathena) lets us create a task specifying as input a list of datasets in a text file (--inDsTxt="myfile.txt"), and with a couple of other options we can ensure that no job in the task will run over multiple datasets, and also we can ask for a part of the dataset name to be put into the output file name. So when running on dataset: mc15_13TeV.123456.something.something   we can ensure the '123456' appears in the name of the outputfile we produce, so it's easy to sort out which files came from which datasets.

Users are asking for something similar from condor batch submissions done with ganga. I am open to suggestions of how this would be achieved. We need a way to specify a list of datasets, where each dataset is itself a list of files (potential for wildcard use would be desirable here, for those of us who have organized our datasets into directories already). We'd like to do this submission as one ganga job (it is easier to bookkeep a single ganga job than multiple ones). The defined subjobs would need to preserve separation between the dataset files, and also provide a way to rename the created output file to contain (a part of) the dataset name. 

I appreciate this is definitely a feature request that could take some time. But I think it's something that needs to be developed for the way people have invested in their analysis setup downstream of the batch processing (I am not one of them, but sadly the rest of the collaboration appears to be).

Let me know if I can do anything to help
Thanks
Will

**Comment by egede** [comment]
@will-cern I think the best would be to demonstrate what this should do using the `GenericSplitter` in `Ganga`. That does not require anything from the `Ganga` developers. If it then is clear what it should do, it would be fairly easy to implement in a specific splitter.

**Comment by will-cern** [comment]
Hmmm. I guess it would be something like:

datasets = {"my.123.dataset":["file1.root","file2.root"], "my.456.dataset": ["file3.root","file4.root"]}
#some code to figure out given a split=N, how to slice up the input files but ensuring file1.root or file2.root isn't combined with either file3.root or file4.root such that you might end up with (for N=3):
fileGroups = [ ["file1.root"] , ["file2.root"], ["file3.root","file4.root"] ]
outputNames = [ "my.123.dataset.1.root" , "my.123.dataset.2.root" , "my.456.dataset.3.root" ]

g = GenericSplitter()
g.multi_attrs = { 'inputdata.names': fileGroups , 'outputdata.outputdata', outputNames }

I will thank you for pointing out the GenericSplitter though, because I *think* it might mean I can come up with a ganga submission script that will create the job that I want. I shall have a play

**Comment by drmarkwslater** [comment]
@will-cern So I think there are two possible ways of doing this:

1. Make a new splitter that does exactly what you want and creates the subjobs of a single master job based the names/folders of the given local input. This will do what you want but be a bit inflexible as regards specifying input data, merging output, etc.

2. Submit a Task that creates a master job per input name/folder. This will mean more than one job but they would collected under a single Task which is (almost) as good and Ganga would handle everything about this as well - you'd just ask if a specific Task is complete rather than a specific Job. The benefit of this is that there's less dev work do to and the your have a lot more options with regards the output (as I say, merging, collating, etc.).

I can do both but the question would be what you'd want the default for the cmd line to be. Also, would there be anything else related to this kind of splitting/submission that would be helpful?

**Comment by will-cern** [comment]
I am happy if this works by submitting one task with many jobs in it. I have to admit I've not really worked with tasks before though. I have some concerns about performance, because I'd want to ensure all the jobs in the task dont end up needing to repeat the 'preparation' work for an athena application (making inputsandbox tarball, extracting config from joboptions etc).

**Comment by drmarkwslater** [comment]
There should be no repeated stuff at all. Actually, what's probably best is if I give it a go and you can check if it's what's needed or not. We can always tweak/rewrite later :smile:

**Comment by will-cern** [comment]
ok thanks. So the new default behaviour for the command line will be that it creates one task containing one job that contains many subjobs. And you will provide a way to specify a collection of files (I'm ok if each collection of files is a separate txt file) and tell ganga to do a separate job for each collection. In fact, that might be a good default way to do it:

--inPfnFile = "fileList1.txt,fileList2.txt,fileList3.txt"

will create a task with 3 jobs, each job handling the files from each txt file. The output filenames of each job will contain the text 'fileList1', 'fileList2', 'fileList3', respectively, perhaps.

What do you think of that way of doing it?

**Comment by drmarkwslater** [comment]
That was pretty much exactly what I had in mind :) Though I was going to keep the default behaviour as it is but if you supplied a comma separated list of PFN files then it would create the Task with multiple jobs. That's up to you though :)

**Comment by will-cern** [comment]
sounds like we're on the same page. Let me know when you have something.

Cheers
Will

**Comment by will-cern** [comment]
Hi.
Any news on this one? 
I'm going to be running a software tutorial in a couple of weeks time, and one of the things I have to show is how to run on the local batch system, so it would be great to be able to demo this stuff in that tutorial. 
Cheers
Will

**Comment by drmarkwslater** [comment]
Rightio - I'll bump it up my priority list! I doubt it'll be in for 6.1.19 but we can do a quick turnaround on 6.1.20 if needed.

**Comment by will-cern** [comment]
Hi Mark. Just checking what the progress on this one is? My tutorial is only a little over a week away now, and I'd need time to check it works. Cheers. Will

**Comment by drmarkwslater** [comment]
@will-cern Working on this as we speak 😄

**Comment by drmarkwslater** [comment]
Addressed with #460
