### ISSUE TITLE
Debugging user jobs and making more use of JobTime object

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#4]
Hi all,

I'm considering adding a (maybe hidden) attribute to the job-time object to record what version of Ganga was used for each change of state of a job.

I have a hunch that moving between Ganga 6.0 and Ganga 6.1 is causing data loss which could otherwise not be happening and ruling this out is taking much longer than just reading the logging data auto-recorded for a job.

Does anyone have any suggestions on whether they think this is a good idea or not?

Thanks,

Rob

**Comment by alexanderrichards** [comment]
As long as we handle old jobs without this attribute gracefully, I don't see a problem with this suggestion. As for whether it's a good idea or not, It's probably best to raise this in the weekly meeting so that we can have a proper discussion about it.

**Comment by egede** [comment]
I am not convinced that this is a good idea. You are effectively suggesting to add debug statements into the persisted repository for all users.

**Comment by rob-c** [comment]
I'm not convinced that this is necessarily debug info.
We already record the transitions and the times of various transitions. (Which I've noticed we _don't_ keep for subjob resubmission and I should open a bug on that)
I think keeping the ganga version used to modify the job would be useful information. For instance I would say it would be useful to know if a job could have been exposed to a given bug when an operation was performed.
I would strictly say that this information should never be used within the ganga code
But this should already be the case for everything else in the job history as it is unless I've misunderstood the reason for this feature?

**Comment by egede** [comment]
My feeling is that the information is there for the user so they can see how long CPU time the job consumed etc. As a side comment we actually discussed *reducing* the amount of information recorded here, at least for the DIRAC backend. At the moment the monitoring loop spends a significant amount of its time requesting this information which is in effect never used.

To record developer aimed debugging information in each users repository seems to me like the wrong direction to take.

**Comment by rob-c** [comment]
After talking a look at this no more or less information is stored here for the Dirac backend. It's mainly that we used to poll Dirac for every single Dirac job we had all at once which would slow down the monitoring loop by getting lots information which is simply disregarded or that causes latencies. This latency seems to have been significantly reduced in the latest Ganga code.

The internal Dirac job states aren't accessible or recorded inside ganga we simply record the time that we progress the job between submitted, running, completing etc...

I'm not going to push for this particularly strongly as it was just a nicety I would have liked to have. i feel it would have given a more complete history of each job recorded as it's processed.

I think I'll close the request if this isn't what the jobtime object is intended for.
