### ISSUE TITLE
Ganga DIRAC integration/communications

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#401]
OK, @po10 met with some of the LHCbDirac developers today at CERN and there have been a few questions asked which I'd like to get people's opinions on with regard to communication between Ganga and Dirac.
### DIRAC and Ganga in the same Python environment?

As far as I know Ganga and DIRAC run in different Python environments due to the 2 projects having incompatible environments in the past.
Would we still like to continue down this route or is there any feeling that we can have Ganga work within the same environment as DIRAC?
(We have reduced the number of non pip-installable externals and we've recently improved our support for different IPython versions etc so would it be possible to test/use a version of Python/IPython which ships with a DIRAC install?)

If we chose to keep Ganga and DIRAC environments separate it may be nice to move back to a server/client model which would allow us to change the `evaluate` method to simply be something like `evaluateOnServer` which reduces the impact of the change on our current code to the 1 function as everywhere else would still work the same.
Does anyone have any good suggestions on how this may be implemented in a good way? @alexanderrichards  I know you mentioned you've looked into this a little and have some ideas.
### Should we group commonly grouped DIRAC calls into a single command which we execute within a DIRAC namespace?

It may be beneficial to simply rewrite some more complex functions such that we have a single `finalizeDIRACJob` method and equivalent for submitting subjobs to the DIRAC backend which we call once.
(there are technical reasons why submitting jobs this way may be tricky but the finalization of a DIRAC hello world job can probably be improved on compared to what we're doing now)

These methods would return a larger dictionary back to user within Ganga but runs a bit more of the risk of timeouts.
#### Option a) move back to a server/client model:

A server/client model sounds like a very nice long term solution but has a lot of potential complexity involved I suspect.
#### Option b) group DIRAC commands which can all be reasonably sent at the same time.

Grouping DIRAC calls from within Ganga to reduce the amount of overhead is potentially a nice solution (and possibly quicker to implement) but it doesn't get rid of all of our overheads it simply reduces them by a large factor.

(NB: I'm not talking about bulk submission here which would reduce the overhead of the submission of many jobs. I'm also not talking about #370 which I believe is a Ganga issue which can be solved well in 6.1.20.)

My vote would for trying **Option b)** and seeing what improvements this brings, what does everyone think?

**Comment by milliams** [comment]
I feel that it's useful having DIRAC running in a separate environment so that we aren't, for exampe, tied to using the same Python version (e.g. they might require 2.6 while we have 2.7 or we might want to move to 3 but can't since DIRAC doesn't support it).

From the point of view of most of the Ganga code, there should be little (or no) difference between a persistent server and what we have now. Having a persistent server means another thing we have to keep track of, start correctly and shutdown afterwards. It potentially gives a performance improvement due to reduced overheads but unless we know that it is a bottleneck, it is probably not worth the investment of effort.

Batching some DIRAC calls together seems like a good idea, especially in some of the simpler cases. We shouldn't try to be too clever about it but this could help reduce the aforementioned overheads a tad.

**Comment by rob-c** [comment]
OK so some ```finalizeJob``` method may be a good idea to code up as this will just return 3 objects instead of 1.
Dealing with submitting multiple subjobs I'd argue is kinda done by the ```parallel_submit``` atm which is limited only by the queue size.

**Comment by alexanderrichards** [comment]
I agree that we cant we should probably not require the same DIRAC/Ganga environment for the reasons @milliams gives.

**Option b)** I think we should do **anyway** so makes sense to start there. As I recall the main overhead from our current way of working comes from the magic DIRAC function `parseCommandArgs` (or whatever it is). It may also help to understand better what this is doing and if we can in some cases/for some operations neglect this.

**Comment by chaen** [comment]
Hi,

The most important thing this ```parseCommandLine``` is doing is to fetch and merge all the configuration. I don't exactly know how you do you actually separate the process, but in principle it needs to be called once (and only once) per process. Do you use ```subprocess.call(['python', 'a_script.py'])``` or what is it that you do ? (sorry, I couldn't find the code anymore)

**Comment by alexanderrichards** [comment]
Yes as I recall we create a new subprocess using `Popen` for any DIRAC API we want to make.

**Comment by egede** [comment]
@chaen See `ganga/python/GangaLHCb/Lib/Server/DiracLHCbCommands.py` for the preamble that is executed each time that anything from Dirac is called.

**Comment by chaen** [comment]
I was more interested in the way this was called, but I think I found it here ```ganga/python/GangaDirac/Lib/Utilities/DiracUtilities.py```. 
If I understand correctly, you create a file which is a concatenation of all what you need to make it a standalone script, which is then executed using ```subprocess.Popen``` ? 
If that is the case, I am afraid that there is no way to avoid the ```parseCommandLine``` every time you call ```DiracUtilities.execute```

**Comment by rob-c** [comment]
@chaen This is exactly what we're doing at the moment, and so our first step is to reduce the total number of calls of this type which we're making.

**Comment by chaen** [comment]
I see. Given that you have this (good!) reason of separate environment, the only alternative I could think of would be to start a process which will do the ```parseCommandLine```, and then use IPC to actually execute calls. It is kind of your server model (if I understand properly), but local...

**Comment by egede** [comment]
From 

```
def test():
    diracAPI('pass')

t = timeit.Timer('test()', setup="from __main__ import test")
times=t.repeat(100,1)
```
I see that the setup takes 5 seconds per job when executed from Imperial and with little variation. So as an example to submit 200 subjobs in 4 parallel threads, about 5 minutes will be spent just setting up Dirac.

**Comment by alexanderrichards** [comment]
> use IPC to actually execute calls. It is kind of your server model (if I understand properly), but local

yes this the the **Option a)** that @rob-c mentions above.

**Comment by rmatev** [comment]
Have you considered using some external library for the technicalities of the client-server part? I recently learned about [RPyC](https://rpyc.readthedocs.io/en/latest/), which IMHO seems to fit quite nicely and will spare most of the technical issues.

**Comment by rob-c** [comment]
@rmatev i think it's worth looking at now that the dirac interface is much cleaner. Is this a pure python module or does it pull in code we would need to worry about supporting on different machine configs?

**Comment by rmatev** [comment]
They say it's pure python:
> RPyC is a pure-python library, and as such can run on any architecture and platform that runs python (or one of its other implementations), both 32- and 64-bit.

**Comment by alexanderrichards** [comment]
yes I am aware of RPyC, this is the technology that I was originally thinking of ;-)

**Comment by drmarkwslater** [comment]
Coming from a fairly ignorant position, I would personally disagree and go for option a) if possible (i.e. directly importing the Dirac API in Ganga). I understand the reasons against it (it ties us in to the Dirac environment, specifically the Python version), however, the latest versions of Dirac are already at Python 2.7 which we're not actually requiring yet anyway and the move to Python 3 (i.e. the dropping of Python 2.x completely) is probably so far off as to be not worth worrying about at this point. If we do just use the Dirac API inside Ganga, then we simplify an awful lot of code and we don't have to worry about either server/client models (which I'm really not a fan of if we can avoid it) and also the overhead of setting up the Dirac environment each time.

I'm guessing this isn't the popular option but just to mention, this is what's done in GangaAtlas, i.e. we have direct DQ2/Rucio API calls in the code.

Anyway, that's my 2 cents :smile:

**Comment by egede** [comment]
@drmarkwslater A few points here.

- It is not just about Python version, but also about the dependence on extension libraries. We have seen problems with wrong versions of shared libraries being loaded and also with the compiled support for unicode.
- If we want to have control over timeouts, we need to start a new process anyway as there is no way to actually kill a thread in Python from outside the thread.
- We would lose the ability to be truly multi-threaded (might not matter that not much of the interaction with Dirac is CPU bound).
- We do not have control over the DIRAC code in the same way that ATLAS has control over the DQ2/Rucio code.

**Comment by mesmith75** [comment]
I think this is obsolete now.
