### ISSUE TITLE
Slowdown in job submissions from 6.1.1-hotfix1 - 6.1.2-hotfix1 and beyond

### ISSUE THREAD

**Issue by jepperandersen** [ganga-devs/ganga#42]
Submitting 100 subjobs to the ARC backend takes ~1 minute in 6.1.1-hotfix1 (well done!), but slows to ~15minutes in 6.1.2-hotfix1 and beyond. I just tested all the way to 6.1.13.

**Comment by rob-c** [comment]
This is probably related to some of the problems being looked at in #41
