### ISSUE TITLE
test needed for Exectuable+files/actual .exe

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#423]
We need a test which actually uses the .exe parameter in the Executable program to submit a job.

I suspect this may be broken in some cases in 6.1.19 but we don't have a test which properly confirms this as far as I'm aware and we really should. The behaviour of this class with the default settings and the 'normal' use-case is extremely different.

If it shows up in 6.1.19 testing I suggest we fix it but if there isn't then I've probably found a corner case.

Also this should be run on multiple backends at some point as the RT/App doesn't ship the files as expected.

I've a PR where I'm adding the files stuff in, quickly as I'm going through and testing job configurations but we need a dedicated test for this app in a few situations especially as it's the default one people go to.

**Comment by egede** [comment]
The agreed Script and Program application objects will make this redundant.
