### ISSUE TITLE
outputSE option for DIRAC jobs

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#428]
I'm planning to add an ```outputSE``` option to the ```Dirac``` backend for DIRAC jobs in 6.1.20.

This will only become a requirement when a user tries to submit a job that requires outputdata but if a user attempts to submit a job without requesting an outputSE then the job submission should fail.

There is currently no nice automated way to upload data automatically to a writable SE based upon where a user can currently write to.

This will be independent of work on the ```DiracFile``` to make it work in a more vanilla DIRAC friendly way.

Obviously I'll add/change some options for LHCb so that LHCb users are unaffected by this change.

Are there any objections to this?

**Comment by egede** [comment]
This doesn't seem to depends on the backend at all. A local job with a 
DiracFile needs this as much as a Dirac job. It has to be a property of the 
DiracFile objects.

Ulrik

**Comment by rob-c** [comment]
No.
This could be done with the DiracFile object on a per object basis but is just an ugly thing to do having multiple files placed on multiple SE at the end of each Job. Are we sure we want this level of functionality given we don't currently enforce checking that the IGangaFile objects are sane before we submit and we would need all of this just to be able to upload a single file on the GridPP Dirac instance.
We'd still be putting the test in the submit step, still be failing jobs if the tests fail and all of the logic belongs in some place so that LHCbDIRAC can overload it.

It's this or we opt to pass the WN code with the job and setup a Dirac env on the WN just to submit a job which puts the burden and an extra ~100 lines of code on us for each job and we drop the ability to manage output files in a sane way imo.

**Comment by egede** [comment]
We can't break the model of that any `IFile` object can go to any backend. On the other hand, I would not really care about if the `Dirac` backend submission code enforce that all `DiracFile`s have the same SE and fail the submission if they don't. The use case for this would anyway almost for sure be a mistake rather than an intention from the user side.

The only other option I can imagine is that we make this SE a config option and that it thus become a property of the Ganga session. I do not really like that idea though.

**Comment by rob-c** [comment]
Some of this was already coded up anyway into other util functions as per #430 .
I don't know why there is talk about ```IGangaFile``` tbh I'm only planning to test and you only use the Dirac output data with ```DiracFile``` objects. Maybe I wasn't clear.

I just want to make sure that an SE of some form is passed to the job so that a file can be uploaded using the Dirac API rather than doing something horrible and subverting the Dirac API for no good reason.
As per the aforementioned PR a user can either set a default SE in their configuration and rely on this or can chose a different SE for each output ```DiracFile``` if they chose to. The functionality was mostly already there, there is just a lot of noise around the config and the some bleed form LHCb into Dirac.
