### ISSUE TITLE
DiracFile quirks when uploading

### ISSUE THREAD

**Issue by olupton** [ganga-devs/ganga#43]
Hi,

There are a couple of minor issues with DiracFile in 6.1.13, particularly in relation to uploading files to grid storage:

*) If you specify namePattern and localDir, but not explicitly an LFN, before calling DiracFile.put() older ganga versions would generate a path like /lhcb/user/x/xxx/GangaFiles_23.46_Wednesday_18_November_2015/MyFile.dst and upload it there. 6.1.13 fails to add the '/MyFile.dst' part, so the LFNs are confusing and not unique if you upload >1 file/minute. (https://github.com/ganga-devs/ganga/blob/master/python/GangaDirac/Lib/Files/DiracFile.py#L720 + lines 751-752 look to blame).

*) Specifying uploadSE as an option to DiracFile.put() doesn't seem to work properly; clicking through github it looks like all_SE_list() uses a global cache, so uploadSE gets ignored on the 2nd and subsequent uses.

Clearly these are both minor issues that can be worked around on the user side, but I think should still be considered low-priority bugs.

Cheers, Olli

**Comment by olupton** [comment]
I just noticed that the 2nd bug I reported has reappeared. It looks like this commit accidentally reverted the change? https://github.com/ganga-devs/ganga/commit/6360234a159c84f8d8716d34c4004799cccf6157

**Comment by rob-c** [comment]
@olupton Which bug exactly was this, apologies it doesn't jump out at me from the diff

**Comment by rob-c** [comment]
OK, I see it, that patch reverts some good features, I'll work on reverting it ahead of 6.1.17

**Comment by olupton** [comment]
@rob-c I should have been clear; the regression that I noticed (in 6.1.13) is that the uploadSE option for DiracFile.put() gets ignored after the first upload/session again (and all files get uploaded to the same SE even if you specify different ones).
