### ISSUE TITLE
DIRAC-ui broken on cvmfs

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#436]
Hi all,

I can't seem to generate an lsst proxy using the dirac-ui on cvmfs due to something being out of date (I suspect a voms proxy but this is not my area of expertise).

Is there a plan/policy which sorts out the voms proxies on the cvmfs install?

Would it be more sane to manage the voms proxies in a user area so that these can be updated by Ganga once the user needs them rather than wait for cvmfs to cycle?

Thanks,

Rob

**Comment by drmarkwslater** [comment]
This is probably due to the problem Daniella mentioned - i.e. there needs to be infrequent updates to the site/VOMS certificates and settings to make sure everything still works. I'll try to set up a cronjob on the CVMFS machine to see if this can be done automatically.

**Comment by rob-c** [comment]
OK, this appears to have fixed itself (I changed nothing my end but now instead of mystery messages I get a proxy which is valid). Or something else changed on cvmfs/the-grid and I didn't notice.

Btw the ```dirac-proxy-init``` is _really, really bad_ at realising when there is an error from the voms tools and returns success even if the voms tools failed to do something like talk to a server... I think this is worth raising with the DIRAC people at some stage.

**Comment by rob-c** [comment]
This has been fixed by changing to use the correct strict flag when generating proxies
