### ISSUE TITLE
Interactive submit failure when successful

### ISSUE THREAD

**Issue by rajanandakumar** [ganga-devs/ganga#44]
When I run a test job with the interactive backend, the job runs fine. However, the job throws a series of errors of the following kind

Ganga.GPIDev.Adapters              : WARNING  ---------- error in user/extension code ----------
Ganga.GPIDev.Adapters              : WARNING  Traceback (most recent call last):
Ganga.GPIDev.Adapters              : WARNING    File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r11/install/ganga/python/Ganga/GPIDev/Adapters/IBackend.py", line 310, in master_resubmit
Ganga.GPIDev.Adapters              : WARNING      result = b.resubmit()
Ganga.GPIDev.Adapters              : WARNING    File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r11/install/ganga/python/Ganga/Lib/Interactive/Interactive.py", line 105, in resubmit
Ganga.GPIDev.Adapters              : WARNING      return self._submit(self.getJobObject().getInputWorkspace().getPath("__jobscript__"))
Ganga.GPIDev.Adapters              : WARNING  TypeError: _submit() takes exactly 3 arguments (2 given)
Ganga.GPIDev.Adapters              : WARNING  --------------------------------------------------

As a result, the job then automatically tries to resubmit, while actually also simultaneously running fine. The resubmit stops when it finishes its maximum number of retries. The output is okay and the ntuples are stored correctly.

VO : LHCb
Ganga Version : v601r11

**Comment by milliams** [comment]
I touched this code not too long ago so I'll take a look.

**Comment by alexanderrichards** [comment]
@milliams thanks Matt

**Comment by milliams** [comment]
I believe I fixed this already in 6.1.12 with commit 9374cf1e51a350d54a5397d9ef092010edadae68.
