### ISSUE TITLE
ganga misses updates of self-built packages

### ISSUE THREAD

**Issue by pseyfert** [ganga-devs/ganga#440]
I quite often run into problems when checking out (DaVinci) packages while a ganga session is running. The running ganga session does not -after building the new packages- send the python modules and shared libraries of the new package to new grid jobs. How I usually end up in this situation is:

1. log in to lxplus in terminal (A)
2. `SetupDaVinci --build-env vVVrRR`
3. `getpack Phys/MYPACKAGE vVVrRR`
4. `cd Phys/MYPACKAGE/cmt ; cmt config ; cmt make -j8`
5. open new terminal (B)
6. in terminal (B) `SetupGanga ; lhcb-proxy-init` (password) `ganga`
7. submit a DaVinci grid job (with `masterpackage="Phys/MYPACKAGE"`)
8. job finds the configurables from MYPACKAGE but fails since I should use a more recent version of `Phys/OFFICIALPACKAGE` (new property added to a DecayTreeTupleTool)
9. go back to terminal (A) `cd ../../.. ; getpack Phys/OFFICIALPACKAGE head ; cd Phys/MYPACKAGE/cmt ; cmt br cmt config ; cmt br cmt make -j8`
10. observe, that also OFFICIALPACKAGE gets rebuilt; check that in `~/cmtuser/DaVinci_vVVrRR/InstallArea` the library for OFFICIALPACKAGE is present
11. check that in `~/cmtuser/DaVinci_vVVrRR/InstallArea/path/to/python/module/of/configurable` the new property is listed
12. go to terminal (B), create a new DaVinci job in ganga (i.e. not cloning or copying the old job)
13. submit the new job, see it fail for the same old reason

rerunning makes and configures in terminal (A) can be done in all sorts of combinations without success. the only way i found so far is to close ganga in terminal (B), close the ssh session in terminal (B), log back in to lxplus and redo steps 6 and 7.

So far i always thought that at the start of ganga the list of present *projects* gets checked (as in, i always failed in the past when doing step 5 before step 4 finished) but it took me once again hours to realise that ganga doesn't even reinvestigate the contents of InstallAreas whenever a new job object gets instantiated.

(This is using v601r18 and v600r44)

**Comment by rob-c** [comment]
@pseyfert Not to sound too naive but does this work if ganga is restarted and is there an issue with restarting ganga to pick these changes up?
I'm wanting to spend time working on the cmake support soon anyway which does away with the versioning system and would make this a lot more sensible.

**Comment by pseyfert** [comment]
@rob-c big fan of cmake support! for now i will not be able to try around (now i need the grid running for me). but i *think* i went through this at some point (after all i tried changing the ganga version, but thinking about it, they may have failed for different reason (incompatible submission script...))
I should be able tomorrow or so to try if SetupGanga / LbLogin execution or starting ganga triggers the refresh

**Comment by pseyfert** [comment]
BOAH, seems my initial diagnosis was wrong. i had some fight reproducing this today and observed:
I cannot reproduce it straight the way i documented it above. the jobs go to the grid and run no matter in which order I start ganga and install packages. and if packages are missing, the pickeling fails already and the jobs don't go to the grid in the first place.

What i missed noting (and probably at some point trying back and forth) is that many of my projects are physically in `/afs/cern.ch/work/p/pseyfert/DaVinci_vVVrRR` and in `/afs/cern.ch/user/p/pseyfert/cmtuser/` there are mostly symlinks. (and now i keep the jobid 131779959 where a job failed on the grid due to a missing property of a configurable - which should fail when pickeling the job).
For that failing job, i started ganga in terminal B before even logging in on terminal A and starting the `SetupProject --build-env`.

just restarting ganga (job 131781178) results in a job that fails.

logging out and back in again in terminal B, setting up ganga, starting, creating and submitting the grid job (131781455) results in a job that also fails. (which is then probably where i restarted the other day, deleted everything started from scratch and was too lazy to symlink)

**Comment by egede** [comment]
Not obvious that there is any Ganga problem here. Please reopen with clear way to reproduce issue if there is one.

**Comment by pseyfert** [comment]
agree, my first diagnosis was far off, reopened in #446
