### ISSUE TITLE
Dirac/Ganga job statuses

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#441]
Hi all,

From memory there is a good reason about having the ```"Done"``` and ```"Complete"``` status in Dirac marked as ```completed``` in ganga.
(I think this was something to do with data replication etc...)

However, when I run my branch #430 I'm seeing jobs consistently being marked as failed as the job is not getting the output file until some time after the job has finished.

After digging around I found my jobs were passing through the monitoring cycle too quickly and were completing whilst Dirac was still processing the output from the Job.

This is responsible for at least some of the problems of jobs completing ahead of the output sandbox or data being made available.

In interests of getting something working I'm keen to move to have only Dirac jobs which are in a ```"Done"``` state (in DIRAC) marked ```completed``` (in Ganga).

Alternatively I'm going to move to mark all jobs in the ```"Complete"``` state but expect some output data in the form of a DiracFile (aka. asking Dirac to upload some output for us) as being in the running state. This is the only way to get Ganga to wait for the output data to be made available as requesting it before it's been uploaded will _work_ and will get an empty output data set which has been a pain to debug as the data exists in DIRAC and could be manually requested in Ganga but was missing after the monitoring loop progressed a job to completed.

Does anyone have any opinions on this?

Thanks,

Rob

**Comment by egede** [comment]
You are correct that the DIRAC status `complete` means that the job has finished on the worker node but that the output might not yet be replicated to both storage elements (as is LHCb policy). I could very well imagine that the `complete` state has a slightly different meaning in this aspect on the generic DIRAC instance. 

I suggest that you in the generic DIRAC instance revert to that jobs should be marked with DIRAC status `Done` before Ganga declares them completed, but that you (unless you have other evidence), lerave things as they are towards LHCb.

**Comment by rob-c** [comment]
@egede This is exactly the same behaviour I'm seeing on the DIRAC instance but I'm seeing jobs fail on both GridPP and LHCb flavours of DIRAC because their output DiracFile objects aren't resolving to anything even though Ganga things that the job has _finished_.
Polling a DIRAC job in the ```Completed``` state doesn't return a valid LFN for all of the outputdata it's been asked to process.

In both cases waiting about 5min for DIRAC to progress the job into a ```Done``` state and performing ```job.backend.reset()``` _fixed_ the problem and on the 2nd pass the output data was resolved and the job completed.

I'm looking to change both DIRAC and LHCbDIRAC commands to reflect this unless there is a strong objection?

**Comment by egede** [comment]
@rob-c We used to have what you propose, but changed it about a year (or maybe two) ago as users complained that "my job is finished but I can't get hold of it". I am happy to change it back again, but wonder if we should move the dictionary to the config system to make flip-flopping on this easier in the future?

**Comment by rob-c** [comment]
@egede I think moving this dictionary should be possible although could require some gymnastics. I'll look into it as one of the last things in #430 .
I have spotted I was accidentally using the Dirac vs DiracLHCb API however (fix incoming) so this may be a bug I've spotted due to that.
Either way I think having this as a configurable can only be an advantage.

**Comment by rob-c** [comment]
OK, I've migrated the dictionary mapping the Dirac to Ganga job statuses to the configuration system in #430 . I'm just in the process of checking a few final jobs then I'll look to merge that PR.
