### ISSUE TITLE
incomplete object errors constantly spamming terminal

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#442]
I suspect there is a minor bug in the Monitoring loop and possibly the flushing algorithm in the Registry.

At the moment I have several jobs which rely on a Ganga plugin in order to fully load the XML file.

The expected behaviour is that the file should fail to load asif the XML is corrupt and I be notified about this error and Ganga should move on with other things.

However I'm constantly (once per 2-3 seconds) being spammed with errors akin to:
```
ERROR    #1 Error(s) Loading File: /afs/cern.ch/user/r/rcurrie/gangadir/repository/rcurrie/LocalXML/6.0/jobs/0xxx/260/data~
ERROR    XML File failed to load for Job id: 260
ERROR    Actual Error was:
Repository 'jobs' object #260 is not accessible because of an InaccessibleObjectError: Repository 'jobs' object #260 is not accessible because of an PluginManagerError: PluginManagerError:  (PluginManagerError(...), u"cannot find 'Im3ShapeApp' in a category 'applications', or elsewhere")
ERROR    Error Loading Jobs! '[260]'
ERROR    #1 Error(s) Loading File: /afs/cern.ch/user/r/rcurrie/gangadir/repository/rcurrie/LocalXML/6.0/jobs/0xxx/260/data
ERROR    #1 Error(s) Loading File: /afs/cern.ch/user/r/rcurrie/gangadir/repository/rcurrie/LocalXML/6.0/jobs/0xxx/260/data~
ERROR    XML File failed to load for Job id: 260
```

This is reduced significantly with the monitoring turned off so I suspect the monitoring is no longer blacklisting jobs it can't load correctly but it doesn't go away and other than the monitoring loop I think only the registry flushing loop is the only active task dealing with handling objects which may be on disk behind the scenes.

I can just about work with this as long as it doesn't get any worse but this should probably be looked into even though it doesn't effect users.

**Comment by egede** [comment]
@rob-c You failed to include the actual error ...

**Comment by rob-c** [comment]
@egede Hit enter too soon but should be updated now
