### ISSUE TITLE
Tasks should use lazy loading and not break Jobs lazy loading

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#443]
In issue #417 it looks like @olupton is seeing problems with Tasks not using lazy loading and maybe breaking job lazy loading as well. I should look into this and fix it.

**Comment by rob-c** [comment]
I've written a test which is in a pending PR which shows that the tasks system doesn't break lazy loading as much as it wasn't stopped from loading with `--no-mon`.
