### ISSUE TITLE
job submission with private package version fails when ~/cmtuser/Project_vVVrRR is a symbolic link

### ISSUE THREAD

**Issue by pseyfert** [ganga-devs/ganga#446]
# what fails
```bash
[ins] pseyfert@lxplus014 ~/cmtuser/DaVinci_v39r1/Phys/BsToKMuNu/cmt > history
<snap>
 8000  rm DaVinci_v39r1
 8001  SetupDaVinci --build-env v39r1 
 8002  getpack Phys/BsToKMuNu head ; getpack Phys/DecayTreeTupleTracking head 
 8003  cd Phys/BsToKMuNu/cmt
 8004  cd ../../../..
 8005  mv DaVinci_v39r1 /afs/cern.ch/work/p/pseyfert/DaVinci_v39r1_for_gangatest
 8006  ln -s /afs/cern.ch/work/p/pseyfert/DaVinci_v39r1_for_gangatest DaVinci_v39r1
 8007  cd DaVinci_v39r1/Phys/BsToKMuNu/cmt
 8008  cmt br cmt config ; cmt br cmt make -j12
```
then open a new terminal, log in to lxplus, start ganga v601r18 and in the ganga prompt
```bash
cd cmtuser/DaVinci_v39r1/Phys/BsToKMuNu/scripts
ganga RunOnGanga.py
```
NB: user name is hard coded in RunOnGanga.py [EDIT: wrong filename in this line in OP]

what then happens is
 * job gets prepared successfully and submitted
 * job fails at run time due to `AttributeError: Configurable 'TupleToolConeIsolation' does not have property 'FillMergedPi0Info` (that's why the head of Phys/DecayTreeTupleTracking is needed.)
(job id 131825119)

## side note
from the successful job preparation I conclude that the preparation of the job correctly picks the local version of DaVinci -- if I don't getpacking and build DecayTreeTupleTracking the job preparation fails.

# how to work around
```bash
[ins] pseyfert@lxplus014 ~/cmtuser/DaVinci_v39r1/Phys/BsToKMuNu/cmt > history
<snap>
 8010  cd
 8011  cd cmtuser
 8012  rm DaVinci_v39r1
 8013  mv /afs/cern.ch/work/p/pseyfert/DaVinci_v39r1_for_gangatest DaVinci_v39r1
 8014  ls DaVinci_v39r1/InstallArea
 8015  ls DaVinci_v39r1/InstallArea/x86_64-slc6-gcc49-opt
 8016  ls DaVinci_v39r1/InstallArea/x86_64-slc6-gcc49-opt/lib
 8017  ll DaVinci_v39r1/InstallArea/x86_64-slc6-gcc49-opt/lib
```
and then start ganga again, in ganga go to the scripts directory, submit with `ganga RunOnGanga.py` results in a succeeding grid job (job id 131825982)

# what i conclude

DaVinci jobs in ganga, sent to Dirac, using private versions of DaVinci, which are symlinks in `$User_release_area` are incorrectly packed to the grid (from the error message, i understand the python configurable classes are not in the inputsandbox, in fact _input_sandbox_conf-6a9bc....tgz does not contain the folders `InstallArea` and `lib` in the failing example)

PS: BsToKMuNu is quite heavy in compile time, so you might want to try in a lighter test case. For what crashes here, actually the addition of a new Property in `Phys/DecayTreeTupleTracking/src/TupleToolConeIsolation.cpp`.

PPS: at the time of writing, the head of BsToKMuNu is r205729 (set up job splitter to run over only one file, for this very bug report), DecayTreeTupleTracking is r203922

**Comment by egede** [comment]
@pseyfert  So this is only related to when you create symlinks inside the cmtuser directory?

**Comment by pseyfert** [comment]
my current impression is that it does not matter when ganga gets started or set up in a different terminal than the one that is used for building (as opposed to what i suspected in #440). i did not (yet?) test if symlinks within the cmtuser/DaVinci_v39r1 cause problems or if cmtuser itself being a symlink is a problem.

**Comment by rob-c** [comment]
@pseyfert Would you be able to have a go at trying this with the new `GaudiRun` application (in the released version v601r21 of Ganga hopefully due out tomorrow).
This application _should_ support working with the new lb-dev project directly. If it doesn't I'm keen to know what feature(s) are missing for this use-case so I can add them.
Thanks, Rob

**Comment by pseyfert** [comment]
will try to translate the test job. Reading the `help(GaudiRun)`, I have two questions:
 1: does `myOpts` also accept lists? (don't have a test for that at hand)
 2: I miss the [`extraopts`](https://lhcbqa.web.cern.ch/lhcbqa/68/can-pass-conddb-tags-davinci-options-file-from-within-ganga) attribute (which the test i posted above uses)

**Comment by rob-c** [comment]
@pseyfert
Ah, Re `myOpts` for now I think it doesn't accept lists. I can add an issue for this.
(This may break everything but the final version in Ganga 6.1.22/6.2.0 we should have a stable API which will allow for more complex jobs like this.)
Did `extraOpts` offer anything over passing multiple opts files in `myOpts`?

I'm understanding this to mean (pseudo-code but I think this explains what I'm thinking I need to support):

```
# In Ganga
j=Job()
j.application=GaudiRun(myOpts=[File1.py, File2.py, File3.py])
j.submit()
...
# On WokerNode
LbLogin.sh && ./run gaudirun.py File1.py File2.py File3.py data.py
```

In the case of a `GaudiPython-like` job should I expect to run?:
```
LbLogin.sh && ./run python -c someWrapperScript.py
#
### someWrapperScript.py
----
from Gaudi.Configuration import *
importOptions(data.py)
execfile(File1.py)
execfile(File2.py)
execfile(File3.py)
----
```

Apologies I'm approaching this from a ganga developer perspective as I've never done anything more complicated than generate/reconstruct/analyse a simple MC sample.

**Comment by egede** [comment]
@rob-c Yes, I think the `extraopts` filed should be added as well. It is often used as a quick way to change the property of a job. It could also be used as a very neat way to create an ensemble of jobs with different options using the `ArgSplitter`.

**Comment by pseyfert** [comment]
Hi,

for the first half, yes I expect that `myOpts=[file1.py,file2.py]` does `./run gaudirun.py file1.py file2.py data.py`.

(I hope `data.py` in `myOpts` wouldn't lead to `gaudirun.py data.py file2.py data.py` with .py files being overwritten on the worker node)

for `GaudiPython` I must admit I'm glad to not use this anymore since a few years. I always thought it would do `python file.py`, didn't expect the `-c`.

for extraopts: to me `extraopts` and one more file in `myOpts` are practically the same thing. (with preference depending on the use case)

**Comment by rob-c** [comment]
@pseyfert The naming of the `data.py` file comes from LHCbDIRAC on the grid (we can't change this and this has been the case for a long time) and from ganga when running on batch/local/other.
I'll try and add a check to throw an error during submit if a user has a file with this name as part of their job.

@egede How about I add an `extraOpts` attribute as a list of `IGangaFiles` which would allow for the most flexibility when splitting/submitting complex jobs?
I can imagine some users would prefer being able to add multiple opts files but this keeps it simple for those not running many different jobs.

I think I'll try and concatenate the different `myOpts` + `extraOpts` files for _GaudiPython-style_ jobs so that the script is just using 1 call to `execfile`

**Comment by egede** [comment]
Created the `extraopts` discussion as a separate issue #640

**Comment by rob-c** [comment]
@pseyfert Does the new GaudiExec support this use case and can we close this issue?

**Comment by pseyfert** [comment]
Actually I think now that this issue doesn't apply to `lb-dev` applications to begin with. Because these don't need to be in `~/cmtuser/Project_vVVrRR` (from where `SetupProject` picks them up). They can just be on `/afs/cern.ch/work/` and be provided to `GaudiExec.directory`. So with the migration from `SetupProject` to `lb-dev` the use case for symlinking is gone.
