### ISSUE TITLE
Standardise positional arguments for GangaObject constructors

### ISSUE THREAD

**Issue by milliams** [ganga-devs/ganga#452]
As mentioned in #449 (and was a potential stopper for #206) it's often useful to be able to construct certain `GangaObject`s with a single positional argument. The most obvious examples are the `IGangaFile` types which, at the GPI are useable as:

``` python
f = LocalFile('test.sh')
```

it also works for some types at the raw level:

``` python
f = stripProxy(LocalFile)('test.sh')
```

The former works because of `__construct__` and the latter works because of the overridden `__init__`. These two implementations are separate and have no enforced consistency.

I think that probably the canonical implementation should be in `__init__` which the proxy `_init` function will call with `*args`. The flow is then:
- If it's a raw `GangaObject` then `__init__` does as expected in the usual Python way
- If it's a proxy object then the proxy `_init` will call `__init__` with `instance = pluginclass([stripProxy(arg) for arg in args])`

There are some questions/caveats to this though:
- `GangaObject`s must remain constructible with no arguments (and most will continue to take none).
- Current default behaviour is to do a `copyFrom` (`GangaObject.__construct__`) which this will break. I think the only place this is really used is for `Job(j)` which could be accounted for in `Job.__init__`.
- This is orthogonal but related to `_auto__init__` which is called argument-less for all proxy objects.

**Comment by rob-c** [comment]
This is compatible with removing the ```__construct__``` imo in favor of fixing the ```__init__``` methods.

I would argue that ```_auto__init__``` should remain with no argument as it's a nice hook I like
