### ISSUE TITLE
Issues with GangaAtlas shutdown

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#459]
It seems there's some problems with GangaAtlas shutdown in (at least) 6.1.19. There are quite often `SessionLock` issues and almost always:

```
[10:12:44]
Ganga In [1]: 
Do you really want to exit ([y]/n)? y

INFO     Stopping running tasks before shutting down Repositories
Exception TypeError: "'NoneType' object is not callable" in <function _removeHandlerRef at 0x7f014ea79f50> ignored
```

I suspect that there is something getting screwed up when DQ2/Rucio is imported and the `atexit` handlers are somehow going wrong.

**Comment by milliams** [comment]
The `_removeHandlerRef` error is due to the logging being shutdown. It was a known [bug in Python](https://bugs.python.org/issue21149) that is fixed in 2.7 and 3.4. I imagine that we can work around it but it's a tricky one. I don't know why it only shows up in ATLAS mode though.

**Comment by egede** [comment]
@milliams LHCb is using Python 2.7 so we will not see it there.

**Comment by milliams** [comment]
@egede True, but I haven't seen it on any of my local testing either which is done on a plain SL6 with Python 2.6 and no LHCb or ATLAS plugins.

**Comment by drmarkwslater** [comment]
OK so this may explain this then. I see it after setting up an Athena release which points me at Python 2.7.9 but NOT on Python 2.6 so I guess it's just the version of Athena/Python that I'm using that's causing the problem.

There may still be issues with the `SessionLock` shutdown which I personally haven't seen but has been mentioned. It looks like on some systems the `SessionLockRefresher` is taking too long to shutdown/hanging:

```
Job status update or output download still in progress (shutdown not completed after 6 seconds).
1 background thread(s) still running: ['SessionLockRefresher'].
Do you want to force the exit (y/[n])? y
INFO     Stopping Job processing before shutting down Repositories
WARNING  Shutdown forced. 1 background thread(s) still running: ['SessionLockRefresher']
INFO     Shutting Down Ganga Repositories
INFO     Registry Shutdown
Exception in thread GANGA_Update_Thread_SessionLockRefresher (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/ALRB/atlasadmin/atlas-sl6x64.triumf.ca/ATLASLocalRootBase/x86_64/Ganga/6.1.19/install/6.1.19/python/Ganga/Core/GangaRepository/SessionLock.py", line 165, in run
  File "/ALRB/atlasadmin/atlas-sl6x64.triumf.ca/ATLASLocalRootBase/x86_64/Ganga/6.1.19/install/6.1.19/python/Ganga/Core/GangaThread/GangaThread.py", line 48, in unregister
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'getInstance'
```

Any thoughts on what could take the `SessionLockRefresher` so long to shutdown?
