### ISSUE TITLE
Move IGangaFile from Ganga/GPIDev/Lib/File/IGangaFile to Ganga/GPIDev/Adapters/IGangaFile

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#46]
Hi all,

This is a minor task which has obvious repercussions of some imports needing fixing but is there any reason why the IGangaFile interface shouldn't be placed with other interfaces in Ganga.GPIDev.Adapters?

This is a relatively simple 'Friday afternoon' task to do one week so I don't think we should have it blocking 6.1.14 but it would be nice to change this imo,

Unless anyone has any good reasons not to fix this?

Thanks,

Rob

**Comment by alexanderrichards** [comment]
Please go ahead, it clearly belongs with the other interfaces

**Comment by milliams** [comment]
Makes sense to me. Go ahead.
