### ISSUE TITLE
master index not being updated with auto-flush

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#461]
The master index was originally only intended to be updated at shutdown or once every 5min or so (I think) given the large amount of I/O.

Given we've fixed a large amount of these I/O issues adding an update of the master index cache to the auto flusher seems sensible otherwise users can potentially have a Ganga session crash and then their job will appear in the incorrect ```new``` state.

I see this when I'm doing work over a bad connection and it's becoming an irritating bug to not know the true status of my jobs.

This shouldn't require too much work, just probably cleaning away the old rate limiting code in the master index writing method and then to call it directly from some flush method (probably best done from the Registry to avoid multiple writes of the same data to disk)

**Comment by milliams** [comment]
I feel that we want to make sure that as far as we possible can, we have the same information in the master index, per-job index and `data` at any one time. Writing them out at different times is I think just asking for trouble.

I'd rather keep this to the repository level as the registry should have to have no knowledge at all about where the repository is getting its data.

**Comment by rob-c** [comment]
ok but just adding the master index flush to the registry flush wold be (a little) wasteful and I think we can streamline the process of passing the list of repo objects to be flushed into the registry otherwise we have to expose some flush_registry (or equivalent) hook for indexes which make little sense to flush 20 times for 20 dirty jobs for instance.

**Comment by rob-c** [comment]
OK, I may implement a very quick solution for this as soon as #458 goes in as I'm hitting this whenever i lose connection to a remote machine with Ganga on that the master index is not updated so the job appears new and completely unmodified from ```jobs``` which gets confusing. (And dangerous as I just cleaned up my repo with ```jobs.select(status='new').remove()``` and lost an active job due to lazy loading working as expected.
