### ISSUE TITLE
Make printPrepTree an override of printTree

### ISSUE THREAD

**Issue by milliams** [ganga-devs/ganga#462]
#458 moves `printPrepTree` to be inside `IPrepareApp` rather than `Node`. If this method was renamed to `printTree` then this would mean that in the places where we currently explicitly call `printPrepTree`, we could instead call `printTree` and MRO would do its thing.

It should be a simple change but we need to make sure that it does not break the prepare hash.

**Comment by tarunlnmiit** [comment]
I want to start contributing as I want to participate in this year's GSOC. If I understand the issue correctly, the function named printPrepTree needs to be renamed printTree and all the calls to this function in the codebase need to be changed accordingly. Also, I didn't understand the last line in the issue described above.

Any help will be appreciated.

**Comment by egede** [comment]
When a job object in Ganga is "prepared" it is placed in a read-only state and a hash is calculated for the attached application object such that it can be checked if it is still consistent. That is what the last sentence refers to. Implementing this long forgotten change should be fine. Just create a pull request.

**Comment by hedonhermdev** [comment]
Hey, @tarunlnmiit are you working on this?

**Comment by tarunlnmiit** [comment]
@hedonhermdev No.

**Comment by hedonhermdev** [comment]
@egede can I take this issue up?

**Comment by egede** [comment]
@hedonhermdev Sure.
