### ISSUE TITLE
DIRAC timestamps incomplete in develop

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#464]
As of the recent changes I put in for the changes in DIRAC I suspect that we're susceptible to a minor bug in the population of the backend timestamps.

This is mainly cosmetic as I think it's only ever used in the same place that it's called from, however in situations such as DIRAC rescheduling a job then our timestamp doesn't reflect this.
We store the information with a private dictionary which now only populates the first values for a job such as time submitted, time running.

I think it's reasonable to expect that we update this when a status update is detected which actually changes the job state that this dictionary be updated accordingly (with as few DIRAC calls as possible). Until now though the dictionary was being updated regardless which was causing quite a lot of traffic to DIRAC for a single job).

Should we expect to record `backend_running` records for instance or should we only record the last one where everything worked which is of most interest to the user?

**Comment by egede** [comment]
@rob-c I wonder if we should remove all the backend specific information here and instead allow the user to request that it is populated on a job-by-job basis. It is indeed expensive and is hardly ever used.

**Comment by rob-c** [comment]
@egede Adding a ```populate_timestamps``` function (or other name) specifically for DIRAC wouldn't be a bad thing but I've managed to bring this down to 3 calls to DIRAC per job now by only populating the dictionary once as opposed to update all information here every time we poll the job.
I'm seeing improved performance on the latest develop with DIRAC and monitoring of these jobs but I can't quantify this so there may be a bias in my saying that things 'seem a bit faster' after #430.
