### ISSUE TITLE
Ganga should fail gracefully on an FS without File Locks

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#465]
At present, if you try to start Ganga on a file system without file locks, it hangs in the Session lock. See #463. This seems like something we should allow to work.

**Comment by egede** [comment]
@drmarkwslater I disagree. We should not support file systems without locks, but we should abort with a clear error message.

**Comment by drmarkwslater** [comment]
@egede Certainly we should fail gracefully in the short term, but as it's 'only' the Session Lock that needs it (I think), can we not disable the Session Lock stuff and completely stop multiple Ganga sessions - i.e. if there are Session files present, stale or not, Ganga won't start? It just seems a bit unfair prevent running Ganga completely for a feature that probably most people won't be using anyway.

**Comment by egede** [comment]
@drmarkwslater No, I am not that keen on it as it can create trouble for long-term support. The documentation for the lock function we use, implies that this should work on all Unix file systems. So I regard this as  a system issue.

**Comment by drmarkwslater** [comment]
Fair enough - I've changed the issue title to reflect that we need it to fail gracefully instead.

**Comment by egede** [comment]
@drmarkwslater So what is the new behaviour. That Ganga stops if no lock can be obtained or it continues without the protection?

**Comment by drmarkwslater** [comment]
Basically, it will now raise an exception that details the `IOError` that is raised by `fcntl.flock` which says 'No locks available` instead of hanging. I thought that would be OK rather than catching this specific error and printing our own?
