### ISSUE TITLE
Change DiracEnv to directly support the dirac-ui bashrc

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#469]
Hi all,

I'm thinking of adding some code to support the ```bashrc``` from the default install of the ```dirac-ui```.

This would mean that we don't need to have a somehow special ```envfile``` generated for Ganga to use.

This should be straightforward to do and will just be to source the actual file pointed to in the config and get the output environment rather than parse the file itself as 1 large dictionary.
The env file format we currently support is _sourceable_ by bash but I'd like to reduce the effort required to get a fresh install working.

This should only be a quick 4 or 5 lines of code in the DiracUtils package,

Rob

**Comment by milliams** [comment]
This is something that I've been confused as to why we don't do for a long time. All it needs to be is wherever we call to the DIRAC UI, preface it in the subprocess call with a `source .../dirac_ui/bashrc`. There's no need for us in Ganga to do anything with the file ourselves.

**Comment by rob-c** [comment]
yes indeed, but we at least cache this in memory once as this should never change under Ganga.
I think this was simply a choice made a long time ago that didn't foresee (amongst other things) the dirac-ui tool.

**Comment by egede** [comment]
@milliams The historic reason was that the call to setup this in LHCb was VERY slow. SO slow that we did not even want to do it once per Ganga session.

@rob-c So will you make the similar change for LHCb? So run something like 

```
lb-run LHCbDirac vXrYpZ printenv
```

**Comment by rob-c** [comment]
@egede 
The command I'm going to run will simply read in a given configuration file and store the env as an in-memory dictionary. This functionality is already (I think) used by the LHCbDirac env scripts which just save a new env to disk somewhere and recall the file at startup.
I'm basically planning to do ```source someEnvFile && printenv``` in a new shell command using a subprocess tool and will parse the results of this into memory.

(I think I'm hiding a lot of complexity in saying this but it's essentially what is done)

I may have a look at the LHCbDirac env code and see if I can add lb-run support in some form, but I'll do that with an eye to cmake support.

**Comment by rob-c** [comment]
Done
