### ISSUE TITLE
running tests locally fails due to import

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#487]
Hi all,

I'm trying to run a small part of the test suite locally but keep hitting a wall,

After the recent changes I keep getting:

```
ImportError: No module named Ganga.testlib.GangaUnitTest
```

Whenever I try and do something like:

```
>py.test Ganga/test/GPI/Bugs/TestJIRA1961.py
```

Running the tests in this way (or something very minimal) is very helpful in debugging I've found.
This was working a while ago and I have a fully setup Ganga environment but still cannot run these tests.

Does anyone know what the correct command line fu is to be able to make this work again?

Thanks,

Rob

**Comment by milliams** [comment]
This works fine for me. I tend to run the tests from the `ganga` directory so I would run:
```bash
$ py.test python/Ganga/test/GPI/Bugs/TestJIRA1961.py
```
but I just tested running from the `ganga/python` directory with
```bash
$ py.test Ganga/test/GPI/Bugs/TestJIRA1961.py
```
and that works too.

Are you inside a virtualenv with Ganga installed with `pip install -r requirements.txt`?

**Comment by rob-c** [comment]
No I'm on LHCb after a standard ```SetupProject ganga``` running on the latest git develop

**Comment by milliams** [comment]
What do we get if you run:
```python
python -c "import sys;import pprint;pprint.pprint(sys.path)"
```

**Comment by rob-c** [comment]
```
['',
 '/afs/cern.ch/user/r/rcurrie/site-packages/kid-0.9.6-py2.6.egg',
 '/afs/cern.ch/user/r/rcurrie/cmtuser/GANGA/GANGA_Dev/external/httplib2/0.8/noarch/python2',
 '/afs/cern.ch/user/r/rcurrie/cmtuser/GANGA/GANGA_Dev/external/python-gflags/2.0/noarch/python',
 '/afs/cern.ch/user/r/rcurrie/cmtuser/GANGA/GANGA_Dev/external/google-api-python-client/1.1/noarch/python',
 '/afs/cern.ch/user/r/rcurrie/cmtuser/GANGA/GANGA_Dev/external/ipython/1.2.1/noarch/lib/python',
 '/afs/cern.ch/user/r/rcurrie/cmtuser/GANGA/GANGA_Dev/external/PYTF/1.6/noarch',
 '/afs/cern.ch/user/r/rcurrie/cmtuser/GANGA/GANGA_Dev/external/figleaf/0.6/noarch',
 '/afs/cern.ch/user/r/rcurrie/cmtuser/GANGA/GANGA_Dev/external/paramiko/1.7.3/noarch/lib/python2.5/site-packages',
 '/afs/cern.ch/user/r/rcurrie/cmtuser/GANGA/GANGA_Dev/external/stomputil/2.4/noarch/python',
 '/afs/cern.ch/sw/lcg/releases/LCG_79/ROOT/6.04.02/x86_64-slc6-gcc49-opt/lib',
 '/afs/cern.ch/user/r/rcurrie/site-packages',
 '/afs/cern.ch/lhcb/software/releases/LBSCRIPTS/LBSCRIPTS_v8r6p1/InstallArea/python',
 '/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/lib/python27.zip',
 '/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/lib/python2.7',
 '/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/lib/python2.7/plat-linux2',
 '/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/lib/python2.7/lib-tk',
 '/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/lib/python2.7/lib-old',
 '/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/lib/python2.7/lib-dynload',
 '/afs/cern.ch/user/r/rcurrie/.local/lib/python2.7/site-packages',
 '/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/lib/python2.7/site-packages']
```
nothing which I think helps too much...

What change could have led to this?

**Comment by drmarkwslater** [comment]
This was shifted in #445 but I can't see why you're having problems - `testlib` is certainly a valid module now...

**Comment by milliams** [comment]
The move of the `GangaUnitTest.py` to `testlib` caused the imports of it to move from being relative to absolute.

I see `/afs/cern.ch/user/r/rcurrie/site-packages` in your list. Is this where you have installed some dependencies? Doing an 'editable install' to that directory or to `/afs/cern.ch/user/r/rcurrie/.local/lib/python2.7/site-packages` (which is some local install of Python you're using?) with `pip install -e .` from within the `ganga` dir would make it available to Python.

**Comment by rob-c** [comment]
apparently there is a ```coverage``` tool (and some others I don't recognise) in ```/afs/cern.ch/user/r/rcurrie/site-packages```

Should we rely on this package as an external if we're installing it via ```pip``` in order to get the tests working?

**Comment by rob-c** [comment]
I've not run the tests locally due to other problems and trusting that Jenkins working, now that I find there are bugs in Jenkins I'm investigating locally

**Comment by rob-c** [comment]
Erm, this starts to install all of the externals again in yet another location... Where are my externals now being accessed from?

**Comment by rob-c** [comment]
OK, for some reason I have to do this with every copy of Ganga I want to run the tests on... Isn't setting up the environment for Ganga supposed to be enough to be able to import the tools under ```Ganga.```?

**Comment by milliams** [comment]
The root problem is that you need to have the directory that contains `Ganga*` in Python `sys.path`. The standard way of working on a Python project is to install it locally within a virtualenv with `pip install -e` which essentially makes a symlink in the `site-packages` directory pointing at the local copy. You only have to run this once as it is a symlink, not a copy.

Do you really have multiple installs of Ganga locally?

**Comment by rob-c** [comment]
yes I have multiple installs as I end up working on different threads. Yes I know I could potentially have multiple branches in 1 install but this is my workflow. (Amongst other things they need a different env setup anyway)
OK, so that explains why my setup is the one with problems.
I think I'm going to revert to using ```PYTHONPATH=.:$PYTHONPATH``` as that seems to fix problems like this I've found

**Comment by milliams** [comment]
Indeed that will work and sounds like a sensible solution for now. The usual solution to multiple installs is to have one virtualenv for each. That way they can have their own environments easily.
