### ISSUE TITLE
losing subjob data

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#495]
this-morning I ran the following on a job which I forgot to be inaccessible to my current ganga setup:

```
jobs(326).subjobs
```

I received the appropriate Incomplete Object error and restarted into the correct Ganga environment (I was missing a plugin initially and so couldn't load the job)

Now I find that all of the subjob information associated with this job has been lost. I'm curious about this as the appropriate XML exist as well as ```subjobs.idx``` so working out why this is failing to load could be a bit tricky.

I'm a little concerned about this as it likely means the loading association of the subjobs object with a class is still a bit too fragile.

**Comment by milliams** [comment]
If you remove all the related index files, does it start working again?

**Comment by rob-c** [comment]
The index file is correct and contains the number of expected subjob entries and the subjobs exist in their own folders in the registry and in the workspace. I'll try and remove it to see if anything gets regenerated later.
I ran through and there aren't any missing, but even still I'd expect the SubJobXMLList to report some sort of failure if it had issues loading the number of subjobs.

I'll do some more investigating as part of 6.1.21 and hopefully construct a test to mock this. recreating it is easy, understanding this one may get difficult. (Or could just be a bad boolean check to see if the job actually has subjobs somewhere _trivial_)

**Comment by rob-c** [comment]
Huh, surprisingly that seems to be a workaround... Maybe this is due to the lazy loading index being badly modified when a job fails to load? I'll have to check that

**Comment by milliams** [comment]
That's what I suspected. I'm guessing that the act of trying to read the `.subjobs` element triggered a load from disk which failed at a tricky point, putting the two out of sync.
