### ISSUE TITLE
`object has no attribute 'splitlines'` on startup

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#499]
I get the following comments at the end of the release notes:

```
Attrib Err: 'int' object has no attribute 'splitlines'
Attrib Err: 'int' object has no attribute 'splitlines'
Attrib Err: 'int' object has no attribute 'splitlines'
Attrib Err: 'bool' object has no attribute 'splitlines
```

This is from the vanilla develop branch running on 6.1.20 for the first time. I don't think this is too harmless but it does also raise some concern from me that something has gone un-noticed.

(For completeness i was launching 6.1.20 for the first time by running a script rather than dropping into the IPython prompt as I know this can cause different code paths to be executed)

**Comment by milliams** [comment]
I haven't seen this myself. Does it happen if you run ganga a second time?

**Comment by rob-c** [comment]
no, and given it happens right after the release notes I wasn't expecting it to. I suspect this isn't a show stopper but is just an annoyance which has worked it's way in

**Comment by milliams** [comment]
If you wipe your gangadir and restart ganga, do the release notes along with this error reappear? Which plugins do you have enabled? Does it continue to appear if you run with no plugins enabled?

**Comment by rob-c** [comment]
Don't know haven't tested yet, will try and do this later

**Comment by drmarkwslater** [comment]
I have also seen this with GangaAtlas but have never had time to investigate. There's definitely an issue here but it doesn't seem to be serious.

**Comment by rob-c** [comment]
Think this got fixed at some point. I don't see this in develop. Can re-open if it crops up again
