### ISSUE TITLE
prepared state not cleaning up after itself

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#505]
Some users are reporting that the prepared state repository isn't correctly removing empty folders after the prepared state is removed (I assume count == 0).

I am also seeing some prepared states locally when I'm developing code which start to store infomation in elements non-zero in the database implying that some information in the prepared state tracking is therefore lost between different Ganga sessions.

I think these should probably be looked into in the neat future:
 - [x] Cleanup empty folders after they're emptied in prepared state
 - [x] Fix bug where repo doesn't address element zero in database correctly, or at least warn users

**Comment by egede** [comment]
@rob-c I wonder if this is partly related to the afs file system. If the directory has some of the funny `.__afs` files in it when we try to delete it, the deletion will fail.

**Comment by rob-c** [comment]
Possibly, but vava reported several hundred empty folders I think so I suspect that we're a little to blame. We should probably write a small sentinel to remove empty folders which haven't been touched in >24hr or something similar. Again, I think somewhat a nicety as this can be fixed with a quick 1 line command from the terminal.

**Comment by rob-c** [comment]
I think this may have been fixed due to recent changes but I'll review it for 6.1.23

**Comment by rob-c** [comment]
I'm planning to add a complex unittest to ensure that folders aren't accidentally created by things such lazy loading or job copying (I don't think they should be but better to be sure).
I'll look into this as part of 6.1.24 and close this issue then as appropriate.

**Comment by rob-c** [comment]
Work has been done in other issues such as #696 to fix this. Users seeing an excess of these folders also have the function `cleanUpShareDirs` within Ganga to cleanup after broken releases.
