### ISSUE TITLE
OutputData for LHCb jobs

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#511]
After having a quick look at the tests to make sure I'm not missing out on any functionality I don't know about I came across the OutputData class from the LHCb plugin.

Is this class particularly used by people and does anyone know if this works?

I was under the impression that the prescribed way of working is to have the inputfiles and outputfiles of the job populated with the new IGangaFile objects. Is this class somehow a remnant of Ganga pre6.0?

I'm tempted to remove this class if it's not used as I don't know if it is only kept around for backwards compatibility?

**Comment by drmarkwslater** [comment]
I don't know why it's there but a quick grep seems to show it's not being used in LHCb at least (though it is imported quite a bit). I'd say get rid of it 😄

**Comment by egede** [comment]
@drmarkwslater Agree

**Comment by alexanderrichards** [comment]
also agree

**Comment by mesmith75** [comment]
Removed the requisite file and mentions. Submitted pull request.

**Comment by milliams** [comment]
This is PR #576.

**Comment by alexanderrichards** [comment]
FYI @mesmith75 if in the commit message for your changes you use fixes/resolves/closes then the issue number #511 in this case then it will automatically link your PR to the issue and automatically close the issue when the PR is merged.

**Note** you can use different tenses of the key words i.e. fix fixes or fixed etc.

**Comment by milliams** [comment]
See https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by alexanderrichards** [comment]
closed by PR #576
