### ISSUE TITLE
Remove the reexec machinery

### ISSUE THREAD

**Issue by milliams** [ganga-devs/ganga#52]
We've discussed several times about getting rid of the ability for Ganga to re-exec itself. Historically this was needed in order to tweak `LD_LIBRARY_PATH` for linking against specific version of numpy but this is not relevant any more.

At the very least I would like to change the default to not re-exec but if possible I would like to completely remove the code from `bootstrap.py`. Given that LHCb has been running for years with `GANGA_NEVER_REEXEC` set without problems, I don't think there should be any trouble.

Any complaints?

**Comment by drmarkwslater** [comment]
Though I'm completely in favour of this I believe that in Atlas it's still needed. I could be wrong but I would need time to test it to be sure. Could we postpone this for 6.1.15 please?

**Comment by alexanderrichards** [comment]
nothing but support here :wink:
 I'm actually surprised that LHCb is running without this as I though that they needed this for some obscure reason.
One question, what was the reason that we needed the specific version of numpy? and why is that no longer an issue?

**Comment by milliams** [comment]
@alexanderrichards I think the reason was we were packaging our own externals which were compiled for a particular libc ABI and compiler version etc. When we do an 'import numpy' it needs to be able to look in the right place for support libraries otherwise you would get a crash. That is how it was explained to me anyway and I wasn't that convinced. Either way, I can't see a good reason for it any more. We no longer use numpy anywhere as it was only a dependency of matplotlib which was used in GangaPlotter.
@drmarkwslater Sure, we can postpone this if necessary.

**Comment by alexanderrichards** [comment]
excellent, get rid of it as soon as then

**Comment by milliams** [comment]
It looks like ATLAS, in its `PACKAGE.py` is giving access to external tools by actually appending the environment variable `PATH` so that when Ganga is re-execd it is running in an environment where doing a `subprocess.Popen` will find the tools.

This is a very heavy-handed way of running an external tool, especially when we can just pass the necessary environment to `Popen` with the `env` argument.

This goes hand-in-hand with my assertion that `PACKAGE.py` should only be used for Python packages, not for adding command-line tools to the `PATH` etc. Paths to tools should be applied at-use and not rely on `os.environ['PATH']` being set correctly.

**Comment by rob-c** [comment]
Is it possible to disable this by default in the config yet or do we still need some environment variabele to be passed by default?
If so can we change the cvmfs scripts to do this in future. Having this code always running concerns me as it causes horrible things like cProfile to give up the ghost.

**Comment by milliams** [comment]
This should be fixed by #420

**Comment by drmarkwslater** [comment]
Fixed by #420
