### ISSUE TITLE
Another deadlock found

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#520]
While doing the work on atexit and (by extension) the coverage reporting (see #510) I've found a definite hard lock up. It is probably made worse by the coverage now working properly and I've only seen it on the CI machines but I can certainly see the problem.

Basically, when you set a value on a `GangaObject` through `__set__` it goes through `_getWriteAccess` which in turn locks the repository, i.e. Obj Lock -> Reg Lock. Flushing however, goes the other way, i.e. Reg lock (in `_flush`) -> Obj Lock. If the timing's bad you get a lock up.

I would argue that `_getWriteAccess` isn't needed when you set a value on an object as if that object is being flushed, either the flusher or the setter has the object lock and the other one has to wait. 

This could also be the source of the other lockups I saw with the coverage but I didn't check the stack traces for those.

What do people think?

**Comment by milliams** [comment]
Indeed, I really don't like the usage of `_getWriteAccess` in the code base at the moment. I understand what it was there for originally (full transaction locks for registry objects so that can be shared across concurrently running sessions) but since we never release any of these locks, I'm not sure that it's even working as it should. This is another example of just how hard it is to have thread safety *and* process safety all at once.

There's a similar potential issue in `GangaObject.__get__` but that is mostly avoided since that should only be called if the object is *not* fully loaded and `flush` will only be called if it *is*.

**Comment by rob-c** [comment]
You need a lock on the file on disk once the object has been loaded I think but it makes more sense to get a writeLock when loading an object and not when modifying one already in memory imo.
We used to mark things dirty and flush them in incoherent ways and it makes more sense to get rid of the Registry locks in Object and have the registry request a file lock when an object is loaded and release one when it's unloaded.

**Comment by milliams** [comment]
If I remember correctly (and I might be wrong) we grab the session lock for *all* objects in the registry when loading them anyway. We're not being that fine-grained.

**Comment by rob-c** [comment]
@milliams I'm not sure I understand what you mean here. We get a lock on an object only when it's loaded else multiple sessions would never have worked.
I think we can drop the lock requests in GangaObject entirely if we're locking the object in the Registry
once they're loaded and we're currently not releasing any locks at runtime we can drop the write/read disk locks entirely for now if they're causing threading issues.

**Comment by milliams** [comment]
@rob-c I think I am agreeing with you :smile: If we write the lock file whenever an object is fully-loaded in the repository and then delete the lock file when we exit Ganga, I think we get most of the correct behaviour that we want.

**Comment by drmarkwslater** [comment]
Rightio - I'll remove this from the setter in #510 and check it works though maybe we should open another issue to properly remove/refactor the `_getWriteAccess` method properly?

**Comment by rob-c** [comment]
I think an issue to look into it would be helpful. I've some thoughts on what we could/should/might want to be doing with regard to releasing some objects. This is more important in some repos than others.

**Comment by drmarkwslater** [comment]
So after some messing around (mostly my fault for not reading the stack trace properly), I've found the following:

1. There was an additional lock up caused by a `_getReadAccess` call in `__deepcopy__` that was catching both Tasks and split jobs. This was actually the lock up I saw originally so the coverage is now running quite quickly and over all the tests. I'll clean the PR and all should be well.
2. I can't just blindly remove the `_getWriteAccess` call in the GangaObject setter as this caused other tests to fail. I don't know why but this definitely means we need to look at this more closely!
3. The root cause of this `_getWriteAccess` problem is that the `has_loaded` function is now `synchronised` (as of 3 days ago from #497). This means that a lock is acquired even if no loading needs to be done, hence the deadlock.

So, I would propose to remove the `synchronised` decorator for the `has_loaded` method and revisit this stuff ASAP to do a proper clean up and fix. What say others?

**Comment by rob-c** [comment]
Hmm, removing the ```synchronised``` for the ```has_loaded``` _should_ be safe 99% of the time.

I was wanting to be overly cautious about the way we use this as it accesses the list of known jobs which will change during the add or remove of a job object from the repository (I don't think we can iterate over lists as they're externally modified). As long as this is protected against modifications of _this_ type (i.e. wrap the call in a ```lock_transaction```) we can relax the ```synchronised``` part as I don't think the whole repo needs to be locked for this.

**Comment by rob-c** [comment]
#526 should address taking off the lock here. Which should get rid of some of the deadlocks.

**Comment by drmarkwslater** [comment]
Though I agree that this should be protected from being called at the same time as add or remove operations, I think in practise this is very unlikely to happen (we've survived without this up until now). I personally think just removing `@syncronised` rather than adding the additional transaction lock and other changes in #526 but we try to address this properly for 6.1.22/6.2.

**Comment by rob-c** [comment]
I'm not a fan of the 'not a problem before now' approach. Debugging this when it comes up (and I always suspect when) would be a nightmare. Best nip it in the bud by fixing the problem correctly, as I would argue #526 does.

We can't have a strong get/set lock without completely stripping away the read/write locks in the Registry as they'd get in the way too much. But I would like to see a get/set lock in the Registry eventually in the same way that we have a get/set lock in Objects. This would then allow us to do things like wrap this in a get lock rather than a set lock which is what we would expect to be correct.

**Comment by rob-c** [comment]
The transaction locks at this stage are effectively get locks with the advantage that we can bail-out of read/write scenarios where we know we don't need to request a file lock on disk as we are already using the object in memory.

**Comment by drmarkwslater** [comment]
Closing this as the discussion should be taken up in #528
