### ISSUE TITLE
Executable application on Dirac backend is losing arguments.

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#521]
The latest changes to the Executable application means that the arguments of a function are no longer passed onto the script. See example below.

```
Ganga In [22]: !cat test.sh
#!/bin/bash
echo Hello. Arguments should appear below.
echo $*
echo Bye. Arguments should have appeared above.
Ganga In [25]: j.application
Ganga Out [25]: 
 Executable (
   exe = File(name='/afs/cern.ch/user/u/uegede/test.sh',subdir='.'),
   hash = None,
   env = [],
   args = [a, b, c]  ,
   is_prepared = None
 )
```
which when run on the `Local` backend works correctly and gives
```
Ganga In [11]: j.peek('stdout','cat')
Hello. Arguments should appear below.
a b c
Bye. Arguments should have appeared above.
```
while with the `Dirac` backend the arguments are not passed on
```
Ganga In [32]: j.peek('Ganga_Executable.log','cat')
<<<<<<<<<< exe-script.py Standard Output >>>>>>>>>>

Hello. Arguments should appear below.

Bye. Arguments should have appeared above.
files on WN: ['pilot.cfg', 'job.info', 'jobDescription.xml', 'test.sh', '_input_sandbox_54.tgz', 'exe-script.py']
```

**Comment by rob-c** [comment]
I've a private PR for this once I am finished with some other work I'll commit it

**Comment by MannyMoo** [comment]
I've just come across this problem - any progress? The problem appears to be that in exe-script.py generated for the job it calls
rc = subprocess.call(exe_cmd, env=my_env, shell=True)
but exe_cmd is a list, so with shell=True only the first element of the list is used and the arguments are lost. So using shell=False would be the fix, but I don't know how this file is generated. The Executable app with LSF backend works fine as it uses shell=False.

**Comment by MannyMoo** [comment]
I found the file to change and created the above pull request. Obviously it should be rejected if there's a good reason to be using shell=True.
