### ISSUE TITLE
Still loading jobs for remove

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#529]
I know this is a minor bug but we're still loading jobs un-necessarily for removal.

If a job is 'new' I wouldn't expect to need to load it from disk to remove it. (I would argue the same for 'completed' and 'failed').

If a job is in a 'submitted', or 'running' state then it's probably a good idea to allow the load due to needing to tell the backend to kill/remove the job as well.

I only mention this as I have new jobs I can't remove because I can't load them if I don't load the correct plugin. It's annoying but not the end of the world

**Comment by egede** [comment]
@rob-c Don't we have some option that will remove the outputfiles when the job is removed? If that is the case, you do need to load the job to get that information.

**Comment by rob-c** [comment]
I think we make use of the autoremove setting to remove all files of a certain type when we remove a job.

Hmmm, you may well be correct that this is triggering it for the 'completed' and 'failed' jobs. It's unclear what is causing it for the 'new' job but I just wanted to remove a bunch of jobs I'd constructed but not submitted and was confronted with errors in loading the XML which seemed counter intuitive.

**Comment by drmarkwslater** [comment]
On a tangential note, I've been thinking for a long time that all plugins should be loadable at the same time, i.e. GangaDirac:GangaLSST:GangaLHCb:GangaAtlas. You may get problems submitting to some of these if they need different environments but I feel that just having them in the namespace should be OK.

**Comment by rob-c** [comment]
There are reasons why this can't be done atm, but yes my problem would go away if I could switch between LHCbDirac and DIRAC by changing a boolean for instance.
Do we still lock the configuration system after startup after all of the recent changes?

**Comment by drmarkwslater** [comment]
Not sure. No more than we did previously but I think the [Configuration] section might be fixed...
