### ISSUE TITLE
Ganga seems to crash on lxplus when disk write access expires during submission of subjobs

### ISSUE THREAD

**Issue by KonstantinSchubert** [ganga-devs/ganga#531]
It seems that Ganga crashes if the grid proxy expires while it is submitting subjobs. I have observed this on lxplys. I am about 80% sure that this was the reason, but please let me know if you think that can't be the case. Then I will try to verify. I cannot say if this happens every time. 

Unfortunately I haven't had time to dig into the source, so I cannot say if there is already a mechanism to catch an expired grid proxy.

**Comment by drmarkwslater** [comment]
I think there **used** to be a check for the lifetime of a proxy before submission begins but maybe that's disappeared over recent weeks. How many subjobs were you submitting and how long was it taking?

**Comment by egede** [comment]
@KonstantinSchubert What do you mean by that Ganga is crashing? That the submission aborts with an Exception? Or that the whole python process is crashing?

**Comment by KonstantinSchubert** [comment]
The whole python process. :)

**Comment by rob-c** [comment]
@KonstantinSchubert Are you certain that this is not due to an afs token expiring? I can't think of a sensible way that a grid proxy can crash the python process

**Comment by KonstantinSchubert** [comment]
You are right, it might have been the AFS token. Apologies.

I am sorry, when I got that error I just rage-quit :D

Later I went back and submitted the issue.

Anyways, since submitting jobs can take longer than the expiration time of
a fresh  AFS token, there should probably be a mechanism that prevents
ganga from crashing in this case...

**Comment by rob-c** [comment]
@KonstantinSchubert What version of Ganga are you using to submit your jobs? and how many subjobs are you getting per job in this case?
Are you doing something unusual in the way you construct your jobs?
I'm able to submit several hundred LHCb subjobs in well under 24hr which is the afs token lifetime.

**Comment by KonstantinSchubert** [comment]
Hi Robert,

Thank you for your help.

I am using the newest version, v601r20.
I am submitting four jobs, one for each year of data taking 2011/2012 and
magnet orientation.
I am getting about 300 subjobs per job, which means I get 1200 subjobs to
process all data.
However, there will obviously be cases where I will need to submit even
more jobs.

Anyway, I feel like this leads us a bit away from the core issue. :)
There are many reasons why somebody might be running Ganga 24 hours after
obtaining the last AFS token.
It shouldn't happen that Ganga crashes and nukes all subjobs, even the
running and submitted ones, like it did for me.

**Comment by rob-c** [comment]
@KonstantinSchubert The advise has always been to run in a screen session with a token valid for more than 24hr or with another process looking after the token validity as far as I'm aware?

Yes ganga did have some way of automatically looking after this (a long, long time ago) but as far as I'm aware this hasn't been working for whatever reason.

**Comment by KonstantinSchubert** [comment]
I guess that it might really be beyond Gangas concerns to make sure the file system it is running on does not stop existing :laughing: 

Probably the bigger issue is HOW it failed for me: It deleted all subjobs, set `application` to `Executable` and `backend` to `Localhost`.

**Comment by egede** [comment]
@rob-c Are you still missing something in synchronising the status of the jobs in the index files? How else can the application and backend be reset to the default?

**Comment by rob-c** [comment]
@KonstantinSchubert Try loading the jobs from disk again have they become corrupt or has the index become corrupt? (type job.backend for each effected (sub) job)
@egede I think this has been fixed in 6.1.21 work, I put in a PR but I forget when now

**Comment by KonstantinSchubert** [comment]
@rob-c I have deleted them now, but I will do so it when it happens again.

**Comment by rob-c** [comment]
I think we can open another issue if we plan to support extending kerberos tokens automatically for afs etc, but for the moment we don't (or this has been broken for a significantly long time).

As for jobs appearing broken this has been fixed at some point by removing the master_index which is corrupt by definition if shutdown didn't occur. There is another issue open to improve this
