### ISSUE TITLE
Index cache not saved correctly for box objects

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#536]
If I do

```
box.add(Dirac(),'Test')
```
and then quit Ganga, I see
```
ERROR    Failed to Shutdown Repository: box !!! please check for stale lock files
INFO     Stopping Job processing before shutting down Repositories
INFO     Shutting Down Ganga Repositories
INFO     Registry Shutdown
ERROR    RegistryAccessError: The object #1 in registry 'box.metadata' is not fully loaded and the registry is disconnected! Type 'reactivate()' if you want to reconnect.
ERROR    Trying to Shutdown cleanly regardless
```
When I subsequently start Ganga, the name of the box object is lost, but it works anyway with a warning.
```
Ganga In [1]: box['Test']
Ganga Out [1]: WARNING  Incorrect index cache of 'box' object #3 was corrected!

 Dirac (
   status = None,
   actualCE = None,
   settings = [CPUTime],
   normCPUTime = None,
   extraInfo = ,
   diracOpts = ,
   statusInfo = ,
   id = 3
 )

[13:50:25]
```

**Comment by rob-c** [comment]
Is this working on the latest develop or is the a bug specific to this repo?

**Comment by egede** [comment]
@rob-c It fails on a blank repository in 6.1.20

**Comment by rob-c** [comment]
I seem to see the same behaviour, I'll see if it's obvious if this can be fixed next week ahead of 6.1.21 but it may slide for other work

**Comment by bifani** [comment]
I just want to report that the same issue happens with jobs


    [sb@eprexb GANGA ~/]$ ganga

    *** Welcome to Ganga ***
    Version: 6.1.20
    Documentation and support: http://cern.ch/ganga
    Type help() or help('index') for online help.

    This is free software (GPL), and you are welcome to redistribute it
    under certain conditions; type license() for details.

    INFO     reading config file /cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r20/install/ganga/python/GangaLHCb/LHCb.ini
    INFO     reading config file /cvmfs/lhcb.cern.ch/lib/GangaConfig/config/6-0-8/GangaLHCb.ini
    INFO     reading config file /home/sb/Work/RD/Ganga/Modules/gangarc
    WARNING  Removing session eprexb.ph.bham.ac.uk.14.24_Friday_27_May_2016.PID.22505.session because of inactivity (no update since 2728.0 seconds)
    ERROR    unknown options [LHCb]ignore_version_check

    [16:24:32]
    Ganga In [1]: box
    Ganga Out [1]:
    Registry Slice: box (4 objects)
    --------------
    id |                type |                                    name |    application
    ----------------------------------------------------------------------------------------
    0 |         LHCbDataset |                                         |
    1 |         LHCbDataset |                                         |
    2 |         LHCbDataset |                                         |
    3 |         LHCbDataset |                                         |

    [16:24:35]
    Ganga In [2]: jobs
    Ganga Out [2]:
    Registry Slice: jobs (4 objects)
    --------------
    fqid | subjobs |                                           name |    status | application | backend | backend.actualCE
    ----------------------------------------------------------------------------------------------------------------------------
       0 |         |                                                |       new |  Executable |Localhos |
       1 |         |                                                |       new |  Executable |Localhos |
       2 |         |                                                |       new |  Executable |Localhos |
       3 |         |                                                |       new |  Executable |Localhos |

    [16:24:36]
    Ganga In [3]: jobs(0)
    WARNING  Incorrect index cache of 'jobs' object #0 was corrected!

     Job (
       comment = ,
       parallel_submit = False,
       outputdir = /home/sb/Work/RD/Ganga/Dir/workspace/sb/LocalXML/0/output/,
       id = 0,
       status = new,
       do_auto_resubmit = True,
       name = Bd2KstEE 7TeV VC MD R14S21r1 LPT CL11,
       inputdir = /home/sb/Work/RD/Ganga/Dir/workspace/sb/LocalXML/0/input/,
       outputsandbox = []  ,
       inputfiles = [ LocalFile (
       namePattern = '',
       compressed = False,
       localDir = ''
     )]  ,
       backend =    Dirac (
         status = None,
         actualCE = None,
         settings = [CPUTime],
         normCPUTime = None,
         extraInfo = ,
         diracOpts = ,
         statusInfo = ,
         id = None
       ) ,
       subjobs = Registry Slice: jobs(0).subjobs (0 objects)
     ,
       application =    DaVinci (
         is_prepared = ShareDir(name='conf-860f73fe-0099-4e64-99d4-284c321778f5',subdir='.'),
         extraopts = None,
         newStyleApp = False,
         args = [-T]  ,
         package = Phys,
         platform = x86_64-slc6-gcc49-opt,
         version = v36r2,
         setupProjectOptions = ,
         masterpackage = None,
         user_release_area = /home/sb/RD/cmtuser,
         optsfile = [ File (
       name = '/disk/lustre/lhcb/simone/RD/DaVinci/Options/Bd2KstEE_CL11_LPT.py',
       subdir = '.'
     )]
       ) ,
       inputdata =    LHCbDataset (
         depth = 0,
         treat_as_inputfiles = False,
         persistency = None,
         files = [4561 Entries of type 'DiracFile'] ,
         XMLCatalogueSlice =      LocalFile (
           namePattern = ,
           compressed = False,
           localDir =
         )
       ) ,
       metadata = {} ,
       outputfiles = [ DiracFile (
       defaultSE = '',
       namePattern = 'DVNtuples.root',
       guid = '',
       remoteDir = '',
       compressed = False,
       localDir = '',
       lfn = '',
       failureReason = '',
       locations = []  ,
       subfiles = []
     )]  ,
       postprocessors = [] ,
       info =    JobInfo (
         monitoring_links = []  ,
         uuid = d083a6e7-aca7-4946-8608-d1d04079942d,
         submit_counter = 0,
         monitor =None
       ) ,
       splitter =    SplitByFiles (
         filesPerJob = 100,
         maxFiles = None,
         bulksubmit = False,
         ignoremissing = True
       ) ,
       inputsandbox = []  ,
       outputdata =None,
       time =    JobTime (
         timestamps =
             Time (UTC)   Status

    2016/05/27 14:02:24 - submitting
    2016/05/27 14:21:52 - new
       )
     )

    [16:25:15]
    Ganga In [4]: jobs
    Ganga Out [4]:
    Registry Slice: jobs (4 objects)

        fqid | subjobs |                                           name |    status | application | backend | backend.actualCE

       0 |         |          Bd2KstEE 7TeV VC MD R14S21r1 LPT CL11 |       new |     DaVinci |   Dirac |             None
       1 |         |                                                |       new |  Executable |Localhos |
       2 |         |                                                |       new |  Executable |Localhos |
       3 |         |                                                |       new |  Executable |Localhos |

**Comment by rob-c** [comment]
I'd recommend trying to use the code in develop as a test, slightly more concerned if this is happening in the

**Comment by rob-c** [comment]
Can you try removing master.idx from the Registry and restart. It may be slightly slower but will regenetate the cached indexes

**Comment by bifani** [comment]
can you give me details on how to access the develop area?
would that work via cvmfs or should I use lxplus?

remove master.idx ?
do you mean this one "repository/sb/LocalXML/6.0/jobs/master.idx"?

**Comment by rob-c** [comment]
As for the master.idx file,  yes, that one.

To access the latest evelop code I advise installing Ganga from the code if you're keen to try the latest code.  I don't know anywhere we provide the develop code pre-installed. ( http://ganga.readthedocs.io/en/latest/UserGuide/InstallAndBasicUsage.html)

**Comment by bifani** [comment]
I removed the master.idx file and restarted ganga
The job for which the index cache was already corrected appeared OK
I then forced correcting the index cache of a box object and quit, but I got the usual error

    ERROR    Failed to Shutdown Repository: box !!! please check for stale lock files
    INFO     Stopping Job processing before shutting down Repositories
    INFO     Shutting Down Ganga Repositories
    INFO     Registry Shutdown
    ERROR    RegistryAccessError: The object #0 in registry 'box.metadata' is not fully loaded and the registry is disconnected! Type 'reactivate()' if you want to reconnect.
    ERROR    Trying to Shutdown cleanly regardless

Restarting ganga once more presented the box object with no name, but the job was still OK

**Comment by rob-c** [comment]
I suspect the box repo problem is different but it's good to know you're seeing a problem I've recently fixed with regards to the master index.

**Comment by bifani** [comment]
btw, the master.idx file got recreated
I think that's normal but I want to double-check

**Comment by rob-c** [comment]
Yes, we expect the file to be regenerated. Although in 6.1.21 onwards it will deleted after startup and only generated on a successful shutdown.

**Comment by bifani** [comment]
If I run the dev version of ganga from /cvmfs/ganga.cern.ch and try something as simple as

    Ganga In [1]: box.add(Dataset(),'Test')
    Ganga In [2]: box
    Registry Slice: box (1 objects)

    id |                type |                                    name |    application
    ----------------------------------------------------------------------------------------
    0 |        EmptyDataset |                                    Test |

I still get the same problem when quitting

    ERROR    Failed to Shutdown Repository: box !!! please check for stale lock files
    INFO     Stopping Job processing before shutting down Repositories
    INFO     Shutting Down Ganga Repositories
    INFO     Registry Shutdown
    ERROR    RegistryAccessError: The object #0 in registry 'box.metadata' is not fully loaded and the registry is disconnected! Type 'reactivate()' if you want to reconnect.
    ERROR    Trying to Shutdown cleanly regardless

and at restart the box object name is lost

    Ganga In [1]: box
    Registry Slice: box (1 objects)

    id |                type |                                    name |    application
    ----------------------------------------------------------------------------------------
    0 |        EmptyDataset |                                         |

**Comment by rob-c** [comment]
@bifani I didn't think we actually have a dev version of Ganga on cvmfs so I'm assuming you're running on some form of 6.1.20
@drmarkwslater Is there a develop version on cvmfs?

**Comment by drmarkwslater** [comment]
Yep and that should be up to date now (as of this morning at ~9:30am anyway, the CVMFS refresh should have kicked in as well). If you run as `/cvmfs/ganga.cern.ch/Ganga/install/ganga/bin/ganga` you get the latest version of develop.

**Comment by bifani** [comment]
yes, indeed

    *** Welcome to Ganga ***
    Version: 6.1.20

I followed the CVMFS instructions at http://ganga.readthedocs.io/en/latest/UserGuide/InstallAndBasicUsage.html because this was the easiest way for me
Shall I try the LHCb instructions for an ‘in development’ release instead?

**Comment by bifani** [comment]
I run ganga as

    /cvmfs/ganga.cern.ch/runGanga.sh

which corresponds to

    /cvmfs/ganga.cern.ch/Ganga/install/LATEST/bin/ganga

It this the correct way to pick up the dev?

**Comment by drmarkwslater** [comment]
Ah - that's a bit of a problem. This script points at the latest **release** not the develop branch. You should run with:
```
/cvmfs/ganga.cern.ch/Ganga/install/ganga/bin/ganga
```
and that will be the develop branch 😄

**Comment by rob-c** [comment]
@drmarkwslater If we're going to start supporting the develop branch are we best printing the git revision at startup to make sure we're not getting confused about what has been pulled in via cvmfs?

**Comment by bifani** [comment]
I am not sure that worked though 

    [sb@eprexb GANGA ~/Work]$ /cvmfs/ganga.cern.ch/Ganga/install/ganga/bin/ganga

    *** Welcome to Ganga ***
    Version: 6.1.19

    Ganga In [1]: box.add(Dataset(),'Test')

    Ganga In [2]: box
    Ganga Out [2]:
    Registry Slice: box (2 objects)

       id |                type |                                    name |    application
    ----------------------------------------------------------------------------------------
        0 |        EmptyDataset |                                         |
        1 |        EmptyDataset |                                    Test |

    Ganga In [3]:
    Do you really want to exit ([y]/n)?

    ERROR    Failed to Shutdown Repository: box !!! please check for stale lock files
    INFO     Stopping Job processing before shutting down Repositories
    INFO     Shutting Down Ganga Repositories
    INFO     Registry Shutdown
    ERROR    RegistryAccessError: The object #1 in registry 'box.metadata' is not fully loaded and the registry is disconnected! Type 'reactivate()' if you want to reconnect.
    ERROR    Trying to Shutdown cleanly regardless

**Comment by drmarkwslater** [comment]
@rob-c I wasn't planning on **supporting** it as such but this is certainly the easiest way to allow someone to try the develop branch. If we want to keep that as an option then I can have it automatically update the branch every night on the CVMFS machine and put the git revision in as well.

**Comment by rob-c** [comment]
Just put in #554 which should fix this issue. I saw it and thought it should be a quick fix, thankfully I as right.
