### ISSUE TITLE
Dont ask for grid certificate until actually required

### ISSUE THREAD

**Issue by will-cern** [ganga-devs/ganga#539]
This is a bit of a request more than anything: at the moment it's a shame that ganga asks for your grid certificate even if you aren't submitting to the grid. Would it be possible to make ganga delays asking for a grid certificate until it actually tries to submit to the grid. For submitting to condor or lsf, it is not needed.

This is a pretty low priority request though

Thanks
Will

**Comment by rob-c** [comment]
This is being looked into my @drmarkwslater with his work to not enable the GLITE system unless a user has properly configured the voms part of the configuration system. #486

If you happen to use both GLITE and Condor for instance then you'll have to wait for the new credentials branch to be merged in 6.2 at some stage which will handle the management credentials in a better way.

**Comment by will-cern** [comment]
I would like to come back to this ticket please. It seems we will have this requirement to load the GLITE middleware setup for ganga to work. In fact, I tried disabling it in my gangarc config file by changing the GLITE_ENABLE to False, but then that lead to the error below when starting ganga.

Is there a way to get the config file in a state that allows us to use ganga without these backends? It might even speed up the startup time?

ERROR    problems with loading Plugin GangaAtlas
ERROR    Reason: ApplicationConfigurationError: Could not get nickname from voms proxy. Please register nickname to ATLAS VO via

   https://lcg-voms.cern.ch:8443/vo/atlas/vomrs
      [Member Info] -> [Edit Personal Info]

Then you can use the new naming convention "user.nickname" which should be shorter than "userXY.FirstnameLastname". 
PluginError:  ('Failed to load plugin: GangaAtlas. Ganga will now shutdown to prevent job corruption.',)
