### ISSUE TITLE
Cannot load subjob index

### ISSUE THREAD

**Issue by KonstantinSchubert** [ganga-devs/ganga#541]
I tried to resubmit a subjob job using 

`job(..).subjobs(...).resubmit()`

Instead of resubmitting, ganga gave me an error message like this:

```
Ganga.Core.GangaRepository         : ERROR    CANNOT LOAD SUBJOB INDEX: 82. Reason: XMLFileError: from-file error (<type 'exceptions.TypeError'>:object of type 'NoneType' has no len())
Ganga.GPIDev.Lib.Job               : ERROR    JobStatusError:  (AttributeError("'NoneType' object has no attribute 'time'",),)
Ganga.Utility.logging              : WARNING  ---------- error in user/extension code ----------
Ganga.Utility.logging              : WARNING  Traceback (most recent call last):
Ganga.Utility.logging              : WARNING    File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py", line 618, in updateStatus
Ganga.Utility.logging              : WARNING      self.time.timenow(str(newstatus))
Ganga.Utility.logging              : WARNING    File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/python/Ganga/GPIDev/Lib/Job/JobTime.py", line 170, in timenow
Ganga.Utility.logging              : WARNING      state] = self.sjStatList_return(state)
Ganga.Utility.logging              : WARNING    File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/python/Ganga/GPIDev/Lib/Job/JobTime.py", line 182, in sjStatList_return
Ganga.Utility.logging              : WARNING      if isinstance(sjs.time.timestamps[status], datetime.datetime):
Ganga.Utility.logging              : WARNING  AttributeError: 'NoneType' object has no attribute 'time'
Ganga.Utility.logging              : WARNING  --------------------------------------------------
```

Ganga is now unresponsive and keeps printing similar error messages over and over.

Is there a way to fix this or should I delete everything and start from scratch again?
If there is anything I can do to help and debug this, I will be happy to do so.

**Comment by rob-c** [comment]
@KonstantinSchubert Can you please try again with the latest ganga version and report if this problem persists? (I think this has been fixed since)

Can you please confirm what backend you're using, this makes debugging this a _lot_ easier for us.

**Comment by KonstantinSchubert** [comment]
This is the Dirac backend. Sorry for not reporting this.

I will try with the latest version.

**Comment by KonstantinSchubert** [comment]
I switched to the newest version and called:
```
for job in jobs(1).subjobs:
    if job.status=="killed":
        job.resubmit()
```
the output is:

**Comment by rob-c** [comment]
Your job has become corrupt by the looks of it.
Can you have a look in the following folder:
```~/gangadir/repository/*/LocalXML/6.0/jobs/0xxx/1```

If you have ```~/gangadir/repository/*/LocalXML/6.0/jobs/0xxx/1/data~``` can you try copying it to ```~/gangadir/repository/*/LocalXML/6.0/jobs/0xxx/1/data``` to recover your job.

Are you forcing Ganga to quit? This will likely explain your corrupt indexes and potentially the job XML files.

**Comment by KonstantinSchubert** [comment]
Sorry, I have since deleted my gangadir and I haven't seen the error again.

I am sorry I wasn't more helpful with debugging this.
