### ISSUE TITLE
ganga athena not working if joboption in package share directory

### ISSUE THREAD

**Issue by will-cern** [ganga-devs/ganga#542]
Hi again,

If I have a joboption in a package share directory, I can run it like this from any location:

athena MyPackage/jobOptions.py

But with "ganga athena" it is unable to find the joboptions. Can ganga athena be taught how to find the joboptions? It's supposed to look in the $JOBOPTSEARCHPATH for joboptions

This is a low priority improvement, but I hope it's a straightforward one, since you just need to iterate over the locations given in $JOBOPTSEARCHPATH env var.

Cheers
Will

**Comment by drmarkwslater** [comment]
@will-cern I'm having trouble recreating this behaviour for athena. Not that it's a problem in general as I can easily just get Ganga to go over the search path anyway but out of interest, how do you get the 'share' directory added to it? And do you need the additional `MyPackage` in the dir? Basically, what I'm asking is if you can send me a tar ball of a working test area and instructions on how to setup it up that would be great 😄  I've gone through the following and it doesn't seem to work:

https://twiki.cern.ch/twiki/bin/viewauth/AtlasComputing/SoftwareTutorialxAODAnalysisInAthena#8_An_example_of_skimming_events

**Comment by drmarkwslater** [comment]
@will-cern Nevermind - just found a rather important part here:

https://twiki.cern.ch/twiki/bin/viewauth/AtlasComputing/SoftwareTutorialxAODAnalysisInAthena#Interlude_Location_of_joboptions

Apologies for the noise - will hopefully get this sorted ASAP!
