### ISSUE TITLE
Import missing in Grid.py for CREAM backend

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#55]
>> Good afternoon,
>>
>> I have tried using Ganga-6-1-6-hotfix1 from cvmfs:
>>
>> /cvmfs/ganga.cern.ch/Ganga/install/LATEST/bin/ganga
>>
>> to submit jobs to Manchester Analysis Facility but I get the error
>> below. Could you please have a look?
>>
>> Thank you,
>> Rustem
>>
>> ---------------------------------------------------------------------------------------------------------------------
>> *** Welcome to Ganga ***
>> Version: Ganga-6-1-6-hotfix1
>> Documentation and support: http://cern.ch/ganga
>> Type help() or help('index') for online help.
>>
>> This is free software (GPL), and you are welcome to redistribute it
>> under certain conditions; type license() for details.
>>
>> Ganga.Utility.Config               : INFO     reading config file
>> /afs/hep.man.ac.uk/u/rustem/.gangarc
>> Ganga.GPIDev.Lib.Job               : INFO     submitting job 3251
>> Ganga.GPIDev.Lib.Job               : INFO     job 3251 status changed
>> to "submitting"
>> Ganga.Lib.Executable               : INFO     Preparing Executable application.
>> Ganga.Lib.Executable               : INFO     Created shared
>> directory: conf-30cf5d3b-450d-4f1b-b234-d4ea6cf07192
>> Ganga.GPIDev.Adapters              : INFO     Sending file object
>> /bin/bash to shared directory
>> Ganga.GPIDev.Lib.Job               : INFO     Preparing subjobs
>> Ganga.Lib.Executable               : INFO     Submitting a prepared
>> application; taking any input files from
>> conf-30cf5d3b-450d-4f1b-b234-d4ea6cf07192
>> Ganga.Lib.LCG                      : WARNING  CREAM CE assigment from
>> AtlasCREAMRequirements failed.
>> Ganga.GPIDev.Lib.Job               : WARNING  ---------- error in
>> user/extension code ----------
>> Ganga.GPIDev.Lib.Job               : WARNING  Traceback (most recent call last):
>> Ganga.GPIDev.Lib.Job               : WARNING    File
>> "/cvmfs/ganga.cern.ch/Ganga/install/LATEST/python/Ganga/GPIDev/Lib/Job/Job.py",
>> line 1592, in submit
>> Ganga.GPIDev.Lib.Job               : WARNING      r =
>> self.backend.master_submit( rjobs, jobsubconfig, jobmasterconfig)
>> Ganga.GPIDev.Lib.Job               : WARNING    File
>> "/cvmfs/ganga.cern.ch/Ganga/install/LATEST/python/Ganga/Lib/LCG/CREAM.py",
>> line 1086, in master_submit
>> Ganga.GPIDev.Lib.Job               : WARNING      if not
>> grids['GLITE'].cream_proxy_delegation(self.CE):
>> Ganga.GPIDev.Lib.Job               : WARNING    File
>> "/cvmfs/ganga.cern.ch/Ganga/install/LATEST/python/Ganga/Lib/LCG/Grid.py",
>> line 914, in cream_proxy_delegation
>> Ganga.GPIDev.Lib.Job               : WARNING      t_expire = time.time() + \
>> Ganga.GPIDev.Lib.Job               : WARNING  NameError: global name
>> 'time' is not defined
>> Ganga.GPIDev.Lib.Job               : WARNING
>> --------------------------------------------------
>> Ganga.GPIDev.Lib.Job               : ERROR    global name 'time' is
>> not defined ... reverting job 3251 to the new status
>> Ganga.GPIDev.Lib.Job               : INFO     job 3251 status changed to "new"
>> JobError: global name 'time' is not defined
>> ---------------------------------------------------------------------------------------------------------------------

**Comment by drmarkwslater** [comment]
This should be a trivial fix - I'll do it ASAP!

**Comment by rob-c** [comment]
@drmarkwslater  I'm aiming for a deadline of 3pm UK Monday to tag 6.1.14 would you be able to verify if this has been fixed by then?
Thanks,
Rob

**Comment by drmarkwslater** [comment]
@rob-c Fix in. Please feel free to tag!
