### ISSUE TITLE
Running tests in different envs

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#557]
Hi all,

Recently a minor(ish) bug had cropped up which effected users not running the bash shell as their environment.
I think the actual bug was due to different behaviour of bash when executed atop another bash session vs bash being executed atop a different shell. (I've not confirmed this but it seem to fit)

I think it would be a good idea to run the tests at least nightly atop a different shell such as 'zsh' or 'tclsh' to avoid the possibility of us being effected by assumptions in the code which may be not be valid.
e.g. executing a bash script within the same (non-bash) shell as the environment.

What are people's thoughts on this?

Thanks,

Rob

**Comment by alexanderrichards** [comment]
:+1: Why not

**Comment by milliams** [comment]
It's possible to run the tests using a matrix configuration where it does each of the combinations (python versions, environments etc.). I'm not completely clear how I can change the shell that Jenkins uses but I can look into it.

**Comment by rob-c** [comment]
@milliams Is it difficult to setup in Jenkins, or should we just look into launching the commands in the different shells via a bash script?

**Comment by milliams** [comment]
We do currently start the tests with an explicit `bash` call so we can easily switch this out. Thinking about it, making it configurable by jenkins should be simple. My main worry is that this will double or triple the test run time for quite a minor gain.

**Comment by rob-c** [comment]
I would rather drop to running it this way nightly. If it's clear our primary support is for running on bash I don't think we'd lose too many people from following us as long as we're testing on any other environments just to make sure things work. I think I've got a user seeing problems again with bash vs something else which they're trying to track down.

**Comment by alexanderrichards** [comment]
> My main worry is that this will double or triple the test run time for quite a minor gain.

Yes this is the main problem with doing it but as rob says perhaps it's ok in the nightlies? We would have to see if this becomes a problem. Don't forget that this will then multiply as we scale up the number of tests.

As python is **fairly** platform agnostic (or at least things can usually be done in such a way) presumably we are seeing these problems when we are using some shell feature through something like an os.system right? 

Perhaps therefore the correct solution (which probably should be a separate issue) is to ensure that Ganga is as POSIX compliant as possible.

**Comment by rob-c** [comment]
I think it makes sense to have multiple nightly tests if this starts taking too long with each test running in a different env.
The main difficulty I imagine is if plugins support different envs. I can think of a few solutions but they all require a little bit of work.

I'm tempted to run the tests myself locally on zfs just to be certain nothing crops up.

**Comment by egede** [comment]
bash seems to rule the world now.  Low priority.
