### ISSUE TITLE
Problems with Dataset for LHCb users

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#561]
LHCb users are reporting problems with the Dataset class (which probably shouldn't be generated anyway)

```
/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r20/install/ganga/python/Ganga/GPIDev/Lib/Dataset/GangaDataset.py
in getFileNames(self)
     77         names = []
     78         for i in self.files:
---> 79             if hasattr(i, lfn):
     80                 names.append(i.lfn)
     81             else:
```
I suspect this is a quick fix to put in the quotations.

**Comment by drmarkwslater** [comment]
Entirely correct. This is my bad. Fixed by #562.

**Comment by rob-c** [comment]
I'm more keen to explore why/how an LHCb user is getting a GangaDataset object (or why the method is being called). Is/Was this due to inheritance and LHCbDataset passing off some tasks to the baseclass or is this a genuine bug?

**Comment by drmarkwslater** [comment]
This is inherited from `GangaDataset` and is called in a few places so it's just a genuine bug that we hadn't picked up.

**Comment by rob-c** [comment]
I'd be happy (keen) to replace functions in LHCbDataset with GangaDataset. There's no need to duplicate functionality but is GangaDataset supposed to know about LFN?
If GangaDataset is written to support LFNs then I say gut LHCbDataset and only have it add the book-keeping extensions which are LHCb specific, this reduces the long term support effort.

**Comment by drmarkwslater** [comment]
`GangaDataset` can include any of the Ganga Core file types (in theory) so needs to know about lfns to a certain extent. If it makes sense to shift more stuff from `LHCbDataset` to `GangaDataset` that certainly makes life easier.

**Comment by egede** [comment]
@drmarkwslater But `DiracFile` is not a Ganga Core file type. So do we create a problematic dependency here?

**Comment by drmarkwslater** [comment]
@egede I would argue that GangaDirac is basically Core anyway, but in any case, these dataset objects (or GangaDataset at least) is very much just an extended list for holding GangaFiles. All the heavy lifting is done by the files themselves so there's no **dependency** as such, just an awareness is needed if that makes sense, (e.g. GangaDataset will never really **do** anything with the LFNs like show replicas, but it just needs to know that these are the names some files use instead of namePattern).

I suppose this particular bit of code could also be shifted to the Files themselves though...

**Comment by rob-c** [comment]
What does the GanagDataset want exactly in this method?
In my mind it should construct the filename from the namePattern and the remoteDir looking at the attributes most files have in common.
LocalFile has (by definition) the same remoteDir as localDir. MassStorageFile would return the correct filename using this. And, DiracFile should (I'll check now) have the remoteDir as the path to the file in the LFN so I don't think there is any need to have anything special here (if the files are all using the same standard attributes)

**Comment by drmarkwslater** [comment]
@rob-c This leads weight to the argument that the `GangaFile` should be asked how to do this rather than just assuming `namePattern`/`lfn`. I would be happy with that.
