### ISSUE TITLE
Potential performance fix

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#565]
I'm trying to do some dev work/testing on AFS and handling large objects is extremely expensive.

In paticular I'm talking about XML files we generate which are ~90Mb or so in size.

I suspect that a lot of the bottleneck in automatic flushes come from the pause of waiting for the file transactions to complete.

Would it make sense to introduce some locking queue of 1 thread which allows us to queue writing the XML string to disk and then release objects to carry on doing whatever the user/monitoring system wants to do with it?

Locking large jobs for a very long transaction like this on AFS is slightly annoying from an end-user perspective.

**Comment by egede** [comment]
@rob-c Should we rather try to address why we write 90 Mb XML files which are highly repetitive? I assume this object contains an infinite list of LFNs with almost no difference between them. Can we compress the object in a transparent way? I would not be surprised if the size went down by a factor 100.

**Comment by drmarkwslater** [comment]
I suppose one thing to look into in the respect, if we're **certain** it's just the file size and I/O that's the problem, is to write the files using `gzip`. That'll bring the I/O required down massively but change very little of the code. Just a thought 😄

**Comment by rob-c** [comment]
@egede Yes I agree writing a 90Mb XML file is bad. But we now have the problem that if we want to modify this the new format of whatever data we write to disk has to be able to parse both the old XML and a new schema.

Ideally I'm thinking of storing the dataset itself in another file probably in some compressed pickle format alongside the main XML and having a reference to it stored in the Schema.
That way old jobs can be read in and if they're modified we can simply migrate the job to the new format.

Being certain about this is tricky but when I have extremely large datasets (Order 200Mb of RAM and 80Mb on disk) I begin to think that we can be more intelligent with the LHCbDataset and store them in some compressed format in memory as well.

**Comment by rob-c** [comment]
@drmarkwslater Adding an inline gzip to storing the XML would be nice to see imo. Is it possible to write something short to determine if a file is compressed or not, or will we have to migrate to use somerthing like `data.gz` everywhere? In which case I worry about handling of older jobs

**Comment by rob-c** [comment]
The dataset as it is returned from DIRAC in a tuple is already over 100Mb in memory from the python subprocess and that is pickled but uncompressed. I think we can reduce this though as the LFN information appears highly compressible.

**Comment by alexanderrichards** [comment]
> over 100Mb in memory

Wow I am surprised by this figure. I assume this if due to the face that the Dataset essentially is a list of DiracFile objects?

Perhaps a way of reducing this is have the dataset internally store simply a list of LFNs and then these get wrapped by a DiracFile when you try to extract them?

**Comment by drmarkwslater** [comment]
@rob-c It would be pretty easy, basically just check if a non-zipped file is present, if so read that, if not read the zipped version. For flushing, either by default zipped files are used (configurable) or if an object is above a certain size then use it. If the zipped file is written, the non-zipped file is removed.

Something like that anyway :smile:

**Comment by drmarkwslater** [comment]
Just as a guide, we're talking 25000 LFNs which is 3+MB as uncompressed string data already. It does seem like a bit of a leap to get to 100MB but it's not out of the question.

**Comment by rob-c** [comment]
The python sub-process returns objects this large (which surprised me a little) but you can watch it.
Run the bookkeeping query and watch for the subprocess to spawn and it grows to around 120Mb for me then returns and Ganga then parses this into about 200Mb of internal objects again.

I think the LHCbDataset as you say could use just flat string data and generate DiracFiles on request without breaking anything but this requires a lot of work behind the scenes.

**Comment by alexanderrichards** [comment]
> Perhaps a way of reducing this is have the dataset internally store simply a list of LFNs and then these get wrapped by a DiracFile when you try to extract them?

This would also reduce the XML size as it wouldn't need to write out a DiracFile object for each LFN

**Comment by rob-c** [comment]
@alexanderrichards Yes but it changes the Schema and so we need to be able to parse old objects somehow into the new ones which requires a bit of being careful.
The object would be constructed via modifying it's internal attributes once it's read from XML but then the class has no way to know it needs to re-analyze these attributes to convert them into the new format.
Additionally users or other code may construct a Dataset from a list of input DiracFiles which would require a step to parse (sanitise) data like this on input into the new format.

**Comment by egede** [comment]
LHCbCompressedDataset implemented to mitigate this.
