### ISSUE TITLE
LHCb proxy tool no longer is able to read disk cache

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#566]
LHCb `ganga-proxy.py` needs to be updated to read the now JSON cache on disk in order to be able to make a dirac proxy when we change to a new version of LHCbDIRAC.

This needs to be done before 6.1.21

This should have showed up in testing. Are we making sure we're removing all of the on-disk caches on the Jenkins server between nightlies does anyone know?

**Comment by milliams** [comment]
I did update the `ganga-proxy.py` tool when I made the cache change. Perhaps I missed something though. What error are you seeing?

**Comment by rob-c** [comment]
My window only showed the code for reading in the old file format (which I think is no-longer needed?)

I wasn't expecting to see the new file format then read afterwards and to overwrite what is already potentially in memory.

This only effects me as I have both types of configs for the same LHCbDirac version lying around on disk. Users won't see this when we bump the version for 6.1.21.

I propose removing the old code for reading the old file format. It's no longer required.
