### ISSUE TITLE
Shutdown should cleanup config system after itself

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#568]
We should add some code to cleanup the config system and any other remaining globals upon shutdown.
This would improve the way that the config is handled between tests, i.e. we cleanly and correctly start from scratch each time rather than any horrible hacks specific to the test system.

**Comment by milliams** [comment]
I think a good starting point for this would be removing the use of `_after_bootstrap` that is scattered around in a few places. If we can wean all the code off that variable then this task will become a lot easier.

**Comment by rob-c** [comment]
I'm not a fan of modifying the config after the bootstrap step just because the tests are having problems.
But if this is a viable workaround until we have the config system under better control go from me.

**Comment by rob-c** [comment]
Scratch that. Why are we modifying the code after bootstrap. I thought this was a test thing. Never looked at it myself.
