### ISSUE TITLE
ARC submission broken

### ISSUE THREAD

**Issue by jepperandersen** [ganga-devs/ganga#569]
I am using submit scripts that work with 6.1.1-hotfix1. But when try to submit using the ARC backend and ganga 6.1.20, I get the following result:

INFO     submitting job 1
INFO     job 1 status changed to "submitting"
INFO     Preparing Executable application.
INFO     Created shared directory: conf-4ea919c6-0a82-4d32-8d56-159a595419c6
INFO     Splitting Job: 1
INFO     submitting 2 subjobs
INFO     Preparing subjobs
INFO     Submitting a prepared application; taking any input files from conf-4ea919c6-0a82-4d32-8d56-159a595419c6
INFO     Submitting a prepared application; taking any input files from conf-4ea919c6-0a82-4d32-8d56-159a595419c6
INFO     ARC CE endpoint set to: ce1.dur.scotgrid.ac.uk
WARNING  preparing 2 subjobs ... it may take a while
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/LATEST/python/Ganga/Lib/LCG/ARC.py", line 240, in process
WARNING  ---------- error in user/extension code ----------
WARNING      my_sc, master_input_sandbox)
WARNING  Traceback (most recent call last):
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/LATEST/python/Ganga/Lib/LCG/ARC.py", line 751, in preparejob
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/LATEST/python/Ganga/Lib/LCG/ARC.py", line 240, in process
WARNING      fileutils = File( inspect.getsourcefile(Ganga.Utility.files), subdir=PYTHON_DIR )
WARNING      my_sc, master_input_sandbox)
WARNING  NameError: global name 'Ganga' is not defined
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/LATEST/python/Ganga/Lib/LCG/ARC.py", line 751, in preparejob
WARNING  --------------------------------------------------
WARNING      fileutils = File( inspect.getsourcefile(Ganga.Utility.files), subdir=PYTHON_DIR )
WARNING  NameError: global name 'Ganga' is not defined
WARNING  --------------------------------------------------
ERROR    Some jobs not successfully prepared
ERROR    JobManagerError: error during submit
ERROR    JobManagerError: error during submit ... reverting job 1 to the new status
INFO     job 1 status changed to "new"
JobError: Error: JobManagerError: error during submit
(consider --debug option for more information)
INFO     Stopping Job processing before shutting down Repositories
INFO     Shutting Down Ganga Repositories
INFO     Registry Shutdown

**Comment by drmarkwslater** [comment]
@jepperandersen I'll make every effort to get this done for 6.1.21!

**Comment by drmarkwslater** [comment]
Fixed by @milliams with this commit 090df24
