### ISSUE TITLE
Allow Tasks to combine the output data of several transforms to a single unit/job

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#572]
This may not be possible in the current implementation but it would nice to allow a single unit process all the output from several transforms. What this boils down to is allowing `TaskChainInput` datasets to have more than one Transform as input.

**Comment by JacekHoleczek** [comment]
There is already something that looks "relevant":

./python/Ganga/GPIDev/Lib/Tasks/ITransform.py:        #'force_single_unit' : SimpleItem(defvalue=False, doc='Force all input data into one Unit'),

**Comment by drmarkwslater** [comment]
I remember I had this in the original implementation of Tasks but I **think** I dropped it because of reasons that now escape me. I will investigate!
