### ISSUE TITLE
Cache data vs fully initialized Job

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#58]
This is an issue to remind me to look into the use of Cached data on an object from the .idx file vs loading the full object description from the .xml.

Currently this feels like it's extremely difficult to follow where the actual data is being stored and where it's being accessed.
I've made some improvements with the optimisation work for 6.1.14 but this highlights that this needs addressing properly imo.

I've some ideas on how the code could be cleaned up with regards to this but it should probably be done for 6.1.15 or onwards. Basically I want to remove the overhead in trying to access data that isn't there and make it much clearer where and when a job should be fully loaded from disk in future.
This goes hand in hand with improving the SubJobXMLList which unfortunately is still loading ALL subjobs for many tasks due to some parts of the codebase requesting the whole subjob or all subjobs before it knows what it wants to do with the information.

**Comment by rob-c** [comment]
After a lot of staring at the code and fixing performance/functionality bugs in the Registry I've come to the conclusion that a lot of the functions were based upon the idea of object inspection to determine things like if an object has been loaded from disk or not.
This was unfortunately failing to do any form of caching due to a hand full of minor looking long-standing bugs.

I've changed the registry to keep track internally of which jobs it has loaded and store their ```_registry_id``` internally.
This has been implemented slightly in a slightly hap-hazard way with a lot of old code/functionality/checks still in place.
As the code in the release/6.1.14 branch is in a working state I aim to release without any major work and will attempt to clean up the tracking of job 'load'-ing within both the Registry and Repository layers as part of 6.1.15

I had to implement this in order to allow for dirty objects to exist in memory without being replaced by a historic version of the object from disk as was observed quite often.

I'm planning to add a simple function within the GangaObject (or Registry) to determine if a Job has been fully loaded or not according to the information stored in the registry and repository. This would allow us to make some simple integration tests around the lazy-loading.

**Comment by rob-c** [comment]
OK, so this was something that crept up in 6.1.14 right at the last minute.

I've no idea how/if/when the mechanism for dealing with the indexes was broken but it was badly broken by the time we got to testing for the release. (I went back through the history and I think I can reproduce the problems I was seeing before 6.1.13).

I think the intention of the current code is that:

1) Data stored in the *.idx contains a small amount of cache data, enough to populate the 'jobs' summary or equivalent.
This data is loaded and stored in the ._index_cache dictionary which is now behind the get/setNodeIndexCache methods. This should be loaded at startup and cleared when the job is fully-read in from data.

2) Data stored in the 'data' XML files contains everything stored in the schema and nothing else. This is read into the ._data dictionary which is controlled through the get/setNodeData methods.
At some point this is translated into the __dict__ of the class object. At the moment right after the XML has been read.

3) The same getter function is used everywhere. This means that the getter function is potentially looking in ._index_cache, ._data and .__dict__ to find the attribute to return for a GangaObject.
This just got confusing so has been simplified slightly in 6.1.14 but more could be done here.


My plan is to try and consolidate this as much as is sensible to reduce the complexity of the getter method which currently adds confusion when trying to access 3 different dictionaries from my experience.
I'm not sure what benefit storing data in ._data for future access has if this is going to be deprecated by objects in __dict__ so I think this should be lost at the XML layer. Which then makes me wonder could the XML be read more directly into the final object rather than taking several steps.

I'm thinking of adding some further caching of data which can be easily/quickly accessed on startup but I'll only look into this once the whole loading of objects becomes much simpler.

Following the flow of the objects from XML into a fully loaded job has become a bit less painful and whilst the loading of a job is now safer due to various checks/locks in the repository this is still an area that would only benefit from being streamlined in the future.

**Comment by egede** [comment]
> Which then makes me wonder could the XML be read more directly into the final object rather than 
> taking several steps.

@rob-c We have earlier wondered about why jobs objects seems to take up so much space in memory. Maybe what you see here leads to a permanent duplication in memory.

**Comment by rob-c** [comment]
@egede It's highly likely.
The actual mechanism involves handing off to a new temporary GangaObject and then to migrate the information to the object in the repository which is the ```Job``` or other object of interest. I suspect that there could be a lot of duplication depending on object scope but if the transient data is accidentally copied which I suspect it is then this could double the memory usage at least.

My plan is to reduce all of this to be that an object contains all of the information it knows about in the schema within the ```__dict__``` of the class. The custom getter can still intercept when an attribute is not in memory, trigger a load from XML and search again with appropriate errors.

I'm not a fan of objects from within the NodeIndexCache being accessed through the standard getter as this is data which depends on the actual repository in question; in addition to not strictly being knowledge that the class should be expected to have imo. Plus it leads to very confusing errors such as 'Job object has no attribute "display:backend"' which can be counter intuitive.

**Comment by milliams** [comment]
There is definitely duplication as I've noticed this recently too. However, there shouldn't be much of an increase in memory usage as the two dictionaries seem to point to the same objects:
```python
e = Executable()._impl
assert e._data['env'] is e.__dict__['env']
assert e._data['args'] is e.__dict__['args']
```
Them being dictionaries pointing at the same place may be a new thing though as looking at 6.1.13, a `GangaObject` did not have the schema items in the `__dict__`, it was only stored in `_data` so this is a new bug which has been introduced.

A related issue might be with [this commit](https://github.com/ganga-devs/ganga/commit/4aa720adde3609a6b2fb2aa506a8eb5a3bd7140f#diff-3a5f5ed88f274eb570dccbab85337abfR60) which makes `__getstate__()` remove the items listed in `_ref_list` from the object's `__dict__`.

**Comment by rob-c** [comment]
@milliams there was a change in 6.1.14 to use dict has it was discovered there was at least one or 2 naieve places of code were looking there for information as this is where it's stored if an object is constructed in memory.

Then the setter needs to duplicate references and the getter needs to examine both if the data dictionary isn't transient. I had difficulty modifying this to avoid excess flushing.

Dancing around with 2 or more dictionaries just leads to problems that can be avoided. Yes this isn't a duplication but causes a problem with a reference still existing for an object which was just removed or overwritten.


The get/setstate just adds more confusion again as this used to do managing of inheritance but this stopped working by design or by bug in 6.1.14 which caused problems when I was trying to get jobs to write to XML correctly.

All of this aside I just want to get this into a working state for 6.1.14 and then I'll fix it properly in 6.1.15

**Comment by milliams** [comment]
Changing `GangaObject`/`Node` to store the schema data in the object's `__dict__` sounds like quite a major change (especially if was just to fix some naïve code) which probably needed some discussion beforehand. There didn't used to be any duplication of information and given that it's not clear where this is happening means this definitely needed some more thought.

I've been going through `Objects.py` to do some cleaning and there's so much broken or nonsensical code in there I'm not surprised we're hitting problems.

**Comment by rob-c** [comment]
The information is always stored in the ```__dict__``` or should have always been stored in there so nothing should have been changed by enforcing that the ```_data``` dictionary is not used at a much higher level than it appears was originally intended (reading in the XML).

Only the values of the attributes which are in the schema are stored in the dictionaries. I am NOT proposing any changes to the use of ```_schema``` within the class objects. Apologies if this isn't clear.
This was discussed in yesterdays meeting to do with loading objects into memory.

The changes were due to some code expecting an object to be in ```__dict__``` and due to some bug the data between this and ```_data``` had become inconsistent. (This appeared to be due to lazy loading being broken but this turned out to be a race condition within the Registry).
All of this being said, if the use of ```_data``` can be dropped this is the direction I'm heading in for 6.1.15 and to remove functions which either aren't called or aren't correctly called.

In 6.1.14 I've had to add numerous checks/locks to the Repository which is heavily integrated within Objects as well as making the getter/setter functions behave in a sane way when presented with large objects I've hit a lot of papercuts which don't merit keeping the complexity of the get/setstate and a few other pieces of code over directly calling the get/setParent methods on assignment and having copies only made in the copy methods.

**Comment by milliams** [comment]
Running
```python
from pprint import pprint
e = Executable()
pprint(e._impl.__dict__)
```
gives (6.1.13):
```python
{'_data': {'args': ['Hello World', ],
           'env': {},
           'exe': 'echo',
           'hash': None,
           'is_prepared': None},
 '_dirty': True,
 '_lock_count': {},
 '_parent': None,
 '_proxyObject': <<Ganga.Lib.Executable.Executable.Executable object at 0x7ff1a2b44bd0> PROXY at 0x7ff1a2b44c90>}
```

or back in 6.0.44:
```python
{'_data': {'args': ['Hello World'],
           'env': {},
           'exe': 'echo',
           'hash': None,
           'is_prepared': None},
 '_dirty': True,
 '_parent': None,
 '_proxyObject': <<Ganga.Lib.Executable.Executable.Executable object at 0x28bb7d0> PROXY at 0x28bb8d0>}
```
In neither case is there any duplication between the `__dict__` entries and what is in `_data`.

**Comment by rob-c** [comment]
At this stage I'm wondering what advantage of having everything set from the setter to be in '_data' at all. Unless I'm completely missing the point of it.

Either way the getter/setter in Objects do not make their expectations particularly clear, the getter can be re-written in about half of the size that it is in 6.1.13 due to the amount of code that's simply not called.

**Comment by milliams** [comment]
I *think* the idea was that a `GangaObject` would store all it's schema data in `self._data` and keep all the raw stuff in `self.__dict__` as implementation details. It's clear that the way this whole system is written is quite weird (or has grown to become so over the years) and needs replacing with something much simpler (i.e. the `GangaObject` just stores descriptor-protocol objects directly in its `__dict__`). @alexanderrichards's rewrite fixes all this and I'm very much i favour of doing this properly.

**Comment by rob-c** [comment]
I still think we could be seeing problems with the way that this was read in which calls a lot of mystery functions who are overloaded in strange ways which isn't understood. Accompanied by wonderful bugs like "I'll put this here because doing a copy destroys parent knowledge at some level"...

Either way, the first thing I'm aiming for in 6.1.15 is to strip out un-needed functions and reduce the amount of code needed to read in an XML file. Once that's done we can look at if we really want/need _data as a final step because it will just be an added redirect.

This all causes confusion to me that an object is not in ```__dict__``` but is still 'gettable' using the standard methods due to overloading of the getter/setter. When you then add the proxy on top I get fed up of it all.

**Comment by milliams** [comment]
The thing is that, for the example of Executable, `'args'` is not in the `__dict__` of an instance of `Executable` but rather in the `__dict__` of the class itself. For example you can do:
```python
class Foo(object):
  a = 'something'

o = Foo()

print Foo.__dict__
print o.__dict__
print o.a
```
gives
```python
{'a': 1, '__dict__': <attribute '__dict__' of 'foo' objects>, '__module__': '__main__', '__weakref__': <attribute '__weakref__' of 'foo' objects>, '__doc__': None}
{}
something
```
In our case we have, in the class's `Executable.__dict__` the descriptor objects which are given an *instance* of the class as `obj` and it extracts the values from `obj._data`. This works because all `Executable` objects have the same set of attributes, even if the *values* of those attributes are different.

**Comment by rob-c** [comment]
I'll leave merging a small branch which does away with _data until after a discussion in January.
(I fail to see any redeeming reason to have the _data object around but if there is an exceptionally good reason maybe I can be convinced.)

Until then it's easy enough to do the rest of the work to put the XML object directly into the class of choice and to get rid of code which doesn't make sense any more.

I still think this is getting to be a major headache to track/set/clear values across multiple dictionaries for things like lazy loading etc, that and there is a lot of dead/defunct code cluttering these interfaces. Maybe once it's been cleared up then dealing with different dictionaries may not seem like such a bad thing but as it stands this made a lot of small tasks to do with reading/writing jobs more of a pain than it should have been to modify, and there are still some sections of code more temperamental than I'd like in 6.1.14, but I think it's close to release-ready.

**Comment by milliams** [comment]
The reason in general for having a `_data` attribute is that if you have a simple descriptor like:
```python
class Descriptor(object):
    def __init__(self, name):
        self.name = name

    def __get__(self, obj, objtype=None):
        return getattr(obj, self.name, None)

    def __set__(self, obj, value):
        setattr(obj, self.name, value)  # This will cause an infinite loop

class MyClass(object):
    x = Descriptor('x')

m = MyClass()
m.x = 'foo'
```
Then since the descriptor is trying to save into `m.x` in `__set__` it causes an infinite loop. Now, you can get around this by setting the value on `obj.__dict__` directly but this is not the conventional way to solve it, particularly because it causes confusion since the data is then *only* accessible via `__dict__`. calls.

Usually, you would instead set the descriptor's `self.name` to `'_'+name` so that the data for `m.x` would be stored in `m._x`. Alternatively, what we have in Ganga instead is a descriptor that looks more like:
```python
class Descriptor(object):
    def __init__(self, name):
        self.name = name

    def __get__(self, obj, objtype=None):
        return obj._data[self.name]

    def __set__(self, obj, value):
        obj._data[self.name] = value
```
so that the data for `m.x` would be stored in `m._data['x']` which is a similar solution except all the schema data is stored in one location.

In 6.1.13 the *only* place that the schema backing data was stored was in the instance's `_data` dictionary, it is only in the current develop branch that it is now also duplicated in the instance's `__dict__`. If the data being duplicated into `__dict__` was introduced accidentally during the 6.1.14 development then *that* is what should be fixed. If it was done on purpose then why was it done?

**Comment by alexanderrichards** [comment]
to add to what @milliams writes above, the way that I solve the problem in the rewritten stuff is to move the location where the data is stored into the descriptor itself using the standard weakrefdict on an instance key. This makes the whole object much cleaner and also more transparent to the developer using the schema attribute.

**Comment by rob-c** [comment]
At this point I'm not even worrying about trying to have the same information in the ```__dict__``` if it's there and it's not intended to be there, then indeed kill it.
Frankly fixing this is a 6.1.15 issue as I just want to get 6.1.14 working then I'll worry about proper scope and location of data (expected vs actual) as this is dragging on and on.
This is why I added the (get/set)Node(Data/IndexCache) methods to try and make it clearer what information goes where and where it is being accessed. There were a few places which I'd argue are accessing information that they shouldn't be.

My problem is the fact that in issues like #74 the cache data and the actual data stored for the object are out of sync and having the ability to define both of these at the same time with one taking preference is bad imo. (this bug is more tricky than just this and I'm digging to try and understand it)

The logic should be very cut and dry either the job is loaded, in which case look in the ```__dict__```, or the job is not loaded, therefore we can see if we can make use of the cached data or try loading the job.
I know that's what the code in the getter methods 'should' have always been doing but there are weird sections of code in 6.1.13 and going back a lot further which are un-callable once you follow through the logic.

**Comment by alexanderrichards** [comment]
ok sorry I have been getting off topic as I thought we were talking about descriptors. To pull things back to what we have now. Can you clarify for me if I'm right in my understanding:

1. If job is loaded we get info from the object
2. If job is not loaded we try to get info from cache and if cant then we load job and get info.

So my question is how does is _data vs __data__ used in this context?
is __data__ used as the store for loaded data while _data used for the cache?

**Comment by milliams** [comment]
@alexanderrichards Did you mean `__dict__` there?

**Comment by alexanderrichards** [comment]
sorry yes ;-)

**Comment by rob-c** [comment]
@alexanderrichards  What should happen and what largely does happen across most of the codebase:

```_data``` is used to store the index cache information i.e. the stuff used by the ```_display``` method behind the call to ```jobs```
This is typically None or `{}` for a job which is fully-loaded in memory but there have been occasions when it's not which just adds confusion imo.

The actual data of the job object when it's loaded from memory should be loaded into the same place as-if the job has been created that session. So a loaded job should correctly have populated the job objects ```__dict__```.

When a job is loaded from disk ```_data``` should be cleared and then the object should be fully populated.
(There confusion in the fact that it's not always empty and I strongly think that if this is largely meta-data-ish then it should be constructed on the fly rather than storing copied information from the job.
The ```_data``` object always takes precedent over a fully-loaded job as per design dating back before 6.1.13 by a long way so if this ever becomes out of sync with the true object funny behaviour can happen)

When a job is not loaded the getter methods will attempt to use information from ```_data``` to satisfy the request which seems perfectly fine until you get things like ```hasattr(myJob, 'display:id')``` sometimes returning true which is odd behaviour imo.

I think this makes sense.

**Comment by milliams** [comment]
This is not my understanding of the situation at all. Looking back at 6.1.13 I see:

`_index_cache` contains the information from the lazy-loading so just some basic data like the id, backend type etc.

`_data` contains the actual data for each schema attribute. So for  a `Job`'s `id` attribute, `Job.id` is a descriptor which stores and retrieves its data from `j._data`. `_data` should only.

While a job is only lazy-loaded, the `_index_cache` dict should contain information but `_data` should be empty. Once the job is fully-loaded, `_index_cache` should be empty and `_data` should be filled. Since 6.0.44 this does indeed seem to have been a bit broken but the "look in `_data` and if not then look in `_index_cache`" logic should still be possible.

The object instance's `__dict__` should contain only things like `_data`, `_index_cache`, `_parent`, `_proxy_object` etc. and not any of the schema data directly.

Has this logic changed *that* dramatically since 6.1.13?

**Comment by rob-c** [comment]
OK, sorry, I've just grabbed a coffee and realised that the above is incorrect. (Apologies I'm trying to juggle a few things at once.)

When an object is constructed in the session then the object has a fully populated ```__dict___```

When an object is stored on disk then the ```._index_cache``` contains the index information for the job from disk.
When a job is fully loaded from disk the ```_data``` object is populated using information from the XML which should contain the normal ```__dict__``` of the object.

```_index_cache``` takes priority over ```_data``` which takes priority over ```__dict__```...

My concern is that surely a fully loaded job should be the same as a job created in that session. Either all attributes should populate ```_data``` or ```__dict__```. And a fully loaded job without a proxy should be equivalent to a Job that can be constructed in python code.

**Comment by alexanderrichards** [comment]
ok so if the schema attributes are descriptors storing their data in `_data` then as @milliams says they should not be in `__dict__`. So from what you say it sounds like a Job constructed from the session should be storing it's data in `_data` not `__dict__`.

**Comment by alexanderrichards** [comment]
Is there a problem then when I partially specify a jobs constructor. i.e.
```python
j=Job(application=MyApp())
```
do we get MyApp in `_data` but the defaults in `__dict__`?

**Comment by milliams** [comment]
In 6.1.13 (and 6.1.14), a newly created `Job._impl.__dict__` looks like:
```python
{'_Job_constructed': True,
 '_data': {'application': <Ganga.Lib.Executable.Executable.Executable object at 0x7fb34a07a890>,
           'backend': <Ganga.Lib.Localhost.Localhost.Localhost object at 0x7fb34a07a610>,
           'been_queued': False,
           'comment': '',
           'do_auto_resubmit': False,
           'fqid': None,
           'id': 6,
           'info': <Ganga.GPIDev.Lib.Job.Job.JobInfo object at 0x7fb34a07aad0>,
           'inputdata': None,
           'inputdir': None,
           'inputfiles': [],
           'inputsandbox': [],
           'master': None,
           'merger': None,
           'metadata': <Ganga.GPIDev.Lib.Job.MetadataDict.MetadataDict object at 0x7fb34a07a9d0>,
           'name': '',
           'non_copyable_outputfiles': [],
           'outputdata': None,
           'outputdir': None,
           'outputfiles': [],
           'outputsandbox': [],
           'parallel_submit': False,
           'postprocessors': [],
           'splitter': None,
           'status': 'new',
           'subjobs': [],
           'time': <Ganga.GPIDev.Lib.Job.JobTime.JobTime object at 0x7fb34a07ad90>},
 '_dirty': True,
 '_index_cache': {'display:application': 'Executable',
                  'display:backend': 'Local',
                  'display:backend.actualCE': '',
                  'display:comment': '',
                  'display:fqid': '6',
                  'display:name': '',
                  'display:status': 'new',
                  'display:subjobs': '',
                  'id': 6,
                  'name': '',
                  'status': 'new',
                  'subjobs:status': []},
 '_lock_count': {},
 '_parent': None,
 '_proxyObject': Job#6,
 '_registry': <Ganga.GPIDev.Lib.Registry.JobRegistry.JobRegistry object at 0x7fb35a644e90>,
 '_registry_id': 6,
 '_registry_locked': True}
```
in `develop` it now looks like:
```python
{'_data': {},
 '_dirty': True,
 '_id': 8,
 '_index_cache': {},
 '_parent': None,
 '_proxyObject': Job#8,
 '_registry': <Ganga.GPIDev.Lib.Registry.JobRegistry.JobRegistry object at 0x1fa09d0>,
 '_registry_id': 8,
 '_registry_locked': True,
 u'application': <Ganga.Lib.Executable.Executable.Executable object at 0x296fe90>,
 u'backend': <Ganga.Lib.Localhost.Localhost.Localhost object at 0x296fe10>,
 'been_queued': False,
 u'comment': '',
 u'do_auto_resubmit': False,
 'fqid': None,
 u'id': 8,
 u'info': <Ganga.GPIDev.Lib.Job.Job.JobInfo object at 0x29740d0>,
 u'inputdata': None,
 'inputdir': None,
 u'inputfiles': [],
 u'inputsandbox': [],
 'master': None,
 u'merger': None,
 u'metadata': <Ganga.GPIDev.Lib.Job.MetadataDict.MetadataDict object at 0x296ff10>,
 u'name': '',
 u'non_copyable_outputfiles': [],
 u'outputdata': None,
 'outputdir': None,
 u'outputfiles': [],
 u'outputsandbox': [],
 'parallel_submit': False,
 u'postprocessors': <Ganga.GPIDev.Adapters.IPostProcessor.MultiPostProcessor object at 0x296ff50>,
 u'splitter': None,
 u'status': 'new',
 u'subjobs': <Ganga.Core.GangaRepository.SubJobXMLList.SubJobXMLList object at 0x296fc50>,
 u'time': <Ganga.GPIDev.Lib.Job.JobTime.JobTime object at 0x29741d0>}
```
which is clearly a big change and I feel is causes a lot of these problems.

**Comment by alexanderrichards** [comment]
Indeed, I assume this was from a default constructed Job. What about with a partially specified constructed job? does the specialisation populate `_data` or `__data__`?

**Comment by rob-c** [comment]
@milliams For me I see both ```_data``` and ```__dict__``` are both populated with all of the application, ... entries, are you using the latest develop?

**Comment by milliams** [comment]
It was indeed simply:
```python
j = Job()
from pprint import pprint
pprint(j._impl.__dict__)
```
Doing the same with `j = Job(backend=LCG())` gives:

6.1.13:
```python
{'_Job_constructed': True,
 '_data': {'application': <Ganga.Lib.Executable.Executable.Executable object at 0x7fb34a0a51d0>,
           'backend': <Ganga.Lib.LCG.LCG.LCG object at 0x7fb34a0a5510>,
           'been_queued': False,
           'comment': '',
           'do_auto_resubmit': False,
           'fqid': None,
           'id': 7,
           'info': <Ganga.GPIDev.Lib.Job.Job.JobInfo object at 0x7fb34a0a52d0>,
           'inputdata': None,
           'inputdir': None,
           'inputfiles': [],
           'inputsandbox': [],
           'master': None,
           'merger': None,
           'metadata': <Ganga.GPIDev.Lib.Job.MetadataDict.MetadataDict object at 0x7fb34a0a5310>,
           'name': '',
           'non_copyable_outputfiles': [],
           'outputdata': None,
           'outputdir': None,
           'outputfiles': [],
           'outputsandbox': [],
           'parallel_submit': False,
           'postprocessors': [],
           'splitter': None,
           'status': 'new',
           'subjobs': [],
           'time': <Ganga.GPIDev.Lib.Job.JobTime.JobTime object at 0x7fb34a0a5490>},
 '_dirty': True,
 '_index_cache': {'display:application': 'Executable',
                  'display:backend': 'LCG',
                  'display:backend.actualCE': '',
                  'display:comment': '',
                  'display:fqid': '7',
                  'display:name': '',
                  'display:status': 'new',
                  'display:subjobs': '',
                  'id': 7,
                  'name': '',
                  'status': 'new',
                  'subjobs:status': []},
 '_lock_count': {},
 '_parent': None,
 '_proxyObject': Job#7,
 '_registry': <Ganga.GPIDev.Lib.Registry.JobRegistry.JobRegistry object at 0x7fb35a644e90>,
 '_registry_id': 7,
 '_registry_locked': True}
```
which looks correct and with `develop` we get:
```python
{'_data': {},
 '_dirty': True,
 '_id': 9,
 '_index_cache': {},
 '_parent': None,
 '_proxyObject': Job#9,
 '_registry': <Ganga.GPIDev.Lib.Registry.JobRegistry.JobRegistry object at 0x1fa09d0>,
 '_registry_id': 9,
 '_registry_locked': True,
 u'application': <Ganga.Lib.Executable.Executable.Executable object at 0x2979a90>,
 u'backend': <Ganga.Lib.Localhost.Localhost.Localhost object at 0x2979a10>,
 'been_queued': False,
 u'comment': '',
 u'do_auto_resubmit': False,
 'fqid': None,
 u'id': 9,
 u'info': <Ganga.GPIDev.Lib.Job.Job.JobInfo object at 0x2979c90>,
 u'inputdata': None,
 'inputdir': None,
 u'inputfiles': [],
 u'inputsandbox': [],
 'master': None,
 u'merger': None,
 u'metadata': <Ganga.GPIDev.Lib.Job.MetadataDict.MetadataDict object at 0x2979b10>,
 u'name': '',
 u'non_copyable_outputfiles': [],
 u'outputdata': None,
 'outputdir': None,
 u'outputfiles': [],
 u'outputsandbox': [],
 'parallel_submit': False,
 u'postprocessors': <Ganga.GPIDev.Adapters.IPostProcessor.MultiPostProcessor object at 0x2979b50>,
 u'splitter': None,
 u'status': 'new',
 u'subjobs': <Ganga.Core.GangaRepository.SubJobXMLList.SubJobXMLList object at 0x2979850>,
 u'time': <Ganga.GPIDev.Lib.Job.JobTime.JobTime object at 0x2979d90>}
```
which has an empty `_data` and still the default value in `__dict__`.

**Comment by milliams** [comment]
@rob-c Yes, I'm using the latest `develop` with no local changes and get the above behaviour, even with a wiped `~/gangadir`.

**Comment by rob-c** [comment]
Ah, I reverted the patch effecting the j2.id bug, sorry for the noise there.
Now I see ```__dict__``` and ```_data``` containing multiple copies of the same data. I'll do some work to investigate what I'm seeing.

**Comment by rob-c** [comment]
I've not intended to implement any changes to how this 'should' be working in 6.1.14 so there is a bug somewhere. I don't know why now I see 2 applications when I run:

```
j=Job(application=DaVinci())
```

In my private repo I see the application in the ```_data``` dictionary set from the atomic set which calls the correct function but I still see an application of the Executable type which is defined at the ```__dict__``` level. I've given a quick grep through the codebase and very few places call ```__dict__``` directly so this shouldn't take too long to track down.


I have an additional question here.

I have created a class which inherits from GangaObject with all of it's features of being a writeable object with various features.
I now want to store a completely transient piece of information alongside that object. This information will be stored within the object's and is defined during the ```__init__``` method of my class. Where should I expect to see this information stored in future?
This transient information is not expected to be in the schema as it's a purely implementation detail so where should I expect to see/check for this object's existence, at the ```__dict__``` level or the ```_data``` level?

**Comment by alexanderrichards** [comment]
if this is transient in that it's non- persistent data, and you don't want it to be in the schema then I assume that you are initialising it as follows:

```python

class MyClass(GangaObject):
    def __init__(self):
        self.my_transient_data = 'blah'
```

in which case this will appear in the `__dict__`. Whether it's better placed in here or in `_data` with 
```python
self._data[my_transient_data] = 'blah'
``` 

I'd have to think about. My initial feeling is that if _data is reserved for schema (cachable) attribute data and this is a transient then possibly it's ok in __dict__

**Comment by milliams** [comment]
I think transient data should be stored directly as an instance attribute (so effectively in the object's `__dict__`). `_data` should be reserved as a backing-store for the schema objects only. So, as @alexanderrichards says, do something like:
```python
class MyClass(GangaObject):
    def __init__(self):
        self.my_transient_data = 'blah'
```
This data will exist as long as that Python object exists in memory.

**Comment by alexanderrichards** [comment]
the advantage of this is also that it makes transitioning to the newer system that I proposed easier because as you say the `_data` is just a backend for the schema which will be replaced.

**Comment by rob-c** [comment]
OK, I think as a result of this discussion and other additional changes in the ```Core.GangaRegistry``` and ```GPIDev.Base``` recently I'm happy to shelve this as a lot of work has been done towards simplifying the core as it stands.
