### ISSUE TITLE
Reduced XML Feature

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#589]
Hi all,

I've been doing some looking at reducing the XML files which we're writing to disk.

Do we explicitly want to write all default Schema attributes to disk?

I suppose the answer for the moment is yes we do because we could add a Schema attribute to change the behaviour of the class.

If we are careful going forward to not change the Schema in a backwards incompatible way we can explore only writing the objects to disk which we have changed from the default Schema value.
This makes loading objects from disk much quicker in addition to making the XML sizes on disk much smaller.

I'm not proposing merging any code to do this but I've played with a private patch to do this in some form and the XML size for a large number of DiracFiles reduces by about 60-70% and the loading of the objects into memory is much quicker.

Do people have a strong opinion about possibly looking into implementing this?

(This is already backwards compatible aka, XML with a very reduced schema on disk can be loaded without issue by Ganga already)

Thanks,

Rob

**Comment by egede** [comment]
@rob-c The straight forward implementation you have here, I do not think is acceptable. It will either make it too complicated for us to implement changes to default values in the future, or it will change the meaning of persisted objects for users if we change the defaults anyway. You could combine it together with some schema versioning (that we in principle have already) to be able to keep track of old default values but again that is a bit fragile if it depends on that we manually update schema versions.

**Comment by drmarkwslater** [comment]
I think I agree with @egede here. Though I agree it would be **very** nice to reduce the size of the XML, we would still need to store a snapshot of the defaults used to create that object somewhere at time of creation. Now what you could do is also store any repeated values as one value and refer back to that in the object body though I'm unsure how much improvement that would give. In the 10K `DiracFile` case, this could be very significant I guess though I don't know how many 'repeated' values there are stored in a DIRAC file.

If size on disk is the major issue, the we could look at automatic zipping (using the gzip module) as I've suggested before maybe?

**Comment by alexanderrichards** [comment]
> If size on disk is the major issue, the we could look at automatic zipping (using the gzip module) as I've suggested before maybe?

This is an interesting idea. I've never tried zipping one of our xml files but I assume that they would compress well

**Comment by drmarkwslater** [comment]
I haven't tried but it's a text file so you've got a bit improvement right there 😄

**Comment by rob-c** [comment]
This is related to constructing 100k * number of schema entries in loading them from disk. The time taken to construct an object at the moment is extremely high but if we know this corresponds to the present Schema then we can simply load the changes atop the Schema and things move much more quickly.

This isn't related to the xml file size although it does go down when not repeatedly writing empty lists and dicts throughout.

I'll come back to this in a bit (other larger tasks to do atm) with a more detailed explanation of what I'm considering but I think there's enough weariness that I'm not going to invest much time into attempting to demonstrate this.
