### ISSUE TITLE
Investigate the use of ordered dictionary for schema attributes

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#59]
As mentioned in the developer meeting on 03/12/2015 I've spotted a problem in Core due to initializing objects can potentially require that other schema attributes be correctly set for a parent object.

I'd like to investigate changing the attributes in the Schema to be stored in an ordered dictionary as of 6.1.15.
The default behaviour would be to have an ordered dictionary but to allow for unmodified classes to still use a dictionary style definition of the schema attributes.

This shouldn't be too invasive but I'd rather not introduce this into 6.1.14.

**Comment by milliams** [comment]
The problem here may be that the schema is defined by:

```python
_schema = Schema(Version(1, 2), {'id': SimpleItem(),
                                 'status': SimpleItem()})
```
and so at creation-time, the attributes are put into a Python `dict`. Even if this is then passed off to an OrderedDict, it is too late to maintain the same order. The class' schema would have to be changed to be defined as:

```python
_schema = Schema(Version(1, 2), OrderedDict([('id', SimpleItem()),
                                             ('status', SimpleItem())]))
```
which is perhaps starting to get a bit invasive.

Once we are on Python 3, we will be able to change `GangaObject`'s metaclass to store attributes in an `OrderedDict` and declare the items directly in the class body.

**Comment by rob-c** [comment]
I was considering changing the definition within the Schema and testing that this works as expected.
Changing this at the class level as you say won't work.

If a class is using an dictionary and it doesn't care what's initialized when then this shouldn't change. If a class is relying on the essentially random way in which it's objects are initialized then if this breaks things I'd genuinely describe this as a bug which needs to be fixed within the class.
I suspect very few places would actually be effected by this even if it is invasive.

I think this may be easier in Python3 but we're not going to be there within the next few weeks so I'm keen to try changing this in a private branch and see what changes. If everything dies as a result of this then I'm happy to abandon the work and wait for Python3 but I'm keen to try and have this feature in 6.1.15.

**Comment by rob-c** [comment]
I don't think there is much of a need for this given the recent improvements/changes with regard to how objects are constructed.
I think the original problem I had no longer applies here so closing this issue
