### ISSUE TITLE
WARNING  Configuration of GLITE for LCG

### ISSUE THREAD

**Issue by JacekHoleczek** [ganga-devs/ganga#600]
I downloaded new ganga using "git clone https://github.com/ganga-devs/ganga.git".
On "Ubuntu 14.04.4 LTS", in my ".gangarc", I explicitly set:
EDG_ENABLE = False
GLITE_ENABLE = False
but I still get the warning:
WARNING  Configuration of GLITE for LCG: 
WARNING  File not found: /afs/cern.ch/sw/ganga/install/config/grid_env_auto.sh
Note: this did NOT happen in older ganga versions.
Up to now, I was always downloading ganga "releases" only using the "ganga-install" script, so possibly there is something missing when I use "git clone" instead (in another thread I reported "Unknown IPython version: 0.13.2", which I got on a "SLC6" machine).

**Comment by rob-c** [comment]
The message about the configuration of GLITE not being found is something I believe @drmarkwslater is looking into as part of 6.1.22.
The problem with IPython is solved if you install via any mechanism other than just running the code via git-clone as we're officially supporting IPython 1.0+ atm.

**Comment by drmarkwslater** [comment]
I believe this has now been fixed with #656 and previous so with 6.1.22 you shouldn't see this anymore.
