### ISSUE TITLE
Ganga doesn't cope well with >> 1000 jobs

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#609]
We should do something better than stalling on startup when a user has >> 1,000 jobs.

Maybe only load the last 1000 jobs into memory and put some logic into the XMLRepo to generate jobs older than this when required.

**Comment by drmarkwslater** [comment]
Shouldn't this be handled by the lazy loading or is even the lazy loading being too slow for this number of jobs?

**Comment by rob-c** [comment]
No, this is users don't use splitters (not usually for good reasons) but I've worked with a few users wondering why we're so slow at loading 10k+ index files from disk on startup from AFS.
I'm keen to move to fix the master index so that it never gets out of sync tbh, that should be a relatively trivial fix and doesn't expose these users to the problem of starting up with lots of initial disk I/O.

This still has the issue that creating this many empty jobs is still an extremely expensive operation but that's another bug for another issue

**Comment by egede** [comment]
No longer relavant as we go to a database solution for persistency.
