### ISSUE TITLE
DIRAC execute running in a random temp directory

### ISSUE THREAD

**Issue by milliams** [ganga-devs/ganga#613]
There's an issue in `DiracFile` caused by the recent change to run DIRAC `execute()` commands in a random temporary directory. DIRAC API calls such as `addFile()` are `cwd`-aware and will look in the the current directory for the source files.

This means that `put`ting a file like:

``` python
Ganga In [0]: !touch test.txt

Ganga In [1]: d = DiracFile('test.txt', localDir='.', defaultSE='UKI-SOUTHGRID-RALPP-disk')

Ganga In [2]: d.put()
INFO     Uploading file './test.txt' to 'UKI-SOUTHGRID-RALPP-disk' as '/gridpp/user/r/robot.general.gangaproject/GangaFiles_13.30_Wednesday_22_June_2016/test.txt'
ERROR    Error in uploading file test.txt : {'UKI-SOUTHGRID-RALPP-disk': {'Message': 'Local file ./test.txt does not exist', 'OK': False}}
Ganga Out [10]: "{'UKI-SOUTHGRID-RALPP-disk': {'Message': 'Local file ./test.txt does not exist', 'OK': False}}"
```

will fail since the `cwd` is now some `/tmp/...` directory.

I'm not sure that the benefit of running all DIRAC commands in a temporary directory is worth having to manually go through and take into account all the places where the DIRAC command is expecting to be run in a certain place.

My preferred solution would be to remove the temp directory code from DIRAC `execute()` unless it can be shown that there is a real performance impact.

**Comment by rob-c** [comment]
You can pass the cwd to the command from the appropriate method in the DiracFile. If this is the preferred way of working then we should be explicit about this within DiracFile, it's not the main caller of the execute function in DiracUtils which is called extensively from elsewhere.

**Comment by egede** [comment]
Fixed at some point.
