### ISSUE TITLE
Clear instructions for creating a release

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#614]
When @milliams was away for a few days (for a happy occasion) it became clear that the rest of us did not know exactly the full release process (or didn't know where to look for it).

**Comment by milliams** [comment]
Indeed, I plan on writing some full documentation to explain how it is done. Some of it is still in a slight state of flux so I didn't want to pin it down too early but it's become better recently.

In summary, it can all be done in two clicks with the exception of running the legacy tests, installing to AFS and doing the LHCb manual (basically all the lxplus/AFS bits).

**Comment by mesmith75** [comment]
I think this can be closed.
