### ISSUE TITLE
Support for SLURM backend in GangaAtlas

### ISSUE THREAD

**Issue by will-cern** [ganga-devs/ganga#615]
Hello,

What would need to happen to get SLURM (https://rc.fas.harvard.edu/resources/running-jobs/) supported as a backend for athena jobs?

Cheers
Will

**Comment by drmarkwslater** [comment]
Not a lot actually 😄  As an initial test, I believe you can just override the settings in the `[PBS]` section of `.gangarc` with the appropriate values for SLURM. I'm afraid it's difficult for us to test as we don't have an installation of this but if you find settings that work I can easily use these for another 'SLURM' backend.

**Comment by drmarkwslater** [comment]
@will-cern Did you make any progress with this? If you send me a typical transcript of job submission and monitoring in SLURM that would be enough I think...

**Comment by will-cern** [comment]
I wasn't actually the one who had access to a SLURM backend either, it was Alex Tuna, who I've asked if he will try out your suggestion. I am assuming that after putting the right values in the PBS section of .gangarc, he can submit a job in the same way as https://twiki.cern.ch/twiki/bin/view/AtlasProtected/AthAnalysisBase#How_to_submit_your_job_to_condor but replacing "condor" with "pbs"

**Comment by drmarkwslater** [comment]
@will-cern Exactly - the PBS backend is pretty generic so if the commands are setup correctly, then it should work out of the box. Let me know if he needs any help!

**Comment by rob-c** [comment]
@drmarkwslater There appears to be some interest from different people to using Ganga with SLURM, is it worth elevating this to a default backend configuration which we 'support' out of the box?

**Comment by drmarkwslater** [comment]
@rob-c That's the plan. The problem is finding a SLURM instance to test it against. If I have a day spare at some point I'll probably set one up myself and use that to get the backend code written.

**Comment by schmitts** [comment]
@drmarkwslater Any update on the slurm support? If not, I would start to implement and test it now.

**Comment by Unode** [comment]
Would [this SLURM image](https://hub.docker.com/r/agaveapi/slurm/) help for testing things out?
Together with the [wercker](http://www.wercker.com/) platform (free for open-source projects) I now frequently use docker images as part of the testing framework of some of my projects.
There's also images for [SGE](https://hub.docker.com/r/kgutwin/simple-sge/), [Torque](https://hub.docker.com/r/agaveapi/torque/) and possibly others.

**Comment by egede** [comment]
@unode in principle an interesting option. I can't see how our development team (total size about 4 times 0.1 effort) will be able to do this any time soon. If somebody else would be able to integrate it into the testing framework then we are happy to assist.

**Comment by mesmith75** [comment]
Slurm is in since #1192 .
