### ISSUE TITLE
Review getter/setter methods on Schema Items

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#616]
We seem to have at least 2 ways of applying getters and setters or callbacks to schema items, the `attribute_filter_blahblah` stuff and the `checkset` value (which is broken and hardly used either). This should be reviewed properly and a single solution settled on and documented.

**Comment by rob-c** [comment]
I'd be happy to see both torched tbh, is there any real need to keep these around?
If there is a need then great, but can't most/all of this be done through different methods?

**Comment by drmarkwslater** [comment]
All of these seem to be different ways of doing exactly the same thing so they certainly need to be consolidated. However, we should take a bit of care as these things are still used (to a certain degree) and there are certain cases we may want to support as well.

**Comment by rob-c** [comment]
I agree there may be cases, but I can't motivate any in a particularly strong way. We can do most of this by intercepting calls to the getter I would imagine and do away with code which is fragile at best.

How many places are these 2 mechanisms used?

**Comment by drmarkwslater** [comment]
Not a lot from a very quick grep but the `attribute_filter` stuff is used in `Jobs` apparently. It should be checked properly but it shouldn't be a major problem to replace with a single implementation.

**Comment by rob-c** [comment]
@drmarkwslater When making changes recently I've discovered we don't have a sensible chain for inheriting the `__getattr__` method in the same way that we can overload the `__setattr__` method.

Would it be sensible to propose that we move the getter method system over to using some form of `__getattr__` call in `__get__` and have this resolve to look in `_data` in the baseclass to allow for higher up classes to better overload getter calls in the future?
(If I'm mixing up the order in which the `Descriptor.__get__` and `myClass.__getattr__` are called I apologize but it appears we can't easily overload the `__getattr__` method which I would naively expect to be able to use)

**Comment by milliams** [comment]
@rob-c There is a fundamental clash between `__getattr__`/`__setattr__` and descriptors. In your recent changes you had to manually call the base class `__setattr__` in order for the descriptor to kick in, this is really a bit of a hack. Really this per-item pre-processing and potential post-precessing on the getting of an item should all be handled *within* the descriptor.

We should have a function which is called by `Descriptor.__set__` at the very beginning which can transform any incoming value (this is basically what the filter does now). Perhaps likewise, the last thing that `Descriptor.__get__` should do before returning a value is pass it though some other transformation function. These functions can have side-effects if we wish as well. The current concept of 'getters' in the schema complicates this a bit as it works very differently to everything else.

**Comment by rob-c** [comment]
@milliams It would be good to see some level of consistency between the getter and setter.
I wonder then if a filter transform of some sort for the setting of a schema attribute may be in order.

My only concern is that the changes which are often expected touch other attributes, not just the one in question and things can cascade very quickly.

I suppose now we have to decide do we support both `__getattr__/__setattr__` moving forward or do we support and promote neither and fix the setter support within the Descriptor/Schema machinery?
I don't think we should support 1 and not the other as things will get confusing and it's a bit tricky for any new devs coming along in the future.

**Comment by milliams** [comment]
Indeed some consistency is needed. I would need to sit down for a while and think this through as there are a number or corner cases we need to support. However, if we're going to make any semi-major changes to the Descriptors it would probably be worth doing the `Schema`/`Descriptor` merge we've thought about in the past.

**Comment by rob-c** [comment]
@milliams Is it worth spending time fixing the filter such that it works in a sensible way and that the `__setattr__` calls can be retired in this case?
It's probably also worth checking the getter equivalent as well but at least now that we don't have the construct getting in the way anymore things should be a little easier to parse.

**Comment by alexanderrichards** [comment]
Hi All,
These changes I have still waiting for me to commit them as part of my rewriting of the object/schema/proxy objects. perhaps it's time I speed up their introduction :wink:
