### ISSUE TITLE
TestSJIDName::test_b_jobResubmit Keeps stalling

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#617]
This is bad behaviour as this test has dramatically different behaviour on the Jenkins box to all of my other systems I've tested it on... (in develop!) I'll open a PR to fix this in a few minutes

**Comment by drmarkwslater** [comment]
Is this a lockup then? What does the thread_trace say on the Jenkins box? If this is failing on develop but was passing previously then that's a bit worrying for 6.1.21...

**Comment by rob-c** [comment]
This doesn't fail on the Jenkins box but locks up on all of my other test systems.

It appears the subjob isn't failing as expected which is causing an unexpected lokup in Job.py  (very bad imo)

but the actual problem I think is caused by not implicitly defining a configurable which is different between LHCb and Core (the handling of wildcard files in outputfiles when no match is found)
