### ISSUE TITLE
GaudiRun application prepare step

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#622]
In the prepare step of the GaudiRun application, there is a "make clean" which should *not* be executed. Also the build.<arch>/ganga directory should be completely cleaned (but the directory itself should be left in place).

**Comment by rob-c** [comment]
@egede I've been looking into this (and other related tasks I'll open issues for).

Are we trusting that a user won't do something crazy such as build their code for gcc49 and then wrap it up in a gcc48 target and submit it? I don't know if there is any mechanism built into the build scripts from LHCb to prepare for this?

I'm thinking of adding an option to turn the make clean on/off but I'm a little weary that disabling it entirely may cause users to make mistakes which require effort to track down.

**Comment by egede** [comment]
> Are we trusting that a user won't do something crazy such as build their code for gcc49 and then wrap it up in a gcc48 target and submit it? I don't know if there is any mechanism built into the build scripts from LHCb to prepare for this?

It all goes into different `build.<cmtconfig>` directories, so it would require the user to manually copy stuff around. I do not see a risk.

> I'm thinking of adding an option to turn the make clean on/off but I'm a little weary that disabling it entirely may cause users to make mistakes which require effort to track down.

I suggest to simply take it away. This is exactly as it is for the current `Gaudi` applications. You might want to add a `make` method to the application class as it would make it easier for users to explicitly request a `make clean` or whatever they might request.

**Comment by rob-c** [comment]
I plan to expose a method to allow users to issue commands to the project from the class (I'm not sure if I do yet).

My thinking is that I don't know how the CMake handles placing the binaries between environments.
If no gcc48 binaries can get into the gcc49 folder then I think my concerns go away. (I'm probably being a little paranoid as I've not used the new CMake stuff yet).

I've removed the make clean in my branch and I'll upload any changes shortly, my code is in a bit of a state of flux
