### ISSUE TITLE
GaudiRun support for different environments

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#624]
I plan to add an additional `LbLogin.sh` call to the appropriate places in GaudiRun as well as exporting the CMTCONFIG to allow for different architectures of the same code to be made and submitted to different backends.

**Comment by egede** [comment]
So for the schema, just add it like 'platform = x86_64-slc6-gcc49-opt', exactly as done for the existing `Gaudi` applications.

**Comment by rob-c** [comment]
Yep that's the plan 👍
