### ISSUE TITLE
GaudiRun add support for streaming MassStorageFile to the Local and Batch backends

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#625]
I plan to add some method to construct the `data.py` file which is run with the job to have the appropriate streaming protocol and location for MassStorageFiles to allow them to be used with Local/Batch jobs.

I'll need to add a check to make sure users don't submit grid jobs with this filetype as they should make use of DiracFile to get their data on these WN.

**Comment by egede** [comment]
> I'll need to add a check to make sure users don't submit grid jobs with this filetype as they should make use of DiracFile to get their data on these WN.

@rob-c No, I do not think we need these checks. The use case is in principle a valid one. Behind the scenes, the file should be transferred though the input sandbox (or there is an expectation that it is accessible on the remote end) depending on the users configuration.

**Comment by rob-c** [comment]
@egede I'm not certain I trust that I know which version of `data.py` the user will get. I would assume they'll get the one that we make which is shipped as part of a tarball which is extracted just before the job runs but if they end up with the `data.py` from LHCbDIRAC (if any) then this would confuse things.

I'm not planning to stop users doing this if they want but a 1 line warning that they might be doing things in a sub-optimal way would probably be better imo. It would hopefully stop people accidentally submitting jobs which `worked at CERN` across to different sites on the grid without access to the data.

I don't think there's any guarantee of being able to stream from the locations we extract from eos or elsewhere to all sites is there?

**Comment by egede** [comment]
> I'm not planning to stop users doing this if they want but a 1 line warning that they might be doing things in a sub-optimal way would probably be better imo. It would hopefully stop people accidentally submitting jobs which worked at CERN across to different sites on the grid without access to the data.

@rob-c I agree.
