### ISSUE TITLE
GaudiRun support for complex splitting of jobs

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#633]
I'm still not certain how best to proceed with supporting the workflow of sending unique files per inputfile with each subjob.

I'm assuming that at some level there is the same inputdata being run over (if any) and in my mind this most likely means checking support for IGangaFile objects in the inputfiles within the GenericSplitter.

This has been reported working but it's worth formalising an example JDL and maybe making a unittest around it for this splitter.

At the same time I think it's worth exploring support for ArgSplitter as users may wish to run over the same inputdata with different conditions which are configured through some command-line arguments to their code?
(This is potentially more complex and I'm not sure how to go about supporting this for now, especially in the case of GaudiPython like behaviour where I may have to pass the sys.argc/sys.argv through to the user script which is executed depending how Python internally deals with execfile).

<Aside>
I can imagine a user wanting to change some inputfile and then run a re-processing, but I'm wondering if a user would do something to the extent of submitting many _near-identical_ jobs which may want to be individually run over a large(ish) subset of data.
I'm thinking of some sort of training exercise where a user may wish to run with 3 or 4 different scenarios over maybe ~50LFN in the inputdata which would produce ~150-200 subjobs total.
I'm wondering if there is some nice way to support this in a new type of splitter or not.
i.e. for each inputdata LFN perform multiple subjobs configured as so and collect them all into 1 master job.
aka:
`job.splitter=MyDataGroupSpltter(secondary_splitter=GenericSplitter(someArgs))`
This would pass the master job with all of the options (without inputdata) to the secondary splitter and the returned subjobs are then duplicated such that 1 set of subjobs exists for every LFN in the inputdata is created.
</Aside>

**Comment by egede** [comment]
@rob-c the `ArgSplitter` is already having some support for this in terms of that it can split on several properties at the same time. Take a look at the documentation and see if what is there is indeed sufficient.

**Comment by rob-c** [comment]
@egede I would have assumed you could use the `GenericSplitter` for this but not the ArgSplitter?

I'm not sure how to use arguments passed to the GaudiRun other than to tag them onto the GaudiPython like behaviour of:
`python someWrapperScript.py someDummyArgs`

This to me is the only sane way to pass args from the arg splitter (unless they always go to extraOpts).

The `GenericSplitter` is capable of splitting a job and assigning multiple attributes to each job as it's split but you'd still need to wrap this behind some larger splitter yourself to construct the large dictionaries which are passed to each subjob. As the functionality is there I won't write `MyDataGroupSplitter` but I will try and add a tutorial of what can be done using the GenericSplitter in this way elsewhere.

**Comment by egede** [comment]
@rob-c Sorry, I did indeed mean `GenericSplitter`.

**Comment by rob-c** [comment]
OK, this appears to be working correctly for the moment, I have a unique job script and extraOpts file generated for each subjob. In the case of backends with access to the shared area these are generated and used on a per-job basis. In the case of DIRAC these are generated at the start of the RTHandler `master_prepare` and then are all uploaded to the grid with DIRAC being told which script to run for which Job. It appears the correct files are picked up as expected from having a quick look at the stdout.
