### ISSUE TITLE
Fix master index flushing

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#635]
Some users are ending up in a very bad situation with many, many jobs causing Ganga to be unusable due to extremely long startup times caused by having to load many index files from disk.
This is exacerbated by events such as user hitting Ctrl+C or dropped connections and the master index not being re-generated correctly until shutdown.

At the moment all we do is remove it upon startup but it would be good to update the master index once every few min or so at least or update a version in memory to flush to disk with the jobs synchronisation so that future startups aren't effected by this bug.

**Comment by egede** [comment]
New persistency system will avoid this.
