### ISSUE TITLE
Have the CERN webpage refer back to github

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#638]
Hi all,

I've been asked by a few people what is the official homepage of Ganga atm?

I propose to put a link at the top of the old CERN page to the github address as well as the readthedocs.
(The CERN page still refers to cvs and savannah.)

Are there any objections or should I add a link to point users to another page?

Thanks,

Rob

**Comment by egede** [comment]
@rob-c Yes, please add a link. Or maybe even better get rid of the page completely and auto-forward.

**Comment by rob-c** [comment]
@egede I've added some useful links and kept the old page as backup for now, happy to make any changes

**Comment by rob-c** [comment]
If nobody objects to the page as it is for now I'll close the issue
