### ISSUE TITLE
Rename myOpts to options in GaudiRun application

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#641]
The name `myOpts` in the `GaudiRun` application is too colloquial and doesn't fit with the general naming in `Ganga`. It should just be renamed to `options`.

**Comment by rob-c** [comment]
This will provide a nice break between the in-development and stable Schema

**Comment by pseyfert** [comment]
To ease the transition from `DaVinci` to `GaudiRun`, wouldn't `optsfile` be the most transparent name? (not that it would matter much)

**Comment by rob-c** [comment]
@pseyfert I think `options` may be better as we're aiming to allow for a list to be generated as well as supporting construction of a list of 1 IGangaFile if the user tries to assign a string to the parameter.

Once I've got a prototype working I'll link to the PR here

**Comment by rob-c** [comment]
The schema has been rewritten as part of migrating to `GaudiExec` I think a quick final review before release is needed but other than that this issue can be closed for now.
