### ISSUE TITLE
delete `gangadir/shared/USERNAME` directories when job object is `remove()`'d

### ISSUE THREAD

**Issue by pseyfert** [ganga-devs/ganga#642]
It appears that the in ganga v601r21-BETA the directories holding the `cmake-input-sandbox.tgz` files do not get deleted when the corresponding job is deleted with `jobs(2637).remove()` in ganga.

What I did is, try to submit a `GaudiRun` job:
```
Created job for the jobs:  GaudiRun_test
Calls splitter
Finally submit the job
INFO     submitting job 2637
INFO     job 2637 status changed to "submitting"
INFO     Preparing GaudiRun application.
INFO     Created shared directory: conf-e153ca7d-178f-4897-a528-1cb2d33d7195
```
(the submission fails, as expected / discussed on the mailinglist)
then call `jobs(2637).remove()` to clean up my afs quota and do
```
find ~/gangadir/shared/pseyfert -name cmake-input-sandbox.tgz
```
to observe that `/afs/cern.ch/user/p/pseyfert/gangadir/shared/pseyfert/conf-e153ca7d-178f-4897-a528-1cb2d33d7195/cmake-input-sandbox.tgz` still exists.

**Comment by rob-c** [comment]
@pseyfert Thanks for providing clear proof that this is a problem!

These files should be being removed by some counter within Ganga which likely is a bit broken.

We __need__ to add a unittest for this to test the expected vs actual behaviour of our prepare tracking.

**Comment by egede** [comment]
@pseyfert Just to check that you quit Ganga and then checked that it was gone. The reason is that you may otherwise still have a reference to the object. So just something like

```
j = Job(app=GaudiRun())
j.submit()
j.remove()
```
In this case `j` will still have a reference to the application object. If you do `j.status` afterwards, you will see that the status is just `removed`.

**Comment by egede** [comment]
@rob-c A test along the lines of

```
j = Job()
j.prepare()
dir = j.application.is_prepared
j.application.unprepare()
assert(not is_dir(dir))
```

should do the trick as the unprepare at the end

**Comment by egede** [comment]
@rob-c I checked this in its simplest form, and at least with a `DaVinci` application is works correctly, so the shared directory is removed when quitting `Ganga` for a job that has been removed in the session.

**Comment by egede** [comment]
@rob-c The suggested test above unfortunately is a bit more tricky as even in this case, the directory is only removed when quitting `Ganga`.

**Comment by rob-c** [comment]
@egede I was under the impression that reducing the count to zero should trigger the removal of the folder. This should probably be addressed I think.
There is a very complex unittest in the old suite which we need to understand/port but I think we've been failing parts of that for a long time now.

**Comment by egede** [comment]
Looking closer at the code reveals that shared directories are indeed only deleted upon exit. This seems a poor choice and makes for a slower exit of Ganga. The suggested change is to delete directories as soon as the reference count goes to zero. The algorithm running at exit can also be dramatically simplified.
