### ISSUE TITLE
Nice avatar for the ganga-ci robot

### ISSUE THREAD

**Issue by alexanderrichards** [ganga-devs/ganga#65]
@milliams As one who is still using the github default I am hardly one to talk but I though it would be a bit more professional if we can give the ganga-ci account a nice avatar. I'm thinking something like the ganga logo... although this would make it indistinguishable from the ganga-devs organisation. Maybe that's a good thing? thoughts?

**Comment by milliams** [comment]
Done for @ganga-ci
