### ISSUE TITLE
Tasks using DIRAC should ask for proxy

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#653]
GangaDIRAC is intended to be executed without a proxy normally and to request one when it's needed.

Unfortunately LHCbTasks will fail to run correctly if a proxy is required. They currently attempt to submit a job and fail due to a missing Proxy.
I think this is minor bug possibly fixed by the credentials branch?

**Comment by mesmith75** [comment]
I think this is fixed so I'll close.
