### ISSUE TITLE
move fqid file naming logic out of MassStorageFile

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#657]
I'm planning to make 2 PR (maybe in 6.1.22 but probably later on due to other work).

The first of these will abstract the fqid file-naming logic out of MassStorageFile and will place it into a common utils file somewhere.

The second will try to take this and implement the same feature on the LocalFile as well as the DiracFile. (and possibly document how it's to be done for others).
I plan to add `outputfilenameformat` to the schema of both file types in order to do this.

Does anyone have any thoughts on this?

**Comment by egede** [comment]
Part of this has been implemented. The rest stale.
