### ISSUE TITLE
Running nightly tests against all targets

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#659]
Hi all,

I've just hit yet another bug where my code ran fine on my machine but failed in testing due to a different configuration.
As a small step to try and avoid problems like this creeping in I propose a minor change to the nightly script to run both the `Ganga/test` and `GangaPlugin/test` directories against the given environment and configuration of each plugin.

Is there a solid reason why we wouldn't expect all of the Ganga tests to pass for all users?

Rob

**Comment by drmarkwslater** [comment]
I believe the Nightlies already do run all plugin tests and actually, I've just checked and it seems that the `gridProxy` was being reported for the last couple of days. I'm not sure if the emails have stopped but I hadn't picked up on that myself...

**Comment by rob-c** [comment]
@drmarkwslater I was seeing problems with the grid proxy behind the scenes but not the missing GPI.

I'm expecting to see:
```
bash -ic "source $pl/testlib/setup_env.sh && py.test --junitxml tests-`basename $pl`.xml --runexternals Ganga/test/"
bash -ic "source $pl/testlib/setup_env.sh && py.test --junitxml tests-`basename $pl`.xml --runexternals $pl/test/"
```
but I can't find an equivalent to the first line in the nightly config atm. The $p1 is always _just_ the Plugin directory.

I'm seeing new bugs again due to LHCb vs Core with regard to what constitutes a job fail and how different classes behave as default. I think it would make sense to add the above line to the tests if there are no objections?

**Comment by rob-c** [comment]
Also I'm really not a fan of the line:

```
# Set up LCG etc.
source /etc/profile.d/grid-env.sh
```

The LCG setup changes how things behave and we're not testing Core-LCG with no extensions on the nightlies atm.

**Comment by drmarkwslater** [comment]
@rob-c These lines are in a bash loop:

```
find . -maxdepth 2 -mindepth 2 -type d -name "Ganga*" | while read pl
do
...
done
```

so `$pl` cycles through `Ganga`, `GangaAtlas`, `GangaLHCb`, etc.

**Comment by drmarkwslater** [comment]
@rob-c Actually, we are testing LCG in the Nightlies. @milliams put at least one LCG job submit test in a few weeks ago. This also makes sure all the env variables are set up for the Grid UI. If LHCb doesn't play well with that, they can be unset in the env script sourced before the tests are done.

**Comment by rob-c** [comment]
yes and ONLY runs the LHCb tests against the LHCb plugin etc. The tests are only running for 13min so aren't running the following combinations:

Ganga in Ganga env, Ganga in GangaLHCb env, GangaLHCb in GangaLHCb env, Ganga in GangaDirac env, GangaDirac in GangaDirac env...

This is where I'm seeing the problems, running the Ganga tests against GangaLHCb (nothing to do with LCG).

**Comment by drmarkwslater** [comment]
@rob-c OK, I understand what you're saying now. I guess running the Core tests in each environment would be fine but going beyond that becomes tricky, e.g. Should we run GangaDirac tests in GangaLHCb environment? etc. etc. Going forward we could setup some kind of matrix to decide what tests are run under which env I suppose.

**Comment by rob-c** [comment]
I agree it would be nice to define which tests can run in which env (probably in a top-level config file within each test folder).
Are there any objections to me trying to run the Core tests in the way mentioned above in all envs? This would at least highlight if we need to be explicit in the Core tests about what the expected defaults are for each test.

**Comment by drmarkwslater** [comment]
I don't see how it would hurt if restricted to just Nightlies for the moment. May be worth extending to PR Builder as well though it would double the time of the tests.

**Comment by rob-c** [comment]
I'll give the nightlies a test run and see if it works without problem, if it does I'll close this an open a new issue for developing some sort of matching about what tests should be run against what plugin.

**Comment by rob-c** [comment]
OK, I've set up the nightly to run the non-external Ganga tests against each plugin which is running and has pushed the nightly build time up considerably but it should help prove that there aren't any bugs creeping into Core that will adversely effect only a handful of users.
I'm going to open a better issue now so I'll close this
