### ISSUE TITLE
Testing backends (jobs not completing)

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#666]
Hi all,

I'm wondering if we can make a sensible policy here about how we test the backends?

The LCG test on nightly is failing when we attempt to wait for a job to be picked up and reach a completed state. I would argue we should **never** be testing for this in an automated way. We cannot.

I think we can safely attempt to submit jobs on each backend and attempt to update the information for a submitted job but we can never construct a test to rely on a backend propagating a job to a completed state.

I am proposing removing the `Ganga.test.GPI.LCG.TestLCG.test_job_complete` test or making it throw some error that is allowed relating to the test not reaching the final completed/failed state.

I would argue we can only ever test for a job completing against a _fully_ mock-ed backend for backends such a Batch, LCG, DIRAC (and others).
There we explicitly know that some information(files) are available and we can test that Ganga parses them correctly. We never know when running the tests that the backend will complete the job or not.

I only mention this as I'll likely start ignoring a set of tests which fails every single night and we end up back with a broken test system. I'm already getting emails in a thread which is 10+ emails deep (mostly unread), all to do with this job failing, and this will hide problems such as a nightly test having a more serious error.

Are there any objections to removing this test until we have a fully mocked LCG backend which will _always_ provide the expected output data for a completed LCG job?

Thanks,

Rob

**Comment by milliams** [comment]
I have a branch locally with a number of LCG and Grid tests with a mocked backend. I will be submitting it for review soon.

There's no need to outright remove `test_job_complete`, instead I'd suggest changing the:
```python
assert run_until_completed(j, timeout=1200, sleep_period=10)
```
line to
```python
stripProxy(j).backend.master_updateMonitoringInformation([stripProxy(j)])
```
to manually prompt the monitoring to run and then change the name of the test to `test_job_monitor`.

**Comment by rob-c** [comment]
@milliams My problem is what is the intention of this test then?
Is it intended to test the updated status code or the code that is invoked when the test has completed?

If there is a branch where this is going to go away then fantastic I'll wait for that to be merged as I'm in no rush. I just read about 10 emails after a week telling me that the same test keeps failing (at a cursory glance). If we're tackling this correctly with a mocked backend I can live with the noise until then :+1:

**Comment by alexanderrichards** [comment]
I 100% support the idea of having these tests with a mocked backend to check that our functionality is working. This then essentially makes these tests fast unit tests. However I thought that the point of the nightlies was to have longer integration tests running which test the whole system. It is useful for us to know if simple test jobs are running properly on the real backends not least because some of these test jobs are given as examples to new users.

**Comment by rob-c** [comment]
@alexanderrichards My mind for the nightly tests were tests taking many minutes to run or tests involving some external component i.e. submitting to the _real_ backend once a day rather than a fully mocked one.

Having said that I think there is still a place for putting fast backend related tests against a mocked backend into the PR tests (in fact I cannot wait for these to arrive as I can begin to profile individual parts of our code).

**Comment by alexanderrichards** [comment]
i think we are saying the same thing then right?

**Comment by rob-c** [comment]
:+1: I think it's worth being explicit with what we may or may not be expecting with the tests, if everyone agrees with this then great I think I can close this, I was just wondering what was going on given the repeated emails about LCG not running jobs.

**Comment by rob-c** [comment]
I'm still getting emails about LCG jobs failing in nightlies... any idea on an eta or should I patch the test so that it stops failing for now?

**Comment by egede** [comment]
Testing system replaced ...
