### ISSUE TITLE
Setting Lbscripts and LHCbDirac versions

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#667]
I have added some functionality to specify the version of LHCbDirac to use at runtime. It is just another LHCb config option. If left blank the default is used. It checks that the given version is valid by checking that the release folder exists - if it doesn't there is a warning and the default is used.

https://github.com/ganga-devs/ganga/blob/Lbversions/python/GangaLHCb/__init__.py#L25

``` python
configLHCb.addOption('diracVersion','',"set LHCbDirac version")
```

https://github.com/ganga-devs/ganga/blob/Lbversions/python/GangaLHCb/__init__.py#L83

``` python
def _store_dirac_environment():
    from GangaDirac.Lib.Utilities.DiracUtilities import write_env_cache, get_env
    diracversion = _guess_version('LHCBDIRAC')
    optionVersion = Ganga.Utility.Config.getConfig('LHCb')['diracVersion']
    if os.path.isdir("/afs/cern.ch/lhcb/software/releases/LHCBDIRAC/LHCBDIRAC_"+optionVersion):
        diracversion = optionVersion
    elif optionVersion != '' :
        logger.warning('LHCbDirac version %s does not exist, using default version %s instead',optionVersion,diracversion)
    logger.info("Using LHCbDirac version %s", diracversion)
    platform = os.environ['CMTOPT']
    fdir = os.path.join(os.path.expanduser("~/.cache/Ganga/GangaLHCb"), platform)
    fname = os.path.join(fdir, diracversion)
    if not os.path.exists(fname) or not os.path.getsize(fname):
        logger.info("Storing new LHCbDirac environment (%s:%s)" % (str(diracversion), str(platform)))
        cmd = 'lb-run LHCBDIRAC {version} python -c "import os;     print(dict(os.environ))"'.format(version=diracversion)
        env = execute(cmd) # grab the stdout text
        env = eval(env) # env is a string so convert it to a dict
        write_env_cache(env, fname)
    os.environ['GANGADIRACENVIRONMENT'] = fname
```

Not sure how to deal with the nightlies just yet.

**Comment by rob-c** [comment]
@mesmith75 I would prefer to see the the whole `_guess_version` code here go away entirely.

I think we want to declare that we expect a given version of LHCbDirac to be available and if not to warn the user (I'd say exit as well as there is likely a site mis-configuration but people running not at CERN can't all be expected to have LHCbDirac set up correctly).

If not I don't want us getting in a situation of not knowing what we're running with as the API may have changed underneath us.

I'd like to see the diracVersion defined explicitly as we move to use it on a line above the config option.
We _cannot ever_ rely on an afs folder exiting, many people are dropping it for cvmfs now so checking a folder exists is probably a bad way of checking on a version being available. I think it's sane to request it and check the rc of the lb commands to see if it's missing/unavailable.

**Comment by mesmith75** [comment]
I agree that checking a folder is not a very good idea. Would it be better to just set the default of the config option to the version we want?

**Comment by rob-c** [comment]
@mesmith75 The goal is to have the version of LHCBDirac we rely on hard-coded into https://github.com/ganga-devs/ganga/blob/Lbversions/python/GangaLHCb/__init__.py
This allows me to modify the release scripts to get the value from there for SetupProject backwards compatibility.
I don't think we can rely on any other way of testing if this is available unless we use `lb-run` or equivalent.

**Comment by egede** [comment]
I agree that the version should be hardwired. However, we need to think about how we want this to run with the nightly testing of LHCbDirac. There I guess we are using the development branch (or whatever the equivalent is) for LHCbDirac) and we need to be able to specify that.

**Comment by rob-c** [comment]
How about we have an option to point to a directory as with other CMake style apps so we can use the `./run` script to give us the environment?
