### ISSUE TITLE
importing GangaDirac turns off releaseNotes

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#676]
Short question,

Taking a look at `GangaDirac\Dirac.ini` I found `ReleaseNotes = False`.

Given GridPP users are likely importing this module to use Ganga is there a reason we're not advertising the changes on the first run of a new version?

I'm tempted to set this to True in a PR if nobody objects?

**Comment by milliams** [comment]
It's been set to `False` for as long back as our Git history goes. I agree it makes more sense to be turned on unless someone (@egede?) knows why not.

**Comment by egede** [comment]
It might cause a bit of confusion for LHCb users as we override certain 
parts in the GangaLHCb module but that is unlikely. So I agree it should be 
turned on.
