### ISSUE TITLE
Extremely slow performance for large job submission (XML and Dataset related)

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#68]
After running some profiling and benchmarking I've discovered that a large source of performance problems is in parsing the XML for a job.

In order to reproduce this I was attempting to run over a 'standard' LHCb dataset of 8082 LFN with a standard LHCb job that effectively just counted the integrated luminosity for each lfn.

This job would stall for a few minutes at a time which didn't make much sense as I don't see this sort of performance bottleneck in simple profiling.

This turned up too late to be considered for 6.1.14, although I wanted to track down and identify what was causing this performance problem before 6.1.14 was released to know if this was a deal breaker.

The problem that I see is that constructing 8k DiracFile objects takes approximately 40s to perform and storing this on disk as a flat array of DiracFiles causes ganga to pause for the 2-3minutes required to process the xml file.

I think for 6.1.15 I would like to rewrite the internals of LHCbDataset to store the LFN in a flat array of strings and act effectively as a generator producing the DiracFile on demand.

Given that there is now a generic GangaDataset I would like to add this generator type functionality there and have a GangaDataset class which is able to store 'flat' information and generate IGangaFile objects on demand which would be more sensible than simply generating 8k (or more) DiracFile objects and storing the full object on disk in a huge XML.

(This could prove tricky with iterators and such but should also reduce the memory footprint which is a bit higher than I would like it to be atm ~200Mb per job when submitting which can expand when the dataset is copied/modified.)

Hopefully this would allow for the LHCbDataset to become a lose wrapper around the Core GangaDataset providing some minor additional LHCb functionality on top of this.

**Comment by rob-c** [comment]
This particular problem can be lowered in priority I hope as I am seeing that this code which used to take several minutes is now down to below 1 minute. Not perfect but the overhead I think is something that people can live with. This does add a significant overhead when running over several large jobs with the monitoring loop, but optimising this is less important than many other tasks atm.

**Comment by rob-c** [comment]
OK, after some investigating I discovered that the XML for an LHCb job which contains 8082 DiracFile in the LHCbDataset is __14 M in size__ which explains why loading the job takes forever.
(Optimising the VStreamer will only get us so far parsing an XML this size is just always going to be slow)

I think moving to store only the LFN in the LHCbDataset and to generate DiracFiles as and when required is the correct way to go about solving this but will likely require some development to be compatible with these older jobs.

**Comment by milliams** [comment]
I think a possible solution to the XML reading/writing would be to switch over to using `xml.etree.ElementTree` since I've heard it is much faster.

Of course, anything we can do to reduce the size would be good since 17KB per file is too large. What does the average DiracFile XML entry look like?

**Comment by rob-c** [comment]
I've looked into the ElementTree in the past but this will likely require a completely new implementation of VStreamer from the ground up, although I think it supports parallel parsing of elements which could be nice.

The average DiracFile is only about ~10 lines of XML but with LHCbDataset from a book-keeping query most of that data is set to empty so we have an LFN stored about about 10 lines of empty string objects (and the empty subfiles).

The problem is that this obviously doesn't scale very well as bzipping one of these drops to ~55kb very quickly so this is highly compressible data. Granted maybe we could drop a lot of the whitespace in this file but the file is still too large to process in it's current form and constructing 8k DiracFile objects is a non trivial task as it takes a few seconds (I'm tempted to look into copying the objects from one already in memory in future rather than constructing a new object each time as this can potentially be a lot cheaper)

**Comment by milliams** [comment]
In which case I'm wondering about what the space is being used up by. A default-constructed DiracFile will be streamed to XML as:

```xml
<class name="DiracFile" version="1.1" category="gangafiles">
	<attribute name="defaultSE">
		<value>''</value>
	</attribute>
	<attribute name="namePattern">
		<value>''</value>
	</attribute>
	<attribute name="guid">
		<value>''</value>
	</attribute>
	<attribute name="remoteDir">
		<value>''</value>
	</attribute>
	<attribute name="compressed">
		<value>False</value>
	</attribute>
	<attribute name="localDir">
		<value>''</value>
	</attribute>
	<attribute name="lfn">
		<value>''</value>
	</attribute>
	<attribute name="failureReason">
		<value>''</value>
	</attribute>
	<attribute name="locations">
		<sequence>
		</sequence>
	</attribute>
	<attribute name="subfiles">
		<sequence>
		</sequence>
	</attribute>
</class>
```
which is only 721 bytes which is two and a half times smaller that the number you quoted above.

Actually VStreamer itself is not used for loading the XML, it's largely handled by expat with some custom hooks for starting and ending elements. I expect there's definitely some scope for some optimisation there. That said, I expect that the writing to dick is also a slow operation which could be optimised.

It certainly sounds like some of the slow-down here is coming from the time it takes to just construct a `GangaObject` which is something we will need to look into separately but is a noble goal.

**Comment by rob-c** [comment]
Yes it's done with expat but we'd have to do a lot of work to optimise which would be better spent with a more modern implementation if we suspected this is the bottleneck.

It's not particularly the I/O. The entire file is read and passed to the VStreamer as a text object in memory so my main problem is that the benchmarking shows all of the time is taken in parsing this HUGE text file.

I'm not sure what 721 bytes is smaller than. I am seeing 14Mb of data being taken up by this file!
```
14:02:44-CERN|~/gangadir/repository/rcurrie/LocalXML/6.0/jobs/0xxx/52
rcurrie@lxplus0064:->ls -l ./data
-rw-r--r--. 1 rcurrie z5 13991604 Jan 15 00:02 ./data
```

It is 275,052 lines long.

One file in this looks like:

```
                      <class name="DiracFile" version="1.1" category="gangafiles">
                         <attribute name="defaultSE">
                             <value>''</value>
                         </attribute>
                         <attribute name="namePattern">
                             <value>''</value>
                         </attribute>
                         <attribute name="guid">
                             <value>''</value>
                         </attribute>
                         <attribute name="remoteDir">
                             <value>''</value>
                         </attribute>
                         <attribute name="compressed">
                             <value>False</value>
                         </attribute>
                         <attribute name="localDir">
                             <value>''</value>
                         </attribute>
                         <attribute name="lfn">
                             <value>'/lhcb/LHCb/Collision12/DIMUON.DST/00020567/0000/00020567_00003624_1.dimuon.dst'</value>
                         </attribute>
                         <attribute name="failureReason">
                             <value>''</value>
                         </attribute>
                         <attribute name="locations">
                            <sequence>
                            </sequence>
                         </attribute>
                         <attribute name="subfiles">
                            <sequence>
                            </sequence>
                         </attribute>
                      </class>
```

Reducing the whitespace doesn't appear to effect the parsing speed significantly but helps readability

**Comment by rob-c** [comment]
It's currently taking some 40sec to parse this XML and a huge chunk of that is in constructing the GangaObjects. I suspect only creating the objects on demand is by far the best solution to this problem

**Comment by milliams** [comment]
I've looked into profiling this and this is what I see. If I run a Ganga script like:
```python
import cProfile
import pstats
from Ganga.Core.GangaRepository.VStreamer import from_file, to_file

j = Job()
j.inputfiles = [LocalFile(compressed=True)]*2000
j.outputfiles = [LCGSEFile()]*2000

to_file(j, open("test.xml", "w"))
cProfile.run('j = from_file(open("test.xml"))', 'read_profile')
assert j[0].inputfiles[0].compressed == True

jobs.clean(confirm=True)

p = pstats.Stats('read_profile')
p.strip_dirs().sort_stats('time').print_stats(10)
p.print_callers(.5, 'sleep')
```

then it prints:

```
Fri Jan 15 13:18:46 2016    read_profile

         6314114 function calls in 12.087 CPU seconds

   Ordered by: internal time
   List reduced from 116 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       16    8.036    0.502    8.036    0.502 {time.sleep}
    89236    0.434    0.000    1.006    0.000 Objects.py:404(__get__)
  1657932    0.426    0.000    0.426    0.000 {hasattr}
    30026    0.357    0.000    0.364    0.000 {eval}
   780534    0.264    0.000    0.595    0.000 Proxy.py:183(stripProxy)
   154412    0.236    0.000    0.656    0.000 Proxy.py:146(isType)
        1    0.224    0.224   12.086   12.086 {built-in method Parse}
    76083    0.205    0.000   11.517    0.000 VStreamer.py:338(end_element)
    12024    0.170    0.000    0.503    0.000 Schema.py:231(_getDefaultValueInternal)
    76083    0.146    0.000    0.171    0.000 VStreamer.py:283(start_element)


   Ordered by: internal time
   List reduced from 116 to 58 due to restriction <0.5>
   List reduced from 58 to 1 due to restriction <'sleep'>

Function      was called by...
                  ncalls  tottime  cumtime
{time.sleep}  <-      16    8.036    8.036  Objects.py:694(__createNewList)
```
so you can see that it takes 12 seconds to load the XML file, 8 seconds of which is spent doing `sleep` and that sleep is being called from `Objects.py:694(__createNewList)`. Removing
```python
while(len(final_list) != len(input_elements)):
    import time
    time.sleep(0.5)
```
and running again gives:
```
Fri Jan 15 13:21:01 2016    read_profile

         176997 function calls in 0.129 CPU seconds

   Ordered by: internal time
   List reduced from 114 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       20    0.014    0.001    0.014    0.001 {built-in method acquire}
     2236    0.013    0.000    0.027    0.000 Objects.py:404(__get__)
    46378    0.012    0.000    0.012    0.000 {hasattr}
     4854    0.007    0.000    0.020    0.000 Proxy.py:146(isType)
    22580    0.007    0.000    0.016    0.000 Proxy.py:183(stripProxy)
        1    0.006    0.006    0.128    0.128 {built-in method Parse}
      626    0.006    0.000    0.006    0.000 {eval}
      424    0.006    0.000    0.017    0.000 Schema.py:231(_getDefaultValueInternal)
     1883    0.005    0.000    0.112    0.000 VStreamer.py:338(end_element)
     1883    0.004    0.000    0.005    0.000 VStreamer.py:283(start_element)
```
so it's down to 0.129 seconds to read the same file. This is giving a 94 times speedup so I feel that this should be removed, especially as there's no explanation in the commit that introduced it ([2a2a2521f0768](https://github.com/ganga-devs/ganga/commit/2a2a2521f0768c3591db10fbd5299e06cbef15da#diff-3a5f5ed88f274eb570dccbab85337abfR731)) or in a code comment.

**Comment by rob-c** [comment]
It's there because the lists are being populated in parallel. Run the lists linearly and you see the same sort of performance.
Take out the check and you have an object in an inconsistent state

**Comment by milliams** [comment]
Ah, ok. Indeed I do see some problems. I'll look into this some more but regardless it seems that this is less due to the XML parsing and more to do with how the objects are constructed.

**Comment by rob-c** [comment]
I see that profiling finds 76% of the time is taken up in the __deepcopy__ method which is called about 12k times in constructing the job (not unreasonable when you consider there are 8k DiracFiles in the job).
Whilst I suspect that some optimisation can reduce the amount of time spent there I'm beginning to think this is much better solved at the higher level than by optimising low-level methods

**Comment by rob-c** [comment]
After some extremely aggressive optimisation of the code in Objects.py I can get this down to ~30sec from ~40sec but even then I'd rather not put the code into git.
I'm seeing 3 calls to create lists in the set method and these are consuming 89% of the time to run. I'm wondering if there is a smarter way of 'handing off' objects through VStreamer rather than by copying objects around this could potentially get a factor of 2 or 3 performance improvement over the current code if I'm correct.

**Comment by milliams** [comment]
With my latest benchmark it was taking 7 seconds to load a large job from XML. I then properly fixed the old bug which was causing loaded objects to not have a `_parent` set which then made it take 9 seconds. Removing the incorrect workarounds for the `_parent` but took it back down to 8 seconds but it was still slower than it started.

I then did some profiling and have reduced some of the hotspots and it is now down to 6.5 seconds. A lot of the remaining slowdown is due to the schema checking and default value getting so I think there's definitely some room for improvement. Once I've worked out the rest of the details I'll put in a PR. I don't expect it to solve all the problems but it's definitely a start. To some extent I think that just simplifying the code will help.

**Comment by rob-c** [comment]
I'm concerned that you say old bug of not setting the parent. This is fixed in develop last I checked unless there is something I've missed.
This aside I've got a pending PR which reduces the large amount of _setParent calls across a few classes which are strictly un-needed.
(This does require some attention to be paid by devs so I'll stick up a wiki on stuff around this at some point, including some slight oddities to do with performance in Ganga related code. I know it's all planned to go away in Python x but it's a problem that I'm seeing crop up time and time again.)

I'm still having problems with performance of loading a large XML even after some modifications, still 30sec after trying to reduce some bottlenecks from profiling.
I've setup the codebase to load the XML objects directly into the object already in memory.
This is rather than the current way of working which is to construct a default Job then copying the contents of the job from xml into the default job then leaving the job from the XML to be picked up by garbage collection.

I'll update this with the PR once I've sorted out my private repo.


Fully constructing a GangaObject class is still bugging me.
I would STRONGLY like to be able to capture the config state when an object is created and then we can dynamically assign the values to attributes only when they're called through the getter.
However as we can't do that we have to assign objects on construction based upon the values in the system config (which I'm still assuming can dynamically change)
(At the very least this feels more pythonic imo)

**Comment by milliams** [comment]
I've made PR #121 which, in my local testing, helps a lot with this. My benchmark is almost twice as fast now.

**Comment by rob-c** [comment]
I'm still having problems with large XML files taking some ~20sec to load so I suspect that this is as good as we're going to get. Still better than the 3min when this all started but still significant enough to make life difficult when working with very large datasets

**Comment by rob-c** [comment]
The loading of objects still appears to be very slow but I'm able to split and submit a very large job much faster as a result of #182 so this may fix a lot of the problem as it's observed by the users.

**Comment by rob-c** [comment]
I think we may be able to close this now for 6.1.17 I'm seeing submission times of well below 30min for 8,000 LFNs split into ~80subjobs using the new splitting tool. I suspect the recent advancements in the repo make us relatively immune to this.
