### ISSUE TITLE
6.1.20: Cannot run job in local backend

### ISSUE THREAD

**Issue by laurentdufour** [ganga-devs/ganga#683]
When running a DaVinci v40r2 script which has some files in the local user release area on a cvmfs machine, the following errors are encountered:

```
 File "/user/laurentd/gangadir/workspace/laurentd/LocalXML/143/7/input/./__jobscript__", line 189, in <module>
    getPackedInputSandbox(f)
  File "/user/laurentd/gangadir/workspace/laurentd/LocalXML/143/7/input/./__jobscript__", line 49, in getPackedInputSandbox
    with closing(tarfile.open(tarpath, "r:gz")) as tf:
  File "/cvmfs/lhcb.cern.ch/lib/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/lib/python2.7/tarfile.py", line 1684, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/cvmfs/lhcb.cern.ch/lib/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/lib/python2.7/tarfile.py", line 1731, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/cvmfs/lhcb.cern.ch/lib/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/user/laurentd/gangadir/shared/laurentd/conf-23f0ab2d-b077-4e9b-83c4-93bb19dedca8/inputsandbox/.nfs000000008bd7baf10000abd2'
Ganga.Lib.Localhost                : CRITICAL wrapper script for job 143.7 exit with code 256
Ganga.GPIDev.Lib.Job               : INFO     job 143 status changed to "submitted"
Ganga.Lib.Localhost                : CRITICAL report this as a bug at https://github.com/ganga-devs/ganga/issues/
```

The folder ```/user/laurentd/gangadir/shared/laurentd/conf-23f0ab2d-b077-4e9b-83c4-93bb19dedca8/inputsandbox/``` does exist and there is a .tgz in there.

I cannot test this with 6.1.22 as this version is still bugged on cvmfs.

When submitting this to Dirac it does run.

**Comment by rob-c** [comment]
Have you tried unpreparing the job and preparing it again? This looks like a filesystem issue due to a lockfile persisting when it shouldn't. There's little Ganga can do to prevent this.

That being said I'm currently looking at the mechanism where by shared files are made accessible to workernodes for backends with access to the local fs as part of 6.1.23 so I'll see if I can make it a little more robust and give better errors.

**Comment by laurentdufour** [comment]
Unfortunately the problem is persistent. I'll have a look whether the time it takes to do the bkquery has anything to do with it though or the version of ganga (I did not experience this in the past).
