### ISSUE TITLE
GangaDirac not handling externally killed jobs well

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#685]
Some users are reporting that jobs killed in the (LHCb?)DIRAC system are causing problems in the monitoring loop and triggering:
`ERROR    Unexpected dirac status 'killed' encountered`

I think this shouldn't take too long to track down and add a try/except handle around but the difficulty could be if this is being thrown from within a bulk request against DIRAC which would then need to be repeated.

**Comment by egede** [comment]
Isn't this just that the state killed is missing in the dictionary of Dirac 
states. This is just part of the configuration system note iirc.

**Comment by rob-c** [comment]
@egede I was assuming I could do something like this, the method which handles finalizing jobs looks for either `completed` or `failed` and I think we can mark a killed job as the latter. https://github.com/ganga-devs/ganga/blob/develop/python/GangaDirac/Lib/Backends/DiracBase.py#L611

**Comment by rob-c** [comment]
I think editing the `statusmapping` and the `finalised_statuses` within the .gangarc to map the dictionary entry `Killed` map to `failed` should suffice but I'll have to run a test before I commit any changes and close this.
