### ISSUE TITLE
Difficulty setting up Vanilla DIRAC job

### ISSUE THREAD

**Issue by alexanderrichards** [ganga-devs/ganga#686]
I think since this seems to be a credential problem that maybe @milliams is the best person to answer this but after just checking out the head of develop I get the following:

```python
[14:24:01]
Ganga In [5]: j=Job(backend=Dirac())

[14:24:04]
Ganga In [6]: j.submit()
INFO     submitting job 62
INFO     job 62 status changed to "submitting"
INFO     Preparing Executable application.
INFO     Created shared directory: conf-8fd0f3b6-4fc7-4531-b47d-47344c745a37
INFO     Preparing subjobs
INFO     Setting Command to be: '['echo', 'Hello World']'
INFO     submitting job 62 to Dirac backend
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/home/hep/arichard/git/ganga/python/Ganga/GPIDev/Adapters/IBackend.py", line 181, in master_submit
WARNING      if b.submit(sc, master_input_sandbox):
WARNING    File "/home/hep/arichard/git/ganga/python/GangaDirac/Lib/Backends/DiracBase.py", line 225, in submit
WARNING      return self._common_submit(dirac_script_filename)
WARNING    File "/home/hep/arichard/git/ganga/python/GangaDirac/Lib/Backends/DiracBase.py", line 148, in _common_submit
WARNING      result = execute(dirac_cmd)
WARNING    File "/home/hep/arichard/git/ganga/python/GangaDirac/Lib/Utilities/DiracUtilities.py", line 243, in execute
WARNING      env = getDiracEnv()
WARNING    File "/home/hep/arichard/git/ganga/python/GangaDirac/Lib/Utilities/DiracUtilities.py", line 42, in getDiracEnv
WARNING      DIRAC_ENV = get_env(source_command)
WARNING    File "/home/hep/arichard/git/ganga/python/GangaDirac/Lib/Utilities/DiracUtilities.py", line 62, in get_env
WARNING      execute('source {0}'.format(env_source), shell=True, env=env, update_env=True)
WARNING    File "/home/hep/arichard/git/ganga/python/GangaDirac/Lib/Utilities/DiracUtilities.py", line 248, in execute
WARNING      _checkProxy(force = True)
WARNING    File "/home/hep/arichard/git/ganga/python/GangaDirac/Lib/Utilities/DiracUtilities.py", line 208, in _checkProxy
WARNING      _dirac_check_proxy( renew, shouldRaise )
WARNING    File "/home/hep/arichard/git/ganga/python/GangaDirac/Lib/Utilities/DiracUtilities.py", line 169, in _dirac_check_proxy
WARNING      _isValid = proxy.isValid()
WARNING  AttributeError: 'bool' object has no attribute 'isValid'
WARNING  --------------------------------------------------
ERROR    JobManagerError: error during submit
ERROR    JobManagerError: error during submit ... reverting job 62 to the new status
INFO     job 62 status changed to "new"
ERROR    Error: JobError: Error: JobManagerError: error during submit
```

To avoid the LCG GLITE warnings I follow the startup suggestion and set
```ini
[LCG]
GLITE_ENABLE = False
```

I also have the following DIRAC setup
```ini
[DIRAC]
userVO = gridpp
DiracEnvSource = /home/hep/arichard/dirac_ui/bashrc
```

any ideas why it thinks that proxy is a `bool`?

**Comment by rob-c** [comment]
@milliams Have you come across this when working on the credentials I keep seeing this intermittently with some configurations although I can't remember what may trigger it or why I'm not seeing it myself on develop.

**Comment by milliams** [comment]
The credential can be a `bool` due to https://github.com/ganga-devs/ganga/blob/cdac0bb8693ab2850/python/Ganga/GPIDev/Credentials/__init__.py#L92 which can return `False` if it fails to get a credential. I guess this could happen if it fails to create the credential at bootstrap and then this code tries to fetch it. The logic there is a bit weird but that's where to start looking.

This is all moot with the new credential system as this code is gone.

**Comment by rob-c** [comment]
Why is this still all tied into the importing of the LCG I thought we were supposed to have separated that?

**Comment by alexanderrichards** [comment]
Thanks guys, If no one has any immediate ideas then I shall keep digging

**Comment by milliams** [comment]
@alexanderrichards Have you set `[LCG]VirtualOrganisation` to `gridpp`?

**Comment by alexanderrichards** [comment]
no as it was presented as an **either/or** option with `GLITE_ENABLE = False`. Since I didn't intend to use GLITE I opted to disable it altogether

**Comment by alexanderrichards** [comment]
I tried adding the `[LCG]VirtualOrganisation` option that you mention and I get the same error. If I remove the `GLITE_ENABLE = False` option but keep the former then I also get the same error except when starting ganga I also see:

```python
WARNING  Configuration of GLITE for LCG: 
WARNING  File not found: /afs/cern.ch/sw/ganga/install/config/grid_env_auto.sh
```
which since GLITE is enabled seems proper

**Comment by alexanderrichards** [comment]
FYI I can make this work if I force a default shell object to be instantiated irrespective of the GLITE config stuff at [GridShell.py@L68](https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/Utility/GridShell.py#L68)

```diff
- s = None
+ s = Shell()
```
I use this in conjunction with the config:
```ini
[LCG]
GLITE_ENABLE = False
```

and I now have `gridProxy` command correctly exported to the GPI and I can renew my proxy.

**Comment by rob-c** [comment]
@alexanderrichards Do the startup errors also go away with this?

I don't think there's any problem with forcing the construction of this here, although maybe we should put it at line 105 so that there is always a shell created and not multiple shells for people wanting to use GLITE or related code.

As long as it doesn't shout at users who don't plan to use it I'd like to see a PR which fixes this

**Comment by alexanderrichards** [comment]
For using DIRAC grid proxy tools I also need to set the following config options:
```ini
[defaults_GridCommand]
init = dirac-proxy-init -g gridpp_user -M -t
info = dirac-proxy-info
destroy = dirac-proxy-info
```

**Note** however that for me at least in a vanilla environment this was *not* sufficient. Ganga would complain that there was no such command as `dirac-proxy-xxx` (i.e. no correct Dirac UI in the calling process).

After consultation with @rob-c it seems that his solution is to modify the above to the following:
```ini
[defaults_GridCommand]
init = source /home/hep/arichard/dirac_ui/bashrc && dirac-proxy-init -g gridpp_user -M -t
info = source /home/hep/arichard/dirac_ui/bashrc && dirac-proxy-info
destroy = source /home/hep/arichard/dirac_ui/bashrc && dirac-proxy-info
```

After doing this things do indeed now work fine.

---

This however is *very* convoluted and I don't know how users are expected to be able to do this. What's more this seems pointless as we already give Ganga the path to the Dirac bashrc in the DIRAC config section:

```ini
[DIRAC]
DiracEnvSource = /home/hep/arichard/dirac_ui/bashrc
```
Is it worth perhaps looking at picking this up automatically when running the grid commands or should we just wait till @milliams credentials patch nukes all this? At the very least I've found it useful to look into and document it in this issue such that if anyone comes across it in the future we know what to do.

**Comment by rob-c** [comment]
I vote to wait for the credentials branch before we consider trying to fix the DIRAC commands in the config as there are some really unstable areas of code in the old credentials lot which I think this proves. We'll be in a better position when it's all been thrown out for something more modern.

**Comment by alexanderrichards** [comment]
> @alexanderrichards Do the startup errors also go away with this?

Yes, for me at least all is calm again after this patch

> I don't think there's any problem with forcing the construction of this here, although maybe we should put it at line 105 so that there is always a shell created and not multiple shells for people wanting to use GLITE or related code.

Anywhere there will have the same effect, there is one variable s which is returned I just defaulted it to a default shell. If someone with the GLITE options enabled then they will just re-bind to a more specific one.

> As long as it doesn't shout at users who don't plan to use it I'd like to see a PR which fixes this

I don't mind doing this if there is agreement between people but as I mention before @milliams credentials branch will nuke this anyway

**Comment by alexanderrichards** [comment]
Closing as the credentials branch with fix this in a more permanent way.
