### ISSUE TITLE
Proposal for a new `internal` attribute for SharedDir

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#689]
Hi all,

I'm considering a hidden attribute to the Job schema (with default of False) to mark a file as internal. I propose the name `internalFiles` unless anyone has a better naming convention.

The intention of this is that if an application (`GaudiRun`) generates a file on a remote fs (`DIRAC`) then the file can be placed in this list without the user being aware of this file. And then we can add some hook into the remove methods to remove all ganga-internal files from storage which were auto-generated by the job during submission.

These files are intended to be different to the prepared state files which are stored in the shared directory of Ganga.

At the moment the `GaudiRun` application is generating `DiracFile` objets and storing them in the application as hidden attributes. This is fine but the objects aren't removed unless the application is unprepared and so it's not 100% clear when they will be removed from Dirac (if ever).
I feel it would be much better to store these files in the Job object rather than having to fudge in some sort of application clean-up logic in the Job remove section.

I won't be looking to add this until likely after 6.2.0 but it would make managing files generated by `GaudiRun` and other apps easier I feel.

Does anyone have any thoughts about this?

Thanks,

Rob

**Comment by egede** [comment]
@rob-c Do you see this as something that is unique to every job (so not a copyable attribute)? If not, then you will have to consider reference counting. If you want that, it might be worth considering the capability you discuss as an extension of the shared area mechanism instead.

**Comment by drmarkwslater** [comment]
@rob-c This sounds similar to how we deal with log files/stdout/stderr. Should these files not be handled by the RT handler of the app (or backend) completely behind the scenes? I know in Atlas that the RT handler simply adds a few files to the output description and deals with those when the job completes. Now I'm not sure what would happen to these files when you delete a job (do we have an 'on remove' hook for an application?) but I'm not sure if an additional set of files is needed.

Having said all that, it may be nice to standardise how we deal with internal input and output files for a job...

**Comment by rob-c** [comment]
@drmarkwslater Not quite, the problem here is we have to generate files on the remote storage system (DIRAC) which then causes the problem of who should delete the files and when if these files are related to the prepared state of the job.

@egede These files aren't strictly re-generated. At the moment I have 1 file which contains the contents of the prepared state which should remain on disk as long as this job is prepared. In addition I have a 2nd file which contains a lot of the actual scripts which Ganga runs on the WN.

After some thought I'm wondering if a shared file within the SharedDir object may be a better idea. This has the limitation that a resubmit for jobs using this will resubmit almost exactly the same code and if there is a bug in generating the job scripts in Ganga the user would have to unprepare and resubmit a job. Somehow this feels like a minor inconvenience to sharing the prepared files on DIRAC/elsewhere in a sane way.

**Comment by drmarkwslater** [comment]
@rob-c Not thinking through all the implications, this sounds like a better idea as this specifically links the internal files to the prepared state (which seems to make sense to me) and I would say if you resubmit a job you would expect it to run the exact same code. If you do want to change it, an unprepare and resubmit is a pretty small price to pay.

One thing I would offer caution on though - if someone is in the habit of just submitting each job from scratch each time, they will generate a lot of these files on DIRAC storage and then if they either don't remove them or just remove their gangadir these files will basically become zombies. I personally think this is OK and expected behaviour but it might require a bit of user education 😄

**Comment by rob-c** [comment]
@drmarkwslater At the moment these files are also placed in a sensible location so I could add a howto in the `GaudiExec` doc on how to remove the parent folder and clean up their Dirac storage.
It would be nice to tie an LFN into the dirac job cleanup service but I imagine this to be difficult and beyond the scope of ganga.
