### ISSUE TITLE
Move workernode templates

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#69]
Hi all,

The naming of the workernode templates when they were extracted from the code was a bit bad and causes problems with code profiling tools etc.
It would be nice to at least change their file extensions so that it's clear this code isn't run in place.
Maybe even some work to turn these script templates into 'pure' python code in some cases.
I'm thinking that passing a dictionary of the inline replacements as arguments to these classes should be enough to do this.

I think this should be a relatively minimal task to do but touches a fair few files, it would be nice to get done in 6.1.15.

Thanks,

Rob

**Comment by milliams** [comment]
This is something I've discussed with @drmarkwslater and we agree. There's been some fixes to this already in the *feature/python-importing-new branch*. Given that these scripts are simply being run on the command line I think passing what we can as arguments to the scripts would be beneficial. The only other problem is that in a few places, the final script is assembled from a number of template files which is perhaps less than ideal.

**Comment by rob-c** [comment]
I'll take a look and try and cherry-pick these diffs from that branch to avoid duplicating effort.

I'm tempted do some playing around with porting the Interactive script to use methods on a branch and see if there is anything to be learned from the experience. That is unless someone has already started elsewhere then I'm happy to see what's been done so far :)

**Comment by egede** [comment]
@milliams The final scripts are assembled from several pieces due to the plugin nature of what is executed. If the user ask for output of type DiracFile, then a piece of code that can do that upload is appended to the script. I guess you could then upload that as a separate script that then takes another set of arguments, but that could end up a bit messy (the outer script would have arguments that are the name of other scripts including their subsequent arguments).

Ulrik.

**Comment by rob-c** [comment]
@egede We could write a worker node script which calls 'static' functions if they've been defined. this would still allow for functionality to be 'injected' into the scripts before they're run.
How easy this is to do in practice now that I've said it I don't know

**Comment by milliams** [comment]
@rob-c am I right in thinking that you did this move now?

**Comment by rob-c** [comment]
This has been done in 6.3
