### ISSUE TITLE
GaudiExec to support multiple options files

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#697]
Hi all,

I'm wondering if there is the call to support multiple options files with the `GaudiExec` application?

In principle this is a minor set of modifications to merge the options or to import them as appropriate.

I think the `options` attribute with `extraOpts` should be enough for 99% of use cases but do power users require the ability to easily have multiple options files passed to steer a CMake job?

If this is required I can look into it after 6.1.23 but if it's not I'm happy to close this as won't fix.

Thanks,

Rob

**Comment by egede** [comment]
@rob-c You are referring to the fact that the options attribute is a single GangaFile object rather than a list of GangaFile objects?

**Comment by rob-c** [comment]
I'm thinking of supporting a list of IGangaFiles in the `options` attribute. At the moment this won't fully work due to some limitations in the code I've written.
It is possible to expand what is there but I went for supporting the simplest use-case first.

**Comment by egede** [comment]
@rob-c Yes, the support of a list would be good. Many of the suggestions for how to do things in LHCb use a list of options file. It should not hold up 6.1.23 though.

**Comment by rob-c** [comment]
I've implemented this as it required a change of the Schema so I think getting the Schema sorted sooner rather than later is better than convincing people to do some sort of update later on for a new feature.
