### ISSUE TITLE
Cannot support negative indexes

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#705]
I've had a stab at re-enabling the negative index notation for the RegistrySlices and have hit a problem:

I have a registry with 90 jobs with the jobIDs ranging from 1 to 353. i.e. lots of deleted jobs:

`jobs[-1:]` actually passes the slice `slice(90:sys.maxsize:None)`
(i.e. the `-1` string is pre-processed away at some level in IPython/ast as far as I can tell and `len(jobs)` returns 90.)

This causes a problem because doing the following works:
`jobs[90:]` gives `slice(90:sys.maxsize:None)`

This can be fixed by getting the `len(jobs)` to return `353` but this would cause problems due to then trying to do: `assert len(jobs[5:6]) == 2` as `len(jobs[5:6])` has to be 6 for `jobs[5:6][-1]` to return `jobs(6)`.

At this stage I'm thinking we can't sensibly enable negative indexes due to the problem of mapping these indices against the position in the registry dictionary.

Does anyone have any experience with this section of the code? I'm suspecting this could be an IPython feature(bug?) but I'm yet to test against IPython4.

(I'll likely leave this on the back burner for now as I was only interested in pursuing this if I could get it working in a few hours in my spare time.)

**Comment by alexanderrichards** [comment]
what about

```python
def __getitem__(self, index):
    if not isinstance(index, (int, slice)):
        raise TypeError("index must be of type int")
    if isinstance(index, slice):
        start = index.start if index.start is not None else min(data)
        stop = index.stop if index.stop is not None else max(data)
        step = index.step if index.step is not None else 1
        return [ data[i] for i in xrange(start, stop, step)]
    if index < 0:
        return data[sorted(data.keys())[index]]
    return data[index]
```
---
**Note** I've used the ternary operator for a condensed post here, feel free to expand it if you don't like it. Also I've used the assumption that the jobs are in a dictionary which is keyed on the jobid which I think is correct.

**Note also** The subtle difference from a normal indexable list in that calling `getitem` will in the case of positive integers get the corresponding entry from the dictionary i.e. `jobs[3]` will get the job with id 3 even if it's the first job in the jobs list. However with negative integers we return to the usual list behaviour of `jobs[-1]` getting the last element. I think that this is the most intuitive user expected response as they expect a mapping by jobid.

**Comment by alexanderrichards** [comment]
> jobs[-1:] actually passes the slice slice(90:sys.maxsize:None)
> (i.e. the -1 string is pre-processed away at some level in IPython/ast as far as I can tell and len(jobs) returns 90.)

for the last element, I don't think you want to be slicing with the : notation simply just `jobs[-1]`

**Comment by milliams** [comment]
@rob-c This is the reason that negative indexing was removed. `jobs` is conceptually a dictionary, not a list and  so does not support any assumption about the ordering of the keys. Slicing a dictionary does not make much sense since we do not have contiguous keys.

**Comment by alexanderrichards** [comment]
@milliams I think that there is still room for negative indexes. Especially as most recently created jobs go to the end of the list. It is far easier to do a 

```python
j=jobs[-1]
```

than

```python
jobs
<ah I have 900 jobs>
j=jobs(900)
```

**Comment by alexanderrichards** [comment]
> Slicing a dictionary does not make much sense since we do not have contiguous keys.

Also isn't this just supposed to return a new registry slice?

e.g. if I do

```python
jobs[3:10]
```

I'm pretty sure that we used to return a new slice with just jobs with `3<=ids<=10` in this case slicing does make sense

**Comment by alexanderrichards** [comment]
I see nothing wrong with negative indexing or slicing even though we do maintain the jobs as a dictionary mapping from job id to job object. Mainly because we present them to the user in a list type interface.

**Comment by rob-c** [comment]
@milliams It should be possible to translate the request to get relative positions within the dictionary. It's wholly possible as long as IPython(Python?) was passing us the raw negative index which can be used with some logic to do the right thing. Slicing the dictionary is potentially very powerful I'm just very concerned about the whole negative index thing not being what it should be.
The issue is more a question of what `[-1]` should return. I contest it should always be the final value of the `ids` but some logic is determining it to be `[len(object)]` which whilst in most cases is the same is obviously wrong here.

@alexanderrichards I've tried exploring what the index value was when using getslice vs getitem but we seem to have little control over this and getslice is always being looked for at some level.
(This could be an IPython 1 bug as IPython2+ is Python3.x compatible so should have deprecated the getslice method entirely).

There were users who used to rely on this who weren't happy that their scripts broke during the 6.1 transition but there weren't too many of them.


Should we drop the list type interface entirely if the logic is broken?
Offering it would only make sense if it worked or failed but if a user uses a negative index they potentially get a random job which will just cause issues.

(Offering support for `(-1)` should be easy as this isn't auto-parsed away I think)

**Comment by alexanderrichards** [comment]
Furthermore, one last point if you'll indulge me. While `jobs` does indeed *contain* a `dict`, it *is not* a `dict` from an OO point of view as it inherits from  `RegistrySlice`. We are therefore at liberty to define the behaviour we see fit. I would point out that we already mix in list type behaviour, e.g.

```python
for j in jobs:
    print j.status
```

doing this with a `dict` would yield j as the keys, i.e. the jobids not the job objects themselves as we currently have (which I think is what users expect).

**Comment by alexanderrichards** [comment]
> I've tried exploring what the index value was when using getslice vs getitem but we seem to have little control over this and getslice is always being looked for at some level.

`__getslice__` should be deprecated and then `__getitem__` will be correctly called with the slice object.



> Should we drop the list type interface entirely if the logic is broken?
> Offering it would only make sense if it worked or failed but if a user uses a negative index they potentially get a random job which will just cause issues.

I've said my piece already. Having had to use Ganga again recently, the lack of a negative index in jobs has been my biggest annoyance. I don't believe that we will get a random job or that it will fail. The example I gave above is guaranteed to return the job with the largest job id as returned by sorted. So I would say no don't scrap it, at the negative indexes back in but do it properly without using `__getslice__`

**Comment by alexanderrichards** [comment]
P.s. There is no problem slicing with the version of IPython that we are currently using for Ganga, I just tested and it works as expected, see below. I suspect that when you remove the `__getslice__` method things will work as expected for you as well.

```python
class mytest(object):
    def __getitem__(self, index):
        return index
[11:32:26]
Ganga In [2]: m = mytest()

[11:33:08]
Ganga In [4]: m[1]
Ganga Out [4]: 1

[11:33:10]
Ganga In [5]: m[-2]
Ganga Out [5]: -2

[11:33:13]
Ganga In [6]: m[1:13:4]
Ganga Out [6]: slice(1, 13, 4)

[11:35:26]
Ganga In [8]: m[::3]
Ganga Out [8]: slice(None, None, 3)
```

**Comment by rob-c** [comment]
Have you tried slicing with negative indexes?

**Comment by alexanderrichards** [comment]
yes
```python
[11:35:35]
Ganga In [9]: m[-1:-3:-1]
Ganga Out [9]: slice(-1, -3, -1)
```

**Comment by rob-c** [comment]
OK, so there is some issue with the Ganga code because I clearly am getting slices without negative indexes which is very, very bad.

**Comment by alexanderrichards** [comment]
did you try removing the `__getslice__` method as I suggested?

**Comment by rob-c** [comment]
@alexanderrichards Last time I did that it all fell down with exceptions so I redirected it to `__getitem__` from within the derived class. I'll try and remove the method again now and see where I get.

**Comment by rob-c** [comment]
@alexanderrichards OK removing the `__getslice__` methods appears to work. I do get the negative indexes correctly passed in a slice object in this case. I suppose there must be some old logic around the behaviour of the now deprecated methods which were being used before.
I'll knock together a PR as this should be quite quick to fix.
