### ISSUE TITLE
New monitoring system

### ISSUE THREAD

**Issue by milliams** [ganga-devs/ganga#71]
The current monitoring is a mire of threads, queues and locks which has grown to the point where it is extremely fragile. Long-term we have expressed a wish for a system which looks like the following:

> An external monitoring dæmon, written in Python 3 and using asyncio which, given a repository on disk will make all the calls to external services to check job status, download output (and do the submission?)

Of course, this doesn't solve the problem of having more than one agent needing to be able to write to a repository so we would still need lock files or make the dæmon act as a server too which all Ganga clients talk to (the dæmon would then maintain a queue of incoming new jobs and change requests).

Since we cannot rely on Python 3 yet, we cannot go straight to this system but an intermediate system which has the same interface characteristics could aid the transition.

The aim of this issue is to log our discussions on this topic to get an understanding of how a final system could look as well as the best way to progress towards it.

**Comment by alexanderrichards** [comment]
Hi matt, thanks for starting this topic. 

@ganga-devs/core 
I was thinking some more about this and realised that we would really like DIRAC to be a daemon as well as it can run in it's own environment. Other potential packages (LHCb or Atlas etc) might indeed want other services in separate environments. We could perhaps then look at a generic solution like below.

__process: services manager__

This would be responsible for registering (processes) services. Package developers would use something like servicemanager.register() to register a service in their `__init__` so the services are registered when you load in a package. This servicesmanager would start when any ganga client starts and only one would run at any given time. It could then be used to start a service (if not started) and return an RPC client to the service:
```python
dirac = servicemanager.getRPCService('Dirac')
dirac.submitjob('blah')
```
where obviously servicemanager here is bound to the RPC client for the servicemanager process.

Then there would be some obvious services that we would want to run for any ganga client instance like monitoring loop and probably a centralised job repository which as you say could have a queue of incoming jobs etc. In this scenario all repository access goes through this service so the monitoring loop service would also have something like

```python
job_repo = servicemanager.getRPCService('JobRepository')
for j in job_repo.select_jobs(status=['submitted', 'running']):
    do stuff
```

With the caveat that I have not really thought through all the consequences or indeed any of the implementation yet how does this sound as an idea?

**Comment by milliams** [comment]
There is some interesting discussion about the current system at #139.
