### ISSUE TITLE
Job preparation fails, but still gets submitted

### ISSUE THREAD

**Issue by rajanandakumar** [ganga-devs/ganga#721]
Dear Developers,

I have a job which failed to get prepared. However, the preparation status of the application is still valid. So, after the preparation stage, if I try to submit the job, submission is successful, which I suppose is incorrect behaviour.

Do let me know if you need more information from me. A traceback of what I did to reproduce this report is in the attached txt file.

[GangaBugReport.txt](https://github.com/ganga-devs/ganga/files/410039/GangaBugReport.txt)

Cheers,
Raja.

**Comment by rob-c** [comment]
Hi Raja,

Unfortunately I think the majority of the LHCb development work moving forward will be around the `GaudiExec` application object being released in 6.1.23 which should fully support split complex jobs with CMake.

The main bug here appears to be in `DaVinci` itself or some other LHCb project I would argue. Ganga shouldn't be submitting the job which is a bug in how this application object is failing to un-prepare itself on error.
If it's a quick fix then it may be possible to make a quick PR but unfortunately there are time constraints on the amount of development we can do on old applications which are being kept around mainly for backwards compatibility,

I'll see if I get a chance to look into this by the end of this week but I suspect this may end up being marked as `won't fix` if the problem gets too complex.

Rob

**Comment by rajanandakumar** [comment]
Hi Rob,

It is not a critical error, so downgrading the priority is fine with me.

About the difficulty, I suppose it is not very difficult. From what I see with non-expert eyes, you need to just trap the ApplicationConfigurationError somewhere around line 1572 or 1578 in the Job.py file and just unprepare the job for this error. Of course, there are probably easier ways out too.

Cheers,
Raja.

**Comment by rob-c** [comment]
Hi Raja,
I think you're correct in your assessment, I'll look into adding a global step to un-prepare any job which failed to prepare just incase the application/job object isn't cleaning up properly. This may arrive in 6.2.1 or 6.1.24,
Rob
