### ISSUE TITLE
List of arguments in Dirac executable are ignored

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#724]
The arguments for an Executable application are being ignored.

The arguments are a list that is the executable command followed by the list of arguments. In the exe_script this is then executed via subprocess.call(exe_cmd, env=my_env, shell=True)
https://github.com/ganga-devs/ganga/blob/develop/python/GangaDirac/Lib/RTHandlers/ExeDiracRTHandler.py#L160

The problem seems to be that for shell=True the executable should be string not a list. At the moment it just takes in the first item (the bit to run) and ignores the rest. Should shell=False instead?

**Comment by alexanderrichards** [comment]
This is a duplicate of #521
