### ISSUE TITLE
New LHCb Gaudi application type

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#73]
A new LHCb application type should be created. It should work with the new structure for the private relase areas based on lb-dev and lb-run.

## Connection to old Gaudi types
There should be no connection to the old application types for Gaudi based applications.

## New GaudiRun application type
* The new application type should be called *GaudiRun* (as a way to distinguish it from the existing 
*GaudiPython* type). It will not need any specialisation for Brunel/DaVinci etc.
* The schema will have
  *  is_prepared = None ,
  * extraopts = None ,
  *  args = [-T]  ,
  *  platform = 'x86_64-slc6-gcc48-opt' ,
   * lb-runtOptions = '' ,
  *  location = '' ,
  *  optsfile = []  
 The *location* attribute is where the release is located. There default value should now be empty for this and the job submission should fail if empty.

## Implementation
 * Marco Clemencic will provide script that can encapsulate environment.
 * Marco Clemencic will provide build target which can pack up local shared libraries.
 * Caching of the environment for running should initially be avoided as there are some tricky issues
 * Implementation that works without local shared libraries should be possible initially without the
  build target above in place.

**Comment by rob-c** [comment]
Hi Ulrik,

I'm thinking that this would be a nice required schema component if for no other reason than for helping users with book-keeping and knowing what job was what.

e.g:
```j.application = GaudiRun(app='DaVinci', location='my/DaVinci/path')```

I think if we ask for it we should avoid using it as much as possible in the App to keep the code generic but having this upon construction makes life a bit easier imo.

It would also allow us to use Bender with the new GaudiRun application as it requires different runtime scripts which we'd need to use only with this application.

This is looking like quite a light weight application to write if we are relying on the build targets from the cmake style apps. I'm going to try and duplicate the functionality that I see in the existing Applications and hopefully this shouldn't take too long.

**Comment by egede** [comment]
> I'm thinking that this would be a nice required schema component if for no other reason than for 
> helping users with book-keeping and knowing what job was what.

@rob-c I do not think this works. It is possible with the `lb-dev` command to create release areas that are no longer associated with any of the *traditional* applications.

**Comment by alexpearce** [comment]
[We](https://github.com/lhcb/starterkit) are preparing lessons for [the next Starterkit](https://indico.cern.ch/event/517378/), which aims to cover more advanced topics than in the [first Starterkit](https://github.com/lhcb/first-analysis-steps). We'll be covering the use of `lb-dev` (we used `lb-run` almost exclusively in the beginner lessons), and I'd like to check the status of `lb-dev` integration in Ganga.

My understanding of the situation right now is: `lb-dev` is not supported ‘natively’ by Ganga, but one can circumvent this by creating a symbolic link to the `InstallArea` created in a `lb-dev`-generated project in a folder in `~/cmtuser`, and then proceeding in Ganga as normal.

The main question is: what would be best to teach the students? One the one hand, it would be ideal to teach developing LHCb software using `lb-dev`, as it's the future. On the other hand, using `lb-dev` with Ganga requires a ‘hack’ that may or may not work in the short-term future, and that may soon be superseeded by native support.

If the symlink hack does indeed work, do you think it's worth teaching it?

**Comment by rob-c** [comment]
@alexpearce I think this is probably the best solution to using cmake style apps with Ganga atm.

There is the risk that for more complex build and private code changes that Ganga may mis-package some input sandboxes by using out of date commands but for tutorial work and 90%+ of users I think this shouldn't be a problem.
@egede I can't think of any reason why teaching this would be a bad thing to do can you?

I'm hoping to look at finishing cmake support as my main development task for 6.1.21 or maybe a little later depending on other work in the Ganga release cycle.
@alexpearce Would you be able to link me to any documentation so that when cmake support arrives I can update any wiki entry accordingly (if it is in a wiki format).

**Comment by alexpearce** [comment]
I make an `lb-dev` project, make some changes, and then symlink the `InstallArea` directory:

```shell
$ cd ~
$ lb-dev DaVinci v36r6
$ cd DaVinciDev_v36r6
$ getpack Phys/DecayTreeTuple
# make edits...
$ make -j8
$ make install
$ mkdir -p ~/cmtuser/DaVinci_v36r6
$ cd ~/cmtuser/DaVinci_v36r6
$ ln -s ~/DaVinciDev_v36r6/InstallArea
```

I'm just adding `std::cout` statements, but when I run DaVinci I don't see any.

```python
j = Job(name='DVTest')
j.application = DaVinci(version='v36r6')
j.application.optsfile = ['/path/to/decaytreetuple_options.py']
j.inputdata = ['/path/to/input_data.root']
j.submit()
```

I don't see my print statements in the logfile. Is there something else I need to do?

**Comment by alexpearce** [comment]
If I also symlink `~/DaVinciDev_v36r6/cmt` and `~/DaVinciDev_v36r6/DaVinciDevSys` then I am able to run `SetupProject DaVinci v36r6` and see that it picks up my local version. So I think that's working.

But then when I run I get an error:

> Cannot create tool TupleToolGeometry (No factory found)

I think this is something to do with the shared library resolution. DaVinci isn't able to load the library is for `TupleToolGeometry`, which is in the `Phys/DecayTreeTuple` package (I didn't edit that class, but I guess I'm getting this error just because DaVinci happens to load the geometry tool first).

**Comment by alexpearce** [comment]
I symlink'd the wrong folders. It works!

**Comment by alexpearce** [comment]
He's the lesson that explains the procedure:

https://lhcb.github.io/second-analysis-steps/01-ganga-with-cmake.html

A PR or issue can be opened on [the GitHub repo](https://github.com/lhcb/second-analysis-steps) when things in Ganga change.

**Comment by rob-c** [comment]
I think I need to extend this application to allow us to control the architecture. At the moment it only supports the running environment ganga is in to build a target. However, I have put an initial `GaudiRun` object in with #578. 
There is the potential for more options to be added and the schema expanded after some user testing so I think I'll keep this issue open until 6.2 and once 6.2 is out we can raise individual issues for required extensions to the `GaudiRun` Application.

**Comment by rob-c** [comment]
OK, the GaudiRun application has quite a few of the initial features and I'm opening specific tasks highlighting individual features it now needs so I'm going to close this shortly (probably with 6.1.22).
@alexpearce Would it be possible for someone (probably more familiar with LHCb software than myself) to test the new Application against the tutorials and work out if anything is missing?
(Aside from Gauss+GaussSplitter I'm not aware of any major problems with trying to use it as a replacement now for most applications within Ganga.)

**Comment by rob-c** [comment]
I think I can close this issue given we now have GaudiExec support and any issues with that should be opened in separate issues
