### ISSUE TITLE
Error resubmitting 'completed' bad subjob on DIRAC backend

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#732]
I'll include the original email from Raja below but it appears we're not allowing for correct state transitions within the DIRAC backend for 'completed' but bad jobs on resubmit.
I suspect this could be some call to `setState` is incorrect and the job state should have been cycled back to some other state first for resubmit.

```
Hi,

Using ganga 6.1.23, I have the following strange behaviour of a job : it has failed (or whatever - it is in a terminal state as far as the backend is concerned), but the job thinks it is still running. So, I am still not able to resubmit it. Log below.

Is there something I am doing wrong? I have now forced the status of the job to "failed", and then the auto-resubmit option came into force, but I thought I should report behaviour this anyway.

Cheers,
Raja.

==========================================================

[10:55:59]
Ganga In [50]: jobs(145).subjobs(26).backend
Ganga Out [50]:
 Dirac (
   status = Completed,
   actualCE = LCG.CERN.ch,
   settings = [CPUTime],
   normCPUTime = None,
   extraInfo = gaudi-script.py Exited With Status 135,
   diracOpts = ,
   statusInfo = Application Finished With Errors,
   id = 137491754
 )

[10:56:11]
Ganga In [51]:

[10:58:04]
Ganga In [51]: jobs(145).subjobs(26).backend.status
Ganga Out [51]: 'Completed'

[10:58:15]
Ganga In [52]: jobs(145).subjobs(26).resubmit()
INFO     resubmitting job 145.26
ERROR    cannot resubmit job 145.26 which is in 'running' state
ERROR    Error: JobError: cannot resubmit job 145.26 which is in 'running' state

[10:58:18]
Ganga In [55]: jobs(145).subjobs(26).status
Ganga Out [55]: 'running'
```

**Comment by rob-c** [comment]
After looking around this could be intended behavior due to the monitoring state of the job. I'll ask Raja to confirm.

**Comment by drmarkwslater** [comment]
This is certainly consistent from the `resubmit` part of the logic. The question is should this job have been marked as `failed` by Ganga - not sure about the answer to that one 😄

**Comment by rob-c** [comment]
I think we should use a query against the `backend.status` to trigger a completion event to cycle the job status as I suppose the job could be in a `running` state in Ganga but look completed after a `backend.status` query which should probably trigger a job status update imo.
I think this isn't critical for 6.2.0 but 'would be nice' as you can force it to be failed then resubmit ganga side...
