### ISSUE TITLE
MassStorage file problem

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#733]
Problem found by LHCb user is:

```
I am using a fresh: v601r23 version and I ma getting the following error:

ERROR    Error Putting or cleaning up file: *.root, err::global name 'glob' is not defined

In the ganga submission script I did define the following:

j.outputfiles=[MassStorageFile(namePattern="*.root", outputfilenameformat=project+'/'+unique_production_name+'/{jid}/{sjid}/{fname}’)]

I think all looks OK and the files are at least stored on the desired eos location.

Can you please advise what to do?
```

The script used for this is:

```
import os

project = 'DiMuon'
configfile = "DiMuon4.py"

unique_production_name = '2011_21r1p1a_EW_up'

# for testing
#datalist = 'test.py'

# 2011
#datalist = 'LHCb_Collision11_90000000_Beam3500GeVVeloClosedMagUp_Real_Data_Reco14_Stripping21r1p1a_EW_DST_26_4_2016.py'
datalist = BKQuery('/LHCb/Collision11/Beam3500GeV-VeloClosed-MagUp/Real Data/Reco14/Stripping21r1p1a/90000000/EW.DST', dqflag=['OK']).getDataset()

projectpath = os.environ['HOME']+'/workspace/LHCb/'+project+'/'

j=Job(application=DaVinci( version = "v39r1p1" ), backend=Dirac() )

j.name = unique_production_name
print "\n["+j.name+"] Working on: " + j.name

print "\n["+j.name+"] Initalizing ganga running of project: " + project + " with unique_production_name version: " + unique_production_name
print "["+j.name+"] Using project path: "+ projectpath +"\n"

print "["+j.name+"] Config file: " + configfile
print "["+j.name+"] Data list in file/from query:\n"
print datalist
print "\n"

j.application.optsfile = [ File ( projectpath+configfile ) ]

j.application.extraopts="""
DaVinci().PrintFreq = 1000
DaVinci().EvtMax = -1
DaVinci().InputType = 'DST'
DaVinci().DataType = '2011'
DaVinci().Simulation = False
"""
print "\n["+j.name+"] Here are the changed job options: "
print j.application.extraopts

#j.inputdata = j.application.readInputData(projectpath+datalist )
j.inputdata = datalist

j.splitter = SplitByFiles( filesPerJob = 10 )
j.parallel_submit = True
j.outputfiles=[MassStorageFile(namePattern="*.root", outputfilenameformat=project+'/'+unique_production_name+'/{jid}/{sjid}/{fname}')]
#j.outputfiles=[DiracFile(DiracFile(namePattern='*.root',locations=["CERN-USER"])]

print "\n["+j.name+"] Writing the following files to EOS:"
print j.outputfiles

print "\n["+j.name+"] Now submitting the job ..."
j.submit()
#queues.add(j.submit)
print "\n["+j.name+"] ... submitting job done.\n"
```

This concerns me slightly as there is an error somewhere around the handling of complex file names which could do with tracking down.
I'm worried that files could be being copied multiple times or not at all or multiple times but once is broken.
Given this effects the integrity of the output data for the user I think we should be sure there are no problems around this in 6.2.0.
(This functionality should also exist across all IGangaFile object types eventually!)

**Comment by jea-umd** [comment]
I played with a couple of different ways of reproducing the error. It does not appear when using a DiracFile, and it does appear when using a MassStorageFile whether a wildcard '*.root' or an explicit file name is used.

**Comment by rob-c** [comment]
@jea-umd I'm in the process of finally writing a `MassStorageFile` test which should make debugging this easier.
Does this appear if there is no `outputfilenameformat` used or if this is used without a subjob at all?

**Comment by mesmith75** [comment]
I think the problem is in the cleaUpClient function. The job gets uploaded fine, but the file is still in the output. It looks as if the function in IGangaFile doesn't work

**Comment by rob-c** [comment]
@mesmith75 I think you've spotted the main cause of the bug but I'm tracking down trying to make a test to pick this up so that it doesn't come back.

**Comment by mesmith75** [comment]
@rob-c Yes the function in IGangaFile needs to look more like:
```python
import glob
import os

    def cleanUpClient(self):
        """
        This method cleans up the client space after performing a put of a file after a job has completed
        """

        # For all other file types (not LocalFile) The file in the outputdir is temporary waiting for Ganga to pass it to the storage solution
        job = self.getJobObject()

        for f in glob.glob(os.path.join(job.outputdir, self.namePattern)):
            try:
                os.remove(f)
            except OSError as err:
                if err.errno != errno.ENOENT:
                    logger.error('failed to remove temporary/intermediary file: %s' % f)
                    logger.debug("Err: %s" % err)
                    raise err
```

The change is the ```import glob``` and  ```import os``` and the change of ```outputfile.namePattern``` to ```self.namePattern```.This works for me.

**Comment by rob-c** [comment]
@mesmith75 This isn't the full fix as I can reproduce this error on other configurations still.

There are a lot of annoying papercuts in the handling of MassStorageFile which could do with smoothing over before 6.2.0 and writing a few basic tests to show what works and what doesn't.

**Comment by mesmith75** [comment]
@rob-c Does this copy files to the ganga repository before uploading them to mass storage? Is it possible to copy them straight there from the WN?

**Comment by rob-c** [comment]
@mesmith75 short answer NO.
Long answer:

We have a configuration system which means that we know from which backend we can access the MassStorage directly. i.e. from a `LSF` or `Local` job on lxplus we can assume we have access to eos and directly put the file there.
From a Dirac WN we can _never_ assume that this is the case due to ports needing to be open in a firewall and such and we don't offer support to work out whether this is the case. A user can edit their config to make sure all DIRAC jobs go to a site with access to EOS and the tools and to upload directly from DIRAC but this is an expert thing to do.

Because of this Ganga will follow 1 of 2 code paths depending on how the file should end up on EOS either using some injected code into the script run on the WN in the case of WN having access or the files are downloaded first and then copied to EOS removed from the output workdir/temp-space (I'm not sure where the cwd is for this operation) during job completion.

I've added a test which tests for a Local job having access to the MassStorage from the WN but I cannot yet add a test which tests for a Local job using the client side code to upload to MassStorage which is where the problems are atm.
This is due to some shortcomings in the design of the file management in Ganga which I'm hoping to address as it keeps getting in the way and is currently holding up stuff I'd like to do for LSST.

**Comment by mesmith75** [comment]
ah ok, that makes sense. Thanks for the explanation.
