### ISSUE TITLE
Implement peek for running jobs on the Condor backend

### ISSUE THREAD

**Issue by will-cern** [ganga-devs/ganga#734]
Hi,

Not sure if this is already a feature of ganga, but it would be great if there was an easy way from to invoke 'condor_tail -f <jid>' from within the ganga prompt for a running condor job. Ideally doing "job.peek('stdout')" for a running condor job would execute this tailing the stdout!

Cheers
Will

**Comment by gurudattapatil** [comment]
Working on this #1899
