### ISSUE TITLE
Add support for running Docker images using the current backends

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#737]
A nice feature would be the possibility of saying you want your job to be run from a docker image that was (possibly) created from during the preparation step. I can see this being independent (to a certain extent) from the backend - you just put in a flag either on the Job object of the application object that says you want to use Docker and the script that's sent will run the appropriate commands on your chosen backend to use the given docker image.

There are probably some issues that could scupper this but I thought it might be worth discussing!

**Comment by rob-c** [comment]
I've been interested in this myself I'll admit (was looking into it a while ago as a private project).

Would it be worth having some backend which ssh-es directly into a machine and runs some commands this backend would have to manage sending files ahead of the application and managing how they're sent back.
This would also deal with credentials an ssh-keypair or username/password.
(Some other authentication mechanism would also be nice but in my mind ssh is everywhere so it would be nice to have that as an option).

I can imagine a docker application would then just run the appropriate commands as the appropriate user on the machine on the cluster.
We could even use Gangas auto-resubmit as some form of poor-mans openstack to keep some images alive over a cluster of machines.

**Comment by drmarkwslater** [comment]
@rob-c I think there are two+ things to talk about here. The one you describe is some sort of combination of the `Remote` backend and the Amazon EC2 backend we had some time ago. This would be either you have several remote machines that Ganga controls jobs on directly AND/OR you talk to an openstack (or whatever) instance to fire up machines for you that have the job run as part of the image. If possible, they would 'phone home' to the parent Ganga process to say they were still alive.

These are good ideas as well and are very much intertwined with usage of Docker but I primarily had in mind just being able to submit to, e.g. a Condor backend but specify a Docker image (or tell Ganga to create one in the Application prepare step) and Ganga would inject the appropriate code to actually run the job within Docker on the worker that Condor dumped the job on. Does that make sense?

**Comment by rob-c** [comment]
@drmarkwslater Is this sounding like the functionality in kubernetes?
http://kubernetes.io/docs/hellonode/

Sounds like a system to send docker containers to/from computing nodes on a cluster. 
Would be nice to have similar functionality in a GangaDocker plugin

**Comment by egede** [comment]
Reopen if you should wish to comment further on this idea.
