### ISSUE TITLE
ganga athena -c option not passing arguments correctly

### ISSUE THREAD

**Issue by will-cern** [ganga-devs/ganga#739]
Hi,

I just tried using the -c option to pass arguments to my joboption in ganga, but I noticed if I did:

ganga athena .... myJobOptions.py -c "test=1"

In the log files for the job, I see that instead of "test=1" being executed, what gets executed is " '''test=1''' " ... i.e. the command has been converted to a string, so the execution isn't the same as a local athena job.

Can this be fixed please!
Sorry for finding all these bugs

Cheers
Will

**Comment by drmarkwslater** [comment]
@will-cern So can I just confirm that the job should be executed as:
```
athena myJobOptions.py -c "test=1"
```
i.e. `"` around the options? I would assume so as otherwise you can't put other commands in there. In which case this should be in ASAP!

**Comment by will-cern** [comment]
That's right, it goes in a double quote. 

Thanks
Will
