### ISSUE TITLE
ganga still gives warning about using 64 bit?

### ISSUE THREAD

**Issue by will-cern** [ganga-devs/ganga#743]
Hi,

This is a super minor issue - I've noticed ganga still gives a warning about CMT being setup with 64 bit when I submit jobs. Is this warning really still necessary? If anything, surely it should be a warning if you setup with 32 bit these days.

Just thought I'd mention this.

Cheers
Will

**Comment by drmarkwslater** [comment]
@will-cern I've also noticed this and thought I should remove it - it will get done soon 😄

**Comment by milliams** [comment]
Should this be marked for 6.1.25 again?
