### ISSUE TITLE
Check stdout/stderr for old LSF jobs that have gone from the batch system

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#747]
If you submit an LSF job and then don't monitor if for a long time, Ganga will think the job has failed because LSF cleans up the job. It should probably just check the the stdout/stderr if LSF reports the job as finished or isn't present any more. This is what Condor does.

**Comment by rob-c** [comment]
This would be nice to see.

**Comment by mesmith75** [comment]
Is this still being worked on?

**Comment by egede** [comment]
Just looking at this one now. @drmarkwslater are you sure this is true. There is a status file written with START and STOP tags that is used by the monitoring. I do not think we use the `bjobs` command at all.
