### ISSUE TITLE
browseBK not working

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#75]
In release 6.1.13 the LHCb function browseBK does not open a GUI dataset browser as expected. It just after a while returns an empty dataset. No error messages. In 6.0.44 it works as expected.

**Comment by rob-c** [comment]
@egede Did you report that this was working in 6.1.14?

**Comment by egede** [comment]
Yes indeed it does. I guess it might have been fixed by an upgrade of the LHCbDirac version.
