### ISSUE TITLE
Move to LHCbDirac 8.3 in Ganga 6.2.1

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#756]
This is just a meta-issue to track the fact we plan to have moved to LHCbDirac 8.3 by  Ganga 6.2.1.

There are some changes to make and as 8.3 is a big change in LHCbDirac I'm opting to avoid changing to this for 6.2.0 for stability reasons but I'm happy to migrate to it asap after 6.2 has been released.

(This will be fixed when the versioning code is handled entirely in the LHCb config and the setupproject code has been written to grep and use the code there rather than hard-code the value elsewhere which can lead to problems.)

**Comment by mesmith75** [comment]
Is there a particular version we want for this? The current release is v8r3p7.

**Comment by egede** [comment]
@mesmith75 I would just take the latest version that is released.

**Comment by mesmith75** [comment]
Closed by #823
