### ISSUE TITLE
Version number in session/job monitoring

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#757]
I should probably open this against the monitoring system as this is the bit most effected but there was a change (at some point in 6.1.x) which caused the version string reported to change dramatically somewhere from `Ganga-x-y-z` to simply `x.y.z`.

I'm leaving an issue open here as it's only prudent to go back and check that nothing else has changed whenever this happened. This took me a few hours to fix the monitoring code to deal with the fact the schema effectively changed in the database at some un-announced interval.
I plan to get a gangamon instance ready to be publicly viewable in the near future so I'm keen that the information be a bit more correct than it was displaying. It looked like 60% of our userbase had shifted to start using `ganga-svn` which thankfully isn't true.

I am seeing a large consistent usergroup using `6.1.2-hotfix1` I'm assuming Atlas (hammercloud?) Does anyone know why they are lagging so far behind since we're now looking at 6.2.0?

**Comment by drmarkwslater** [comment]
@rob-c Hammercloud are technically using 6.1.2 but have patched it numerous times. I've said they should be able to transparently shift to the latest version but I don't think they have the manpower/time to do it yet.

**Comment by rob-c** [comment]
@drmarkwslater I'm assuming this is just a case that the Ganga release is reporting this version despite a lot of private patches to keep things working?
I'd be curious if they have any nonAtlas problems when they come to move (they shouldn't) but this would be telling about if we're missing some coverage in our tests I think

**Comment by drmarkwslater** [comment]
@rob-c Basically yes - If they have any problems (almost always with Atlas specific stuff) I'll put the patch into Ganga and they'll just manually patch the version they're running. as you say, I don't believe there should be any problems when they eventually decide to shift but we'll have to see.
