### ISSUE TITLE
hostname resolution broken

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#758]
nearly all LHCb users  (and probably many more not LHCb) (regardless of site etc) see their hostname stored as `localhost`.

This is due to the following exception being caught in a catch all exception handler:
``` WARNING  NameError: global name 'hostname_tmp' is not defined ```

This is thrown from:
https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/Utility/util.py#L160

I suspect this is because the object simply isn't defined.

Why we're simply not using `socket.getfqdn` I don't know but I'll prepare a PR for this.

This has ruined the monitoring data and messes up the jobs summary such that #383 is an issue.

This should probably have been caught a _long_ time ago.

This isn't serious but I will get this into 6.2.1 as this is slightly bad. If there are any more PR before 6.2.0 I'd like to bump this for a few reasons.

**Comment by drmarkwslater** [comment]
This seems to be my fault - I don't know why I missed this but there we go. I agree that a call to `getfqdn` makes the most sense but I think that having it wrapped is a good idea due to the non-threadsafe-ness of these commands that have already been found. I'll get a PR done ASAP...
