### ISSUE TITLE
Proxy repr issue reported by LHCb user.

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#767]
An LHCb user is reporting the following call from in front of the GPI can potentially timeout.

```
I tried
Ganga In [n]: subjob0.outputfiles
and ganga just stopped, I killed it after a few minutes but it looks like the __repr__ is not a simple text string (probably waiting for the file to be created to evaluate).
```

This may or may not be a ganga issue as if this is doing some form of file I/O I suppose this could just be AFS hanging behind the scenes. Adding this in case it's revealing a problem in our logic.

I'll check what the full job config was soon.

**Comment by mesmith75** [comment]
Can we close this?
