### ISSUE TITLE
Add protection for large amounts of Dirac inputfiles

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#768]
There was an issue in LHCb in the last couple of days that a user had put all their input data into the `inputfiles` field of the job. These jobs failed but caused a few issues while doing so. We've had a request from the computing team to put in a check for very large `inputfile` declarations, including `DiracFiles` to catch this problem. This sounded like a good idea to me, hence this issue 😄

**Comment by rob-c** [comment]
What is the limit being asked for?
The `DiracFile` atm more or less maps 1 to 1 when it comes to objects per LFN, wildcards aren't supported.

Should we stop submission of jobs which have 20+ (or some other number) LFN in the inputfiles?
It would be nice to have the ability to turn this off incase anyone needs to run a custom complex job in the future although I imagine this would be a highly specialized use case.

**Comment by egede** [comment]
This is far too difficult to define in a sensible manner just based on counting. There could be 600 small files and it would be fine.
