### ISSUE TITLE
Exported Job which has a prepared App is not loadable

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#77]
If you do the following, it will fail with the given error:

```
j = Job()
j.prepare()
export(j, 'my_job.txt')
load('my_job.txt')

Ganga.Runtime.bootstrap            : ERROR    TypeMismatchError:  ('Attribute "is_prepared" expects a value of the following types: [\'type(None)\', \'bool\']',)
```

I'm not sure what the solution is but I guess it should probably create a job in a `new` state and an unprepared app? Though maybe it would be good to load a `completed` job including the shared dir ref. But then I don't know how that's going to work.

Any suggestions welcome!

**Comment by rob-c** [comment]
This has been highlighted in #29

**Comment by drmarkwslater** [comment]
Apologies - forgot about that one!
