### ISSUE TITLE
Problems with DIRAC nightly

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#774]
The DIRAC job object seems to be struggling in the latest nightlies:

```
    @pytest.yield_fixture(scope='class')
    def dirac_job(load_config):
```
... Leads to:
```
>       get_file_lfn = output_data_info['getFile.dst']['LFN']
E       KeyError: 'getFile.dst'
```

As a result a lot of the tests fall over. I'll have a look at how we've arrived here and see if it's obvious.

**Comment by milliams** [comment]
This is being caused by ` execute('getOutputDataInfo("%s")' % job_id)` returning `{}` where it should be returning something like:
```python
{
  'getFile.dst': {
    'LFN': '/gridpp/user/r/robot.general.gangaproject/1312/1312284/getFile.dst',
    'GUID': '607324E0-6DA2-C863-DA00-2B1772397B34',
    'LOCATIONS': ['UKI-LT2-Brunel-disk']
  },
  'removeFile.dst': {
    'LFN': '/gridpp/user/r/robot.general.gangaproject/1312/1312284/removeFile.dst',
    'GUID': '0F5B7D39-6A1F-81D1-5FEB-C007685A7A65',
    'LOCATIONS': ['UKI-LT2-Brunel-disk']
  }
}
```

This is possibly due to the line:
```python
while not output_data_info.get('OK', True):
```
which perhaps should be:
```python
while not output_data_info.get('OK', False):
```

**Comment by rob-c** [comment]
OK, sound like you've managed to get further than I have I'm having to start again with a fresh config env with DIRAC available. Would you know what is required to fix this in a short PR?

**Comment by milliams** [comment]
Well I think this is only an ephemeral problem (which is why we haven't seen it before) and only crops up when the SE is being a little slow to respond. The loop I mentioned above is there to keep trying until it gets the right result but the way it's coded, if it gets a null result then it assumes that it succeeded:
```python
assert {}.get('OK', True) == True
```

Most likely, rerunning the nightly will pass but I'll put together a PR to avoid it happening again.

**Comment by milliams** [comment]
It looks like the nightly test is progressing past the stuck point before but I'll put in a tiny PR to fix the issue you noticed.
