### ISSUE TITLE
Problems with config in unittests

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#776]
I've introduced the following:

```
import pytest
from Ganga.Utility.Config import getConfig

glite_status = getConfig('LCG')['GLITE_ENABLE']

@pytest.mark.skipif(glite_status == False, reason="Cannot run test GLITE not enabled")
```

into a short unittest the intention is to never run the test when I know it will fail. Standard stuff when supporting multiple platforms and multiple configs.

However. I find that the glite_status is being set to the coded default value regardless of what is in my `.gangarc`, `LHCB.ini` or other configuration sources.

If there some special treatment of the LCG config within the unittests I'm not aware of?

**Comment by milliams** [comment]
This is because at module-level the config files have not been read yet and so `getConfig` is just getting the default value.

**Comment by rob-c** [comment]
I'm quickly realising this.
The following works:
```
from Ganga.testlib.GangaUnitTest import start_ganga, stop_ganga
start_ganga('/tmp/')
glite_status = getConfig('LCG')['GLITE_ENABLE']
stop_ganga()
```
What would be involved in factoring out the configuration system so that we can start this up in a minimal way to correctly parse the environment?

**Comment by milliams** [comment]
Firstly, that's a bad idea because it's not going to scale to it being done lots of times. From what I can tell, the best solution is to do something like:
```python
@external
def test_job_submit_and_monitor(gpi):
    if not getConfig('LCG')['GLITE_ENABLE']:
        pytest.skip('No LCG')

    from Ganga.GPI import Job, LCG
    ...
```

Secondly, we already have that factored out in `Ganga.testlib.GangaUnitTest.load_config_files` and `Ganga.testlib.GangaUnitTest.clear_config`.

**Comment by rob-c** [comment]
@milliams If you're referring to the working example, that is not a solution it's a workaround to what I would regard as a bug. I'll try `load_config_files` and see if this works correctly and then change the decorator accordingly.
This is one of the few times I would prefer the decorator as it does in 1 line what you can do in 3 or 4.

**Comment by milliams** [comment]
I really don't want to be doing config file reads etc. at test module import-time. We want test discovery to be fast.

**Comment by rob-c** [comment]
It doesn't matter if it's running on a dedicated test machine I would argue. We can easily wrap this behind something external that doesn't effect the rest of the tests when running quickly

**Comment by milliams** [comment]
Tests don't only run on dedicated machines. For example they constantly run on my local machine as I'm doing development.

**Comment by rob-c** [comment]
This adds <0.3sec to test discovery on an AFS system from testing. On my SSD I don't notice accessing the 1 file during test discovery, is there anything else contributing to this being slow?
