### ISSUE TITLE
Changing default of GenericSplitter

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#778]
Should the GenericSplitter throw an exception if it fails to split?

And LHCb user posted that:

```
   splitter =    GenericSplitter (
     attribute = ,
     values = [49 Entries of type 'list'] ,
     multi_attrs = []
   ) ,

and submitting it gets

jj.submit()
INFO     submitting job 1353
INFO     job 1353 status changed to "submitting"
INFO     Job 1353's application has already been prepared.
INFO     Splitting Job: 1353
INFO     Preparing subjobs
INFO     submitting job 1353 to Dirac backend
INFO     job 1353 status changed to "submitted"
```

I'm thinking that maybe we should throw an exception if no subjobs were created by the splitter rather than submitting the (probably incorrect) single master job.

What are people's thoughts about this?

**Comment by milliams** [comment]
I agree that a splitter should always create subjobs. Even the proposed `NullSplitter` (or `EmptySplitter` or whatever it was going to be called) would create a single subjob.

**Comment by egede** [comment]
Not just for this splitter, but for all splitters, I believe that an exception should be thrown if no subjobs are created. Creation of a single subjob is allowed though.

**Comment by rob-c** [comment]
OK, I'll look to adding something a little more generic in Job or elsewhere that if the splitting failed to return any subjobs we regard this as an error and will throw an exception.

**Comment by drmarkwslater** [comment]
I had thought this was already in but it seems it was just present for Atlas splitters. I agree, if the splitter returns no jobs, that should be an exception.

**Comment by mesmith75** [comment]
This appears to be sorted.
