### ISSUE TITLE
Problems loading configuration file 'ipythonrc'

### ISSUE THREAD

**Issue by alexpearce** [ganga-devs/ganga#78]
When I try to start Ganga v601r13 with `lb-run Ganga ganga`, I see the following error:

```
Traceback (most recent call last):
  File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r13/external/ipython/0.6.13_ganga_patch1/noarch/lib/python/IPython/ConfigLoader.py", line 71, in load
    fname = filefind(fname,incpath)
  File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r13/external/ipython/0.6.13_ganga_patch1/noarch/lib/python/IPython/genutils.py", line 439, in filefind
    ' not found in current or supplied directories:' + `alt_dirs`
<type 'exceptions.IOError'>: File'ipythonrc' not found in current or supplied directories:'/afs/cern.ch/user/a/apearce/.ipython-ganga'

WARNING: Problems loading configuration file 'ipythonrc'
Starting with default -bare bones- configuration.
```

This is annoying because none of the cool IPython stuff works now, like tab completion and history searching (where you can type the beginning of a previous command and go through matching history with the up key). How can I get the IPython session set up correctly?

---

To try to fix the problem, I deleted everything I know of connected to Ganga and IPython, namely:

* The `.ipython-ganga` and `.ipython` folders
* The `gangadir` folder
* The `.gangarc` file and any archived `.gangarc.XX` files
* The `.ganga.log` and `.ganga.py` files

When I started a new Ganga session, with `lb-run Ganga ganga`, I see:

```
WARNING:root:trying old SetupProject (cannot find project Ganga prod for x86_64-slc6-gcc48-opt in /afs/cern.ch/user/a/apearce/cmtuser:/afs/cern.ch/user/a/apearce/cmtuser:/afs/cern.ch/lhcb/software/releases:/afs/cern.ch/sw/Gaudi/releases:/afs/cern.ch/sw/lcg/releases:/afs/cern.ch/sw/lcg/app/releases:/afs/cern.ch/lhcb/software/releases:/afs/cern.ch/sw/Gaudi/releases:/afs/cern.ch/sw/lcg/releases:/afs/cern.ch/sw/lcg/app/releases:/afs/cern.ch/lhcb/software/releases/LBSCRIPTS/LBSCRIPTS_v8r4p2/LbRelease/data/DataPkgEnvs:/afs/cern.ch/lhcb/software/releases/LBSCRIPTS/LBSCRIPTS_v8r4p2/LbUtils/cmake)
ALWAYS:SetupProject:Configuring Ganga v601r13 from /afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r13
Configuring Ganga v601r13 from /afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r13

*** Welcome to Ganga ***
Version: 6.1.13
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


Ganga.Utility.Config               : INFO     reading config file /afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r13/install/ganga/python/GangaLHCb/LHCb.ini
Ganga.Utility.Config               : INFO     reading config file /afs/cern.ch/sw/ganga/install/config/LHCb/6-1-11/CERN.ini
Would you like to create default config file ~/.gangarc with standard settings ([y]/n) ?
```

I respond with `y` and get:

```
Ganga.Runtime.bootstrap            : INFO     Creating ganga config file /afs/cern.ch/user/a/apearce/.gangarc
Press <Enter> to continue.

WARNING: Configuration file ipythonrc not found. Ignoring request.
------------------------------------------------------------
Traceback (most recent call last):
  File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r13/external/ipython/0.6.13_ganga_patch1/noarch/lib/python/IPython/ConfigLoader.py", line 71, in load
    fname = filefind(fname,incpath)
  File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r13/external/ipython/0.6.13_ganga_patch1/noarch/lib/python/IPython/genutils.py", line 439, in filefind
    ' not found in current or supplied directories:' + `alt_dirs`
<type 'exceptions.IOError'>: File'ipythonrc' not found in current or supplied directories:'/afs/cern.ch/user/a/apearce/.ipython-ganga'

WARNING: Problems loading configuration file 'ipythonrc'
Starting with default -bare bones- configuration.
```

I'm then dropped in to a (dumb) IPython shell.

**Comment by alexpearce** [comment]
I should also say: this is on an lxplus node, and `which -a ipython` just gives me `/usr/bin/ipython`.

**Comment by egede** [comment]
@alexpearce If I remove both the .ipython and .ipython-ganga directories before starting I can reproduce the problem.

A short-term solution is to do

    mkdir .ipython-ganga
    touch ipythonrc

Nevertheless there is a bug that should be fixed.

**Comment by alexpearce** [comment]
My Ganga is submitting jobs at the moment, so I can't exit to test, but I think I tried this a while ago. 

It did stop the error message appearing, but I _think_ you still end up with a bare-bones IPython shell, without a lot of the goodies.

**Comment by rob-c** [comment]
Just a few comments,

If you're referring to the magic tab-complete for functions etc. This was broken at some point in the move to Ganga 6.1.
It's not fully understood when this stopped working, but due to this being a 'goodie' style feature we've not had the manpower to get around to using this yet.

As it stands 6.1.14 has moved to ipython 2.x by default (I think) and we don't make use of the system default ipython rather the version that we ship with ganga as an external package.

Rob

**Comment by rob-c** [comment]
@alexpearce Ganga 6.1.14 is upgrading to IPython 1.2, once it's been released I would like to invite you to try and check if this is still a problem as some of the code handling this has changed a lot since 6.1.13.
Thanks,
Rob

**Comment by alexpearce** [comment]
I'll make sure to have a look. Thanks for the update!

**Comment by alexpearce** [comment]
This error has indeed gone away with 6.1.14, and I've got my beloved history completion back.

Thanks for the fix!
