### ISSUE TITLE
More checks needed in DIRACBase

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#786]
Looking through the DIRAC Base I think we should look into checking the output from DIRAC a lot more. The monitoring code in particular still falls over in bad ways when DIRAC returns something unexpected due to various reasons. This would help for people with potentially flaky connections or when DIRAC is under heavy load for instance.

**Comment by milliams** [comment]
Traditionally in Python the way to enforce checking of error conditions is to raise exceptions. It makes sure you can't accidentally ignore an error. I think this is the better approach for us too but it does require a decent test suite.

**Comment by rob-c** [comment]
At this point we try to do crazy things like expand a tuple out of a `None` object at times still so we need some basic assertion checks when dealing with DIRAC output. Throwing and catching sane exceptions is obviously the best way to write the monitoring loop.

**Comment by egede** [comment]
@rob-c Can we create a new exception `GangaDiracInvalid` and then throw this one from some low level in out interaction with Dirac if the result from a call does not satisfy the expected structure.

**Comment by rob-c** [comment]
@egede Possibly, this would be nice but I think adds more confusion about what may be going wrong.

I think though that this can be handled by some simple assert checks on the output from the DIRAC API calls. We still have no way of getting a Boolean response from DIRAC to determine if a command succeeded in a nice way.
I know DIRAC returns a dict which has this information but atm we ignore this in almost all cases which is far from ideal. Whether we want to add a global check for DIRAC returns from within the DiracUtils or whether we want to add a unique test for each object in the GangaDirac codebase I don't know but we can win a lot of stability here if we look into this as mostly everything else seems to be quite responsive atm.

**Comment by milliams** [comment]
All DIRAC API calls should return a dictionary created by either [S_OK](http://diracgrid.org/files/docs/CodeDocumentation/Core/Utilities/ReturnValues.html#DIRAC.Core.Utilities.ReturnValues.S_OK) or [S_ERROR](http://diracgrid.org/files/docs/CodeDocumentation/Core/Utilities/ReturnValues.html#DIRAC.Core.Utilities.ReturnValues.S_ERROR). These will all have the key `'OK'` which maps to a bool. We should make sure that we are always checking this in `DiracCommands.py` with something like:
```python
result = deleteJob(257324)
if not result['OK']:
    raise GangaDiracError(result['Message'], result['Errno'])
...
carry on as usual
```
We then have to make sure that `execute()` propagates these exceptions correctly and then make sure that any call to execute is wrapped in a `try`/`except` at some level to make sure that these errors never make it to the user.
