### ISSUE TITLE
Organisation of tests

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#787]
I have come across a potential bug in the sorting of the tests and I'd like some clarification.

I think we had decided that all unit and integration tests requiring an external resource such as DIRAC or LCG should be marked as external and _not_ run as part of the continual testing but only run nightly.

If we're sticking to this I'm going to tag some tests as external which haven't been marked as such but if we've changed our minds on this what is the policy with regard to tests requiring access to external resources?

**Comment by milliams** [comment]
Indeed, any test that is contacting an external server which might fail should be marked as `@external`. In *most* unit tests we should aim to mock-away any external communication so it *shouldn't* be necessary.

**Comment by rob-c** [comment]
OK, I'll add some missing external tests into another PR where I'm doing some DIRAC work/testing then.

**Comment by rob-c** [comment]
Closing this but there are clearly issues that any test requiring objects or strings being returned to Ganga through the stdout will _never_ work without a DIRAC proxy. We don't allow the users access to this without a proxy so this is not a problem. These tests explicitly require some fixing and this is coming in another PR.
