### ISSUE TITLE
It is still possible to subvert __setattr__ with some GangaObject inherited classes

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#79]
This has been a problem which appears to come and go and I've plugged a few areas in the GangaObject and Proxy code where the situation arises.

The problem is basically that a member attribute of a class (which happens to be in the Schema but strictly this shouldn't matter!) fails to have it's _parent attribute assigned upon the attribute being assigned.

I've added some _setParent and #FIXME statements into the Job class (https://github.com/ganga-devs/ganga/commit/9be4d2b58e5a6b0a616e166fd720c29e13084b64) which should be removed and un-needed by the next release.

This 'fix', whilst works, concerns me that this may be broken in more places in the testing or in some usage I'm not currently testing (i.e. maybe the atlas env or similar).

I've debugged this particular problem multiple times before and it often turns out to be some init/construct/(some-other) method which oversteps itself and assigns an item directly subverting the setter methods in the GangaObject.

My plan is to try and trace the setter/getter methods to check for either an assignment which fails to correctly assign a parent to an attribute of GangaObject type and/or to make sure that without a proxy that the bare class always calls the getter/setter methods as intended without the possibility of these methods being ignored for the standard python methods.

**Comment by rob-c** [comment]
This could also be caused by objects trying to assign values to a classes ```__dict__``` or ```_data``` (depending on if the value is in the schema from other discussions).

I want to therefore cut down on any use of get/setNodeData and get/setNodeAttribute calls outside of either ```Ganga.Core.GangaRepository``` and ```Ganga.GPIDev.Base``` (and maybe ```Ganga.GPIDev.Lib.Repository```).
These namespaces are designed to deal with the structure of GangaObject classes and this should be effectively hidden from elsewhere without a very good reason.
If an external class makes use of these then they should be expected to 'pick up after themselves' and check that they are doing things like getting/setting parents/repositories as appropriate.

**Comment by milliams** [comment]
I'm not sure about the overall bug yet but indeed we should not have any use of `get/setNodeAttribute` outside of Obejcts.py. All editing of the information in `_data` should be done via the descriptor protocol and setting things like `_dirty`, `_parent`, `_registry` etc should be done with care. The only exception to this might be the serialisation but even then providing a serialisation interface in `GangaObject` would perhaps be better.

**Comment by rob-c** [comment]
@milliams Either we allow it in object construction within the repository or we make some interface to pass the contents of what we want the object to contain into Objects.py (as you say for serialisation).
I'm for allowing the use of these 'internal' functions within the GangaRepository as this is very low level and relies on the structure of the GangaObject in order to do what it's doing anyway. It has to use a lot of low-level knowledge of the Node attributes in order to parse/construct the XML for instance.
I'm happy to add an interface for this functionality but I think it's somehow 2nd order to the particular problem I'm experiencing and want to fix for the moment.

On a related note (but as an aside for now I don't propose doing this for 6.1.15):
I strongly prefer moving _dirty out of the Object and into the repository myself. If the Object calls for a flush then it shouldn't care if it happens right now or in 10 minutes as long as it's done.
We unfortunately have to keep or change ```_setDirty``` if we move ```_dirty``` out of the Objects.py scope but I feel that this is really something that the Repsitory should be dealing with entirely imo.

**Comment by milliams** [comment]
@rob-c I think I agree with all of that.

Back to the main issue, currently in *release/6.1.14* `_setParent` is called inside `Descriptor.__set__` so I guess what you're seeing is that for some reason the descriptor protocol is not kicking in? Do you have any small test cases which show this behaviour?

**Comment by rob-c** [comment]
Not a 'correct' unittest in the conventional sense.
If you remove the _setParent methods from the fixme statements in the method above, submit an LHCb job which runs over 'data' and comes back then I get objects which have a _parent of ```None```.
First step is to understand this well enough to construct a unittest :)

**Comment by rob-c** [comment]
Think I may have fixed this in the above commit. I was seeing jobs failing when they should have been succeeding for LHCb and this led me to the fix above.
I suspect the construction of the object was triggering a flush to disk which was inadvertently not assigning the correct parent to many of the attributed when they were loaded in from disk again.
This fix expressly sets the parent within the setNodeAttribute function which means that a lot of additional calls to setParent in the Objects.py are probably now defunct. However, better to be safe than sorry so I'll try and cleanup excess calls to _setParent in 6.1.15
I'm not going to take out the fixes I've already put in as I'm keen to get 6.1.14 out, however without https://github.com/ganga-devs/ganga/commit/08f476b9221a1254542d4299dff631162d74a234 At the very least a lot of LHCb jobs would have been failing due to outputfiles errors which weren't quite as simple as the other problems to fix.

**Comment by rob-c** [comment]
I'm going to close this as I don't seem to be seeing this bug anymore after adding a setParent in the setNodeAttribute method (arguably where it should have been all along).
