### ISSUE TITLE
Should tests respect the .gangarc?

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#799]
Hi all,

Just a quick question, should we let the test configuration as used by py.test make use of the `.gangarc` configuration file?

I only ask this as I am surprised to see settings in my .gangarc file _not_ overloaded by the test configuration.
(In particular because I've been experimenting with my gangadir in different locations I ended up with multiple tests running on the same repo which is less than ideal).

Should we bump the setting of options within the tests to be the same as a a user-set option rather than what it is now so that the test configuration always takes priority?
If the test knows it needs a certain configuration parameter having a different one from .gangarc would just lead to false errors I think an could lead to confusion.

I'm keen to hear people's thoughts on this,

Rob

**Comment by milliams** [comment]
I'm of the opinion that the test system should not real the .gangarc at all. Those settings are for the end-user, not for the tests. I've been running the tests using `GANGA_SITE_CONFIG_AREA` to provide config (and this is also how Jenkins is set up to work).

**Comment by rob-c** [comment]
then I would argue it makes sense to add this to the test startup somehow to save having to go to some effort to isolate a test run on a dev machine.
I'll investigate adding a check that if this value is the same as the default value then it points elsewhere to avoid picking up the configuration of a machine the test is being run on.

**Comment by rob-c** [comment]
Hmm, the unittests are specifically asking for the `.gangarc` btw. I'll add something which makes use of the `--config` option
