### ISSUE TITLE
Need to stop monitoring threads from within a thread

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#805]
I spend some time yesterday evening playing with getting the disk checking working again in the monitoring system in Ganga.
This took only 2-3min of work to have it checking my AFS space so that it doen't try to download a file when I've `<2%` storage left on my account.

The problem I have spotted here is that from within this thread there is no nice way of communicating back up to the monitoring loop that I want to stop the monitoring entirely.
Trying to call something like `disableMonitoring` fails due to the thread-lock caused by the worker thread waiting for itself to finish.

Does anyone have a good idea of the best way of communicating back up to the monitoring system that it needs to stop running because of an event such as the disk is now _dangerously_ full?

I'm tempted to add a class level boolean to the main monitoring loop and to flip it within a thread that is calling for the monitoring loop to stop and the queues to be emptied. Does anyone have a better suggestion for how to go about this?

**Comment by egede** [comment]
We have a way that we notify threads that we want to quit Ganga. Can we use the same type of mechanism?

**Comment by rob-c** [comment]
@egede There's not a fully unified way of doing this that I know of. (I'll have a look I could be wrong)
It may be a good idea to have some `stopAllThreads` type function which can stop all background threads which would allow the threads to proceed until their next safe point and stop running.
I suppose the advantage to this is it catches _everything_ not just the monitoring threads.

I would wonder though what is the best approach:
 1. Stop all functions in ganga and wait for user input to start again.
 2. Exit ganga in a clean(as much as possible) manner and tell users what they have to do before starting up ganga again?

The advantage of 1. is that we could write some equivalent method to start things running safely again.
I'm wondering though if something is serious enough to cause us to pause ganga should we just exit and tell the user why?

**Comment by egede** [comment]
@rob-c The loss of the ability to write to the local disk can cause problems all over the place so simply quitting Ganga is actually a quite good idea. How do we deal with the loss of the grid proxy when monitoring jobs? There to kill the Ganga sessions seems like an overkill.

**Comment by rob-c** [comment]
At the moment we don't as far as I know. Of we have sure mechanism for communicating a stop or exit from worker threads then we could do something sensible. The only thing we can't do is ever exit from a non master thread so we need to the master to exit and try to shutdown cleanly. I think the system is robust enough that I could write something to give us this behavior atm so I'll give it some spare time next week to see if I can formalise something.
