### ISSUE TITLE
Funny behaviour of unittests in 'clean' environment

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#81]
Both the atlas and lhcb unittests (and I presume core as well but I've not cleaned and tested) stall before running if the .gangarc file isn't there.

It would be nice to have ganga startup and auto-create files like .ganagrc and such by default without waiting for user input.

This should be a trivial fix of just checking the config system before requesting keyboard input from the interfaces.

I don't want to waste time fixing this for 6.1.14 but this should be addressed soon imo.

**Comment by rob-c** [comment]
I'm assuming this has gone away by now? @milliams Do you see this in the release process at all when running the tests by hand for Core/LHCb/Atlas?

**Comment by milliams** [comment]
I've never seen this in the release scripts so I will close it for now. It I see it again I will reopen.
