### ISSUE TITLE
Failure to upload GaudiExec sandbox to Dirac

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#813]
This is a reminder to myself to try and look into this problem. This probably isn't a Ganga issue but it seems to have cropped up a few times.

When uploading the tarball for the GaudiExec application some users are reporting:

``` python
ERROR    Error in uploading file __conf-c8456350-f597-45f6-b581-33674656ab1e.tgz : {'RAL-USER': {'Message': 'Write access not permitted for this credential.', 'OK': False}}
```

which suggests a problem with their grid proxy. It is independent of target SE.

The problems are coming from those not using lxplus to submit jobs (i.e. using lx at Imperial) and only affects GaudiExec.

**Comment by rob-c** [comment]
@mesmith75 there was a DIRAC update last week, could this be to blame? does it still fail now?

**Comment by mesmith75** [comment]
I don't think that was to blame. I have reproduced it myself on the Imperial machines so I'll look into it.

**Comment by mesmith75** [comment]
I think I have found the issue. When it is constructing the LFN base it takes the local user name, not the CERN username so it is trying to put the file to an LFN that doesn't/cannot exist.

**Comment by rob-c** [comment]
How is the username being extracted again from the system, python or the Ganga config?

**Comment by rob-c** [comment]
OK, I think I spotted it. It appears to be from the ganga config as expected. I'll do a quick grep of the core to check there are no gotchas with the core getting inconsistent usernames.

**Comment by mesmith75** [comment]
There perhaps might be. It might be generally neater to have a separate config for the grid LFN base and if it is not specified to take the current method.

**Comment by rob-c** [comment]
There already is.

**Comment by egede** [comment]
@mesmith75 solved this - well spotted. It is caused by the assumption that the local username is the same as the username on the Grid.

Mark, the user name on the Grid is reported by the proxy (it is listed as part of the lhcb-proxy-info command), so I guess we can extract this rather than relying on the configuration. Relying on the configuration is also will not work with the 6.3 ability of Ganga in terms of working with new multiple proxies at the same time.

**Comment by rob-c** [comment]
@egede For the moment we only really support moving between roles (groups) easily I think (I could be wrong). I'll see if there is a way of getting this from the current proxy in 6.3 but I don't think this has been built in yet.

**Comment by egede** [comment]
@mesmith75 Could we catch the exception that is thrown when the upload fails and rethrow a new one that explains what the problem might be?

**Comment by mesmith75** [comment]
@egede Yes although I am hesitant as that could catch any proxy problem beyond this issue. I guess if it is clear it *might* the issue it shouldn't be too bad

**Comment by rob-c** [comment]
@mesmith75 I think just adding an extra error line before/after the existing error should suffice no?

**Comment by egede** [comment]
@mesmith75 Yes, that is fine.

**Comment by mesmith75** [comment]
Sorted by #852
