### ISSUE TITLE
Auto-retry for failing DIRAC requests in 6.3.0

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#817]
Hi all,

I've committed large changes to catch DIRAC exceptions at the lowest level in Ganga and raise an appropriate error.

My question is should we attempt to retry all/most requests which fail automatically now?
I don't see much harm in retrying each command say 5 times and have some function option to request this be deactivated for some certain calls.
(Obviously we can avoid this for failures due to invalid proxies etc).

What are people's opinions on this?

Rob

**Comment by egede** [comment]
@rob-c My only problem with this is for timeout errors. If we already have a long timeout, then repeating it 5 times over could be very painful.

**Comment by rob-c** [comment]
@egede In this case I'm tempted to look into functions which are expected to run for <60sec and have these calls able to repeat in case of error.
I would say book-keeping and other long calls should maybe not be best to repeatedly call, however the latest problems with the book-keeping are (I believe) mitigated by waiting and calling the method again as it's a database access issue behind the scenes.

I will give some thought as to default timeouts and possibly auto-retrying fast calls only and see if I can some up with something.
