### ISSUE TITLE
Ganga documentation in readthedocs

### ISSUE THREAD

**Issue by twhyntie** [ganga-devs/ganga#818]
Hello,

I'm just starting to use Ganga for getting [MoEDAL](http://moedal.web.cern.ch) on the grid (as mentioned a few Ops meetings back). Thanks again to @drmarkwslater who helped me out last week with some non-interactive scripting issues 😄 - it's going pretty well so far, particularly using Ganga over CVMFS.

I'm going through the [docs](http://ganga.readthedocs.io) and was wondering - what's the best/preferred way to make/implement suggestions for these? There are a few gotchas I'm coming across as I work through them, and a few more worked examples would be useful - I'd be happy to fork/branch/PR doc changes if needed - what do you think?

Cheers, @twhyntie

PS: I've caught up with @rob-c's [GridPP37 talk](https://indico.cern.ch/event/556609/contributions/2256974/attachments/1330559/1999383/GangaTalk.pdf) too - great stuff!

**Comment by milliams** [comment]
Hi Tom,

The best way to provide changes to the docs is via a pull request. We'd welcome any additions or changes you can provide. If you need help with building the docs while writing them (we use [Sphinx](http://sphinx-doc.org)) let us know.

**Comment by twhyntie** [comment]
Great, thanks - will do 😄
