### ISSUE TITLE
Make 6.3 play nice with LHCb

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#819]
I'm leaving this here to remind me to look into some _fix_ to make Ganga 6.3 pick up LHCb proxies generated externally and make them available in Ganga.
This will probably require some parsing of the voms tools output and making a symlink or modifying the credentials code to allow for a LHCbDiracProxy object to be derived which differs with the naming scheme.

This should ideally go into 6.3 before LHCb start using this but I think we can settle for 6.4...

**Comment by milliams** [comment]
An externally created proxy should be picked up by the credential system.

**Comment by rob-c** [comment]
well at least for LHCb this isn't happening. I see an AFS proxy in my credential store but nothing else

**Comment by milliams** [comment]
But if you do:
```python
credential_store[DiracProxy()].info()
```
what happens?

**Comment by rob-c** [comment]
a stacktrace and ```"Matching credential [DiracProxy(group='lhcb_user')] not found in store."``` I think we need to improve the handling of the exceptions within ```proxy_wrapped``` as it shouldn't throw a stacktrace from situations like this...

**Comment by milliams** [comment]
And is `X509_USER_PROXY` set correctly?

**Comment by rob-c** [comment]
regardless I can submit and work with LHCbDirac externally to Ganga with the proxy after running `lhcb-proxy-init` (or the cmake compatible function if LHCbDirac 8.3+) failing to pick up a proxy produced from this method is going to at least cause confusion as users will have to enter their password twice and any proxy created in Ganga is unusable after they exit Ganga. (Yes some users use Ganga to setup a proxy)

**Comment by rob-c** [comment]
Why is the credential store not throwing a better exception at the users? KeyError is not what we should be throwing up to the user level.

**Comment by rob-c** [comment]
Why is the credential_store a `GangaObject`? It's hidden and has no schema and I'm unsure if it uses any of the logic from the GangaObject base or have I missed something? I don't think we ever plan to store/resurrect this from a given state.

**Comment by milliams** [comment]
Indeed the credential store is never persisted. I chose to make it a `GangaObject` to make use of the exported function ability with automated proxy stripping.

**Comment by rob-c** [comment]
I've tried with monitoring on/off and Ganga via the `DiracProxy` is refusing to find a proxy which is at the default location.
Ganga __should__ find my external proxy at `/tmp/x509up_u54830` which is constructed _itself_ by the `default_location` as LHCb doesn't define the `X509_USER_PROXY` env var.
Ganga doesn't find this and will insist on making `/tmp/x509up_u54830:lhcb_user` which is just wrong.
I'm not seeing any logic to parse the 2 different filenames so I'm going to investigate adding some better logic around the external detection and use of proxies.

**Comment by rob-c** [comment]
We don't do this for _any_ of the other singletons which have hidden/exposed methods. I think having to construct the whole GangaObject chain for this seems overkill imo.

**Comment by rob-c** [comment]
OK with monitoring off I created a new job submitted it to DIRAC and I ended up with 2 credentials in my system AFS+DIRAC. I then restarted ganga (again with monitoring off) and I then used `runMonitoring` on a chosen job and I'm now left with a credential store with only my DIRAC proxy in it. Is it expected that my AFS token now be unknown to Ganga in this situation?
(Full disclosure I'd moved the remaining interface classes to Ganga.GPIDev.Adapters but this should not have broken things in the way I describe).

**Comment by rob-c** [comment]
The credential store also returns un-proxied objects which seems incorrect. I'll check this isn't something I've done to this section of code inadvertently.

**Comment by rob-c** [comment]
What is the best way of creating a DiracProxy by hand from the interactive prompt? I can't find an easy way to manually generate one using the new mechanism I just get an error trying to do the same as the voms tests. (And there is no DiracProxy test.)
I may just end up writing a helper function to do so for testing.

**Comment by mesmith75** [comment]
I think this has been sorted by #825. Can we close this?
