### ISSUE TITLE
Add a check for available SEs

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#828]
We need to add a check for which SEs are available for uploads in case one goes into downtime. This might be best done at startup.

**Comment by egede** [comment]
@mesmith75 We should try to minimise checks at startup as they delay everything else in Ganga and might in reality never be needed. In this example it would most likely require a GridProxy at startup which might otherwise not be required. Can we delay it until the first time that it is needed?

**Comment by rob-c** [comment]
@mesmith there is simply no api I'm aware of in DIRAC which will return on request a some lost which we would need. Adding this is complex and the complexity is the reason I've held off going near it. We could add redundancy checks to attempt to upload to sites of an upload fails in Ganga but there is little we can do to find which sites are currently in a writable state for a given credential unfortunately.

**Comment by egede** [comment]
So should we rather just have a mechanism where it picks one and if it fails, it goes onto try the next. If 1 of the 6 are out, it means that on average one in every six uploads will get to see this delay.

**Comment by mesmith75** [comment]
There are functions in Dirac to do it, so it can be done, but maybe it is simpler just to cycle through the list in case of a failure.

**Comment by mesmith75** [comment]
Looking again, the function in the Dirac DataManager I wanted to use is not accessible outside. Its a bit annoying as it would be really useful to have. In which case I'll change it to try and cycle through the SEs.

**Comment by rob-c** [comment]
@mesmith75 It's worth noting that there have been problems with site configurations not being 100% reliable when automatically generated as per the GridPP Dirac. We can roughly trust the SE in LHCbDirac but I'm weary to add any checks for vanilla Dirac based on some previous conversations with the Imperial experts.
At what stage are you planning on introducing these checks?

**Comment by rob-c** [comment]
This is looking like a duplicate of #416 which one should I close?

**Comment by egede** [comment]
@egede. I suggest to close #416

**Comment by mesmith75** [comment]
They are slightly different things. I think this is the more pressing issue. I'll try and get it done for tomorrow.

**Comment by mesmith75** [comment]
Closed by #852 for the GaudiExec upload. The function is now in the DiracAPI if we decide we want to check SEs elsewhere as well.
