### ISSUE TITLE
LHCb plugin overrides some configs

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#829]
When the LHCb plugin loads it overrides some configurations that the user may have set (such as the list of SEs to use). Do we want to take the user configuration over that?

**Comment by drmarkwslater** [comment]
@mesmith75 How are the user configs getting overwritten? I don't know of a reason that, e.g. the user's `.gangarc` should be ignored for certain settings though maybe there's a specific LHCb reason...

**Comment by mesmith75** [comment]
I think it is because the LHCb plugin loads last and sets the configs when it does.

**Comment by egede** [comment]
@drmarkwslater I had a discussion with @mesmith75 about this. We have changed the way that plugins are loaded in Ganga and I wonder if we in that process have broken the rules for the precedence chain, that is

- Default value in code
- Anything defined via files in `GANGA_CONFIG_PATH`
- The users `.gangarc` file
- The command line via `ganga -o ...`
- Interactive at he prompt.

**Comment by rob-c** [comment]
So originally this code over-wrote the default value in the code in the config system.
It was decided this was bad I forget why but this should have been shifted to a session value which is set within Ganga. I think this may look the same as being set from `GANGA_CONFIG_PATH` which is annoying as this would mean that a user cannot overload this value in keeping with the fact that you can't overload the site config as expected.

**Comment by rob-c** [comment]
OK after reviewing some of the changes when they happened I think this was because the tests reset the value back to the value from the codebase between tests.
We decided that the config _must_ be setup at module import rather than having this be somehow a configurable option or another step. I still personally dislike this but c'est la vie.

The result of this is that the LHCb config needs to change the session value rather than changing the default value as it's never fully _re-importable_ and is never truly un-loaded.
If there is a problem with a site being down _for instance_ this should be handled at a CERN site config I would argue and any external users can worry about implementing the changes for their site.

**Comment by egede** [comment]
@rob-c OK, so now I understand. This relates to the places in the code where the LHCb plugin is changing the default value of config items defined elsewhere (in the core presumably). You write that the user can't override the site config value. That goes against the precedence that I set out above and I do not understand why that is the case.

**Comment by rob-c** [comment]
@egede I just checked the code in Config.py and I think the order is what you say it is (Apologies I'm mis-remembering based upon a few different conversations about what we have).
I've just checked the Config code and the user value should always take priority and should be defined in the order you gave above.

@mesmith75 Can you change these values from within your .gangarc as you expect regardless of the values being in this section of the LHCb config?

**Comment by rob-c** [comment]
Actually I think this all worked for me I banned `SARA` privately when I was running some `DiracFile` tests and everything works as I expect.

**Comment by mesmith75** [comment]
This definitely doesn't work from the command line. It only works from the .gangarc if I change the gangadir to a new folder.

The logic of this doesn't make a great deal of sense to me. The LHCb plugin postBootstrapHook is the last thing that loads. The configOptions have the hasModified attribute but this never get queried so what was set gets overwritten and there is nothing to stop that.

**Comment by rob-c** [comment]
@mesmith75 Thanks for looking into this... I feared this could be the case which is slightly annoying.

I'll give this a look as the solution is a bit non-trivial I fear...

**Comment by mesmith75** [comment]
So the logic works with regard command-line vs. gangarc (if the variable is set at the command line it ignores the one in  the gangarc) . The problem is that these are being set as sessionValue rather than userValue. I'll find out where and stick a fix in.

**Comment by rob-c** [comment]
_all_ that's required from memory is to separate the user and system/session parameters I the precaching of the input which isn't being done correctly atm as it squashes everything into the system level so it's not possible to override .gangarc changes with command line ones i think.
