### ISSUE TITLE
Class not propagated using execfile

### ISSUE THREAD

**Issue by maubeck** [ganga-devs/ganga#833]
Hi all,
I tried to update to the newest ganga version on lxplus with the atlas setup on cvmfs but I got some problems with classes when using execfile.
What I do is setting up the ATLAS environment: 
`source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh`
then setting up the ganga verison (which is currently 6.2.2): 
`localSetupGanga`
setting up python over cvmfs (which is currently python 2.7.4-x86_64-slc6-gcc48) : 
localSetupPython
and then starting ganga.
I did a minimal setup where the problem can be seen. The files needed are saved here: 
https://cernbox.cern.ch/index.php/s/bCeCYcEmhR0XBSl
When doing
`execfile("userCode.py")`
The TestUtils.py are executed but when calling 
`methodCall()`
the class is not known. So it seems that the class definition is not propagated when using execfile. 
This worked for version Ganga-6-1-2
Is it intended that this will not work in newer versions of ganga ? 

Cheers,
Maurice

**Comment by maubeck** [comment]
Hi,
is there anything new on this topic?

Cheers,
Maurice

**Comment by alexanderrichards** [comment]
@drmarkwslater is our resident ATLAS person so I'll ping him

**Comment by drmarkwslater** [comment]
HI Maurice,

Apologies for not being in touch - I've been swamped with teaching and illness in the last month :disappointed: I'll make every effort to get back on the Ganga horse in the next few days!
