### ISSUE TITLE
Update LHCb Dirac version

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#835]
Just a reminder to update the default LHCbDirac version for the next release. There is a bugfix for the BK in v8r3p10 which would be good to have .

**Comment by rob-c** [comment]
@mesmith75 shouldn't users be able to access this from editing their .gangarc now?

**Comment by mesmith75** [comment]
@rob-c Yes they can. I just thought it would be good to update the default as well.

**Comment by rob-c** [comment]
I'm tempted to suggest adding some logic to allow us to track the latest as and when Ganga is launched and consider dropping the LHCbDirac project from the Ganga cmt config in time.

**Comment by egede** [comment]
@mesmith75 To ask users to change the Dirac version is dangerous. They will forget that they have done it, and they are then stuck on an old version that maybe a year later will give odd unpredictable errors.

@rob-c It is a bit of a tricky decision if we just follow the "latest" release. It again means that users might get a different experience to what we have been testing with.
