### ISSUE TITLE
Multiple sessions fails to update Repository correctly

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#837]
I've noticed that when running multiple sessions now I don't see jobs appear in one session that were newly created in another.
Nothing is falling over itself atm but at a glance I think the code to re-scan the repository for underlying changes had been removed or has moved.
It isn't insane to declare that new objects aren't safe to access between sessions and that accessing old objects which have been deleted would lead to problems but having some re-load functionality back in the registry would help keep the `jobs` summary consistent between sessions which may confuse users as it gets out of sync.
(I've confirmed no jobs are lost on disk due to not being present in the database on shutdown but it may cause some confusion, potentially with the master index is my only worry).

**Comment by egede** [comment]
Will be reconsidered as part of new persistency model
