### ISSUE TITLE
Remove additional load after flushing an object to disk

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#84]
When an object is flushed to disk the object is then immediately loaded back into memory and overloads itself.

This is an expensive operation and I'm not seeing a very good motivation for this to being performed on every single flush so I'm opting to have this removed.

**Comment by milliams** [comment]
I would guess that the reason for it it to make sure that the state is consistent by always relying on the load logic. However, I agree that if the rest of the code is working correctly then there is no need for it and it is only slowing things down.

**Comment by rob-c** [comment]
The load logic here replaces an object with itself after serializing it and de-serializing it from t he XML. There isn't any fancy logic other than replacing objects in memory with the new objects from disk.
