### ISSUE TITLE
GaussSplitter not overriding LHCbApp for GaudiExec

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#840]
I paste the email below. We had a problem before with the GaussSplitter overriding the LHCbApp options but it seems here to still not interacting with them properly.

I have 2 different jobs with 2 subjobs each. The former uses a private version of Gauss with GaudiExec, the latter a default Gauss version. Both use GaussSplitter

 GaussSplitter (
   numberOfJobs = 2,
   eventsPerJob = 50,
   firstEventNumber = 0
 )

as splitter. In the option file I setup the number of events to generate with

LHCbApp().EvtMax = 100

If I run the default version of Gauss then I get 50 events per subjobs correctly uncorrelated --> Don't know why the NextNext event (spillover event) seems to have the same seeds between subjobs, but the main event have different seeds so it is fine
If I run the same option file with GaudiExec then I get 100 events per subjobs, 50 of each are totally correlated among the 2 subjobs since they have the same seeds.
I know I can easily avoid the problem if I change

LHCbApp().EvtMax = 100 --> LHCbApp().EvtMax = 50

when I run with GaudiExec, but I'm wondering if this is a bug or a known behaviour.

**Comment by rob-c** [comment]
We can consider adding the `LHCbApp().EvtMax = 100` line into the extra options for `GaudiExec` however doing this for the `Gauss` application causes problems due to pickling and other related stuff going on.
Given this is easily fixed by the user I somehow feel this is a low priority and potentially a dangerous thing to introduce as we risk breaking `Gauss` again.

**Comment by mesmith75** [comment]
Perhaps but a less careful user won't notice that a significant portion of their events are not independent.

**Comment by rob-c** [comment]
The filename will be different to what they're expecting I think as the filename relies on this config doesn't it?

**Comment by mesmith75** [comment]
I can't see a way around this immediately. The ```ApplicationMgr``` doesn't seem to do anything and we can't mess with LHCb app after the options are pickled.

**Comment by rob-c** [comment]
@mesmith75 there is no pickling in `GaudiExec` I'm not sure I understand this?

**Comment by mesmith75** [comment]
Sorry, I've just read what you wrote again. Ok, I'll see if the LCHbApp option does the job for GaudiExec and check it doesn't mess up the SIMCOND tags etc.
