### ISSUE TITLE
Bugfix readInputData in GaudiExec

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#841]
I know there is not much appetite for keeping this feature but it seems like a lot of people still use it and I don't think it has been properly eradicated from the tutorials yet. At the moment is throwing up and error. I'll look into it.
```python
INFO     Started parsing input Data file
ERROR    PythonOptsCmakeParserError:
'GaudiExec' object has no attribute 'exec_cmd'                                                                                                                                      
ERROR    Error: ApplicationConfigurationError: Unable to parse the job options. Please check options files and extraopts. 

```

**Comment by egede** [comment]
@mesmith75 So I guess the annoying thing from an implementation point of view is that it depends on the "dry-run" feature of running a Gaudi application depending for determining which options eventually are set for the dataset. Nevertheless I agree that it is a feature that is used quite a lot.

**Comment by rob-c** [comment]
@mesmith75 Sorry for not being completely up to speed on this. Is this a broken function within `GaudiExec`?

**Comment by mesmith75** [comment]
@rob-c Sorry, should have been clear. This is just within GaudExec. The older applications are still fine.

**Comment by rob-c** [comment]
So if I'm correct there is a bug in the `readInputData` method? I don't see where resurrecting something comes into this?

**Comment by egede** [comment]
@rob-c I guess it is a bit more than just a bug. For `readInputData to work` you need to have a method to set up the local environment of the application and then run it. I guess we do not have that for the new style local release areas?

**Comment by rob-c** [comment]
@egede Is this not just a case of making use of `lb-run` and is just a simple case of changing the calls to `exec_cmd` to `execCmd`. This worked at some stage in testing and I think it broke when we changed the API and no test picked up that this method hadn't been updated.
`execCmd` makes sure that `lb-run` within the app directory works and then executes the command in the application env.
If there's something I've missed I'm happy to do some digging.

**Comment by mesmith75** [comment]
@rob-c I think it is just execCmd - exec_cmd. Poor choice of title on my part.

**Comment by egede** [comment]
@rob-c Yes, it may very well be that simple.
