### ISSUE TITLE
GangaDIRAC: /cvmfs Dirac.ini needs updating

### ISSUE THREAD

**Issue by twhyntie** [ganga-devs/ganga#842]
Hello,

I'm trying to run Ganga with the (GridPP) DIRAC back end and it's failing, I think because`Dirac.ini` needs updating as follows:

``` bash
$ cat /cvmfs/ganga.cern.ch/Dirac.ini
...
[DIRAC]
#DiracEnvFile = /cvmfs/ganga.cern.ch/dirac_ui/envfile # Deprecated, right?
DiracEnvSource = /cvmfs/ganga.cern.ch/dirac_ui/bashrc
...
```

As when I try submitting a job to the DIRAC backend I get:

``` bash
...
INFO     submitting job 6 to Dirac backend
ERROR    'DiracEnvSource' config variable empty
[more ERRORs]
```

Other than that I think it looks like it will work out of the box... what do you think?

Cheers, Tom

**Comment by twhyntie** [comment]
(Of course, adding:

```
[DIRAC]
DiracEnvSource = /cvmfs/ganga.cern.ch/dirac_ui/bashrc
```
to one's own `.gangarc` works too... but it would be great to have it configured out of the box :smile:)

**Comment by rob-c** [comment]
@drmarkwslater Would you be able to have a look at the cvmfs config if it needs updating?
@twhyntie Thanks for letting us know the config file is out of sync

**Comment by egede** [comment]
@drmarkwslater Did this ever happen? Close?

**Comment by afortiorama** [comment]
it's still not working

**Comment by afortiorama** [comment]
Infact I get this

ERROR    unknown configuration section: [defaults_GridCommand]
ERROR    unknown configuration section: [defaults_GridCommand]
ERROR    unknown configuration section: [defaults_GridProxy]
ERROR    unknown configuration section: [defaults_GridProxy]
ERROR    unknown options [LCG]GLITE_ENABLE
ERROR    unknown options [LCG]GLITE_ENABLE

**Comment by drmarkwslater** [comment]
Hiya! Sorry for the delay - this has now been fixed and I've updated Dirac on CVMFS as well so I **think** ganga should work out of the box now.

**Comment by afortiorama** [comment]
mmmhhh could you look at it again please?

```
aforti@vm7>/cvmfs/ganga.cern.ch/runGanga-dirac.sh

*** Welcome to Ganga ***
Version: 7.0.2
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


INFO     reading config file /cvmfs/ganga.cern.ch/Dirac.ini
ERROR    problems with loading Plugin /cvmfs/ganga.cern.ch/Ganga/install/7.0.2/ganga/GangaDirac
ERROR    Reason: GangaValueError: DIRAC Proxy `group` is not set. Set this in ~/.gangarc in `[defaults_DiracProxy]/group`
PluginError: Failed to load plugin: /cvmfs/ganga.cern.ch/Ganga/install/7.0.2/ganga/GangaDirac. Ganga will now shutdown to prevent job corruption.
(consider --debug option for more information)
INFO     Stopping Job processing before shutting down Repositories
INFO     Shutting Down Ganga Repositories
INFO     Registry Shutdown

```

**Comment by rob-c** [comment]
@afortiorama This is because you need to configure a file on your system `$HOME/.gangarc` This file needs to contain something like (I think the `_users` part is needed here from memory):

```
[defaults_DiracProxy]
group=lsst_users
```

Ganga has no way of knowing which default credential you plan to use when accessing grid resources so needs to be told this as part of the initial config.
