### ISSUE TITLE
Some jobs aren't picked up or progressed by monitoring loop

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#85]
Hi all,

I'm just adding a task to describe that I'm seeing some jobs not being progressed or picked up by the monitoring loop.

I've no concrete reproducible example yet, however in some situations I see that I can construct a job and it will not get picked up in the monitoring even if I wait for about 5min (The longest timeout for any of the monitoring variables was set to <30sec).
If I then restart ganga the monitoring correctly progresses the job through to the completed state (on the same machine) very quickly.
I can observe the jobs having finished externally so I have good reason to believe the monitoring loop is struggling somehow.

If I can construct a solid example of this I will but until then I can't help but wonder if this is related to the monitoring loop causing the shutdown to freeze on some occasions.

If any user experiences this the obvious solution is to advise them to restart ganga, but it would be much more convenient for us to correctly understand this.

Rob

**Comment by alexpearce** [comment]
I think I'm seeing the same thing. I see jobs where the Dirac status has long been “Done”, but Ganga stills says “Submitted”. I've even created a few very simple jobs, like `Job().submit()`, which appear as a mix of new/submitted in the `jobs` list.

I'm also seeing Dirac jobs finishing, but the `DiracFile` objects in the `outputfiles` of the subjobs aren't updated with the final LFN. I don't _think_ that's related to the monitoring loop, but I'll put it here just in case.

**Comment by alexpearce** [comment]
Add to that: jobs where all subjobs have `completed`, but the master job is still `running` or `submitted`.

**Comment by rob-c** [comment]
A word of caution. A repo containing lots of jobs with the Dirac backend will take a long time to progress between states. This is related to a combination of factors:

1. Large repos take a long time (still) to load into memory for monitoring. I plan to look at this further as time goes on.
2. Lots of jobs on Dirac require lots of forwards and backwards communication which happens on sub-threads currently making profiling/debugging more difficult that it should be.
3. If a single job causes problems the Montoring loop will get stuck (or delayed) for all jobs using that backend. This is probably related to the issue at hand but is a pain when the backend isn't the simple case of running on the Localhost.
4. Communication with Dirac often gets held up when one command suddenly takes much longer than usual to complete. It's not known if this is due to Ganga or the way we're accessing Dirac atm.


I think there are too many separate steps with regard to the DiracFile objects not being updated with the LFN. I have tested this briefly as part of the release and would prefer to open a separate issue if there are problems here as this is a different part of the codebase.

I suspect that seeing a lot of jobs not being migrated to the running state may be due to this but I say this with the points above in mind.

**Comment by alexpearce** [comment]
Thanks for the information, I understand it's a complicated issue. In these situtations, where something seems to be stuck but the user isn't sure whether it's a genuine problem or just something taking ‘a while’, is there a recommend course of action other than restarting Ganga?

**Comment by rob-c** [comment]
Unfortunately no, that's one of the reasons I made the bug to advise people. The best (and only real) solution is to turn it off and on again.

**Comment by alexpearce** [comment]
:+1: then off and on it shall go.

**Comment by egede** [comment]
When Ganga is in a state where it seems that things are not updated, it would be worth to look at if the worker threads are reported empty or not (the queues command I believe).

**Comment by rob-c** [comment]
@egede The original problem I'm seeing is that the thread pool inside the monitoring loop isn't cycling as expected and it's not always clear what is/isn't running there as there is no nice monitoring tool atm. But the worker threads could yes be occupied which is causing a delay until the current tasks have completed.

**Comment by egede** [comment]
@rob-c What happens if you stop the monitoring and restart it (without exiting Ganga)?

**Comment by rob-c** [comment]
@egede Unfortunately I don't know for certain, I've not had great success with this in the past. I think this is related to the fact I see the monitoring loop 'stall' on shutdown still and although this happens much less it hasn't gone away. So, because of this shutting down the monitoring loop in the session causes similar problems

**Comment by rob-c** [comment]
This may be improved by #182.

I'd like to keep this open to test stopping and starting the monitoring in an interactive Ganga session which 'should' work but has been fraught with difficulties.

**Comment by rob-c** [comment]
I believe this has been understood as part of 6.1.16, closing
