### ISSUE TITLE
Ganga credits and publications

### ISSUE THREAD

**Issue by twhyntie** [ganga-devs/ganga#853]
Hello,

I'm giving a talk about GridPP engagement etc. for SKA this week and Ganga will now be featuring as the UI of choice :smile:

Is there a list of people/funders to credit for development anywhere please? And any recent publications that it might be nice to cite?

Cheers, @twhyntie

**Comment by egede** [comment]
@twhyntie That is great to hear. Who is working on this from the SKA side? You, or somebody else? It would be great to hear more about the ideas. Concerning credit, it should go to Imperial College London, Birmingham University and GridPP. For publications, I am afraid that we have not have a recent publication, but you can give the DOI for the most recent release series, https://doi.org/10.5281/zenodo.61374, with https://zenodo.org/badge/DOI/10.5281/zenodo.61374.svg containing a nice image of the DOI link.

**Comment by twhyntie** [comment]
@egede Thanks! GridPP/Cambridge/Manchester at the moment - they have been playing with the IC GridPP DIRAC instance so far. All very preliminary but one thing to think about is integrating HPC into the workflow (though this is probably more of a DIRAC thing than a Ganga thing).

Will keep you posted!
