### ISSUE TITLE
pycrypto needs to be re-built with gcc49

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#86]
Hi all,

In releasing Ganga 6.1.14 for LHCb gcc49 I spotted that the external pycrypto is currently still built for gcc48.

I don't know how complex building this external is but I'd rather leave building of the externals to the experienced.

After a quick look I don't think this is particularly used in the Core so if it's easier to move this external to module rather than re-building it for gcc49 I propose this as a solution to the problem.

Thanks,

Rob

**Comment by egede** [comment]
@rob-c  pycrypto is **only** used for the remote backend. 

@drmarkwslater Did you say that the remote backend was broken anyway?

**Comment by drmarkwslater** [comment]
Basically yes - best thing to do at present is bypass it in the quickest way possible and I'll revisit the Remote backend at some point in the future

**Comment by rob-c** [comment]
@drmarkwslater Shall I just remove this from the list of Core externals for 6.1.15 in this case?

**Comment by drmarkwslater** [comment]
I think so - as I say, it's currently broken anyway and needs a rewrite!

**Comment by milliams** [comment]
I would suggest removing it from the list of externals. The `import paramiko` is inside a function call anyway so it shouldn't cause any import errors for users.

**Comment by rob-c** [comment]
@milliams I'm assuming you mean that we can drop both paramiko and pycrypto from the Core externals in this case?

**Comment by milliams** [comment]
@rob-c Yes, I think we can. The only place they are used (pycrypto is only there as an indirect dependency of paramiko) is inside the `opentransport()` method of `Remote`.

**Comment by milliams** [comment]
This was fixed by #94
