### ISSUE TITLE
Job status shown as "completed" despite having subjobs with "new" state

### ISSUE THREAD

**Issue by chrisburr** [ganga-devs/ganga#862]
Ganga appears to prioritise the "completed" state above "new" when computing the status of a job containing subjobs. I would expect the parent job to only be shown as "completed" when all subjobs are also completed.

Output of `jobs`:
<img width="879" alt="screen shot 2016-11-13 at 12 15 27" src="https://cloud.githubusercontent.com/assets/5220533/20245139/fb5bae0a-a99a-11e6-9377-ee5e5f68f637.png">

Output of `jobs(58).subjobs`:
<img width="879" alt="screen shot 2016-11-13 at 12 15 57" src="https://cloud.githubusercontent.com/assets/5220533/20245140/fc5ae6ae-a99a-11e6-9c3e-c0b7056eaefc.png">

**Comment by egede** [comment]
@chrisburr When all subjobs are finished (completed, failed, killed), the master job is no longer monitored. How did the job manage to get into this state?

**Comment by chrisburr** [comment]
I think it was caused by ganga being killed just before it finished submitting the job, I manually submitted 58.915 but missed 58.914.

I can reproduce this by killing ganga while it's half way through submitting a job using:
```python
j = Job(application=Executable(exe='/bin/echo', args=['Hello World']), backend=Dirac())
j.splitter = ArgSplitter(args=[[x] for x in range(100)])
j.submit()
```
The resulting job goes into the completed state despite still having many new jobs that were never submitted.

**Comment by rob-c** [comment]
@chrisburr Can you confirm the job status is the same as the summary i.e. run `job(a).subjobs(b).backend` to trigger loading this job from disk it could be that the index is incorrect.
Do you let ganga shut down correctly or do you force close the session? If you force close ganga we can't offer any assurance to the job statuses being correct as the registry hasn't been reliably flushed.

**Comment by chrisburr** [comment]
@rob-c I normally let ganga close gracefully, just in this instance it was unintentionally killed.

`jobs(58).subjobs(914).backend` returns a default instance of Dirac as I'd expect given this job was never submitted and doesn't appear in on the dirac web interface. I know that I can fix this particular job by calling `jobs(58).subjobs(914).submit()`.

The behaviour which I would think of as a bug is that the parent job's status can shown as completed despite some subjobs having never been submitted, even if this shouldn't normally happen.

**Comment by egede** [comment]
@chrisburr In principle the job should be in the status `submitting` but this is a transient status while the submission process is ongoing. In the case we have here, the submission process was terminated. I would be tempted to say that the job should go into the `failed` state.

**Comment by mesmith75** [comment]
Can we introduce a check for successful submission of all the subjobs?

**Comment by egede** [comment]
@mesmith75 I think a simple update of the code around https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/GPIDev/Lib/Job/Job.py#L746. If you just add `new` to the start ofthe list, the master job will revert to `new`. If calling `submit` on that job works this is actually fine.

**Comment by mesmith75** [comment]
ah yes.

**Comment by rob-c** [comment]
@chrisburr Were these jobs submitted sequentially or in parallel? If parallel then OK, if not I can't understand how the subjobs have managed to get into the state they're in.
@egede I'm not sure it's wise to add the 'new' status here. Changing the master job status back to a status earlier in the submission step is something which has to be done correctly ala the logic in `DiracBase`. We chose that if a subjob has submitted or is submitting the master job be moved to progress this. I imagine just enabling the 'new' attribute here will break a lot of the logic when the job is in the submitting step as a single subjob still in the new state could confuse the job status potentially. I'm not certain this is the case but it's what I remember it being last time I looked at this.

**Comment by egede** [comment]
@rob-c Yes, you are right that care has to be taken here. If the job submission is put on a queue, it could also open up for a job being submitted twice creating a race condition. It still seems fair enough to me that a job should not be able to go into `completed` unless all subjobs are `completed`. The current logic in the code implicitly ignores the situation that we have here.

**Comment by rob-c** [comment]
@egede Yes I think you're correct. We need a check to make sure that nothing is not in a completed state before progressing the master job to avoid problems as highlighted here.
I think moving the master job into `submitting` until all jobs are submitted would be appropriate and simply not allowing it to progress until all subjobs have been submitted seems correct.
Does the monitoring pick up jobs in a non `submitted` state? I forget where we got with that.

**Comment by egede** [comment]
@rob-c OK. I think I can see a solution now. The logic is that we want the master to show the "least progressed" state of the subjobs. However
 - That is not what we do now (as we ignore `new`)
 - Is not really what we want

The minimal change would be to leave the code as is and then just at the end add a check that if any (but not all) subjobs are in the `new` state, the master should be left in `submitting`. The side behaviour of this is that the monitoring will not start for the other subjobs, but I think that is actually OK.

**Comment by chrisburr** [comment]
@rob-c They were submitted sequentially. If the confusion is about `58.915` having been submitted, its because I manually submitted several jobs after ganga was killed (but missed `58.914`).

**Comment by egede** [comment]
Not important enough to fix.
