### ISSUE TITLE
importing little ganga doesn't import plugins

### ISSUE THREAD

**Issue by alexanderrichards** [ganga-devs/ganga#863]
```python
>>> import ganga
INFO     reading config file /home/local/ganga/.gangarc
>>> d=ganga.Dirac()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Dirac'
```

Note I have the plugin defined in my config

```ini
RUNTIME_PATH = GangaDirac
```

and it works interactively
```python
*** Welcome to Ganga ***
Version: 6.2.2
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


INFO     reading config file /home/local/ganga/.gangarc
[16:11:59]
Ganga In [1]: d=Dirac()

[16:12:02]
Ganga In [2]:
```

**Comment by rob-c** [comment]
@alexanderrichards Does this work if you define the config in your .gangarc?

This worked once upon a time for me as I did once submit a grid job this way.
I suspect the config for the `ganga` system doesn't read the env vars atm.

**Comment by alexanderrichards** [comment]
the config **was** defined in my `.gangarc`

**Comment by rob-c** [comment]
Ah, apologies this never made it into `develop` but is in a PR  have lying around. I'll see if I can clean something up for this quickly.

**Comment by alexanderrichards** [comment]
thanks @rob-c can you link it to this issue so I can keep track of it

**Comment by rob-c** [comment]
will do once I get anything in

**Comment by alexanderrichards** [comment]
@rob-c Don't want to rush you but if this is a simple fix it would be great if we could get it in the next release as I need it for some LZ work

**Comment by rob-c** [comment]
Hmm on closer inspection last night the `loadPlugins` call is in the `__init__.py` this could be due to the `ganga` not correctly parsing the config system before attempting to load things as it looks like the code I was thinking of has gone in but something has clearly changed breaking this in the meantime. I'll do some digging.

**Comment by rob-c** [comment]
@alexanderrichards check out #866 this fixes it for me.
