### ISSUE TITLE
hello world with ganga

### ISSUE THREAD

**Issue by gcongedo** [ganga-devs/ganga#865]
Hi all, I'm a new user on gridPP, and a fresher on ganga, but eager to crack on. I've tried a simple 'hello world' exercise with ganga following: https://www.gridpp.ac.uk/userguide/ganga-first-steps/ganga-first-steps.html but it throws errors. It'd be great if you could take a look into this - thanks so much for your help!

/cc @twhyntie  @alahiff

$ source /cvmfs/ganga.cern.ch/runGanga.sh

WARNING  Ganga will soon be depending on Python 2.7. You have Python 2.6 installed. See https://github.com/ganga-devs/ganga/wiki/Python-2.7

*** Welcome to Ganga ***
Version: 6.2.2
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.

INFO     LCG config is not set. Please set [LCG]VirtualOrganisation to your VO (e.g. "gridpp") or disable LCG with [LCG]GLITE_ENABLE=False
ERROR    A severe error occurred in the Repository 'prep.metadata': IOError on lock ('/home/tier1/gcongedo/gangadir/repository/gcongedo/LocalXML/6.0/sessions/global_lock'): [Errno 37] No locks available
ERROR    If you believe the problem has been solved, type "reactivate()" to re-enable 
INFO     Ganga is now attempting to shut down all running processes accessing the repository in a clean manner
INFO      ... Please be patient! 
ERROR    Unable to disable Internal services, they may have already been disabled!
RepositoryError:  (RepositoryError(...), "IOError on lock ('/home/tier1/gcongedo/gangadir/repository/gcongedo/LocalXML/6.0/sessions/global_lock'): [Errno 37] No locks available")
(consider --debug option for more information)
INFO     Stopping Job processing before shutting down Repositories
INFO     Shutting Down Ganga Repositories
INFO     Registry Shutdown

**Comment by twhyntie** [comment]
Thanks @gcongedo! Welcome to Ganga! 😄

**Comment by rob-c** [comment]
@gcongedo What filesystem are you using? I'm assuming some sort of nfs? in which case unless your running multiple ganga sessions (not strictly supported on a shared-fs) then this looks like a site config issue.

**Comment by gcongedo** [comment]
Hi @rob-c , thanks. It's NFS indeed.

**Comment by twhyntie** [comment]
Thanks @rob-c - in which case, any clues as how to fix this from the site side please? Is it something @alahiff might be able to help with if so?

**Comment by egede** [comment]
@gcongedo Take a look at #465 . The error means that the file system doesn't support file locking. Can you check with your local sys admin if you have `local_lock=all` as an option to the NFS mount. We need to be able to obtain what is called an `flock` on a file. Basically the code below should be able to work.

```
import os, fcntl
open("/home/tier1/twhyntie/gangadir/mylock", "w").close()
fd = os.open("/home/tier1/twhyntie/gangadir/mylock", os.O_RDWR)
fcntl.lockf(fd, fcntl.LOCK_EX)
fcntl.lockf(fd, fcntl.LOCK_UN)
```

To continue with your testing, you can maybe also move your `gangadir` to an non-NFS mounted disk. In your local `.gangarc` file, you can simply change the location of where Ganga keeps its metadata.

**Comment by twhyntie** [comment]
Thanks @egede! @gcongedo you'll need to replace `twhyntie` with `gcongedo` in that code, obviously 😄

**Comment by gcongedo** [comment]
Hi @egede , thanks. The code breaks up at:
>>> fcntl.lockf(fd, fcntl.LOCK_EX)
IOError: [Errno 37] No locks available

**Comment by egede** [comment]
@gcongedo That was what I would expect. 

@twhyntie Did you ever resolve this problem when you saw it? From looking at your file system path, it seems like you are located in the same place.

**Comment by twhyntie** [comment]
@egede I don't have this problem (and have never seen it) as I don't use a system that uses NFS.

@gcongedo It looks like the problem is with your cluster's NFS settings, not `ganga` per se. As @egede says, if you do not have somewhere else you can write files to (and set your `gangadir` accordingly) the configuration of the NFS system needs changing in order to proceed. Do you know who your site admin is?

**Comment by egede** [comment]
@twhyntie I think the problem you reported in #463 was the same.

**Comment by twhyntie** [comment]
@egede Indeed it was! Apologies, wow, was that only May? And of course I even have an account on the same cluster... I resolved it with your suggestion of setting `$HOME` to somewhere non-NFS.

@gcongedo In which case can you please try:

```bash
# Check the scratch directory exists (presumably if I had one you will too...).
$ ls /scratch/gcongedo
# (Temporarily) set your $HOME variable to somewhere non-NFS writeable. 
$ export HOME=/scratch/gcongedo
# Try running Ganga again.
$ source /cvmfs/ganga.cern.ch/runGanga.sh
```

Thanks and sorry again for the confusion!

**Comment by egede** [comment]
@twhyntie Which cluster is it that you have accounts on? Do you know the sysadmin? I would like to have a brief discussion with the sysadmin about the NFS options that are obviously causing trouble.

@gcongedo Rather than fiddling with the `$HOME` environment variable, I think it would be better to simply tell Ganga to store its information in a different location. You can either edit the `gangadir` variable in the `.gangarc` file (remember to take away the `#` at the beginning of the line), or you can simply start Ganga with a command line like

```
ganga -o'[Configuration]gangadir=/scratch/gcongedo/gangadir'
```

**Comment by twhyntie** [comment]
@egede I believe this is RAL Tier-1 cluster. @alahiff kindly provided me with the account back in May - one of many I've been using to test Ganga/DIRAC/etc. - I don't know if @alahiff is the sysadmin, or who is - but there is a lcg-admin email list that I will reply to too with the relevant config query.

I will also add some "gotcha" information to the UserGuide - this is a trivial problem that as you say can be overcome with a simple tweak of the configuration, but rather spoils the "out of the box" elegance of Ganga via CVMFS... - apologies @gcongedo, hang on in there! 😄

**Comment by gcongedo** [comment]
Thanks so much for your help, folks.

@twhyntie I've tried the temporary $HOME solution and it works!

@egede I see no .gangarc file, nor I can run 'ganga -o ...' (command not found)

**Comment by alexanderrichards** [comment]
you should have been asked if you wanted to create one on first usage. If not you can create a `~/.gangarc` file by running:
```bash
$ ganga -g
```

**Comment by egede** [comment]
@gcongedo It works for you so nevermind. The `.gangarc` will probably sit on the scratch file system now (as you have changed `$HOME`). The `ganga` just sits inside the `runGanga.sh` script. You should be able to just add it as an argument there

```
source /cvmfs/ganga.cern.ch/runGanga.sh -o'[Configuration]gangadir=/scratch/gcongedo/gangadir'
```

In fact I just tried this on a different system and it works for me.

**Comment by twhyntie** [comment]
@gcongedo Awesome! Thanks for letting us know. You should be able to work through the rest of the UserGuide - including the [CERN@school example](https://www.gridpp.ac.uk/userguide/example-workflow-local/example-workflow-local.html) (which from what you've described elsewhere, is very close to your workflow...).

And looking ahead, before you even [need DIRAC](https://www.gridpp.ac.uk/userguide/example-workflow-grid/example-workflow-grid.html), you can use the HTCondor backend by changing

```bash
j.backend = Dirac()
```

to

```bash
j.backend = Condor()
```

and it all just works the same. It's why we're using Ganga 😉

**Comment by gcongedo** [comment]
OK, great! Thanks so much to you all for the useful information. I'll follow the user guide and let you know. Fingers crossed! :-)
