### ISSUE TITLE
GangaDataset doesn't work for batch jobs

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#870]
A local job with the line
```
j.inputdata=GangaDataset(files=[LocalFile('/home/hep/egede/file1'), LocalFile('/home/hep/egede/file2')])
```
results in that the `__jobscript__` gets the line
```
open("__GangaInputData.txt__", "w").write( "\n".join( ['file:///home/hep/egede/file1', 'file:///home/hep/egede/file2'] ) )
```
injected. If the backend is changed to a batch backend, this no longer happens.

**Comment by egede** [comment]
The relevant code for writing the file is https://github.com/ganga-devs/ganga/blob/b9ef1b26def5daf93b09c7d831eff9cdaf7035da/python/Ganga/GPIDev/Lib/File/OutputFileManager.py#L341

**Comment by egede** [comment]
In fact this has never been implemented in the batch backends ...

**Comment by egede** [comment]
@JacekHoleczek Please follow up here.

**Comment by JacekHoleczek** [comment]
Many thanks.
I "backported" #871 to my Ganga 6.2.3 and it seems to work fine (see below for more details).

But first, could you, please, fix a small bug in the "python/Ganga/Lib/Batch/BatchScriptTemplate.py.template" file.
Change the line:
print("--- GANGA APPLICATION ERROR BEGIN ---", file=sys.stdout)
into:
print("--- GANGA APPLICATION ERROR BEGIN ---", file=sys.stderr)

BTW. For each job, in the "stderr" file, I get a warning (could one get rid of it?):
----------------------------------------------------------------------
/var/spool/torque/...: DeprecationWarning: The popen2 module is deprecated.  Use the subprocess module.
  import popen2
----------------------------------------------------------------------

And here's my "full report".

1. I ran my simple "job" and the splitter seems to work fine. There is a (small?) inconvenience, though. In the output of "jobs" and then also "jobs[0]", none of the (sub)jobs has a name. Then in the output of "qstat", all jobs have the same name "__jobscript__". Could you, please, create meaningful names for all subjobs, for example adding the internal "fqid" to the PBS (sub)jobs' names.

2. I ran my simple "task" and the splitter seems to work fine. There is a (small?) inconvenience, though. In the output of "qstat", jobs are named as "T0:0_U0", "T0:0_U1", and so on. Unfortunately, when a transform is additionally split into subjobs", all its subjobs have the same name in the output of "qstat". Could you, please, create meaningful names for all PBS subjobs. For example something like "T0:0_U0.0", "T0:0_U0.1", "T0:0_U0.2", ..., "T0:0_U1.0", "T0:0_U1.1", "T0:0_U1.2", ..., and so on.

**Comment by egede** [comment]
Can I get you to file the different issues below as individual new issues?
