### ISSUE TITLE
LocalFile inputdata

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#874]
It looks as if LocalFiles cannot be used for inputdata for local testing. The directory path gets stripped off so only the namePattern is used. Is this a deliberate choice or something we should fix?

**Comment by egede** [comment]
@mesmith75 This is for an LHCb dataset? When I tried with a `GangaDataset` and with `LocalFile` objects that had a full path in them, it seemed to be forwarded to the job script in the correct way.

**Comment by mesmith75** [comment]
@egede  Sorry, it does work fine, I just wasn't using LHCbDataset.

**Comment by rob-c** [comment]
If there is a use case that doesn't work should we add a check to disallow users from doing something bad?

**Comment by mesmith75** [comment]
So this definitely doesn't work for LHCbDataset.

I am wondering if returning the full path rather than just the name would break anything?
