### ISSUE TITLE
Overly verbose error message when LFN not available

### ISSUE THREAD

**Issue by mrwillia** [ganga-devs/ganga#887]
I had some ganga jobs fail this morning due to the unavailability of input files (they were on a site that is having planned down time today). The message I see includes a long stack trace that obfuscates the original reason for the failure. Perhaps this should not be shown. This issue was created on the suggestion of Robert Currie.

I am running on the dirac back-end, and tested both boole jobs and brunel jobs, both show similar errors. 

Here is the full message dumped to my screen:

> Ganga In [3]: ganga boole/boole-ganga_planB.py 1771
> INFO     Job 1783: Preparing Boole application.
> INFO     submitting job 1783
> INFO     job 1783 status changed to "submitting"
> INFO     Job 1783's application has already been prepared.
> INFO     Splitting Job: 1783
> INFO     Constructing subjobs
> INFO     Requesting LFN replica info
> INFO     Got Replica Info: [0:250] of 438
> INFO     Got Replica Info: [250:438] of 438
> WARNING  LFN:
> /lhcb/user/m/mrwillia/2016_11/146305/146305859/Gauss_MinBias_11102003.sim
> was either unknown to DIRAC or unavailable, Ganga is ignoring it!
> WARNING  LFN:
> /lhcb/user/m/mrwillia/2016_11/146307/146307131/Gauss_MinBias_11102003.sim
> was either unknown to DIRAC or unavailable, Ganga is ignoring it!
> WARNING  LFN:
> /lhcb/user/m/mrwillia/2016_11/146307/146307419/Gauss_MinBias_11102003.sim
> was either unknown to DIRAC or unavailable, Ganga is ignoring it!
> WARNING  LFN:
> /lhcb/user/m/mrwillia/2016_11/146305/146305859/Gauss_MinBias_11102003.sim
> was either unknown to DIRAC or unavailable, Ganga is ignoring it!
> WARNING  LFN:
> /lhcb/user/m/mrwillia/2016_11/146307/146307131/Gauss_MinBias_11102003.sim
> was either unknown to DIRAC or unavailable, Ganga is ignoring it!
> WARNING  LFN:
> /lhcb/user/m/mrwillia/2016_11/146307/146307419/Gauss_MinBias_11102003.sim
> was either unknown to DIRAC or unavailable, Ganga is ignoring it!
> WARNING  LFN:
> /lhcb/user/m/mrwillia/2016_11/146307/146307461/Gauss_MinBias_11102003.sim
> was either unknown to DIRAC or unavailable, Ganga is ignoring it!
> ERROR    Errors found getting LFNs:
> []
> WARNING  ---------- error in user/extension code ----------
> WARNING  Traceback (most recent call last):
> WARNING    File
> "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r3/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py",
> line 1472, in submit
> WARNING      rjobs = self._doSplitting()
> WARNING    File
> "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r3/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py",
> line 1361, in _doSplitting
> WARNING      subjobs = self.splitter.validatedSplit(self)
> WARNING    File
> "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r3/install/ganga/python/Ganga/GPIDev/Adapters/ISplitter.py",
> line 70, in validatedSplit
> WARNING      subjobs = self.split(stripProxy(job))
> WARNING    File
> "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r3/install/ganga/python/GangaLHCb/Lib/Splitters/SplitByFiles.py",
> line 195, in split
> WARNING      split_return = super(SplitByFiles, self).split(job)
> WARNING    File
> "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r3/install/ganga/python/GangaGaudi/Lib/Splitters/GaudiInputDataSplitter.py",
> line 70, in split
> WARNING      for dataset in all_jobs:
> WARNING    File
> "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r3/install/ganga/python/GangaDirac/Lib/Splitters/OfflineGangaDiracSplitter.py",
> line 349, in OfflineGangaDiracSplitter
> WARNING      raise SplittingError("Error trying to split dataset with
> invalid LFN and ignoremissing = False")
> WARNING  SplittingError: Error trying to split dataset with invalid
> LFN and ignoremissing = False
> WARNING  --------------------------------------------------
> ERROR    Error trying to split dataset with invalid LFN and
> ignoremissing = False ... reverting job 1783 to the new status
> INFO     job 1783 status changed to "new"

> JobError                                  Traceback (most recent call last)
> /afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r3/external/ipython/1.2.1/noarch/lib/python/IPython/utils/py3compat.py
> in execfile(fname, *where)
>     202             else:
>     203                 filename = fname
> --> 204             __builtin__.execfile(filename, *where)
> 
> /afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r3/install/ganga/bin/ganga
> in <module>()
>      61 j.do_auto_resubmit = True
>      62 j.prepare()
> ---> 63 j.submit()
>      64
> 
> /afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r3/install/ganga/python/Ganga/GPIDev/Base/Proxy.py
> in proxy_wrapped(*args, **kwargs)
>     666         s_args = [stripProxy(a) for a in args]
>     667         s_kwargs = dict((name, stripProxy(a)) for name, a in
> kwargs.items())
> --> 668         r = f(*s_args, **s_kwargs)
>     669         return addProxy(r)
>     670
> 
> /afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r3/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py
> in submit(self, keep_going, keep_on_fail, prepare)
>    1470             logger.debug("Checking Job: %s for splitting" %
> self.getFQID('.'))
>    1471             # split into subjobs
> -> 1472             rjobs = self._doSplitting()
>    1473
>    1474             # Some old jobs may still contain None assigned to
> the self.subjobs so be careful when checking length
> 
> /afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r3/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py
> in _doSplitting(self)
>    1359             logger.info("Splitting Job: %s" % fqid)
>    1360
> -> 1361             subjobs = self.splitter.validatedSplit(self)
>    1362             if subjobs:
>    1363                 if not isType(self.subjobs, (list, GangaList)):
> 
> /afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r3/install/ganga/python/Ganga/GPIDev/Adapters/ISplitter.py
> in validatedSplit(self, job)
>      68
>      69         # try:
> ---> 70         subjobs = self.split(stripProxy(job))
>      71         # except Exception,x:
>      72         #raise SplittingError(x)
> 
> /afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r3/install/ganga/python/GangaLHCb/Lib/Splitters/SplitByFiles.py
> in split(self, job)
>     193                 logger.debug("Returning []")
>     194                 return []
> --> 195         split_return = super(SplitByFiles, self).split(job)
>     196         logger.debug("split_return: %s" % split_return)
>     197         return split_return
> 
> /afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r3/install/ganga/python/GangaGaudi/Lib/Splitters/GaudiInputDataSplitter.py
> in split(self, job)
>      68         logger.info("Constructing subjobs")
>      69         logger.debug("Filling DataSet")
> ---> 70         for dataset in all_jobs:
>      71             logger.debug("Creating Subjobs with dataset of
> size: %s" % str(len(dataset)))
>      72             #logger.debug( "Creating Subjobs with dataset: %s"
> % str(dataset) )
> 
> /afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r3/install/ganga/python/GangaDirac/Lib/Splitters/OfflineGangaDiracSplitter.py
> in OfflineGangaDiracSplitter(_inputs, filesPerJob, maxFiles,
> ignoremissing)
>     347         if ignoremissing is False:
>     348             logger.error("Errors found getting LFNs:\n%s" % str(errors))
> --> 349             raise SplittingError("Error trying to split
> dataset with invalid LFN and ignoremissing = False")
>     350
>     351     # This finds all replicas for all LFNs...
> 
> JobError: JobError: Error: Error trying to split dataset with invalid
> LFN and ignoremissing = False
> 
> [12:19:00]

**Comment by mesmith75** [comment]
We can check the read status of SEs now. Should we add that into the splitter?

**Comment by rob-c** [comment]
@mesmith75 Potentially yes, but this would likely be a very expensive op. It is essentially also done in the splitter, hence why it raises an exception. The problem is that the user gets far too much verbosity to the screen when the job fails to submit due to expected reasons. This needs looking into.
