### ISSUE TITLE
Have the .gangarc loaded and checked for each package on module imported

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#89]
When the config system is initially setup (now in `__init__.py` - see #87), the .gangarc file should be loaded, cached and then each option checked for the package. This should then allow:

```
import Ganga    # config system setup, all config options created are checked in .gangarc
import GangaDirac   # additional config options are created and checked against the cached .gangrc
```

This can then be mostly removed from bootstrap.py.

**Comment by egede** [comment]
This is implemented and working
