### ISSUE TITLE
ganga athena --local not executing joboptions in 6.2.3

### ISSUE THREAD

**Issue by will-cern** [ganga-devs/ganga#893]
Hello,

I just tried using the --local option in ganga athena in the version I get from cvmfs by default (6.2.3 apparently). The job fails, the issue appears to be because the joboptions are not executed. 

It would be useful if in the log file ganga would print the exact athena command it is executing, as it can be hard to work out what is at fault here. You can reproduce the problem by putting, e.g. just "import AthenaRootComps.ReadAthenaxAODHybrid" in a joboption file and then do:

ganga athena --local --inputtype Local --locallocation '/some/input/files' '*.root*' --split=4 --outputlocation="/path/to/somewhere" --outputtype 'ATLAS' --extOutFile 'blah.txt' jobo.py

Note I had to specify an output file just to get ganga to run this. That is another thing, ganga should surely allow us to submit jobs that produce no output, no?

Anyway, my log files from the above suggests jobo.py doesn't run, just the preexec and the input.py, and the latter causes the failure because the EventSelector isnt set up.

Sorry for reporting all these problems in one go, I hope this only affects the --local option and not the other options??

Thanks
Will

**Comment by will-cern** [comment]
I can confirm that this isn't a problem with the --condor option at least.

**Comment by will-cern** [comment]
Any progress on this?
I know you are busy, just good to have an idea on when this might be looked it. It prevents us running with the --local option at the moment.

Thanks
Will

**Comment by mesmith75** [comment]
Can we close this?
