### ISSUE TITLE
Missing configuration option in default .gangarc file - [defaults_DiracProxy]

### ISSUE THREAD

**Issue by twhyntie** [ganga-devs/ganga#895]
Hello,

It looks like with the roll-out of 6.3.0 a configuration option has been missed in the default `.gangarc` file, so running via CVMFS throws an error:

```bash
ERROR    problems with loading Plugin /cvmfs/ganga.cern.ch/Ganga/install/LATEST/python/GangaDirac
ERROR    Reason: GangaValueError:  ('DIRAC Proxy `group` is not set. Set this in ~/.gangarc in `[defaults_DiracProxy]/group`',)
```

The culprit looks to be `[defaults_DiracProxy]`, which for me had no value assigned when I ran 6.3.0 for the first time.

Is this is intentional, as you can't know by default which user group a user will be using? If so, could there be a more graceful fail if no value is supplied, or a user prompt to set it?

Many thanks as ever, @twhyntie

PS: Thanks to @willfurnell and Giuseppe (EUCLID) for pointing this out :smile:

**Comment by twhyntie** [comment]
OK, so this appears to have opened bit of a can of worms... with my updated configuration file when I now try to close Ganga (Ctrl-D, Enter) I get:

```bash
Ganga In [1]: 
Do you really want to exit ([y]/n)? 

ERROR    XML to-file error for file:
unbound method accept() must be called with DiracProxy instance as first argument (got VStreamer instance instead)
INFO     Stopping the monitoring component...
INFO     Stopping Job processing before shutting down Repositories
INFO     Shutting Down Ganga Repositories
INFO     Registry Shutdown
ERROR    A severe error occurred in the Repository 'jobs': Error of type: <class 'Ganga.Core.GangaRepository.VStreamer.XMLFileError'> on flushing id '415': XMLFileError: to-file error (<type 'exceptions.TypeError'>:unbound method accept() must be called with DiracProxy instance as first argument (got VStreamer instance instead))
ERROR    If you believe the problem has been solved, type "reactivate()" to re-enable 
ERROR    Cannot disable monitoring loop. It has already been stopped
INFO     Ganga is now attempting to shut down all running processes accessing the repository in a clean manner
INFO      ... Please be patient!
ERROR    Unable to disable Internal services, they may have already been disabled!
INFO     Ganga is shutting down the repository, to regain access, type 'reactivate()' at your prompt
ERROR    XML to-file error for file:
unbound method accept() must be called with DiracProxy instance as first argument (got VStreamer instance instead)
ERROR    A severe error occurred in the Repository 'jobs': Error of type: <class 'Ganga.Core.GangaRepository.VStreamer.XMLFileError'> on flushing id '415': XMLFileError: to-file error (<type 'exceptions.TypeError'>:unbound method accept() must be called with DiracProxy instance as first argument (got VStreamer instance instead))
ERROR    If you believe the problem has been solved, type "reactivate()" to re-enable 
ERROR    Cannot disable services, they've already been disabled
INFO     Ganga is now attempting to shut down all running processes accessing the repository in a clean manner
INFO      ... Please be patient! 
ERROR    Unable to disable Internal services, they may have already been disabled!
ERROR    Exception on flushing 'jobs' registry: RepositoryError:  (RepositoryError(...), "Error of type: <class 'Ganga.Core.GangaRepository.VStreamer.XMLFileError'> on flushing id '415': XMLFileError: to-file error (<type 'exceptions.TypeError'>:unbound method accept() must be called with DiracProxy instance as first argument (got VStreamer instance instead))")
```

I don't have any proxies initiated, but I'm only doing local running (at the moment) so I wouldn't expect Ganga to expect that there was one active.

Any ideas?

**Comment by twhyntie** [comment]
Ah, no, ignore that - started up again, quit, no errors.

**Comment by rob-c** [comment]
@twhyntie The error in your second comment is being addressed in #901 and #902 and is due to a bug creeping in, in the final stages of 6.3 development.
As for the defaults with regard to the DIRAC configuration these need to be provided by the user as Ganga can't automatically detect your VO or what storage spaces you have access to very easily.
I think there may be some work which can be done to address the latter but the former requires explicit user input I think still.

**Comment by twhyntie** [comment]
@rob-c Cool, thanks - I agree that automatic VO/storage is a luxury at this point, and I'll happily put the instructions to do this in the UserGuide 😄 
When do you think the best time to do this will be - is there a stable-ish 6.3.X update slated in the near future?
Thanks again, @twhyntie

**Comment by rob-c** [comment]
@twhyntie I was under the impression 6.3.0 was going to be stable. That being said there are some minor bugs which are obviously present so I think 6.3.1 is being released later today/tomorrow.
@mesmith75 Is this correct?

**Comment by twhyntie** [comment]
@rob-c Great, thanks - in which case I will wait for 6.3.1 :wink:
(cc @willfurnell)

**Comment by mesmith75** [comment]
@rob-c Yes I will start the release this evening - so should be done by tomorrow morning.

**Comment by mesmith75** [comment]
Can we close this?
