### ISSUE TITLE
Importing Ganga in Python scripts

### ISSUE THREAD

**Issue by willfurnell** [ganga-devs/ganga#900]
Hello,
I'm a brand new user of Ganga (and relatively new to Grid Computing in general) and I'm looking into integrating it into some analysis software I am developing for [CERN@school](http://researchinschools.org/CERN/) (with help from @twhyntie). I can see that you can create scripts and run them in [batch mode](http://ganga.readthedocs.io/en/latest/UserGuide/InstallAndBasicUsage.html#scripting-and-batch-mode) which does look like a great feature. 
However, if possible I would like to import Ganga directly into my code so I can call and initialise Job objects etc. and run jobs locally or on [GridPP](https://www.gridpp.ac.uk/) quickly and easily providing very few parameters as needed, and automating uploading files to DIRAC storage, by being able to call a script like:
```
python run-analysis.py frames.zip
```
Is something like this possible using Ganga?

(I'm currently using the CernVM and accessing Ganga via CVMFS. I've done some research and seen it might be possible to import when putting /cvmfs/ganga.cern.ch/Ganga/install/LATEST/python/ in my Python library path).

Thank you,
Will Furnell.

**Comment by egede** [comment]
@willfurnell Yes, you can do 

```
import ganga
```

which gives you access to the global functions like `jobs` in the `ganga` namespace. To get access to the API, do something like 

```
from ganga import Job
```

To allow Ganga to be used like this is a quite new feature. Please report any problems you might see.

**Comment by willfurnell** [comment]
That sounds brilliant, thank you - exactly what I want to do.
I'll let you know if I encounter any issues.
Thanks.

**Comment by twhyntie** [comment]
Thanks @egede!
