### ISSUE TITLE
Monitoring Error and XML from-file error for file

### ISSUE THREAD

**Issue by vlukashenko** [ganga-devs/ganga#904]
Hi, everyone. I’m quite new with Ganga and I have a big issue with it now.

I had two jobs that were submitting for a week already, so I tried to change their status to the “failed”, but I got a connection loss at this very moment and now every time I setup ganga project I see those errors:
```
ERROR    Monitoring Error: Credential store query should be of type ICredentialRequirement
ERROR    XML from-file error for file:
object of type 'NoneType' has no len()
close failed in file object destructor:
---------------------------------------------------------------------------
XMLFileError                              Traceback (most recent call last)
/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v603r0/install/ganga/python/Ganga/Core/GangaRepository/SubJobXMLList.py in _getItem(self, index)
    404                         subjob_data = self.__get_dataFile(str(index), True)
    405                         sj_file = self._loadSubJobFromDisk(subjob_data)
--> 406                         loaded_sj = from_file(sj_file)[0]
    407                         has_loaded_backup = True
    408                     except (IOError, XMLFileError) as err:

/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v603r0/install/ganga/python/Ganga/Core/GangaRepository/VStreamer.py in from_file(f)
     97     except Exception as err:
     98         logger.error("XML from-file error for file:\n%s" % err)
---> 99         raise XMLFileError(err, "from-file error")
    100
    101 ##########################################################################
```
It also doesn’t like that first job, which is now in “failed” status (another one is still submitting), so I can’t kill it or remove it at all. Every time I try to do that same errors appear. All other jobs are okay, but those errors started to appear all the time, even if I don’t touch the “bad” jobs. 

Have no idea what to do with it.

Thank you very much for your help or any kind of advice.

Lera

**Comment by rob-c** [comment]
@vlukashenko I believe this should be fixed by https://github.com/ganga-devs/ganga/pull/901
If you are comfortable using a git branch then I'd advise testing on this PR as it should solve the problems your seeing.

**Comment by rob-c** [comment]
This is a duplicate issue so I'm closing it for now. If anyone wants to follow this I would follow #901 and #902
