### ISSUE TITLE
Update CVMFS config

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#905]
Does anyone know how to update the CVMFS config? We need to get rid of the ```[LCG]EDG_ENABLE,GLITE_ENABLE``` and ```[defaults_AfsCommand]``` options for 6.3. This was already done for the AFS release.

**Comment by rob-c** [comment]
@mesmith75 Which CVMFS config? The one we control on our partition is done via adding a new system file (which should propagate correctly via cvmfs) and the one done via LHCb is done via requesting the release manager put a new file up in the appropriate place.

**Comment by mesmith75** [comment]
@rob-c The site config. The one on CVMFS is pretty ancient - I'll stick in a JIRA task for it to be updated, Thanks!

**Comment by rob-c** [comment]
@mesmith75 just a quick NB but remember we can't edit files reliably on cvmfs due to the caching so we should look to release a new config under 6-3-0.

**Comment by mesmith75** [comment]
Sorted.
