### ISSUE TITLE
Can't submit a DIRAC job with DiracFile outputfile without setting a defaultSE. (Dirac backend)

### ISSUE THREAD

**Issue by willfurnell** [ganga-devs/ganga#906]
Hello,
I'm having an issue with trying to store output data using DIRAC as a backend.
I'm getting the following error when trying to run my job:
```
Can't submit a DIRAC job with DiracFile outputfile without setting a defaultSE. (Dirac backend)
```
Here's my job file:
```
## The Ganga job.
j = Job()

# Name the job.
j.name = "CERN@school_dirac_02"

# Tell Ganga it's running an executable: run.sh
j.application = Executable()
j.application.exe = File('run.sh')

# run.sh takes one argument - the dataset directory.
j.application.args = ['B06-W0212/2014-04-02-150255/']

# Specifiy which local files to upload with the job.
j.inputfiles = [ DiracFile('CERNatschool.zip') ]

# Specify which files should be downloaded as output from the job.
j.outputfiles = [ DiracFile('frames.json'), LocalFile('log_process-frames.log'), DiracFile('output_images.tar') ]

j.backend = Dirac()
j.submit()
```
Where do I need to set defaultSE in my .ganagarc file? I've tried the following
```
[DIRAC]
defaultSE = UKI-LT2-QMUL2-disk
```
(And different iterations eg. DefaultSE, DiracDefaultSE etc.)

I'm using Ganga via CVMFS.

Thank you,
Will

**Comment by egede** [comment]
@drmarkwslater I think you are best at understanding this.

**Comment by rob-c** [comment]
@egede This is expected behaviour. GridPP DIRAC at least can't work out where to put a file on the grid without being told where it can upload the files to. This behaviour should be easy enough to change but I think it involves another discussion with some DIRAC devs about how to safely get a list of default SE that a user can write to. (or whether vanilla-DIRAC plans to support some sort of failover way of uploading a file until it worked. We can do it in Ganga but it involves some new development work on the handling of job scripts for DIRAC files.)

**Comment by willfurnell** [comment]
I've done a bit of searching in the code and this repository, and have found the following file:
https://github.com/ganga-devs/ganga/blob/b9ef1b26def5daf93b09c7d831eff9cdaf7035da/python/GangaLSST/LSST.ini which seems to include the option I want.

By setting 
```
[defaults_DiracFile]
defaultSE = 'UKI-LT2-QMUL2-disk'
```
in my ~/.diracrc I can now submit output data to the Grid! Thank you.

Would it be acceptable for me to submit a pull request to make this a bit clearer in the documentation - on how to set this option (http://ganga.readthedocs.io/en/latest/UserGuide/InputAndOutputData.html) - or should I do this in the GridPP documentation (@twhyntie) instead? Thanks.

**Comment by twhyntie** [comment]
@willfurnell Nice once, thanks 😄 
As @rob-c has noted this is a DIRAC - and, to be fair, GridPP DIRAC - specific issue (as Ganga users generally may not be using DIRAC, or the [GridPP DIRAC](https://dirac.gridpp.ac.uk) instance) so I can add this to the GridPP UserGuide - please raise an [issue](http://github.com/gridpp/user-guides/issues).
Thanks again, @twhyntie

**Comment by willfurnell** [comment]
I can see why it will be better to put this in the UserGuide with the limited scope of Ganga users it would cover. I'll raise an issue with the GridPP userguides repository. Thanks.
