### ISSUE TITLE
Nightlies failing in odd way

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#908]
The following test is an example of the recent failing nightlies.

The test in question works fine when I run locally in what I believe is the equivalent to a DIRAC env and when the tests are run on integration tests but for the nightlies there is a bug of some sort which prevents the test from running:

```
>       assert getConfig('Output')[_getName(self.fileClass)]['backendPostprocess']['Local'] == 'client'
E       KeyError: 'Local'
```

I'm not expecting to see a bug in the configuration system but this has been changed recently so has this altered the way that tests now configure themselves?

https://ganga-ci.cern.ch/jenkins/job/Nightly/539/testReport/junit/python.Ganga.test.GPI.FileTests.TestMassStorageClient/TestMassStorageClient/test_a_testClientSideSubmit/

**Comment by mesmith75** [comment]
Naively I wouldn't have thought that the changes to the config I put in should have affected that. It looks as if the configuration files on the master node carrying out the nightlies are very old.

Alternatively maybe we have overlooked something now in the default configurations.

**Comment by rob-c** [comment]
@mesmith75 Yes the exception there looks like a bug to me that should have been spotted sooner.
(Advantage of testing with multiple env configs we can try to get through these different code paths in testing).
I'll have a look at how the options for the tests are parsed. I suspect this is due to the tests making changes at the system level and other changes are being incorporated at the user level now which isn't necessarily what we want.

**Comment by rob-c** [comment]
`FakeDirac` is also now escaping the bounds of the single test where it was intended to be loaded.
This test needs to be fixed again to stop the class being in the Plugin system which will break other tests looking for the backend.

**Comment by egede** [comment]
Nightlies have been fixed.
