### ISSUE TITLE
GaudiBase loses version

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#909]
It appears that creating an old style LHCb app from a python script loses the version number.
eg
```python
j = Job(application = DaVinci(version = 'v38r1p1'))
```
works fine at the ganga prompt but from a script tries to create an object with the latest version that fails as setup project doesn't exist anymore.

**Comment by rob-c** [comment]
@mesmith75 Can you confirm if this is nested options parsing being broken again or the old style apps?
AKA do we see this with say:
```
j=Job(application=GaudiExec(directory='blah'))
```
If it's the old style apps I'm fairly sure we saw something like this before and never solved it. If it's a general bug it will likely be in the Proxy and I can walk through what would be involved to track it down at some point.

**Comment by mesmith75** [comment]
On closer inspection it looks as if the job object picks up the version correctly. However the GaudiBase doesn't pick up the job version so tries to use the default.

**Comment by mesmith75** [comment]
Actually, sorry this is nonsense. Apologies for the noise.
