### ISSUE TITLE
Spurious error at startup

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#92]
Copying From: https://its.cern.ch/jira/browse/GANGA-2039

Startup error looks like:

```
[11:16:25 lxplus0049: ~]$ rm .gangarc
[11:16:36 lxplus0049: ~]$ ganga

*** Welcome to Ganga ***
Version: 6.1.14
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


Ganga.Utility.Config               : INFO     reading config file /afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r14/install/ganga/python/GangaLHCb/LHCb.ini
Ganga.Utility.Config               : INFO     reading config file /afs/cern.ch/sw/ganga/install/config/LHCb/6-1-11/CERN.ini
Ganga.Utility.Config               : ERROR    sanity check failed: defaults_BoxMetadataObject: no makeConfig() found in the code
Would you like to create default config file ~/.gangarc with standard settings ([y]/n) ?
y
Ganga.Runtime.bootstrap            : INFO     Creating ganga config file /afs/cern.ch/user/r/rmatev/.gangarc
Press <Enter> to continue.


[11:17:28]
Ganga In [1]:
Do you really want to exit ([y]/n)? y



  27
Ganga.Core.InternalServices        : INFO     Stopping running tasks before shutting down Repositories
Ganga.Core.InternalServices        : INFO     Shutting Down Ganga Repositories
Ganga.Runtime                      : INFO     Registry Shutdown
[11:17:34 lxplus0049: ~]$ ganga

*** Welcome to Ganga ***
Version: 6.1.14
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


Ganga.Utility.Config               : INFO     reading config file /afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r14/install/ganga/python/GangaLHCb/LHCb.ini
Ganga.Utility.Config               : INFO     reading config file /afs/cern.ch/sw/ganga/install/config/LHCb/6-1-11/CERN.ini
Ganga.Utility.Config               : INFO     reading config file /afs/cern.ch/user/r/rmatev/.gangarc
Ganga.Utility.Config               : ERROR    sanity check failed: defaults_BoxMetadataObject: no makeConfig() found in the code

[11:17:41]
Ganga In [1]:
```

**Comment by rmatev** [comment]
Ah sorry, I didn't realise you also migrated the issues here.

**Comment by rob-c** [comment]
@rmatev Are you able to update to and test the latest code in git? We've changed a lot of the Config system in Core.
If you need I can provide some instructions

**Comment by rmatev** [comment]
Some instructions or a pointer would be great. I won't be able to test it before Monday.

**Comment by rob-c** [comment]
@rmatev Apologies I've been a bit busy this week, I plan to setup a wiki page with instructions for LHCb users on how to test the latest code I'll update this once I've done that.

I'm now seeing this on my latest dev branch and appears to be a bug which has been recently exposed.

This problem goes away if I include the following in ```Ganga/__init__.py```
```
box_config = makeConfig('defaults_BoxMetadataObject', 'Config part required for BoxMetadataObject')
box_config.addOption('name', '', 'default Name to give to objects in Box Registry')
```

I suspect what is happening is that a BoxMetadataObject isn't being constructed during the config phase which would lead to the Schema not being loaded until after the Config has completed.
@milliams and @drmarkwslater Do either of you know if this is possible?

**Comment by milliams** [comment]
Yes, it seems like perhaps the `BoxRegistry` module is not being imported until after the config has run. It's strange though that it's not affecting `JobRegistry` etc.

**Comment by rob-c** [comment]
From what I can tell the Registry is imported fine however I suspect that it's possible that no ```BoxRegistryMetadata``` instance is declared until after the config has been parsed.

Would constructing a new Schema object after the 'defaults' have been initialized in the config lead to problems is it known?

**Comment by rob-c** [comment]
After wading through ```ganga --debug``` everything is initialized before this error is printed which leads me to suspect that the box.metadata repo should handle initializing this if it's not automatically constructed on startup.

**Comment by milliams** [comment]
When a `GangaObject` is created, as part of the metaclass construction it should run `Schema.createDefaultConfig()` which is where `makeConfig()` is called. If a schema is created outside of a `GangaObject` then perhaps this could break but I don't see how otherwise.

What the error is saying is that at the time that `Ganga.GPIDev.Lib.Config.Config.bootstrap()` is run, a config section in `allConfigs` exists called `defaults_BoxMetadataObject` which was made via some method other than `makeConfig()` (since that is where `_config_made` is set to `True`). However, the only place we create anything beginning with `defaults_` is in `Schema.createDefaultConfig()`.

Ahh, except in `Schema._getDefaultValueInternal()` there's a call to `Ganga.Utility.Config.getConfig(def_name)` and that function, if it can't find a config will create one from scratch, not using the `makeConfig()` function (which is a behaviour I've complained about before, I think it should instead raise an exception). So, perhaps there's a schema object being made and having the default value questioned before the `GangaObject` it exists in has been created.

**Comment by rob-c** [comment]
Not having looked at the code surely the better behaviour is to fix ```Schema._getDefaultValueInternal()``` to either call or do the same thing as ```makeConfig()```?

If this throws an exception (it should) cause the repo to fail to load in this case I would imagine (unless there is some catch-all exception).
This would mean that the repo potentially needs to be re-factored.

**Comment by rob-c** [comment]
@milliams Is there any conclusion to draw from this because I suspect it effects #129.

Is manually adding a makeConfig advisable as we don't make use of this function anywhere else with regards to the config parameters ```defaults_xxx```?

Although adding it to the schema makes this go away it doesn't fix it and I'd rather not set a precedent.

Or, is this likely a bug in the loading of the Config or the repository(ies)?

**Comment by milliams** [comment]
@rob-c I don't think we should manually add a `makeConfig()` as that is just going to hide the problem. I will have a look to see if I can reproduce this bug. Is there an easy way to make it show up as I haven't seen it myself?

**Comment by rob-c** [comment]
```SetupProject ganga; ganga``` seems to be enough to trigger it every single time. I'll have a go at wiping my repo later and see if it's a corruption problem of some sort although I doubt it.

Maybe if you're able to load GangaLHCb alongside the Core then it might be enough to trigger this problem.

**Comment by rob-c** [comment]
I'm happy to say aside from some minor changes within functions I've no idea how the Config system is actually coded and it intimidates me enough to stay away from it.

**Comment by milliams** [comment]
In general I'm happy to take this bug as I've looked into the config system a bit in the past. However, I'm completely unable to reproduce the bug. Logging into a fresh LHCb terminal on lxplus and doing:
```bash
SetupProject Ganga
rm -rf ~/gangadir ~/.ganga*
ganga
```
I get
```
*** Welcome to Ganga ***
Version: 6.1.14
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


Ganga.Utility.Config               : INFO     reading config file /cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r14/install/ganga/python/GangaLHCb/LHCb.ini
Would you like to create default config file ~/.gangarc with standard settings ([y]/n) ?
y
Ganga.Runtime.bootstrap            : INFO     Creating ganga config file /afs/cern.ch/user/m/mwilliam/.gangarc
Press <Enter> to continue.


[20:39:50]
Ganga In [1]:
```
and even running it a second time I still get no error. The other difference I see is that you have `/afs/cern.ch/sw/ganga/install/config/LHCb/6-1-11/CERN.ini` in your list of sourced config files. Where is that coming from?

**Comment by egede** [comment]
@milliams the .ini file at the end is normal. It sets a few CERN specific options for the config system. The latest version below is picked for this (to avoid that we have to update it for every release).

**Comment by rob-c** [comment]
@milliams Apologies I forgot to mention you need to be doing this with the latest code from develop. If you use 6.1.14 I could not reproduce this on AFS

**Comment by milliams** [comment]
I'm now seeing this on my local checkout of Ganga so I'll start looking into it.
