### ISSUE TITLE
py.templates not installed

### ISSUE THREAD

**Issue by schmitts** [ganga-devs/ganga#920]
Release 6.3.1 installed via pip.

```
j = Job()
j.submit()
```

fails with

```
INFO     submitting job 2 to Local backend
ERROR    GangaException:  ('Error Finding script file: somewhere/.local/lib/python2.7/site-packages/Ganga/Lib/Localhost/LocalHostExec.py.template',)
ERROR    JobManagerError: error during submit
```

There are no `py.template` files installed at all.

**Comment by egede** [comment]
I confirm this problem. It must be realted to how the distribvution is packed up for pip.

**Comment by egede** [comment]
The configuration of the upload to PyPi is done on the Jenkins service. I do not know how it is configured though. As a stop-gap, the file can simply be downloaded from the web interface https://github.com/ganga-devs/ganga/tree/develop/python/Ganga/Lib/Localhost and dropped in place.

**Comment by schmitts** [comment]
For 6.2.3 it works. I haven't tested releases in between.

**Comment by mesmith75** [comment]
I'm not sure the templates were ever there.

As the penultimate step in the release before the upload to PyPi we make the distribution with 
```python
python setup.py sdist
```
For the default this only takes the python source, so the file ending .template is being ignored (see here for the defaults: https://docs.python.org/2/distutils/sourcedist.html).

We can try generating a list of files to be included (probably anything in the workspace directory), or just rename the file.

**Comment by egede** [comment]
@mesmith75 The change is that the `.template` files were introduced. Before they were just called `.py` but it caused trouble with code checking tools (as the files are not valid Python before the substitutions has been made). https://wiki.python.org/moin/Distutils/Tutorial seems to have a nice tutorial on how to write the MANIFEST.in file.

**Comment by mesmith75** [comment]
ah ok - I'll add in a manifest file with a recursive include under the current directory.

**Comment by mesmith75** [comment]
The templates will be in the distribution of the next release.
