### ISSUE TITLE
Change *.root file default from LCGSEFile to LocalFile

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#921]
Probably more likely people are using `LocalFile`s than `LCGSEFile`s these days.

Thanks,

Mark

**Comment by JacekHoleczek** [comment]
Please make Ganga COMPLETELY unbiased / impartial / neutral what concerns ANY file types.
Without EXPLICIT entries in user's own ".gangarc", NO hidden assumptions should be effective.

**Comment by rob-c** [comment]
@JacekHoleczek Changing this breaks a _lot_ of higher level features for a _large_ number of existing users.
I think that the `LCGSEFile` is maybe overstepping what is 'sensible' for a default configuration but there are good reasons for having this default behaviour such as handling of sandboxes and storage limitations for many users.
