### ISSUE TITLE
Change of behaviour for Dirac.getOutputDataLFNS?

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#930]
From 
https://twiki.cern.ch/twiki/bin/view/LHCb/FAQ/GangaLHCbFAQ#How_do_I_use_the_outputdata_from

It seems that this used to work:
```
ds = LHCbDataset()
for sj in j.subjobs.select(status="completed"): 
     ds.extend(sj.backend.getOutputDataLFNs())
new_job.inputdata = ds
```

but now doesn't as `getOutputDataLFNs` just returns a string rather than (at least) 'LFN:'+string and therefore the default for constructing a `DiracFile` doesn't set the LFN properly/at all. I'm not sure if this is a change in API or a bug but it should be easy to fix (one way or another) if it's the latter!

**Comment by rob-c** [comment]
I think this is a bug looking at: https://github.com/ganga-devs/ganga/blob/develop/python/GangaLHCb/Lib/Backends/Dirac.py#L58
This should work for LHCb users but for vanilla dirac users I expect them to see problems.
If this is an LHCb user why aren't they seeing the overloaded method?

If the above code is broken then surely there's a bug in the dataset expanding from another dataset?

**Comment by mesmith75** [comment]
The LHCbDirac plugin isn't loading properly. I think something may be happening in the wrong order.
