### ISSUE TITLE
Take username for Dirac LFNs from Proxy rather than local username

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#931]
If users don't specify `DiracLFNBase` specifically then it is taken from the local username. However, this is unlikely to be the same username specified in the Voms Proxy attributes and what should be used through Dirac. It should be fairly easy to use this instead.

(Note that this **may** just be an LHCb problem - not sure!)

**Comment by mesmith75** [comment]
Yes this is a good idea to implement.
