### ISSUE TITLE
Nasty traceback in GaudiExec submission if no gridProxy is valid

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#933]
If you create a job with a GaudiExec application and a Dirac backend, but do not have a valid gridProxy, the submission results in the traceback below. It can be seen that getting a proxy then allows the submission to happen. Some extra error checking should be implemented to give a nice error instead.

```
[11:44:16]
Ganga In [23]: j.submit()
INFO     submitting job 20
INFO     job 20 status changed to "submitting"
INFO     Job 20's application has already been prepared.
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v603r1/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py", line 1498, in submit
WARNING      jobmasterconfig = self._getJobMasterConfig()
WARNING    File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v603r1/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py", line 1196, in _getJobMasterConfig
WARNING      jobmasterconfig = rtHandler.master_prepare(self.application, appmasterconfig)
WARNING    File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v603r1/install/ganga/python/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py", line 377, in master_prepare
WARNING      generateDiracInput(app)
WARNING    File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v603r1/install/ganga/python/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py", line 255, in generateDiracInput
WARNING      new_df = uploadLocalFile(job, os.path.basename(compressed_file), tmp_dir)
WARNING    File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v603r1/install/ganga/python/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py", line 349, in uploadLocalFile
WARNING      return returnable
WARNING  UnboundLocalError: local variable 'returnable' referenced before assignment
WARNING  --------------------------------------------------
ERROR    local variable 'returnable' referenced before assignment ... reverting job 20 to the new status
INFO     job 20 status changed to "new"
ERROR    Error: JobError: Error: local variable 'returnable' referenced before assignment

[11:44:30]
Ganga In [24]: gridProxy.create()
Generating proxy...
Enter Certificate password:
Added VOMS attribute /lhcb/Role=user
Uploading proxy for lhcb_user...
Uploading proxy for private_pilot...
Proxy generated:
subject      : /C=UK/O=eScience/OU=Imperial/L=Physics/CN=ulrik egede/CN=proxy/CN=proxy
issuer       : /C=UK/O=eScience/OU=Imperial/L=Physics/CN=ulrik egede/CN=proxy
identity     : /C=UK/O=eScience/OU=Imperial/L=Physics/CN=ulrik egede
timeleft     : 23:53:59
DIRAC group  : lhcb_user
rfc          : False
path         : /tmp/x509up_u12230
username     : uegede
properties   : NormalUser
VOMS         : True
VOMS fqan    : ['/lhcb/Role=user']

Proxies uploaded:
 DN                                                    | Group         | Until (GMT)
 /C=UK/O=eScience/OU=Imperial/L=Physics/CN=ulrik egede | lhcb_user     | 2017/10/30 11:52
 /C=UK/O=eScience/OU=Imperial/L=Physics/CN=ulrik egede | private_pilot | 2017/10/30 11:52

[11:44:49]
Ganga In [25]: j.submit()
INFO     submitting job 20
INFO     job 20 status changed to "submitting"

**Comment by rob-c** [comment]
Ah, I think this just requires that the `returnable` be defined to be None in the case that it isn't constructed in the method.

NB: I'm also seeing exceptions showing full traces from GangaException type errors from background threads.
@alexanderrichards is there any way to handle the exceptions from worker threads in ganga?

**Comment by alexanderrichards** [comment]
are we talking about worker threads from the queues system or GangaThreads?

**Comment by alexanderrichards** [comment]
worker threads from the queues system were build to be robust against user code raising exceptions. I'll have a look. As I recall they simply log the exception traceback and carry on with the next task. It should therefore be impossible to kill them accidentally  by executing rogue user code. If your asking about how you can silence the logging of this traceback then you should be able to just pick out the correct logger and turn it off.

If your asking about GangaThreads then I'll have to check.

**Comment by rob-c** [comment]
@alexanderrichards This because I was sat at a users terminal and the monitoring spammed me with tracebacks of errors due to the DIRAC job failing in a bad way. I don't know why sometimes this happens but I am wondering if we can either buffer errors/warnings on threads or do something to stop them flooding the user if possible.

Also GangaException type exceptions (aka the ones we intend to throw) shouldn't cause a trace as in:
https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py#L140
and https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py#L126
I think we need to add a check here to look for the exception type which is the same as the exception handling for IPython so that users just see a friendly exception of `No output for job` rather than what they get atm.

**Comment by alexanderrichards** [comment]
> GangaException type exceptions (aka the ones we intend to throw) shouldn't cause a trace

The alternative is to swallow them. I'm confused as you say these are the ones we **intend** to throw. Remember we cannot re-raise them as that would kill the thread.

**Comment by rob-c** [comment]
yes but these are exceptions from the backend which can not be resolved so should just throw, send a message and abort

**Comment by alexanderrichards** [comment]
we cant just throw them and abort as this would kill the worker thread for future use. We can either display them or swallow them.

**Comment by rob-c** [comment]
swallowing them at the queue manager level should be fine if they're of the type we have explicitly thrown ourselves as these would go to the user as an error message not a trace. we want the same behaviour from the worker thread, warn the user in a polite way and move on to the next queued item for running

**Comment by alexanderrichards** [comment]
Thats fine we can issue a more friendly logger message instead of the traceback. Then we need to consider what should said message be? by their nature the threads could be doing anything the user wants so it would have to be a generic message alone the lines of:

```python
"Thread <num> experienced an error running function <name>"
```

In which case it could be argued that this message is of limited use?

**Comment by rob-c** [comment]
If it was thrown by Ganga on purpose then the string rep of the exception should be good enough to be useful. We can consider adding the word monitoring I front of it but there's no need to tell the user this happened on a thread imo. If there is a catastrophic exception not of type GangsException then defaulting to the trace and telling the user we don't know better is all that can be done imo

**Comment by mesmith75** [comment]
Has this already been fixed - I cannot reproduce it.

**Comment by egede** [comment]
@mesmith75 Not quite sure why you do not see an error. In any case, from looking at the code, it is obvious that ```returnable``` is not defined in
https://github.com/ganga-devs/ganga/blob/develop/python/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py#L349 if either there are no SEs found or if they are not writable. If the gridProxy is there or not seems a red herring.
