### ISSUE TITLE
Move LHCb.ini into GangaLHCb

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#935]
Pursuant to my email, do we think it would be a good idea to move the GangaLHCb,ini into the GangaLHCb folder, rather than have it completely separate?

This would be useful for future releases.

**Comment by alexanderrichards** [comment]
there already is an LHCb.ini in the GangaLHCb folder, see:
[LHCb.ini](https://github.com/ganga-devs/ganga/tree/develop/python/GangaLHCb)

Do you mean the CERN site config? what is this LHCb.ini that your talking about? (I'll read the email first ;-))

**Comment by mesmith75** [comment]
oops..
