### ISSUE TITLE
GenericSplitter can't use gangafiles as values (ganga fails to parse value in XML)

### ISSUE THREAD

**Issue by apingault** [ganga-devs/ganga#940]
Hi,
When trying to use the generic splitter with either the `inputdata` or `inputfiles` attribute with `gangafiles`, ganga has trouble reading the xml file generated.

Here is a MWE to reproduce the problem:
``` python
  j=Job()
  s = GenericSplitter() 
  s.attribute='inputfiles'
  s.values=[[LocalFile('./toto.txt')]]
  j.splitter=s
  j.submit()
```
And the failing message when I restart a ganga session:
```bash
ERROR    XML from-file error for file:
GangaException:  ("ERROR in loading XML, failed to correctly parse attribute value: '<LocalFile(namePattern='toto.txt', localDir='/eos/user/a/apingaul/testJob') PROXY at 0x14ce3d0>'",)
```
Here is the XML section in question:
```XML
    <attribute name="splitter">
          <class name="GenericSplitter" version="1.0" category="splitters">
             <attribute name="attribute">
                 <value>'inputfiles'</value>
             </attribute>
             <attribute name="values">
                <sequence>
                   <sequence>

                       <value>&lt;LocalFile(namePattern='toto.txt', localDir='/eos/user/a/apingaul/testJob') PROXY at 0x14ce3d0&gt;</value>
                   </sequence>
                </sequence>
             </attribute>
```
I can see the subjobs are all correctly submitted and their exe can run and complete....though status is stuck at submitted. I can also see that only the first file is uploaded. (when s.values has mulitple LocalFile)

**Comment by rob-c** [comment]
This could probably be mitigated by #701 (or a simple extension thereof) which seems like a pragmatic approach to fixing the problem.
Ultimately Ganga has for a long time been braking the promises of the Schema when it comes to simple items and there is no trivial way of fixing this without breaking backwards compatibility in a significant way for many users. #701 is a pragmatic fix which stops users being exposed to these sort of problems however so I'd strongly re-consider merging it.

**Comment by mreboud** [comment]
I have the same issue when submitting DiracFiles instead of LocalFiles, though all the file are uploaded. The subjobs run and complete and all is well until I restart a Ganga session. Then the job is treated as corrupted ('IncompleteObject ()').

**Comment by egede** [comment]
@mreboud Are you using the latest Ganga release? A fix to this problem went into the 6.5.0 release on March 4. However, please use the latest 6.5.1 release. If operating inside an LHCb environment, you simply type `ganga` after login. No need for `SetupProject` or `lb-run`.

**Comment by mreboud** [comment]
@egede Yes, I am using the 6.5.1 release.

**Comment by mreboud** [comment]
Here is my error:
```
ERROR    XML from-file error for file:
GangaException: ERROR in loading XML, failed to correctly parse attribute value: '<DiracFile(namePattern='Ntuple_Inclb_Up.root', lfn='/lhcb/user/m/mreboud/2017_04/161047/161047358/Ntuple_Inclb_Up.root', localDir='') PROXY at 0x7fb4790aabd0>'
```
I am working on a MWE...

**Comment by rob-c** [comment]
@mreboud Did you manage to reproduce this if the job was created in 6.5? There will likely be information loss if not. (The sight of a proxy at the XML layer is extremely concerning that something is broken, however it could simply be that the string is parsed into a proxied object which we're not stripping properly.
Could you attach the broken XML file?

**Comment by mreboud** [comment]
Ok, here we are (on Ganga 6.5.1):
```python
j = Job(backend=Dirac())
s = GenericSplitter()
s.attribute = 'inputfiles'
s.values = [[DiracFile(lfn = '/lhcb/user/m/mreboud/2017_04/161047/161047358/Ntuple_Inclb_Up.root')]]
j.splitter = s
j.submit()
```
When I restart Ganga I have a lot of ERRORs. The interesting part of the XML file is:
```
    <attribute name="splitter">
          <class name="GenericSplitter" version="1.0" category="splitters">
             <attribute name="attribute"> 
                 <value>'inputfiles'</value>
             </attribute>
             <attribute name="values"> 
                <sequence>
                   <sequence>

                       <value>&lt;DiracFile(namePattern='Ntuple_Inclb_Up.root', lfn='/lhcb/user/m/mreboud/2017_04/161047/161047358/Ntuple_Inclb_Up.root', localDir='None') PROXY at 0x7f74cdb79210&gt;</value>
                   </sequence>
                </sequence>
             </attribute>
             <attribute name="multi_attrs"> 
                 <value>{}</value>
             </attribute>
          </class>
    </attribute>

```

**Comment by rob-c** [comment]
@mreboud You've stumbled upon a problem in the proxy I fear. I'm very concerned by the sight of a proxy string in the XML.
This probably explains why the XML parser fails to identify the object as inheriting from GangaObject and correctly parses it into complete XML.
I suspect there is something broken in `GangaList` which is failing to descend into iterable objects and correctly strip the proxy on assignment.
An easy workaround for this is to add a few lines to `VStreamer` to identify proxied objects and strip them before passing it to the code which generates the XML for objects being written to disk.
I suspect that you would have a few problems if the proxy isn't stripped for member objects within lists of lists.

**Comment by egede** [comment]
@rob-c Will you look at this or do you expect somebody else to pick it up?

**Comment by rob-c** [comment]
@egede I could provide a short workaround for `VStreamer` but unfortunately I've not got the time at the moment to go looking through the `GangaList` tests to find how a proxied object has been incorrectly assigned.
(It may have to wait a day or 2 until I've finished some other work)

**Comment by mreboud** [comment]
@rob-c I am not sure I understand your workaround (I know nothing about VStreamer), but as long as Ganga remains opened, the jobs are doing well, so I can work.

**Comment by rob-c** [comment]
@mreboud Apologies, the workaround involves a bit of an intrusive hack at the Ganga code which can't be done at runtime. If this isn't too urgent I will see if I can get to this over the weekend.

**Comment by mreboud** [comment]
@rob-c No problem, I can wait. Thanks.

**Comment by mesmith75** [comment]
I think this has been fixed somewhere along the way so I'll close this.
