### ISSUE TITLE
Document how /cvmfs releases are updated

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#942]

**Comment by mesmith75** [comment]
Can we also add in a DEV folder that pulls from the develop branch, say once per day.

**Comment by drmarkwslater** [comment]
So I've done a version of this that should cover the basics and added it to the Twiki:

https://github.com/ganga-devs/ganga/wiki/Release-process

I'll now look into adding the Dev version, removing ancient releases and installing from github.

**Comment by mesmith75** [comment]
Done.
