### ISSUE TITLE
Bug in generated exe-script.py file

### ISSUE THREAD

**Issue by olupton** [ganga-devs/ganga#946]
I am submitting jobs using the `Executable()` application and the `Dirac()` backend.
For some (unknown) reason these are failing at one grid site.
Ganga is not reporting whatever the real error is, because there is a bug in the script ganga generates:
https://github.com/ganga-devs/ganga/blob/master/python/GangaDirac/Lib/RTHandlers/ExeDiracRTHandler.py#L163

This means the reported error is simply
```
> Traceback (most recent call last):
>   File "/scratch/plt/153162074/exe-script.py", line 28, in <module>
>     print('Exception occured in running process: ' + exe_cmd)
> TypeError: cannot concatenate 'str' and 'list' objects
```

**Comment by mesmith75** [comment]
Thanks, that is indeed not very good.
