### ISSUE TITLE
strange logging behaviour

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#95]
Hi all,

I'm putting a task here before I forget to bring it up yet again.

There are parts of the codebase where using the info logging function doesn't display as I would naively expect it to.
(Obviously this is working in some 95%+ of the time and it's only in some places it fails)

This isn't a case of the message is being held and not flushed until some event like a carriage return and I can confirm that the code is executed by placing a print statement either before or after the logging. (The print statements work as expected despite the fact that logger.info doesn't)

I don't know what could be leading to these messages being lost (and I haven't yet tracked down whether the information is perhaps written to the logfile but not stdout.

I'll update this with an example in the near future.

Without some real digging into the logging code I don't know what could be going on and I think some others have looked at this recently so I don't know if anyone else suspects where there could be problems with the logger?

Thanks,

Rob

**Comment by milliams** [comment]
I haven't seen this myself. Without a (mostly) reproducible test case it is hard to say.

**Comment by rob-c** [comment]
Next time I come across a function where I observe this I'll update, I'll give it until the end of the week and will mark it as can't reproduce if I have stopped seeing it. Some recent changes have made this go away

**Comment by rob-c** [comment]
OK, can't seem to reproduce this anymore. Marking as closed
