### ISSUE TITLE
GaudiExec clean up

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#957]
Reminder to look into having GaudiExec remove its files of the grid if the job is removed.
Also, consider replicating the tarball once to reduce possible failures - may need a postprocessor for cleanup.

**Comment by egede** [comment]
There is some work do be done with testing the reliability of the local shared area cleanup to be done before this issue can be addressed.

**Comment by rob-c** [comment]
I think you would just need to add a cleanup hook for application objects which is called upon job removal. Some of the information uploaded to the grid is specific to each job and some (I think) is potentially common to multiple jobs. I had something like this sort of working a while ago but never committed it. I'll try and dig it out after looking at #917

**Comment by egede** [comment]
@rob-c The situation is exactly that it is shared between jobs. This complicates matters somewhat.

**Comment by rob-c** [comment]
The easiest way I looked into having objects shared between jobs just required expanding or using the API in the `SharedDir` to store a list of `IGangaFile` objects and allowing it to call `IGangaFile.remove` when it's cleaning up after itself.
In my implementation I just told `GaudiExec` to place new objects in an attibute for the SharedDir as well as in the (hidden) attribute where it already knows about them in the application.
The idea was that after a few releases the hidden attribute could be correctly dropped and users would be none the wiser as well as users moving forward being able to clean-up after existing jobs. (Old versions of ganga still loading the jobs but not cleaning up when removing them).

I held off on touching SharedDir as at the time there was a lot of work being done to fix the index counting and a few other minor bugs. It may be formally better to have some new SharedObjects class for sharing files between jobs but I'm not sure how much work this would be and would be backwards incompatible.
We should still look into making a cleanup hook for Applications/backends and other objects to be called by the remove method in the job class.
(or generically a method for all GangaObject type classes which would be called when objects are removed from a database which would be the ideal solution imo.)
