### ISSUE TITLE
missing template

### ISSUE THREAD

**Issue by baoboa** [ganga-devs/ganga#961]
Maybe i did miss something but following the install instruction for pip
```python
virtualenv ~/gangaenv
source ~/gangaenv/activate
pip install ganga
```
installation are missing  lib/python2.7/site-packages/Ganga/Lib/Localhost/LocalHostExec.py.template

so the exemple provided
```python
j=Job()
j.submit()
```
fail

    ERROR    GangaException: Error Finding script file: /home/userXXX/SOFTWARE/gangaenv/lib/python2.7/site-packages/Ganga/Lib/Localhost/LocalHostExec.py.template
    ERROR    JobManagerError: error during submit

**Comment by egede** [comment]
@baobao I thought this was fixed by the addition of the *.py.template wildcard in 

https://github.com/ganga-devs/ganga/blob/develop/MANIFEST.in

Are you somehow trying to install an old Ganga release rather than the latest one?

**Comment by baoboa** [comment]
i set up a new virtualenv and i removed ~/.gangarc ~/gangadir

```
Successfully installed ganga-6.4.0 google-api-python-client-1.6.2 httplib2-0.10.3 ipython-1.2.1 oauth2client-4.0.0 pyasn1-0.2.3 pyasn1-modules-0.0.8 python-gflags-3.1.1 rsa-3.4.2 stomp.py-4.1.17 uritemplate-3.0.0
```

from that i got same error , is ganga-6.4.0 not the last version ?

**Comment by egede** [comment]
@baobao Yes, it is indeed. So obviously we have somehow not solved the problem.

**Comment by egede** [comment]
OK, I reproduce problem. There is a bit of an issue here in that we do not use pip for our own testing.

The real problem is that we use `setuptools` to make our pip distribution but the `MANIFEST.in` file is used by `distutils`. Should be fairly easy to fix.

**Comment by baoboa** [comment]
@egede

is it pip specific ?
```bash
    wget https://github.com/ganga-devs/ganga/archive/develop.zip
    unzip develop.zip
    cd ganga-develop/
    python setup.py install
    ls lib/python2.7/site-packages/ganga-6.4.0-py2.7.egg/Ganga/Lib/Localhost/
```
```
    __init__.py  __init__.pyc  Localhost.py  Localhost.pyc
```
i didn't got template either

**Comment by rob-c** [comment]
@baoboa Is there a reason not to use `git clone`?

**Comment by egede** [comment]
It is a problem with the setup.py script. So after I merge the pull request, the wget method should work.

**Comment by egede** [comment]
@baoboa OK, I merged now. So please try the `wget` method again. The `pip` install should be working correctly after the next release is made. Report back if you see any problem.

**Comment by egede** [comment]
Fixed by #962

**Comment by baoboa** [comment]
ok
 
    pip install  https://github.com/ganga-devs/ganga/archive/develop.zip

it works 

now should the readme.rst be modified (temporally)?

**Comment by egede** [comment]
@baoboa Thanks. Next release should be out within a few days, so we will let the problem fix itself.
