### ISSUE TITLE
Change the default BkQuery dqflag to be ['OK',UNCHECKED']

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#963]

**Comment by mesmith75** [comment]
Why do we want this? As a casual user would one not expect the files returned to only be checked ones?

**Comment by egede** [comment]
If I understand it correctly, the label UNCHECKED can persist in principle forever, and it is the BAD data that you do not want. I was explicitly asked to make this change, but will ask on the mailing list to ensure that there is a general agreement.

**Comment by egede** [comment]
Agreed that this change should *not* be made. Would be good to keep new test cases though.
