### ISSUE TITLE
Create Jenkins slot for testing against LHCb Dirac certification server

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#964]
This should not run automatically but should be able to be started on demand. Permission should be given to @fstagni.

**Comment by egede** [comment]
This is now done. See https://ganga-ci.cern.ch/jenkins/view/Testing/job/LHCb%20-%20Dirac%20certification/

@fstagni Can you see if the permissions have been set up correctly for you to make a `build`. The tests using the certification server are all failing right now, but I think that reflects a problem with the certification server rather than a problem with the tests. Feedback welcome.

**Comment by fstagni** [comment]
I confirm I could start the build, and I see that some of the tests are failing. Which of the tests in https://ganga-ci.cern.ch/jenkins/view/Testing/ is the "same" as the above but targeting the production setup?

**Comment by rob-c** [comment]
I'm assuming this is due to:
```
#x1B[0;33mWARNING  Required credential [DiracProxy(group='lhcb_user')] not found in store#x1B[0;0m
Generating proxy...
Can't find user certificate and key
```
@egede is it understood why there is a grid-proxy-destroy at the start of this test?
Would it be better that if a test makes a proxy it should clean up after itself?
(I'll admit I never understood how this was setup despite looking into it)

**Comment by egede** [comment]
I reran the tests with the change mentioned below, but unfortunately it still fails.
 - https://ganga-ci.cern.ch/jenkins/job/LHCb%20-%20Dirac%20certification/lastBuild/testReport/python.GangaLHCb.test.GPI.TestDatasets/TestDatasets/testDatasets/ fails as the LFN it looks for replicas for is not registered in the bookkeeping that it queries.
 - https://ganga-ci.cern.ch/jenkins/job/LHCb%20-%20Dirac%20certification/lastBuild/testReport/python.GangaLHCb.test.GPI.TestDataFiles/TestDataFiles/testDataFilesExternal/ fails for the same reason
 - https://ganga-ci.cern.ch/jenkins/job/LHCb%20-%20Dirac%20certification/lastBuild/testReport/python.GangaLHCb.test.Unit.DiracAPI.TestDiracCommands/ fails as the setup requires a job to submit and complete. In the monitoring, I see that the job is just in `waiting`.




@fstagni The test to compare them to is `LHCb Nightly` https://ganga-ci.cern.ch/jenkins/job/Nightly%20-%20LHCb/

@rob-c I just fixed a problem with how to get a proxy (related to that I create a fake `$HOME` where the `.dirac.cfg` file is stored).

**Comment by fstagni** [comment]
Just a clarification: the content of the DFC (replica catalog) and the Bookkeeping in the "LHCb-Certification" setup are not the same as those in the "LHCb-Production" setup. Mostly, their content is "similar" (about 2 years ago they have been populated with what was the content of their production counterparts), but recent files are not present - and from that moment only what was produced in certification is present. So this a likely explanation for the failures in first 2 tests that you report.

For the job failing test: I see only one job, ID 1317305. It is in status failed while uploading the job outputs. The reason is unclear (I have problems finding the log)

**Comment by egede** [comment]
If you look at the pilot stdout of 1317332 you see a long set of errors. If I run the job on the production server these errors are not present. 

The test is requesting that the output is uploaded to a set of SE's located in the UK. My guess is that proxy used by the pilots on the certification server are not allowed to upload to those SEs.

**Comment by mesmith75** [comment]
Can we close this?

**Comment by fstagni** [comment]
Well, technically the task "create the Jenkins slot" is done, but the tests themselves are not fully correct for this setup

**Comment by egede** [comment]
@fstagni To get this working we need some information from your side.

- Why can't we write to the UK SEs?
- Is there a "safe" datafile LFN that we know can be accessed in the long term on both production and certification server?

**Comment by fstagni** [comment]
- From what I see from the pilot log, the "gangage" could not write anywhere, not only only UK SEs. Does the proxy has a VOMS extension? To debug, can you try a simple `dirac-dms-add-file` from lxplus (targeting the certification setup?) 
- Do you need only just one LFN? Does it need to be a DST or any other format? Can you point me to what is actually used in the tests today? (point me to the test code here in github, please)

**Comment by egede** [comment]
When contacting the production server I see

```
[egede@lx01] ~ % lb-run LHCbDIRAC/prod bash --norc
[LHCbDirac prod] [egede@lx01] ~ % dirac-dms-list-directory /lhcb/user/g/gangage
/lhcb/user/g/gangage/: 0 files, 39 sub-directories
```

but when I contact the certification server I see

```
[LHCbDirac prod] ~ $ dirac-dms-list-directory /lhcb/user/g/gangage
Error retrieving directory contents - Directory does not exist:  /lhcb/user/g/gangage/
```

If you fix that, I will try again.

**Comment by egede** [comment]
As to the tests, the majority of them are https://github.com/ganga-devs/ganga/blob/develop/python/GangaLHCb/test/Unit/DiracAPI/TestDiracCommands.py . They all fail as they depend on an initial job created in the `dirac_job` function.

**Comment by fstagni** [comment]
It should be OK now:
```
[LHCbDirac prod] ~ $ dirac-dms-list-directory /lhcb/user/g/gangage
/lhcb/user/g/gangage/: 0 files, 0 sub-directories
```
