### ISSUE TITLE
Change default LHCbDirac version to `prod`

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#965]
Care should be taken in dereferencing what `prod` means to keep the cached environment correct.

**Comment by rob-c** [comment]
Is `prod` LHCbDirac shipped on cvmfs? I get problems with finding the `prod` version of some projects on there.

**Comment by mesmith75** [comment]
Yes it is - `lb-run LHCbDirac prod` points to /cvmfs/lhcb.cern.ch/lib/lhcb/LHCBDIRAC/LHCBDIRAC_prod

Do we want to always have the latest version?

**Comment by egede** [comment]
The `prod` version is a decision made by the `LHCbDIRAC` team and is not always the latest version. Another option would be to have something like `v8r*`.

@fstagni Can you comment.

**Comment by fstagni** [comment]
There is also `LHCbDIRAC/latest` version, which is not necessarily the same as `LHCbDIRAC/prod` version, even if for the most part they should be. What we try to assure is that `prod` is stable, or at least the client version found in `prod` should be stable enough for ganga use.

**Comment by egede** [comment]
@fstagni We decided indeed to go with the `prod` version. This will be the default from version 6.5.1 of Ganga.

**Comment by egede** [comment]
Closed by #971
