### ISSUE TITLE
Eliminate the ability of users to ban DIRAC sites

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#966]
Consider if this should be done. Consultation required??

**Comment by mesmith75** [comment]
@egede I can see the rationale but I think it is something we need to keep. For example when I was messing around with trying to run stuff on the nightlies I had to ban sites to get them to run.

**Comment by egede** [comment]
@mesmith75 The ability will still be there as we can inject commands directly to the Dirac script that is executed. It will just be more hidden.
