### ISSUE TITLE
Implement a way to automate the download/merging of Remote files

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#97]
I'm not certain, but I believe you still can't automatically download and merge anything other than LocalFiles - I think this might even be broken in Tasks. If this is not possible, we should make it possible :)

**Comment by rob-c** [comment]
I thought we had decided that if the file wasn't stored locally then we would explicitly not allow for them to be merged?
If the files are large we run the risk of overwhelming local storage if we download everything don't we?

**Comment by drmarkwslater** [comment]
To be honest I can't remember. I think I would personally lean towards it being worth implementing as generally the user would want to do this straight away anyway if the job has succeeded. However, maybe it would be better just having this in Tasks rather than normal jobs? I don't know - what do others think?

**Comment by egede** [comment]
What the user often want (without thinking about the consequences) is that they want all the intermediate files as Grid files and they want the merged output as a grid file as well. To do this on the client I think is a recipe for disaster. To do it as a separate Grid job, which can then be included in a Task seems on the other hand quite sensible. So implementing a Merger application might be a better idea.

**Comment by rob-c** [comment]
How about MassStorageFiles?
Is it possible to use streaming commands to create a new file on MassStorage 'on the fly' or would there need to be some mechanism for allowing for file transfers and merging.
Or, should we expect that some file types allow or automated merging of data but not all?

**Comment by egede** [comment]
@rob-c While it would be possible to merge Root files by streaming them from places like EOS or a Storage Element, it would only work in certain combinations and I think it would be fragile. And again it would potentially stream multiple GB of data through the client which is probably not ideal.

**Comment by rob-c** [comment]
Good points.
I think merging grid files on the grid for instance would be a nice thing to have, but how many of the different GangaFiles we can sensibly support merging the output for?
I suspect in reality it's just LocalFile and maybe DiracFile?

**Comment by egede** [comment]
@rob-c We could in priciple support many more, but the problem is that they would lead to contorted dataflows. We already see that with LHCb people running Dirac jobs that have MassStorageFile as the output. These jobs upload the data to EOS and then move it to a different location in EOS by copying it to the client first and then uploading it again. Merger jobs would suffer from similar issues. The **templates** that we have put in the framework for but in reality never developed would be a nice way to demonstrate jobs that could do some of these operations (like merging DiracFiles).

**Comment by rob-c** [comment]
If we want to make some jobs that merge files then this may be a nice 'template' job to provide to users somehow, but I don't think any direct development in Core is required.
Maybe making a few template jobs in a 'sticky' template repository which can be used by Tasks or other users would be useful?

**Comment by drmarkwslater** [comment]
I think the points raised here are valid - we won't have an 'easy' option of download/merge in normal jobs but we should look in to providing a job template to create a job that does it and I'll go down this route for Tasks as well.
