### ISSUE TITLE
Old DaVinci application not working locally

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#973]
The old DaVinci application on Local or Interactive backends is trying to use an environment variable that is being set by LbScripts: `DaVinci_release_area`. I think all the old Gaudi programs will have this problem - I assume this is due to the changes in the more recent Lbscripts that we fixed for the Dirac backend.

I don't know if we want to fix this. It is pretty trivial.

**Comment by egede** [comment]
@mesmith75 Yes, trivial fixes are fine.
