### ISSUE TITLE
Provide instructions for running tests

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#978]
@VanyaBelyaev has asked for instructions on how to get the testing framework up and running. To set it up from scratch seems actually to be far from trivial. On lxplus7, I went through the steps below. If somebody can make it shorter I would be pleased.

```
# Upgrade virtualenv as the default version provides too old a
# version of setuptools
pip install --upgrade --user virtualenv

# Subsequent virtualenv command fails without this.
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/afs/cern.ch/sw/lcg/releases/LCG_87/Python/2.7.10/x86_64-centos7-gcc62-opt/lib

# Create a virtualenv for the testing
python ./.local/lib/python2.7/site-packages/virtualenv.py testGanga

# Go into the virtualenv for the testing
cd testGanga
bash --norc
source bin/activate

# Clone the Ganga repository
git clone https://github.com/ganga-devs/ganga.git

# Install Ganga dependencies, including those for the testing.
cd ganga
pip install --upgrade -r requirements.txt

# Get ready for the testing.
cd python
export PYTHONPATH=$PYTHONPATH:`pwd`

# Run a test
py.test Ganga/test/Unit/Notebook
```

and then for subsequent logins (where the installation is already there)

```
# Subsequent virtualenv command fails without this.
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/afs/cern.ch/sw/lcg/releases/LCG_87/Python/2.7.10/x86_64-centos7-gcc62-opt/lib

# Go into the virtualenv for the testing
cd testGanga
bash --norc
source bin/activate

# Get ready for the testing.
cd ganga/python
export PYTHONPATH=$PYTHONPATH:`pwd`

# Run a test
py.test Ganga/test/Unit/Notebook
```

**Comment by rob-c** [comment]
@egede I don't think you can reduce this any further .This is the expense of our externals for testing not all being in the lhcb python install. It's possible to do this without the virtualenv but you are required to track the installed packages yourself in your user area so I'd recommend this way to people moving forward.

This is not really different to installing any other python package although the `PYTHONPATH` step should probably be taken care of in the py.test configuration step imo.

**Comment by egede** [comment]
@rob-c The first step (updating `virtualenv` itself) is really painful. And that is even on `centos7`. But as you say it seems the only way. I guess we can make a little script that takes care of the steps.

@VanyaBelyaev Can you give the aobve a go and see if it works for you.

**Comment by rob-c** [comment]
@egede you can just install ganga yourself with `pip --install --user` if you want even on lxplus but this will give the unexpected result of hard-coding the ganga path into the test-suite at some level.
You shouldn't need to update it, I think it's just virtualenv being fussy for no good reason, or does this introduce problems?

**Comment by VanyaBelyaev** [comment]
@egede  Hi Ulrik, thank you very much for instructions. The procedure is not very obvious. But I'll make a try around week-end

**Comment by alexanderrichards** [comment]
hmmm I did the following in a new directory which I think looks simpler to my eyes :wink::

```bash
# create the virtualenv
virtualenv venv

# activate the virtual env
. venv/bin/activate

# install pytest
pip install pytest

# get the repo
git clone https://github.com/ganga-devs/ganga.git

# change to the source root
cd ganga/python

#run test
py.test Ganga/test/Unit/Notebook
```

Then subsequently after its already installed I can just do the following.

```bash
#go to the tmp dir
cd <the dir from before>

# activate the virtual env
. venv/bin/activate

# change to the source root
cd ganga/python

#run test
py.test Ganga/test/Unit/Notebook
```

**Comment by VanyaBelyaev** [comment]
@alexanderrichards  Hi Alexander, I agree,   it is a bit more clean.  I'll make a try soon.

**Comment by egede** [comment]
@alexanderrichards Yes, this might work but has a few worries. The `python` installation you use is *not* the one that LHCb is using. I am worried that this might break something with DIRAC where we have extension libraries. Also, you will not in the above install packages like the `mock` package which is what the `pip install --upgrade -r requirements.txt` pull in.

**Comment by alexanderrichards** [comment]
> The python installation you use is not the one that LHCb is using.

True but the unit test in question was a core one and as such shouldn't depend on LHCb python version.

> Also, you will not in the above install packages like the mock package which is what the pip install --upgrade -r requirements.txt pull in.

yes indeed, you will have to manually pip install the requirements for the testing. There is an argument that these (namely pytest and mock) should be in a separate requirements file as these are only necessary for the testing and not the main operation of Ganga.

**Comment by egede** [comment]
> yes indeed, you will have to manually pip install the requirements for the testing. There is an argument that these (namely pytest and mock) should be in a separate requirements file as these are only necessary for the testing and not the main operation of Ganga.

Isn't there an argument that when a package is installed, it should be able to run its own tests?  As an aside, is there a reason this file has the generic name `requirements.txt`? SHould it not have a name that reflects that it is for the testing, and maybe even be placed inside the `testlib` directory?

**Comment by mesmith75** [comment]
Can we close this now?
