### ISSUE TITLE
Shared Area persistency rebuild

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#985]
There was a recent catastrophic loss of shared area persistence for prepared jobs.

Is it worth writing a short script to correctly rebuild the dictionary of shared folders for all jobs in the repo?
(And offer to clean up after obviously lost shared dirs in the past?)

Any user who simply loaded the effected version of Ganga will cause all shared areas to become unaccounted and unlinked simply by loading and closing an effected version of Ganga as this destroyed the metadata dictionary on disk.
(This isn't the same as when we bled empty folders in the shared space but users will potentially lose a _lot_ of storage space due to the likes of `GaudiExec` jobs.)

This is probably best done in a script which is exposed to the GPI and the old `rebuild` methods for the `ShareRef` dropped imo as they feel overly complicated from having gone through them multiple times.
This will not be as painful as it was during 5.x and 6.0 as we now have correct lazy loading of subjobs and a few other optimizations that mean that loading an individual job from disk shouldn't take too long. (Obviously pending #917).

**Comment by mesmith75** [comment]
I think this has gone stale...
