### ISSUE TITLE
GaudiExec.extraArgs not working

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#987]
I expect to be able to do the following with GaudiExec:

```
job.application.extraArgs = ['arg1', 'arg2']
```

But this doesn't work and looks like an error in parsing the string.

(Running without gaudirun)

**Comment by mesmith75** [comment]
Are you referring to that it wants a list of lists?

**Comment by rob-c** [comment]
I think #991 fixes this, I don't want to start debugging this but the change looks safe imo. I think users are currently doing: `j.application.extraArgs.append('blah')` which is a bit ugly
