### ISSUE TITLE
Ganga submits impossible jobs

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#988]
The OfflineDiracSplitter should remove the SE associated with the banned sites from the possible sites to use in the splitter. Additionally the splitter should abort on submit when there are LFN with no valid replicas available, I'm not sure if there is a proper check for this or not.

This should stop users not knowing why jobs can't run because they've banned a site.
This saves the DIRAC servers wasting time trying to run a job that can't run.

(If this functionality is directly removed from the backend we can still can the extra args for the banned sites attribute)

**Comment by mesmith75** [comment]
Is the first part what we really want? Are the SEs only usable at the site?

**Comment by egede** [comment]
@mesmith75 In reality I think it is often the storage that has problems and not the CE. So banning the site is a way to ban the SE.
