### ISSUE TITLE
Jenkins security needs looking at

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#995]
OK, I've just had to install java8 on the ganga nodes @ CERN and reboot some things. (This whole thing was down with java errors in the logs...).

I've taken a backup of the existing install and have updated everything to clear some concerning security holes. I looked at 2 WN but if people want the rest up they will need to update java on them too.
The `PR Quality` test should be evaluated for it's usefulness it generates an unreasonable amount of small files (~1million!)

There are outstanding security warnings which need to be looked at (I think just sorting out the ssh certificate on the host is enough and it's hopefully not a serious problem).

I'm generating a backup of jenkins after the switch to JRE8, and it's looking like a cleanup might be needed at some point soon.

Rob

**Comment by mesmith75** [comment]
I think we can close this now we have moved the testing to Imperial.
