### ISSUE TITLE
Ganga error when accessing metadata from LHCb raw file

### ISSUE THREAD

**Issue by dhcroft** [ganga-devs/ganga#999]
When trying to get information about an LHCb RAW file (/lhcb/data/2015/RAW/FULL/LHCb/COLLISION15/163163_0000000082.raw) ganga has an error with a request submit a bug report. 

Steps to reproduce (x86_64-slc6-gcc49-opt from CVMFS if it matters):
lb-run ganga/v603r1 ganga
d = DiracFile(lfn="lfn:/lhcb/data/2015/RAW/FULL/LHCb/COLLISION15/163163_0000000082.raw")
d.getMetadata()

Full error log below:
$ echo $CMTCONFIG
x86_64-slc6-gcc49-opt

$ lb-run ganga/v603r1 ganga

WARNING:lb-run:trying old SetupProject (cannot find /cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v603r1/InstallArea/x86_64-slc6-gcc49-opt/manifest.xml)
ALWAYS:SetupProject:Configuring Ganga v603r1 from /cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v603r1

*** Welcome to Ganga ***
Version: 6.3.1
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.

INFO     reading config file /cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v603r1/install/ganga/python/GangaLHCb/LHCb.ini
INFO     reading config file /cvmfs/lhcb.cern.ch/lib/GangaConfig/config/6-3-0/GangaLHCb.ini
INFO     reading config file /user/hutchcroft/.gangarc
INFO     Using LHCbDirac version v8r4p4
 === Welcome to Ganga on CVMFS. In case of problems contact lhcb-distributed-analysis@cern.ch === 

[12:13:43]
Ganga In [1]: d = DiracFile(lfn="lfn:/lhcb/data/2015/RAW/FULL/LHCb/COLLISION15/163163_0000000082.raw")

[12:14:22]
Ganga In [2]: d.getMetadata()
ERROR    Error: 'lfn:/lhcb/data/2015/RAW/FULL/LHCb/COLLISION15/163163_0000000082.raw'
ERROR    !!Unknown/Unexpected ERROR!!
ERROR    If you're able to reproduce this please report this to the Ganga developers!
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v603r1/install/ganga/python/Ganga/GPI/__init__.py in <module>()
----> 1 d.getMetadata()

/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v603r1/install/ganga/python/Ganga/GPIDev/Base/Proxy.py in proxy_wrapped(*args, **kwargs)
    691         s_args = [stripProxy(a) for a in args]
    692         s_kwargs = dict((name, stripProxy(a)) for name, a in kwargs.items())
--> 693         r = f(*s_args, **s_kwargs)
    694         return addProxy(r)
    695 

/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v603r1/install/ganga/python/Ganga/GPIDev/Credentials/__init__.py in cred_wrapped_method(self, *args, **kwargs)
     42                 raise InvalidCredentialError('Proxy is invalid')
     43 
---> 44         return method(self, *args, **kwargs)
     45     return cred_wrapped_method
     46 

/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v603r1/install/ganga/python/GangaDirac/Lib/Files/DiracFile.py in getMetadata(self)
    328 
    329         if self.guid != ret.get('Successful',{}).get(self.lfn,{}).get('GUID',False):
--> 330             self.guid = ret['Successful'][self.lfn]['GUID']
    331 
    332         reps = self.getReplicas()

KeyError: 'lfn:/lhcb/data/2015/RAW/FULL/LHCb/COLLISION15/163163_0000000082.raw'

**Comment by mesmith75** [comment]
Thanks for reporting this; it looks like a bug. I'll get a fix in.

**Comment by dhcroft** [comment]
Yes, it was a mistake in the lfn definition (I forgot the run number directory), so d.getReplicas() works properly and returns no replicas but getMetadata() as you say does not check the file exists.
